### ISSUE TITLE
At overflow requests can not be displayed notifications and messages

### ISSUE THREAD

**Issue by websistema1** [PHPfox-Official/phpfox-v4-issues#1692]
Hello! Error notifications and messages repeated ( https://github.com/moxi9/phpfox/issues/1658 ) - users of my site constantly tell me about these mistakes. At first I thought that these errors are associated with third-party components - I was wrong. I installed a clean site to a folder 4.4.3 Developer (development) to test the error. Mistakes happen again - for example, if the user writes a message long texts of other users - then the user and the recipient of an empty box appears instead of the message. I think that the error stems from the fact that the website users are using the Russian and Ukrainian languages. Developers, please correct this mistake!
![2016-10-15_094310](https://cloud.githubusercontent.com/assets/14079310/19408145/eea3e3fa-92be-11e6-894b-149c7574064d.jpg)

To test the error can give the administrator access to the site. Sorry for bad english.

**Comment by Data66PF** [comment]
I tried on my site using Russian. I can't reproduce it. My site does not have the IM chat enabled. Is your site using IM chat?

**Comment by websistema1** [comment]
On my site is not included IM chat. Visit the demo site and make sure that there is an error:
site: http://vsitut.com/development/
e-mail: test@vsitut.com
password: tester
Try adding a large amount of text to the user in Russian (Ukrainian) language in the message (you can add other accounts to the test - by mail verification is disabled) - will be everywhere this error. The error was discovered already at version 4.4.2. Maybe because otsustvija on your website Russian and Ukrainian language packs you do not see this error. Sorry for bad english.

**Comment by Data66PF** [comment]
Please submit a ticket as the issue on the site is odd.

**Comment by websistema1** [comment]
Hello! The error will be corrected for version phpfox 4.5.0? Members of my site still can not use the messaging. Thanks in advance.

**Comment by Ylmzef** [comment]
I have same issue when i disable Mail App

**Comment by websistema1** [comment]
Dear developers! Please Fix for version 4.5.1 - this critical error for non-English users who actively exchange messages and emotions. Thanks in advance.

**Comment by neil96** [comment]
It's hard for us to reproduce. If you can give us some **messages** that make this error. We will check again.

**Comment by websistema1** [comment]
Error existents and version 4.5.0. Try to send a message to Russian or Ukrainian language with lots of offers - you'll get an error. It is necessary to make the restriction on entering characters for the message (for example, 250 characters) - and the error disappears. The same should be done for notifications.

**Comment by neil96** [comment]
@websistema1 I tried some ** Russian texts** (with google translate), but it works. I know this error happen with some special phrase only, but I don't know which phrases.

**Comment by websistema1** [comment]
Try, for example, add a message to all the text on this [www.psi.lib.ru/statyi/raznoe/sampvtpg.htm](url) - and you'll get an error. Phrases nothing to do with. The error occurs when you add a large amount of text in the message. Tell us, in any file you can limit the text message to be sent, for example up to 250-500 characters? On my website users because of this error, delete their accounts - they can not write messages. This is a critical error for non-English users. Please help. Sorry for bad english.
