### ISSUE TITLE
links to Liked Pages and Joined Groups doesn't work on the left block, personal profile.

### ISSUE THREAD

**Issue by clarkyu** [PHPfox-Official/phpfox-v4-issues#1725]
When click on those links, it shows Page Not Found.
![qq20161031-2](https://cloud.githubusercontent.com/assets/3412340/19840958/e51f010e-9f3c-11e6-9bcd-dff065597c06.png)

**Comment by neil96** [comment]
Please give us detail steps to reproduce. It works on my side.

**Comment by clarkyu** [comment]
Click on the page links under Liked pages or group links under Joined groups.
visit my site http://gzgz.org and login as g@gzgz.org and password is phpfox

**Comment by neil96** [comment]
We don't check site issue here.

I guest there is an app (or similar) that modifies default data structure.

**Comment by clarkyu** [comment]
nope.

**Comment by clarkyu** [comment]
I didn't install any other apps or modifications.

**Comment by Vivian-phpFox** [comment]
@clarkyu can you reproduce this issue on V4.5-RC?
