### ISSUE TITLE
Search in private messages does not work.

### ISSUE THREAD

**Issue by Criotin** [PHPfox-Official/phpfox-v4-issues#1735]
Search in private messages does not work.

![default](https://cloud.githubusercontent.com/assets/15389101/20114137/3442511e-a604-11e6-93d6-b8bc56e55678.png)

**Comment by neil96** [comment]
Where do you find this page?

**Comment by Criotin** [comment]
sitename.com/admincp/mail/private/?q=admincp/mail/private/&page=1

**Comment by phpfoxaccount** [comment]
@Criotin , the function is removed by default in V4 engine, no entry point, it is therefore not working properly. We do have plan to bring this back in Neutron 4.6, of course it will need improvement.

**Comment by Criotin** [comment]
Ok.

**Comment by chena321** [comment]
is this issue solved in any other ways?
