### ISSUE TITLE
Uploading a multiple image using responsive mobile view

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#1744]
Hi, could you please pay attention the improving of multiple photo upload using mobile view. After I select all photos I need to upload, just only 1 image successfully upload. Thank You

**Comment by neil96** [comment]
@juniortimeline 
Could you attach some screenshots?

**Comment by Vivian-phpFox** [comment]
I can upload multi photos via mobile. Kindly recheck on V4.5-RC
