### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#1751]
Some videos lose title.
Some videos don't have view count.

**Comment by neil96** [comment]
>Some videos lose title.

How to reproduce it?

>Some videos don't have view count.

Duplicate with #1745
P.S: Please post 1 issue/request.

**Comment by djafrika** [comment]
Cannot figure out when is this happening. It just does. I't doesn't seem to have a rule when it will happen. I'll try to figure out then I'll elaborate it here.
Same goes for issue #1745 and #1731

**Comment by neil96** [comment]
Hi @djafrika ,

I have tested this issue on latest verion (4.5.1b2), but I can't reproduce. Could you double check again.

Regards.
