### ISSUE TITLE
Befor You release v4.5!

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1752]
Hello.

Before you release a new version 4.5 I beg developers to pay attention to the following issues.

As can be seen from the figures, there are a number of problems in the design (for mobile devices), and with the transfer. Not all the possible phrases translated.

Fortunately, for the translation already made for AM & PM. But I must still resolve the problem of translation for the names of groups, as shown in the figure.

Thank you.

![1](https://cloud.githubusercontent.com/assets/11414490/20596564/77fb3ff0-b23f-11e6-87a3-344a9c65ea85.jpg)
![2](https://cloud.githubusercontent.com/assets/11414490/20596569/7dc88276-b23f-11e6-8e45-6190d51a1d9e.jpg)
![3](https://cloud.githubusercontent.com/assets/11414490/20596573/81ea799a-b23f-11e6-8c9f-0a413bfd0120.jpg)

**Comment by phpfoxaccount** [comment]
@CimborNet : thanks for your contribution.
Since policy allows one issue per post, so we can keep track easily, can you split this issue according to guideline - https://github.com/moxi9/phpfox ?

**Comment by neil96** [comment]
#1832
