### ISSUE TITLE
Full AJAX Mode Disables Ads V4.4.3(build 2)

### ISSUE THREAD

**Issue by Gatsby-PF** [PHPfox-Official/phpfox-v4-issues#1755]
When AJAX Mode is enabled in site settings, ads drop out of many screens.  To test, set full ajax enabled, then
1. create an ad
2. set it to display sitewide (no controller)
3. go into each and every nav menu screen to view the ad

Next, disable full AJAX and repeat steps 1 through 3 above.

Disabling full AJAX is not an option as it is apparently required for cron based notification.

**Comment by neil96** [comment]
@Gatsby-PF How to set to display sitewide? Are you saying our default ad?

**Comment by Gatsby-PF** [comment]
This is the default ad.  Sorry, forget step 2 above as that was for images in blocks (which also disappear), but for this test it concerns the default ads (do not have a sitewide block control).

**Comment by Vivian-phpFox** [comment]
@Gatsby-PF, I can not reproduce this issue. Kindly recheck this issue on V4.5-RC
