### ISSUE TITLE
Single Signin Problem 4.5 RC

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1756]
when we sign in with different browsers at same time then our one account logout. that fine but when we logout from both browser than login again in single then problem comes. that it automatically logout after some time pop up appears again and again.. one another problem when we click on home its take u to welcome landing page but menu option is still visible to us.
![sing out problem](https://cloud.githubusercontent.com/assets/13433124/20638776/9ec18ab6-b3d6-11e6-8211-a2454612b555.png)
![single sign in problem](https://cloud.githubusercontent.com/assets/13433124/20638777/9edd6bbe-b3d6-11e6-93f8-6427bd977437.png)

**Comment by neil96** [comment]
The ajax mode only reload the main contain, header and footer are not reload. 
It will be improved on next version. Thanks for report!

**Comment by SalmanKhan86** [comment]
but about the error message that still comes even when i logout into another session. 
now currently i am login into only single session but still that pop up appears.
