### ISSUE TITLE
The default avatar is not displayed.

### ISSUE THREAD

**Issue by Criotin** [PHPfox-Official/phpfox-v4-issues#1762]
The default avatar is not displayed. phpfox-4.5.0-RC

![default avatar](https://cloud.githubusercontent.com/assets/15389101/20904941/cf5e0d9c-bb52-11e6-98f6-da4932d63dbe.png)

**Comment by neil96** [comment]
Does it happen with all your users or with this user only?

**Comment by Criotin** [comment]
This is happening with users having the name in Cyrillic.

**Comment by neil96** [comment]
Could you give us some example names?

**Comment by Criotin** [comment]
Ок. 
1) Арнольд Шваргенеггер
2) Давид Вилья

**Comment by neil96** [comment]
I can't reproduce with the names that you gave. Can you reproduce on our demo?

**Comment by Criotin** [comment]
I made a mistake. This happens only with this user.

![default avatar 2](https://cloud.githubusercontent.com/assets/15389101/20910402/44288e58-bb72-11e6-8ef6-95f61bf406bb.png)

**Comment by Criotin** [comment]
![default avatar 3](https://cloud.githubusercontent.com/assets/15389101/20910565/55eee7d0-bb73-11e6-9d8e-87ec83ed6938.png)

**Comment by Criotin** [comment]
The image appeared.

![default avatar 4](https://cloud.githubusercontent.com/assets/15389101/20947908/585e538e-bc22-11e6-99b3-016cda3ce055.png)

**Comment by Criotin** [comment]
After updating of a copy of my main site, the default avatars stopped appearing for some users.

![default avatar 5](https://cloud.githubusercontent.com/assets/15389101/21014232/44f0f200-bd6e-11e6-9be1-f8d462191572.png)

![default avatar 6](https://cloud.githubusercontent.com/assets/15389101/21014240/4d1c13a6-bd6e-11e6-8390-6a67a6ade04e.png)

**Comment by neil96** [comment]
I can't reproduce this issue on our side. Could you [submit](https://clients.phpfox.com/submitticket.php) a ticket with your site information. So we can detect this is our bug or your site issue. Remembering link to this issue on your ticket.

**Comment by Criotin** [comment]
After the server restarts, avatars appeared.
