### ISSUE TITLE
Bundle JavaScript & CSS - still causes marketplace pictures looks weird 

### ISSUE THREAD

**Issue by maniacscorpio** [PHPfox-Official/phpfox-v4-issues#1766]
Bundle JavaScript & CSS - still causes marketplace pictures looks weird 

if i disabled Bundle JavaScript & CSS than it looks ok ..

I am talking about market place item pictures scrolling window (slide show )

just upgraded to 4.5 stable version .. same issue again

**Comment by neil96** [comment]
I can't reproduce. Do you have 3rd app(s) on your site?

**Comment by maniacscorpio** [comment]
No i don't have any 3rd party module and theme .. i am on stock phpfox..  but still facing this bug ...

**Comment by neil96** [comment]
I can't reproduce this issue on any sites that I have. Could you double check other configurations on your site.

**Comment by matthewpomar** [comment]
I too face numerous issues with bundler. It brings down my entire site as it causes JS errors.
