### ISSUE TITLE
The placement is not created.

### ISSUE THREAD

**Issue by Criotin** [PHPfox-Official/phpfox-v4-issues#1767]
The placement is not created.

Video:
https://v4.phpfox.com/v/play/1687/

**Comment by neil96** [comment]
I can't reproduce. Do you use redis cache?

**Comment by Criotin** [comment]
Not using.

**Comment by neil96** [comment]
I can be a cache issue. Please clear your cache try again. If it does not help, feel free to send us a ticket with your site information, then we will check for you.
