### ISSUE TITLE
Appeared doubles on all pages

### ISSUE THREAD

**Issue by Criotin** [PHPfox-Official/phpfox-v4-issues#1770]
After upgrading to version 4.5.0 appeared endless duplicates on all pages (groups).

![default](https://cloud.githubusercontent.com/assets/15389101/21071659/9cf2fc6e-beb8-11e6-88f5-9361a2edbeb5.png)

**Comment by Criotin** [comment]
It sees only the administrator. Ordinary users duplicates are not displayed.

**Comment by neil96** [comment]
@Criotin I tested with administrator user too, but I can't reproduce. Can you reproduce on our demo?

**Comment by Criotin** [comment]
How can I reproduce it on your demo site?
This anomaly occurs with only one administrator account.

**Comment by neil96** [comment]
Do you still get this issue? If yes, feel free to send us a ticket with your site information, then we check for you.
