### ISSUE TITLE
Not displaying application icons

### ISSUE THREAD

**Issue by Criotin** [PHPfox-Official/phpfox-v4-issues#1772]
Not displaying application icons in the Cyrillic alphabet.

![default](https://cloud.githubusercontent.com/assets/15389101/21072023/487d3ff2-bec5-11e6-9cc6-c7c99d21a5b2.png)

**Comment by neil96** [comment]
Are these default apps?

**Comment by Criotin** [comment]
Yes, it's default application.

**Comment by neil96** [comment]
I can't reproduce, do you use phpFox 4.5.0 final?

**Comment by Criotin** [comment]
Yes, I use phpFox 4.5.0 final.
Yes, the icons blend with the background.

![2](https://cloud.githubusercontent.com/assets/15389101/21087550/ed6ee060-c037-11e6-9cca-f3b4d582ff50.png)

**Comment by neil96** [comment]
If you still get this issue, feel free to send us a ticket with your site information. We will check for you. Don't forget link to this issue on your ticket.
