### ISSUE TITLE
When Pages Video Title is changed, it is not reflected in main video page.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1776]
When Video Title is changed, it is not reflected in main video page.

**Comment by neil96** [comment]
I can't reproduce. Could you give me detail steps!

**Comment by prepperz** [comment]
Just change the title and then go look on the main video page that list all the videos

**Comment by neil96** [comment]
Actually, the videos of pages shouldn't display in main video page.

**Comment by prepperz** [comment]
I think it should, unless it's private or a closed group. This way when people see the video it leads them back to the page. Helps people to discover stuff.
