### ISSUE TITLE
Theme issue

### ISSUE THREAD

**Issue by one44123** [PHPfox-Official/phpfox-v4-issues#1780]
I had an issue with my bootstrap theme and was advised such.  The theme issues were caused by a bug in the setting to bundle css and js. Please feel free to submit the bug to phpFox Github. We have disabled the setting. Vers 5.4 build 1

**Comment by neil96** [comment]
Could you attach the community link here. Thanks!

**Comment by one44123** [comment]
which community link

**Comment by neil96** [comment]
I do not totally understand your issue. I thought you had reported on community.
Could you give us more detail about this issue.

**Comment by one44123** [comment]
Hi

 

This is a site wide blocks issue causing issues with themes and third part plug ins.

 

ED

**Comment by neil96** [comment]
Could you give us some screenshots! Thanks!

**Comment by one44123** [comment]
This was a general error that caused bought themes not to work out the box and the phrasesot to show under phrases. the 3rd party theme developer http://www.templatemechanic.com has done a work around until the issues are resolved.

**Comment by neil96** [comment]
Hi @one44123 

Could you test again on latest build (4.5.1b2). I though it's the same with #1864 

Regards.
