### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1784]
after upgrading my site to 4.5 sometimes i have internal server errors. never had these before the upgrade. have to check the logfiles later to hopefully find out what is going on... any ideas?

**Comment by Criotin** [comment]
I confirm. I have the same problem.

**Comment by Ylmzef** [comment]
https://community.phpfox.com/forum/thread/55719/javascript-error-after-upgrade-to-4-5-0/

**Comment by neil96** [comment]
Which page did you get this error?
Btw, could you give us some screenshots.

**Comment by lordofnos** [comment]
i get this randomly. can not reproduce it but my users did also get those error.  its the standard 500 Internal Server Error page. i have checked with my hosting company and they have not found any issues on server side. they say it has to be a problem of the script. i have deleted all files but uploaded files from users in the file folder and then uploaded all phpfox files again to make sure there are no old files left. the site works normal but i get the error again sometimes.

**Comment by neil96** [comment]
Did you disable any default apps?

**Comment by lordofnos** [comment]
do you mean phpfox apps or the modules that are listed in the apps manager?

**Comment by neil96** [comment]
It's module that's listed in the app manager.

**Comment by lordofnos** [comment]
i have disabled these modules: ad, egift & music

**Comment by prepperz** [comment]
You're probably having issues on pages and groups. 

Are you using fcgid or cgi wrapper? Try switching it and make the php run time unlimited and see if that help.

**Comment by neil96** [comment]
@lordofnos I can't reproduce after disable ad, egift & music.

If you can give us detail page or error log, so we can check this issue easier (you can check log in /var/log).
