### ISSUE TITLE
notification popups

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1785]
after upgrading to v4.5 the notification popups are very slow. some users have written that it does not show up at all. slow popup is also an issue on the phpfox demo.

**Comment by neil96** [comment]
It might be your network issue. It's working normal on our side.

**Comment by lordofnos** [comment]
i have tested this with different networks and mobile devices... its much slower than with v4.4.3. i have both script running and can clearly see the difference on all of the devices and desktops.

**Comment by neil96** [comment]
We have some performance improves on 4.5.1. Feel free to open a new issue if you still get this issue.
