### ISSUE TITLE
language issue

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1786]
i had the issue that after reloading the page language shows up in forrmat full_name_has_just_replied_to_the_thread_title it was a sidewide problem with main menu included. the only way to get the phrases back was to switch default to englisch and then back again. i can not reproduce this but there is an issue...

**Comment by Criotin** [comment]
I confirm. I have the same problem.

**Comment by Criotin** [comment]
I went back to a previous version. In version 4.5.0 too many problems.

**Comment by lordofnos** [comment]
i am thinking about switching back but i have one day of users doing crazy stuff on my site that i want save

**Comment by lordofnos** [comment]
this issue completely stops your site working and i can not watch the site 24/7 to clear cache when the issue happens. we need a very fast fix for this.

**Comment by neil96** [comment]
There is a similar issue on our community: https://community.phpfox.com/forum/thread/55740/language-error/

We can't reproduce this issue. This might be a site issue  or in-compatible app issue.

**Comment by lordofnos** [comment]
maybe this all comes down to this? https://community.phpfox.com/forum/thread/55738/disable-cache-completely/

**Comment by Criotin** [comment]
![phpfox 4 5 0](https://cloud.githubusercontent.com/assets/15389101/21167915/0adabf40-c1c1-11e6-9e2f-e01ee04190fa.png)

![phpfox 4 5 0 2](https://cloud.githubusercontent.com/assets/15389101/21167920/0ff8452e-c1c1-11e6-833f-c64040a4c0d2.png)

**Comment by websistema1** [comment]
I have the same problem. Plus still does not work cache - helping update the cache folder on the server. Generally a lot of critical errors - I wait for fixes. I moved back to version 4.4.

**Comment by lordofnos** [comment]
i moved back too...

**Comment by Promastertr** [comment]
this issue completely stops your site working and i can not watch the site 24/7 to clear cache when the issue happens. we need a very fast fix for this.I lost so many members. Urgent regulation required

**Comment by neil96** [comment]
Could you upgrade to phpFox 4.5.0b2 that was released yesterday.
If you still get this error, could you send us a ticket with your site information, so I can detect this issue easier.
Thanks!
