### ISSUE TITLE
cron error

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1787]
cron is setup and working for 4.4.3 but after upgrading to 4.5 i have an error. it come not with every cron but i had it two times in 10 hours now: /bin/sh: line 1: 23152 Bus error... what can cause this error?

**Comment by neil96** [comment]
Could you put your error logs or errors here?

**Comment by lordofnos** [comment]
/bin/sh: line 1: 17267 Bus error               /usr/local/bin/softlimit -m 300000000 -o 200 -p 80 -t 180 /usr/local/pd-admin2/bin/php5-5.6 -f /home/mysite/www.mysite.com/cron.php > /dev/null 2>&1

**Comment by neil96** [comment]
It's your cron job command line, not error log.
