### ISSUE TITLE
photos in blog

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1789]
when using the ckeditor app to insert images in blogs the image does not show when browsing blogs.

**Comment by neil96** [comment]
Did you enable "Allow HTML" setting?

**Comment by lordofnos** [comment]
yup, the setting is enabled. but the app shows a message that i have to enable it ;) when showing the blog the image works fine. only on browsing blogs it does not work.

**Comment by neil96** [comment]
Is this your blog? It's working.

<img width="657" alt="screen shot 2016-12-14 at 09 32 25" src="https://cloud.githubusercontent.com/assets/15936115/21167624/4b62c5b6-c1e0-11e6-85a2-6f077de458f4.png">

**Comment by lordofnos** [comment]
as you can notice ckeditor is not enabled on your demo.

**Comment by lordofnos** [comment]
i have double checked this. when disabling ckeditor and upload like normal the image shows when browsing blogs. ckeditor enabled and uploaded the app changes the tags and the image does not show on the blog index.
