### ISSUE TITLE
If user gets themselves Banned by the system, user still visible on feed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1793]
If user gets themselves Banned by the system, users still visible on feed, clicking on banned user results in page not found.

**Comment by neil96** [comment]
All contents from banned users can view normal, even their profile.

>clicking on banned user results in page not found.
=> I can't reproduce

**Comment by prepperz** [comment]
No, you can't ban them yourself. If you do that that it works like normal. The user has to get themselves banned by the system. It's a strange issue.

**Comment by neil96** [comment]
Hi @prepperz 
>The user has to get themselves banned by the system

"Automatic ban by the system" is temporary disable in core. How do you enable it?
