### ISSUE TITLE
Status --> inactive users doesn't keep track which emails have already been sent.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1797]
If the process get stuck and the admin restarts it, it will keep sending emails to the same users. This can get a server ip black listed..

**Comment by neil96** [comment]
>emails have already been sent

Could you explain for us more detail about this.

**Comment by prepperz** [comment]
For example, say you want to send email reminder for inactive users for the last 30 days, in batches of 5.

Now say you that there is a total of 2000 to be sent, but it's only on 500 and then it get's stuck. If you restart the process it will send email to the same exact people again instead of continuing where it left off.

**Comment by neil96** [comment]
Hi @prepperz ,

This is an enhancement, please request us [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.

**Comment by prepperz** [comment]
OK just added a request here: https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/330

**Comment by neil96** [comment]
Thanks for your report! We will consider add feature to next versions.
