### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#1800]
After trying to backup the site, it locks down and admin cannot login. Backup doesn't get created at all...

**Comment by neil96** [comment]
We have the warning on configuration page:
> The site will put to maintenance mode during backup time.

Please double check the backup process is done or not.

**Comment by djafrika** [comment]
It's logical to lock the site during a backup. I don't have to read anything to know that. The point is that it logged me off. After I clicked on backup button, it started the "backup". And after it was "done", I clicked on manage button and it logged me off. It didn't downloaded any zip file nor does any file exist in manage backup page.

**Comment by prepperz** [comment]
This backup system doesn't take server configurations into consideration. The best option is to use a server level backup solution, but not everyone will have access to such. So the phpfox backups are fairly limited.

**Comment by neil96** [comment]
@djafrika ,
We have a manage page that allows you download a ___backup package___.

**Comment by djafrika** [comment]
I know. There isn't any backup to download. That's why I wrote that it didn't do the backup right...

**Comment by neil96** [comment]
It can be a site issue, please open a [ticket](https://clients.phpfox.com/submitticket.php) with your site information then we can check your issue. Don't forget link think issue to ticket. Thanks.
