### ISSUE TITLE
group url issue

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1801]
when a group url is set and there are pending users the pending link does not redirect to the pending page. it shows the users under the group feed. you have to scroll down the complete feed to approve. deleting the url does not delete the database entry so it also does not work. tested on dev and phpfox demo.

![groupissue](https://cloud.githubusercontent.com/assets/13225682/21290042/fd80a5b4-c4ac-11e6-96ea-7d5c89608429.png)

**Comment by lordofnos** [comment]
this is also an issue on 4.4.3 b2
