### ISSUE TITLE
Category language issue

### ISSUE THREAD

**Issue by robert9592** [PHPfox-Official/phpfox-v4-issues#1807]
I've updated today to 4.5.0 build 2 and now all of my custom categories have names like
forum.forum_category_73c1fc4f2e0c255ae212a39abc1f4947
photo.photo_category_73c1fc4f2e0c255ae212a39abc1f4947
on everything... blog, forum, poll, marketplace etc...

From @AFRIKA on [community](https://community.phpfox.com/forum/thread/55759/upgrade-problem/)

**Comment by djafrika** [comment]
This is similar problem that you marked as fixed. But it isn't... #1706

**Comment by neil96** [comment]
@djafrika 
No, it's very different with old one.

**Comment by djafrika** [comment]
but the problem exist on new version...

**Comment by neil96** [comment]
If anyone who get this issue, please submit us a [ticket](https://clients.phpfox.com/submitticket.php), we will apply a fix batch for you or wait 4.5.1 release.
