### ISSUE TITLE
Photos issue

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#1816]
Latest phpfox, Chrome
If we visit the photos section   http://www.example.com/index.php/photo/  All the photos are displayed in  Grid layout. But If we do a page refresh then  the layout changes and we see big size photos.

**Comment by neil96** [comment]
I can't reproduce this issue. Please double check on your site. It might be other error(s) effect to this page.

**Comment by aakash83** [comment]
check it yourself   here  http://www.virtualians.com/
Go to photos and do a page refresh.  OR    Directly Open this URL http://www.virtualians.com/index.php/photo/  
The problem occurs only if we access the photos section through direct URL. (Either a page refresh or typing direct URL ).
If you are coming from other sections  ( forum, groups, etc. ) the the first time the view is normal but it changes on page refresh OR even if you click on photos in top menu while you are already browsing photos module.

**Comment by neil96** [comment]
I can reproduce on your site, but not on my site and our demo, it can be a site issue or a specific case.
Do you disable any default module?

**Comment by aakash83** [comment]
Yes I have disabled some of default modules .(ads , blogs ,egift, invite, marketplace, Music, newsletter,polls,quizes).   On your community if you notice when we open photos  https://community.phpfox.com/photo/   first time it loads full photos for a very short time( less than second) . then it display them as grid.

**Comment by neil96** [comment]
Hi @aakash83 ,

I tested with these modules are disabled. But I can't reproduce. Could you upgrade to latest version (4.5.1b2) and test again.

Reagards.
