### ISSUE TITLE
Unable to Delete blocks

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#1818]
Latest PHPFox, Chrome

If we create new blocks other than default ones. We cannot delete the newly created blocks.  We can disable them but  If we try to delete a disabled block,   PHPfox shows a notification that the block has been removed successfully. But  The block remains there, and  All disabled blocks become enabled again. 

Recently I was trying to add a block to show a user's groups on Index page (logged in) just below Friends Online Block.  I mistakenly added three  blocks to  user >> profile >> index.  But now cannot delete them.
![image](https://cloud.githubusercontent.com/assets/406030/21425445/6e4fab10-c849-11e6-9e1c-3feb5148c631.png)

**Comment by aakash83** [comment]
Also I need help to create a block on user >>. index (logged in)  page . just under friends online block  to display user's joined groups . Thanks

**Comment by neil96** [comment]
This is a cache issue. For now, please clear your cache after delete a block.

**Comment by aakash83** [comment]
Even after clearing cache, it remains the same.
