### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by one44123** [PHPfox-Official/phpfox-v4-issues#1820]
Group image no longer shows on cover image of group  as it does on pages still.

**Comment by neil96** [comment]
Could you tell us more detail.

**Comment by aakash83** [comment]
He is talking about this thing as shown below(we dont have Group Image.) . But I thought the change was made by phpfox to not dsiplay group photo.
![image](https://cloud.githubusercontent.com/assets/406030/21449615/61d51aea-c8ef-11e6-9c15-4923cc7928ca.png)

**Comment by neil96** [comment]
@aakash83 It's default photo, we can add it on manage theme. By default, it's empty.

**Comment by aakash83** [comment]
No. Ususally we have two photos one cover image and one Avatar . One44 is talking about avatar. As we have on Member Profiles ,and Pages

**Comment by one44123** [comment]
Yes Avatar image is missing it appears when groups tab/topmenu selected but does not show on actual group.groupname page of that group.

**Comment by neil96** [comment]
That's how we designed. The facebook group doesn't have avatar image too.
