### ISSUE TITLE
block site wide issue messup

### ISSUE THREAD

**Issue by Viewsfx** [PHPfox-Official/phpfox-v4-issues#1821]
site wide issue messup each n everry auto added to site wide block and not be deleted
check in attach image
![site wide 1](https://cloud.githubusercontent.com/assets/13310845/21457581/6fb1a3c4-c956-11e6-8973-7a4593d8f9de.png)
![site wide 2](https://cloud.githubusercontent.com/assets/13310845/21457582/6fb3b2ea-c956-11e6-82a8-fd624bb1c394.png)

**Comment by neil96** [comment]
Duplicate with #1794
