### ISSUE TITLE
choose username on registratration setting missing

### ISSUE THREAD

**Issue by Viewsfx** [PHPfox-Official/phpfox-v4-issues#1822]
in PF 4.5 in the registration prosess user can`t choose username because of choosing username on registration prosess setting removed

**Comment by neil96** [comment]
Please [request us this](https://github.com/PHPfox-Official/phpfox-v4-feature-requests) feature if you'd like it. It's not a bug.

**Comment by robert9592** [comment]
@Viewsfx 
We already supported this setting on 4.5.0. You can find it in Admincp -> Settings -> Registration -> Display Full Name (Display Name) and Username on Sign Up
