### ISSUE TITLE
Poll automatically adds a "?" mark at the end.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1823]
Whether there needs to be a question mark or not, should be determined by the poll creator.  Otherwise, it won't look right.

**Comment by neil96** [comment]
Here's for bug tracer only. If you'd like ask a question, please ask [here](https://community.phpfox.com/). If you'd like request a feature, please request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests).
