### ISSUE TITLE
issue facebook login

### ISSUE THREAD

**Issue by wetricks** [PHPfox-Official/phpfox-v4-issues#1827]
hello, 
on my phpfox site , when i'm logged out and i have facebook open and logged on an another window of my browser , my phpfox site try to connect and i have the error attached.
FYI : i have a normal account on my phpfox site.

thanks 

best regards

sylvain
![facebook issue](https://cloud.githubusercontent.com/assets/15895902/21522569/fe061de0-cd06-11e6-9313-d0a802fb6506.JPG)

**Comment by neil96** [comment]
Please double check your facebook app permission. It might be lack of permission.

**Comment by wetricks** [comment]
Hi neil, 
thanks for the reply.
could you just help us about the configuration of the permission of the Facebook app ?
thanks
best regards

sylvain

**Comment by wetricks** [comment]
Hello ,
It is the same issue which were fixed on the 3.9 version of phpfox.
https://blog.phpfox.com/2016/03/03/phpfox-3-9-0-released-2/
Thanks for the support

**Comment by neil96** [comment]
Hi @wetricks 

Sorry for late reply. For support, you can post a new thread on our [community](https://community.phpfox.com/forum/) or submit a ticket [here](https://clients.phpfox.com/submitticket.php).

Regards.
