### ISSUE TITLE
unable to delete custom blocks..the same problem wih custom fields group

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-issues#1828]
created blocks to bring advanced filter in separate block from http://mysite.com/admincp/block/  ..but they were showing code on the frontend ..so i clicked on delete...they have gone from the frontend ..
but still there on the backend.cliking on delete shows successfully deleted ..but they are still there...

**Comment by aakash83** [comment]
Clear cache .

**Comment by neil96** [comment]
#1818
