### ISSUE TITLE
Categories Lang Translate - Urgent need to fix it BUG!

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1831]
**URGENT PLEASE fix this problem, because the search engines are scanning the site is not properly see the links and text translation for the categories. They form is not the correct content and broken links !!!!**

After I upgrade from 4.5.0 to 4.5.0.b2 no longer displayed correctly translate the text for categories. This error remained in the new version 4.5.0.b3

![category_lang_bag-2](https://cloud.githubusercontent.com/assets/11414490/21565352/fafa6b42-ce96-11e6-9cfe-63585b9333b4.jpg)

As can be seen from the figures, in the base of all translations are stored data. But on the screen, we see only the names of variables, not their value.

![category_lang_bag-1](https://cloud.githubusercontent.com/assets/11414490/21565345/ea674aac-ce96-11e6-8934-f49263843846.jpg)

Once the error search revealed that the problem applies only to categories of phrases that have been translated.

Those categories, which are not translated into other languages are still intact in the database and displayed correctly.

But those categories that are translated are displayed incorrectly. The values of the variables for such phrases are not taken from the table phpfox_language_phrase !!!

![category_lang_bag-3](https://cloud.githubusercontent.com/assets/11414490/21565425/ea71849e-ce97-11e6-8713-2db2380dac9f.jpg)

![category_lang_bag-4](https://cloud.githubusercontent.com/assets/11414490/21565505/35f0dda6-ce99-11e6-88b8-4078bf6272f8.jpg)

**Comment by neil96** [comment]
Duplicate with #1807
