### ISSUE TITLE
Translation of phrases in the title groups

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1832]
Hello,
I would like to be able to translate the names of the groups, like may edit and translate "country".
As you can see from the picture, it is not an option.

![2](https://cloud.githubusercontent.com/assets/11414490/21566305/27df4e2e-cea2-11e6-8d44-d8a33a959671.jpg)

![9](https://cloud.githubusercontent.com/assets/11414490/21566344/7c8074ee-cea2-11e6-9b57-b00a5350cc18.jpg)

**Comment by neil96** [comment]
I moved to request: PHPfox-Official/phpfox-v4-feature-requests#314
