### ISSUE TITLE
Search users with incomplete names

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1833]
Good day

v: PHPFox 4.5.0.b3

There is a strange behavior when users search in the admin CP panel by their names.

If search user by his full name, the system finds it.
But, if search user for not complete his name, the system displays an empty result.

Example:
admi**n** (enter) = OK
admi (enter) = NO result

obam**a** (enter) = OK
obam (enter) = NO result

joh**rdan** (enter) = OK
joh (enter) = NO result

The result can also be seen in the figure below
![1](https://cloud.githubusercontent.com/assets/11414490/21577034/eef93494-cf4b-11e6-8252-abf10f502eb7.jpg)

**Comment by neil96** [comment]
I can't reproduce.
<img width="1214" alt="screen shot 2017-01-01 at 11 33 52" src="https://cloud.githubusercontent.com/assets/15936115/21580218/284de03e-d017-11e6-882b-d27366d1982c.png">

**Comment by CimborNet** [comment]
Hi

Because display name = email name.

Try to change You display name "Neil" to "OtherName", and search Your account for an incomplete email like "phpfox.co" or "nei" or "eil"

**Comment by neil96** [comment]
Hi @CimborNet ,

Please test again on latest version (4.5.1b2), it seems this issue is fixed.

Regards.
