### ISSUE TITLE
Translation for the region

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1834]
Hi,

After the recent renovation updates appeared a lot of errors with the translation.

Now I have ver: PHPFox 4.5.0.b3

In the system (AdminCP), all regions is translated. In the database they are correct stored data. But on the site, they phrases view only in the original English! Why?

The cache is cleared.
Before the update 4.5.0.b2 was installed correctly displayed for all.

![10](https://cloud.githubusercontent.com/assets/11414490/21578021/39bcd376-cf71-11e6-9fa1-abefa0b31cfc.jpg)

![11](https://cloud.githubusercontent.com/assets/11414490/21578023/3d45e2a8-cf71-11e6-8f8c-42d668f67bfc.jpg)

![12](https://cloud.githubusercontent.com/assets/11414490/21578029/75311bd8-cf71-11e6-9ad5-bfc14bcf29d0.jpg)

**Comment by neil96** [comment]
It's working on my side. Could you double check your configurations.

**Comment by CimborNet** [comment]
All this works fine before the upgrade 4.5.0 or 4.5.0.b2
Similarly, I can not say right now, already.
Now 4.5.0.b3
Since an update did not change in the settings.

**Comment by neil96** [comment]
Could you give us more information? We can't reproduce with your information that you gave.
