### ISSUE TITLE
Guest unable to view events

### ISSUE THREAD

**Issue by raviji** [PHPfox-Official/phpfox-v4-issues#1836]
Guest unable to view created events by registered user. Actually Guest want to see the Events without login... anyone help me out

**Comment by neil96** [comment]
Guest can view public events. Are these events public?

**Comment by raviji** [comment]
Yes it is, while creating given option are:

Event Privacy: Everyone
Share Privacy: Everyone

but still Guest unable to view any events in version 4.5

**Comment by neil96** [comment]
Do you turn off setting `friend only community`?

**Comment by raviji** [comment]
I didnt do. I just installed yesterday and checked new version of v4.5. Can you tell me where this setting is there to check once?

**Comment by neil96** [comment]
[Here](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/1837#issuecomment-270595840) you are.
