### ISSUE TITLE
Unable to view Event on the event page

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#1837]
All events not posted on the main event page but available to view on the news feed.

**Comment by jhayden2000** [comment]
i am also having this issue

**Comment by neil96** [comment]
To make an event display on event page, it must be:
- Event start time >= current time
- Event end time <= current time

Please double check on your site.

**Comment by raviji** [comment]
Current time means what? Please check the screenshot of attachment here for your reference my site not getting display events.


![asdfasdfasdfsadf social networking community](https://cloud.githubusercontent.com/assets/12031387/21649978/84b60798-d2c9-11e6-87b2-7a096cfe05b6.png)
![events social networking community](https://cloud.githubusercontent.com/assets/12031387/21649979/84e7a398-d2c9-11e6-961e-8a6b9e476940.png)

**Comment by jhayden2000** [comment]
it seems that the "ongoing" option is the culprit in the "when" category. when i change it to upcoming, i see the events.. wouldn't ongoing mean an event that is already in the middle of happening? Ongoing is the default option.

**Comment by raviji** [comment]
I have tried changing 'When:' as "Upcoming" and "All Time" but still not working. Check the screenshots.

![events social networking community 1](https://cloud.githubusercontent.com/assets/12031387/21669755/5e5b17ee-d334-11e6-8fe9-5f0d34ac5847.png)
![events social networking community](https://cloud.githubusercontent.com/assets/12031387/21669756/5e5c8976-d334-11e6-9344-9e1d49efe646.png)

**Comment by Vivian-phpFox** [comment]
Kindly check site setting from ACP:
> Go to ACP --> Settings --> Site Settings--> Find the setting "Friends Only Community". 
=> If it set "Yes", only show items from the member and his or her friends list so that non login users can not find any items.

**Comment by raviji** [comment]
Yes its working, you saved my day. But now i want to change 'When:' as 'Upcoming' is by default, how to set?

**Comment by jhayden2000** [comment]
@neil96 , i think the big issue here is that for some reason the default setting for the "when" category is set to ongoing when it used to be upcoming.

**Comment by neil96** [comment]
It is working as our designed. If you still confuse about this feature, you can ask us on our [community](https://community.phpfox.com/forum/).

**Comment by raviji** [comment]
Hi Neil, 

Its not working as expected for guest users. Facing big problem here, events are not appearing after few mins for guest users. Please have look asap. also you can check the screenshot here...

![2](https://cloud.githubusercontent.com/assets/12031387/21885351/38a94ef4-d8dd-11e6-95e9-5f1532b7f0d6.png)
![1](https://cloud.githubusercontent.com/assets/12031387/21885352/38aa02b8-d8dd-11e6-9944-6559dcf3694b.png)

**Comment by neil96** [comment]
Hi @raviji ,

I can't reproduce the issue above, it can be a site issue.

Regards.

**Comment by raviji** [comment]
Hi @neil96 ,

Could you check my website gootoplay.com for live reference.

1. Registered user created a Event with Everyone permission.
2. Events are showing for 5-10 min and then disappearing.
3. For registered user can see always, but guest users can not be showing...

site issue means what should i do? I just installed v4.5 version and created event thats all i did.

**Comment by neil96** [comment]
Hi @raviji ,

One hour ago, I visit this this page: http://gootoplay.com/index.php/event/, I see two events. Now, I visit it again, I see two the same events too. The event doesn't disappear.

Regards.

**Comment by juniortimeline** [comment]
Hi @raviji 

I'm jealous because you will see your event on your event page 5-10 minutes. I create more events on my site but I never see any event on my Event page and my users can see event only on my site feed.

I believe that this event module have issue. I have development page 4.4 and event is working fine and when I try to update to 4.5 the all events disappear on my events main page.
