### ISSUE TITLE
video comments groups

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1839]
when a video is postet in a group and is commented by groupmembers via main feed the comments do not show in the group entry only on main feed.

also the following issue happens when trying to comment the video via group feed https://github.com/PHPfox-Official/phpfox-v4-issues/issues/1731

maybe this goes togehter somehow...

tested on 4.4.3

**Comment by neil96** [comment]
Please test on 4.5.0b3.

**Comment by Scheinwelt-Media** [comment]
i can not reproduce it on the demo
