### ISSUE TITLE
4.5.0 b3 doesnt send emails

### ISSUE THREAD

**Issue by liviufox** [PHPfox-Official/phpfox-v4-issues#1841]
fresh install of 4.5.0 b3 
doesn't send test emails nor any emails on registration

**Comment by neil96** [comment]
Did you setup smtp? Most emails are sent from default php server are blocked by the filter mail.

**Comment by liviufox** [comment]
it worked just fine till 4.5.0 b2 for me with the default mail option

**Comment by neil96** [comment]
Please try sending test email to public mailbox like [mailinator](https://www.mailinator.com/). They don't filter mail.
