### ISSUE TITLE
Search "whole words only" in AdminCP

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1842]
I ask you to add a new option in the search functionality in the AdminCP that allows administrators to search phrases only for a whole word .

What I mean...

Show me ONLY one phrase with exact match word!

For example:
when I'm looking for a short word "and", "in", "at", "info" or simple word "user" in the phrases that I want translate, then the system displays me FULL LIST of phrases, where these words are found in the text.

But I only want to find a specific word as a whole, and not all of the phrases in which these words occur at least once.

I search ------------ System result:
user ---------------- username, user, user_name, ...
at ------------------ at, at time, at....
and ---------------- ...and..., ... and..., and
info ---------------- ....info, ... info, info_..., ..._info
etc.

Example, see figure below.

![17](https://cloud.githubusercontent.com/assets/11414490/21751390/a86b11a6-d5c6-11e6-987c-ee8068c00e89.jpg)
![18](https://cloud.githubusercontent.com/assets/11414490/21751391/a86c924c-d5c6-11e6-900c-7230acbb3245.jpg)

But I search ONLY whole word phrase like this:

![19](https://cloud.githubusercontent.com/assets/11414490/21751455/19bd0016-d5c8-11e6-86ad-158e68bca683.jpg)
![20](https://cloud.githubusercontent.com/assets/11414490/21751456/19d794b2-d5c8-11e6-95d7-4ac73691dedc.jpg)

**Comment by neil96** [comment]
Here's bug tracker only. I moved to phpfox-v4-feature-requests#319
