### ISSUE TITLE
Profile image in main feed, unavailable in photos.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#1843]
In the demo... If someone has updated their profile image, then in the main feed the image is visible. When the image is clicked it goes to Photos where it states "Not Found".

I'm believe that the image should appear there?

**Comment by neil96** [comment]
This is cdn issue. If you don't use cdn, you will not get this issue.

**Comment by starplan** [comment]
Thanks for the info.
