### ISSUE TITLE
Events are not showing after few mins for Guest user

### ISSUE THREAD

**Issue by raviji** [PHPfox-Official/phpfox-v4-issues#1844]
Events are not showing after few mins for Guest user please check the screenshot for your ref.

When i do the feed setting `Friends Only` on or off then only showing but that too only few mins. Please check this issue asap.

![screen shot 2017-01-11 at 3 12 38 pm](https://cloud.githubusercontent.com/assets/12031387/21843337/a6bc1a98-d810-11e6-8d69-be4a9ee95fba.png)

![screen shot 2017-01-11 at 3 00 09 pm](https://cloud.githubusercontent.com/assets/12031387/21842949/0acb150e-d80f-11e6-9a0c-c3f6c4d5a240.png)

**Comment by raviji** [comment]
How to make events for guest users? please help me asap, coz already events are online but unable to check people.

**Comment by neil96** [comment]
Hi @raviji ,
I can't reproduce this issue on my side. Could you give us  more information.
Regards.
