### ISSUE TITLE
Admin Deletes a users offensive profile picture, but avatar still remains

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1845]
If you visit a profile click on the avatar and then delete the photo, the avatar still remains. And then when you search the user from the admin CP,  and then edit user. It doesn't allow you to change the profile image in chrome, but works fine in firefox.

**Comment by neil96** [comment]
Hi @prepperz ,

I have just tested on our demo, it works. Could you give us more information to reproduce.

Regards.

**Comment by prepperz** [comment]
OK. I just tested again on my test server for v4.5.1 seems to be working.
