### ISSUE TITLE
Uploading Multiple Photos using Mobile browser

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#1848]
Multiple Photos upload using mobile browser support only IOS mobile. I try to upload multiple photos using Android Lollipop and Marshmallow with Google Chrome browser and I'm sad to say that it is not working. Only 1 photo only allow to upload.

**Comment by neil96** [comment]
Could you touch and hold to the photo, then select other photos? It works for me.

**Comment by juniortimeline** [comment]
Yahh I can select multiple photos but only 1 image can upload and not all the photos I select.

**Comment by neil96** [comment]
Hi @juniortimeline ,
Did you check the size of these photos? By default, the photo size is limit < 500KB.
Regards.

**Comment by juniortimeline** [comment]
Yes @neil96  I have set 20480kb max size users can upload.

**Comment by neil96** [comment]
I have tested and it's working. Can you reproduce it on our demo?
