### ISSUE TITLE
Pages and group menu colors are lighter than main menu

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1849]
#The menus are too light. On firefox you can barely see it. I can't believe no one has reported it. 

![stuff](https://cloud.githubusercontent.com/assets/19594886/22022244/1f9902fa-dc8f-11e6-91c7-4e4f2610cdac.png)

**Comment by neil96** [comment]
What version are you using? This is screenshot from latest version:
<img width="381" alt="screen shot 2017-01-18 at 08 52 53" src="https://cloud.githubusercontent.com/assets/15936115/22047829/e7467568-dd5b-11e6-88ff-0f08aa1f0564.png">

**Comment by prepperz** [comment]
This is right on the the phpfox demo site... the menu for pages and groups are too light compare to the main menu up top.

**Comment by prepperz** [comment]
See here: http://prntscr.com/dx1ygn

**Comment by prepperz** [comment]
You closed this seriously? So I have to create a feature request to get this issue fixed? This is ridiculous.
