### ISSUE TITLE
Pages permissions issue: widget -> members only. Not visible to admin

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1850]
When the pages permission on widget is set to members only, admin can no longer see widgets in the page manager. Also during widget creation it will not show as well.

Might want to check this for groups as well.

**Comment by neil96** [comment]
I can't reproduce on latest version. What version are you using?

**Comment by Vivian-phpFox** [comment]
After set the user become page/group admin, they will be the members of the page/group. If they unlike/unjoin the page/group, removed from admin list
