### ISSUE TITLE
v4.5.1 Gap in egift between first and second row

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1851]
Gap in egift between first and second row  and display is not responsive.
![stuff](https://cloud.githubusercontent.com/assets/19594886/22108734/8452f338-de22-11e6-8085-8a1d9dee5bf7.png)

**Comment by neil96** [comment]
I moved to PHPfox-Official/phpfox-v4-feature-requests#338
