### ISSUE TITLE
v4.5.1 Sharing photo, video, pages, groups link does not show image,  title or description on facebook

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1852]
Sharing photo and video link does not show title Sharing photo, video, pages, groups link does not show image,  title or discription on facebookor discription

**Comment by neil96** [comment]
I have tested, the photo and video work fine. We don't support display image when sharing Pages and groups in current version.

**Comment by prepperz** [comment]
Likely, due to the security restriction as it's on our test server which doesn't have a signed security authority unlike our production server.
