### ISSUE TITLE
Member index

### ISSUE THREAD

**Issue by EgyCheETah** [PHPfox-Official/phpfox-v4-issues#1853]
In the past we could modify the member index with codes like

{$aprofilephoto} or something like dat and gives profile avatar

No with results the same code gives {$aprofilephoto} dont showup the profile avatar

**Comment by neil96** [comment]
Hi @EgyCheETah ,
Could you tell us where did you do this?
>In the past we could modify the member index with codes like

**Comment by EgyCheETah** [comment]
On the left block

**Comment by neil96** [comment]
I am sorry, I still don't know how can you modify the member index code. Could you explain for us more detail. The screenshots might help. Thanks!
