### ISSUE TITLE
4.5.1 Error

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#1855]
After I upgrading my site to the newest version, I see this: 

Notice: Undefined variable: html in /home/erickcap/public_html/PF.Src/Core/View/Functions.php on line 276 Notice: Undefined variable: html in /home/erickcap/public_html/PF.Src/Core/View/Functions.php on line 279
  This is shown in block 11.

**Comment by erick260** [comment]
I create another test site, with 4.5.1 and try to move over the files to replace those, it says you have made no changes, I dont know whats wrong.

**Comment by neil96** [comment]
Hi @erick260 , 
Could you create a [ticket](https://clients.phpfox.com/submitticket.php) with your site information, then I can check this issue on your site. I can't reproduce on my side.
Regards.

**Comment by neil96** [comment]
#1864
