### ISSUE TITLE
4.5.1 Where is the event?

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#1859]
This problem since 4.5.0 unable to view events on event page. 

I create 5 events and shows only on the feed

Sweet :cry:

**Comment by Scheinwelt-Media** [comment]
change the filter from ongoing to upcoming.

**Comment by juniortimeline** [comment]
How Do I set default my event page to upcoming view? I did not see any option on AdminCP

**Comment by neil96** [comment]
Hi @juniortimeline ,
There isn't option to do it, but you can request us this feature [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).
Regards.

**Comment by juniortimeline** [comment]
This is sad. People going to blank information Event Page. I need to go back to 4.4 I receive a lot of complain about my event page because some people did not waist time to use a Filter to see What's New :(

**Comment by neil96** [comment]
You can read this [thread](https://community.phpfox.com/forum/thread/55829/events-not-showing/) to find your own solution.

**Comment by juniortimeline** [comment]
@neil96  that thread save my time to downgrade my site. Thank You so much
