### ISSUE TITLE
Recent Posts Problem

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#1860]
Recent Posts block still show the image destination link instead of the image.

**Comment by neil96** [comment]
Hi @juniortimeline 

By default of phpFox, we show text only on *block recent posts*. If you'd like to display image or hide image url in *block recent posts*, you can request us this feature [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
