### ISSUE TITLE
Ads Issue

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#1861]
1. "Body Text" of ads not show after creating an ad.
2. Manage Campaign - No Edit option

**Comment by neil96** [comment]
Hi @juniortimeline ,

As our [policy](https://github.com/PHPfox-Official/phpfox-v4-issues), please report 1 issue /request. For this one, we check the first item only.

I can't reproduce this. As you can see on your [demo](https://v4.phpfox.com/), the *ads block is display well*.
>"Body Text" of ads not show after creating an ad.

Regards.
