### ISSUE TITLE
Notifications Icon Does Not show

### ISSUE THREAD

**Issue by mrfenix** [PHPfox-Official/phpfox-v4-issues#1863]
When logged in, the number displaying the amount of notifications/message does not display above the relevant icon.

The user must click on an icon in order for it to display the amount of messages/notifications.

**Comment by neil96** [comment]
Hi @mrfenix ,
What version are you using? Can you reproduce on our [demo](https://v4.phpfox.com/)?
Regards.

**Comment by mrfenix** [comment]
It works on the demo. But this has been reported by some users who use a custom theme. Any idea what could be conflicting with this?

**Comment by neil96** [comment]
Hi @mrfenix ,

Where are these reports? Could you send us the link here. Btw, `a custom theme` is the theme download from our store or the theme is created from admincp?

Reagards.
