### ISSUE TITLE
Block Disappears

### ISSUE THREAD

**Issue by mrfenix** [PHPfox-Official/phpfox-v4-issues#1864]
I have created a block with custom html in it which appears on the core.index-visitor page.

The block works but then after some time it does not display any longer and I have to login to admincp then disable and enable the block for it to display on the front end.

**Comment by neil96** [comment]
Hi @mrfenix 
Could you tell us how long does it disappear?
Regards.

**Comment by maniacscorpio** [comment]
After upgraded to 4.5.1 all the custom blocks disappeared..  Needs emergency fix on it...  

Neither adsense showing,  nor arrow chat...  Or any other custom html block..

**Comment by neil96** [comment]
Hi @maniacscorpio and @mrfenix ,

If you'd like to apply the patch for this issue, please submit a [ticket](https://clients.phpfox.com/submitticket.php) with your site information and attach the link of this issue. We will apply this patch for you.
Regards.
