### ISSUE TITLE
Liked notification of pages video title shows original name before it was changed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1866]
When a friends "Like" your feed, the notification of pages video title shows original name before it was was changed. However, if you go you go to the video from the main video page or from pages it shows the changed name.

**Comment by neil96** [comment]
Hi @prepperz

By default, the video does not show `video title` on notification. Could you explain for us more detail. Thanks!

Regards.

**Comment by prepperz** [comment]
It mean that when you click on the notification it shows the original title. So it is apparently storing 2 sets of title. I've also noticed the video number on the notification is also different than the video on pages or main.

**Comment by neil96** [comment]
Hi @prepperz 

I tested on our [demo](https://v4.phpfox.com/v/play/p-246/), but I can't reproduce. Could you double check and give us more information. Thanks!

Regards.

**Comment by prepperz** [comment]
OK. Just checked. It seems that this issue only applies to v4.4.3.
