### ISSUE TITLE
Inactive account name does not show on list when composing a new message

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1867]
I've noticed that inactive account don't show up when you go to compose a message from the message icon on top

**Comment by neil96** [comment]
Hi @prepperz,

By default, you can send message to your friends only. Are these inactive user and the user that composes message already friend together?

Regards.

**Comment by prepperz** [comment]
Yes they are all my friends

**Comment by neil96** [comment]
Hi @prepperz 

I have just tested, but I can't reproduce.

Regards.

**Comment by prepperz** [comment]
Seem this is only applicable to v4.4.3
