### ISSUE TITLE
http 500 error

### ISSUE THREAD

**Issue by liviufox** [PHPfox-Official/phpfox-v4-issues#1868]
fresh install 4.5.1 b2
only changes:
-https enabled
-recaptcha enabled

new member registration gives http 500 error after clicking "i'm not a robot"
admin can surf with no problems on the site
 this is what i found in log :  500  POST /index.php/user/register/ HTTP/1.1

after getting a code 200

for 

GET /index.php/_ajax/?&core[ajax]=true&core[call]=core.getChildren&country_iso=BY&country_child_id=undefined&core[security_token]=49856f04e9c003f295605a630fa5bfc1&core[is_admincp]=0&core[is_user_profile]=0&core[profile_user_id]=0&_=1485461456445 HTTP/1.1

no problems without recaptcha

**Comment by neil96** [comment]
Hi @liviufox

I can't reproduce. As you can see, our demo is running latest version, https and recaptcha is enabled. Could you give us more information to reproduce. Thanks!

Regards.

**Comment by liviufox** [comment]
maybe you reopen it according to this thread???????????
https://community.phpfox.com/forum/thread/56003/registration-500-error-blank-screen/
