### ISSUE TITLE
4.5.1b2 comments problem

### ISSUE THREAD

**Issue by adrifixbg** [PHPfox-Official/phpfox-v4-issues#1869]
Content is empty.
what is going on now?
Do you recommend version 4.4.3b2 for now?

**Comment by neil96** [comment]
Hi @adrifixbg ,

I can't reproduce, could you give us more information to reproduce.

Regards.

**Comment by adrifixbg** [comment]
I have no idea.
I received a complaint from a customer that he could not comment anything in activity, photos, videos ... everything
Whether the problem is not in cache cleaning?

**Comment by adrifixbg** [comment]
I have no idea.
I received a complaint from a user that he could not comment anything in
activity, photos, videos ... everything
Whren trying to comment feed, see error Content is empty.
Whether the problem is not in cache cleaning?
whatever.
Do you recommend version 4.4.3 at this stage?

2017-01-29 17:10 GMT+02:00 Neil J. <notifications@github.com>:

**Comment by neil96** [comment]
Hi  @adrifixbg ,

Could you double check your site configurations, your 3rd-party apps.
We always recommend latest version. If you'd like listen other ideas, you can ask on our community [here](https://community.phpfox.com/forum/).

Regards.

**Comment by adrifixbg** [comment]
2 things I did before.
Turn on and off check in and watermark image
clean cache
I can not install apps, giving error: App not found in folder PF.Site/Apps/
A little late to see the site, because I uninstalled it and I was going to
install 4.4,3b2

2017-01-30 2:25 GMT+02:00 Neil J. <notifications@github.com>:

**Comment by adrifixbg** [comment]
Development on the topic.
After replacing collation of databases on utf8 unicode website is better.
Applications are installed, the comments work.

**Comment by neil96** [comment]
Hi @adrifixbg 

I have tested with these cases, but I still can't reproduce. Could you test again.

BTW, please test on latest version (4.5.1b2)

Regards.

**Comment by adrifixbg** [comment]
I turned off the option comment hack check, and now works well.
But when you turn on this option:
http://imgur.com/a/u2XLB

2017-02-03 5:02 GMT+02:00 Neil J. <notifications@github.com>:

**Comment by Epicure94** [comment]
Just upgrading our website to 4.5.1b2, same trouble and thanks to neil96 we solved it !
