### ISSUE TITLE
member search issue

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1870]
when using the global search tool and clicking on members the "view more" button does not work. it shows no more results. tested on 4.4.3 and 4.5.1 phpfox demo. this means users can not find all registered members. only the first 10.

**Comment by Scheinwelt-Media** [comment]
you can test it by searching for "to" e.g.

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

On this page, we use "load more". More users will be automatic load more when you scroll down. Where do you find "view more" button?

Regards.

**Comment by Scheinwelt-Media** [comment]
this is a screenshot before and after clicking the button. it can be found after using the global seach and selecting members on the left menu on your demo. i had to hide the search box because of this... would be nice to get a small temp fix.

![global search1](https://cloud.githubusercontent.com/assets/13225682/22536686/ffc289fc-e903-11e6-92c9-6979c097e55c.jpg)

![global search2](https://cloud.githubusercontent.com/assets/13225682/22536687/0488a91c-e904-11e6-8996-0e14ac95e425.jpg)

**Comment by Scheinwelt-Media** [comment]
btw when using the user browse search there are much more users with "to" or anything else...

**Comment by PhpFoxJohnJr** [comment]
Looking through the bugs and noticed this was fixed on March 12 and changed from 4.5.2 to 4.6.0 but then it looks like on March 30 it was change from 4.6.0 to 4.5.2 so I am confused or maybe I am reading it wrong.  You can delete this post if it is still for 4.6.0...

**Comment by neil96** [comment]
Hi @PhpFoxJohnJr ,

We apologize for making you confused. This issue should have been fixed in 4.5.2, but for some reasons, we had to move to 4.6.0.

Regards.
