### ISSUE TITLE
Missing Phrase in Group App

### ISSUE THREAD

**Issue by Foxgerman** [PHPfox-Official/phpfox-v4-issues#1873]
If a user send an invitation to another the recipient will get an email with subject "{{ full_name }} sent you a page invitation." This is 1st: not correct since this is a group and 2nd: this phrase is not available in phrase manager yet. 

Would be nice if the dev´s could  add this.

**Comment by neil96** [comment]
Hi Foxgerman,

I have tested on our [demo](https://v4.phpfox.com/) and it works. Did you do "find missing phrase" during upgrade?

Regards.

**Comment by Foxgerman** [comment]
Hi Neil, found this after check twice. Can be closed.
