### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by kseniya93** [PHPfox-Official/phpfox-v4-issues#1875]
Fix it http://uploads.im/I6tcA.jpg
Fix it http://uploads.im/RYsME.jpg

**Comment by neil96** [comment]
Hi @kseniya93 ,

Our community is opened for our clients only, so we removed register button.

Regards.

**Comment by kseniya93** [comment]
I speak for the indentation, and not for lack of registration keys. Make the normal indentation. Button curve icon and search curve.

**Comment by kseniya93** [comment]
Indent button next to do. Button comes near the edge.

**Comment by neil96** [comment]
Hi @kseniya93 ,

Can you reproduce on https://v4.phpfox.com/, our community is a custom site.

Regards.

**Comment by kseniya93** [comment]
No.

**Comment by kseniya93** [comment]
In the screenshot above problem. Fix it.
