### ISSUE TITLE
V4.5.1b2. In ACP all the "MODULES" are missing. (Settings - Module).

### ISSUE THREAD

**Issue by kaligula7** [PHPfox-Official/phpfox-v4-issues#1878]
Hello!
I just updated my PHPFOX to version V4.5.1b2.  (from 4.4)

All update steps were made!
After updating, 32 changed files are found.
In ACP all the "MODULES" are missing. (Settings - Module).
![module](https://cloud.githubusercontent.com/assets/21354832/23095377/4ceb2812-f609-11e6-9f30-62e0172d80c0.JPG)

Best regards

**Comment by neil96** [comment]
Hi @kaligula7 ,

From 4.5.0, we moved all modules to AdminCP -> Apps. Please check again.

Regards.

**Comment by kaligula7** [comment]
Excuse me, I've tried it 3 times to install the update. Everything as in instruction.
My ACP is missing all the important functions and modules. Debug mode - is only a white page.

![apps](https://cloud.githubusercontent.com/assets/21354832/23144163/1040b332-f7c6-11e6-8f2a-104fbfbe5274.JPG)

![bootstrap](https://cloud.githubusercontent.com/assets/21354832/23144170/1c1baf40-f7c6-11e6-948d-167d2cd421fa.JPG)

![themes](https://cloud.githubusercontent.com/assets/21354832/23144221/656b7de2-f7c6-11e6-8a69-d80c349057bb.JPG)

**Comment by neil96** [comment]
Hi @kaligula7 

It might be your upgrade process does not complete or there is an issue on your 3rd-apps. If you have support plan, you can submit a [ticket](https://clients.phpfox.com/submitticket.php), we can check more detail for you.

Regards.
