### ISSUE TITLE
faulty Notifications on newsfeed and notification menu

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-issues#1879]
After every 10-15 mins , a notification appears on my newsfeed , that i have 6 new updates , you have 3 new updates ..http://prntscr.com/ecra0g  ..Even though I have no new updates , clicking on them just refreshes the page with old newsfeed ..Same appears on notification menu , it becomes red , indicating new activitty , but clicking on that shows days old things .

**Comment by neil96** [comment]
Hi @shashankguitarist 

I can't reproduce. Could you give us more information.

Regards.

**Comment by shashankguitarist** [comment]
SEE THE VIDEO 
i am getting notification as New Feeds even when i have visited the site many times after those activities ......https://www.dropbox.com/s/2vnfajroauzy104/notification%20fault.avi?dl=0

**Comment by neil96** [comment]
Hi @shashankguitarist 

I got your issue, but I can't reproduce on my side. Please submit a [ticket](https://clients.phpfox.com/submitticket.php) with your site information and link to this issue. It can be server issue or only happen with special configurations.

Regards.

**Comment by neil96** [comment]
I saw your ticket and I can't reproduce this issue on your site too.

**Comment by shashankguitarist** [comment]
found the way to reproduce it .it has something to do with THIS SETTING: https://MYSITE/admincp/setting/edit/?module-id=feed#refresh_activity_feed .
SEE WHAT IS WRONG :http://prntscr.com/eny73b

**Comment by neil96** [comment]
Hi @shashankguitarist ,

What's wrong with this setting? Be default, it's 60 (seconds). It defines how long the feed should check for new feed.
Regards.

**Comment by shashankguitarist** [comment]
Is it designed to show last 4-5 feeds again and again ? I thought it will show only NEW feeds , the feeds that I have not seen ...my site is not live right now , every time I login or refresh , it says you have NEW FEEDS and shows me the same OLD FEEDS.

**Comment by neil96** [comment]
Hi @shashankguitarist ,

We tried to reproduce on our site and your site but can't reproduce. Please reply the ticket if you can show us detail steps to reproduce.

Regards.

**Comment by shashankguitarist** [comment]
posted the video screen recording on ticket .please see
