### ISSUE TITLE
unknown login alert not working fine

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-issues#1880]
i always use the same device to login to my account . http://prntscr.com/ecrclw ..It sends me the email notification all the times http://prntscr.com/ecrclw ..Other users also complaint about the same issue

**Comment by shashankguitarist** [comment]
fixed in 4.5.2 ?

**Comment by shashankguitarist** [comment]
ANY UPDATE ?

**Comment by neil96** [comment]
Hi @shashankguitarist ,

As our designed, when your public IP is changed, you will receive alert even you are using the same PC.

Regards.

**Comment by shashankguitarist** [comment]
No , my IP remains the same

**Comment by neil96** [comment]
Please use the tool (like this: https://www.whatismyip.com/) to check your public IP.

Regards.

**Comment by shashankguitarist** [comment]
Please enable single login app on v4.phpfox.com ..let me check or you check yourself ..because all members in my site complaints the same ..it can't be like their IP is changing within minutes..
