### ISSUE TITLE
Create New Apps Missing

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1881]
Where is the create new apps button and import module? My phpFox version is 4.5.0 (build 1)

![image](https://cloud.githubusercontent.com/assets/16043743/23300772/0dffe152-fac2-11e6-8828-8465403b9ac1.png)

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

These features are available with techie mode only. 

Regards.

**Comment by sanjosedennis7593** [comment]
Thanks.
