### ISSUE TITLE
Video upload from localhost issue !

### ISSUE THREAD

**Issue by crea7web** [PHPfox-Official/phpfox-v4-issues#1882]
You can not upload video from localhost from phpfox v4 as in the old version of phpfox v3 !

**Comment by neil96** [comment]
Hi @crea7web ,

You have to set up Zencoder api and Amazon S3 to make it works.
You can follow this tutorial for more detail: https://docs.phpfox.com/display/FOX4MAN/Setting+Up+the+Video+App

Regards.
