### ISSUE TITLE
No IM chat on phpfox v4 from localhost issue !

### ISSUE THREAD

**Issue by crea7web** [PHPfox-Official/phpfox-v4-issues#1884]
No IM Chat directly from localhost on phpfox v4 as in the old version of phpfox v3 !

**Comment by neil96** [comment]
Hi @crea7web ,

On phpFox v4, we have IM. But you have to config nodeJS server to make it works. There are some tutorials that you can reference: 
https://docs.phpfox.com/display/FOX4MAN/Server+Setup+for+IM+Module
https://docs.phpfox.com/display/FOX4MAN/Using+IM+Chat
Regards.
