### ISSUE TITLE
Missing some folder in create apps. 

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1885]
I just want to ask is this an issue in phpFox? i just create an app in the admin dashboard then some folder are missing like controller,blocks and hooks. It is not same as in the developers documentation of phpFox im using phpFox version 4.5.0 build 1

![image](https://cloud.githubusercontent.com/assets/16043743/23331546/070a5ae4-fba3-11e6-8666-d786491799cc.png)

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

I can't reproduce on latest version (4.5.1b2). Could you try again.

Regards.

**Comment by sanjosedennis7593** [comment]
same as what i've been said some folder are missing. may version is 4.5.0b1

**Comment by neil96** [comment]
Please test again on latest version.

**Comment by sanjosedennis7593** [comment]
how to update to latest version? i can't update

**Comment by neil96** [comment]
You can follow this tutorial to upgrade your site: https://docs.phpfox.com/display/FOX4MAN/Upgrading+Your+phpFox+Website

**Comment by sanjosedennis7593** [comment]
okay sir thanks, one more think i just want to ask, what should i do if i want to extend a functionality? to add custom function something like that? should i create an application? block? or module?

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

For question like this, please ask on our [community](https://community.phpfox.com/forum/).

Regards.
