### ISSUE TITLE
issue shared file with page

### ISSUE THREAD

**Issue by wetricks** [PHPfox-Official/phpfox-v4-issues#1886]
hello, 
when you upload a photo or video , when you create an event or something with a page, it is displayed in the page but not on the photo, event , video module. 
for exemple, i have created an event for a page, i can find this event in my page but not on the event module. it's the same for photo, video and other thing i want to share with the page.
thanks 
best regards
sylvain

**Comment by neil96** [comment]
Hi @wetricks ,

It's our rule. The items are created from pages/groups do not display in module home page.

Regards.

**Comment by wetricks** [comment]
Hi , ok but it could be interresting to let the administrtor of the site the choice to enable or not to display or nit the thing  posted with a page..
Nobody would like this feature ?
Thanks
Sylvain
