### ISSUE TITLE
phpFox v4.5.1 b2 not working

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1887]
After i install phpFox latest version, im done with database config and account setup, blank screen only appears. It appears to be an internal server error. 

![image](https://cloud.githubusercontent.com/assets/16043743/23351764/ffc4ab0c-fcfd-11e6-8857-b66cbfa16085.png)

**Comment by sanjosedennis7593** [comment]
When i enabled the debug mode, a message says theme not found.

![image](https://cloud.githubusercontent.com/assets/16043743/23351892/02fa51f4-fcff-11e6-8bb9-27b8084b513b.png)

**Comment by neil96** [comment]
Duplicate with #1889
