### ISSUE TITLE
No themes on phpFox admincp

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1889]
I just updated my phpFox version from 4.5.0 b1 to 4.5.1 b2, why is there are no themes in the themes section and when i click rebuild core themes the page said "The page you are looking for cannot be found."
Even i have themes in PF.site/flavors. It doesn't appear on the admincp

![image](https://cloud.githubusercontent.com/assets/16043743/23398615/34724596-fdd8-11e6-8c1f-e8801699ee0e.png)

**Comment by sanjosedennis7593** [comment]
Another question to ask, after i install phpFox v4.5.1 it doesn't work propery, it needs to modify the database first, every installation it needs to modify the value of pf_theme and pf_theme_style.

**Comment by sanjosedennis7593** [comment]
This is what actually happen after installation. This is the latest version of phpFox

![image](https://cloud.githubusercontent.com/assets/16043743/23410318/cb3b7d0e-fe09-11e6-840a-b98e004caf31.png)

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

We can't reproduce this issue. It might be your steps are not correct or your server doesn't meet phpFox's requirement. For these case, if you have support, please submit a ticket here: https://clients.phpfox.com/submitticket.php

Regards.
