### ISSUE TITLE
phpFox v4.5.0 b1 to phpFox 4.5.1 b2

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1891]
Why is this error happening? I upgrade phpFox via web upgrade

![image](https://cloud.githubusercontent.com/assets/16043743/23461161/bd630a66-fec3-11e6-8b42-425b551a00f4.png)

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

I can't reproduce this issue. This issue can be:

- Your server doesn't meet our [requirements](https://www.phpfox.com/requirements/). 
- Permission for directories PF.Base and PF.Site must be 777 during installation and upgrade.
- 3rd-apps do not compatible with newer version.
- Your upgrade steps do not correct ([our tuts](https://docs.phpfox.com/display/FOX4MAN/Upgrading+Your+phpFox+Website)).

For better support, you can submit a [ticket](https://clients.phpfox.com/submitticket.php) with your site information if you have support plan. We can check detail on your site.

Regards.
