### ISSUE TITLE
There is no auto cache clearing option

### ISSUE THREAD

**Issue by orgazilla** [PHPfox-Official/phpfox-v4-issues#1892]
Why isn't there a auto cache clearing option? Why must it be manual? Wouldn't an auto cache clearing option eliminate the need to manually do it? I hate having clients interested in my website not being able to sign-up due to me having to clear the cache. I don't have time to sit in the control panel of my website and clear the cache every 10 mins. **Please add a auto cache clearing option for people who don't have time to sit in their admin panel all day and do it manually.**

**Comment by neil96** [comment]
Hi @orgazilla 

You can post your request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new). This repo for bug tracker only.

Regards.
