### ISSUE TITLE
Activity point properties

### ISSUE THREAD

**Issue by Promastertr** [PHPfox-Official/phpfox-v4-issues#1893]
When members share, they gain points as they see their share. For example; Win 1000 points, gain 10 activity points. Did I get it?

**Comment by Promastertr** [comment]
On this counts, makes a share and makes effort in sight. Earns as much money as you earn. Make good quality shares to make money

**Comment by neil96** [comment]
Hi @Promastertr 

I don't understand what's the bug here. Could you explain for us more detail. If you'd like request a new feature, you can request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
