### ISSUE TITLE
Index is undefined error.

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1894]
I got an undefined index error in my phpFox. I notice that in the apps table there are no apps_dir columns, in the code i check and i see that they search for that column even if its not exist. I just recently updated my phpFox v4.5.0 b1 to v4.5.1 b2. Why phpFox not updated the database? i thought it will update it automatically.

**Comment by sanjosedennis7593** [comment]
I got an error on this one, if i change the apps_dir to apps_id. It works.
![image](https://cloud.githubusercontent.com/assets/16043743/23578724/44c790d4-0118-11e7-9a2b-c32d7e88e905.png)

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

The column "apps_dir" must be exist on 4.5.1. There might be error(s) during your upgrade process. Please test again on your side.

If you have support plan, you can [submit](https://clients.phpfox.com/submitticket.php) a ticket, we can check for you.

Regards.
