### ISSUE TITLE
phpFox Operating System issue.

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1896]
I run my phpFox on windows and it is not working properly. However, it works on my mac. Is there any issue in windows OS? Actually all of my concern only happening in windows but not on mac.

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

Could you tell us detail about your issue? It can be your window doesn't meet our [requirement](https://www.phpfox.com/requirements/).

Regards.

**Comment by sanjosedennis7593** [comment]
From installation, upgrade and several functions aren't working properly like when creating an application some folder aren't generated. I also encounter when i uninstalled a plugin that is not related to themes. However, the themes got deleted too.

I already checked the requirements and all of it are passed.

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

We can install, upgrade normally in a window PC without any problem.

>several functions aren't working properly like when creating an application some folder aren't generated
I can reproduce on 4.5.0, but we fixed on 4.5.1. Did you test on latest version.

Btw, please follow our [guidelines](https://github.com/PHPfox-Official/phpfox-v4-issues/blob/master/README.md) during posting a issue.

Regards.

**Comment by sanjosedennis7593** [comment]
Can this be an issue on my machine? Windows 10 is my operating system. I just still wondering why it happen on my laptop but on my macbook don't.

**Comment by neil96** [comment]
Yes, It can be your machine is missing some extensions. I close this issue. If you can give us detail steps to reproduce, kindly open new issue.
