### ISSUE TITLE
invite group

### ISSUE THREAD

**Issue by wetricks** [PHPfox-Official/phpfox-v4-issues#1897]
hello, 
when i want to invite friend to a group, not all my friend are displayed in the list.
i have 89 friend and in the list , there is just 36 friend
thanks
best regards
sylvain

**Comment by neil96** [comment]
Hi @wetricks ,

Could you tell us what's the list you mention here?

On our demo, this user has over 1k friends: https://v4.phpfox.com/bryanfox/friend/. The site will automatically load more friends when you scroll down.

Regards.

**Comment by wetricks** [comment]
hello, 
it's not on the friend page module. the issue is on the group module : 
- when you create a group and want to invite friend to this group , it does not show all your friend...

let me know if you do not understand.

regards

**Comment by neil96** [comment]
Hi @wetricks ,

The feature *suggest friends* is limit by this setting "Friends Cache Limit". By default, it's 100. Base on your business, you can increase it.

Regards.

**Comment by wetricks** [comment]
Hi neil96, 
thanks for the answer but maybe i don't explain well : 
- i have created a group here : https://spotypark.com/groups/
- when i want to invite friend to my group , it suggest just 36 friend (i have 89 friend )

i have try to change the setting you explain but it do not change anything.

thanks for the support

best regards

sylvain

**Comment by neil96** [comment]
Hi @wetricks ,

By default, it shows 36 friends, to show more friends, please use feature search (type your friend name then click enter).

Regards.

**Comment by wetricks** [comment]
Hi.
Ok thanks for the info.
Last question.
Is it possible to change this setting the more friends ?
Where can i change it ?
Thanks
Best regards 
Sylvain
