### ISSUE TITLE
Video Tab is not showing in profile page

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1899]
when we enable video app its not showing on user profile page.its confuse for user where to upload video.
so any setting to show here this tab same as on homepage
![video tab](https://cloud.githubusercontent.com/assets/13433124/23751563/f3d10a00-04f7-11e7-882f-5ff932c157c1.png)

**Comment by neil96** [comment]
Duplicate with #1574
