### ISSUE TITLE
Unable to cache template file.

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1902]
When i'm trying to create a new apps, an error display, it said that unable to cache the template file. Anybody encounter this issue? 

Unable to cache template file: C:\xampp\htdocs\supportcommunity\PF.Base\file\cache\template\TodoList/views_controller_index.html.php.php

**Comment by sanjosedennis7593** [comment]
![image](https://cloud.githubusercontent.com/assets/16043743/23954457/4bd1f596-09d2-11e7-9d18-c7c6e45b946e.png)

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

It might be apache doesn't have permission to create new file. If you use windows, I'd recommend that you do not install wamp/xampp on disk C.

Regards.
