### ISSUE TITLE
Hardcoded word "by" in photos section

### ISSUE THREAD

**Issue by makfoulie** [PHPfox-Official/phpfox-v4-issues#1904]
Hello,

On an album, when you put your mouse on a thumbnail, a slide appears with photo name and "by USERNAME".

This word "by" is hardcoded.

Here is a screenshot:
![2017-03-19_18h52_56](https://cloud.githubusercontent.com/assets/25231367/24083331/68fe260c-0cd5-11e7-8b97-70f520996dcf.png)

**Comment by neil96** [comment]
Duplicate with #1874
