### ISSUE TITLE
Forum Reply Post not delete.

### ISSUE THREAD

**Issue by vignesh20993** [PHPfox-Official/phpfox-v4-issues#1905]
In Forum Reply delete is not working . it displays "$Core.jsConfirm is not a function"

**Comment by neil96** [comment]
Hi @vignesh20993 ,

I can't reproduce on latest build, default configurations. Could you double check again.

Regards.

**Comment by vignesh20993** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/26535960/24090502/d0a7ed24-0d66-11e7-9032-30a17b412c47.png)
Don't know whether this problem occur in my site. see the screenshot.

**Comment by vignesh20993** [comment]
Don't know whether this problem occur in my site. please see the screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/26535960/24090532/1f80e054-0d67-11e7-9dbd-370d32872597.png)

**Comment by neil96** [comment]
Hi @vignesh20993 ,

This issue can come from a 3-rd app. You can disable app by app to check. If you have support plan and would like we check for you, please submit a ticket [here](https://clients.phpfox.com/submitticket.php).

Regards.

**Comment by vignesh20993** [comment]
OK i will Check. Thank you for your quick response.

**Comment by vignesh20993** [comment]
Hi @neil96 
I fixed forum issue .thanks for your support
