### ISSUE TITLE
phpFox 4.5.1b2 - notification does not display Name

### ISSUE THREAD

**Issue by zenepay** [PHPfox-Official/phpfox-v4-issues#1906]
![notification](https://cloud.githubusercontent.com/assets/1179823/24099023/ec057ed6-0d9f-11e7-9f68-88c07f0d6f3e.png)
In the notification, the name does not display for users who registered with Facebook (Facebook Base Module). It displays as {{user_full_name}}
In the profile  of the user, it displays correctly.

**Comment by neil96** [comment]
Hi @zenepay ,

These phrases are not in core, please double check your 3rd apps.

Regards.
