### ISSUE TITLE
Amazon CDN Content uploaded on site server as well 4.5.1b2

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1907]
i have enabled Amazon CDN and photo content uploaded by user puts into Amazon CDN as well as on local hosted server. then how can i get benefit of amazon cdn.
in photo inspect element tab its show amazon s3 url.
same file on local server
![amazon local server](https://cloud.githubusercontent.com/assets/13433124/24244046/5a7315be-0fe3-11e7-976c-50f6968e6e0f.png)
same file on amazon cdn
![amazon s3 cdn](https://cloud.githubusercontent.com/assets/13433124/24244045/5a6b6166-0fe3-11e7-841f-1d60457cf6b9.png)

**Comment by neil96** [comment]
The same with #1810
