### ISSUE TITLE
admincp/seo/rewrite not working

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1910]
Why admincp/seo/rewrite aren't working? i tried to change user/logout to user/logout2 and it does redirect to user/browser ? I need the modify the module url and in the community ,i saw that they suggest using this rather than .htaccess, i tried to rewrite it using .htaccess and won't work. 

I need to remove the ynclean in the url, because by default when i clicked the dashboard, in the address bar it displays ynclean/dashboard. i saw a lot of post regarding about this issue and no one replied.

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

This feature is not supported redirect from new url to default url and opposite. Btw, this feature is hidden from V4.

Regards.
