### ISSUE TITLE
deleting user when group member

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1911]
on v4.4.3(build 2) i have noticed that users that are group members can not be deleted from the site. the routine deletes some db entrys (e.g. friends) of this user but seems to stop the process on groups. unfortunately i had no time to test on v4.5 yet.

**Comment by neil96** [comment]
@Scheinwelt-Media 
Please test on latest version. Thanks!
Regards.
