### ISSUE TITLE
Blank site when exporting theme

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1913]
On 4.5.2 i get redirected to a blank site after exporting themes. The exported zip seems to be fine. Not a big issue...

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

I tested on v4.phpfox.com and my localhost site, but I can't reproduce. Could you double check again.

Regards.

**Comment by Scheinwelt-Media** [comment]
i have only tested on my upgraded site on local lampp (without any third party apps). will check on online server and with debug enabled asap.

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

Do you test again?

Regards.

**Comment by Scheinwelt-Media** [comment]
on online server it opens a blank page or tab when exporting a theme and stays there.

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

Could you give us detail steps to reproduce. We can't reproduce it.

Regards.

**Comment by Scheinwelt-Media** [comment]
go to theme manager and click "export". tested on linux firefox 50.0.2

**Comment by neil96** [comment]
Hi @Scheinwelt-Media 

I tried with firefox on ubuntu. It works.

Regards.
