### ISSUE TITLE
Username on profile

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1914]
the username and extra info block on profile is not positioned correct. looks a bit strange... tested on dev 4.5.2 and phpfox demo.

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

Could you give us a screenshot of them.

Regards.

**Comment by Scheinwelt-Media** [comment]
![profileun1](https://cloud.githubusercontent.com/assets/13225682/24639030/409e27f6-18ed-11e7-8051-5c19c5cd8601.jpg)
![profileun2](https://cloud.githubusercontent.com/assets/13225682/24639031/409edce6-18ed-11e7-9765-7a66d3317a44.jpg)

**Comment by Scheinwelt-Media** [comment]
![profileun3](https://cloud.githubusercontent.com/assets/13225682/24639103/a9904d52-18ed-11e7-8004-5f7d7b8b42c6.jpg)

**Comment by neil96** [comment]
Thank @Scheinwelt-Media ,
I can reproduce this issue IE only.

Regards.
