### ISSUE TITLE
phpfox 4.5.2 relationship problem

### ISSUE THREAD

**Issue by foxbgnet** [PHPfox-Official/phpfox-v4-issues#1916]
relationships аre not visible in profiles with whom.

**Comment by neil96** [comment]
Hi @foxbgnet ,

I can't reproduce. Please checkout my screenshot.
<img width="383" alt="screen shot 2017-04-17 at 09 05 41" src="https://cloud.githubusercontent.com/assets/15936115/25076681/22104a20-234d-11e7-97b4-50e0eb9ce3c8.png">

Regards,
Neil.

**Comment by foxbgnet** [comment]
http://imgur.com/a/WNWwx

**Comment by neil96** [comment]
Hi @foxbgnet ,

Does your friend accept your request?

Regards.
