### ISSUE TITLE
Translation in App titles

### ISSUE THREAD

**Issue by iogames** [PHPfox-Official/phpfox-v4-issues#1917]
This is not an issue or bug, mostly a detail...

in the app section all the old apps' titles can be translated, but all the new have not been include it

http://yoursite.com/index.php/admincp/apps/

![phpfox](https://cloud.githubusercontent.com/assets/342235/25056687/aa9fda7c-2127-11e7-88b7-da46fc1c7718.jpg)

So can you add in the translation section those app titles to translate?

**Comment by neil96** [comment]
Hi @iogames ,

Our default apps already support translate. You can go to phrase manager, find and translate them.

Regards.

**Comment by iogames** [comment]
Thanks!
I´ve done that for 7 years, I meant the phrases are not included for
translation



*AR©ADIA*™

**Comment by Foxgerman** [comment]
Some of them like Groups and Facebook Base are not translatable in backend. Same issue here.

**Comment by iogames** [comment]
Yeah, it's not big deal but sometimes clients use that excuse to say it's not a good product, then demand refunds... when it's not even the 0.1%
From Amazon CDN - Videos, those titles are not included to translate, that's why I didn't report it as a bug but as a detail :)

**Comment by neil96** [comment]
Hi all,
As commented above, all apps from phpFox are supported translate app title. We don't have a separate place for them, but you can go to phrases manage, find and translate them.

Regards.
