### ISSUE TITLE
Issue post as page

### ISSUE THREAD

**Issue by wetricks** [PHPfox-Official/phpfox-v4-issues#1918]
Hello,
I have created an event as page on the demo site, i can see this event in the feed but not in the event section of my page.
Thanks 
Best regards 
Sylvain

**Comment by neil96** [comment]
Hi @wetricks ,

By default, The event section only displays *on going* events. If you'd like to see all events, please select "All time" in **When** filter.

Regards.

**Comment by wetricks** [comment]
Hi Neil96, 
thanks for the answer , i'm a noob ;)
regards
