### ISSUE TITLE
Missing Phrase

### ISSUE THREAD

**Issue by Foxgerman** [PHPfox-Official/phpfox-v4-issues#1919]
![bildschirmfoto 2017-04-19 um 06 43 15](https://cloud.githubusercontent.com/assets/5095754/25163987/507f2a16-24ce-11e7-812e-96ec07e218e3.png)
There are a missing phrase in 4.5.2:
{{ full_name }} is requesting to join your group "{{ title }}"

Phrase is still in english language pack but not found in other languages.  
PF.Site/Apps/core-groups/Service/Callback.php line 816

**Comment by neil96** [comment]
Hi @Foxgerman ,

To update new phrases in other languages, please to go AdminCP -> language -> select a language and click on "Find missing phrases".
From 4.6.0, new phrases will be updated automatically.

Regards.
