### ISSUE TITLE
Incorrect formatting Custom Fields (ua, ru)

### ISSUE THREAD

**Issue by websistema1** [PHPfox-Official/phpfox-v4-issues#1924]
After updating to version 4.5.2, the formatting of user fields is not correct for Russian or Ukrainian languages.
![2017-04-27_215420](https://cloud.githubusercontent.com/assets/14079310/25500303/3427ae86-2b97-11e7-8125-89a4e98e4235.jpg)
![2017-04-27_215444](https://cloud.githubusercontent.com/assets/14079310/25500310/3a90aa20-2b97-11e7-88b4-0a83f7e7dece.jpg)

**Comment by neil96** [comment]
We improved this feature in phpFox 4.6.0.


Regards.

**Comment by websistema1** [comment]
The error remains - checked on version 4.6.1b6
![2018-08-27_071004](https://user-images.githubusercontent.com/14079310/44640193-fd1eaf00-a9c8-11e8-9a3e-1a414182d853.jpg)
![2018-08-27_071059](https://user-images.githubusercontent.com/14079310/44640197-014acc80-a9c9-11e8-94b5-3dceb3c5d415.jpg)
