### ISSUE TITLE
Video App;  converting Old videos problem

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#1926]
Latest Phpfox with latest Video App

When We click convert old videos in video App we get an internal server error. And after a page refresh,  We get a message " Videos are converting. Remaining videos now is 2320". Now every time I visit video convert section I am getting the same message "Videos are converting. Remaining videos now is: 2320" 

I have about 3000 videos on my website posted only in Groups. Not anywhere else on my website.

All my old videos are embedded from Youtube. No locally uploaded video.

**Comment by neil96** [comment]
Hi @aakash83 

Did you click "Convert directly" or "Convert via cron".  If you selected "convert via cron", you site have to setup cronjob.

Regards.

**Comment by aakash83** [comment]
I clicked convert directly. And after clicking the page remained busy for some time and then I got an Internal Server error.  Now every time I visit video  App >> Conver old videos  I get this message  "Videos are converting. Remaining videos now is: 2320"
