### ISSUE TITLE
Video App : Wrong Error Message

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#1927]
Latest PHPfox with Latest Video App

When we browse Video section (front end) and click My videos we get videos shared by the current user. but we also get an error message  "Unable to find the page you are looking for." . All my videos are embedded from youtube. No locally hosted video.
![image](https://cloud.githubusercontent.com/assets/406030/25567118/21361e50-2de7-11e7-97cf-1ea5a8d5195e.png)

**Comment by neil96** [comment]
Hi @aakash83 ,

Please go to AdminCP -> Maintenance -> "Remove files no longer used" and delete them. Old files from old video app might be root cause.

Regards.

**Comment by aakash83** [comment]
Hi Neil , I deleted all old files but the error message is still there.

**Comment by aakash83** [comment]
@Vivian-phpFox  The problem is still there in the latest version.

**Comment by neil96** [comment]
Hi @aakash83 ,

We have released a new version of [video](https://store.phpfox.com/product/1819/video), please upgrade your video app.

Regards.

**Comment by aakash83** [comment]
I already upgraded it. But the error message is still there.

**Comment by neil96** [comment]
Hi @aakash83 ,

I have checked with team, because you ran convert process, so videos belong to deleted pages/groups can not be removed. For your case, please send us a [ticket](https://clients.phpfox.com/submitticket.php) with your site information. We will manually remove them for you.
Regards.
