### ISSUE TITLE
Video App : Duplicate video module showing in all menus

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#1928]
latest phpfox and lastest video app
After installing Video App there are two video modules showing on Home Menu , Pages and Groups menu. Each having a different URL .
http://www.example.com/index.php/groups/233/video/
http://www.example.com/index.php/groups/233/v/

![image](https://cloud.githubusercontent.com/assets/406030/25567158/143e695e-2de8-11e7-8643-d89a24ae3d5d.png)

**Comment by neil96** [comment]
Hi @aakash83 ,

Please go to AdminCP -> Maintenance -> "Remove files no longer used" and delete them. Old files from old video app might be root cause.

Regards.
