### ISSUE TITLE
Deleted group status shows up on new groups

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1929]
When groups are deleted and new groups are added you can sometimes see status messages from the deleted groups in the new ones.

**Comment by Scheinwelt-Media** [comment]
this indicates that comment are not fully deleted when a user or admin deletes a group and they get somehow connected to the newly created groups. i have not checked the database yet or could this be a cache issue? the groups on my testsite are deleted some days ago...

**Comment by Scheinwelt-Media** [comment]
to reproduce this add some groups and left a status on each. then delete the groups and add some more. the status will show up again.

**Comment by Scheinwelt-Media** [comment]
i can not reproduce it on the demo but using the same version 4.5.2 on dev site

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

From 4.6.0, we will improve this rule. All contents of group will be deleted if group is deleted.

Regarding this issue, could you give us your demo link?

Regards.
