### ISSUE TITLE
issue with Display friend count on Find Member Page

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#1930]
Latest Phpfox
When We search for a member by entering a name on browse member page (front-end). The search results come up with users profiles ( name ,images) and friend count is also shown. If a member don't have any friends then  phpfox only display  " Friends ". it don't  display 0 friends .

![image](https://cloud.githubusercontent.com/assets/406030/25596345/f114b3d4-2ec8-11e7-9710-b0351af3d0cf.png)

**Comment by neil96** [comment]
Hi @aakash83 ,

It might your site is missing phrases. Could you go to admincp -> languages -> selecet a language -> find missing phrases. Then do again with all language packages.

It works on my side. 
![screen shot 2017-05-03 at 09 04 43](https://cloud.githubusercontent.com/assets/15936115/25646189/195d4c80-2fe0-11e7-9d03-4f669aa6f624.png)

**Comment by aakash83** [comment]
hi neil. i did all these steps and then cleared cache. plus rebuild core theme. But issue is still there.
I have only English Language installed on my website.

**Comment by neil96** [comment]
Hi @aakash83 ,

It can be other apps override our phrase. Could you send us a [ticket](https://clients.phpfox.com/submitticket.php) with your site information, so I can check detail this issue.

Regards.
