### ISSUE TITLE
Which class should be change to implement Jalali Calendar

### ISSUE THREAD

**Issue by narengenet** [PHPfox-Official/phpfox-v4-issues#1931]
I want to know how i can change calendar and every date calculation?
I know that i can add jquery picker for local culture and change date picker. But the year calculation remains unchanged with jquery picker for local culture.
Do i change date.class.php?

**Comment by neil96** [comment]
Hi @narengenet ,

Here is bug tracker only. For question and discussion, please post on your [community](https://community.phpfox.com/forum/). Thanks!

Regards.
