### ISSUE TITLE
new video app - click on a category but why do the others disappear ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1932]
wonder why if you click on a category why do the others disappear ? should stay active so we can scroll by clicking on the categories at any time, not hide and then have to click all videos or my videos or friends videos in order to see category list again ??
here is photo after i have clicked on a video category

![category does not show after click on one](https://cloud.githubusercontent.com/assets/17736688/25650314/9336ea8c-2fa1-11e7-85ec-8da91a993a33.GIF)

**Comment by neil96** [comment]
Hi @spirogg,

This is our default rule. In all our apps that support sub-category, if you click on a category, block category will show all sub-category belong to that category. If that category does not have sub-category, block category will be hidden.

If you have better rule, you can suggest for us [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new). Thanks.

Regards.

**Comment by spirogg** [comment]
https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/359
