### ISSUE TITLE
You don't have permission to access /index.php on this server.

### ISSUE THREAD

**Issue by aliraza170** [PHPfox-Official/phpfox-v4-issues#1933]
When I try to Edit any user it returns me 403 Error Page

https://www.funkodia.com/index.php?do=/admincp/user/add/

Please update, Thanks

**Comment by neil96** [comment]
Hi @aliraza170 ,

I can't reproduce, these check your server configurations.

Regards.

**Comment by aliraza170** [comment]
Can you please guide me that what configurations are required for this?
