### ISSUE TITLE
keycdn issue - my sites images were not showing and could not login

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1935]
i turned on and tried keycdn, after entering url and turning it on following the instructions you have online
https://docs.phpfox.com/display/FOX4MAN/Setting+Up+the+CDN+Service+App
, after my site went to all links and there was no images and i could not login to the site. so i went into phpmyadmin and found the app set it to 0 off then was able to login, but when i tried to turn on the app again to turn off cdn and remove url it kept going to all links on the website and i could not save anything.. finally i used mt tab on my keyboard to select NO and hit enter and then site came back up and i was able to remove the keycdn url. 

but why did this happen and how to correct it ?

please i would like to use this feature unless you have a better solution ?

this is what the site looks like when i add the keycdn url and turn on the feature ??

![cant-set-to-no-and-remove-cdn-url-please-help 2](https://cloud.githubusercontent.com/assets/17736688/25787174/dbdca08a-3364-11e7-9d3c-bc189638b9d0.jpg)

**Comment by neil96** [comment]
Hi @spirogg ,

Is your site using https? Do you use keyCDN with https?

Regards.

**Comment by spirogg** [comment]
yes https yes had it turned on shared..  also i have nginx setup on my vps engintron app for cpanel sir ?

**Comment by spirogg** [comment]
@neil96 anyway to give you my info for keycdn and my site to see what the issue maybe ?? its not really live with really any users just starting out but your more than welcome to sue as a test site for checking this ?

**Comment by neil96** [comment]
Hi @spirogg ,

Thanks very much! Please send us these information [here](https://clients.phpfox.com/submitticket.php). (Please attach this issue in your ticket)

Regards.

**Comment by spirogg** [comment]
@neil96 ok sent a ticket sir thanks again

**Comment by spirogg** [comment]
@neil96 ticket #140018

**Comment by neil96** [comment]
@spirogg ,

I will check the ticket soon. Thanks!

Regards.

**Comment by spirogg** [comment]
Now working. Thanks.
