### ISSUE TITLE
go to main site - then click on login or register and just click on logo see error

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1936]
@neil96 

hi when i go to my site and click on login, a popup appears i leave the popup window open and then click on my logo and the page crashes i see all of site in text

same thing if you go to site click on register and then you see the popup then dont close but just click on logo of your site and the same happens crash.. chrome browser, and firefox
wonder if this has to do with engintron for cpanel ? or can this be mod security issue, since on the forums robert had said there are some issues with mod security ON and phpfox ? just wondering

**Comment by neil96** [comment]
Hi @spirogg ,

If the mod_security is OFF, does it happen?

Regards.

**Comment by spirogg** [comment]
@neil96 it was enginetron nginx. When I turn it off. It doesn't  do that. When it's enabled it does.

**Comment by spirogg** [comment]
Is there a way to have nginx setup on server with cpanel / whm on vps and not be a plugin or will cpanel cause an issue to nginx configuration Everytime you update cpanel ? I see your demo site works well with nginx and does not create any issue like this. ?

**Comment by neil96** [comment]
Hi @spirogg ,

I can't reproduce my our server. Could I test on your site?

Regards.

**Comment by spirogg** [comment]
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/1939
the issue was engintron but i still have the issue above in the link.. 1939
i can ope support ticket again and give you details for my server login etc to check both out if you can that would be great.. enginetron for cpanel is in whm left side all the way down under plugins im sure you know just fyi thanks
spiro i will reference this post in support ticket

thanks

**Comment by spirogg** [comment]
i put a ticket in #619874 with login info to server etc
