### ISSUE TITLE
Websocket Issue in chat applications

### ISSUE THREAD

**Issue by sanjosedennis7593** [PHPfox-Official/phpfox-v4-issues#1937]
Hi,

I'm currently have a websocket issue in my web applications. I integrated YouNetChat in my phpfox application, however it only display in the chat frame a message "Unable to connect to chat. Check your Internet connection."

I check it in the console, it shows an error message "WebSocket connection to 'ws://127.0.0.1:9009/chat' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET"

Does anybody encounter this in younetchat ?

**Comment by neil96** [comment]
Hi @sanjosedennis7593 ,

Here only for phpFox core bug tracker. For 3rd-party apps, please get in touch with developers to help.

Regards.
