### ISSUE TITLE
Design does not allow me to change colors gives error when publish

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1939]
Design
((You can easily change the color palette of your site by selecting the colors you want for specific elements. These elements are unique to a theme and designers can provide you with countless ways of managing your site's design without the need to know CSS or HTML. Changes you make are previewed live and you simply need to hit Publish once you are happy with your work.)) 

this does not work for me ? 4.5.2 ( latest chrome browser, will test firefox edge and report back
<<EDIT same thing on latest firefox & edge browsers >>

 i get error or i can not select the little square box.. and when i hit publish i see all text on my screen 
![crashed-all-test](https://cloud.githubusercontent.com/assets/17736688/25833575/ea76b2ce-3437-11e7-81af-4f0715a0812b.GIF)
Also i cant click back.... its stuck there.... I have to refresh page or publish and then hit back button
![cant click back either stuck here](https://cloud.githubusercontent.com/assets/17736688/25833668/b21999b8-3438-11e7-9e09-bf7b0fcc328a.GIF)

**Comment by spirogg** [comment]
PS   I did not have mod security on and enginetron nginx was disabled  php 7 centos 7.3.  this still happening. Just for FYI.

**Comment by neil96** [comment]
Hi @spirogg ,

I can't reproduce with steps you gave. Tested on php 7 both on centos and ubuntu.

Regards.

**Comment by spirogg** [comment]
@neil96 hi put support ticket in just now 619874

**Comment by spirogg** [comment]
@neil96 has login to server cpanel and site

**Comment by neil96** [comment]
The same with #1940
