### ISSUE TITLE
Other users image as profile image

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1941]
after checking this issue https://github.com/PHPfox-Official/phpfox-v4-issues/issues/1940 i have found out that i am able to click on the button to make this image my profile image. you can see the pic on my profile but i have not uploaded any photos yet, is this by design or a bug?

**Comment by Scheinwelt-Media** [comment]
btw on my site (4.5.2) there is no issue with photos...

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

Yes, that's our design. 

Regards.
