### ISSUE TITLE
Manage friends not showing correct count. 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1942]
Hi it shows I am friends with 6 people the one photo shows steviepx as my friend but does not show up when I go to manage friends it only shows 5 friends ? Is this a bug ? 
![screenshot_20170512-104422](https://cloud.githubusercontent.com/assets/17736688/26006706/0e7b2182-3703-11e7-80c9-c62bf3f803ed.png)
![screenshot_20170512-104559](https://cloud.githubusercontent.com/assets/17736688/26006713/155b3226-3703-11e7-99bf-67584d09d107.png)

**Comment by spirogg** [comment]
@neil96  PS i have same server username and passwords that i sent in last ticket, so if you ever need to login to check something even for another bug please help yourself to trying it out on mine 💯

**Comment by spirogg** [comment]
@neil96 if user is not verified , ( user never verified email ) is that  why it doesn't show up in my friends list ?

if so this is not a bug ? I dont want to verify the user on my own so how can i see if this is it ?

**Comment by neil96** [comment]
Hi @spirogg ,

We are discussing with team about this issue. We will update the status to you soon.

Regards.
