### ISSUE TITLE
Trends No tags have been found. Hashtags Trend Block not working on your site

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1943]
@neil96 
I keep adding #phpfox as a hashtag and it seems it never works. see on your demo also i added the hashtag in a number of places and click in it, it shows related to tag but the Trend Block shows no tags have been found ? 
Trends
No tags have been found.

------------------------------------------------------------------------------------------------------
![hastag-trend-not-working](https://cloud.githubusercontent.com/assets/17736688/26022514/1bb408cc-376d-11e7-9d99-31c80c4d5135.GIF)

**Comment by neil96** [comment]
Hi @spirogg ,

There are two main settings control this block:
- **Cache** (*Define how long we should cache tag clouds that are displayed on sections that use them.  Note that this setting must be defined in minutes. It is important to cache tag clouds as this removes a query to the database that can be rather memory extensive.*): Default 180 minutes.
- **Days a Tag Can Trend** (*Define how many days a tag can trend.*): Default 7 days.

Now the tag **phpfox** is displayed in *Trends* block.

Regards.

**Comment by spirogg** [comment]
@neil96  my settings are as shown in photos, but still not working ?

thanks

![tag-settings](https://cloud.githubusercontent.com/assets/17736688/26036792/829fa56c-38aa-11e7-8e8e-cdb18850b22d.GIF)
![tag-settings2](https://cloud.githubusercontent.com/assets/17736688/26036793/82a03176-38aa-11e7-96d8-bb4ed79d12a2.GIF)

**Comment by spirogg** [comment]
@neil96  should the last Enable Hashtags be set to YES or NO ?

thanks
