### ISSUE TITLE
New video app. Meta keyword not showing @neil96 please read further

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1945]
Hi it says that keyword and description is edited in phrases. When I set keywords It doesn't work..
only description works.. 
**Also is there a way to add different title for videos ? it seems video takes the same title as main site other than <title> Videos - the rest is from main site title.. also its on all the links blog photo polls events music etc.. maybe we can have a spot to change each title also better for SEO**

title>Videos - Latinos Online | Latino - Hispanic Social Community. Meet Latino Singles, Friends and Family from around the world. Create & Share Latino photos, music, videos, events, pages, groups, plus </title>
				<meta name="description" content="latin videos, latina videos, latino videos, hispanic videos - Watch - Listen to Latin Music Videos - Share your videos with friends, family, " />
		<meta name="robots" content="index,follow" />
		<meta name="keywords" content="meet latino singles, hispanic singles, Latino Social Community, Hispanic Social Community, Latino dating, Latina dating, Latino singles, Latino personals
![description](https://cloud.githubusercontent.com/assets/17736688/26037353/d4cbac58-38b6-11e7-925f-c8500cb6297b.GIF)
![keywords](https://cloud.githubusercontent.com/assets/17736688/26037356/dc1016c0-38b6-11e7-979b-5bc05cab750a.GIF)

**Comment by spirogg** [comment]
<meta name="description" content="latin videos, latina videos, latino videos, hispanic videos - Watch - Listen to Latin Music Videos - Share your videos with friends, family" />

**Comment by neil96** [comment]
Hi @spirogg ,

Both `video_meta_description` and `video_meta_keywords` are working as I checked. It might be cache issue. Please check again. These are some suggestions for you:
- Clear you cache
- The phrases are edited and the language package you are using.

For option to allow ** title**, we do not support it by default. But you can request us [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.

**Comment by spirogg** [comment]
Ok thanks. I turned off. Keycdn and it works. Tha ks.

**Comment by spirogg** [comment]
@neil96 hi just thought i would add if you remove meta tag keywords in settings>>site settings 
then the video keywords work sir.. I thought it was working and closed this request, but noticed when i add keywords in site settings it reverts back to the wrong keywords..

 i just removed the meta keywords from site settings and it shows the correct keywords for video app, but when i add keywords in that area it doesn't work.. it shows the keywords in the site settings.

 please check my site.  it says its suppose to take meta keywords from other apps instead but it didn't work, i cleared cache also using main language phrase..
![note-if - remove this-then it works](https://cloud.githubusercontent.com/assets/17736688/26041495/f44a6e7a-38f2-11e7-9fb2-bc3eb653388d.GIF)

**Comment by spirogg** [comment]
Enter the meta keywords for all pages. These are used by search engines to index your pages with more relevance. 


this below seems not to work for me sir ??

**Note that certain modules or pages have their own meta keyword settings and if those are set they will override this setting.**

**Comment by spirogg** [comment]
meta name="description" content="latin videos, latina videos, latino videos, hispanic videos - Watch - Listen to Latin Music Videos - Share your videos with friends, family, " />
		<meta name="robots" content="index,follow" />

**these are not the keywords below i have in the phrase area for video app sir ??**

		<meta name="keywords" content="meet latino singles, hispanic singles, Latino Social Community, Hispanic Social Community, Latino dating, Latina dating, Latino singles, Latino personals, Latino personal ads, Latino dating service, Latino matchmaking, Create, Share, photos, music, videos, events, pages, groups, quizzes, polls, Mexico, Puerto Rico, Cuba

**Comment by spirogg** [comment]
<meta name="keywords" content="meet latino singles, hispanic singles, Latino Social Community, Hispanic Social Community, Latino dating, Latina dating, Latino singles, Latino personals, Latino personal ads, Latino dating service, Latino matchmaking, Create, Share, photos, music, videos, events, pages, groups, quizzes, polls, Mexico, Puerto Rico, Cuba

**Comment by neil96** [comment]
Hi @spirogg ,

The setting mete keyword apply for index video page, in video detail, we use title for video detail.

Regards.
