### ISSUE TITLE
Videos that were stuck in convert process and were fixed have no description ??

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1946]
hi, when i first installed the new video app and went to convert old videos i had issue where they were not showing and stuck at 220 videos converting.. 

then i put in a ticket to fix this issue and you guys did, but i just noticed, none of the descriptions saved ? 

so all the prior videos do not have any descriptions underneath the actual video just the title of the video.. ? 

**if you need to take a look all I just updated cpanel, I misspelled username but now username and passwords are correct in prior ticket ##619874**

if you search for: Alejandro Fernández -
you will see 2 videos one from today just now and one from april 16, the one i just added now has a description the other has no description under it. 

wonder if there is a way to find the description for all those other videos or is it gone for each video ?

thanks sorry just noticed this

**Comment by neil96** [comment]
Hi @spirogg ,

I checked on your site, but I see everything is OK! Could you give me detail video url is not correct.

Regards.

**Comment by spirogg** [comment]
Missing decription for YouTube videos. Under the Facebook email etc. Share buttons there should be detail of description. That's what's missing from April 16 and before  videos . The description. If you add new video from you tube it adds description. Well the videos from April 16 and before don't have any description. They are missing that.

**Comment by neil96** [comment]
I see your oldest video on "**May 1, 2017**" and it has description.

**Comment by spirogg** [comment]
sorry ive been sick a little with a head cold. :(  but here are the photos so you an understand what i mean
![description](https://cloud.githubusercontent.com/assets/17736688/26186082/a015a07c-3b54-11e7-9913-180f67f586eb.GIF)
![no description1](https://cloud.githubusercontent.com/assets/17736688/26186096/b1bb365c-3b54-11e7-9df3-dde0d85ffa03.GIF)
![no-description](https://cloud.githubusercontent.com/assets/17736688/26186095/b1baf21e-3b54-11e7-9006-d84253eca57a.GIF)

**Comment by neil96** [comment]
Hi spirogg,

I check see them in your site, but our script can't control if you or your users update the description.

Regards.

**Comment by spirogg** [comment]
Ok when I added the YouTube videos they all had descriptions. I never changed description. All videos that we put back after they were stuck in processing. Ended up with no description in them. No one changed anything. Just FYI.
