### ISSUE TITLE
special characters in video app <title>Jesse &amp; Joy - &quot;Me Soltaste&quot; (Video Oficial) - 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#1947]
this is link, title and description from youtube video that I uploaded to my site.
when i look at title and description in view source it is not correct, seems we have bug with special characters 
**here is title and description of video 
Jesse & Joy - "Me Soltaste" (Video Oficial)**

is there a way to fix this maybe utf8 ? or another one for special characters for seo ? 

shows like this below in link, title and description

Chrome browser
video/play/181/jesse-joy-quot-me-soltaste-quot-video-oficial/
<title>Jesse &amp; Joy - &quot;Me Soltaste&quot; (Video Oficial) -
<meta name="description" content="Jesse & Joy - &quot;Me Soltaste&quot; (Video Oficial)" />

Opera browser
video/play/181/jesse-joy-quot-me-soltaste-quot-video-oficial/
<title>Jesse &amp; Joy - &quot;Me Soltaste&quot; (Video Oficial) -
<meta name="description" content="Jesse & Joy - &quot;Me Soltaste&quot; (Video Oficial)" />

Firefox Browser
<title>Jesse &amp; Joy - &quot;Me Soltaste&quot; (Video Oficial) -
<meta name="description" content="Jesse & Joy - &quot;Me Soltaste&quot; (Video Oficial)" />

Edge Browser
<title>Jesse &amp; Joy - &quot;Me Soltaste&quot; (Video Oficial) -
<meta name="description" content="Jesse & Joy - &quot;Me Soltaste&quot; (Video Oficial)" />

**same thing on all browsers**

**we need a fix for better SEO title descriptions and video links**

@neil96 Thanks for all your hard work  and thanks to rest of PHPFOX TEAM.. 
you are all my heros.
 you have a solid program that rocks ( just thought i would be honest) 💯 

sincerely Spirogg

**Comment by spirogg** [comment]
possible in database mysql
 set to utf8_general_ci 

this was a fix for another video script that had errors with special characters that i had last year, 
but not sure how you have mysql database setup and where to try and change in phpfox database ?

 just trying to help if any help at all :)

**Comment by spirogg** [comment]
any way to strip some characters : &  " " quotes and others from title and description, so if we have john & "steve",  it will just put  yoursite.tld/video/298/john-steve in link and john steve in title and description

**Comment by neil96** [comment]
Hi @spirogg ,

I tested with some video with utf-8 title, but I can't reproduce. Are you upgrade to latest version of video?

Regards.

**Comment by spirogg** [comment]
Yes. I just clicked on video again and I believe in installed. ?? I'm I doing it correct. Admincp then apps. Find video app and GET that should upgrade video app correct.

**Comment by spirogg** [comment]
If you put "" "" quotes in title 

so upload a video and name it 

my ""test"" video. 

The ""test""  part of the title will be 
Yoursite/video/234/my-quot-test-quot-video
It should strip the "" quot 

and just be 

Yoursite/video/234/my-test-video 

Link and title and I believe description all need to strip out the "" qout so it just says the words my test video.

**Comment by neil96** [comment]
Thank @spirogg ,

We confirmed this is an enhancement.

Regards.
