### ISSUE TITLE
Translate 

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1949]
Hi

Some words do not have an equivalent to translate this phrase.

Look and add these variables.

![1](https://cloud.githubusercontent.com/assets/11414490/26169564/6e4892e0-3b3e-11e7-965c-c9d338f440e2.jpg)

![2](https://cloud.githubusercontent.com/assets/11414490/26169618/b969d6da-3b3e-11e7-8c2d-ca37495182e2.png)
![3](https://cloud.githubusercontent.com/assets/11414490/26169728/0741a374-3b3f-11e7-9460-238075bf96ff.png)

**Comment by neil96** [comment]
Hi @CimborNet ,

I conformed the phrase in first image (_Search_) is not translated.

The phrase **am** in second and last image is translated with var_name _am_

Regards.

**Comment by CimborNet** [comment]
ok!
Cool!
Tnx

But... look this one too....
![1](https://cloud.githubusercontent.com/assets/11414490/26268191/5dff8356-3cee-11e7-86f0-a50c708855d9.jpg)

**Comment by CimborNet** [comment]
and next one..
![22232342323](https://cloud.githubusercontent.com/assets/11414490/26277666/63498750-3d8c-11e7-9f6c-90139af124e7.jpg)

**Comment by CimborNet** [comment]
And some one...
![1](https://cloud.githubusercontent.com/assets/11414490/26459004/46ee04ae-4175-11e7-923a-b47e158f5558.jpg)

**Comment by CimborNet** [comment]
neil96 ! ITS COOL var_name am

I HAVE IT, BUT IN VIDEO MODULE IN NOT TRANSLATED. WHY? MAY BE IN TEMPLATE THIS VAR IS NOT PRESENT IN MODULE VIDEO

**Comment by neil96** [comment]
Hi @CimborNet ,

Please post 1 issue per request. Please move recently posts to new issue. Thanks! 

P.S: You can read our policy about post issue [here](https://github.com/PHPfox-Official/phpfox-v4-issues).

Regards.
