### ISSUE TITLE
Facebook Embed Video Portrait screen Problem

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1951]
video Embed Link Facebook Video > Then Post In Status bar > Video Posted >  If Video captured in landscape its shows Good Result > If Video Captured In Portrait way Then not coming proper way

**Comment by SalmanKhan86** [comment]
![screenshot_1495730525000](https://cloud.githubusercontent.com/assets/13433124/26442945/32e152c0-4154-11e7-8dc0-6cf431df6fe4.png)

**Comment by neil96** [comment]
Can't reproduce on latest version of Video. Please test again on latest version
