### ISSUE TITLE
Music Player Views problem

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1953]
i upload mp3 music and i continue press play button again and again its views are continue increasing

**Comment by SalmanKhan86** [comment]
![screenshot_1495730773000](https://cloud.githubusercontent.com/assets/13433124/26443204/0ba45094-4155-11e7-9ec9-16a4573bde4f.png)

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,

After checked with the team, the team confirmed it's working as our designed. Each time you click to play button, it reloads the music and number of plays will count up.

Regards.
