### ISSUE TITLE
Location is not displayed 

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1956]
Location is not displayed when we move the mouse over the name or avatar of the user.

![untitled-2](https://cloud.githubusercontent.com/assets/11414490/26461425/60f9be80-417d-11e7-8b76-139c92c50632.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/11414490/26461429/6431c9f8-417d-11e7-84a7-86f73f7b4217.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

In the hover popup, it shows birth of day, not the state. Please check again.

Regards.

**Comment by CimborNet** [comment]
Sorry and Tnx!
