### ISSUE TITLE
Ads goes inactive 

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#1957]
When you create an ad in better ads, it will show up for  while but when you come back, the ad is inactive.

**Comment by neil96** [comment]
Hi @erick260 ,

Does that ad use up its resource (enough number of views/clicks).

Regards.

**Comment by erick260** [comment]
No, on my live site, when i create an ad in better ads,the ad is set to unlimited. when i come back to my site that ad complain is inactive.

**Comment by neil96** [comment]
Hi @erick260 ,

Creating ad with unlimited resource only available in AdminCP. Does your ad create in adminCP?

Please also check your " Ad Placement" is still active.

Regards.
