### ISSUE TITLE
Translate (part 1 of ~) user_group_title

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1959]
Hi

When you hover your mouse over the user's name, the translation of his group in the cyrillic language is not displayed correctly.

Just look on pic and html tag "A HREF TITLE"  in code.

user_group_title
![untitled-2](https://cloud.githubusercontent.com/assets/11414490/26519912/114d1cd6-42c9-11e7-8115-d778116398f3.jpg)

The same problem was once used with categories.
But you successfully fixed it.
Correct it, too.

**Comment by neil96** [comment]
Hi @CimborNet 

Could you clear cache and try again. Or give us more information to reproduce this.

Regards.

**Comment by CimborNet** [comment]
Hi

When viewing user information, the group is displayed correctly.
But when you hover the mouse in his name near his photo - the variable is displayed and not its value.
![untitled-222](https://cloud.githubusercontent.com/assets/11414490/26552361/16068842-4487-11e7-8cb2-930de758e0ab.jpg)


This applies only to those groups for whom the translation is made.

If you do not make a translation for the group, the variable is not created and the user group is displayed correctly.

I certainly cleaned the cache.
