### ISSUE TITLE
Users search in AdminCP

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1960]
1. Copy the username completely.
2. We paste into the search field by name or e-mail
3. Press the search button
4. There is no result!

Why?
![untitled-4](https://cloud.githubusercontent.com/assets/11414490/26519984/74ff2fca-42ca-11e7-92dd-b3de0d409de3.png)
![untitled-6](https://cloud.githubusercontent.com/assets/11414490/26519988/79535362-42ca-11e7-8156-feda13393e17.png)

P.S.
Full or partial email search works fine.

It seems to me that this is due to a different approach in the code for storing and searching for users with non English characters.

I have described this before. When the database stores the cyrillic records one in the UTF-8 encoding and the others in the ASCII. but already converted before save to db PHP HTMLENCODE function.

-----------------------------------

Guys!

Your project is very cool! REALLY very cool and I'm in every way ready to support it!

But...
  You need to eliminate errors with non-English characters. Refuse to convert all applicable characters to HTML entities. Keep not English characters in the database exclusively in UTF-8 and use MBSTRING to work with such characters!

Dushan

**Comment by neil96** [comment]
Hi @CimborNet 

**User Name** and **Name** are separate field, and that search form does not support search **username**. Please check again.

> Copy the username completely.
> We paste into the search field by name or e-mail

Regards.

**Comment by CimborNet** [comment]
In the list of users that AdminCP displays to me, I only see the "DISPLAY NAME"

Copy this text and paste into search field (box) and press enter.

Zero results.

What should I put in the search field? 

Where do I get this "User Name" and where is this "Name"?

To dig in the database every time?

**Comment by neil96** [comment]
Hi @CimborNet ,

phpFox support: full name, first name and last name. Base on your settings, **Display name** will be changed. In the search form, we have **keyword** form in both back-end and front-end.

FYI, phpFox support search user with utf-8 language. The search is case sensitive with utf-8 language but is not case sensitive with English.

Regards.
