### ISSUE TITLE
Millions tons of letters.

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1961]
Guys! I have a fast growing network.
And this is bad for sending mail and notifications to my mail server.

Millions of notifications with user actions are sent by the mail server, which has a bad effect on his reputation.

Users block and mark these emails as spam, although this is not spam. This is a notification from the mail server about what do or like their friends on the site.
When such actions of users for a day hundreds or thousands - millions of letters are sent from the mail server to all friends and their friends.

I'm afraid that because of so many letters, my mail will be blocked not only by users but also by other postal services such as GMAIL and others.

Is it possible to disable by default for all new and existing users the distribution of letters and notifications about their actions on the network?
![untitled-8](https://cloud.githubusercontent.com/assets/11414490/26520344/dcad476e-42d0-11e7-8792-76935b94dfd7.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

For feature request issue, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
