### ISSUE TITLE
Change Cover	Photo for Users by Administrator

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1966]
Why does not the administrator of the network have the ability to edit, change the position or delete the user-created cover photo for his profile?

I do not have anywhere such an option that would enable / disable it. If it is, then why is it not enabled by default for root?

It often happens that a new user can not or does not understand how to install/moving posions a cover photo on the his profile and asks to do it for him. 

But even I, having the rights of an administrator on the site, I can not edit his profile cover.

Even when editing users on AdminCP, there is an option to change their avatar (Profile picture) but there is no way to change or delete their profile cover photo.

Why?

Users profiles.....
![untitled-16](https://cloud.githubusercontent.com/assets/11414490/26520569/9eebcb9e-42d5-11e7-9432-07ee9052907b.jpg)

My profile....  (Im administrator)
![untitled-18](https://cloud.githubusercontent.com/assets/11414490/26520571/a1ebf2b0-42d5-11e7-9b7a-f6b0db03b3c4.jpg)

![untitled-20](https://cloud.githubusercontent.com/assets/11414490/26520587/2ce1c642-42d6-11e7-8f0f-72cd6ec59152.jpg)

For example, the administrator has the ability to edit or change the cover for groups and pages. But for the user profile there is no such possibility.
![untitled-22](https://cloud.githubusercontent.com/assets/11414490/26520653/0ae90b4e-42d7-11e7-9026-10b9dd72c8cc.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

For feature request issue, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
