### ISSUE TITLE
Redirect after login

### ISSUE THREAD

**Issue by makfoulie** [PHPfox-Official/phpfox-v4-issues#1968]
Hello,

The redirect after login doesn't work if you sign in with url yoursite.com/login.
If you sign in with the login prompt from core index visitor when you clic login, it works fine. but if you use yoursite.com/login url, you are redirected to your user profile.

Tested on V4.5 build 3.

Regards.

**Comment by neil96** [comment]
Hi @makfoulie ,

Our latest version is 4.5.2b1. Please test on latest version. Thanks!

Regards.
