### ISSUE TITLE
Tagged in a link

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#1969]
When a user is tagged in a link he gets the notification phrase "{full_name} tagged you in a link." E.g. "user A tagged you in a link. " but user A is the owner of the post not the user who has tagged. The picture is right but the users name is wrong...

In the notification email everything is fine.

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

As I tested, user does not receive email or notification when someone tag he/she in the link.

Regards.

**Comment by Scheinwelt-Media** [comment]
hey @neil96, on my site (4.5.2) they get notified. how did you test?

**Comment by SalmanKhan86** [comment]
yes it will be notified
