### ISSUE TITLE
Double video menu

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1970]
For some reason, after updating the video module ("Core Video App v4.5.3 Release" 07 May 2017), two menus appeared on the pages of users. And both lead to the video page!

How to remove one menu "Video"?
![untitled-3](https://cloud.githubusercontent.com/assets/11414490/26695082/d0ce581a-4709-11e7-8e53-3c35fcb6bf43.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

Do you remove file no longer used? It's a required step when install Video.

Regards.

**Comment by CimborNet** [comment]
Oh thats cool! Thank you very much. Everything worked!

The truth was for some reason to manually delete files from the server. The script wrote that it was deleted, and the files on the server remained on.

But still thanks a lot!
