### ISSUE TITLE
Photos set as Mature Content:

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#1973]
Photos or other content approved as Mature Content, cannot be unmarked as mature content by user.  Users should not be allowed to un-mark content already uploaded/approved as mature content.

**Comment by neil96** [comment]
Hi @erick260 ,

For feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new)

Regards.
