### ISSUE TITLE
group notification issue

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1974]
when someone comment on my post in group then in notification users and title not comes correct
pfa the same
![screenshot_33](https://user-images.githubusercontent.com/13433124/27181694-4b38efd8-51f6-11e7-94ae-ba93999484a2.png)

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,

I can't reproduce. Do you test on latest version?

Regards.

**Comment by SalmanKhan86** [comment]
Hello
yes i test on latest v4.5.2(build 1). i am able to reproduce it

**Comment by neil96** [comment]
Hi @SalmanKhan86 

The issue can come from 3rd-party apps, your site configurations, your site configurations,... So please give more detail. Thanks.

Regards.
