### ISSUE TITLE
mobile device icons not support in chrome

### ISSUE THREAD

**Issue by SalmanKhan86** [PHPfox-Official/phpfox-v4-issues#1975]
when we posted icon from mobile device its not display in chrome browser. now days everyone posted icons with status update.this is big problem pls resolve it soon
icon posted from mobile device:-
![screenshot_2017-06-16-11-18-15](https://user-images.githubusercontent.com/13433124/27213882-1abafa04-5287-11e7-8cbc-1732905d5628.png)
display properly in Firefox:-
![icom suppoort firefox](https://user-images.githubusercontent.com/13433124/27213904-2e067d4a-5287-11e7-9995-a62c4a1fc55d.png)
chrome problem:-
![icon not support in chrome](https://user-images.githubusercontent.com/13433124/27213911-356e1200-5287-11e7-8bc6-0c9291394e1c.png)

**Comment by SalmanKhan86** [comment]
icon display in twitter **very popular feature among users**:-
![icon in twitter](https://user-images.githubusercontent.com/13433124/27214135-7a6211e4-5288-11e7-9236-b1184af5e397.png)

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,
I can't reproduce. It shows normally on my side (Chrome Version 58.0.3029.110 (64-bit) - MacOS).
<img width="559" alt="screen shot 2017-06-16 at 13 39 33" src="https://user-images.githubusercontent.com/15936115/27214975-7051d28c-5299-11e7-997d-801db8f88cee.png">
Regards.

**Comment by SalmanKhan86** [comment]
hello

i am using Window OS

**Comment by SalmanKhan86** [comment]
@neil96 can u check it on Window OS

**Comment by SalmanKhan86** [comment]
@neil96 Any update on this

**Comment by neil96** [comment]
Hi @SalmanKhan86 ,

As I checked, these icons come from mobile. Each device has their own icon, we can't support all of them.

Regards.
