### ISSUE TITLE
Wider frame when selecting

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1976]
Hi

It would be nice if you could expand the frame for selecting categories.

When 5 categories - everything is fine. When 10 can also be tolerated.

But if more than 10 - then each time you need to do this long scrolling!

I understand that I can change CSS, but with each update I will have to make a tone of changes to the standard theme. And I want to have good functionality from the box.

![untitled-2](https://user-images.githubusercontent.com/11414490/27260043-4b1c9f3a-5422-11e7-98a0-30f92a5a9387.jpg)

And this applies to all pages where there is a choice of category for editing!

**Comment by neil96** [comment]
Hi @CimborNet 
For feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new)
Regards.
Neil.
