### ISSUE TITLE
admincp > pages does not load the complete code to be edited

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1977]
When editing a page, it does not load the complete code to be edited.

**Comment by neil96** [comment]
Hi @prepperz ,

Could you give us more information.

Regards.

**Comment by prepperz** [comment]
One example: http://prntscr.com/flj438

Another example: http://prntscr.com/flj7bm

**Comment by prepperz** [comment]
If I create a new page and add some snippet of code it will be able to retrieve as normal. So somewhere in between something is happening. Just to be sure I also looked on my development site and it seem the issue also occurs there as well. So it is only affecting previous creating. On the front end the page is served up fine, but when you go to edit it, it doesn't load the complete snippet of code.

**Comment by neil96** [comment]
Hi @prepperz ,

I tested with these cases that you gave, everything is OK. Are you using latest version?

Regards.

**Comment by prepperz** [comment]
Yes it's the latest. You make a new page everything works fine. It's when previous created pages that have been there for a while.

**Comment by neil96** [comment]
Hi @prepperz ,
I tested with that case, but I still can't reproduce.

Regards.

**Comment by prepperz** [comment]
Somehow the db is getting corrupted (and it is it in a production environment as well as the developemnt environment, what are the odds that this issue occuring in both environments?), in older versions of phpfox there used to be a DB repair tool in the admincp. This isn't avaible in v4.x.x.

**Comment by prepperz** [comment]
Basically, "phpfox_pages_text" gets corrupted in the DB.

**Comment by prepperz** [comment]
So basically, "phpfox_page_text" gets corrupted in the DB.

**Comment by prepperz** [comment]
So here is what we found out after Robert's investigation. This was a bug in the core script prior to v4.5.2. So any pages that was enter prior to v4.5.2 would have this issue and would not be able to load the full source of the page even with the updated fix. So, the page would have to be deleted or updated with original source since it is unable to retrieve the original source from the database.
