### ISSUE TITLE
Featured video shows  two different view stats

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1978]
The same Featured video from pages shows different view stats between the right side and one displayed on the left. when viewed on the main list of videos, but when it is clicked on it show the correct stats.

**Comment by neil96** [comment]
Hi @prepperz ,

Could you tell us more detail. Thanks!

Regards.

**Comment by prepperz** [comment]
http://prntscr.com/fltsk5

**Comment by neil96** [comment]
Hi @prepperz 

I still can't understand the issue with the screenshot you that you gave.

Regards.

**Comment by prepperz** [comment]
See the view stats? This is a video from pages that has been featured that also shows on the main video section. The video on the left and right is one in the same. The view stats should match but it doesn't.

**Comment by prepperz** [comment]
v4.5.3 stil has this issue in the video section. If you look at at the video in the featured column on the right, that same video added by the same user on the left side will show two different view stats between the featured column and the same video that is displayed on the left of the featured column.
