### ISSUE TITLE
video in pages status shows double description and "view more"

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1979]
See screenshot attached.
![screenshot1](https://user-images.githubusercontent.com/19594886/27510823-04fdce60-58e7-11e7-9591-e3b442a30a9e.png)

![screenshot2](https://user-images.githubusercontent.com/19594886/27510845-47bb5c72-58e7-11e7-920b-b4b7e80a6a35.png)

**Comment by neil96** [comment]
Hi @prepperz 
I can't reproduce on latest version of Video App. 
Did you test on latest version of Video?

Regards.

**Comment by prepperz** [comment]
Yes it's the latest version

**Comment by neil96** [comment]
Hi,
I approved your video and it works.

Regards.

**Comment by prepperz** [comment]
So when I clicked the link it says page not found:  

Your video has been approved on phpFox Demo.nnTo view this video, follow the link below:n https://v4.phpfox.com/video/333/cambodia’s-hollywood-dad-scott-neeson-from-hollywood-highs-to-cambodia’s-sl/ .

**Comment by prepperz** [comment]
Also, no it doesn't work properly and the bug is still there. See screen shot.
![2017_06_25_22_31_41_social_networking_community](https://user-images.githubusercontent.com/19594886/27522791-9e949d14-59f6-11e7-9df2-a83f0553d1dd.png)
