### ISSUE TITLE
Notification displays  {{ users }} instead of display name

### ISSUE THREAD

**Issue by Candrom87** [PHPfox-Official/phpfox-v4-issues#1980]
Sometimes content of notifications show incorrect output.

![capture](https://user-images.githubusercontent.com/26220448/27633787-edf4c88c-5c00-11e7-8453-9d8c3a48e0b2.PNG)

This problem is also present in some notifications send via mail:

" {{ full_name }} commented on one of {{ gender }} own comments on the group "{{ title }}". To see the comment thread, follow the link: {{ link }}

Kind Regards,
xxx"

**Comment by neil96** [comment]
Hi @Candrom87 ,

I can't reproduce. It might be your site is missing phrase. Please "Run Find Missing Phrases" in AdminCP >> Language and click to the left of the default English language to run this. 
 ![Find missing phrase](https://docs.phpfox.com/download/attachments/852020/find%20phrases.png)

Regards.

**Comment by Candrom87** [comment]
I did do run "Find Missing Phrases". Problem still present:

![stillcapture](https://user-images.githubusercontent.com/26220448/27697293-15880ab4-5cf4-11e7-8d7a-f758251c0d80.PNG)
