### ISSUE TITLE
Lots of inbound messages  to admin hangs message access via message icon

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1986]
When there are tons of messages, clicking on the message icon on the upper right fails to open the message window and just hangs.

**Comment by neil96** [comment]
Hi @prepperz ,

How many messages do you have?

Regards.

**Comment by prepperz** [comment]
Don't know. Lots msgs and thousands of comments.

**Comment by prepperz** [comment]
Now users are reporting this issue as well: "I can't get my PM's. I have the notifications at the top, but I can't open it."

**Comment by neil96** [comment]
Sorry @prepperz ,

I can't reproduce due to your information very generally.

Regards.

**Comment by prepperz** [comment]
![screenshot](https://user-images.githubusercontent.com/19594886/28059112-13187bfa-65f1-11e7-9f26-fcd89319190f.png)

**Comment by prepperz** [comment]
Sheinwelt-media said, "i had the same problem with an earlier version of phpfox and solved it by marking the messages of that user read via /mail or checking the database for unsupported characters on the messages and delete or exchange it. what language do you use?"

**Comment by neil96** [comment]
Hi @prepperz ,

> i had the same problem with an earlier version of phpfox and solved it by marking the messages of that user read via /mail or checking the database for unsupported characters on the messages and delete or exchange it. what language do you use?

It was fixed.

Regards.

**Comment by prepperz** [comment]
Ok. Cool. I have access to mail with the suggested link. yoursite.com/index.php/mail 

Marking off all the messages didn't help. Same blank pop-up.

However, I was able to access mail via the message icon from another account with only 1 or 2 inbox messages. Also there is no option to delete messages, only archive.

Accounts with lots of messages will not be able to access their messages using the message icon from the upper right corn.

The phpfox message system really needs an overhaul.
