### ISSUE TITLE
Add cover image via selecting photos does nothing in pages.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#1989]
Add cover image via selecting photos does nothing in pages.

**Comment by neil96** [comment]
Hi @prepperz ,
Please give us more information. It works on my side.

Regards.

**Comment by prepperz** [comment]
It does not. I just tried it on the demo.

Steps.
1. goto page
2. add cover
3. choose from photo
4. select photo

All it does is takes you to the photo. It doesn't add it as a cover.

**Comment by neil96** [comment]
Hi @prepperz ,

After select a photo, you can make it as cover photo in action menu. It's our workflow. I confirmed this flow is not good, we will improve it in next versions.

Regards.
