### ISSUE TITLE
PhpFox 4.5.2 - Impossible to edit and delete event

### ISSUE THREAD

**Issue by Amagio** [PHPfox-Official/phpfox-v4-issues#1992]
I have seen this bug after upgrading from 4.5.1 to 4.5.2. Maybe it was existing before, I don't know, because I use Event app seldom. Also, I must notice, that upgrading from 4.5.1 to 4.5.2 I didn't know I have to turn off all third party addons, plugins and themes. When upraging, all 3rd party soft was turned on. Nevertheless, upgrading was successful and I would never find any issues, if not trying to create the sample event one day. Now, I can create event. However, when I try to edit or to delete it, I see white screen. I tried to Rebuild Core Theme and clear cash, but in vain. This bug still remains on my site. Please, tell me, where can I find a mistake or is it a bug?
![111](https://user-images.githubusercontent.com/30136728/28149639-c25aa21a-67c1-11e7-82a8-5ae040c53ac4.png)
![222](https://user-images.githubusercontent.com/30136728/28149640-c25b8b8a-67c1-11e7-8e06-c5561788a86e.png)

**Comment by neil96** [comment]
Hi @Amagio ,

I can't reproduce. Could you give us more information. 
It might be your site/server configuration.

Regards.

**Comment by Amagio** [comment]
Hi, Neil!

My site is on shared hosting, no VPS. Here is shared server configuration.

URL: http://victoree.ru
Server Overview
Core Version: 4.5.2(build 1)	
PHP Version: 5.6.29	
PHP Sapi: litespeed
PHP safe_mode: False
PHP open_basedir: False
PHP Disabled Functions: None
PHP Loaded Extensions: Core date ereg libxml openssl pcre sqlite3 zlib bcmath bz2 calendar ctype curl dom enchant hash fileinfo filter ftp gd gettext SPL iconv session intl json mbstring mcrypt standard mysqlnd mysqli mysql Phar posix pspell Reflection imap SimpleXML soap sockets exif tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip litespeed PDO pdo_mysql imagick timezonedb ionCube Loader SourceGuardian Zend OPcache
Operating System: Linux
Server Time Stamp: July 14, 2017, 2:04 am (GMT)
GZIP: Enabled
SQL Driver Version: MySQL 5.6.35
SQL Slave Enabled: No
SQL Total Slaves: N/A
SQL Slave Server: N/A
Memory Limit: 0.5 b (-1)
Load Balancing Enabled: No
Total Server Memory: 96416 MB
Available Server Memory: 2056 MB
Current Server Load: 8.58 

I could give you admin access to check it, but in personal message only.

**Comment by neil96** [comment]
Hi @Amagio ,

We can reproduce on your site via ticket system. Could you check again on latest phpFox and Event app. Thanks!

Regards.
