### ISSUE TITLE
STATUS SHARE BOX limitations

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-issues#1993]
to keep people engaged is the ultimate thing a social community site wants ,
phpfox has very limited things to share from status share box .
WE CAN only share normal text,photo,video or checkin ( one thing at a time ).
see what rival softwares have got : http://prntscr.com/fv8ndx   ,http://prntscr.com/fv8o1i
Hoping for some improvements in next version

**Comment by neil96** [comment]
Hi @shashankguitarist ,

Here is bug tracker only, for feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
