### ISSUE TITLE
control shortcuts/menus in AdminCP

### ISSUE THREAD

**Issue by shashankguitarist** [PHPfox-Official/phpfox-v4-issues#1994]
every admin will need the ability to add/remove some links/shortcuts like , "Create a Page" ,"Upload a Video" , "Upgrade your account" , " Items in your cart" etc  HERE http://prntscr.com/fv8ppb  .
It should be a core feature , please consider this and implement in the core code or as an app asap

**Comment by neil96** [comment]
Hi @shashankguitarist ,

Here is bug tracker only, for feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
