### ISSUE TITLE
Two clicks to launch one music

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1995]
It is very inconvenient, when to listen to music it is necessary two times in two different places to press the button "Play"

![untitled-3](https://user-images.githubusercontent.com/11414490/28225999-ce2ae82a-68d4-11e7-821f-5f374ae44331.jpg)

And also inconvenient that the player does not appear above the name of the song, but on the top of the list. And it seems that this is the player for the first song on the list!

![untitled-4](https://user-images.githubusercontent.com/11414490/28226000-ce2e79fe-68d4-11e7-9f7d-5293e7bba322.png)

**Comment by neil96** [comment]
Hi @CimborNet ,
I can't reproduce this. Please give us more information.
> It is very inconvenient, when to listen to music it is necessary two times in two different places to press the button "Play"

For feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).
> And also inconvenient that the player does not appear above the name of the song, but on the top of the list. And it seems that this is the player for the first song on the list!

Regards.

**Comment by CimborNet** [comment]
In the page https://v4.phpfox.com/music/ must two clicks (steps) to start play musics! Check.

![untitled-3](https://user-images.githubusercontent.com/11414490/28371150-7619714e-6c9c-11e7-9fbb-b6109fd6daf7.jpg)
![untitled-4](https://user-images.githubusercontent.com/11414490/28371151-761c12fa-6c9c-11e7-973a-3869dd6ec244.jpg)
![untitled-5](https://user-images.githubusercontent.com/11414490/28371152-7622cad2-6c9c-11e7-9ef7-38f71919d5a6.jpg)

**Comment by neil96** [comment]
Hi @CimborNet 

This feature is now available on new music app.

Regards.
