### ISSUE TITLE
Stretched avatar image in QUIZ

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#1996]
When displaying user results, their avatars are distorted (stretched) disproportionately.

Icon size in HTML is 50x50 - everything is correct!

But the image itself (natural size) is cut off incorrectly (not proportionally) 50x37, 50x27, and so on.

One side is always 50 pixels, and the other is always less than 50 pixels.

![untitled-1](https://user-images.githubusercontent.com/11414490/28228899-bbb8181e-68e0-11e7-8a90-c3e742056ba6.jpg)
![untitled-2](https://user-images.githubusercontent.com/11414490/28228900-bbd4232e-68e0-11e7-9ba4-a6a5bf19e440.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

I tested on v4.phpfox.com and my testing site but I can't reproduce.

Regards.
