### ISSUE TITLE
Admin CP missing navigation

### ISSUE THREAD

**Issue by Silkonchord** [PHPfox-Official/phpfox-v4-issues#1997]
![navmissing](https://user-images.githubusercontent.com/30218665/28251214-97328442-6a35-11e7-8827-a38d91c00f04.png)
Hello,

I've installed V4.5.2 as per installation document @ https://docs.phpfox.com/display/FOX4MAN/Installing+phpFox
Also ensure server meet all the requirements via the phpfox.php script etc.
However in my AdminCP, the following TOOLS options are missing and I don't know if this is a change from v4.4.0 build 1 to v4.5.2:

Missing Navigation from TOOLS:
Modules
Announcements
Newsletter

Am reluctant to do proceed with customisation and installation of third party products until this is clarified.  Also the installation document seem to be out of date as I don't get from the webinstaller, trial, developer o premium options.

Has anyone experience this missing navigation items in admincp please?

Many Thanks

**Comment by neil96** [comment]
Hi @Silkonchord ,

We merged the "Modules" to "Apps". The "Announcements" and "Newsletter" is moved to "Apps" too. 

Regards.
