### ISSUE TITLE
Administrator account

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-issues#1998]
On version: 4.5.2(build 1)
 On my site, i am owner- Administrator,I have made another account an Administrator - saved it. Then i tried to edit it again (the same account), and it wouldent let me. I get "You are unable to edit a site administrators account."

**Comment by Erick000** [comment]
theres no way for me to remove it as admin now gggrr

**Comment by neil96** [comment]
Hi @Erick000 ,

It's working as our designed. However, from 4.5.3 we allow administrator edit an administrator.

Regards.
