### ISSUE TITLE
join via facebook

### ISSUE THREAD

**Issue by Erick000** [PHPfox-Official/phpfox-v4-issues#1999]
4.5.2(build 1)
   for members that join with facebook sign ups have login/access issues...  these members cannot sign in, due to their membership be changing on its own. When we place them back in normal user group, and tell them to try again, i refresh the page and that membership lvl is now blank again. 
![admin cp browse users 19social com](https://user-images.githubusercontent.com/29802466/28257224-fc5946ec-6a7d-11e7-97ad-85ec79c6df53.png)

**Comment by neil96** [comment]
Hi @Erick000 ,

By default, membership of user signup via facebook is registered user.

Regards.

**Comment by Erick000** [comment]
Yes, when they join via facebook they are placed in registered user, but when they sign in, it wont let them, then you go to admincp, users, and you'll see that user mebership level is blank..

**Comment by Erick000** [comment]
i have removed all bans, and user promotions...   for accounts that join via facebook, and try to sign in, will get this issue...  i keep adding, and adding that user to the same usergroup (Registered user) and try to sign in again, it wont let me, and the membership goes back to where it was. Blank..

**Comment by Erick000** [comment]
i got tired of just doing the same thing over, and over, so i made the account an admin, and the account was able to sign in like normal. then i made the account a member again, an got the same issue.

**Comment by neil96** [comment]
Hi @Erick000 ,

I have just tested again and still can't reproduce. Please give us more information. Thanks!

Regards.
