### ISSUE TITLE
Event Problem without CKEditor

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2000]
I don't want to use CKEditor on my website that's why I'm facing a problem on my Event.
If you not use a CKEditor your all Event description text is merging together. 

I disable my event app because of this problem and I hope this is going to fix on the next build.

**Comment by neil96** [comment]
Hi @juniortimeline ,

Could you explain for us more detail.

Regards.

**Comment by juniortimeline** [comment]
Hi @neil96 
It's easy. Just disable CKEditor and create a new Event with description and you will see that the all text is merge together without any </br> like what you did on the description box
