### ISSUE TITLE
Gaining Activity Points for Like, Read, and Follow

### ISSUE THREAD

**Issue by Promastertr** [PHPfox-Official/phpfox-v4-issues#2001]
Üyelerin Sitedeki daha aktif olmasını sağlamak için, Etkinlik Puanlarını görüntülendikleri, okudukları ve paylaşıldıklarında izledikleri için kazanmalarına izin verilmelidir. Bu Sayede Üyeler sevdirmek, okumak ya da izlemek için Çaba harcarlar. Kaliteli paylar alacaktır.

**Comment by Promastertr** [comment]
To ensure that members are more active on the Site, they should be allowed to earn Activity Points as they are viewed, read, and watched as they are shared. In this Sayede Members will spend Effort to get liked, read or watched. It will make quality Shares.

**Comment by neil96** [comment]
Hi @Promastertr ,

For feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
