### ISSUE TITLE
 Event and SCHEMA.ORG structured data

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2002]
On Google structured data testing tool we have 

2 ERRORS
5 WARNINGS

Please check and repaire/
Thanks

![untitled-5](https://user-images.githubusercontent.com/11414490/28495013-28840498-6f40-11e7-885b-96735099d1bf.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

phpFox does not support itemprop anymore. They will be removed in next versions. For now, please ignore it.

Thanks for reported.

Regards.
