### ISSUE TITLE
Captcha failed-Password request

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2004]
on my site, i've changed my main admin password to make it stronger, now i have a problem with it, now i'm locked out...   WHen i use the forgot password tool, i get "Captcha failed. Please try again." The Captcha dont even appear, so i cannot change my password due to that...  
   I though about another way of doing it though the myphpadmin in server end..   i got to phpfox-users- found my admin account changed the password. tired to log into site, and it did not work? 

    Can you pleaseeee help e get my password fixed? 

  
![password request 19social com](https://user-images.githubusercontent.com/19263189/29185385-e9fd9bc6-7dbd-11e7-8583-bec4d022b970.png)

**Comment by neil96** [comment]
Hi @erick260 ,

I can't reproduce this issue on phpFox 4.5.2. What phpFox version, captcha type are you using?

If you'd like to reset your password quicker, please submit a ticket [here](https://clients.phpfox.com/submitticket.php) with your site information.

Regards.

**Comment by maishtuluva** [comment]
so any user registered in php fox which we have hosted will not be able to reset password??
