### ISSUE TITLE
The Default Setting for the Menu

### ISSUE THREAD

**Issue by ubuntume** [PHPfox-Official/phpfox-v4-issues#2006]
I don't like the whitespace when the menu is hidden. I've worked around it with css, but it would be great to have the entire menu div removed when the switch is set to hid.

The flush page with header menu is better design and should be optional.

**Comment by neil96** [comment]
Hi @ubuntume ,

For feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
