### ISSUE TITLE
Youtube Problem (v4.5.3)

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2010]
![yt](https://user-images.githubusercontent.com/16037019/29942446-8d081472-8e9e-11e7-9674-89810ffe5090.jpg)

Did not detect Youtube Video Title and Description.

**Comment by neil96** [comment]
Hi @juniortimeline,

You are sharing a status, not a video.

Regards.

**Comment by neil96** [comment]
Hi @juniortimeline ,

Youtube have upgraded their website, so our code does not work anymore. We will improve our code soon.

Regards.

**Comment by juniortimeline** [comment]
@neil96 Thank You so much

**Comment by juniortimeline** [comment]
Hi @neil96 our live site not very friendly to use about this sharing youtube issue. Starting I create this "issue" and till now we need to wait a long days and month to use a fix version of voutube problem. You guys know that 4.6.0 making a long test from development test to beta to rc and stable and like me I'm not decide quickly to upgrade my site to 4.6.0 and It means this problem is stable on my live site. People don't like to write them again the title and description of their video on my site if they can share easily to another social media site. and that is the reason why people starting to stay away. Please understand that sometime we need to give a simple satisfaction our registered user. Thank You guys.

**Comment by neil96** [comment]
Hi @juniortimeline ,

I understand your situation. However, the root cause of this issue come from YouTube side (they upgraded their website). We have to update our library to get title and description YouTube. The library is used anywhere in core the 3rd-party apps. So we put the fix on 4.6.0. Please understand our situation too.

Regards.
