### ISSUE TITLE
v4.5.3 no longer shows Youtube cover image when adding vdeos

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2011]
![screenshot](https://user-images.githubusercontent.com/19594886/29996347-17865726-8fcb-11e7-8c35-2bc30dc3611b.png)

**Comment by neil96** [comment]
Hi @prepperz ,

It works on my side. Are you using latest version of video?

Regards.

**Comment by prepperz** [comment]
yes. I am, Here. try approving this video. https://v4.phpfox.com/video/play/414/youtube/

**Comment by neil96** [comment]
Hi @prepperz ,

I approved your video. The thumbnail photo is showing normally.

Regards.

**Comment by prepperz** [comment]
Hmm... I try to install the video app again and see it solves it.

**Comment by prepperz** [comment]
OK. Seem reinstalling it resolved the issue.
