### ISSUE TITLE
group cover photo

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2012]
in a group clicking on "Add a Cover"->"Choose From Photos" i am not able to add a photo. when a photo is selected i can only delete it...

**Comment by neil96** [comment]
Sorry @Scheinwelt-Media , I made a mistake here. We have to select and click to a photo, then in the photo detail, we can select that photo as the cover photo of pages/groups.

Regards.

**Comment by Scheinwelt-Media** [comment]
ok neil, i have found it thanks...
