### ISSUE TITLE
Try again in 1 minute

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#2013]
When I try to create new page or a group, I get notice "Try again in 1 minute."
Was told that it will be fixed in 4.5.3 but the the problem still exists...

**Comment by neil96** [comment]
Hi @djafrika ,

Could you wait for 10 seconds before creating new group?

Regards.

**Comment by djafrika** [comment]
??? Are you being sarcastic or what?
I waited 2 months... As I was told it will be fixed... If it's not a bug, can you tell me what is causing this error notice?
To quote Robert: 

> -> We have checked and there is a issue with the Core script. We will fix it in the next version 4.5.3. Thanks for your report.

**Comment by djafrika** [comment]
Btw, only I as admin get this notice. Other users can create pages normally... Is there some kind of limit?

**Comment by neil96** [comment]
Hi @djafrika ,

This action prevents spam on your site. Any users can't create two pages/groups within 10 seconds.  If you always get this issue, it can be your database does not valid. There is a pages/groups have "created time" greater than the current time. You can manually check your database in table phpfox_pages, field time_stamp, if there are any rows have a value greater than 1504601180 (UTC timestamp at this comment), please correct them (you can edit timestamp to 1504601180).

If you'd like us check this issue for you, please [submit a ticket](https://clients.phpfox.com/submitticket.php).

Regards.

**Comment by djafrika** [comment]
Thank you...
