### ISSUE TITLE
Forum error 500

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#2014]
When click on any post on forum, I get error 500...

**Comment by neil96** [comment]
Hi @djafrika ,

I can't reproduce on my side. Could you [create a ticket](https://clients.phpfox.com/submitticket.php) if you'd like us reproduce on your site.

Regards.

**Comment by djafrika** [comment]
I could, but since others have same problem, isn't it better to post solution so others can see it?

**Comment by neil96** [comment]
Hi @djafrika,

Could you try again with phpFox 4.5.2b2. 

Regards.

**Comment by djafrika** [comment]
Works with 4.5.2b2
