### ISSUE TITLE
Hashtag / Trends Problem

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2015]
![hashtag](https://user-images.githubusercontent.com/16037019/30395695-bc1eef5c-98cf-11e7-9dbe-3c075a9584cd.jpg)

I have fresh install 4.5.3 and I found some code automatically appear on my trends block.
This screen shot is from pfphox demo site and the tag display that I highlight is not a post.
Some phrase include # is appearing on the trends block.

**Comment by neil96** [comment]
Hi @juniortimeline ,

What are the codes automatically appear in your site? I tested with fresh install 4.5.3, but can't reproduce.

On your demo, the hash tag code should be `#1` (don't have html tag), we will improve this feature in next versions of phpFox.

Regards,
Neil.

**Comment by juniortimeline** [comment]
@neil96 Sorry about the other codes I show it to you. I found that this problem is coming while my Note 3rd party app is enable. But the #1 should be fix on the future. Thank You
