### ISSUE TITLE
New Music App Photo Problem

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2017]
Hi, Thank You so much for the new music stand alone app and I love the new concept. But need to update the music thumbnail image. The image too much low quality if you are using a mobile device and I have I can disable the attachment and ckeditor on music setting to avoid the non proper looks on tje news feed and the music page. Thank You

![screenshot_2017-09-20-21-13-50](https://user-images.githubusercontent.com/16037019/30660153-6b027446-9dec-11e7-9ab0-5871316ea04a.png)

**Comment by neil96** [comment]
Hi @juniortimeline ,

Thank for reporting, we will improve this on Music 4.6.0

Regards.
