### ISSUE TITLE
Site notifications instantly gone

### ISSUE THREAD

**Issue by Candrom87** [PHPfox-Official/phpfox-v4-issues#2018]
Upon mentioning user "B", user "B" either does not get a site-notification or the bell indicator only briefly appears.
E-mail notifications for mentioning work fine.

**Comment by neil96** [comment]
Hi @Candrom87 ,

Where do you mention a user?

Regards.

**Comment by Candrom87** [comment]
Hello, on wall entries for example!

**Comment by neil96** [comment]
Hi @Candrom87 ,

It works on my side. Are you using latest version (4.5.3)?

Regards.

**Comment by Candrom87** [comment]
Yes using latest version. I just comment on any entry like this: @username and I get an instant notification via mail on the mentioned account. Checking the site, with the mentioned account, I see the red indicator on the bell, clicking on it it disappears and I see no notification.

If that user would not have turned on e-mail notification, it would be impossible to see where he was mentioned.

**Comment by neil96** [comment]
Hi @Candrom87 

The notification does not disappear. You can test on [our demo](https://v4.phpfox.com/) to see this.

Regards.

**Comment by Candrom87** [comment]
Hi @neil96 

I just tested again. On normal status updates it works fine. It only seems to happen on certain feed entries such as "User X has added new photo album" or on "User X has shared a video". If commenting on these items with @username I get the notification problems mentioned above.

I also tested by disabling all custom apps to isolate the issue, it is still present.

If you'd like to test it on our site, please let me know.

**Comment by neil96** [comment]
Hi @Candrom87 ,

I can reproduce when comment of a video feed only.

Regards.

**Comment by Candrom87** [comment]
Hi @neil96 ,

It happens in comments of video feed items & the feed entry when a new photo album has been created! 
Please have a look on our site, in the feed there is the following entry: "Glenn Charpantier added new photo album "My Quads" " tagging people in comments in this feed has the same problem with notifications disappearing.

Regards,
Glenn
