### ISSUE TITLE
Music App Version: 4.5.3p1

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2020]
Hi, just only 30 songs per album? There is no option how many songs users can upload each album and how many album users can create. Thanks

**Comment by neil96** [comment]
Hi @juniortimeline 

I have uploaded an album with 40 songs. Could you try again.

Regards.

**Comment by juniortimeline** [comment]
Still I can upload only 10 songs. I'm still searching about this problem because of maybe I need something to add a module on my nginx. I already add "max_file_uploads = 50" on my php.ini but this problem still exist on my site. Thanks @neil96

**Comment by neil96** [comment]
Thanks for you reply @juniortimeline ,

I tested with many servers and all work fine. If you'd like we check on your server, please [submit a ticket](https://clients.phpfox.com/submitticket.php) with these information:
- Your server information 
- phpFox admin account
- Link of this issue

Regards.
