### ISSUE TITLE
plugins cant run after flushing the cache

### ISSUE THREAD

**Issue by Farid-Najafloo** [PHPfox-Official/phpfox-v4-issues#2021]
after below line plugins can't run any more because the cached file no longer exist.
\PF.Base\module\admincp\include\service\module\process.class.php:327
`
           $this->cache()->remove();
`

call stack

```
4
Phpfox_Cache_Storage_File remove
…\module\admincp\include\service\module\process.class.php:327
3
Admincp_Service_Module_Process updateActivity
\PF.Src\Core\App.php:144
2
Core\App __construct
…\include\init.inc.php:270
1
 include
…\start.php:82
0
 require
index.php:9
```

**Comment by neil96** [comment]
Hi @Farid-Najafloo ,

What phpFox version are you using?  As I checked on phpFox 4.5.3b2, `\PF.Base\module\admincp\include\service\module\process.class.php:327` isn't `$this->cache()->remove();`

Btw, The cache will be generated automatically if it can't be found.

Regards.

**Comment by Farid-Najafloo** [comment]
i'm using phpfox 4.5.1
thanks

**Comment by neil96** [comment]
Hi @Farid-Najafloo 
Could you test on latest version (phpFox 4.5.3b2). Thanks
Regards.
