### ISSUE TITLE
CRITICAL multi language issue

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2022]
I have some multilingual content with special characters like as https://en.wikipedia.org/wiki/German_orthography

But when i enable Redis and Memcache support for cache i got sembols on database like �

**Comment by neil96** [comment]
Hi @Ylmzef ,

Could you give us more information. I copied all contents from that wiki and paste to the blog, everything OK. I copy some special characters to blog and user status, everything OK too.

I am using phpFox 4.5.3b2 and Redis.

Regards.

**Comment by Ylmzef** [comment]
Move back to file system the cache engine please

**Comment by neil96** [comment]
Sorry @Ylmzef  I do not understand you :(

**Comment by neil96** [comment]
Hi @Ylmzef 
It might be the same with this issue #2030. Could you take a look it. Thanks!

Regards.
