### ISSUE TITLE
PAGES - Maybe remove integrated item menu issue.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#2025]
Just install latest pages app and under Manage Integrated Items.  It listed:
Blog
Coupon
Business Directory
Advance Events
Forum
Photos
Click them all to off (and it worked awesome!!)
Then went back to page and it still shows Advance Marketplace.  Not sure if it is a phpfox issue or a YouNet issue.  Will check out the database and hack something for a quick fix :)

**Comment by neil96** [comment]
Hi @PhpFoxJohnJr ,

Can you explain more clearly to us? Thanks!

Regards.

**Comment by neil96** [comment]
Hi @PhpFoxJohnJr ,

I don't "Advance marketplace" supports integrate with pages/groups or not. If it supports but the menu is not display, it's app issue.

Regards.
