### ISSUE TITLE
Blackberry users cannot verify gmail email link when registering

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2027]
Blackberry users cannot verify gmail email link when registering

**Comment by neil96** [comment]
Hi @prepperz ,

Do you mean: users use Blackberry phone? Blackberry isn't listed in [device and browser support](https://docs.phpfox.com/display/FOX4MAN/Supported+Browsers+and+Devices)

Regards.

**Comment by prepperz** [comment]
Yes the blackberry phone

**Comment by neil96** [comment]
Hi @prepperz  BlackBerry isn't included in our device list.
