### ISSUE TITLE
custom field update

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2029]
when i add an extra option to a existing custom field it is not saved after clicking update.

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

It's working on my test. Could you give us more information.

Thanks!

**Comment by Scheinwelt-Media** [comment]
i can reproduce this with the following steps:

1. add a custom field with radio buttons and add option 1

2. go to custom fields and edit
![custom1](https://user-images.githubusercontent.com/13225682/31752713-a5b6cdc4-b48c-11e7-90e8-1f657d02e3c3.jpg)

3. add option 2
![custom2](https://user-images.githubusercontent.com/13225682/31752724-b411d45e-b48c-11e7-8177-66a5433776db.jpg)

4. click on update
![custom3](https://user-images.githubusercontent.com/13225682/31752736-bf45ba34-b48c-11e7-97f9-c94bae668590.jpg)

option 2 is now gone
