### ISSUE TITLE
language breaks script

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2030]
a client asked me for help because the register page showed errors in the console when using his french language pack. i found out that he uses a phrase in terms with a ' symbol that breaks the code. after changing the phrase the error (Uncaught SyntaxError: missing ) after argument list) was gone. unfortunately i can not reproduce the issue on my dev server but it was there.

**Comment by Scheinwelt-Media** [comment]
i found out that the error was caused by line 21 in user/template/default/controller/register.html.php but still not able to reproduce.

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

All texts/phrases added from phpFox are formatted to a unify standard. If the texts/phrases are inserted or modified directly in the database or from a tool, then there may be errors, in this case, should delete or modify again with phpFox form. If you are sure that the texts/phrases are added with phpFox form, please provide more information to us.

Regards.

**Comment by Scheinwelt-Media** [comment]
i dont know how the text was added. maybe from the french language pack. will the phrase be formatted when importing language... could this cause the error? then i would understand why i can not reproduce it. only tested with phrase manager...

**Comment by Scheinwelt-Media** [comment]
the issue comes up when importing language with ' symbol. i can now reproduce it:

![register1](https://user-images.githubusercontent.com/13225682/31753189-6f566c46-b48f-11e7-927d-17cd5ecd5068.jpg)

![register2](https://user-images.githubusercontent.com/13225682/31753196-72b2a814-b48f-11e7-9f1d-104486655520.jpg)
