### ISSUE TITLE
Cannot delete messages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2032]
This is a major issues and will deter people from wanting people to buy phpfox software or people from using the site. Users cannot delete messages and no option to delete messages from the admin panel.

**Comment by neil96** [comment]
Hi @prepperz ,

Users can't delete messages, but users can archive  messages. We will consider add this feature in next versions. 

Regards.

**Comment by PhpFoxJohnJr** [comment]
Legally the way it is set up now is correct as you know facebook keeps every post you every make whether you delete it or not.  But I can understand why some sites might want this :)
