### ISSUE TITLE
There are no new feeds to view at this time.

### ISSUE THREAD

**Issue by Silkonchord** [PHPfox-Official/phpfox-v4-issues#2033]
Hello,

Where do I find the display setting to change this please? 

My display feed setting is not showing older post, need to fix this with some urgency.

Kind regards

Dean

**Comment by neil96** [comment]
Hi @Silkonchord ,

This message will be shown if there is no more feed. Could you explain us which error here?

Regards.

**Comment by Silkonchord** [comment]
Hi,

It's not showing errors as such, it's more what it is supposed to do and NOT doing.

On my profile page, I have post only upto the 21st October.

Then on the index page I have post that goes back for 3 month and these post are not showing on my profile.  Other members are also reporting the same problem

Please please help.

Dean

**Comment by neil96** [comment]
Hi @Silkonchord ,

It works on my side. Could you give us more information.

Regards.

**Comment by Silkonchord** [comment]
test

**Comment by Silkonchord** [comment]
Hello,

The first image contains the last post to show on my profile page.  

![my profile page nonewfeed](https://user-images.githubusercontent.com/30218665/31924889-e55d872a-b841-11e7-978e-4c3737f7efe9.jpg)

But below here on the index page, I have older posts that goes on for 3 months, but there not appearing on my profile page wall???


![oct21](https://user-images.githubusercontent.com/30218665/31924896-ef0084a8-b841-11e7-8547-db9bd6173f9f.jpg)
![oct9](https://user-images.githubusercontent.com/30218665/31924897-ef301470-b841-11e7-9166-9522568803f0.jpg)
![oct18](https://user-images.githubusercontent.com/30218665/31924898-ef5f0690-b841-11e7-9a8e-d6e2a4683bee.jpg)
![oct18b](https://user-images.githubusercontent.com/30218665/31924902-f1f6b6b4-b841-11e7-9a9e-682f039c1953.jpg)

Kind Regards

Dean

**Comment by neil96** [comment]
Hi @Silkonchord ,

We use ajax to load older feeds, if there is an error via this ajax request, old feeds can't be loaded.  Could you open console log and copy all errors and paste here.

Thanks!
