### ISSUE TITLE
v4.5.3 b2 Fresh install Fail Test on php7, centos 7

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2035]
V4.5.3 b2 failed. I then tested v4.5.2 and it installed without any issues at all.

The the complete error log showed the following:

mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required '/home/mytx/public_html/PF.Base/file/settings/license.php' (include_path='.:/opt/remi/php70/root/usr/share/pear:/opt/remi/php70/root/usr/share/php:/usr/share/pear:/usr/share/php') in /home/mytx/public_html/PF.Base/install/include/installer.class.php on line 1177, referer: http://mytx.com/`

**Comment by neil96** [comment]
Hi @prepperz ,

On phpFox 4.5.3b2, if you install fail, it will display a page with all logs. Could you copy and paste here. Thanks!

Regards.

**Comment by prepperz** [comment]
if memory serves, the log only mentioned something about a new install and nothing else so I just deleted everything and installed v4.5.2

**Comment by prepperz** [comment]
So here is the current result of upgrading from v4.5.2 to v4.5.3 b2. Fail.
![phpfox1](https://user-images.githubusercontent.com/19594886/32062292-15ac53b4-ba42-11e7-9588-69ae153fc277.png)

![phpfox2](https://user-images.githubusercontent.com/19594886/32062304-1df32840-ba42-11e7-98d4-749de8da5110.png)

**Comment by prepperz** [comment]
Tried a test upgrade from v4.5.2 to v4.5.3 b2 and got the following:

`            
Installation New PhpFox Site
running step: completed.install_app_core_groups
error level 512
[512] Missing Param: [db][port] (/home/mypresidiotx/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99]
Stack trace:
#0 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error(Missing Param: [db][port], 512)
#1 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/setting/setting.class.php(495): Phpfox_Error::trigger(Missing Param: [db][port])
#2 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(315): Phpfox_Setting->getParam(Array, )
#3 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/database/database.class.php(80): Phpfox::getParam(Array)
#4 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/database/database.class.php(104): Phpfox_Database->__construct()
#5 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/locale/locale.class.php(55): Phpfox_Database::instance()
#6 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/phpfox/support.php(132): Phpfox_Locale->__construct()
#7 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/phpfox/support.php(75): Phpfox_Service_Container->build(locale)
#8 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(405): Phpfox_Service_Container->get(locale)
#9 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/locale/locale.class.php(122): Phpfox::getLib(locale)
#10 /home/mypresidiotx/public_html/PF.Src/Core/Phrase.php(38): Phpfox_Locale::instance()
#11 /home/mypresidiotx/public_html/PF.Src/Core/Lib.php(24): Core\Phrase->__construct()
#12 /home/mypresidiotx/public_html/PF.Base/start.php(177): Core\Lib::phrase()
#13 /home/mypresidiotx/public_html/PF.Site/Apps/core-groups/Install.php(45): _p(Groups)
#14 /home/mypresidiotx/public_html/PF.Src/Core/App/App.php(237): Apps\PHPfox_Groups\Install->setName()
#15 /home/mypresidiotx/public_html/PF.Src/Core/Lib.php(358): Core\App\App->__construct()
#16 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(2285): Core\Lib::appInit(PHPfox_Groups)
#17 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(2455): Phpfox_Installer->subStepCompleteInstallApp(PHPfox_Groups, Installing Emoticon, completed.install_app_twemoji)
#18 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(2538): Phpfox_Installer->_processSubStep(Array)
#19 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(357): Phpfox_Installer->_completed()
#20 /home/mypresidiotx/public_html/PF.Base/include/init.inc.php(251): Phpfox_Installer->run()
#21 /home/mypresidiotx/public_html/PF.Base/start.php(84): include(/home/mypresidiotx/public_html/PF.Base/include/init.inc.php)
#22 /home/mypresidiotx/public_html/index.php(9): require(/home/mypresidiotx/public_html/PF.Base/start.php)
#23 {main}

Error: Call to undefined function mysql_connect() in /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/database/driver/mysql.class.php:681
Stack trace:
#0 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/database/driver/mysql.class.php(85): Phpfox_Database_Driver_Mysql->_connect('localhost', '', '', false, false)
#1 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/database/database.class.php(80): Phpfox_Database_Driver_Mysql->connect('localhost', '', '', '', false)
#2 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/database/database.class.php(104): Phpfox_Database->__construct()
#3 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/locale/locale.class.php(55): Phpfox_Database::instance()
#4 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/phpfox/support.php(132): Phpfox_Locale->__construct()
#5 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/phpfox/support.php(75): Phpfox_Service_Container->build('locale')
#6 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(405): Phpfox_Service_Container->get('locale')
#7 /home/mypresidiotx/public_html/PF.Base/include/library/phpfox/locale/locale.class.php(122): Phpfox::getLib('locale')
#8 /home/mypresidiotx/public_html/PF.Src/Core/Phrase.php(38): Phpfox_Locale::instance()
#9 /home/mypresidiotx/public_html/PF.Src/Core/Lib.php(24): Core\Phrase->__construct()
#10 /home/mypresidiotx/public_html/PF.Base/start.php(177): Core\Lib::phrase()
#11 /home/mypresidiotx/public_html/PF.Site/Apps/core-groups/Install.php(45): _p('Groups')
#12 /home/mypresidiotx/public_html/PF.Src/Core/App/App.php(237): Apps\PHPfox_Groups\Install->setName()
#13 /home/mypresidiotx/public_html/PF.Src/Core/Lib.php(358): Core\App\App->__construct()
#14 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(2285): Core\Lib::appInit('PHPfox_Groups')
#15 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(2455): Phpfox_Installer->subStepCompleteInstallApp('PHPfox_Groups', 'Installing Emot...', 'completed.insta...')
#16 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(2538): Phpfox_Installer->_processSubStep(Array)
#17 /home/mypresidiotx/public_html/PF.Base/install/include/installer.class.php(357): Phpfox_Installer->_completed()
#18 /home/mypresidiotx/public_html/PF.Base/include/init.inc.php(251): Phpfox_Installer->run()
#19 /home/mypresidiotx/public_html/PF.Base/start.php(84): include('/home/mypresidi...')
#20 /home/mypresidiotx/public_html/index.php(9): require('/home/mypresidi...')
#21 {main}
Stack trace:
#0 (unknown file)(0): Phpfox_Installer->exceptionHandler(Error)
#1 {main}`

**Comment by neil96** [comment]
Hi @prepperz 

> require(/home/mypresidiotx/public_html/PF.Base/vendor/composer/../symfony/polyfill-intl-normalizer/bootstrap.php): failed to open stream: No such file or directory in 

=> It seems you upload missing file. You can upload the zip file, then unzip on server to be sure all files are uploaded.

> Error: Call to undefined function mysql_connect()
You are missing php mysql extension. Could you double check it.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Prepperz,  

Just FYI... I also have Centos 7.4 and PHP 7.0.24.
Did two fresh install with no issues.

**Comment by prepperz** [comment]
Hmmm. I downloaded the latest zipped file again. Uploaded and tested 4 times. Same result. I will download the file from phpfox and try again just in case.

@PhpFoxJohnJr which version did you do a fresh install?

**Comment by PhpFoxJohnJr** [comment]
4.5.3(bulid 2)
php 7.0.24
MySQL 5.5.56-MariaDB 

I had issues with php 7.1 in the previous version with my YouNet theme so I moved back to 7.0.24.  They said it was fixed but I have not tried it yet.

**Comment by neil96** [comment]
Dear all,

We tested with php 7.0 and php 7.1 without any issues. Please be sure your server is configured properly.

Regards.

**Comment by prepperz** [comment]
checked the requirements, all passed. 
![requirementchk](https://user-images.githubusercontent.com/19594886/32117280-cae9073e-bb1b-11e7-99f6-074715545880.png)
tried another test install and failed. After entering the the license and db info and submitting it, it just gets a blank screen. The funny thing is I can can install v4.5.2 just fine.

**Comment by prepperz** [comment]
I spun up a VS on the production server and v4.5.3 b2 install with no issues. So, something is amiss with the test server.

**Comment by neil96** [comment]
Hi @prepperz ,

We can check this issue on your server if you'd [submit a ticket](https://clients.phpfox.com/submitticket.php) with your vps root account.

Thanks!

**Comment by prepperz** [comment]
@ neil96

OK I opened a ticket. Something that is intriguing is that if I upload the files into a subdirectory, it installs just fine, but not the root.
