### ISSUE TITLE
"seo_photo_meta_description" doesn't properly insert site name.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2037]
![screenshot](https://user-images.githubusercontent.com/19594886/31945870-60325b72-b89e-11e7-9d39-01027b07011c.png)

**Comment by neil96** [comment]
Hi @prepperz ,

At configuration step, we ask for this value. If you keep default, we use "Site Name".
<img width="518" alt="screen shot 2017-10-25 at 08 50 36" src="https://user-images.githubusercontent.com/15936115/31976455-dcef06d8-b961-11e7-9cf1-789b562784dd.png">

Regards.

**Comment by prepperz** [comment]
It's a bug because what ever site name you put in at configuration, it doesn't insert to it.

**Comment by PhpFoxJohnJr** [comment]
I am pretty positive that I added my site name on a fresh install and the variable listed above as well as this one (seo_blog_meta_description) both liste "Site Name" instead of my site name.

I am guessing that the under settings / site setting under Core Live is where this variable is set.
