### ISSUE TITLE
comment notification

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2038]
when a status is commented only the status owner gets notifications about comments. i need a patch for this asap.

**Comment by Scheinwelt-Media** [comment]
in user/include/service/callback.class.php on line 1140:

`if ($iUserId == $iSenderId) {
 return;
}`

commenting that out gives me back the notification for all users commenting on the same item. what is the purpose of this?

``

**Comment by neil96** [comment]
Hi @Scheinwelt-Media ,

> when a status is commented only the status owner gets notifications about comments. i need a patch for this asap.

It works in my test.


> in user/include/service/callback.class.php on line 1140:
> 
> if ($iUserId == $iSenderId) { return; }
> 
> commenting that out gives me back the notification for all users commenting on the same item but only on local server not online.
> 
> tested on local server, live site and phpfox demo.

Could you explain the detail to us this point. Thanks!

Regards.

**Comment by Scheinwelt-Media** [comment]
you can test this on the v4 live demo:

1. add a status with user A
2. with user B comment on this status
3. with user A comment on thius status
4. user B will not get a notification
