### ISSUE TITLE
v4.5.3 b3 Admin CP Grey Font on Dark Background make it difficult to see menu

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2040]
The current menu items in the control panel is difficult to see as the font doesn't contrast with the background.

**Comment by neil96** [comment]
Hi @prepperz ,

In adminCP, we use light text color on dark background. Could you show us where's the gray color. Thanks!

P.S: Please be sure you are using default theme without custom color.

Regards.

**Comment by prepperz** [comment]
The text and background doesn't really contrast and requires the eyes to do too much work just to see it.
![too-dark](https://user-images.githubusercontent.com/19594886/32206741-6341dd5e-bdcd-11e7-926d-1a736ed2c889.png)

**Comment by neil96** [comment]
Hi @prepperz ,

I feel normal and clear.

Regards.
