### ISSUE TITLE
Error creating custom fields

### ISSUE THREAD

**Issue by metall13** [PHPfox-Official/phpfox-v4-issues#2041]
Good afternoon everyone, there is an error when creating custom fields after installing the Russian language package, tried on versions of phpFox 4.5.3b2 and phpFox 4.5.2 and phpFox 4.5.2b3, on them the error is identical

![image 1](https://user-images.githubusercontent.com/33246328/32210105-eb3fbda8-be1c-11e7-911b-9849f90b3d2b.jpg)

Server Overview

Core Version:

4.5.3(build 2)

PHP Version:

7.0.16

PHP Sapi:

cgi-fcgi

PHP safe_mode:

False

PHP open_basedir:

False

PHP Disabled Functions:

None

PHP Loaded Extensions:

Core date libxml openssl pcre sqlite3 zlib bcmath bz2 calendar ctype curl dom hash fileinfo filter ftp gd gettext SPL iconv session intl json mbstring mcrypt standard mysqli mysqlnd PDO Phar posix pspell Reflection imap SimpleXML snmp soap sockets exif tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip cgi-fcgi pdo_sqlite pdo_pgsql pdo_mysql pgsql timezonedb yaml

Operating System:

Linux

Server Time Stamp:

October 27, 2017, 11:35 am (GMT)

GZIP:

Enabled

SQL Driver Version:

MySQL 5.5.51-38.2

SQL Slave Enabled:

No

SQL Total Slaves:

N/A

SQL Slave Server:

N/A

Memory Limit:

0.5 b (-1)

Load Balancing Enabled:

No

Total Server Memory:

31901 MB

Available Server Memory:

1752 MB

Current Server Load:

1.39

Google Chrome 
Версия 61.0.3163.100 (Официальная сборка), (64 бит)

**Comment by neil96** [comment]
Hi @metall13 ,

Did you fill all require fields?

Regards.

**Comment by metall13** [comment]
Yes, I can also shoot video of action logic

**Comment by metall13** [comment]
1) Installed the engine
2) I have installed a package of Russian
3) Created a group with the name in Russian and in the English language, gave the rights to custom fields
3) I add a group of fields and an error occurs

**Comment by neil96** [comment]
Hi,

I did the same these steps.

Regards.

**Comment by metall13** [comment]
https://www.youtube.com/watch?v=lltPv3gjXEg

**Comment by metall13** [comment]
In fields of naming it is necessary to write not in Latin, but in Cyrillic alphabet

**Comment by metall13** [comment]
in the English name Latin, and in Russian Cyrillic

**Comment by metall13** [comment]
https://youtu.be/tmrbATNbTVk  best quality

**Comment by neil96** [comment]
Hi @metall13 ,

I did the same steps in your video, but I can't reproduce. If you'd [submit a ticket](https://clients.phpfox.com/submitticket.php) with your site information, we will reproduce this issue on your site.

Regards.

**Comment by metall13** [comment]
The ticket was created on October 25, gave access to the admin panel and cPanel, there is still no answer

**Comment by neil96** [comment]
Hi @metall13 ,

The ticket #427180 is already answered, could you double check it. If #427180 isn't your ticket, please add new comment with this github link.

Regards.

**Comment by neil96** [comment]
Hi @metall13 ,

This is invalid configuration (hidden user group setting has invalid value) in your site only.

Regards.
