### ISSUE TITLE
group of users in Russian

### ISSUE THREAD

**Issue by metall13** [PHPfox-Official/phpfox-v4-issues#2042]
This is all the same bug if you create a group of users in Russian then it is not properly registered in the database and has consequences for it, and if I switch to English the group of users is correctly created in the database

video?)

**Comment by neil96** [comment]
Thanks @metall13 

I can reproduce this case. For now, please create new user group with English, enable user group setting "Can have special custom fields?", then translate for edit to Russian later.

Regards.
