### ISSUE TITLE
Browse Users by Last Login not working

### ISSUE THREAD

**Issue by queenmother305** [PHPfox-Official/phpfox-v4-issues#2043]
When you set the default browse results in admin for user browse to display by last login it does not. Instead it displays results  on the user browse page in reverse alphabetical order.

**Comment by neil96** [comment]
Hi @queenmother305 ,

Do you test on latest version?

Regards.

**Comment by queenmother305** [comment]
yes i am using the latest version. i have set results to be displayed by last login but if u go to my site http://tgirls.online you will see they are displayed in reverse alphabetical order. 

in previous versions of phpfox everytime a search was conducted, even with filters, the users were displayed by last login. 

this feature is not functioning properly and therefore the site does not look freshly updated when a user visits the browse user section. please fix it neil. thank you.

please also note that my site is NSFW 18+.

**Comment by neil96** [comment]
Hi @queenmother305 ,

Could you test again on phpFox 4.6.0 official. 

Thanks!
