### ISSUE TITLE
Sharing pages video main link does not properly insert meta description

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2044]
https://v4.phpfox.com/stupid-stuff/video/

![screenshot](https://user-images.githubusercontent.com/19594886/32407691-ee514054-c162-11e7-8684-637e7f351bab.png)

**Comment by neil96** [comment]
Hi @prepperz ,

Could you tell us more detail. Thanks!

Regards.
