### ISSUE TITLE
Vanity URL checking process needs modifying...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2045]
When creating a vanity url in groups and pages, checking the availability of a word automatically creates the url if the word is availible. This should not be the case. The availability of the vanity word should be checked and its availablity status shown, then the option to create or cancel the creation should be given.

**Comment by neil96** [comment]
Hi @starplan ,

This feature is working as our designed. However, I marked this issue as **Feature request**, we will  discuss with team and consider adding this feature in next versions.

If you have another feature request, please feel free adding [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new). Thanks!

Regards.
