### ISSUE TITLE
Single Device login keeps duplicating settings

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2048]
on my site 4.5.3(build 3) the single device login keeps duplicating settings. I go to Remove Duplicates-usergoup settings, and it does nothing. 

  The same settings keeps getting displayed over, and over again. 

![image](https://user-images.githubusercontent.com/19263189/32418179-b88a0908-c219-11e7-8765-1ca9f7ab983e.png)
![image](https://user-images.githubusercontent.com/19263189/32418180-bdbfabb2-c219-11e7-9f89-fc7a66f68cf9.png)

**Comment by neil96** [comment]
Duplicate with #2034
