### ISSUE TITLE
Search filter tab highlighting...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2052]
When a search is carried out you will see the results page with filter tabs on the left hand side. By default the the "All Results" tab is hightlighted. Clicking on any of the other tabs filters the search results appropriately but does not hightlight the tab that indicates what is being shown in the search results.

Could you please hightlight the tab that indicates the results being shown.

**Comment by neil96** [comment]
Thanks @starplan , we fixed this issue on 4.6.0.

Regards.
