### ISSUE TITLE
Sharing internal links to pages  on status doesn't show any thumbnail image

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2054]
Sharing internal links to pages  on status doesn't show any thumbnail image when parsing link.

**Comment by neil96** [comment]
Hi @prepperz ,

It works in my test, you can check [here](https://v4.phpfox.com/aqua/?link-id=683). Please be sure the link that you share is public and has thumbnail image.

Regards.

**Comment by prepperz** [comment]
I don't mean video links. I mean pages. 
![screenshot](https://user-images.githubusercontent.com/19594886/32715834-d3883122-c821-11e7-928c-c3648776febc.png)

**Comment by david-phpFox** [comment]
Improved in Pages/Groups 4.7.5
