### ISSUE TITLE
Cannot edit the name of usergroups

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2056]
I've tested this on version 4.5.3(build 3) & 4.6.0(dev-build) Same issue. 

  We cannot edit the name of a usergroup, when we click on Edit usergroup, it takes you to create a new usergroup Inherit a usergroup that you already have. It will not allow you too Edit a usergroup name.

**Comment by neil96** [comment]
Thanks @erick260 ,

I can't reproduce this issue on 4.5.3b3. phpFox 4.6.0dev-build is not opened for bug tracker now.

Could you double check and give us detail steps to reproduce this issue on 4.5.3b3.

Regards.
