### ISSUE TITLE
Edit Page Error

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2057]
on version 4.6.0(dev-build)
   When you click on a page, then click Edit it loads to a blank white page.

**Comment by neil96** [comment]
Thanks @erick260 ,

phpFox 4.6.0-dev-build is opened for 3rd-party check compatible. Please do not report issue for this build. The bug tracker will be opened in beta version. 

FYI, this issue is reported by our QCs and already fixed in 4.6.0.

Regards.
