### ISSUE TITLE
v4.5.3 b3  Missing 3rd colum in pages of Newly created category

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2058]
When a new category is created in v 4.5.3 b3 and when a page is added to that category, the 3rd column is missing from the the pages home pages when adding videos.

![screenshot](https://user-images.githubusercontent.com/19594886/33157499-7dacbb36-cfd0-11e7-97d1-279c81e96253.png)

**Comment by neil96** [comment]
Hi @prepperz ,

The block will be hidden if does not have data. Please double check this.

Regards.

**Comment by prepperz** [comment]
Yes. I've double checked. This is what it should look like:  
![screenshot3](https://user-images.githubusercontent.com/19594886/33160177-02d5fb76-cfe8-11e7-8ef5-8887a44d2e99.png)

Steps to reproduce:

1. Goto amincp apps > pages
2. Create a new category
3. add page and select the newly created category and complete the new page.
4. Add a video in the pages section (clicking on the 3 dots > video).

**Comment by neil96** [comment]
I still can't reproduce with these steps.

Regards.

**Comment by prepperz** [comment]
Can you create a new pages category on the demo site?

**Comment by neil96** [comment]
I did, and I removed it. Our demo is not environment for testing.

**Comment by prepperz** [comment]
then can you do it on the stage site or test site.

**Comment by neil96** [comment]
> then can you do it on the stage site or test site.

I did on my test site.

**Comment by prepperz** [comment]
Maybe we are not understanding the steps or something. It might be helpful if there was something on the phpfox side that we can test against since we can't do it on the demo.

**Comment by prepperz** [comment]
OK. I can also reproduce the issue on my test server as well (The one you installed due to the phpfox install script issue). http://mypresidiotx.com/index.php/pages/3/

**Comment by neil96** [comment]
I see all pages do not have right block. Please be sure you have enough data.

> **The block will be hidden if does not have data**

Regards.

**Comment by prepperz** [comment]
What data is it looking for specifically? Does it only reference within a particular category?

For example if category "A" has 42 pages and Category "B" has 5 page. Even tho all of are music videos, if the user views a page in category "B" would it display "likes" from category "A" also or just from "B" ?

**Comment by neil96** [comment]
Hi @prepperz ,

Could you test again on 4.6.0 official.

Regards.

**Comment by prepperz** [comment]
OK. It seems that this issue only occurs when no categories are selected. and it does the same thing with 4.6
