### ISSUE TITLE
Sharing pages on facebook does not properly insert meta

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2059]
![screenshot2](https://user-images.githubusercontent.com/19594886/33158774-f617db50-cfda-11e7-9e17-ae47c8f9363e.png)

**Comment by neil96** [comment]
Hi @prepperz 

I don't recognize the link that you shared. Is it a pages detail or a custom page?

Regards.

**Comment by prepperz** [comment]
No. it's totally stock default setup of a "pages" that was added and then using the vanity url in from the mage option.
