### ISSUE TITLE
photos on pages photo is not displayed for usergroup administrator

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2060]
to reproduce:

1. login as administrator and visit the the pages photo section. You'll notice there's no photos are displayed.

2. login as regular user or just stay logged out and visit the pages photo section again and you see there are photos displayed.

**Comment by neil96** [comment]
Hi @prepperz ,

Could you give us more information.

Thanks!

**Comment by prepperz** [comment]
Not sure how much more I can give. I will send private info via ticket for you to see.

**Comment by prepperz** [comment]
works in v4.6
