### ISSUE TITLE
No option to delete themes

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2061]
There's no option to delete themes

**Comment by neil96** [comment]
Hi @prepperz ,

You can delete a theme if it's not default theme.

<img width="262" alt="screen shot 2017-12-01 at 06 21 51" src="https://user-images.githubusercontent.com/15936115/33460292-10ffa2fa-d660-11e7-91f5-39d2dd55e5e0.png">

Regards.

**Comment by prepperz** [comment]
OK. I see it now. The whole grey text on black background make it difficult to see the menu items  in the admin cp. It should be white on black or something and maybe change colors or something during mouse-overs.
