### ISSUE TITLE
Banned members still shows their posts

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2062]
Posts from members that are banned are still visible

**Comment by neil96** [comment]
Hi @prepperz ,

Like most other platforms, we do not remove posts from banned users.

Regards.

**Comment by prepperz** [comment]
Not remove, but hide.

**Comment by neil96** [comment]
Hi @prepperz ,

In most forums, I can see the contents from the banned user normally.

Regards.
