### ISSUE TITLE
No Option to Upload Photo Contents Into Exisitng Pages Albums

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2065]
In the pages album there is no way to upload to an existing album except your own which is totally counter productive. Any member of the page should be able to upload to any album on pages.

**Comment by neil96** [comment]
Hi @prepperz ,

It's working as our designed.

Regards.

**Comment by prepperz** [comment]
It would make it more productive if it people can upload to those albums. Other wise what's the point of having a community page. Could you que this as a feature request.

**Comment by neil96** [comment]
Hi @prepperz ,

Could you help us move this to [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues). Thanks!

Regards.

**Comment by prepperz** [comment]
ok
