### ISSUE TITLE
Page with error code...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2067]
Thought I would let you known that I got an error page after clicking on "view_all_notifications" after clicking on the notifications icon ... Error code: 6d786e. I had poked someone and then received a notification.

**Comment by neil96** [comment]
Hi @starplan ,

Which version did you test? 

> Error code: 6d786e

=> Could you open file main.log and paste the error detail here? 

Regards.

**Comment by starplan** [comment]
This was on your demo site on the day of the original posting.
