### ISSUE TITLE
Green button moves...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2070]
In Forum: Clicking on General in forum... Green button with + moves position (on desktop). Moves back after clicking on post.

**Comment by neil96** [comment]
Hi @starplan ,

I do not understand this issue, could you explain more detail. Thanks!

Regards.

**Comment by starplan** [comment]
![green-button-forum](https://user-images.githubusercontent.com/17064302/34001770-cc7d93d8-e0e8-11e7-911f-960653239d1d.jpg)
![green-button-others](https://user-images.githubusercontent.com/17064302/34001771-ccec1ac4-e0e8-11e7-82ed-f806d2edc4d2.jpg)

Hopefully you'll be able to view the difference in the location of the green button in the two images above.

**Comment by neil96** [comment]
Hi @starplan ,

This is our new design. If you'd like to change, please post a new request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Thanks!
