### ISSUE TITLE
Claim page button...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2071]
Claim page button in header image - Should be three dots button with popup menu. Having the button so prominent places to much emphasis on it and detracts from the page itself. There is a claim page link on the page, which is fine. The one in header image, I believe is too much in your face.

**Comment by neil96** [comment]
Hi @starplan ,

This is our new design. If you'd like to change this, you can post a request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new). Thanks!

Regards.
