### ISSUE TITLE
Can't "View Site Layout" in admincp

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2076]
Better Ads: Add placement - The site layout does no appear when clicking on "View Site Layout" in admincp.

**Comment by neil96** [comment]
Hi @starplan ,

It works in my side. Could you give us more information.

<img width="1296" alt="screen shot 2017-12-15 at 09 05 42" src="https://user-images.githubusercontent.com/15936115/34023386-3c1a80c8-e177-11e7-9e10-5a7cc7d1f05f.png">

Regards.

**Comment by starplan** [comment]
I checked in Chrome and it appears correctly in that browser. It maybe an issue within my Firefox.

**Comment by neil96** [comment]
It works with firefox in my side.
