### ISSUE TITLE
Multi-line comments...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2080]
Added multi-line comments - field should expand better so that you can see all that you have written.

**Comment by neil96** [comment]
Hi @starplan ,

Do you mean post a new status?

Regards.

**Comment by starplan** [comment]
See image below... I know that you can see the line that you are currently typing on, it's just that I can't see the first line typed.

![mulitline](https://user-images.githubusercontent.com/17064302/34043980-1da0586a-e19b-11e7-9fc4-dd0165c242c1.jpg)

**Comment by neil96** [comment]
Thanks @starplan ,

This feature have been working this way on firefox. However, we will discuss with team and consider improving this feature.

Regards.
