### ISSUE TITLE
international currency improvement

### ISSUE THREAD

**Issue by ESA55** [PHPfox-Official/phpfox-v4-issues#2082]
Hi,

It would be nice to complete the international currency customization feature in this version 4.6.0beta1. The user needs to fill the price field in the marketplace with the new currency format.

Thanks

![currency](https://user-images.githubusercontent.com/13573330/34042344-62078cc0-e183-11e7-8e9b-b2536e5091e3.jpg)
![currency1](https://user-images.githubusercontent.com/13573330/34042345-622d5054-e183-11e7-942d-10d2cd538d7d.jpg)

**Comment by neil96** [comment]
Hi @ESA55 ,

This is not request repo. This is [the correct one](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.

**Comment by neil96** [comment]
Hi @ESA55 ,

I close this issue because it is not in the correct place. Please move this issue to request repo.

Thanks!
