### ISSUE TITLE
Material template not working 4.6.0 beta1

### ISSUE THREAD

**Issue by MeSammy** [PHPfox-Official/phpfox-v4-issues#2085]
from 4.5.3 to 4.6.0 beta1 upgrading or fresh installing with all apps material template not working. Shows only grey screen. In debug mode show cache (template file) not found.

**Comment by neil96** [comment]
Hi @MeSammy ,

From 4.6.0, developers have to define a default page in AdminCP for their app. If they do not do this, the default page shows grey screen as you can see now. We noticed this point for developers, they will update their apps soon.

Could you explain for this us this point:
>In debug mode show cache (template file) not found

Regards.

**Comment by MeSammy** [comment]
Hi @neil96 ,

As I said before in **upgrading from 4.5.3 to 4.6.0beta1,** it is working fine but when i switch template from current template to material template, it shows nothing even in debug mode. 
If I **freshly install 4.6.0beta1**, after view site show white screen and in debug mode gives error(included attachment)
Sorry, I forgot to mention that it is in the windows localhost.
I attached screenshot with this thread. Please PFA.

In debug mode shows:
![capture](https://user-images.githubusercontent.com/34576269/34402104-b98fe1bc-ebc5-11e7-90d8-76d21009cf7b.PNG)

**Comment by neil96** [comment]
Hi @MeSammy ,

We  fixed this issue on phpFox 4.6.0RC. Could you check again.

Regards.

**Comment by MeSammy** [comment]
Hi @neil96 

It is working fine now. If i find any more issue, i'll let you know...

**Comment by MeSammy** [comment]
In trending block tags are not coming...

**Comment by neil96** [comment]
Hi @MeSammy ,

Could you put new issue to another thread. It's easier to follow. Thanks!

Regards.
