### ISSUE TITLE
4.6 beta Forum Edit Title for Forums and Songs

### ISSUE THREAD

**Issue by ubuntume** [PHPfox-Official/phpfox-v4-issues#2086]
When creating a forum and making a mistake. If you go back to fix it the word it will not show changes. This also occurs for music files. If the name is 234dksdfkjsd.png and you edit it to a day in the sun, it does not change.

Plesk -
Centos -
PHP - 5.6
Modified Url Rewrite - As usual the one in admin isn't taking (no complaint) but could be wrong
SSD Cloud via GummyHost

Loving the work you guys. I have never been so happy with this script until now.

**Comment by neil96** [comment]
Thanks @ubuntume  for you report, but I can't reproduce this issue. Could you give us more information.

Regards.
