### ISSUE TITLE
Sponsored Ad doesn't pull down fully...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2087]
In a narrow window all blocks pull down except for the Sponsored Ad. As you can see in the image below. Friends and Recent Photos all pulled down fully, but the Sponsored Ad has only partially pulled down.

![ad-pull-down](https://user-images.githubusercontent.com/17064302/34065607-6e5d1ba2-e1fb-11e7-9983-ad66d7a045cd.jpg)

**Comment by neil96** [comment]
Hi @starplan ,

This is our new design. The old data might not look nice. But new data will more beautiful.

Regards.

**Comment by starplan** [comment]
Hi Neil

Advertisers are paying for their ads to be shown, I can't understand how it would acceptable to them to only show half of their ad... Could you explain the strategy please?

**Comment by neil96** [comment]
Hi @starplan 

We are sorry for this inconvenient. This design is applied for all blocks in small screens, so it's also applied for ad block. 

We have discussed with team, and we will add except for featured blocks, sponsor blocks and ad blocks. It will be done as soon as we can.

Thanks for your feedback!

Regards.
