### ISSUE TITLE
Bottom of sponsored ad clipped...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2088]
I noticed that the bottom of the sponsored ad clipped slightly in 4.6.0 Beta. See image...

![ad-bottom-clip](https://user-images.githubusercontent.com/17064302/34065795-c333aedc-e1fd-11e7-9990-f5fedca9ed0d.jpg)

**Comment by neil96** [comment]
Hi @starplan ,

We crop image to the correct size. Please use the correct size image and try again.

Regards.

**Comment by starplan** [comment]
I have been trying to find out the recommended sizes of images for phpfox, could you post a link to them so that I can make sure the ad sizes are correct.

**Comment by neil96** [comment]
Hi @starplan ,

The recommended size is: 200x101px. We do not update document for this update yet. We will notice you when the document is available.

Regards.

**Comment by starplan** [comment]
Hi Neil

Thanks for the information, it is much appreciated. I look forward to seeing the updated documents. ;)

**Comment by neil96** [comment]
We added `Recommended Dimension` on create ad form.

Regards.
