### ISSUE TITLE
Code on Announcement page...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2089]
Clicking on "Read more" in the announcements block, show code on the announcement page.

![announcements](https://user-images.githubusercontent.com/17064302/34066258-187a0714-e204-11e7-95e1-cfa4ce62ba4d.jpg)

**Comment by neil96** [comment]
Hi @starplan ,

Do you turn on setting "**Allow html**"?

Regards/

**Comment by starplan** [comment]
I was simply testing and just went into announcements typed and saved, that's it. I didn't turn on any settings. I shall take a look at that now.

**Comment by starplan** [comment]
Turned on "**Allow html**" Announcements are working fine. Shouldn't this then be default?

**Comment by neil96** [comment]
Hi @starplan ,

Turn on "**Allow html**" setting is a require step when you install CKEditor.

Regards.
