### ISSUE TITLE
Photo album swatches at bottom not persistent and photo do not show as part of album

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2090]
In chrome, the photo album swatches at the bottom of the screen does not always stay persistent and disappear. When this occurs the photo does not show an option to move forward or backward through the photos.

Steps to reproduce.

1. Go here: here: https://v4.phpfox.com/photo/8171/desert/albumid_6830/
2. Now click on any photo in the swatch
3. Now refresh

You will now see that the swatches are gone.

**Comment by neil96** [comment]
Hi @prepperz , I can't reproduce on 4.6.0beta. Could you test again on this version.

Regards.

**Comment by prepperz** [comment]
Cannot be reproduced in v4.6, however there are other issues.  Too much space above photo. 

![screenshot](https://user-images.githubusercontent.com/19594886/34096472-6b76693a-e3a3-11e7-8322-c3ea08592d8f.png)

**Comment by neil96** [comment]
Hi @prepperz ,

This is our new design. You can post a [request](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new) if you don't like this.

Regards.
