### ISSUE TITLE
Posted image not in main feed.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2092]
I am using 4.6.0 beta and simply posted a photo. the photo now doesn't appear in the main feed even though I have scrolled to the bottom of the page. It does appear in photos.

I had sponsored the photo in feed and the photo appeared at the top of the feed and also further down the feed where it should have appeared previously. I then unsponsored in feed and the sponsored photo was removed from the top of the main feed and the image futher down the feed was also removed.

I noticed that the photo now appears on the home page prior to logging in. It being used as the background image and the image next to the sign up fields. I don't why it is there.

**Comment by starplan** [comment]
I have since the above posting, posted another photo and the photo that was not showing up in the main feed is now visible. I don't know what is happening?

**Comment by neil96** [comment]
Hi @starplan ,

The issue can come from an incompatible app or cache issue. We can't resolve this problem if you don't give us detail steps to reproduce this again.

Regards.
