### ISSUE TITLE
Social media icons disappeared

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2093]
When I first installed phpfox I didn't select the opton to be able to log in with facebook or to have social media icon anywhere on the website, but I did see social media icons below photos after they had been clicked on. Those icons have disappeared, I don't know why they have dissappeared or if they should have been there by default.

**Comment by starplan** [comment]
I viewed a photo in another browser and the social media icons are there.

**Comment by neil96** [comment]
Hi @starplan ,

These icons are addthis plugin. This plugin is added from 4.5.3 (in new apps). I tested on chrome and firefox, both work well. Could you give us more information.

Regards.

**Comment by starplan** [comment]
I don't see them in my firefox, don't know why. I had a look in some other browsers and the icon are there. It must be my firefox. The thing is I want to remove them, I thought there was an option for this?

**Comment by neil96** [comment]
Hi @starplan ,

Could you test again on phpFox 4.6.0 official.

Thanks!
