### ISSUE TITLE
Forum Post title is too small

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2094]
![screenshot](https://user-images.githubusercontent.com/19594886/34107452-41c646c4-e3ca-11e7-8577-0e7082c3ca70.png)

**Comment by neil96** [comment]
Thanks for your report @prepperz ,

This is our new design. You can post a request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new) if you'd like the title bigger.

Regards.
