### ISSUE TITLE
Error displaying phrases

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2096]
ver: `PHPFox 4.6.0.beta1` + `Material Theme`

As you can see from the figure, when you load photos, the text on the button is not displayed correctly.
![pictureupdatetext](https://user-images.githubusercontent.com/11414490/34132162-e04a3f6a-e44e-11e7-90a1-e631efb4e473.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

I tested with Russian language package on 4.6.0beta, but I can't reproduce.  Could you give us more information.

Regards.

**Comment by CimborNet** [comment]
I updated the variable and it all worked. Thank you.
