### ISSUE TITLE
Clarify image upload in Market place.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2097]
When adding a listing in Market Place it is not obvious how an image is added without making an effort to look for it. Could you make it more obvious how to add images to Market Place listings. In other areas how an image is added is clear to see.

**Comment by starplan** [comment]
I withdraw this issues... I tested it on some friends of mine and they were ok with it.

**Comment by neil96** [comment]
No problem @starplan .
Regards.
