### ISSUE TITLE
Issue in Group Forum 4.6.0b1

### ISSUE THREAD

**Issue by Foxgerman** [PHPfox-Official/phpfox-v4-issues#2101]
For some reasons I was not able to start any discussion in groups (Forum integration in groups is active). The green plus sign is not available for group admins. The site admin can post new threads in to a group.

More than that a a wrong email notification was send to the group admin with this content after a site admin has create a new thread:

Hello Chris, 

posted some images on your group "XXX". 
To see the image, follow the link below: 
http://domain.com/groupname/	

Kind Regards, 
Phpfox 460

This is the wrong phrase and should be changed.

_p('full_name_post_some_images_on_your_group_title'
_p('full_name_post_some_images_on_your_group_title_link'

/phpfox460b1/PF.Site/Apps/core-groups/Job/SendMemberNotification.php
![bildschirmfoto 2017-12-22 um 09 17 59](https://user-images.githubusercontent.com/5095754/34290692-21154c7c-e6f9-11e7-9255-37025880e1a1.png)
<img width="1178" alt="bildschirmfoto 2017-12-22 um 09 04 37" src="https://user-images.githubusercontent.com/5095754/34290699-2cf249c8-e6f9-11e7-82fc-1f46f6d483c1.png">

**Comment by franklambertt** [comment]
> The green plus sign is not available for group admins

Hi Foxgerman,
I cannot reproduce this issue. Please check user group setting "Can post a new thread?" that group's admin belongs to.

Regards,
Frank

**Comment by Foxgerman** [comment]
Regarding the first issue I have forget to set "Can post a new thread", sorry for that:-(
