### ISSUE TITLE
Activate button in Menu Manager

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2103]
On clicking the activate button in the Menu Manager, the button disappears. Refreshing the page show the button in the new state.

**Comment by neil96** [comment]
Hi @starplan ,

Could you explain detail for us.Please attach some screenshots if available. thanks!

Regards.

**Comment by starplan** [comment]
Clicking on Appearance > Menu takes you here. Active button for Home is on.
![menu-active-button1](https://user-images.githubusercontent.com/17064302/34363290-b24757e0-ea72-11e7-850a-065019354ea4.jpg)

Clicking on Home active button makes button disappear.
![menu-active-button2](https://user-images.githubusercontent.com/17064302/34363291-b262061c-ea72-11e7-9665-86df96eba9a1.jpg)

Refreshing page shows button in new state.
![menu-active-button3](https://user-images.githubusercontent.com/17064302/34363289-b22b2c3c-ea72-11e7-9c6f-03ff90ff38c5.jpg)
