### ISSUE TITLE
Messages notification

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2104]
A message was sent via contact seller. Waited for message notification to appear. When notification indicator appeared. Clicked on message icon and saw the image below. Clicking on the yellow are took me to message.

![message1](https://user-images.githubusercontent.com/17064302/34326513-547a566c-e8a6-11e7-970a-7d3e90ce6930.jpg)

**Comment by neil96** [comment]
Hi @starplan ,

I tried with these steps , but I can't reproduce. Could you give us more information. Thanks!

Regards.
