### ISSUE TITLE
Notification panelnot working

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2105]
I have ot of notification since 2015 on my admin account.
It's so large, it was not working on notification panel since i clear it.
But it was woking on /notification/panel page.

**Comment by neil96** [comment]
Hi @Ylmzef ,

I can't reproduce. What version do you test?

Regards.

**Comment by Ylmzef** [comment]
4.5.3

**Comment by neil96** [comment]
Hi @Ylmzef ,

Could you test again on phpFox 4.6.0 official.

Thanks1
