### ISSUE TITLE
Add (Edit) marketplace - No translation for categories is displayed

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2109]
ver: PHPFox 4.6.0.beta1 + Matherial

As you can see from the figure, when editing or adding goods in the market section, categories are not translated.

![untitled-4](https://user-images.githubusercontent.com/11414490/34366328-70f81e0a-ea9a-11e7-914b-87a2ba2d8cb5.jpg)

While viewing the same product, the correct translation is displayed.

![untitled-5](https://user-images.githubusercontent.com/11414490/34366401-3315cfd2-ea9b-11e7-8905-52604435f75e.jpg)

**Comment by neil96** [comment]
Hi @CimborNet ,

I can't reproduce on my side, could you give us more information. 

Thanks!

**Comment by CimborNet** [comment]
This problem occurs only when you add or edit a product.
When viewing the products and category list in the "Market" section, these problems are not present. All categories are displayed correctly and translated.
