### ISSUE TITLE
Link to a nonexistent file

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2110]
ver: PHPFox 4.6.0.beta1 + Matherial

As you can see from the figure and the code above, the link refers to a nonexistent file in this directory.

`<img data-src="https://cimbor.net/PF.Base/file/pic/pages/2017/10/676dd2de924658b89c1b82c3ac8c0f0d_50_square.jpg" src="https://cimbor.net/PF.Base/file/pic/pages/2017/10/676dd2de924658b89c1b82c3ac8c0f0d_50_square.jpg" alt="SILVERPROM" class="_image__120 image_deferred  built has_image">`

In this directory there are files with such names:
```
676dd2de924658b89c1b82c3ac8c0f0d.jpg
676dd2de924658b89c1b82c3ac8c0f0d_50.jpg
676dd2de924658b89c1b82c3ac8c0f0d_120.jpg
676dd2de924658b89c1b82c3ac8c0f0d_200.jpg
676dd2de924658b89c1b82c3ac8c0f0d_200_square.jpg
```

...but there is no file named:
`676dd2de924658b89c1b82c3ac8c0f0d_50_square.jpg`

...and so with all similar files in all directories.

![untitled-3](https://user-images.githubusercontent.com/11414490/34366579-ca8ac262-ea9d-11e7-8179-d1ce5392e72a.jpg)

**Comment by franklambertt** [comment]
Hi @CimborNet,
Did you setup cron in your site?

**Comment by CimborNet** [comment]
Oh sure. Crown works and is configured as indicated in your manual.

**Comment by franklambertt** [comment]
Hi @CimborNet,

In Pages v4.6.0, we created a job to generate missing square thumbnails from Pages v4.5.3.
Please help us check again if your cron run and thumbnails generated.
