### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS - Upgrading procces from 4.6.0.beta1 to 4.6.0.RC

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2111]
After updating the core code from 4.6.0.b1 to 4.6.0 RC (file: 4.6.0.b3.zip) the following error appears: `ERR_TOO_MANY_REDIRECTS`

What I just did not do. And disabled HTTPS (core and for pictures) and cleared the cache - nothing helps.

If I disable HTTPS support then the web site opens, but there are no styles and CSS, and AdminCP is displayed as if in the old version 4.5.3

I disabled all third-party Apps and cleaned the cache.
I even "Rebuild Core Theme" and made "Find Missing Settings".
And nothing helped.

**Comment by neil96** [comment]
Hi @CimborNet ,

You closed this issue. Is your problem resolved?

Regards.
