### ISSUE TITLE
Edit pages categories don't work

### ISSUE THREAD

**Issue by cespiritual** [PHPfox-Official/phpfox-v4-issues#2113]
When I try to edit the categories of a page, to change it, it don't work.

When I change the main category, the combo box of the sub category don't update. And when I select the categories and save, still show the previest one selected on page creation.

Thanks

**Comment by neil96** [comment]
Hi @cespiritual ,

I can't reproduce. Could you give us more information.

Regards.

**Comment by cespiritual** [comment]
Tested on your demo site and it's working ok... again some problem with my server...
