### ISSUE TITLE
Featuring photo issue

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2115]
In 4.6.0 RC... I shared a photo from my profile page. Clicked on it in main feed. Featured it. When viewing it on detail page it has the feature icon on it but it is not featured on right hand side in Photo app. Photos shared from photo app feature Ok.

**Comment by neil96** [comment]
Hi @starplan ,

I can't reproduce. Could you give us more information or some screenshots.

Thanks!
