### ISSUE TITLE
Featured and Sponsored album photos

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2116]
In 4.6.0 RC although I am given the option to feature and sponsor photos in my albums, but they don't show up as featured or sponsored photos in photo app.

**Comment by starplan** [comment]
Sponsored album photo has shown up. I turned the computer off and came back to it later in the day. I don't know why it didn't appear earlier, even though I had cleared the cache. I'll keep checking this.

**Comment by neil96** [comment]
Hi @starplan ,

Do you mean **featured** and **sponsored** photos? Photo do not support feature and sponsor album.

Regards.
