### ISSUE TITLE
"The feature or section you are attempting to use is not permitted with your membership level." Warning gives user a negative connotation

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2119]
When clicking on the upper right down arrow > membership, The warning message should reflection something more meaningful rather than giving users the impression that something is very wrong. This issue has been raised in previous version, yet it keeps cropping up.

**Comment by neil96** [comment]
Hi @prepperz ,

This is not a bug. If you'd like to change this, please post a request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new). If you already post this request, please comment to remind us. Thanks!

Regards.

**Comment by prepperz** [comment]
It's not a bug, but the wording is very misleading and should change to something more meaningful.

**Comment by neil96** [comment]
Please post request for this case.

Regards.
