### ISSUE TITLE
Pages blog selection covers blog title (likely the  same for groups)

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2120]
![screenshot](https://user-images.githubusercontent.com/19594886/34451436-895632ec-ecf3-11e7-8c31-e97fd2f675e1.png)

**Comment by neil96** [comment]
Hi @prepperz ,

This is our new design.

Regards.

**Comment by prepperz** [comment]
The title should really be moved a few spaces to the right so people could actually see what it is that is being selected. If that acceptable by design, then people will see it as very poor quality control.

**Comment by neil96** [comment]
Hi @prepperz ,

We have new design for 4.6.1. Thanks for your report.

Regards.
