### ISSUE TITLE
Editing information within an app...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2121]
I have noticed that when you click on edit in order to edit an item. A new page appears so that editing can take place except for the photo app. It opens a lightbox type popup window that contains the information that can be edited.

Shouldn't all editing pages open in the same why?

**Comment by neil96** [comment]
Hi @starplan ,

This is our design. Please post [a new request](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new) if you do not like this rule.

Regards.
