### ISSUE TITLE
No translation of the phrase "Liked"

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2126]
`ver: PHPFox 4.6.0.RC1 + Matherial`

No translation of the phrase "`Liked`" if you hover your mouse over the icon.

![untitled-4](https://user-images.githubusercontent.com/11414490/34623500-efeb6488-f251-11e7-91f5-f09d6ea39a61.jpg)

**Comment by EgyCheETah** [comment]
U can do that in admin panel

In lang just search for word and manual translate

**Comment by CimborNet** [comment]
Are you serious?

Do you really think that I know how to create this post and do not know where and how phrases are translated in the system?

If I created this post, it means that I translated this phrase into the admincp, but it still does not translate.

Or should I give you a piece of code where the error will be seen?

**Comment by EgyCheETah** [comment]
easy man i just wanted to give hand 

now try this

now use browser element inspection and hover dat word to define which file need to edit

then change it with phrase liked 

thats it

**Comment by CimborNet** [comment]
We are here making posts with the aim of eliminating the found bugs and not allowing them in new releases.

We all know how to eliminate this error.

But if the developers do not fix this error in the code core, then the next update, this error should be corrected to me again manually.

Leave your amateur offers with you, ok?

**Comment by EgyCheETah** [comment]
I just want to help each others and give hand

But U r really seems idiot. Keep ur freakn head in WC
