### ISSUE TITLE
Coding

### ISSUE THREAD

**Issue by EgyCheETah** [PHPfox-Official/phpfox-v4-issues#2127]
Hello everyone

I just want to do some modifcations to member index but cant do that for an example

I want add profile picture and profile cover.. Etc
 but it render codes

So any hint

**Comment by EgyCheETah** [comment]
* sry i was able to do dat all modifcations in v3 but with v4 unable to do

**Comment by neil96** [comment]
Hi @EgyCheETah ,

To discuss about phpFox, please post on our [community](https://community.phpfox.com/forum/).

Regards.
