### ISSUE TITLE
Video Description HTML issue

### ISSUE THREAD

**Issue by karargaht** [PHPfox-Official/phpfox-v4-issues#2128]
Video Description HTML issue

![screenshot](https://user-images.githubusercontent.com/8930862/34637703-d68525da-f2cc-11e7-95e6-cd757e01041d.png)

**Comment by CimborNet** [comment]
Give a link to this video in Youtube. I'll check it on my site.

**Comment by neil96** [comment]
Hi @CimborNet ,

Please enable "Allow Html" on your site. This is a required step when install CKEditor. On 4.6.0 official, we automaticlly enable this setting when you install CKEditor.

Regards.
