### ISSUE TITLE
Comments notification -"Mark as Read"

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2130]
In version 4.6.0 - Clicking on comment notifications there are two tiny icons on the right hand side. One for Archive and the other for Mark as Read.

Rolling of the "Archive" icon show the alt text "Archive". Rolling over the "Mark as Read" icon does not show any alt text.

Could you please add the appropriate alt text to the archive icon. I guess it would be "Mark as Read".

**Comment by neil96** [comment]
Hi @starplan ,

It's not "Mark as Read" button. It's just an icon.

Regards.
