### ISSUE TITLE
White band at bottom of home page...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2131]
In version 4.6.0 - When home page is viewed at 1920 x 1080 there is a white band at the bottom of the screen. If you can't see it, try switching the visibility of the main menu to off.

![white-band-at-bottom-of-homepage](https://user-images.githubusercontent.com/17064302/34677532-5d6f336c-f488-11e7-897c-a6afede85276.jpg)

**Comment by neil96** [comment]
Hi @starplan ,

I can't reproduce this issue on phpFox 4.6.0 official. Could you try again.

Regards.
