### ISSUE TITLE
ERROR on upgrade from 4.6.0.RC1 to 4.6.0 Release

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2132]
```
running step: verify_app_state
array (
  'step' => 'verify_app_state',
  '_ajax' => '1',
  'phpfox-upgrade' => '1',
)
running step: rebuild_bootstrap
array (
  'step' => 'rebuild_bootstrap',
  '_ajax' => '1',
  'phpfox-upgrade' => '1',
)
error E_ERRORCall to a member function default_photo() on boolean

Stack trace:
#0 (unknown file)(0): Phpfox_Installer->onInstallationShutdown()
#1 {main}

```
  
![untitled-4](https://user-images.githubusercontent.com/11414490/34750261-89f5df34-f5a6-11e7-965e-9071f0ff80fe.jpg)
![untitled-5](https://user-images.githubusercontent.com/11414490/34750263-8a15d80c-f5a6-11e7-8132-ad8d0dadb8b3.jpg)

comes to this place and stops

![untitled-6](https://user-images.githubusercontent.com/11414490/34750264-8a32f0d6-f5a6-11e7-875c-2222a9f329ae.jpg)

and then nothing happens and the "Next" button is not present

**Comment by neil96** [comment]
Hi @CimborNet ,

I can't reproduce this issue.

Could you [submit a ticket](https://clients.phpfox.com/submitticket.php) with your site information. We will check detail on your site.

FYI, at the step "Rebuild Core Theme", it can take some minutes to be done. 

Regards.
