### ISSUE TITLE
Top Bloggers Cover Image

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2133]
The coverimage of the Top Blogger does not show up in the block. Tested on v4.6 bootstrap demo.
![topblogger](https://user-images.githubusercontent.com/13225682/34778016-5a728a52-f61c-11e7-8f65-0f8385cb68be.jpg)

**Comment by neil96** [comment]
Thanks for your report @Scheinwelt-Media ,

This is our demo issue only. We will fix it soon.

Regards.
