### ISSUE TITLE
comment_text remains in database 

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2134]
comment_text remains in database on status delete. we need something to get rid of all comment texts without comment id to clean up the database. inline delete on comments works. tested on v4.6 stable.

**Comment by neil96** [comment]
Thanks for your report @Scheinwelt-Media ,

New comment_text is deleted. However, we do not fix for old data.

Regards.

**Comment by Scheinwelt-Media** [comment]
i have tested this with v4.6 and the new comment text was still there after deleting the status.

**Comment by neil96** [comment]
I can't reproduce this.

**Comment by Scheinwelt-Media** [comment]
will check how to reproduce later
