### ISSUE TITLE
new install latest ver 4.6.0 in admicp >>settings >> SEO : all links do not work to edit seo wording??

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2135]
<title>Quiz Meta Description</title><info>Meta description added to pages related to the Quizzes app.Click here to edit meta description.(SEO) 
in admicp >>settings >> SEO : all links do not work to edit seo wording??

new install latest ver 4.6.0
I tried all of them and none of them open a window to change SEO for blogs, marketplace, music, videos etc ? just opens admincp main area 

i just did install not even 2 days ago still cannot open SEO to edit from click here links the language file still has session ids and directs me to admincp page always

https://mywesite-address/admincp/setting/edit/admincp/language/phrase/?sessionid=5a56285ef41e5?q=seo_pages_meta_keywords this is what the link looks like and redirects to admincp page

is there a newer file from yesterday ?? that you updated to correct this ?

**Comment by spirogg** [comment]
@neil96 @RaymondBenc this is still issue for me i sent request in your support with my login details and ftp so you can see for yourself, uploaded and installed yesterday

**Comment by Foxgerman** [comment]
This issue is not fixed (https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2084).
There is a quick solution in this thread to search for the phrases. 

Problem is the link in the phrase. It has to be:

https://mywesite-address/admincp/language/phrase/?q=seo_pages_meta_keywords 

and not

https://mywesite-address/admincp/setting/edit/admincp/language/phrase/?sessionid=5a56285ef41e5?q=seo_pages_meta_keywords

**Comment by spirogg** [comment]
@Foxgerman 
Thank you for answer this :) you are correct.

**Comment by neil96** [comment]
Hi @spirogg ,

We fixed this issue, but you have to re-install the app. Could you re-install (from store) apps that have this problem.

Regards.

**Comment by spirogg** [comment]
@neil96 yes Frank fix for me the other day sorry forgot to close ticket thanks

**Comment by spirogg** [comment]
Hi I just did fresh installed 4.6 and after it had a few apps to update. But still there are 5 apps - pages, music, video, events, forum that SEO links when you click not working. If it's fixed it should of installed from store new apps with fix. But not working. I will try to.go to store and see if it works. From there. Sorry to reopen this link
