### ISSUE TITLE
ver 4.6.0 when not allow guest to see website links we need to disable search function too

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2136]
ver 4.6.0 new install, when not allow guest to see website - links, we need to be able to disable search function also otherwise they can browse website once they perform a search in the search bar ?

so i set my site for guests not to be able to browse site, but search bar is still available and when i do a search with a letter or word, it brings up my admin and users  and displays my info ( user info ) then can browse to photos marketplace etc.. is there a way to break search function when we turn that feature on in admincp ?? s0 nothing can be seen unless they signup

thanks

**Comment by Scheinwelt-Media** [comment]
go to usergroup guest and disable "can use the global search tool".

**Comment by spirogg** [comment]
@Scheinwelt-Media  thank you - i was looking everywhere for this and now i see i have to choose search app and all other apps to make changes in usergroups.. nice thank you - new to version 4.6

 by any chance do you know how to get the seo links to open to change meta description etc.. it seems the links redirect to admincp and do not open the page to add description and keywords, you have the go to phrase and find it then change it, but in admincp under SEO that page links do not work for me?
