### ISSUE TITLE
v4.6 browse from admincp does not retain filter settings

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2137]
Browing members from admincp does not retain filter setting. For example. when registered users are seletected > and then seearched. Select a user and delete and the whole thing will reset.

Also when when the scroll bar hits the bottom the ban/delete etc... options disappear.

**Comment by neil96** [comment]
This is our design. If you'd like to change, please post on our [request](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new) repo.

Regards.
