### ISSUE TITLE
the menu item in admincp darkens when selected make it difficult to see

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2138]
When an item is selected, it darkens to indicate where you are. The problem is that it's difficult to see. When a menu item is selected it should be a white or something instead of  dark font on a dark background.

Also, the grey font on black is also too dull and doesn't stand out when mousing over the menu items. It should be bright white fonts instead so it will be easier to see.

**Comment by Scheinwelt-Media** [comment]
i like the new look and can see everything. do not get the point of your issue. where do you see black background?

**Comment by neil96** [comment]
Hi @prepperz ,

This is our new design. I feel everything easy to see.

Regards.

**Comment by prepperz** [comment]
If someone is saying that it's hard to see the text. There must be a reason, no? 

![screenshot](https://user-images.githubusercontent.com/19594886/34857011-842638f8-f716-11e7-8952-d617abf45716.png)
