### ISSUE TITLE
4.6 update breaks bootstap pages admin template.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2141]
See screenshot

![pages-admin](https://user-images.githubusercontent.com/19594886/34902157-cf837fb8-f7e3-11e7-8bc1-5fc7dace1fc0.png)

**Comment by neil96** [comment]
I can't reproduce. Could you give us more information.

**Comment by prepperz** [comment]
OK. It seems, I had to clone the new bootstrap and then edit instead using the one from v4.53.
