### ISSUE TITLE
Blog selection / title not properly aligned on bootstrap

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2143]
![screenshot](https://user-images.githubusercontent.com/19594886/34905373-2f611058-f825-11e7-8e73-49a3a9e93ef5.png)

**Comment by CimborNet** [comment]
Yes there is such a small problem in the design. But this effect is observed only if you are allowed to edit this blog. For other users, this problem does not exist.

**Comment by neil96** [comment]
#2120
