### ISSUE TITLE
@neil PLEASE READ - Sorry but not music mp3 doesn't upload keeps spinning, movie-photos work NO MP3

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2146]
It seems the latest update of phpfox 4.6.0 have issues on their Phpfox CDN app.
The photos wont upload to the external storage.
It works on Phpfox v4.5 and older versions.

 anyone notice the same issue ? I have server and added other server for cdn only, but its not working, do you notice or know of any bugs with latest version 4.6.0 clean install ?

also just a question, if you fix something in an app that has a bug or bugs fix, can we can just re upload the app again and it should workout the bugs ?

**Comment by spirogg** [comment]
![file seems stuck-notuploading](https://user-images.githubusercontent.com/17736688/34922872-1707a3c8-f95b-11e7-8b70-889add0cdc72.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

I can't reproduce this issue. Could you give us more information. 

FYI, [our demo](https://v4.phpfox.com/) is using phpFox CDN.

Regards.

**Comment by spirogg** [comment]
I have a ticket in phpfox support with my login credentials For admincp.
For my site. If you could please please login an check it. Maybe ?

Thank you sir.

Spiro

**Comment by spirogg** [comment]
@neil96 I left message. Just FYI Incase it doesn't show you if I don't add your @ name  😂

**Comment by spirogg** [comment]
@neil96 sent you ftp details etc in phpfox client portal

**Comment by spirogg** [comment]
@neil96 I'm sorry but now it doesn't allow music mp3 songs to upload I haven't tried a real video yet. But mo3 songs don't upload. Spinning and spinning. So sorry.  I just want it to work :(
