### ISSUE TITLE
Sorry but seems like there is issue with mp3 uploads, i tried 12 times only 2 worked READ PLEASE

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2147]
seems like there might be issue, before cdn i did music mp3 with no issues really fast, noe after we change cdn it spins and spins, 2 music mp3 got uploaded the others ( i do one at a time ) they spin for over 5-6-7-mins, and i just close window no error ? just dont refresh and or close window it says and spining around ?

maybe a little tweek for upload mp3 because of cdn app issue with photos before ?

**Comment by spirogg** [comment]
my internet at home 
PING 8 ms 
DOWNLOAD 813.96 Mbps 
UPLOAD 24.18 Mbps 
speedtest.net just fyi

**Comment by neil96** [comment]
Hi @spirogg , I can't reproduce.

**Comment by spirogg** [comment]
did you try to upload video on my site - you just fixed the cdn bug, i cannot now uoload any more videos i just tried 15 times small 8mb 9mb mp3 just spins even on edge browser ? maybe php5.5 issue like cdn issue ?

**Comment by spirogg** [comment]
![music app - mp3](https://user-images.githubusercontent.com/17736688/34938438-fccf77bc-f9ad-11e7-9112-19c2a14d6886.PNG)

**Comment by neil96** [comment]
Hi @spirogg  ,

Please double check "max_file_uploads" and "post_max_size" on both server. By default, it's only 2MB.

Regards.
