### ISSUE TITLE
Pages and Groups - Duplicated "Photos and Video" icons

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2151]
In version 4.6.0 - When you click onto a page or group, there are icons below the cover photo. The "Photos" icon is duplicated, so there are two of them.

![pages---duplicate-photos-icons](https://user-images.githubusercontent.com/17064302/34960004-ea2dae48-fa30-11e7-849b-f19ffe48503a.jpg)

![groups--duplicate-photos-icons](https://user-images.githubusercontent.com/17064302/34960150-8d67767a-fa31-11e7-9d2b-716a5088a256.jpg)

**Comment by spirogg** [comment]
not sure whats going on with yours but i did clean install and dont see 2 photos, mine says photos and next to it Videos

![page-photo-video shows properly](https://user-images.githubusercontent.com/17736688/34961757-4461fa5c-fa06-11e7-98b1-0f8b76c49580.PNG)

**Comment by spirogg** [comment]
YES ON DEMO PHPFOX THIS IS SHOWING

**Comment by starplan** [comment]
Yes, you are correct in saying that it is on the phpFox demo.
