### ISSUE TITLE
When using mobile phone on profile and delete a feed when blue menu is showing the  page gets stuck 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2152]
Using version 4.6.0 Hi go to profile and in your feed scroll down untill the menu bar turns blue if you have to scroll untill it says load more then click load more then find a feed to delete like a photo, video or music feed and then try to scroll back up or down. Page gets stuck Android 7.1.1 HTC phone. Chrome.browser.

**Comment by neil96** [comment]
Hi @spirogg , could you give us more information. Thanks!

Regards.

**Comment by spirogg** [comment]
@neil96 this is an intermittent issue... on my HTC Phone.. sometimes after deleting asks if i'm sure to delete and i select OK...  then it says deleting feed, 

If i click on the X when it says deleting feed and don't wait for the screen to go away by itself it sometimes freezing the screen 

 IF i let the popup that says deleting feed go away on its own, 
it doesn't freeze the page... no worries on this one, i can probably say its intermittent only when clicking on the X in the deleting Feed popup, so I will close this one.
