### ISSUE TITLE
Clicking on Update twice on edit "info"in pages takes user out edit.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2153]
Clicking on Update twice on edit "info"in pages takes user out edit.

**Comment by neil96** [comment]
Hi @prepperz , I can't reproduce. Could you give us more information.

Thanks!

**Comment by prepperz** [comment]
I can reproduce this on the demo.

1. Goto pages manage. Then the info section.
2. Click update. wait. and then click update again. and it will take you out of edit mode.

**Comment by neil96** [comment]
I still can't reproduce with these steps.

**Comment by prepperz** [comment]
I can reproduce it on phpfox's demo site.

**Comment by prepperz** [comment]
So here it is on the first click on update, it goes to this url: https://v4.phpfox.com/pages/add/?id=321&tab=info

After the second update click, it goes to this: https://v4.phpfox.com/pages/add/?id=321&tab=

so it takes the user out of the ckedit mode.
