### ISSUE TITLE
Content is cut-off and not properly containerized on pages info section  under firefox with bootstrap template

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2154]
When viewing on firefox the content in the pages info section is cut-off under firefox using the bootstrap template. Under chrome it displays properly.

**Comment by neil96** [comment]
Hi @prepperz ,

Could you give some screenshots?

Thanks!

**Comment by prepperz** [comment]
I will send you a link via support.

**Comment by neil96** [comment]
We support scroll if the content is too wide. It's not a bug.

**Comment by prepperz** [comment]
That odd. Wouldn't it be best to have it automatically fit within the container? I see that it works works perfectly in chrome, but not firefox. Could the same be done across all browsers?

**Comment by neil96** [comment]
Hi @prepperz ,

Once we allow user can add html, we can't control the height and width of the content. So scroll is the best solution.

Regards.
