### ISSUE TITLE
when selecting your group on Android phone, selecting drop down menu to add photo, video etc doesnt work

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2157]
He when selecting your group on Android phone running 7.1.1 HTC and selecting drop down menu to add photo video music the green plus sign doesn't open to give option to share video, share photo, or upload anything
Using.latest version 4.6.0 using material template. Tried with phpfox cdn on and off. Same issue.

![cant add photos to group](https://user-images.githubusercontent.com/17736688/35026344-261581e4-fb10-11e7-935a-0e34d9d9b90f.png)

![cant add photos to group](https://user-images.githubusercontent.com/17736688/35026348-2d182a96-fb10-11e7-85c3-0d956621a2ee.png)

**Comment by spirogg** [comment]
@neil96 the share photos popup doesn't show when you click on the green plus button (add button)

![share photos](https://user-images.githubusercontent.com/17736688/35026402-79920da6-fb10-11e7-820c-42d51b2571e1.jpg)

**Comment by spirogg** [comment]
@neil96 when selecting the main menu to see all photos on site or all music on site the popup works to add photo and music, videos etc, 

![using main menu selecting music](https://user-images.githubusercontent.com/17736688/35027072-1fe6abe6-fb14-11e7-9428-b1a499659a49.png)

![selecting main menu photos](https://user-images.githubusercontent.com/17736688/35027085-3117f168-fb14-11e7-8e22-c7e22432bb67.png)



**@neil96 but when selecting from drop-down from groups pages your own profile it doesn't work**

**Comment by spirogg** [comment]
@neil96 when selecting the main menu the Green + button doesn't move, it is on the bottom right as if it were floating and stays there as you scroll up or down, but on the other pages i show it moves when you scroll, so I think its got something to do with CSS or something in the placement of the button in the code

**Comment by spirogg** [comment]
@neil96 same thing happens to me on your demo site v4.phpfox

![phpfox demo also](https://user-images.githubusercontent.com/17736688/35027585-2555f598-fb17-11e7-9332-fa080aae444e.png)

![phpfox demo button not working](https://user-images.githubusercontent.com/17736688/35027586-2561eb0a-fb17-11e7-9b35-b5e843cf1f20.png)

![phpfox demo same affect](https://user-images.githubusercontent.com/17736688/35027587-256d85d2-fb17-11e7-9aa3-0e6a6acba976.png)

**Comment by neil96** [comment]
You tagged me 5 times in this post. 😲

**Comment by spirogg** [comment]
sorry

**Comment by spirogg** [comment]
this issue should be the same bug as these other two I added earlier
#2149 
#2150

**Comment by spirogg** [comment]
any word on this fix and also whats the next date you think you will have fixes  for most of these bugs - this one is a a good bug to fix, there are alot of users on phones that cant use this feature ?

thanks

Spiro

**Comment by spirogg** [comment]
when you fix this can you just show me the page and lines of code to fix this so i can implement on my site please.. :)

thanks
