### ISSUE TITLE
AJAX sitewide off causes Quiz and Polls results fail to load

### ISSUE THREAD

**Issue by optpf** [PHPfox-Official/phpfox-v4-issues#2160]
Hi.
If you have the setting `Turn off full ajax mode` set to `Yes`, you can't load other results of Quizzes and Polls. I'm pretty sure it causes problems in other apps as well (as they share the pagination mode).

### Steps to reproduce:
1. Turn off full ajax mode on the website
2. Create a Quiz and make at least 11 people answer to it
3. Visit the Quiz and in the left column there will be the block "Recently Taken": click at its bottom "View More"
4. You will be redirect to https://website.com/quiz/{id}/{quiz-name}/results/ as expected
5. Here will be a list of "Member results". Click on the second page or any other page to view other answers
6. You'll be redirected to `http://ajax-paging` instead of getting the new results in the block

### What happens:
You get redirected to a new page

### Expected
Getting the refreshed block with other answers

### phpFox version
4.6.0 stable

### Server info
Ubuntu 16.04 LTS 64bit, all phpFox requirements satisfied
Nginx as web server
Redis for caching

### Browser info
Tested in Chrome Stable and dev, Firefox and Microsoft Edge

The problem happens in a fresh install of v4.6 and in an upgraded instance from 4.5 to 4.6 

Can't reproduce in `v4.phpfox.com` because it has full ajax mode enabled.

### Suggestion
The problem is coming from the `pager` template/service - I think that solving it will solve the problem.
Also, seems that phpFox isn't able to load the new results because a part of Javascript that loads ajax isn't loaded, so it redirects to a new website, `ajax-paging`

Possibly other Apps by phpFox are compromised with this problem because all use the new paginating mode introduced in v4.6

**Comment by neil96** [comment]
Thanks @optpf , we confirmed this is our issue.

Regards.

**Comment by optpf** [comment]
Hi Neil, thanks for checking this out.
When you will fix the issue, could be possible to send / tell me the files and lines edited/added so I can apply the fix before the next release or build?
My community relies so much on these features, and having them broken is a problem, as for technical reasons we can't have ajax sitewide enabled.

Hope you understand. Thank you!
