### ISSUE TITLE
Page edit is missing source

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2163]
When editing a previously saved page, only a few  lines of the source shows. The rest  are missing.

**Comment by neil96** [comment]
Could you give us more information.

Regards.

**Comment by prepperz** [comment]
This is the same issue from the last two releases. https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2049

**Comment by prepperz** [comment]
The problem still exist

**Comment by neil96** [comment]
I need more information from you to reproduce it.

**Comment by prepperz** [comment]
Just create anew page, paste in a asource of 7 lines or more and save it. Then go back and edit the page. Portions of the source will be missing.

**Comment by neil96** [comment]
I still can't reproduce.

**Comment by prepperz** [comment]
I can send you the info in support ticket if you want. to take a look.

**Comment by neil96** [comment]
It can be a site issue only. You can send us a ticket if your support plan is active.

Regards.

**Comment by prepperz** [comment]
OK. Figured out what is causing the issue. I can reproduce it on a test server. It is a phpfox issue. It works fine without ckeditor, but as soon as ckeditor is installed the issue occurs. 

It would be helpful to know what phpfox has installed when testing so it can be an apples to apples comparison...

**Comment by neil96** [comment]
I tested with CKEditor enable.

**Comment by prepperz** [comment]
Ya. So I spun up a test server and it does the exhibit the issue of ckeditor removing most of the html source.

**Comment by prepperz** [comment]
This issue is still persistent in v4.6.1 in appearance > pages.
