### ISSUE TITLE
Bundler brings down the entire site. 

### ISSUE THREAD

**Issue by matthewpomar** [PHPfox-Official/phpfox-v4-issues#2164]
I have been working with support for weeks on this, so I thought I'd post the issue here to see if others can contribute any useful info to help phpFox solve this problem. It's so bad for me, it brings down my entire site at times; other times it just makes certain pages look weird.

It appears if you have bundler enabled, then make an Admin CP change, it will break existing JS code. 

I believe support made a change to fix an issue with deleted Blog categories showing in RSS. I looked at the code, and database tables, and there appears to be script inside the database field. I could see how if they made a change to that code in the DB, but didn't unbundle and clear cache, that might have caused my site to crash.

When I turned off bundling, the site went from this:

![2018-01-29_15-00-51](https://user-images.githubusercontent.com/7439207/35540487-b2aec272-051b-11e8-9839-b8bbbe0a9b50.png)

To this:

![2018-01-29_17-42-38](https://user-images.githubusercontent.com/7439207/35540510-d2ea7838-051b-11e8-9cc9-08ef67b3ca43.png)

**Comment by neil96** [comment]
Hi @matthewpomar , I can't reproduce. I see you disable a lot of apps. Could you send us the list of disable apps. Thanks!

**Comment by neil96** [comment]
I checked this issue on your server. This is a site issue.

**Comment by matthewpomar** [comment]
Thanks Neil.

I have been working with Paul, and it according to Paul, this is a hosting issue, not a site issue. The site is vanilla. I only disable certain menus in settings. The issue is the hosting plan I bought from you guys isn't capable of fully hosting the software. Paul said the bundler times out creating the bundle due to the slow server, leaving empty JS files.

Hopefully you guys can either speed up the server, or move me to a capable server with minimal (preferably no) cost.
