### ISSUE TITLE
Meta not working properly

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2165]
![pages_meta_description](https://user-images.githubusercontent.com/19594886/35543760-e55299ec-0534-11e8-8f5e-90741745572f.png)

![phrase](https://user-images.githubusercontent.com/19594886/35543623-0da65d3a-0534-11e8-8d19-df1f4e44e9b2.png)

**Comment by arcticwolf8** [comment]
They rely on OG tags. There is an app in the store which I used to remedy this.
