### ISSUE TITLE
Deleting pages status does not remove feed when users shared on their wall.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2166]
Deleting pages status does not remove feed when users shared on their wall.

**Comment by neil96** [comment]
Hi @prepperz ,

I can't reproduce. Could you give us more information.

Regards.

**Comment by prepperz** [comment]
Steps to reproduce.

1. Post a status on pages
2. share posted pages status on your wall.
3. delete the pages status.
4. go check your wall.

**Comment by neil96** [comment]
5. The shared post is disappeared.

Regards.
