### ISSUE TITLE
Short URL problem

### ISSUE THREAD

**Issue by bennington111** [PHPfox-Official/phpfox-v4-issues#2167]
After update my site 3.7.1 to 4.6.0, and enable short url, photos not show. Show only photo upload after update. If disable short url, photo show normal.
![f1d8510e7ec8f557a326e7721fb65edb](https://user-images.githubusercontent.com/36040586/35682162-5ff3d096-0768-11e8-80fe-b74d2f8cb17c.png)
Original photo use prefix _1024. If short url enable, all photo without this suffix.
**Example**:
Short URL disable: /PF.Base/file/pic/photo/2017/11/c4be896c232c4b27ce60651f827e5562_1024.jpg
Short URL enable: /PF.Base/file/pic/photo/2017/11/c4be896c232c4b27ce60651f827e5562.jpg
Problem whith option to "**Delete Original Photo After Resize**" in phpfox v3. I have this option turned on. If this option enabled in phpfox v3, original photo delete, and not show after update to phpfox v4 and enabled "**Short URL**".
**How to introduce this bug:**
1. Install phpfox v3.
2. Enable option "**Delete Original Photo After Resize**". **(Importantly!!!)**
3. Add few photo.
4. Update phpfox 3 to 4.
5. Enable short url.
Old photo not show.
**This is a bug.**

**Comment by neil96** [comment]
Hi @bennington111 ,

Did you do this step: [Cleaning up V3 Files after Upgrade](https://docs.phpfox.com/display/FOX4MAN/Cleaning+up+V3+Files+after+Upgrade)

Regards.

**Comment by bennington111** [comment]
> Yes, i cleaning up V3 Files
