### ISSUE TITLE
Disabled Music app still appears on Groups menu

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2170]
Disabled Music app still appears on Groups menu

**Comment by neil96** [comment]
It works on my side. Could you give us more information.

**Comment by prepperz** [comment]
What I mean is that when you disable the music app, it's not suppose to show up on the menu. However, it is still showing up on the groups menu when it shouldn't.

**Comment by neil96** [comment]
I can't reproduce. 
<img width="669" alt="screen shot 2018-02-07 at 08 26 29" src="https://user-images.githubusercontent.com/15936115/35893439-a68a240c-0be0-11e8-9112-b5b91c798331.png">

**Comment by prepperz** [comment]
Try bootstrap

**Comment by neil96** [comment]
tried with bootstrap.

**Comment by prepperz** [comment]
IDid you disable it from the app page?
