### ISSUE TITLE
"With" phrase translation

### ISSUE THREAD

**Issue by kirkkhua** [PHPfox-Official/phpfox-v4-issues#2171]
Hi,

If you try to add a translation for "With" phrase it won't be translated.

![screen shot 2018-02-07 at 4 20 56 pm](https://user-images.githubusercontent.com/5412712/35921301-f53b1aba-0c22-11e8-88d0-4c99822a9f21.png)

Tested on v4.6.0 – even if with phrase changed in English it won't be translated.

**Comment by kirkkhua** [comment]
Same happens when you're tagging someone on a photo and it says With ... below the photo.

**Comment by neil96** [comment]
#2140
