### ISSUE TITLE
phpFox favicon shown instead of uploaded favicon in firefox back button list...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2172]
In version 4.6.0 using firefox 58.0.2 browser

Click on several links in the main menu then click and hold down the back button in the Firefox browser to view previously visited pages. The phpFox favicon is shown not the favicon that was uploaded.

**Comment by prepperz** [comment]
It seems the same thing is happening with the site logo as well. I just noticed it today that phpfox default is randomly appearing. I logged in as admin and cleared the cache and it went away, but this is a problem.

**Comment by neil96** [comment]
I can't reproduce with these steps.

**Comment by starplan** [comment]
I forgot to state to first of all upload a new favicon.ico file in admincp>appearance>Edit>Logo>Favicon.

**Comment by neil96** [comment]
Hi @starplan ,
I did it.

FYI, browse cache favicon. So after favicon is changed, it still displays old favicon in short time.

Regards.
