### ISSUE TITLE
Amazon s3 settings in 4.5.3

### ISSUE THREAD

**Issue by MeSammy** [PHPfox-Official/phpfox-v4-issues#2175]
I am still using 4.5.3 in live, to upgrade in 4.6.0 it takes time. In 4.5.3 amazon s3 settings are not coming, It shows "This setting group has no available settings."

**Comment by neil96** [comment]
I can't reproduce both on phpFox 4.5.3 and phpFox 4.6.0.

**Comment by MeSammy** [comment]
ok
