### ISSUE TITLE
4.6.1 Photo app issue...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2176]
Since updating photo app to 4.6.1 photos now appear in feeds as in image below.

![photo-issue1](https://user-images.githubusercontent.com/17064302/36174873-8e514710-1105-11e8-888b-ad73cf5838d6.jpg)
![photo-issue2](https://user-images.githubusercontent.com/17064302/36174876-910816dc-1105-11e8-950e-129760bb69d9.jpg)

**Comment by neil96** [comment]
Could you give us more information.

**Comment by starplan** [comment]
All I can tell you is that since upgrading the above now happens in all browsers that I have tried; Firefox, Chrome, Opera, Vivaldi. Now all image posts are like this. :(

**Comment by starplan** [comment]
I have restored the website from backup and only updated the Marketplace app... All is well.

**Comment by neil96** [comment]
Our [demo](https://v4.phpfox.com/) uses photo 4.6.1. Could you test on our demo.

**Comment by starplan** [comment]
Tested it on the [demo](https://v4.phpfox.com/), it worked fine. The image I uploaded is [here](https://v4.phpfox.com/photo/11196/jaguar-cx16-concept-sketch/feed_13709).

**Comment by starplan** [comment]
This better shows the problem that I am having with the new 4.6.1 photo app. What do you suggest is the best way to resolve it?

![photo-issue3](https://user-images.githubusercontent.com/17064302/36287360-3ccb3c86-12ac-11e8-95d2-8bb9c5a2f241.jpg)

**Comment by neil96** [comment]
I can reproduce on bootstrap.

**Comment by neil96** [comment]
This issue is gone after you rebuild core theme and clear cache.

Regards.

**Comment by starplan** [comment]
Ok. I rebuilt core theme, cleared cache and updated CSS. Everything is working now. Thanks
