### ISSUE TITLE
Profile Crop Images 4.6.0

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2177]
Hello Guys,

Could you return back the option to disable the crop image on profile picture? This cropping image not work properly.

http://prntscr.com/ifrczz

**Comment by neil96** [comment]
Hi @juniortimeline ,

For feature request, please post [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
