### ISSUE TITLE
Issues with "Mark all read" for notifications

### ISSUE THREAD

**Issue by FuSoftware** [PHPfox-Official/phpfox-v4-issues#2178]
Spam-clicking the "Mark all read" button in the notifications thing in the top right of the screen, it just keeps adding "Marked all read successfully" on top of another.

It should only show one and not stack up like that.

Also, using that button doesn't actually "reads" the notifications, they still appear as unread in the same popup when the page is reloaded.

Example : http://puu.sh/zplii.jpg

**Comment by neil96** [comment]
> Spam-clicking the "Mark all read" button in the notifications thing in the top right of the screen, it just keeps adding "Marked all read successfully" on top of another.

=> It's our design.

>Also, using that button doesn't actually "reads" the notifications, they still appear as unread in the same popup when the page is reloaded.
=> I can't reproduce.
