### ISSUE TITLE
Photo album swatches disappears

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2182]
The photo album swatches disappears.

Steps to reproduce.

1. Click on an album
2. Click on a photo from the album
3. Click refresh on your browser and the album swatches at the bottom disappears.

**Comment by neil96** [comment]
Hi ,

Could you give us more information!

Regards.

**Comment by prepperz** [comment]
I can reproduce it on the demo. https://v4.phpfox.com/photo/11342/img_20180221_125556461-min/albumid_9072/

make sure you're not logged in.

**Comment by spirogg** [comment]
this happens to me too and with android phone chrome browser also 

1) go to menu and click photos 
then the bottom popup has more photos to view 
so if you refresh screen the bottom popup disappears...

your demo site also i try this
