### ISSUE TITLE
Uploading multiple Photos (uploading progress) 4.6.0

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2184]
## Steps to reproduce:
1. Create a New Album
2. Select multiple photos you want to share/upload
3. After selecting multiple photos you will see only 1 button "DONE"
4. After clicking 'DONE" the page is not moving or any notice to all users that the photo is still progress uploading.

## What is expected
After clicking "DONE" must have a uploading progress then users know what happened. Users think that after clicking "DONE" all images is already uploaded.

## Browsers tested
Chrome, Firefox

## Server informations
CentOS, Nginx, PHP Version 5.6.33

## phpFox versions
4.6.0

## Screenshots
...

**Comment by neil96** [comment]
Thanks @juniortimeline , it works as our designed. We will discuss with team and improve this process.

Regards.

**Comment by juniortimeline** [comment]
Thanks @neil96
