### ISSUE TITLE
Blog views only shows "1k+ views" stops displaying ticks then "2k+" then stops ticking again til 3k etc...

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2185]
Blog views only shows "1k+ views" and then stops. I hope this isn't the case for view counts in other sections.

**Comment by neil96** [comment]
And then it shows 2k+, 3k+, ...

**Comment by prepperz** [comment]
The way this id done feels like nothing is happening. The views should display ticks instead of 1k+, 2k+ etc....
