### ISSUE TITLE
Incorrect display of user action list on Notifications 

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2190]
## Steps to reproduce:
1. When you click on the Notifications icon

## What is expected
The appearance of a list of user actions. 

## Browsers tested
All

## phpFox versions
4.6.0 + Matherial (original version from PHPFox)

## Screenshots
![untitled-2](https://user-images.githubusercontent.com/11414490/36897256-21c2d50a-1e16-11e8-884a-a237a9ecdc50.jpg)

and data from DB

![untitled-3](https://user-images.githubusercontent.com/11414490/36897257-21e27392-1e16-11e8-880c-457fa6c11e2b.jpg)

## Steps by step:
1 Make (in AdminCP) clonecopy theme from Matherial to Mytheme
2 Twice check languages phrases
3 Rebuild core theme
4 Clear cache
5 Go to the Frontsite and check Notifications
6 We see incorrect display them

**Comment by neil96** [comment]
The var_name of this phrase is `app_db30c09abafe09086b94d5f5f705c115`. It might be this phrase is missing on your site.

Regards.

**Comment by CimborNet** [comment]
Hmm ... strange.
I have this phrase.
Why then be displayed exactly as shown in my picture?
Okay ... I'll deal with the problem.

![untitled-2](https://user-images.githubusercontent.com/11414490/37222490-9814c684-23cd-11e8-8260-955cbe00d3d7.png)
