### ISSUE TITLE
Error while editing users in AdminCP

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2191]
## Steps to reproduce:
1. Select the user and go to edit it
2. The first thing we see is that the user's image is replaced with the image of the one who edits (Administrator) #2180
3. Custom Fields "About Me" the user has this section empty (not filled), but after saving - this user has an entry that is set by the user who made the editing (like Administrator) !!! Why? (see in figure)

## Note
This problem appeared after the release, before such problems were not noticed.

In addition, this problem does not concern all users, but only those who have been edited by the site administration through AdminCP

## Browsers tested
All

## phpFox versions
Core Version:  4.6.0
PHP Version:  5.6.27
Theme: Matherial

## Screenshots
...
![untitled-2](https://user-images.githubusercontent.com/11414490/36898027-60433682-1e19-11e8-9838-6c4817cf63ce.jpg)

![untitled-3](https://user-images.githubusercontent.com/11414490/36898028-605e24a6-1e19-11e8-8918-28eb54c24c4c.png)

![untitled-4](https://user-images.githubusercontent.com/11414490/36898426-1a8e3e0a-1e1b-11e8-9adc-7ea01cfdab71.jpg)

**Comment by neil96** [comment]
All issues are reported and we fixed in phpFox 4.6.1

Regards.
