### ISSUE TITLE
RESTful API – Feed (user's profile) output includes private events

### ISSUE THREAD

**Issue by kirkkhua** [PHPfox-Official/phpfox-v4-issues#2192]
## Steps to reproduce:
1. Create a private event
2. Get all feeds from user's profile using RESTful API
3. Find an event in API output that's not accessible

## What is expected
Private events should not appear in Feed API output

## Browsers tested
-

## Server informations
-

## phpFox versions
4.5.3 beta 2

## Screenshots
![private_event_1](https://user-images.githubusercontent.com/5412712/37092827-ecbb4b40-2215-11e8-8069-250c3b3a42b3.png)
![private_event_2](https://user-images.githubusercontent.com/5412712/37092826-ec9b6c30-2215-11e8-93f3-b68333c9bcfe.png)
![private_event_3](https://user-images.githubusercontent.com/5412712/37092824-ec715e36-2215-11e8-82e3-8fcc65148983.png)

**Comment by david-phpFox** [comment]
Support in Mobile Api App
