### ISSUE TITLE
When in phrases search SEO and try to save some changes no access 403 forbidden error always 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2194]
## Steps to reproduce:
1. Go to admin cp
2. Globalization
3. Phrases search SEO and try to change something and save selected or save all 
It throws error 

Forbidden
You don't have permission to access /index.php/admincp/language/phrase/ on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request

## What is expected
... To save what you changed. 

## Browsers tested
(Example: Chrome, Firefox and Microsoft Edge)
Chrome 
## Server informations
...
Centos 7 with cloudlinux and cpanel whm
## phpFox versions
...
4.6.0 fresh install 

When I go to phrases and use the numbers below page 1 page 2 etc  and then make a change and try and save it works

**Comment by neil96** [comment]
This is a server issue. Could you double check your server configurations.

**Comment by spirogg** [comment]
Could.it be I have imunity360 from.cloudlinux modsecurity issue ??

**Comment by neil96** [comment]
We do not have this environment. You can disable this mode and try again.

Regards.

**Comment by spirogg** [comment]
was imunity360 and modsecurity false positives, now it works sorry
