### ISSUE TITLE
When you go to main site click on sign in sign up bottom link gives wrong form 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2203]
## Steps to reproduce:
1. Go to main site https://v4.phpfox.com
2. Click on bottom link says sign in. Now click on sign up then sign in it's the wrong form 
3. 

## What is expected
...to be at the right form for sign in and the right form for sign up 

## Browsers tested
(Example: Chrome, Firefox and Microsoft Edge)
Chrome Android phone. Will test at home later windows 10 and report back here. 
## Server informations
...

## phpFox versions
...
Fresh install 4.6.0 also your demo https://v4.phpfox.com

## Screenshots
...
![screenshot_20180312-155759](https://user-images.githubusercontent.com/17736688/37309690-afeda32c-260f-11e8-9d34-71bf6597f2dc.png)
![screenshot_20180312-155752](https://user-images.githubusercontent.com/17736688/37309697-b4db9114-260f-11e8-88b4-1d32ad8f19c3.png)

**Comment by spirogg** [comment]
can you please check this #2206 and see if its related to #2203

**Comment by neil96** [comment]
Sure @spirogg !
