### ISSUE TITLE
BUG :: create new template>Material> upload logo-save as default - main page SIGN IN NOW link is dead

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2204]
EDITED ## Steps to reproduce:
1. NEW THEME 
SELECT MATERIAL 
NAME IT 
UPLOAD LOGO 
SAVE AS DEFAULT 
Log off as admin and do not login just go to home page you cant click on sign in link at the bottom
2. its completly dead link does not do anything
3. 

## What is expected
...
to get sign in page
## Browsers tested
(Example: Chrome, Firefox and Microsoft Edge)
chrome - edge windows 10 and android crome phone
## Server informations
...

## phpFox versions
...fresh install 4.6.0 cant check your website demo cause you use material template not new renamed template. 

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/37315608-808b81c6-2628-11e8-9174-e8ed0a11d326.PNG)

**Comment by spirogg** [comment]
Here is Android mobile 



![screenshot_20180312-191059](https://user-images.githubusercontent.com/17736688/37315757-410a711e-2629-11e8-943b-5bd01e89ab64.png)

**Comment by neil96** [comment]
Hi @spirogg ,

Could you tell me the name of this setting `turn off option to view site`

Regards.

**Comment by spirogg** [comment]
@neil96 ok i figure it out - make new theme name it (whatever you want)  then upload logo other than phpfox then try it doesnt work those links

**Comment by spirogg** [comment]
@neil96 
Steps to reproduce:

to to themes select: NEW THEME
SELECT MATERIAL
NAME youe theme whatever
UPLOAD A LOGO
SAVE your new theme AS DEFAULT
Log out of website 

Go to home page and you will see you cant click on sign in link at the bottom
its completely dead link does not do anything
