### ISSUE TITLE
PhpFox Favicon still show on our site

### ISSUE THREAD

**Issue by juniortimeline** [PHPfox-Official/phpfox-v4-issues#2205]
## Steps to reproduce:
1. https://community.phpfox.com/forum/thread/56905/default-phpfox-logo-fav-icon-randomly-randomly-appears-instead-of-site-logo/

## What is expected
To avoid PhpFox favicon on our site that shows anywhere on our site link.

## Browsers tested
(Example: Chrome, Firefox and Microsoft Edge)
Chrome, Firefox
## Server informations
Apache and Nginx

## phpFox versions
4.6.0

## Screenshots
This issue is belong to this community forum https://community.phpfox.com/forum/thread/56905/default-phpfox-logo-fav-icon-randomly-randomly-appears-instead-of-site-logo/

**Comment by spirogg** [comment]
#2199
this is fixed in 4.6.1

**Comment by neil96** [comment]
Duplicate of #2199

**Comment by juniortimeline** [comment]
@neil96 issue #2199 is different issue. I'm talking about default phpFox favicon that alwys show anylink comes from our website. Thank You
