### ISSUE TITLE
enable bundle js/css., then creating new material theme and after uploading your logo and setting as default - signup links dont work

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2206]
@neil96
Steps to reproduce:
Enable bundle js/css.
GO to themes select: NEW THEME
SELECT MATERIAL
NAME your theme whatever name you give it
UPLOAD A LOGO
SAVE your new theme AS DEFAULT
Log out of website

Go to home page and you will see you cant click on sign in link at the bottom
its completely dead link does not do anything

**Comment by neil96** [comment]
Hi @spirogg ,

I can't reproduce with above steps. Could you give us more information.

Regards.

**Comment by spirogg** [comment]
Hi @neil96 ,

If I use material theme that comes with phpfox it works. But when I click on create new theme and select material , to make a duplicate , then I upload my logo, upload new photos for main page and also new photos for each other default area in the new template I create. Then After I click save as default and use my new template. Those links don't work. ?? It always happens. I tried to delete theme , restarted need theme and uploaded logo and default photos for the theme and it always does this. ?

**Comment by spirogg** [comment]
when i click on sign in now

it says 
in the bottom left of browser (Chrome Browser) 

> javascript:void(0);

I also test in Edge same thing doesn't work

thanks

Spiro

**Comment by neil96** [comment]
I can reproduce now. It happens you we enable bundle js/css.

**Comment by spirogg** [comment]
i am still having this issue after upgrade 4.6.1

**Comment by neil96** [comment]
I see you create new issue. But I can't reproduce. Please give us more information, in new issue. Thanks!
