### ISSUE TITLE
Latin (UTF-8) characters in Blog title

### ISSUE THREAD

**Issue by hexplor** [PHPfox-Official/phpfox-v4-issues#2207]
## Steps to reproduce:
1. Create example blog item with title: **Usiąść na ściółce**
2. Url (Item permalink) will look like that: **usi???-na-?ci??ce**

## What is expected
Expected blog permalink: **usiasc-na-sciolce** (This is how Wordpress do it and all other CMS)

## phpFox versions & System Info
![](https://monosnap.com/file/sDtVuFYpq734uQX34AUk55z65mpXwj.png)

## Screenshots
![](https://monosnap.com/file/lzWIAmDOHu87S4BUnRJeDHpX79azh3.png)

**Comment by neil96** [comment]
It does not display `?` for unicode text. We designed that the title displays original text.

Btw, I can't see your screenshots.

Regards.

**Comment by hexplor** [comment]
Hey, 
Thanks for quick reply. I updated code so it can display the screenshots.
Did you try the exact text ? Maybe that bug is related to specific php version. Gonna do more investigation..

**Comment by hexplor** [comment]
Ok, 
So i did some further testing. I thing it's related to some server or phpFOX setting. When i added this to **PF.Base/file/settings/debug.sett.php**

```
<?php
define('PHPFOX_LANGUAGE_SHORTEN_BYPASS', true);
```

Then issue is gone.

**Comment by hexplor** [comment]
Ok, I fixed it myself..
I think you guys have a small issue in your cleanTitle function:

**PF.Base/include/library/phpfox/url/url.class.php**, line 775

```
        **$sTitle = strtolower($sTitle);**
        if (function_exists('mb_strtolower')) {
            $sTitle = mb_strtolower($sTitle, 'UTF-8');
        } else {
            $sTitle = strtolower($sTitle);
        }
```

You'are using strtolower function TWICE. First, before IF statement, second, when, using mb_strtolower check. That means that whole IF statement is useless, because you lowered strings before. More. strtolower uses current locale (!). This was causing my bug to happen because mb_strtolower($sTitle, 'UTF-8') was used AFTER strtolower which already messed up my url . 

https://justbugs.wordpress.com/2012/03/07/php-strtolower-special-characters-not-converted/

Also:
http://php.net/manual/pl/function.strtolower.php (see first comment about Polish language).

Hope hat helps :)

**Comment by neil96** [comment]
Hi,

I do not see new information to reproduce this issue.

Regards.

**Comment by hexplor** [comment]
??
Well..
I told you exactly where the error in your code is, you have duplicate functions in url.class.php. You first convert using strtolower and then using a check for mb_strtolower which is doing the same, and then if it does not exist you convert it once again using strtolower. Also i gave you examples and links where strtolower is related to server locale. To reproduce that issue you have to set up your local server to use default locale. Everything (including potential issues) is described in php article: http://php.net/manual/en/function.strtolower.php . You have right code , just one line too much (see my above post https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2207#issuecomment-374878895)

**Comment by neil96** [comment]
```php
 $sTitle = strtolower($sTitle);  <--- this should be removed
        if (function_exists('mb_strtolower')) {
            $sTitle = mb_strtolower($sTitle, 'UTF-8');
        } else {
            $sTitle = strtolower($sTitle);
        }
```

The first `strtolower` is unnessary, but it does not cause an error.  

Regards.

**Comment by hexplor** [comment]
Hello,
It actually does on my environment as first strtolower blocks mb_strtolower which has proper support for latin characters and UTF-8. I know it only happens on certain configurations but it happened to me and for my friend install as well. This looks like a minor thing but I'm just reporting it. You will do what you think it's proper :) I can always modify that file manually :) Have a nice day :)
