### ISSUE TITLE
Login form on mobile

### ISSUE THREAD

**Issue by kirkkhua** [PHPfox-Official/phpfox-v4-issues#2209]
## What happened?
When I try to type email and password in login form on mobile cursor jumps off the field.

## Steps to reproduce:
1. Open v4.phpfox.com from mobile device
2. go to login page
3. type something in email and password fields

## What is expected?
Cursor should be in the same field we're editing, it should not jump or display in the middle of the screen.

## Browsers and Devices tested
Safari on iPhone 6+

## Server information
-

## phpFox version
phpFox 4.6.0

## Screenshots
![img_98893bb50503-1](https://user-images.githubusercontent.com/5412712/37913391-72068c68-311d-11e8-9f82-2486a8d4e1ed.jpeg)

**Comment by david-phpFox** [comment]
This issue belong to Safari browser, please upgrade to newest IOS version to check it again. It has fixed on newest version.
