### ISSUE TITLE
addlink for create album is missing in add song

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2211]
## What happened?
...

adding a song is what users will click on to upload song, they can get really confused when they see selector to select album, ( where is link to create album) 
## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...
Create a link in the add song area so user doesnt have to look for add album under my albums

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![image](https://user-images.githubusercontent.com/17736688/37954251-dc136066-316a-11e8-9051-fa14c942c08d.png)

**Comment by neil96** [comment]
This is not a bug. If you'd like this feature, please post request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).
