### ISSUE TITLE
pages share feature just says admin shared... but noit say what or from where 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2212]
## What happened?
...
shared a page and all it says id admin shared ... not what or from where  ?
## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
... should say admin shared whatever he shareds and from where pages

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![when adding shared it just says admin shared but not specify what shred and from where in pages](https://user-images.githubusercontent.com/17736688/37955596-9d0eb858-316e-11e8-8326-6ef5b3e931b8.PNG)

**Comment by spirogg** [comment]
also when i updated cover photo of my page, it doesnt specify i uodated cover photo from my page it just says admin updated cover photo - should say admin updated pages cover photo

**Comment by neil96** [comment]
It's working as our designed. If you'd like to change them, please post request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).
