### ISSUE TITLE
Forgot Password - takes you to signup page after you submit, should tell you to check email and then

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2215]
## What happened?
...
when you have forgotten your password and you submit your email address to change password it should tell you to check email, then when you click email to change password it takes you to signup page not telling you to check your email for password ??
## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
... when you submit email it should say go check your email to get link to change your password, then when you click link it should tell you to check your email again for your temporary password..

or user might get confused why its not allow him or her to change there password when they see the sign in screen after clicking the email to change their password

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.0
...

## Screenshots
...

**Comment by neil96** [comment]
Hi @spirogg ,

We have the message at the bottom, but it will automatically disappear after a short time. This is our rule. If you'd like to change it, please post a request us [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.

**Comment by spirogg** [comment]
@neil96 on mobile device you cannot read the whole message just FYI.

**Comment by neil96** [comment]
Thanks @spirogg , we notes this point and improve it in next versions of phpFox.

Regards.
