### ISSUE TITLE
Material theme, Paging Mode turned to next prev or numbered doesn't work i change in apps too but not working

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2216]
## What happened?
... i went to turn on paging to Next Prev Button or Numbered  in admincp doesn't work when you click the home button on the main website, the feeds just scroll down and  and scroll again and again until it has no more feeds to show, I want to have next prev buttons or numbered , I also tried setting all apps to next prev and that doesn't work either

## Steps to reproduce:
1. admincp
2. select site settings 
3. Paging Mode
select Use Next Prev buttons or use pagination with page number 
Please select paging mode for all items on your site.

## What is expected?
...
should be able to switch to those features and it should work..
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 cloud linux php 5.6 and 7.0
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.0
## Screenshots
...
![feed keeps scrolling next prev not working](https://user-images.githubusercontent.com/17736688/38057451-245ce5aa-32a5-11e8-90f8-2e748ac0803f.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

Could you turn on debug mode, then open **Inspect** (chrome developer tool, or similar if you use other browser) -> select tab **Network**, again try again. If you can see error 500 request, please paste that error here.

Thanks!

**Comment by spirogg** [comment]
@neil96 i don;t see any error 500 all 200 but when i make the change it is always stuck on scroll down to view more? I will make a ticket you can see it yourself on my site will have all login info for you to check please i cannot figure it out

**Comment by spirogg** [comment]
Ticket Created  and debug mode is ON

**Comment by neil96** [comment]
Sorry @spirogg for not read careful your message. At feed, we only support load more. There are no way no switch to other paging mode

Regards.

**Comment by spirogg** [comment]
Ok in Feed this is not an option is this also not option for feed in pages or groups ? where would this apply ?

**Comment by neil96** [comment]
It does not apply in pages/groups/event feed too. It applies in browse items of each app. Example: blog index, event index, ...

Regards.

**Comment by spirogg** [comment]
Ok thank you sir. Would be nice option to have for front page when you are on home page. If I want to click on invite contact read privacy terms rss while I'm on that page. I have to wait till I scroll all the way down to click in it. Maybe in another version you could make this load.more button a option.

**Comment by neil96** [comment]
Thanks @spirogg , we will discuss with team this point.

**Comment by spirogg** [comment]
https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/635
