### ISSUE TITLE
Admin profile and video detail page layout changed.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2218]
## What happened?
Admin profile page and video detail page layout changed (they just changed)... I don't know why it happened as I had not done anything. I'm guessing 4.6.1 will be totally different and would correct this issue?

## Steps to reproduce:
1. I just went to the Admin profile page and the Video detail page
2. 
3. 

## What is expected?
See images.

## Browsers and Devices tested
Firefox, Windows 7

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.0
...

## Screenshots

![layout-change-profile](https://user-images.githubusercontent.com/17064302/38097773-2dba4f60-336e-11e8-8c16-a72342062fc6.jpg)

![layout-change-video](https://user-images.githubusercontent.com/17064302/38097787-343c9514-336e-11e8-99f1-7398c813253e.jpg)

**Comment by starplan** [comment]
I think this may have happened when I upgraded firefox to the latest version 59.0.2.

**Comment by neil96** [comment]
Could you give us more information.
What's your current theme?

I guess this issue comes from 3rd-party or custom theme

**Comment by starplan** [comment]
Material Theme... The only customization is the changing of colors via css. Everything was working fine, I have not edit anything to do with the theme for a while. That's why the only thing I can think of is the Firefox update.

**Comment by starplan** [comment]
Ah... I think I might know. The only thing that I have done is added analytics tracking code. I will remove it and see if it changes anything.

**Comment by starplan** [comment]
Yep, its the analytics code.
