### ISSUE TITLE
RESTful api - user returns wrong value for is_online 

### ISSUE THREAD

**Issue by hexplor** [PHPfox-Official/phpfox-v4-issues#2219]
## What happened?
So I'm using your RESTful API which is great addition to phpFOX. Thanks. However there is one small issue which is actually making my integration kinda tough. 
http://example.com/restful_api/user/mine/ it returns plenty of data including ```is_online``` key which would be VERY useful for external services. Unfortunately it does not work like expected. Sometimes it returns 1, sometimes 0, and I even saw it to return 2. 
For example when i logout it returns 0. When i log in, in stays 0 for few minutes then it's set to 1, then i log out, it's still 1. I log In .. it's 0. I thought it's cache related but it look like it's totally random.

## Steps to reproduce:
1. Create APP with RESTful API
2. Request access token 
3. Make a request using POSTMAN or any other JSON readers to http://example.com/restful_api/user/mine/ 
4. Try to log in, log out few times. You will noticed that the "is_online" key return different values in random cases. 

## What is expected?
Logged in:
```"is_online": "1",```
Logged out:
```"is_online": "0",``` or ```"is_online": "null",```

## Server information
PHP Sapi: | apache2handler
PHP safe_mode: | False
PHP open_basedir: | False
PHP Disabled Functions: | None
PHP Loaded Extensions: | Core date libxml openssl pcre sqlite3 zlib bcmath bz2 calendar ctype curl dba dom hash fileinfo filter ftp gd gettext SPL iconv json ldap mbstring session standard odbc mysqlnd PDO pdo_mysql PDO_ODBC pdo_sqlite Phar posix Reflection mysqli shmop SimpleXML soap sockets exif sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip apache2handler apcu imagick yaml ionCube Loader Zend OPcache xdebug
Operating System: | Darwin
Server Time Stamp: | March 30, 2018, 8:12 am (GMT)
GZIP: | Enabled
SQL Driver Version: | MySQL 5.5.5-10.2.11-MariaDB
SQL Slave Enabled: | No
SQL Total Slaves: | N/A
SQL Slave Server: | N/A
Memory Limit: | 0.5 b (-1)
Load Balancing Enabled: | No

## phpFox version
4.6.0
--

## Screenshots
![rest](https://monosnap.com/file/RqhNjs0dfq6bT3iaR9d6UttGlkiKJV.png)

**Comment by hexplor** [comment]
I think with 4.6.1 there's progress with that. in 4.6.1 is_online returns null for offline users, and user id for online users. So in 4.6.1 it basically works as expected.

**Comment by david-phpFox** [comment]
Will support in Mobile API App
