### ISSUE TITLE
Bad (with a large free space) display pictures on the board's

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2220]
## What happened?
When I put pictures on my board, they are displayed in such a way that there is a large free space, and only then a picture.

## Steps to reproduce:
1. After installing the new clean version of phpfox 4.6.0 I put two test photos on my administrator's board.

## What is expected?
See attached photos

## Browsers and Devices tested
Chrome 65.0.3325.181, Edge on Windows 10

## Server information
CentOS 7, php 7.1 apache

## phpFox version
phpFox 4.6.0

## Screenshots
![buq1](https://user-images.githubusercontent.com/38014237/38209006-2afed1e0-36b3-11e8-83d1-9d68b6b5b20b.png)
![buq2](https://user-images.githubusercontent.com/38014237/38209007-2b1d9c7e-36b3-11e8-8157-0d7ae3c37230.png)

**Comment by starplan** [comment]
Try rebuilding core theme and clearing the cache.

**Comment by kerstar** [comment]
It works! Thank you for your help. Problem solved.
