### ISSUE TITLE
RESTful api - broken user_image

### ISSUE THREAD

**Issue by hexplor** [PHPfox-Official/phpfox-v4-issues#2221]
## What happened?
RESTful api returns broken image name. 

## Steps to reproduce:
1. Make sure your user image is set
1. Make a request for http://example.com/restful_api/user/mine/
2. RESTful api will return something like: 

```
"user_image": "2018/03/834e4d8505273a57520388f459f010e2%s.jpg",
```

## What is expected?
```
"user_image": "2018/03/834e4d8505273a57520388f459f010e2.jpg",
```

In short. Phpfox adds **%s**, not sure why. Original image is without spaces.

## Server information
PHP Sapi: | apache2handler
PHP safe_mode: | False
PHP open_basedir: | False
PHP Disabled Functions: | None
PHP Loaded Extensions: | Core date libxml openssl pcre sqlite3 zlib bcmath bz2 calendar ctype curl dba dom hash fileinfo filter ftp gd gettext SPL iconv json ldap mbstring session standard odbc mysqlnd PDO pdo_mysql PDO_ODBC pdo_sqlite Phar posix Reflection mysqli shmop SimpleXML soap sockets exif sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip apache2handler apcu imagick yaml ionCube Loader Zend OPcache xdebug
Operating System: | Darwin
Server Time Stamp: | March 30, 2018, 8:12 am (GMT)
GZIP: | Enabled
SQL Driver Version: | MySQL 5.5.5-10.2.11-MariaDB
SQL Slave Enabled: | No
SQL Total Slaves: | N/A
SQL Slave Server: | N/A
Memory Limit: | 0.5 b (-1)
Load Balancing Enabled: | No

## phpFox version
phpFox 4.6.0

**Comment by neil96** [comment]
We add extra `%s` to help you easy to change custom thumbnail with function `sprintf`

To use original file:
```php
$user_image = sprintf($user_image, '');
```

To use thumbnail 120:
```php
$user_image = sprintf($user_image, '_120');
```

Regards.

**Comment by hexplor** [comment]
Thank you very much :)
