### ISSUE TITLE
sign in shows signup form signup shows sign in login form still ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2224]
----------------------------------------

## What happened?
...sign in links on front page still same issue #2203

 sign in shows signup form 

signup shows sign in login ?

i have Bundle JavaScript & CSS off casue if i turn on links dont work  at all ?

## Steps to reproduce:
1. i create a new theme from Material theme and name it my name
2. then I turn OFF Bundle JavaScript & CSS
3. then I
have search OFF for guests so they cant search your website unless members, have all pages groups music videos OFF so no one can view unless signed up. then click on sign in link
 
same issue as this #2203 

not fixed after upgrade from 4.6.0 to 4.6.1 for me ?

## What is expected?
...  sign in shows signin form 

signup shows sign up form

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome browser latest version 
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1 upgrade
...

## Screenshots
...
here is this issue in photo below 

![sign up](https://user-images.githubusercontent.com/17736688/38765077-950946d0-3f80-11e8-920f-62946298de0f.PNG)

![login](https://user-images.githubusercontent.com/17736688/38765081-a316ccf2-3f80-11e8-9d94-09fcc6dabaf6.PNG)

**Comment by neil96** [comment]
Could you give us detail steps to reproduce

**Comment by spirogg** [comment]
i create a new theme from Material theme and name it my name
then I turn ON Bundle JavaScript & CSS
then I 
have search OFF for guests so they cant search your website unless members, have all pages groups music videos OFF so no one can view unless signed up. then click on sign in link  

click on sign In now link in photo you will see and not working

![sign in now not working still](https://user-images.githubusercontent.com/17736688/38765069-69de06ee-3f80-11e8-8a8c-91db12572f41.PNG)

**Comment by spirogg** [comment]
sorry this is another issue in photo above
here is this issue in photo below 

![sign up](https://user-images.githubusercontent.com/17736688/38765077-950946d0-3f80-11e8-920f-62946298de0f.PNG)

![login](https://user-images.githubusercontent.com/17736688/38765081-a316ccf2-3f80-11e8-9d94-09fcc6dabaf6.PNG)

**Comment by spirogg** [comment]
@neil96 i fixed the form with details

**Comment by spirogg** [comment]
I did fresh install 4.6.1 and now it works
