### ISSUE TITLE
Bundle JavaScript & CSS on signup links dont work

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2225]
upgraded to 4,6,1 but still this issue persist.

signup  and sing in links dont work with this feature on Bundle JavaScript & CSS ON

**Comment by neil96** [comment]
Could you give us detail steps to reproduce.

**Comment by spirogg** [comment]
i upgraded to 4.6.1 followed instructions... then I tried enter my ftp info sftp info and tried using file in settings.    
clicked on Remove files no longer used - then clicked cache then delete cache then click on check Modified Files and check unknown files and i still see files there ?? 
is what you see on your end an upgrade from 4.6.0 to 4.6.1 or just fresh instal 4.6.1 cause I dont have fresh install yet of 4.6.1 to check if it is only because upgrade or also on fresh install ?

**Comment by spirogg** [comment]
created new theme >> from Material theme, rename new theme to my name
javascript bundle ON

search for whole site off unless you are registered user
no forums music groups pages etc.. all off unless you are registered user 
go to main website and 
>>>>>>>>>>.click on sign In now link in photo you will see and not working

![sign in now not working still](https://user-images.githubusercontent.com/17736688/38765069-69de06ee-3f80-11e8-8a8c-91db12572f41.PNG)

**Comment by spirogg** [comment]
tested on windows 10 edge browser and chrome browser

**Comment by spirogg** [comment]
@neil96 same exact issue as this ticket that was marked fixed and closed #2206

**Comment by spirogg** [comment]
I did fresh install 4.6.1 and now it works
