### ISSUE TITLE
Turn off full ajax mode  OFF slows site down really slow after a minutes.. 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2226]
## What happened?
Turn off full ajax mode OFF = I want full ajax mode on so I click to turn off. that means its on ( full ajax mode) so then i kept on clicking on music photos etc.. for a minutes and all of a sudden it slows down the site to almost  stop. waiting waiting waiting waiting admincp also really slow. 

## Steps to reproduce:
1. Turn off full ajax mode OFF
2. keep on clicking on music photos groups etc.. for a 1 minutes to 2 minutes really fast as you have alot of users

## What is expected?
should work as normal and fast not slow down site 
if I turn setting to ON so there is no Full Ajax Mode. it runs really fast ? 
## Browsers and Devices tested
chrome browser latest version 

## Server information
centos 7 php 7

## phpFox version
4.6.1 upgraded

## Screenshots
![capture](https://user-images.githubusercontent.com/17736688/38767146-7680029a-3fa2-11e8-90ad-102f181c235d.PNG)

```
====================================================
+++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++++++++++++++++++
```

![capture](https://user-images.githubusercontent.com/17736688/38767228-45455e54-3fa3-11e8-90ce-358d80b7b52c.PNG)

**Comment by neil96** [comment]
Could you give us more information.

**Comment by spirogg** [comment]
if i have full ajax ON after a little while of clicking on just different parts of the website, it slows down the site really really bad. continuously - click on photos music groups members more and more and more as if you had a whole bunch of users clicking on your site, it will start to slow down like as if it were going so slow worse than 2G on a cellular phone ( speed 2G )

**Comment by spirogg** [comment]
@neil96 updated your template

**Comment by spirogg** [comment]
I did fresh install 4.6.1 and now it works
