### ISSUE TITLE
cant reposition user cover - pages cover - group cover - no button to save position ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2227]
click to change cover photo - then  try to reposition in user cover, group cover, page cover, no save button to save where you reposition it too ? upgraded from 4.6.0 to 4.6.1

**Comment by neil96** [comment]
We fixed in pages/groups 4.6.1. They will be released soon

**Comment by spirogg** [comment]
@neil96   >>>>>>>>>>>>>>>>Please this is for users cover photos also

**Comment by neil96** [comment]
The users cover photos work with me. Could you give us detail steps.

**Comment by spirogg** [comment]
ok i just installed 4.6.1 fresh install and it works.

**Comment by hasanaffe** [comment]
if i choose reposition on pages, save button doesn't appear, i use version 4.6.1
how can i fix this issue?

**Comment by tagdo** [comment]
if i choose reposition on pages, save button doesn't appear, i use version 4.6.1
how can i fix this issue?
