### ISSUE TITLE
photos >my photo > click on first photo > next button - prev button - swatch at the bottom not working

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2228]
## What happened?
...click on photos go to My photos, you click on first photo of yours

now you see at the bottom of page the list of photos from the (swatch) if you click on another photo in the swatch it disappears.. 

If you click on  photos again > My photos> click your first photo > then try to click the next button you move to the next photo but the next button - previous button are gone. 
so you cant view more photos ? 

## Steps to reproduce:

**If I have Turn Off full Ajax mode = NO then photos swatches next prev buttons work.**

**If I have Turn Off full Ajax mode = YES then swatches and next prev buttons don't work**

1. click on  photos > My photos>
2. click your first photo > then try to click the next button
3. next button - previous button are gone so is swatch of photos at the bottom of page

## What is expected?
... should be swatch stay in place and have next and previous button available to view all the photo selction

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome browser latest version 

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7
...

## phpFox version
(Example: phpFox 4.6.0)

4.6.1 fresh install 
...

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/38767003-3b38c2f0-3fa0-11e8-8540-7ca9ddc6e7fd.PNG)
![capture](https://user-images.githubusercontent.com/17736688/38767018-67557676-3fa0-11e8-8350-ae73b8dd0ff0.PNG)
![capture](https://user-images.githubusercontent.com/17736688/38767040-b0968f28-3fa0-11e8-842c-6aa53d7b4c54.PNG)

**PS. 

If you go to your timeline - then it works as expected  
swatch doesn't disappear if you click on any photo in the swatch
and 
next button - prev button work correctly.. you get to view all your photos**

**Comment by spirogg** [comment]
If I have full Ajax mode = OFF this works.
But site slows down really slow after clicking through a few photos. 

 If I have full Ajax mode = ON 
Then there is no next prev buttons but site s not slow really fast. ??

**Comment by neil96** [comment]
Hi @spirogg ,

I can't reproduce. Could you double check. The latest phpFox photo version now is 4.6.1.

Regards.

**Comment by spirogg** [comment]
HI @neil96  if you do this go to admincp >> settings >> Turn off full ajax mode = YES 

then go to photos and click on a photo you don't have the swatch and next or previous buttons 

is t

**Comment by spirogg** [comment]
but if you do admincp >> settings >> Turn off full ajax mode=  NO

then go to photos and click on a photo 
then it works = you see the swatch at the bottom and the next previous buttons

**Comment by spirogg** [comment]
by the way I do have 4.6.1 photos fresh install of 4.6.1 not an upgrade just fresh install 4.6.1

thanks


my photo shows 4.6.1 photo app
![capture](https://user-images.githubusercontent.com/17736688/38844500-61c70718-41b9-11e8-87a5-737194af34f6.PNG)
