### ISSUE TITLE
click photo then all albums i get Unable to find the page you are looking for.

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2230]
Hi i upgrade 4.6.0 to 4.6.1 if i click on photos then all aulbums i get this Unable to find the page you are looking for.
below i see photos 

![all aulbums error](https://user-images.githubusercontent.com/17736688/38756353-d223df8c-3f2e-11e8-8663-f04b7649418e.PNG)

**Comment by spirogg** [comment]
if i click on LGBT's Profile Pictures I get another error see photo below

![if i click here i get another error](https://user-images.githubusercontent.com/17736688/38756457-39cd8386-3f2f-11e8-8c9e-c56500e505c4.PNG)

![another error](https://user-images.githubusercontent.com/17736688/38756471-40c8b0c0-3f2f-11e8-8522-8e235dbc5ba9.PNG)

**Comment by spirogg** [comment]
**this happens again when I use these features on** 

Display User Profile Photos within Gallery
Disable this feature if you do not want to display user profile photos within the photo gallery.

Display User Cover Photos within Gallery
Disable this feature if you do not want to display user cover photos within the photo gallery.

Display photos/albums which created in Group to the Photo app
Enable to display all public photos/albums to the both Photos/Albums page in group detail and in Photo app. Disable to display photos/albums created by an users to the both Photos/Albums page in group detail and My Photos/Albums page of this user in Photo app and nobody can see these photos/albums in Photo app but owner. 
Notice: This setting will be applied for all types of groups, include secret groups.

Display photos/albums which created in Page to the Photo app
Enable to display all public photos/albums to the both Photos/Albums page in page detail and in Photo app. Disable to display photos/albums created by an users to the both Photos/Albums page in page detail and My Photos/Albums page of this user in Photo app and nobody can see these photos/albums in Photo app but owner.

Display User Timeline Photos within Gallery
Disable this feature if you do not want to display user timeline photos within the photo gallery.

**Comment by spirogg** [comment]
if I turn them off I don;t have that option to see error ?

**Comment by spirogg** [comment]
also noticed in groups / whatever_groups_you_created / photos

i click on profile photo get the same error
By LGBT
3 hours ago in LGBT's Profile Pictures

![click here](https://user-images.githubusercontent.com/17736688/38759547-130e8aa8-3f3c-11e8-80ff-6fa3c47d25d1.PNG)



![unable to find the page you were looking for groups profile photo link](https://user-images.githubusercontent.com/17736688/38759549-189e20b4-3f3c-11e8-8d99-a51c7a3ebf91.PNG)

**Comment by spirogg** [comment]
seems to be with old groups profile pics only, cause I make new group add prifile pic and it works good. so not sure what the issue

**Comment by neil96** [comment]
Could you give us detail steps to reproduce.

**Comment by spirogg** [comment]
this is old profile picture pic i had in 4.6.0 i am not sure why ? it happens ? 
but i go to groups click on an old group, then click on group photos, then click on photo that is profile photo, the on the top left of that profile photo there is a link (groups name profile pictures if you click on this link that is what happens, then i just notice if I am click on the button (little gear) to right > when you click on it - it says >> edit this album 

you cannot click on the link - it doesn't work ? see photo

![new profile picture uploaded for this group and it is the same thing](https://user-images.githubusercontent.com/17736688/38764781-fc872652-3f7a-11e8-89bf-dc1ed2884499.PNG)

**Comment by spirogg** [comment]
PS i delete the old profile picture and just added a new picture for the profile, and in this group it still has the same error and the edit this Album link doesn't work ?

**Comment by spirogg** [comment]
now I am getting this error on new group profile pictures




![ok now i see in new group prifle pic same errors](https://user-images.githubusercontent.com/17736688/38764907-80a2ecda-3f7d-11e8-976a-008b4bdef152.PNG)

**Comment by spirogg** [comment]
plus the right side (edit this Album) if you look into the last support request I have in phpfox.com support, you have my login details if you want to see for yourself what i am explaining i dont mind you can do as you like to check it fix it work on it,...  please help yourself

**Comment by spirogg** [comment]
@neil96 

**OK i think this seems to be issue** when you have all the options to add profile photos cover photos pages photos and group photos in Photo Gallery ON

**the tiny picture of your profile says pages/5 and the link says group/5 the TINY profile picture should link to group/5 but it links to pages/5 which is not valid so error shows**

see photo

![pages vs group in group profile](https://user-images.githubusercontent.com/17736688/38765886-5a3e645e-3f8f-11e8-8e00-560bdf8df1e8.PNG)
