### ISSUE TITLE
Remove files no longer used and check modified files - never delete again same issue ??

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2231]
Remove files no longer used and check Modified Files still not working after installing some phpfox apps

119 file(s) failed

i try to clear via sftp/ssh - ftp - file 

Remove files no longer used 
 cleared cache
Check Modified files 
also tried 

Remove files no longer used 
 cleared cache
Rebuild core theme
find missing phrases
Check Modified files 

 nothing still same thing ?? read post below for more info what happened please 

phpfox version 4.6.1.b3

centos 7 php7 apache

chrome browser

**Comment by spirogg** [comment]
this is to me the same issue as before, upgrade

**Comment by spirogg** [comment]
sorry didnt see same one marked as bug

**Comment by spirogg** [comment]
When installing an app from store. This happens again 4.6.1b3 

After I installed better ads and backup and restore also single device login - from phpfox apps

- go to admincp >> apps>> find more app>> select better ads >> Get App 
the app installs and it seems it make chmod folder/ folders 755 ??? so I change to 777 folders and files and tried to ( Remove files no longer used - from admincp ) cleared cache and Check Modified files   still same thing
 
- Something after installing of apps is changing something (chmod)  that won't allow to Remove files no longer used and they show in check modified files or show missing files.

- So what I did was I deleted the apps just to test, then I Remove files no longer used clear cache and Check Modified files and it was clean ??
 Except  for : 
PF.Base/module/language/include/service/language.class.php | MODIFIED (this never delete) ?



- Then i reinstall the apps and did the same Remove files no longer used checked same thing. Shows files modified and a lot of files missing. 

PF.Site/Apps/core-better-ads/app.lock | MISSING
PF.Site/Apps/core-better-ads/Block/Sponsored_Event.php | MISSING
PF.Site/Apps/core-better-ads/Block/Sponsored_Quiz.php | MISSING
PF.Site/Apps/core-better-ads/hooks/quiz.template_block_entry_links_main.php | MISSING

plus many more missing? 

maybe something changed in app vs core ?

 Not sure but this is still a bug after installing apps. Not remove files no longer used .. 

Thanks

**Comment by neil96** [comment]
Thanks @spirogg ,

We also append the files from 3rd-party and it's the root cause. We will double check this case with team.

Regards.

**Comment by spirogg** [comment]
@neil96 

does this affect the script from working correctly or apps from updating - installing correctly. ?? Just wondering. 

Thanks

**Comment by neil96** [comment]
Hi @spirogg ,

As discussed with team, we will keep the current rule. Btw, we will notice for developers this case. 
If you find unknown/modified files from a 3rd-party apps, please report issue to the app owner.

Regards.
