### ISSUE TITLE
When set website to not show search or members, photos,blogs etc 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2232]
When we set the website to not show members photos blogs videos etc. Or not show search bar. So users have to sign up to see stuff on website. Works but not 100% 

If you get an email from notification saying someone commented on your page. 
When you click the link you should get the sign in form or redirect to main website so they need to login to view but if I click on the email link from an notification. It shows me - so this part is not blocking someone from view website. Should be redirect tommain page or sign in popup until that users logs in to view.

**Comment by neil96** [comment]
If a user access to a detail link, we will use privacy of this item.
