### ISSUE TITLE
group photos don't have the swatch or next prev buttons when view group photos ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2235]
in groups when you click photos and try to view photos it doesn't have the swatch at the bottom or the next prev button. So you can only view 1 photo then have to click back browsers button or the
Groups / whatever_page/ photos
link to see the other photos ( should have the photo swatch at bottom and the next prev link like timeline photos

**Comment by neil96** [comment]
We only support these button if you are viewing an album, or photos in feed (upload multi photos).
