### ISSUE TITLE
newly created group - profile pic in user profile area not showing see photo

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2236]
## What happened?
...
i updated 4.6.0 to 4.6.1 and created a new group added a profile photo but its not showing in photo below

if you click your profile on the left side under groups the profile pic is not showing

Defer Profile Images was ON creates this issue..

when I turned it off seems like photos show now but you have to re-upload photo to show

## Steps to reproduce:
1. Defer Profile Images was ON then go to groups create a group 
2. upload photo and finish settings up group
3. then go click on members and select the member who created the group 

## What is expected?
... should be able to see the tiny profile pics in the groups

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome browsers latest version
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1
...

## Screenshots
...

![profile pic not showing new group created in 4 6 1](https://user-images.githubusercontent.com/17736688/38760361-74876eb8-3f40-11e8-9a62-90bab06f6343.PNG)

**Comment by spirogg** [comment]
![no profile pic in groups](https://user-images.githubusercontent.com/17736688/38760708-ed6923b0-3f42-11e8-926f-d16475f3db7d.PNG)

**Comment by spirogg** [comment]
![screenshot_20180413-175108](https://user-images.githubusercontent.com/17736688/38760828-f2590e3e-3f43-11e8-8e03-5655c60e5afc.png)

**Comment by spirogg** [comment]
the last one that shows 2 members was old one created in ver 4.6.0

**Comment by neil96** [comment]
Could you give us more information.

**Comment by spirogg** [comment]
created a page, uploaded a photo and then finished the page. then I clicked on member profile which created that page and the left menus you see in photo doesn't have the thumb picture ??

**Comment by spirogg** [comment]
sorry but I have to ask you if your end is fresh install 4.6.1 or upgrade from 4.6.0 to 4.6.1 ? cause your demo site is still 4.6.0

**Comment by spirogg** [comment]
@neil96 Defer Profile Images was ON creates this issue..
Load profile images after the site has loaded.

when I turned it off seems like photos show now

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/38766235-c47be59e-3f94-11e8-8b1a-a89aca9d4946.PNG)


**but still issue if we have Defer profile Inmages ON**
_Load profile images after the site has loaded_

**Comment by neil96** [comment]
Thank @spirogg ,

I still can't reproduce with these steps. Are you using CDN?

Regards.

**Comment by spirogg** [comment]
no worries seems to be working on 4.6.1 must of been cache or something with update. I deleted and reinstalled fresh 4.6.1 and this is working correctly. 

thanks

Spiro
