### ISSUE TITLE
when view a group - under group info i see <div class="core-ckeditor-content"></div>

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2238]
## What happened?
i created a group but did not enter any INFO just uploaded a photo
then i clicked on group then i selected the group i created. then i see

**Group Info**
_Admin_
Founder
`<div class="core-ckeditor-content"></div>`
...

## Steps to reproduce:
1. create a group and just add photo and finish
2. selct your group you created
3. look on left side under GROUP INFO

## What is expected?
... blank area where `<div class="core-ckeditor-content"></div>` it should be just blank

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome latest version
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 cloudlinux php7 nginx proxy apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.0 upgraded to 4.6.1
...

## Screenshots
![under group info - div class core ckeditor content div](https://user-images.githubusercontent.com/17736688/38766168-d508db3e-3f93-11e8-9e27-0a5dbf02a0b1.PNG)

...

**Comment by spirogg** [comment]
Allow HTML
**Set this to Yes if you would like to allow HTML on your site.** 

_Note that even with this setting enabled by default we only allow certain HTML tags we feel that will not harm your site._

if we turn this off we  see  the code `<div class="core-ckeditor-content"></div>` if we turn this setting  ON then it is normal

**Comment by neil96** [comment]
It works as our designed. When you turn off setting **Allow Html** it will display html like this.
