### ISSUE TITLE
New usergroup menu system

### ISSUE THREAD

**Issue by Scheinwelt-Media** [PHPfox-Official/phpfox-v4-issues#2243]
## What happened?
In 4.6.1 menus can be hidden for usergroups. When you set a module to not allow browsing for guests menus are hidden but not for all (e.g. marketplace and members shows even when module is deactivated for guest).

## Steps to reproduce:
1. Set guests are not allowed to browse marketplace 
2. Logout

## What is expected?
Marketplace menu should not show up for guests. Better would be to show all menus even when browsing of the module is deactivated for guests and let admin decide wich menu to show for guests via new usergroup function.

## Browsers and Devices tested
All browsers

## Server information
Linux, Apache

## phpFox version
4.6.1

**Comment by Scheinwelt-Media** [comment]
Nevertheless there are some issues i like 4.6.1. Great modern interface and fast. Thanks!

**Comment by neil96** [comment]
It works in my test. Could you clear cache and try again.

Regards.

**Comment by kibcode** [comment]
to reproduce go to usergroup settings of an app and disable guests for browsing the app/module (e.g. photo or forum). when disabled the menu of that app does not show even when it is enabled for guests in the menu settings. maybe you want guests to only browse blogs but then there is only one item on the menu... that does look strange on a landingpage and guests do not see what they will get when signing up.

there is one exception... when guests are not allowed to browser members the menu DOES show up.
