### ISSUE TITLE
problem with cron and ajax mode Turn Off full Ajax mode = YES ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2246]
----------------------------------------

## What happened?
...                                     
**please see my support ticket** not sure if you want me to post here

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome - edge browser
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7 apache 

**your demo site too**
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1
...

## Screenshots
...

**Comment by neil96** [comment]
By default, browser does not allow two or more requests at the same time. Our cron job need 5 mins to be done. Default request timeout is 30s, so when you run cronjob via web, it will hang all requests to current domain. All other users will not be affected.

Regards.
