### ISSUE TITLE
recent threads not showing in forums only recent discussions even though title is recent threads ??

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2248]
## What happened?
... go to blocks for home (forums) you see 3 blocks 
1) recent Threads
2) recent Posts
3) Tending

## Steps to reproduce:
1.  go to admincp
2. blocks
3. select drop down for home (forums) 
4. Title says Recent Threads but all we see is  Recent Discussions and trends
even though there are recent threads  ? should be recent threads as it is in title
or whatever we rename title for recent threads.. 

## What is expected?
...should say recent threads as it is in title of block not recent discussions

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7 apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1
...

## Screenshots
...

![capture](https://user-images.githubusercontent.com/17736688/38966685-287fe9de-4349-11e8-8dd1-77f1374d7646.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/38966692-2b4b45b4-4349-11e8-9f30-5f73734cf2eb.PNG)

![recent discussions](https://user-images.githubusercontent.com/17736688/38966635-e9d3bde6-4348-11e8-9ba0-ff323285d24a.PNG)

**Comment by spirogg** [comment]
your demo site also https://v4.phpfox.com/forum/

says recent discussion 

![capture](https://user-images.githubusercontent.com/17736688/38966763-749c9128-4349-11e8-9dee-16794c825497.PNG)

**Comment by neil96** [comment]
**Recent Thread** or **Recent Discussions** have similar meaning. In pages/groups, forum is called **discussions**
You can update these phrases as your bussiness. 

Regards.

**Comment by spirogg** [comment]
@neil96 where can I change this?

 I tried to change the block title to Recent Thread but it always says recent discussion ?

 So where can I change this ?

 I thought the title of a block would change the wording ?

**Comment by neil96** [comment]
Did you update this phrase `recent_discussions`?

**Comment by spirogg** [comment]
Ok I have to change phrase.

But

Why not make it able to rename title and it will show what title is ?

If I make a new block and make name in title frog. The block will show
frog. So why not make all blocks (title) to we can change and rename title
from block area ?

Thanks.

Spiro :)

**Comment by spirogg** [comment]
Should I make this a feature request ??

**Comment by neil96** [comment]
The title can be changed base on data. So you can't change or rename it from block area.

**Comment by spirogg** [comment]
Ok thank you sir.
