### ISSUE TITLE
when setup email server to smtp authentication ON and save changes after clear cache it turns OFF ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2254]
----------------------------------------

## What happened?
...go to admicp >> settings >> Mail server 
setup for smtp and try to turn ON SMTP Authentication clicking on save changes seems to work but after clear cache or clear all cache the button for SMTP Authentication turns OFF

## Steps to reproduce:
1. go to admicp >> settings >> Mail server
2. setup for smtp and try to turn ON SMTP Authentication
click save changes
3. now go clear all cache  or just clear cache and go look at SMTP Authentication now= OFF 

## What is expected?
...
button to stay active = SMTP Authentication =ON
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome browser
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7 apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.61b2

...

## Screenshots
...
![smtpauthentication in mail server wont stay on after clear cache](https://user-images.githubusercontent.com/17736688/39243154-23518f68-4852-11e8-8dd1-01d2bd7139ff.PNG)

**Comment by kerstar** [comment]
The same is for the button above "Check ssl...".

**Comment by Elshara** [comment]
Yeah can confirm it here two. It's a pretty serious bug. It happens in other settings areas as well.

**Comment by davidnguyen88** [comment]
This issue belong to Safari browser, please upgrade to newest IOS version to check it again. It has fixed on newest version.

**Comment by spirogg** [comment]
4.6.1.b4 seems to work fine.

**Comment by spirogg** [comment]
@neil96 im closing this seems to be fixed in version 4.6.1.b4

**Comment by Elshara** [comment]
Just tested in Chrome, Waterfox, Firefox, same issue.

**Comment by Elshara** [comment]
Internet Explorer, Microsoft Edge, problem persists.

**Comment by neil96** [comment]
I can't reproduce on latest version. Do you test on latest version?

Regards.
