### ISSUE TITLE
Styling Issue on mobile login page.

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#2255]
Styling Issue on a mobile login page. the login form is not displaying properly as shown in the screenshot. 
...

## Steps to reproduce:
Just open your site's login page from a mobile page

## Browsers and Devices tested
Chrome, safari on iPhone 6.

## phpFox version
phpFox 4.6.0

![31239458_10156680622954369_7257638936531435520_n](https://user-images.githubusercontent.com/406030/39254590-b7bee3aa-48aa-11e8-9b0d-deeafe2da1bd.jpg)

**Comment by neil96** [comment]
Hi,

Could you test on phpFox latest version (4.6.1b2)

Regards.

**Comment by aakash83** [comment]
Hi, This screenshot is from latest version. I installed few days ago.

**Comment by aakash83** [comment]
The problem is only with Bootstrap theme. Any quick way to fix it ??

**Comment by neil96** [comment]
Could you give us more information?
