### ISSUE TITLE
Issues after clicking on "You have x updates" button...

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2256]
# Important!

Please follow this template!

----------------------------------------

## What happened?
... In demo update content is not visible after returning to home page

## Steps to reproduce:
1. Click on "You have x updates" button" when it appears (image 1)
2. Update content appears (image 2)
3. Go to any other page and return to home page (image 3)
4. Updated content is no longer visible, "You have x updates" button" will show in a moment

## What is expected?
... Updated content not visible after returning to home page.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

... phpFox Demo 4.6.1

## Screenshots
...
![info-button-1](https://user-images.githubusercontent.com/17064302/39302946-3d36dd2a-494c-11e8-989f-fcdb961eb83b.jpg)

![info-button-2](https://user-images.githubusercontent.com/17064302/39302951-44bd5b96-494c-11e8-9a65-8e73bf761502.jpg)

![info-button-3](https://user-images.githubusercontent.com/17064302/39302956-4da7cb38-494c-11e8-9ca5-95f8d11d2696.jpg)

**Comment by spirogg** [comment]
@starplan @neil96 
happens to me too fresh install 4.6.1.b2 
says you have 2 updates i click on the updates they show then click home button and there gone. after a few seconds it says you have 2 updates again its just a loop over and over again

![keeps saying 2 new updates](https://user-images.githubusercontent.com/17736688/39537411-24b24318-4dff-11e8-9f48-467cc8b077fc.PNG)
![2 new updates](https://user-images.githubusercontent.com/17736688/39537417-286ebcf2-4dff-11e8-9b08-1797dbca40c9.PNG)
![updates not showing](https://user-images.githubusercontent.com/17736688/39537462-420d664a-4dff-11e8-997f-58ae6e9c17fc.PNG)

**Comment by spirogg** [comment]
re installed 4.6.1.b2 no issues now. either cache problem or ssl issue if you had cpanel now working as normal for me

**Comment by neil96** [comment]
Can we know your site url?
