### ISSUE TITLE
edit: main site has description and title  - but in feeds shows just title 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2258]
----------------------------------------

## What happened?
... i just noticed when you go to the main website, v4.phpfox.com we have no Meta <Description>
when we add this site to feeds ? ( both templates ) Material and Bootstrap

we need to have meta Description also in feeds
```
<!DOCTYPE html>
--
  | <html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
  | <head>
  | <title>Social Networking Community</title>
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="social networking, phpFox demo" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

```
**Edit: Description is really far below but still issue I think**

(this is Members Page)

```
<!DOCTYPE html>
--
  | <html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
  | <head>
  | <title>Browse Users &#187; Social Networking Community</title>
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="social networking, phpFox demo" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
```
**Edit: Description is really far below but still issue I think**

## Steps to reproduce:
1. go to your demo v4.phpfox.com and add to the feed https://v4.phpfox.com
2. also for Members , photos, music, blogs etc. add the links to the feed. 
in the feed you see just title not description of those links

 does this mean the coding is not properly set like phpfox.com coding of meta title description keywords ?

## What is expected?
...
when adding a link to feeds in website it should show us title and description of the links
blogs should show blog title and description. music, videos, forums etc..

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
all
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7 apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b2

## Screenshots
...
here is more in-depth on my reporting below

if you look at the rest of the  - ( apps) blogs, photos, music, etc.. the source code shows meta description up top. even though main site and members page shows description at the middle of code, we still get no description in feeds ?

when you post the link in the feed section of v4.phpfox.com demo - it only give you title, [see here for example](https://v4.phpfox.com/profile-4166/?link-id=1168)

if you add https://phpfox.com in feed of v4.phpfox.com demo, [see here for example](https://v4.phpfox.com/profile-4166/?link-id=1170) 

you will see it gives you title and description of website in feed

if you look at source code here>  https://v4.phpfox.com/blog/   says it has title - meta description - keywords 

but when adding that link to feed ([ here is blogs link](https://v4.phpfox.com/profile-4166/?link-id=1175) )  **you see no description just title ??**

So why is it your main website shows title and description in feed but phpfox script links dont show title and description  ?

**I think this is bug** we should be able to see title and description in feed just like your main site https://phpfox.com

**Comment by spirogg** [comment]
this is phpfox.com source code

`<!DOCTYPE html><html lang="en-US" prefix="og: http://ogp.me/ns#"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"><link rel="shortcut icon" href="https://www.phpfox.com/themes/pf-website-theme/fav..." /><link type="text/css" media="all" href="//wwws.phpfox.com/wp-content/cache/autoptimize/css/autoptimize_64fe724cdbe843ad38543b99e1104408.css" rel="stylesheet" /><title>Features - phpFox Social Network</title><meta name="description" content="Our community builder software provides full social network features to start your own niche community. Learn more phpFox features to see how amazing it is."/><link rel="canonical" href="https://www.phpfox.com/features/" /><meta property="og:locale" content="en_US" /><meta property="og:type" content="article" /><meta property="og:title" content="Features - phpFox Social Network" /><meta property="og:description" content="Our community builder software provides full social network features to start your own niche community. Learn more phpFox features to see how amazing it is." />`

**Comment by neil96** [comment]
It's working as our designed. Please post this in feature request.
