### ISSUE TITLE
Home Feed and Profile Feed Loads youtube Video Images slow

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2262]
----------------------------------------

## What happened?
...Home Feed and Profile Feed Loads youtube Video Images slow - also on mobile devices ?

but Video app Loads youtube Images almost automatically and super fast  

## Steps to reproduce:
1. share youtube videos on feed or from profile or add to video and have them be part of feed.
2. when using mobile device and home computer and you view home feed or user profile feed - the youtube Video images take really long to load on mobile device longer - on Home Feed and Profile Feed
3. 

## What is expected?
...Should be fast the same on Home Feed and Profile Feed for Youtube videos as Video App ?

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome edge
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7 apache

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b2
..
## Screenshots...
Feed Post of  youtube videos on mobile below

![screenshot_20180501-015830](https://user-images.githubusercontent.com/17736688/39464906-cc0e2390-4ce5-11e8-8595-85cd81cdbd55.png)
![screenshot_20180501-015858](https://user-images.githubusercontent.com/17736688/39464907-cc1898c0-4ce5-11e8-8d7d-6cc5a91ff27c.png)

**Comment by spirogg** [comment]
but when you click on video app the youtube images show up right away
see photo below

![screenshot_20180501-015810](https://user-images.githubusercontent.com/17736688/39464905-cbfe876e-4ce5-11e8-80bd-b301a48e26cc.png)

**Comment by neil96** [comment]
Please double check the network on your side. We use direct images from youtube.

Regards.

**Comment by spirogg** [comment]
My network is 1gig downloads ?? 
Seems the video app caches the YouTube images. But feed doesn't cache. If you click video app. The images show up fast. Right away... 

 But when view more than 2 videos in a row  in feed it takes too long time to see image. . On mobile device.
