### ISSUE TITLE
Redis issue

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2264]
# Important!

Please follow this template!

----------------------------------------

## What happened?
All IM messages going lost when i clear cache in admincp

## Steps to reproduce:
1.  Enable redis for cache
2.  Clear cache
3.  check im messages on frontpage

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

Centos 6
Php 5.5
Apache

...

## phpFox version
(Example: phpFox 4.6.0)
phpFox 4.6.1b2

...

## Screenshots
...

**Comment by neil96** [comment]
Please do not use IM and Redis cache on the same server.
We saved IM message on Redis. If you use Redis cache and you clear cache, it will remove ALL DATA on redis.

Regards.
