### ISSUE TITLE
Secure Pages with HTTPS, keeps saying "Your server does not support https" but I have https and SSL on site ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2265]
----------------------------------------

## What happened?
...
fresh install of 4.6.1.b2 on new server centos 7 w/ cPanel WHM. auto ssl is on and site shows SSL cert. ok 
but I tried to set https in admincp for website and it will not stay ON??

  I try to turn this option ON and it doesn't work , I have SSL and https: show good ?
```
Secure Pages with HTTPS
Warning This is an important setting. Select a wrong option here can break the site or affect some features. If you are at all unsure about which option to configure, use the default value or contact us for support.
If your server has support for HTTPS you can enable this feature to secure certain pages like the login, registration and account setting pages.
```
## Steps to reproduce:
1. go to admincp >> settings >> SSL
2. try to click on Secure Pages with HTTPS
3. will not stay ON 

## What is expected?
... button to stay on YES

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome edge
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 OS php7 php7.1 php7.2 apache
...

## phpFox version
(Example: phpFox 4.6.0)
fresh install 4.6.1.b2
...

## Screenshots
...
![https not supported](https://user-images.githubusercontent.com/17736688/39659799-ac411d7e-4ff6-11e8-8d10-5b1b5b23fe50.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

Could you check your ssl status here: https://www.sslshopper.com/ssl-checker.html

If you see this:

> None of the common names in the certificate match the name that was entered (yourdomain.com). You may receive an error when accessing this site in a web browser

It means your ssl configuration is not valid on all browsers.

Regards.

**Comment by spirogg** [comment]
Shows All green check marks. on sslshopper. Good. Not one bad. ??

**Comment by spirogg** [comment]
I have put support request for this I don't know why it's not working.

**Comment by hexplor** [comment]
I have the same issue. Can you tell me how you fixed this @spirogg  ?

**Comment by hexplor** [comment]
Ok. Fixed. It should be stated in docs that you can't on this feature when you're using HTTP Authentication
