### ISSUE TITLE
update profile picture pops up but just spinning around ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2266]
----------------------------------------

## What happened?
... i tried to update profile and the popup shows but keeps spinning spinning ?

## Steps to reproduce:
1. go to home page click on pic to update profile photo and it keeps spinning never to allow to update or crop ?
2. 
3. 

## What is expected?
...
should show profile pic and be able to update or crop
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome edge
## Server information
(Example: CentOS 7, php 7.1 apache)

...CentOS 7, php 7.1 apache

## phpFox version
(Example: phpFox 4.6.0)
fresh install 4.6.1.b2
...

## Screenshots
...
![update profile picture keeps spining](https://user-images.githubusercontent.com/17736688/39659842-56a0e66e-4ff7-11e8-8f79-6edd33617ddc.PNG)

**Comment by neil96** [comment]
Are you using Cdn?

**Comment by spirogg** [comment]
@neil96 no cdn. Just centos 7 php7 apache.

**Comment by spirogg** [comment]
Input in support request. Can't figure this out.
