### ISSUE TITLE
custom about me -reg user - we need to set limits to this since you have made it html 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2267]
----------------------------------------

## What happened?
... user creates about me and its too long also with photos and links - looks bad messing up site

## Steps to reproduce:
1.reg user create a long about me article with links and photos in the custom about me section.
2. messes up page and there is no limit set see photo
3. 

## What is expected?
... we need to set limit in all blocks for custom about me not allow photos - images and limit to 255 characters or we can set this ourselves in admicp or the block itself

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome edge
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php 7 apache

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b2
...

## Screenshots
...
![too long we need to limit here](https://user-images.githubusercontent.com/17736688/39678248-8548fae4-514e-11e8-8af5-7ae201aeee55.PNG)

**Comment by neil96** [comment]
It's working as our designed. Please post in feature request repo.

Thanks!
