### ISSUE TITLE
when you go to block for visitor landing page (core.index-visitor) blocks dont show ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2268]
----------------------------------------

## What happened?
... i went to my blocks - admincp>>appearance>>blocks 
select visitor landing page (core.index-visitor)
i try to make welcome or featured user guest appear in any blocks but not working ? is this not possible in 

## Steps to reproduce:
1. admincp>>appearance>>blocks 
2. select visitor landing page (core.index-visitor)
3. try to add or make featured user appear - not working

## What is expected?
... should be able to get blocks working on visitor landing page per block definition ?
this should work even if we use Material Theme.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome edge
## Server information
(Example: CentOS 7, php 7.1 apache)
CentOS 7, php 7.0 7.1 7.2  apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b2 Theme is Material Theme
...

## Screenshots
...
![guest blocks not working](https://user-images.githubusercontent.com/17736688/40079409-77d8528c-584d-11e8-84f6-bbcebf83bc73.PNG)

**Comment by neil96** [comment]
We noticed this point in our document: https://docs.phpfox.com/display/FOX4MAN/Material+Template
