### ISSUE TITLE
upload image for album does not cover default image completely see photo

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2269]
----------------------------------------

## What happened?
... upload image to album and default image rounded shows in right side of uploaded image

## Steps to reproduce:
1. go to music - select album 
2. create new album and add photo
3. 

## What is expected?
... uploaded photo of album show not show default image on the right side also when feature album it does the same in block

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7 apache
...

## phpFox version
(Example: phpFox 4.6.0)

...   4.6.1.b2

## Screenshots
...
![album in music upload image not cover default image](https://user-images.githubusercontent.com/17736688/40138402-2cba0276-5912-11e8-8c66-dd07af7e8141.PNG)
![when upload phpto for album in music not cover all of image](https://user-images.githubusercontent.com/17736688/40138410-33d93b12-5912-11e8-8827-dd680dfde10c.PNG)
![upload album featured image bad also](https://user-images.githubusercontent.com/17736688/40138416-374d3fd2-5912-11e8-8b01-84a7d3edcb01.PNG)

**Comment by spirogg** [comment]
maybe this is by design ?? 

not sure but i just noticed it in the difference between Sponsored Albums and Featured Albums
they are different ??

thanks

Spiro

**Comment by nativedragon11** [comment]
It looks like that's supposed to be a vinyl record coming out of the side. This is intentional, but you can remove it by either deleting this from your CSS file completely:

.list-view.music .albums-bg-outer .albums-bg-inner::before {
    background-color: #555555;
    border-radius: 100%;
    right: -6px;
}

OR by adding display:none; to that same section if you don't want to remove it. Like so:

.list-view.music .albums-bg-outer .albums-bg-inner::before {
    background-color: #555555;
    border-radius: 100%;
    right: -6px;
    display: none;
}

**Comment by spirogg** [comment]
should be a CD image    not a record :)  records are obsolete  lol lol sorry I thought that was funny 🥇 

i will close this ticket and thank you @nativedragon11 for your help 💯
