### ISSUE TITLE
username spaces in registration - should not allow spaces 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2270]
#
----------------------------------------

## What happened?
... when setting username at signup spaces are allowed - . but if you are admin and edit user from admincp it will not allow to use spaces in username

Username is required and can only contain alphanumeric characters and _ or - and must be between 5 and 25 characters long.

## Steps to reproduce:
1. set username at signup
2. user signs up and uses space in between their username (example) 
php fox  <<<<<<<<<<<should not be allowed
instead should be only
 phpfox 
or 
php-fox 
or 
php_fox

but when you are edit user in admincp it will not allow you to use space it will warn you only username or dash - or underscore _ only... in username
3. 

## What is expected?
... should not allow space in username and have popup warning what is allowed like in admincp edit user 

also username edit by user should have error message not just make username with dash 

(example) i type john jones  in username area
 but it will just make it john-jones 
should not make it john-jones

 should warn no spaces and allow user to make decision
 if they want  john_jones or johnjones or john-jones 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php 7 apache

## phpFox version
(Example: phpFox 4.6.0)

... 4.6.1.b2

## Screenshots
...
https://mydomain.com/Zoe%20G/  this is after signup allow user to signup with username or both

 
![edit username in admincp_li](https://user-images.githubusercontent.com/17736688/40149505-a4402da8-5939-11e8-87a5-b27ea6cdbffd.jpg)
![username space allowed](https://user-images.githubusercontent.com/17736688/40149529-c5579b02-5939-11e8-8acd-3a7de520315c.PNG)

![no warning just adds a dash in between username](https://user-images.githubusercontent.com/17736688/40149432-2b4662e6-5939-11e8-9a84-07a1ae621ce8.PNG)

**Comment by spirogg** [comment]
should give error on signup when admin selects username on signup or both Full Name and Username >> 

Username is required and can only contain alphanumeric characters and _ or - and must be between 5 and 25 characters long.

should give error in User >> Account Settings >> 

Username is required and can only contain alphanumeric characters and _ or - and must be between 5 and 25 characters long.

**Comment by Elshara** [comment]
I think that spaces should be allowed in usernames. It really bugs me we have to have two name fields.

**Comment by spirogg** [comment]
Fixed in 4.7.0
