### ISSUE TITLE
when change name it doesnt update right away - stays in cache until admin clears cache?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2274]
----------------------------------------

## What happened?
... i changed a name from michelle to mich after update name I see some areas change but not all areas, the only way to see change is admicp clear cache ? should this not show change everywhere ?

## Steps to reproduce:
1. change name for user 
2. check the website the user that you change the name doesn't update
3. 

## What is expected?
...  should update right away

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php 7 apache

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b2

## Screenshots
...
![changed name to mich from michelle but does not update](https://user-images.githubusercontent.com/17736688/40168473-2be250de-5989-11e8-99ab-378b7e6f2818.PNG)
![not update right away name change_li](https://user-images.githubusercontent.com/17736688/40168663-a1c77cde-5989-11e8-82bc-8a1822c7e9e1.jpg)
![not update right away name_li](https://user-images.githubusercontent.com/17736688/40168696-bfc660d8-5989-11e8-87ce-bf46d53715ef.jpg)

**Comment by spirogg** [comment]
this should not be cache that we need to clear cache in admincp when a user change name

It should change right away. for no confusion

**Comment by spirogg** [comment]
![changed name phpfox demo site](https://user-images.githubusercontent.com/17736688/40169352-6fc44274-598b-11e8-986f-a2273db40ee9.PNG)
![changed name phpfox demo site1](https://user-images.githubusercontent.com/17736688/40169360-74990ece-598b-11e8-944e-89bdbf9f35cc.PNG)

**Comment by neil96** [comment]
I can't reproduce this issue on my side. Could you give us more information?

Thanks!

**Comment by spirogg** [comment]
the last 2 photos were from your site demo v4.phpfox.com 

I change my name from greekvideos to spirog when I went to members page i still see greekvideos but elsewhere i see spirog. so is it because cache and you have time limit for cache to clear 

or we have to clear cache for it to take affect ?

**Comment by spirogg** [comment]
here it is again I change my name to spirogg from spirog see photos only in members page is stuck and if I was featured member it would stay stuck also to old name..


![changed name on your site again](https://user-images.githubusercontent.com/17736688/40402139-a180a2ac-5e0f-11e8-8c16-061fb78e98d0.PNG)

![members page shows old name](https://user-images.githubusercontent.com/17736688/40402130-96690e36-5e0f-11e8-87aa-97e7bce3e83b.PNG)

**Comment by spirogg** [comment]
still I have this, when change my name only in members area - featured block doesn't change name right away we need to clear cache for it to work

**Comment by spirogg** [comment]
if I un-feature then feature again - it switches names
or if we clear cache it switches to correct name

- but if I don't clear cache or un-feature and feature again - it stays like that?

-


![featured members block](https://user-images.githubusercontent.com/17736688/40635431-984bf4c0-62bf-11e8-8887-6b00068eedc4.PNG)
![featured members edge browser](https://user-images.githubusercontent.com/17736688/40635432-98582e5c-62bf-11e8-8311-84ed7a60c0f8.PNG)
