### ISSUE TITLE
pages profile photo if clicked some open in popup some open in photo app ??

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2276]
----------------------------------------

## What happened?
... your demo site I tested go to pages select a page that has an image in profile round pic. once you click on it it opens in popup and sometimes another pages profile opens in photo app? 

## Steps to reproduce:
1. https://v4.phpfox.com/mybandlatinos/     opens in photo app when you click on the Profile picture
2. https://v4.phpfox.com/pages/831/          opens in popup window when you click on profile pic not photo app
3. https://v4.phpfox.com/uttarakhand-tour-packages-from-delhi/   opens in popup 

## What is expected?
...
 not sure if they all should popup or open in photos when click on round profile image
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
your demo
...

## phpFox version
(Example: phpFox 4.6.0)
your demo
...

## Screenshots
...
![pages profile popup photos](https://user-images.githubusercontent.com/17736688/40220239-1a7f68c6-5a3e-11e8-91d9-568a3cd8a83c.PNG)
![how come some photos popup and other do not](https://user-images.githubusercontent.com/17736688/40220248-21c009d8-5a3e-11e8-8756-89c0afe5ac6a.PNG)
![no popup photo view in photos app](https://user-images.githubusercontent.com/17736688/40220252-28ebe34e-5a3e-11e8-9ada-58e893aa02f7.PNG)

**Comment by neil96** [comment]
Thanks @spirogg , it should redirect to photo detail pages.

**Comment by neil96** [comment]
Hi @spirogg ,

This issue comes from old data. Old profile photos do not belong to photo, so it shows popup. New profile photos will redirect to photo. On your site, just re-update profile photo.

Regards.
