### ISSUE TITLE
feed settings sort by top stories not working always stuck on most recent in home page feeds

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2278]
----------------------------------------

## What happened?
... Feed section where you set up settings
use select sort by top stories or most recent and save clear cache then go to home page for feeds and it doesnt save the sort option

this is not working right this is what causes updates to show in popup and then after you refresh page it goes away and pops up again saying you have updates

also in feed section (home) if you select sort by then you can fix it, but I dont think feed settings sets top stories or most recent which ever you select in feed options of app it always defaults to most recent

## Steps to reproduce:
1. go to feed app
2. select option to sort by both and also by top stories click save
3. clear cache and all cache then go to home page of feeds wait for the time limit you set to refresh feeds and you will see it has updates.. click on popup of updates you get to view updates, then refresh page and the updates go away and after the limit to refresh feed the update popup shows again with same updates.  also in home page if you select the sort by it will always default to most recent not top stories as we have set in feed option section

## What is expected?
... when in feed option settings and you save sort by top stories the main feed page should change to sort by top stories
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7 apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b2
...

## Screenshots
...
![you have 3 updates sort stuck on most recent](https://user-images.githubusercontent.com/17736688/40259370-674be562-5abb-11e8-87ee-b5ee4fef2b41.PNG)
![you have 3 updates show](https://user-images.githubusercontent.com/17736688/40259379-70ae25de-5abb-11e8-8648-f425ff631f3c.PNG)
![you have 3 updates again after refresh](https://user-images.githubusercontent.com/17736688/40259385-79f0ccaa-5abb-11e8-8519-43b4e2120048.PNG)
![feed settings top stories](https://user-images.githubusercontent.com/17736688/40259391-82a4796e-5abb-11e8-9917-b856ef0cb901.PNG)
![you have 3 updates sort stuck on most recent](https://user-images.githubusercontent.com/17736688/40259410-953d0ce4-5abb-11e8-90e0-347f9fb1d943.PNG)

**Comment by spirogg** [comment]
@neil96 if you manually set sort in home page feed section then you dont get all the popups that you have updates and they stay after refresh page

![main feed page select sort by top stories qnd you never get popup again](https://user-images.githubusercontent.com/17736688/40259443-bd8e1b2a-5abb-11e8-9ca4-177c99b4db7e.PNG)

**Comment by spirogg** [comment]
#2256

**Comment by spirogg** [comment]
here is complete feed settings i have setup so you can test 4.6.1.b2

![feed settings](https://user-images.githubusercontent.com/17736688/40261143-9830e2c8-5ac4-11e8-91b8-a6d21249c317.PNG)
![feed settings 1](https://user-images.githubusercontent.com/17736688/40261150-a83449c6-5ac4-11e8-9cfa-3b56e4612161.PNG)
![feed settings 3](https://user-images.githubusercontent.com/17736688/40261154-ae0314b8-5ac4-11e8-8695-79b0133b05a7.PNG)

**Comment by neil96** [comment]
I can't reproduce this issue on my side.

**Comment by spirogg** [comment]
@neil96 if i select option to sort by both and also by top stories and click save
i dont get top stories I have to manually change sort options in feed (home Page)
or if I have manually set sort in homepage to top stories it wont change in admincp ?
 
1) go to your homepage first and see what you have for sort. 
if its top stories leave it alone 
2) then go to admincp and change settings to opposite of top stories then click save clear cache and all cache 
3) then go to (homepage) feed again and see it does not change sort option  will be the same as you had when you first checked it unless you manually change to sort option form homepage feed only

**Comment by spirogg** [comment]
ok again i did the same thing I change manually to SORT= Most Recent in homepage feed

then went down the feed and made a comment  The first photo shows now there is 1 update

![sort by most recent manually](https://user-images.githubusercontent.com/17736688/40402357-b565f7da-5e10-11e8-9874-ac5695f00e07.PNG)
=
=
=
=

now I clicked on 1 update and it shows me the update 2nd photo below
![clicked updates and page shows updates](https://user-images.githubusercontent.com/17736688/40402397-000d8528-5e11-11e8-987e-615017e56e6e.PNG)

=
=
=
=

now I go back to homepage feed and wait i see 1 update again and its the same update as before 3rd photo below
![same update again](https://user-images.githubusercontent.com/17736688/40402422-2521a92a-5e11-11e8-83c7-d1f316b853c3.PNG)

=
=
=
If I leave sort Manually in homepage feed to top stories then everything works right ?? so Basically the new updates dont stay updated in feed they disappear until you set SORT=Top Stories in feed manually as a registered user admin or whatever user you have set

**Comment by spirogg** [comment]
![this is on your demo now same 2 updates i keep seeing this 2 updates](https://user-images.githubusercontent.com/17736688/40403276-65f2a756-5e16-11e8-9900-fb51be4bdae7.PNG)
i keep seeing this 2 updates even after click on 2 updates and refresh page or go to home button and view feed again after a little bit same thing same updates just fyi
