### ISSUE TITLE
12 hour format in event app when selecting times for events we make?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2279]
----------------------------------------

## What happened?
... when in event app settings we set 12 hr format but still in event area when setting up an event ( the time is 24hr) we need to have 12 hr format also set from event app settings.. when we change to 12 hr format it should allow user to have 2:30am to 5:45pm instead of 02:30 to 13:45 this is very confision to users who do not know military time (24hr Format) please fix this

## Steps to reproduce:
1. go to apps installed select events go to settings
2. scroll to 12 hr format and save. 
3. 

## What is expected?
... when changing from 24hr format to 12 hr format the time setting option when creating an event should change to 12 hr format also

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php7 apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b2
...

## Screenshots
...
![time set to 12hr format](https://user-images.githubusercontent.com/17736688/40265050-3d5d6de4-5af6-11e8-9d2d-8ab7970d9e4d.PNG)
![24hr format](https://user-images.githubusercontent.com/17736688/40265051-40cfb86a-5af6-11e8-9bfe-d46bebcbf099.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

In the setting description, we wrote: **"when viewing an event"**. These settings do not effect when create/edit an event.

Regards.
