### ISSUE TITLE
Edit photo and then save thumbnail does nothing in pages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2280]
Steps to reproduce
1.  manage > photo > edit thumbnail
2. Save (does nothing).

**Comment by spirogg** [comment]
Did you update to new version of pages 4.6.1 ?? There us an update. Just FYI.

**Comment by prepperz** [comment]
yup

**Comment by neil96** [comment]
Hi @prepperz ,

The new image is cached by browser (because the url does not change), it will be changed in a little bit. We will improve this case in next versions of Pages app.

Regards.

**Comment by prepperz** [comment]
What I mean is that it is not saved. As in there is no confirmation of whether it is being saved or not.

**Comment by neil96** [comment]
>What I mean is that it is not saved. As in there is no confirmation of whether it is being saved or not.

I can't reproduce this case, could you give us more information.

Thanks!

**Comment by prepperz** [comment]
OK. saves, but it really slow that it seems like it not saving. On the demo too.

**Comment by prepperz** [comment]
Also can you test it on the bootstrap template as well?
