### ISSUE TITLE
adding a flag to language doesn't work 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2281]
----------------------------------------

## What happened?
... I uploaded a flag to the language English but it doesn't show.. I cleared cache and All Cache still nothing ?

## Steps to reproduce:
1. go to admincp>> globalization >> Languages
2. edit settings >> upload flag 128x128 png
3. save clear all cache and clear cache 

## What is expected?
... when selecting language Flag should show like your demo site

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome edge
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7 apache

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b2

## Screenshots
...**my admincp are where I added Flag** 

![flag to english language](https://user-images.githubusercontent.com/17736688/40322382-d2e9bfc2-5cf7-11e8-8cd3-9287b24fbedd.PNG)
**Your Demo Site had a Flag ??**
![your demo site has flag](https://user-images.githubusercontent.com/17736688/40322465-165f366a-5cf8-11e8-83c1-d3d3afc09ca3.PNG)

**my site has no Flag ??**
![no flag my site](https://user-images.githubusercontent.com/17736688/40322501-379d2e9a-5cf8-11e8-867f-3cab77d831ff.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,
I can't reproduce this issue on my side. Could you give us more information.
Thanks!

**Comment by spirogg** [comment]
hi, I saw on your site you had a flag next to english, so i went to language and edit english saw option to upload photo for flag. I use a 128x128 png image of american flag. I uploaded and cleared cache and all cache then went to main page and clicked on english language popup but no flag. ? not sure why

**Comment by spirogg** [comment]
please try to change flag icon on the demo site v4.phpfox.com to something different you will see doesnt work.
I also notice now when I try to change Icon it will act is if it uploaded but still same image but doesn't show when we click language

**Comment by spirogg** [comment]
this for sure doesn't work - i cant remove the flag I added it is stuck,
 even when I try to add another flag to upload and click save the same flag shows in admincp but not the main site when you click on language ? this is something wrong for sure
![flag to english language](https://user-images.githubusercontent.com/17736688/40322382-d2e9bfc2-5cf7-11e8-8cd3-9287b24fbedd.PNG)

**Comment by neil96** [comment]
Could you double check directory permission here `PF.Base/file/pic/flag/`, it need to be writable.

Regards.

**Comment by spirogg** [comment]
Hi - I changed to 0777 all folders PF.Base/file/pic/flag/
Still not working. 

 I see en.png In flag/ folder but still doesn't show when I click in language in popup? 
funny thing is it shows in admincp but not in language popup, also it shows after i did search flags in admincp and turn on flag option to show next to language link. but still not show in popup ?

 really weird

**Comment by spirogg** [comment]
still not working
4.6.1b3 fresh install

**Comment by neil96** [comment]
HI @spirogg 
Please submit a ticket, we will fix it if this is a issue of core.

Regards.

**Comment by spirogg** [comment]
Ok I make support request already. Thanks.

**Comment by spirogg** [comment]
Sorry about last night. I fell asleep while emailing you :( I was Soo tired 23 hrs awake. But I put in request with correct ftp info. Sorry again and thanks.

**Comment by spirogg** [comment]
Thank you.
