### ISSUE TITLE
finding errors in console view chrome: Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2282]
# 

----------------------------------------

## What happened?

util.js:228 Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required

Gw.j | @ | util.js:228
-- | -- | --
  | (anonymous) | @ | js?libraries=places&…$Core.Feed.init:159
  | (anonymous) | @ | js?libraries=places&…=$Core.Feed.init:65
  | (anonymous) | @ | js?libraries=places&…=$Core.Feed.init:63
  | (anonymous) | @ | js?libraries=places&…=$Core.Feed.init:65
  | (anonymous) | @ | js?libraries=places&…$Core.Feed.init:137
  | (anonymous) | @ | js?libraries=places&…=$Core.Feed.init:63
  | (anonymous) | @ | js?libraries=places&…$Core.Feed.init:137
  | (anonymous) | @ | js?libraries=places&…=$Core.Feed.init:63
  | (anonymous) | @ | js?libraries=places&…$Core.Feed.init:137
  | Qd | @ | js?libraries=places&…=$Core.Feed.init:65
  | Od.wa | @ | js?libraries=places&…$Core.Feed.init:137
  | (anonymous) | @ | util.js:1

Also we get

 **because of its detrimental effects to the end user's experience**

**[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.**

send @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:585
ajax @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:565
jQuery._evalUrl @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:576
domManip @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:371
domManip @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:2576
domManip @ im-libraries.min.js?v=ba1e27c707bf15e9fdb654f87a03d31b:1
append @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:357
(anonymous) @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:366
jQuery.access @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:240
html @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:363
$Core.show_page @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:1714
complete @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:1704
fire @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:182
fireWith @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:187
done @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:574
callback @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:592
XMLHttpRequest.send (async)
send @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:589
ajax @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:565
reloadPage @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:1703
(anonymous) @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:1752
dispatch @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:278
elemData.handle @ autoload-461.js?v=ba1e27c707bf15e9fdb654f87a03d31b:251

## Steps to reproduce:
1. login to your site and go to home page feed and inspect using chrome 
2. see photos im worried that some of this is causing slow loading times for end users ?? 
3. 

## What is expected?
... fix warnings that may slow down site - because of its detrimental effects to the end user's experience

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php7 apache
...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b2

## Screenshots
...
![console violations](https://user-images.githubusercontent.com/17736688/40334558-1fcb658a-5d24-11e8-80d7-76af8abb1e23.PNG)
![console violations1](https://user-images.githubusercontent.com/17736688/40334560-244a72cc-5d24-11e8-8b93-e9084d9f5943.PNG)
![errors in console](https://user-images.githubusercontent.com/17736688/40334564-2d2f219e-5d24-11e8-84bb-361f76811469.PNG)

**Comment by spirogg** [comment]
your demo site.. login and right click from chrome browser select inspect you will see same
![phpfox demo](https://user-images.githubusercontent.com/17736688/40394664-fb59fb00-5de9-11e8-9aae-3584503d647b.PNG)

**Comment by spirogg** [comment]
then if you refresh or go to home again it will give you this below
just wondering about this one 

Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.


![phpfox demo](https://user-images.githubusercontent.com/17736688/40394778-7bdd4f7a-5dea-11e8-956b-a4b84ba0768a.PNG)

![phpfox demo2](https://user-images.githubusercontent.com/17736688/40394783-813c5e2a-5dea-11e8-9232-290b6baf442c.PNG)

**Comment by neil96** [comment]
I tried on facebook and google, they have the same warnings. And these warnings are hidden by default on browser.

Regards.
