### ISSUE TITLE
timestamp in phpfox is always show GMT I have set server and phpfox to America/Chicago not showing correctly ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2283]
----------------------------------------

## What happened?
...

Current Time
-- my server is set to:
Mon May 21 19:00:18 CDT 2018
America Chicago

my timestamp is set to America/Chicago in pgpfox admincp Timpstamp.

but the maintenance>> system Overview>>  timestamp shows 

Server Time Stamp: | May 21, 2018, 11:59 pm (GMT)
-- | --

how to get this sorted out CDT not GMT ?? 

## Steps to reproduce:
1. set my server time to America/Chicago CDT 
2. set phpfox to America/Chicago
3. go to maintenance>> system Overview   show different timestamp even though we have set all timestamps to America/Chicago ? 

## What is expected?
... should show America/Chicago CDT

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome edge
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7 apache
...

## phpFox version
(Example: phpFox 4.6.0)

...
4.6.1.b2
## Screenshots
...

![servertime stamp](https://user-images.githubusercontent.com/17736688/40335628-4e21d83c-5d2a-11e8-8276-e6bd75f6d8a6.PNG)
![timestamp settings phpfox](https://user-images.githubusercontent.com/17736688/40335639-5c13eae8-5d2a-11e8-9315-f2795c69d5b1.PNG)
![phpfox time stamp](https://user-images.githubusercontent.com/17736688/40335646-6353335e-5d2a-11e8-8df2-e5f5b67b81e0.PNG)

**Comment by neil96** [comment]
In **maintenance>> system Overview>> timestamp shows **, it displays the time of your system. It likes phpinfo. phpFox does not use this value.

**Comment by spirogg** [comment]
how do I change GMT to UTC  on my sever ??
