### ISSUE TITLE
Hard coded phrases

### ISSUE THREAD

**Issue by cespiritual** [PHPfox-Official/phpfox-v4-issues#2286]
## What happened?
Hard coded phrases on the new "download your information" page. See attach image

## phpFox version
4.6.1b3

## Screenshots

![screenshot-2018-5-26 configuracoes da conta 1](https://user-images.githubusercontent.com/1458586/40575355-4d6e2026-60db-11e8-8cf7-6cd9bbda4933.png)

**Comment by neil96** [comment]
Yes @cespiritual , All texts in this session are not phrases.

Regards.
