### ISSUE TITLE
Cannot Disable Photos App

### ISSUE THREAD

**Issue by Elshara** [PHPfox-Official/phpfox-v4-issues#2287]
# Important!

Please follow this template!

----------------------------------------

## What happened?
...
There is no button to disable the photos app.
## Steps to reproduce:
1. Go to the Admin CP
2. Go to apps > Installed Apps
3. Notice, the button does not exist to turn off photos.

## What is expected?
...
The photos app to have a disabled button like all the other ones listed.
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Microsoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
Chrome, firefox, latest version, win 10
## Server information
(Example: CentOS 7, php 7.1 apache)

...
php7.2 centos7 apache 2
## phpFox version
(Example: phpFox 4.6.0)
php v4.6.1B3
...

## Screenshots
...
![phpfox_photos](https://user-images.githubusercontent.com/12810222/40580023-a6b09b1e-60ea-11e8-94f8-66ad37a9d88c.png)

**Comment by spirogg** [comment]
see here in apps installed click the link that says photos now you go to registred users and follow photos
![click photos](https://user-images.githubusercontent.com/17736688/40582276-5f3bd4aa-6136-11e8-8231-37da9296aadd.PNG)
![photos usergroup](https://user-images.githubusercontent.com/17736688/40582277-66f8f38a-6136-11e8-8af3-0e4675972be1.PNG)

![photo off](https://user-images.githubusercontent.com/17736688/40582265-0cd2e2c6-6136-11e8-886c-7835c90b1e60.PNG)

**Comment by spirogg** [comment]
hope this helps you

**Comment by neil96** [comment]
This is default, it can not be disabled.

Regards.

**Comment by Elshara** [comment]
Okay sorry I didn't know that was default behavior.

**Comment by neil96** [comment]
No problem friend!
