### ISSUE TITLE
Expand Cron To Detect Last Run

### ISSUE THREAD

**Issue by Elshara** [PHPfox-Official/phpfox-v4-issues#2288]
# Important!

Please follow this template!

----------------------------------------

## What happened?
...
The cron area of settings currently only detects the file path. It does not show when the last cron was run. It also doesn't give you the complete cron command, which it should based on detected Linux environmental variables.
## Steps to reproduce:
1. Go to Admin CP
2. Go to Settings > Cron
3. This is where the magic happens.

## What is expected?
...
Cron provide last run time. Also full in page documentation to be provided instead of a link to the help article for on site access.
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
N/A server issue - Chrome Firefox tested windows 10
## Server information
(Example: CentOS 7, php 7.1 apache)
Centos 7 Linux php7.2 Apache2
...

## phpFox version
(Example: phpFox 4.6.0)
v4.6.2B3
...

## Screenshots
...
![phpfox_cron](https://user-images.githubusercontent.com/12810222/40580082-49b72408-60ec-11e8-9d83-9d87aad349b2.png)

**Comment by neil96** [comment]
It's working as our designed. To request this feature, please post a request [here](https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/new).

Regards.
