### ISSUE TITLE
Cannot Complete Installation Of Apps

### ISSUE THREAD

**Issue by Elshara** [PHPfox-Official/phpfox-v4-issues#2289]
# Important!

Please follow this template!

----------------------------------------

## What happened?
...
Apps just fail to install.
## Steps to reproduce:
1. Login to Admin CP
2. Go to Apps > Find More Apps
3. Pick one and install it. Free, paid, doesn't matter. Click on get it to begin its installation.

## What is expected?
...
It goes through a few redirections and then stops. "missing [type]" What is expected is that at the install method step, it continues to completion so that the app can be fully integrated in to phpfox.
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
Windows 10 Firefox, Chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
Centos Linux php 7.2 Apache
...

## phpFox version
(Example: phpFox 4.6.0)
v4.6.1B3
...

## Screenshots
...
![phpfox_apps](https://user-images.githubusercontent.com/12810222/40580182-87d51c52-60ee-11e8-9c11-8c54032691e5.png)

**Comment by spirogg** [comment]
do you have file, ftp/sftp selected in admincp ?
![ftp in search](https://user-images.githubusercontent.com/17736688/40582256-bbabd4ac-6135-11e8-8437-f76c4a1c5562.PNG)
![ftp select](https://user-images.githubusercontent.com/17736688/40582257-bbb634d8-6135-11e8-8983-a2f8d5e829f3.PNG)
after select you need to look at all settings if you use ftp/sftp or ssh and click save or you can try just use file and click save

**Comment by Elshara** [comment]
Oh, I'm sorry. I didn't know it was meant to happen. I apologize.

**Comment by spirogg** [comment]
Did you try and did it work ?? :)

**Comment by Elshara** [comment]
I tried to enter in FTP information when I purchased the app from the
store. But all it did is ask me for the information. When it got it,
it did something because I could see the app files in the
/pf.base/apps folder. But after they were found there, it just said
missing [type]
the same thing occurred when I tried directly from the admincp but
that's as far as the install got.
So where do you enter in FTP information? I never was asked to when I
was logged in from admincp. It wouldn't let me enter it, that error
poppped up before I could do anything.
It let me enter it when I logged in to the full url of the admincp
when I tried from the store.phpfox.com site itself. But then it
failed. So because I'm new to phpfox, I'm going to delete the install
and redo it.
I know the files coppied over. But that's all that happened.

**Comment by spirogg** [comment]
Read this. Says alot of people get error when use ftp. So use file instead. 

But please read docs. Will help you. :)

https://docs.phpfox.com/plugins/servlet/mobile#content/view/1343496

**Comment by Elshara** [comment]
Some servers don't allow the connection back. Maybe that's my problem.

**Comment by spirogg** [comment]
I know the files coppied over. But that's all that happened.

Before you try to install again make sure you search like in my photo I sent you in admincp. And fund the ftp area 
There is a selector to select from file ftp/sftp ssh.  But don't add ftp details. Just use selector and use file. After try to use admincp and try to install app from there. 
**Also in your browser if you use chrome make sure it allow third party cookies or you have issue to view apps in store.phofox.com.**

**Comment by spirogg** [comment]
also after reinstall phpfox you can see what apps you purchased in admincp>> apps>> purchase History
from there you see and can try to click links to take you to store to upload again.

make sure your chmod is 0777 PF.Base and PF.Site so it can upload and write

**Comment by spirogg** [comment]
Did you ever get it working ?? Hope so. ;)

**Comment by Elshara** [comment]
Okay so it appears there's no easy way to get to apps > Core >
Settings. As in the "Core" app itself won't appear in the apps list. I
reinstalled it, used file system, on a completely different server,
and it works fine. Thanks for all the help! Why FTP is giving me grief
I have no idea. Thank you so much!
You don't know something is a bug or not until you are aware of it as
a problem. It's good to know where to improve.

**Comment by Elshara** [comment]
BTW I had to go to the settings of the app CKEditor for it to show me
an error message saying I had to enable html in core settings for it
to work. Only then could I access the apps > core > settings page.
Got any other short cuts for that area? I think it's a crutcial part
of PHPFox settings administration area.

**Comment by spirogg** [comment]
What I did was read the docs and in admincp I use search on top and type the letter ab ea ft (has to be 2 letters)  to see in drop-down what settings there are. It's hard way to do but you can learn each part by doing this. 
After a while you oearn the settings. :) 
- also go to admincp - members - user group settings. Select apps drop-down and groups drop-down. Then go through all settings. If you don't understand one. Search google and docs of phpfox. There you can find alot. Also please close this bug report and if you have questions ask in community of phpfox. You will get an answer. :) 

Thanks have an Excellent Day.

**Comment by Elshara** [comment]
Oh boy. Just seems quite a huge thing not to put in documentation of
the page. I Wish we could add menu items to admincp.
