### ISSUE TITLE
When create an ad it says creating an ad should say create an ad 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2293]
----------------------------------------

## What happened?
... When creating an ad I think the words should say 
- Create an AD 
instead of 
Creating an AD. 

Just a typo possibly. 

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...
4.6.1.b3
## Screenshots
...

**Comment by neil96** [comment]
We changed in latest version of ad.
