### ISSUE TITLE
Email White List Not working

### ISSUE THREAD

**Issue by aakash83** [PHPfox-Official/phpfox-v4-issues#2296]
# Important!

Please follow this template!

----------------------------------------

## What happened?
Can't disallow emails 

## Steps to reproduce:
1. Add a specific type of email in EMAIL White List  .  For example    *@mydomain.com
2. Users still can use name@example.com.
3. 

## What is expected?
I want my members to only use a specific type of email address for registrations   Like   name@mydomain.com     . Not  yahoo, gmail ,hotmail etc

## Browsers and Devices tested
Chrome, Opera

## Server information
Linux

...

## phpFox version
Latest PHPFox

...

## Screenshots
...

**Comment by david-phpFox** [comment]
Please use AdminCP > Ban Filters > Emails to config only use a specific type of email address for registrations

**Comment by aakash83** [comment]
Hi @davidnguyen88  ,
Your proposed solution is not working.  There is no option to allow a certain type of email address and disallow any others.   However We can  disallow a certain type of email address by using this method.  As the spammers and other non relevant  users can  use countless type of email addresses like ( @abc.com, @xyz.com and  so on. So it is not possible to restrict them.  
We can do it only through  Email white list / Black List. And  it is not working. So please add the  bug labale again. 

thanks
