### ISSUE TITLE
shows in GTmetrix.com: 2 recaptcha codes - lines, for defer parsing of javacript ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2301]
when run a check on GtMetrix.com 
under defer parsing of javascript 

RECOMMENDATION | GRADE | TYPE | PRIORITY
-- | -- | -- | --
Defer parsing of JavaScript | score: F (4) | JS | HIGH
What's this mean?
1.3MiB of JavaScript is parsed during initial page load. Defer parsing JavaScript to reduce blocking of page rendering.

https://mydomain.tld/PF.Base/file/static/autoload-461.js?v=4a62270b20435c14567b82dd7adc9e6d (894.7KiB)

## why it shows in GTmetrix: 2 recaptcha below ( the same recaptcha ? is there 2 lines for recaptcha by accident in code ?

- https://www.gstatic.com/recaptcha/api2/v1528855115741/recaptcha__en.js (182.4KiB)

- https://www.gstatic.com/recaptcha/api2/v1528855115741/recaptcha__en.js (182.4KiB)

https://mydomain.tld/PF.Site/Apps/core-im/assets/im-libraries.min.js?v=4a62270b20435c14567b82dd7adc9e6d (60.3KiB)

https://mydomain.tld/ (3.6KiB of inline JavaScript)

----------------------------------------

## What happened?
...

## Steps to reproduce:
1. go to admincp turn on google - recaptcha then goto gtmetrix.com and run test on your v4.phpfox.com demo 
2. on the very first line : Defer parsing of JavaScript
3. you will see 2 lines of the same code - link for google recaptcha 

- https://www.gstatic.com/recaptcha/api2/v1528855115741/recaptcha__en.js (182.4KiB)

- https://www.gstatic.com/recaptcha/api2/v1528855115741/recaptcha__en.js (182.4KiB)

- should be only 1 correct ?

## What is expected?
... should only show 1 line for recaptcha in code ?

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome browser latest version
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php7.1 apache
...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1b4

## Screenshots
...

**Comment by neil96** [comment]
>https://www.gstatic.com/recaptcha/api2/v1528855115741/recaptcha__en.js 

Default phpFox does not add this javascript, could you double check your 3rd-party apps.

Thanks!

**Comment by spirogg** [comment]
this is when I add php recaptcha from google your app from phpfox

**Comment by spirogg** [comment]
i have fresh install no other apps except phpfox apps

**Comment by spirogg** [comment]
![recaptcha](https://user-images.githubusercontent.com/17736688/41896403-238f65cc-78ea-11e8-80a3-fcce24346fe9.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

As I checked, this issue is from reCaptcha. Other sites have the same issue. But this does not affect the site.

Regards.
