### ISSUE TITLE
IM not working followed directions, what version nodejs and redis-server is needed for your app

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2304]
hi can we install latest nodejs and redis-server to work with IM I tried but no working added http://mydomain.tld:3000 and password not working

redis-server is 127.0.0.1 
6379

maybe my version of nodejs is to new v6.**
----------------------------------------

## What happened?
...

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by neil96** [comment]
Hi ,

The latest version of nodeJs is 10.5.0. However, our IM server can work with nodeJs v6. Could you give us the detail error here.

Regards.

**Comment by spirogg** [comment]
error in chrome console
im-libraries.min.js?v=e530a8d0ad4e2e3df7aee74cebed524a:1 GET https://mydomain.tld:3000/socket.io/?token=6c74689aac1c3a29c00822af315aec02&EIO=3&transport=polling&t=1530075348125-101 0 ()

**Comment by neil96** [comment]
It's just a request information.

**Comment by spirogg** [comment]
![chat error](https://user-images.githubusercontent.com/17736688/41953919-09eb18e6-799e-11e8-9945-eb5efdf65f26.PNG)
![error-im-chat](https://user-images.githubusercontent.com/17736688/41953921-10f4dee2-799e-11e8-932e-b8457bf6a3e7.PNG)

**Comment by spirogg** [comment]
Do I turn on error reporting in phpfox script then try to use chat. Will that give me error. Not sure where else to check for error. ??

**Comment by spirogg** [comment]
I turned on debug in phpfox script. No errors.

**Comment by spirogg** [comment]
if i click on message for a user in phpfox script it seems like its working but cant use search bar also after send message and login as other user, no message for them ? really weird i updgraded to ver 10 of nodejs 

need some guidence - it doesnt seem to work like your demo version, I have open ticket that paul reply, i have all my account logins for server and phpfox script admincp etc.. please see if you get a change to see whats up.. i folloe direction perfect...

**Comment by spirogg** [comment]
don't worry about this for now, I am getting another server and will try on that or just ask you guys or someone for install and fix this. new server being built right now, so i am Not going to install redis or nodejs or npm
- I will let someone who is better at installing to do it
- if still issues i will open this bug request again

thanks

Spiro
