### ISSUE TITLE
single device login has wrong version number  $this->version = '4.2.0'; install.php file

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2305]
----------------------------------------

## What happened?

I keep seeing the upgrade button for the app > single dvice login after uploading to new install. 
seems you might of forgot to update version number in install.php to 4.2.2
... protected function setName()
    {
        $this->name = 'Single Device Login';
    }

    protected function setVersion()
    {
        $this->version = '4.2.0';
    }

## Steps to reproduce:
1. i uploaded from apps >> files>>Single Device Login the new 4.2.2 app from store
2. after wards clear cache. 
3. still shows we have an upgrade to Single Device Login. I think in code you forgot to update file (install.php) to 4.2.2 

## What is expected?
...Single Device Login app install.php file needs to have version number added to correct version 4.2.2 i still see version 4.2.0 when i look at install.php file 

protected function setName()
    {
        $this->name = 'Single Device Login';
    }

    protected function setVersion()
    {
        $this->version = '4.2.0';
    }

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
php7.1
...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b4

## Screenshots
...

**Comment by neil96** [comment]
Sorry, this is my mistake, I will correct it soon.

**Comment by neil96** [comment]
We updated the package.

Regards.
