### ISSUE TITLE
location in feed not working only get this: https://maps.google.com/maps?daddr=,

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2306]
i have api for google maps but everytine i use location on feed it gives me this address only

https://maps.google.com/maps?daddr=, 
i think the comma is a bug v4.6.1.b4 where can i go to code to see where this comma is coming from ?

----------------------------------------

## What happened?
... using location in feed doesn't give me map when posting (  Iget the dropdown of locations near me - just not the map when I post my feed with location) 
- and link to address is https://maps.google.com/maps?daddr=,

- The static Map works in events when adding a location (just FYI) so api is good ??

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7.1 apache
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b4

...

## Screenshots
...![location google api](https://user-images.githubusercontent.com/17736688/42256232-b365b986-7f15-11e8-9411-ee1e30705093.PNG)

- this is all i get is a link no map

![only link and link is wrong](https://user-images.githubusercontent.com/17736688/42256243-c006f1c8-7f15-11e8-8ce4-4867e160f0cc.PNG)

**Comment by spirogg** [comment]
here is my google maps requests from google, seems the api is working and its something in the script ?

- here is 

![google maps](https://user-images.githubusercontent.com/17736688/42256958-d27e1fb2-7f19-11e8-9ce0-5d7bb1e2db6d.PNG)

**Comment by spirogg** [comment]
![google maps api in use](https://user-images.githubusercontent.com/17736688/42257081-790a43f6-7f1a-11e8-9d71-b791be0eacd5.PNG)

**Comment by spirogg** [comment]
![statc maps work in events](https://user-images.githubusercontent.com/17736688/42257804-059af22c-7f1e-11e8-94c7-11ea3d92c58c.PNG)


- STATIC MAPS WORK IN EVENTS

**Comment by neil96** [comment]
It works in my test. Could you give us more information.
