### ISSUE TITLE
Marketplace SEO small fix see below

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2315]
----------------------------------------

## What happened?
...

`<title>Marketplace Meta Description</title><info>Meta description added to pages related to the Marketplace app. <a role="button" onclick="$Core.editMeta('seo_marketplace_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="marketplace_meta_description"></span></info>`

**- should be:**
`<title>Marketplace Meta Description</title><info>Meta description added to pages related to the Marketplace app. <a role="button" onclick="$Core.editMeta('seo_marketplace_meta_description', true)">Click here</a> to edit meta description.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_marketplace_meta_description"></span></info>`

and this one:

`<title>Marketplace Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Marketplace app. <a role="button" onclick="$Core.editMeta('seo_marketplace_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="marketplace_meta_keywords"></span></info>`

**- should be:** 

`<title>Marketplace Meta Keywords</title><info>Meta keywords that will be displayed on sections related to the Marketplace app. <a role="button" onclick="$Core.editMeta('seo_marketplace_meta_keywords', true)">Click here</a> to edit meta keywords.<span style="float:right;">(SEO) <input style="width:150px;" readonly value="seo_marketplace_meta_keywords"></span></info>`

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by neil96** [comment]
Hi @spirogg ,

`seo_marketplace_meta_description` is a phrase var_name
`marketplace_meta_description` is a setting var_name. We use this var_name in our code. They do not need to be the same and aren't necessary to change.

Other cases are the same.

Regards.
