### ISSUE TITLE
The main search at the top is extremely limited and almost useless

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2318]
Main search does not include pages, groups or photos titles or descriptions.

**Comment by spirogg** [comment]
User Group Settings
Can use the global search tool?

Search Results: cp
For keyword: cp

CPANEL HELP
CH
Cpanel Help
Groups . July 3, 2018


Bruce Wayne
US3EhoaRGVkqXk4xz61vhRefyopn6tlzMAncGK8XCpjeKRSkzEUo1B3DwXP2...
Photo . June 15, 2018


nmbdwcppp
nmbdwcppp
Members . May 1, 2018


Albert Santiago
Sneak Peek for the new phpFox AdminCP
Blog . March 2, 2018



venteens
61TY6cCpXFL._SL1035_
Photo . January 24, 2018



Neil
How do you feel about the new AdminCP in phpFox 4.6.0?
Poll . January 11, 2018



Metro
monkeyfu_s_cutie_mark__request__by_lahirien-d61vcp6
Photo . October 31, 2017



jcpruett98
jcpruett98
Members . October 30, 2016



CPANEL
CP
cpanel
Page . October 12, 2016

**Comment by spirogg** [comment]
v4.phpfox.com I search cp and links to groups photos members poll blog show up are you sure you have that setting on for global search ?

**Comment by neil96** [comment]
Hi @prepperz ,

I can search photo, pages and group in main search normally. Could you test again.


Thanks @spirogg for your information.

Regards.

**Comment by prepperz** [comment]
To reproduce:

Goto to this link: https://v4.phpfox.com/photo/14791/mushrooms/albumid_11655/

Now try to search for mushroom like this:
![screenshot1](https://user-images.githubusercontent.com/19594886/42441769-f8a412fc-8336-11e8-8599-d37591aa3491.png)


The result will be the following:
![screenshot2](https://user-images.githubusercontent.com/19594886/42441715-d9b5dcd6-8336-11e8-9040-34f52c3e47b4.png)

**Comment by spirogg** [comment]
Maybe related to this ?? #2319

**Comment by neil96** [comment]
HI @prepperz ,

To display photos/albums create in pages, you must enable this setting `Display photos/albums which created in Page to the Photo app`. I enabled this setting on our demo, please try again.

Regards.

**Comment by prepperz** [comment]
yup it works now
