### ISSUE TITLE
your demo type in search bar then press search button says: Provide a search query.

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2319]
----------------------------------------

## What happened?
...  if you type in the search bar **phpfox**  and then click with mouse on search button it keeps saying Provide a search query.

if you press enter it works

## Steps to reproduce:
1. login to v4.phpfox.com
2. type in the search bar    phpfox
3. click with mouse on search ( search glass) see phpto below
not working.. if you hit enter on keyboard is the only way it works

## What is expected?
...
should be able to click with mouse and it should work
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b4 freshh install 
and 
v4.phpfox.com demo

## Screenshots
...
![search bar click here not working](https://user-images.githubusercontent.com/17736688/42447274-e747db26-833e-11e8-9607-7e3f311a7bd0.PNG)

**Comment by prepperz** [comment]
if you type in mushroom and press enter, it does not work either.

**Comment by spirogg** [comment]
@prepperz 
Yes you are correct. I tried also. Not working.
