### ISSUE TITLE
Ban Filters only display 1 email domain

### ISSUE THREAD

**Issue by elite1290** [PHPfox-Official/phpfox-v4-issues#2320]
# Important!

Please follow this template!

----------------------------------------

## What happened?
...Ban Filters only display 1 email domain, issue is i added
4-5x email domain *@mail.ru, *@yandex.ru, etc tested all got block working but the display list below always only show the 1st email domain, so now i cannot delete the 2nd,3rd email domain if i want to make change, please fix this bug.

## Steps to reproduce:
1. go to admin, maintainence
2. ban filter
3. select email and add 4-5 email domain, then add, only 1st email domain display, the other 2,3,4th email domain didn't display please fix this bug

## What is expected?
...issue is i added
4-5x email domain *@mail.ru, *@yandex.ru, etc tested all got block working but the display list below always only show the 1st email domain, so now i cannot delete the 2nd,3rd email domain if i want to make change, please fix this bug
![ban-filter-bug](https://user-images.githubusercontent.com/3941435/42566513-6b831dd2-8539-11e8-902a-1a0e7d48162b.png)

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1 latest
...

## Screenshots
...please find attached

**Comment by spirogg** [comment]
Ok it doesn't seem to keep emails under emails even after you clear cache. But if you  clear cache and then go to display. You will see your emails listed. If you delete you have to clear cache to see them deleted. 

@neil96

This area should not be cached. Maybe will work better.

**Comment by spirogg** [comment]
Display Name	Added By	Added On
Delete *@mail.ru	Admin	July 11, 2018
Delete *@yandex.ru

This is a bug. This is a display name area to show a users display name that we ban. Not email section. 

Just fyi.

**Comment by spirogg** [comment]
@neil96 
1) I have a question here. There is a button that says ban. When we add emails or words or IP addresses to exclude. Do we need to click that ban button YES in order for those emails or words or IP etc to be banned. ? Or even if it's off will they still be ban (not allowed to sign up etc. )

**Comment by spirogg** [comment]
seems to be working correct if you clear cache except for this bug #2328

**Comment by neil96** [comment]
Dear,

I tested this feature, everything works normal. Could you give us more information.

Regards.
