### ISSUE TITLE
edited: Pages - SEO, when you add description and keywords they dont show when view source 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2321]
your demo v4.phpfox
----------------------------------------

## What happened?
...
**Pages has same issues as group see below we dont see any keywords or description when view source**
```
<!DOCTYPE html>
--
  | <html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
  | <head>
  | <title>Pages \| Social Networking Community</title>
  | <meta name="description" content="pages_meta_description" />
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="social networking, pages_meta_keywords" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

```

## Steps to reproduce:
1. when you go to SEO >> Pages and add your description and keywords
2. then save, then go to your site and click pages in menu
3. now you go to view source and you will see only the phrase: pages_meta_description and pages_meta_keywords, 
the actual words that you typed in SEO >> pages doesn't show up.

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b4
...

## Screenshots
...

**Comment by neil96** [comment]
Here it is:
<img width="803" alt="view-source_https___v4_phpfox_com_pages_" src="https://user-images.githubusercontent.com/15936115/43053806-cd440a2c-8e58-11e8-969b-8fa4c993cd8e.png">

**Comment by spirogg** [comment]
@neil96 click pages then view source

It Only shows: pages_meta_description
and pages_meta_keywords Phrase.

It does Not show actual SEO description and keywords.

That's the issue
```
title>Pages \| Space Social Networking Community</title>
--
  | <meta name="description" content="pages_meta_description" />
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="Space, social networking, pages_meta_keywords" />
```

i changed in SEO pages and its not showing here ?? so when I add to SEO my own description and keywords it should show after click pages and view source, but its not working

**Comment by spirogg** [comment]
It Only shows: pages_meta_description
and pages_meta_keywords Phrase. 

It does Not show actual SEO description and keywords. 

That's the issue

**Comment by spirogg** [comment]
maybe in pages it should be seo_pages_meta_description and seo_pages_meta_keywords 


change phrase in content="    "  to meta name="description" content="seo_pages_meta_description" />
and 
meta name="keywords" content="Space, social networking, seo_pages_meta_keywords" />


we now have this below when we click pages and view source...

```
<title>Pages \| Space Social Networking Community</title>
--
  | <meta name="description" content="pages_meta_description" />
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="Space, social networking, pages_meta_keywords" />
```


but maybe we need to have it like this to work
```
<title>Pages \| Space Social Networking Community</title>
--
  | <meta name="description" content="seo_pages_meta_description" />
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="Space, social networking, seo_pages_meta_keywords" />
```

**Comment by spirogg** [comment]
This is bug even in your demo. There is no SEO for description or keywords. Just the phrases are showing. Click pages then view source. You will see what you entered in admincp SEO for pages description and keywords. Do not show when you view source.

**Comment by spirogg** [comment]
ok this is BUG

**Comment by neil96** [comment]
It shows, but does not show correct.

**Comment by spirogg** [comment]
@neil96 will this issue be corrected soon ?

**Comment by neil96** [comment]
@spirogg It will be released in next version of Pages App. I don't the detail date 😞

**Comment by spirogg** [comment]
@harrison05
this seems to be fixed.
Thanks you guys. :)
