### ISSUE TITLE
Maps (Check-In) not working php7.1 php7.2 i did fresh install 2 times 4.6.1.b4 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2322]
----------------------------------------

## What happened?
...https://maps.google.com/maps?daddr=,
thts all i get after try to get (check-in) maps to show in feed with php7.1 and php7.2

## Steps to reproduce:
1. go to main page when logged in and click check in add your place or address and submit..
2. only shows a link name and no maps
3. 

## What is expected?
... should show map of (check-in) place you entered if script is compatible with php7.1 and php7.2

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
 php7.1 php 7.2
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b4
...

## Screenshots
...
![location google api](https://user-images.githubusercontent.com/17736688/42664410-3f0b11ac-8600-11e8-8297-dd723c4afe20.PNG)
![maps not working](https://user-images.githubusercontent.com/17736688/42664412-3f178608-8600-11e8-9d39-d2a792df8158.PNG)
![no map](https://user-images.githubusercontent.com/17736688/42664413-3f231f4a-8600-11e8-881a-066784daecd1.PNG)
![only link and link is wrong](https://user-images.githubusercontent.com/17736688/42664414-3f2e631e-8600-11e8-853e-786f591420ab.PNG)

**Comment by spirogg** [comment]
all are enabled

![i have all enabled](https://user-images.githubusercontent.com/17736688/42669170-abb33014-8619-11e8-827f-52421d1b5bb7.PNG)

no restrictions on my api key ?
still not working

![google api unrestricted for testing only](https://user-images.githubusercontent.com/17736688/42669174-afc826fa-8619-11e8-82e9-7ae6ada85c69.PNG)

**Comment by spirogg** [comment]
API working because in events i get static maps so the google api is working this brings me to believe this is phpfox issue not user issue, i've installed before earlier versions and it worked latest versions 4.6.1.b4 and b4 not working

**Comment by spirogg** [comment]
**OK HERE IS ISSUE in PHP7.2 there is no mcrypt extension
 so maps dont work without it in php7.1 php7.0 Maps work because we have mcrypt extension**


- here is something I found online a little old but read: 

PHP 7.2 is coming… mcrypt extension isn’t
Early September, it’s about 3 months before PHP 7.2 is expected to be release (schedule here). One of the changes is the removal of the mcrypt extension after it was deprecated in PHP 7.1. The main problem with mcrypt extension is that it is based on libmcrypt that was abandoned by it’s upstream since 2007. That’s 10 years of keeping a library alive, moving the burden to distribution’s security teams. But this isn’t new, Remi already wrote about this two years ago: “About libmcrypt and php-mcrypt“.

But with removal of the extension from the PHP code base , it would force the recommendation was done “nicely” till now. And forcing people means some noise, although an alternative is PHP’s owns openssl extension. But as many migrations that require code change – it’s going slow.

The goal of this post is to reach to the PHP eco system and map the components (mostly frameworks and applications) to still require/recommend mcyrpt and to pressure them to fix it before PHP 72 is released. I’ll appreciate the readers’ help with this mapping in the comments.

For example, Laravel‘s release notes for 5.1:

In previous versions of **Laravel, encryption was handled by the mcrypt PHP extension**. However, beginning in **Laravel 5.1, encryption is handled by the openssl extension**, which is more actively maintained.

**Comment by spirogg** [comment]
https://lukasmestan.com/install-mcrypt-extension-in-php7-2/

The mcrypt extension is an interface to the mcrypt cryptography library. This extension is useful for allowing PHP code using mcrypt to run on PHP 7.2+.

The main problem with mcrypt extension is that it is based on libmcrypt that hasn’t been developped since its upstream in 2007. Thus, it has been already 10 years, even though the library has been still used. However, without the proper developement and maintenance library has become security alert for many system administrators.

Because of the end of the mcrypt extension’s development, the extention was also removed from PHP 7.2 and moved to an unofficial PECL repository. However, you can still find the mcrypt extention in PHP 5.4 through PHP 7.1. The arrival of PHP 7.2 has been announced but it won’t contain mcrypt extention. For PHP 7.2+, PHP instead uses libsodium as a cryptography library

**Comment by spirogg** [comment]
@neil96 
**ok sorry its php7.1 and 7.2 NOT WORKING** 

**ONLY php7.0 works for maps** 

I have same extensions in 7.1 but they do not work
if someone can share if 7.1 or 7.2 works for them,  then let us know here please.

here is my extensions in php7.0  php7.1  php7.2 

i'm using cPanel with EA4


- **Apache 2.4**

config

config-runtime

mod_bwlimited

mod_cgid

mod_deflate

mod_expires

mod_headers

mod_hostinglimits

mod_mpm_event

mod_proxy

mod_proxy_fcgi

mod_proxy_http

mod_proxy_wstunnel

mod_remoteip

mod_ssl

mod_suexec

mod_suphp

tools


- **PHP 5.6**

build

libc-client

pear

php-bcmath

php-calendar

php-cli

php-common

php-curl

php-devel

php-exif

php-fileinfo

php-fpm

php-ftp

php-gd

php-imap

php-intl

php-ioncube

php-litespeed

php-mbstring

php-mcrypt

php-mysqlnd

php-pdo

php-posix

php-sockets

php-xml

php-xmlrpc

php-zendguard

php-zip

runtime

- **PHP 7.0**

build

libc-client

pear

php-bcmath

php-calendar

php-cli

php-common

php-curl

php-devel

php-exif

php-fileinfo

php-fpm

php-ftp

php-gd

php-imap

php-intl

php-ioncube6

php-litespeed

php-mbstring

php-mcrypt

php-mysqlnd

php-opcache

php-pdo

php-posix

php-sockets

php-tidy

php-xml

php-xmlrpc

php-zip

runtime

- **PHP 7.1**

build

libc-client

pear

php-bcmath

php-calendar

php-cli

php-common

php-curl

php-devel

php-exif

php-fileinfo

php-fpm

php-ftp

php-gd

php-imap

php-intl

php-ioncube10

php-litespeed

php-mbstring

php-mcrypt

php-mysqlnd

php-opcache

php-pdo

php-posix

php-sockets

php-tidy

php-xml

php-xmlrpc

php-zip

runtime

- **PHP 7.2**

build

libc-client

pear

php-bcmath

php-calendar

php-cli

php-common

php-curl

php-devel

php-exif

php-fileinfo

php-fpm

php-ftp

php-gd

php-imap

php-intl

php-ioncube10

php-litespeed

php-mbstring

php-mysqlnd

php-opcache

php-pdo

php-posix

php-sockets

php-tidy

php-xml

php-xmlrpc

php-zip

runtime

- **Others**

apr

apr-util

brotli

cpanel-tools

documentroot

libcurl

libmcrypt

libnghttp2

libtidy

libxml2

nghttp2

openssl

openssl-devel

php-cli

php-cli-lsphp

profiles-cpanel

**Comment by david-phpFox** [comment]
Hi spirogg, 

Please update php.ini on php version > 7.1
Set serialize_precision = -1

Best Regards,
David Nguyen

**Comment by spirogg** [comment]
@davidnguyen88 

in php7.2 
php-mcrypt seems to be the only difference from the other php versions.
  Is this why maps won't work in php7.2 because 7.2 doesn't support extension php-mcrypt ? 

#2324

**Comment by neil96** [comment]
Hi @spirogg ,

Our demo uses php 7.1, my test site uses php 7.2, both work normal. Could you give us more information.

Regards.

**Comment by spirogg** [comment]
Is maps dependent on php-mcrypt ? Because I don't have it on php7.2 or is it dependent on this : Set serialize_precision = -1

**Comment by neil96** [comment]
No, it isn't. The maps is using javascript to load.

Regards.

**Comment by spirogg** [comment]
I will set php.ini for both 7.1 and 7.2 to: 
Set serialize_precision = -1
If this works. I will close this. If not I will try give more Info as I can. 

Thank you

**Comment by spirogg** [comment]
OK I setup php.ini for both 7.1 and 7.2 to:
Set serialize_precision = -1
THIS WORKS NOW
@davidnguyen88 @neil96  you guys are awesome!!!!!!
Thank you so much php7.2 is faster than 7.0 with phpfox script.. thanks again closing this ticket
