### ISSUE TITLE
Question: The mcrypt-extension is deprecated will be removed in PHP 7.2 ?.

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2324]
----------------------------------------

## What happened?
...
The mcrypt-extension is deprecated and will be removed in PHP 7.2 according to the comment posted here. 
https://bugs.php.net/bug.php?id=73734

Do we need to worry about this with phpfox script not working properly trying to use php7.2 ?? 

Just wondering. 

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

... php7.2 

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b4

## Screenshots
...

**Comment by neil96** [comment]
Hi @spirogg ,

Our core script does not use this library. Some vendors in phpFox use it, however it does not cause an error. Please don't worry.

Regards.

**Comment by spirogg** [comment]
Ok thank you.
