### ISSUE TITLE
proper placement of meta name="description"  in 2 areas

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2325]
----------------------------------------

## What happened?
... Clicking on Home and browse doesn't show the proper placement of meta name="description" 
should be right under <head>

example below is missing proper placement of <meta name="description"
- this is Home:  view-source:https://v4.phpfox.com/

```
<!DOCTYPE html>

  | <html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
  | <head>
  | <title>Social Networking Community</title>
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="social networking, phpFox demo" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

```

- this is Browse:  view-source:https://v4.phpfox.com/user/browse/

example below is missing proper placement of <meta name="description"
```
<!DOCTYPE html>
--
  | <html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
  | <head>
  | <title>Browse Users &#187; Social Networking Community</title>
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="social networking, phpFox demo" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

```

- why don't we have meta name description in same area as other meta name:
 I think this ruins  SEO and for google to pickup properly our description 

## Steps to reproduce:
1.  go here :     view-source:https://v4.phpfox.com/
2. also go here :     view-source:https://v4.phpfox.com/user/browse/
3. see that there is no <meta name="description" like all other links

## What is expected?
...
- proper placement of <meta name="description" for home https://v4.phpfox.com/ 
and 
- members (browse) https://v4.phpfox.com/user/browse/

- example below of proper placement of <meta name="description"

```
<!DOCTYPE html>
--
  | <html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en">
  | <head>
  | <title>Videos &#187; Social Networking Community</title>
  | <meta name="description" content="Share your videos with friends, family, and the world on phpFox Demo UK." />
  | <meta name="robots" content="index,follow" />
  | <meta name="keywords" content="social networking, phpFox demo, video, sharing, free, upload in US" />
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  | <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

```

thanks

Spiro

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b4
...

## Screenshots
...

**Comment by neil96** [comment]
Hi @spirogg ,

The meta description is the end of `head` tag. Please check again.

Regards.

**Comment by spirogg** [comment]
Yes sorry my mistake. :) I will close.
