### ISSUE TITLE
Ban Filter: if you click ban button Yes then No it give you more options only, but not by default - so no one know its got more options ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2328]
----------------------------------------

## What happened?
...
 ok so we go to admincp>>maintenance>>ban filters
you see area with Ban NO as default, if you click Ban Yes then Ban NO it will then allow you to have more options to write why you ban, these options should be available in default (first time you go to Ban Filters, If you dont know to click Ban button YES and then NO you never know that those options are available ?
## Steps to reproduce:
1. go to admincp>>maintenance>>ban filters
2. then click Ban button to YES
3. then click Ban button to NO (now you see more options) 

## What is expected?
...
should be default that you see Ban Filter: Options 
when you first go to admincp>>maintenance>>ban filters

**- See photos of explanation**

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome latest
## Server information
(Example: CentOS 7, php 7.1 apache)
cdntos 7 php7.0
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b4
...

## Screenshots
...

**- Here is first default view when you click Ban Filters**
 **you should see more options in this first view or you never know there is more options**

![banfilters](https://user-images.githubusercontent.com/17736688/42926118-0dfc9d60-8af6-11e8-87c6-88753d129dbd.PNG)

**- Here is view when you click Ban Filters YES**

![banfilters1](https://user-images.githubusercontent.com/17736688/42926119-0e0f5126-8af6-11e8-9d95-7eda6743c4c7.PNG)

**- Here is view when you click Ban Filters NO again (here you see more options only after click Ban button YES and then NO)**

![banfilters-no-yes-no](https://user-images.githubusercontent.com/17736688/42926120-0e20e53a-8af6-11e8-967e-d06ff901440f.PNG)

**Comment by neil96** [comment]
The more options should visible when **Ban User** is yes.

Regards.
