### ISSUE TITLE
Found the BUG: after add words in ban filters: I clear cache then it says  Cache Manager **No cache data found.** this is error

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2329]
----------------------------------------

## What happened?
... I go to add words in ban filter then cache manager and see this below:
Cache Manager
**Total Objects: 379**
**Cache Size: 1.66 Mb**

I then click clear cache then it says 
Cache Manager
**No cache data found.**
## Steps to reproduce:
1. admincp add a few words in Ban Filter 
2. then go to clear cache you will see not found
3. then go delete ban filter words and then clear cache now it works as should be

## What is expected?
if you add ban filter words you should still see cache like below

**- after click cache should be like below**
...Cache Manager
Total Objects: 2
Cache Size: 69 b

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php7.0 nginx
...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b4

## Screenshots
...
- first go to add Ban Filters - Words

![add word in ban and no cahce issue appears](https://user-images.githubusercontent.com/17736688/42981195-9aa687d0-8ba0-11e8-87e5-d133da467c54.PNG)

![ban filters words same replacement word error with cache not found](https://user-images.githubusercontent.com/17736688/42981198-9deaaca0-8ba0-11e8-8cad-a4dcfa48724b.PNG)

- then click on cache manager

![click cache manager](https://user-images.githubusercontent.com/17736688/42981201-a29eb796-8ba0-11e8-872b-4cb10d4f0483.PNG)

- then click on clear cache

![clear cache not found](https://user-images.githubusercontent.com/17736688/42981206-a511e3ea-8ba0-11e8-8ca7-3b2fb0698734.PNG)

- If no words in Ban Filters Clear cache works as it should

![if no words cahce works correctly](https://user-images.githubusercontent.com/17736688/42981216-b351db54-8ba0-11e8-91e1-ce73a0f4fa4c.PNG)

**Comment by spirogg** [comment]
also to note: I added 2 same prmotions by accident
regsiter user to be group 1 

0 days or 1 point 
just to test if working after i notice promotion is same I delete all promotions make user back to registered user. clear cache and it say cache not found. - also then i delete users from registered user do I have only 1 admin user. clear all cache - clear cache - delete cache dolders and files at PF.Base/file/cache/here and still have same error message - issue (cache Not Found)

**Comment by spirogg** [comment]
I also went to  maria database i run: check database. and repair database 
all said ok still same issue cache not found

**Comment by neil96** [comment]
Hi @spirogg ,

You get this message **No cache data found** because there are no cache were generated at the time you view. Sometime you get this message after you clear cache. This is normal.

Regards.

**Comment by spirogg** [comment]
@neil96 you are wrong go test it.

 **this happens all the time when you add 1 word to Ban filters for all of site** 
after you add one word to Ban Filters all the time you will see No Cache Data Found

you can add one word to Ban Filter then use site how you would use it then after 2 3 4 5 10mins go clear cache you will see same message No Cache Data Found

**Comment by neil96** [comment]
I assert that message "No Cache Data Found" is normal.
