### ISSUE TITLE
ban words don't work in shoutbox ? can this work somehow ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2331]
## What happened?
...ban words don't work in shoutbox ? can this work somehow ?

## Steps to reproduce:
1. if you ban a few words and then go add something to shoutbox
2. the ban words still show up
3. 

## What is expected?
...
- ban words to change to other word like how it works in feeds

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php7.0
...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b4

## Screenshots
...
![shoutbox](https://user-images.githubusercontent.com/17736688/42993839-0b6ebb3c-8bd2-11e8-9743-a7d3c5c8a40f.PNG)

**Comment by david-phpFox** [comment]
Will fix in Shoutbox App 4.2.1
