### ISSUE TITLE
Pages All Events Shows Nothing

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2332]
After creating an event on pages, clicking "All" events shows nothing.

**Comment by spirogg** [comment]
Hi @prepperz look at the start time. It has to be current to show.

Example below: 
 If it's for tomorrow at 9am till Friday at 9pm. It won't show in all untill 9am tomorrow if you set it for today and it's 8am you would need to set it today start at 8am end whenever you want. Then it will show in All Events. 
I just tested. 

Hope this helps coear this up. :)

**Comment by spirogg** [comment]
Also there is a drop-down for sorting events. It says ongoing if you click that sort drop-down you see All Time ,

Select and it will show you all events. 
See photos.   Also I remember seeing a setting to show events already past I think. Do search in admin for events. And see the list and there is a setting there that might be to show all events even if expired or not started. 

![screenshot_20180729-052544](https://user-images.githubusercontent.com/17736688/43365287-251862e8-92f0-11e8-913f-98befc0eb2c4.png)
![screenshot_20180729-052603](https://user-images.githubusercontent.com/17736688/43365290-306ecc18-92f0-11e8-8352-ad123c9484ad.png)

**Comment by neil96** [comment]
Thanks @spirogg for help me explain this.

Regards.
