### ISSUE TITLE
Sitewide block 6 code insert does not display / work for pages > blogs, videos, events, forums, photos

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2333]
Sitewide block 6 code insert does not display / work for pages > blogs, videos, events, forums, photos.

This might be the same for groups.

This is on the bootstrap template have not tried on others.

**Comment by neil96** [comment]
It works in my test. On both templates. Could you give us more information.

Regards.

**Comment by spirogg** [comment]
@prepperz   check your log for errors  /PF.Base/file/log/main.log

**Comment by prepperz** [comment]
steps to reproduce: 
1. create block. select: produce > core, modeule > core, typee > phpcode, page > sitewide 

insert the following code

`<div id="google_translate_element"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>`

2. You will notice that "select language" is visble at this link: https://v4.phpfox.com/stupid/info

For the following pages "select language" is not displayed or working.

https://v4.phpfox.com/stupid/blog/

https://v4.phpfox.com/stupid/event/

https://v4.phpfox.com/stupid/forum/

https://v4.phpfox.com/stupid/photo/

https://v4.phpfox.com/stupid/video/

**Comment by harrison05** [comment]
This block still show in User Profile on my site
![screen shot 2018-09-19 at 10 11 41](https://user-images.githubusercontent.com/41947198/45729020-d5e88580-bbf4-11e8-87d8-084fa2322269.png)

**Comment by prepperz** [comment]
@harrison. You're in the wrong area wrong area. This is for the only for pages section. See title or first post.

**Comment by harrison05** [comment]
@prepperz ya, I found this on my side. We will check it. 

Thanks.
