### ISSUE TITLE
I found error logs for music app sponsor a song,no block showing please read.

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2334]
----------------------------------------

## What happened?
... when you go to sponosr a song it doesnt have a block that shows up? also when un-feature a song it still stays on feature block until you clear cache. 

when you un-sponsor a song - (the popup comes up ** Song Successfully Unsponsored** but it is stuck there doesn't disappear on its own, I wait 1 minute still there... but un-feature it goes away on its own.
## Steps to reproduce:
1. go to music app click sponsor no block for sponsored music and un-sponsor popup doesn't go away unless you click the X

2. feature song then unfeature song you have to go to admincp to clear cache in order for it wot not display any longer

3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 nginx 
...

Core Version: | 4.6.1 (build 5)
-- | --
PHP Version: | 7.2.8
PHP Sapi: | fpm-fcgi
PHP safe_mode: | False
PHP open_basedir: | False
PHP Disabled Functions: | None
PHP Loaded Extensions: | Core date libxml openssl pcre zlib filter hash Reflection SPL session standard cgi-fcgi ctype curl dom ftp gd imap intl json mbstring mysqlnd PDO Phar posix SimpleXML sqlite3 tokenizer xml xmlwriter xsl zip mysqli pdo_mysql pdo_sqlite wddx xmlreader xmlrpc Zend OPcache
Operating System: | Linux
Server Time Stamp: | July 31, 2018, 9:31 am (GMT)
GZIP: | Enabled
SQL Driver Version: | MySQL 5.5.5-10.2.16-MariaDB
SQL Slave Enabled: | No
SQL Total Slaves: | N/A
SQL Slave Server: | N/A
Memory Limit: | 0.5 b (-1)
Load Balancing Enabled: | No
Total Server Memory: | 31886 MB
Available Server Memory: | 26740 MB
Current Server Load: | 0.12

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots
...

![sponsor song no block](https://user-images.githubusercontent.com/17736688/43451610-f513b412-947a-11e8-97ed-dacd85849b17.PNG)
![sponsored music no block shows](https://user-images.githubusercontent.com/17736688/43451611-f527315e-947a-11e8-9248-a3943fbc0f19.PNG)
![sponsored](https://user-images.githubusercontent.com/17736688/43451612-f5385e8e-947a-11e8-9653-14d4894a0973.PNG)
![unsponsor stuck wont go away](https://user-images.githubusercontent.com/17736688/43451613-f555005c-947a-11e8-9ed3-212245aeb522.PNG)

**Comment by neil96** [comment]
FYI: These blocks are cached, so there are a little delay to update new content.

**Comment by spirogg** [comment]
There is no block for sponsored. . That's the issue. I cannot get sponsored block to show. This is fresh install of 4.6.1.b5

**Comment by spirogg** [comment]
It's been 2 days. No sponsored block shows up.

**Comment by spirogg** [comment]
https://user-images.githubusercontent.com/17736688/43451611-f527315e-947a-11e8-9248-a3943fbc0f19.PNG

**Comment by neil96** [comment]
<img width="924" alt="screen shot 2018-08-02 at 14 51 39" src="https://user-images.githubusercontent.com/15936115/43570056-98872a0e-9663-11e8-8661-4c1d74712211.png">
This block should be added by default. Does someone remove it on your site?

Regards.

**Comment by spirogg** [comment]
No sir. I just did fresh install and testing. Never show.

**Comment by neil96** [comment]
Yes, fresh install and this block is added by default.

Regards.

**Comment by spirogg** [comment]
Sorry not for me. Is this the music app that adds this by default. Maybe I need try download music app again ? Because I don't have this block. In photos app it works but not music app.

**Comment by spirogg** [comment]
The block is under music main. But doesn't show up on website  It's using block 3 it's really weird.

**Comment by spirogg** [comment]
@neil96  I just did another fresh install 3 times using default material theme, I did not add another theme, just left everything default and I still get same issue ??? 

here is log file errors 

 /PF.Base/file/log/main.log

error
2018-08-02 17:36:10
[256] Call to undefined method Apps\Core_Music\Service\Callback::enableSponsor_song() (/home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99]
Error Code: 41f474
Stack trace:

```
# stream loggererror
2018-08-02 17:29:11
[256] Call to undefined method Apps\Core_Music\Service\Callback::enableSponsor_song() (/home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99]
Error Code: 540a96
Stack trace:
#0 /home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error('Call to undefined method Apps\Co...', 256)
#1 /home/ls/public_html/PF.Site/Apps/core-music/Service/Callback.php(1965): Phpfox_Error::trigger('Call to undefined method Apps\Co...', 256)
#2 /home/ls/public_html/PF.Base/include/library/phpfox/module/module.class.php(1526): Apps\Core_Music\Service\Callback->__call('enableSponsor_song', Array)
#3 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(660): Phpfox_Module->callback('music.enableSponsor_song', Array)
#4 /home/ls/public_html/PF.Site/Apps/core-better-ads/Service/Process.php(138): Phpfox::callback('music.enableSponsor_song', Array)
#5 /home/ls/public_html/PF.Site/Apps/core-music/Ajax/Ajax.php(146): Apps\Core_BetterAds\Service\Process->addSponsor(Array)
#6 /home/ls/public_html/PF.Base/include/library/phpfox/ajax/ajax.class.php(213): Apps\Core_Music\Ajax\Ajax->sponsorSong()
#7 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1482): Phpfox_Ajax->process()
#8 /home/ls/public_html/PF.Base/start.php(636): Phpfox::run()
#9 /home/ls/public_html/index.php(9): require('/home/lsspace/public_html/PF.Bas...')
#10 {main}


error
2018-08-02 17:36:10
[256] Call to undefined method Apps\Core_Music\Service\Callback::enableSponsor_song() (/home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99]
Error Code: 41f474
Stack trace:
#0 /home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error('Call to undefined method Apps\Co...', 256)
#1 /home/ls/public_html/PF.Site/Apps/core-music/Service/Callback.php(1965): Phpfox_Error::trigger('Call to undefined method Apps\Co...', 256)
#2 /home/ls/public_html/PF.Base/include/library/phpfox/module/module.class.php(1526): Apps\Core_Music\Service\Callback->__call('enableSponsor_song', Array)
#3 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(660): Phpfox_Module->callback('music.enableSponsor_song', Array)
#4 /home/ls/public_html/PF.Site/Apps/core-better-ads/Service/Process.php(138): Phpfox::callback('music.enableSponsor_song', Array)
#5 /home/ls/public_html/PF.Site/Apps/core-music/Ajax/Ajax.php(146): Apps\Core_BetterAds\Service\Process->addSponsor(Array)
#6 /home/ls/public_html/PF.Base/include/library/phpfox/ajax/ajax.class.php(213): Apps\Core_Music\Ajax\Ajax->sponsorSong()
#7 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1482): Phpfox_Ajax->process()
#8 /home/ls/public_html/PF.Base/start.php(636): Phpfox::run()
#9 /home/ls/public_html/index.php(9): require('/home/lsspace/public_html/PF.Bas...')
#10 {main}


error
2018-08-02 17:44:28
[256] Call to undefined method Apps\Core_Music\Service\Callback::enableSponsor_song() (/home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99]
Error Code: 0512eb
Stack trace:
#0 /home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error('Call to undefined method Apps\Co...', 256)
#1 /home/ls/public_html/PF.Site/Apps/core-music/Service/Callback.php(1965): Phpfox_Error::trigger('Call to undefined method Apps\Co...', 256)
#2 /home/ls/public_html/PF.Base/include/library/phpfox/module/module.class.php(1526): Apps\Core_Music\Service\Callback->__call('enableSponsor_song', Array)
#3 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(660): Phpfox_Module->callback('music.enableSponsor_song', Array)
#4 /home/ls/public_html/PF.Site/Apps/core-better-ads/Service/Process.php(138): Phpfox::callback('music.enableSponsor_song', Array)
#5 /home/ls/public_html/PF.Site/Apps/core-music/Ajax/Ajax.php(146): Apps\Core_BetterAds\Service\Process->addSponsor(Array)
#6 /home/ls/public_html/PF.Base/include/library/phpfox/ajax/ajax.class.php(213): Apps\Core_Music\Ajax\Ajax->sponsorSong()
#7 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1482): Phpfox_Ajax->process()
#8 /home/ls/public_html/PF.Base/start.php(636): Phpfox::run()
#9 /home/ls/public_html/index.php(9): require('/home/lsspace/public_html/PF.Bas...')
#10 {main}


error
2018-08-02 17:50:42
[256] Call to undefined method Apps\Core_Music\Service\Callback::enableSponsor_song() (/home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99]
Error Code: e5b273
Stack trace:
#0 /home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error('Call to undefined method Apps\Co...', 256)
#1 /home/ls/public_html/PF.Site/Apps/core-music/Service/Callback.php(1965): Phpfox_Error::trigger('Call to undefined method Apps\Co...', 256)
#2 /home/ls/public_html/PF.Base/include/library/phpfox/module/module.class.php(1526): Apps\Core_Music\Service\Callback->__call('enableSponsor_song', Array)
#3 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(660): Phpfox_Module->callback('music.enableSponsor_song', Array)
#4 /home/ls/public_html/PF.Site/Apps/core-better-ads/Service/Process.php(138): Phpfox::callback('music.enableSponsor_song', Array)
#5 /home/ls/public_html/PF.Site/Apps/core-music/Ajax/Ajax.php(146): Apps\Core_BetterAds\Service\Process->addSponsor(Array)
#6 /home/ls/public_html/PF.Base/include/library/phpfox/ajax/ajax.class.php(213): Apps\Core_Music\Ajax\Ajax->sponsorSong()
#7 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1482): Phpfox_Ajax->process()
#8 /home/ls/public_html/PF.Base/start.php(636): Phpfox::run()
#9 /home/ls/public_html/index.php(9): require('/home/lsspace/public_html/PF.Bas...')
#10 {main}


error
2018-08-02 17:55:54
[256] Call to undefined method Apps\Core_Music\Service\Callback::enableSponsor_song() (/home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php) [99]
Error Code: 417bb4
Stack trace:
#0 /home/ls/public_html/PF.Base/include/library/phpfox/error/error.class.php(99): trigger_error('Call to undefined method Apps\Co...', 256)
#1 /home/ls/public_html/PF.Site/Apps/core-music/Service/Callback.php(1965): Phpfox_Error::trigger('Call to undefined method Apps\Co...', 256)
#2 /home/ls/public_html/PF.Base/include/library/phpfox/module/module.class.php(1526): Apps\Core_Music\Service\Callback->__call('enableSponsor_song', Array)
#3 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(660): Phpfox_Module->callback('music.enableSponsor_song', Array)
#4 /home/ls/public_html/PF.Site/Apps/core-better-ads/Service/Process.php(138): Phpfox::callback('music.enableSponsor_song', Array)
#5 /home/ls/public_html/PF.Site/Apps/core-music/Ajax/Ajax.php(146): Apps\Core_BetterAds\Service\Process->addSponsor(Array)
#6 /home/ls/public_html/PF.Base/include/library/phpfox/ajax/ajax.class.php(213): Apps\Core_Music\Ajax\Ajax->sponsorSong()
#7 /home/ls/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1482): Phpfox_Ajax->process()
#8 /home/ls/public_html/PF.Base/start.php(636): Phpfox::run()
#9 /home/ls/public_html/index.php(9): require('/home/lsspace/public_html/PF.Bas...')
#10 {main}
```

**Comment by spirogg** [comment]
ok so here is the block content for music. It shows Sponsor but it does not work.. I tried 4 times to reinstall and still same issue. 


![here is block content](https://user-images.githubusercontent.com/17736688/43605221-53573312-965d-11e8-9e8e-a206627e54f6.PNG)

**Comment by spirogg** [comment]
#2337

**Comment by spirogg** [comment]
ticket number support-phpfox#588497 with login details to mysite

**Comment by spirogg** [comment]
PS I'm using Material theme you show me bootstrap theme. Did you test material theme also. ?

**Comment by neil96** [comment]
It seems your `better ads app` does not up to date.

Regards.

**Comment by spirogg** [comment]
It's fresh install I will try to update better ads but I think it's issue. I got 2 emails to update. But was the same version 4.2.2 
can you check if tye version number for better ads is correct. On your end.

**Comment by spirogg** [comment]
@neil96 better ads, It shows I have version 4.2.2 of better ads when view installed apps

there is no other update.. In store shows 4.2.2 for better ads also and in my admincp I have ads 4.2.2 ?

so it shows I have latest verison, so this has to be bug or you didn't change to correct version number in store like the , and possibly related to this #2337

**Comment by spirogg** [comment]
@neil96 @Harrison05 this is a bug YES ??

**Comment by spirogg** [comment]
@harrison05
this seems to be fixed.
Thanks you guys. :)
