### ISSUE TITLE
eGift shows code tags in first category 1st and last page

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2335]
![screenshot](https://user-images.githubusercontent.com/19594886/43537005-15ba0df8-958c-11e8-86c6-d19fcd17fe7f.png)

![screenshot-1](https://user-images.githubusercontent.com/19594886/43537014-1b77249c-958c-11e8-851f-2a810bb43f35.png)

**Comment by neil96** [comment]
Could you give us more information.

Thanks!

**Comment by spirogg** [comment]
@prepperz check your log for errors  /PF.Base/file/log/main.log

**Comment by prepperz** [comment]
Steps to reproduce
1. for category 1, you need to add 9 images. In category 2, add 10 images. In category 3, add 10 images.

2. Now go visit a profile and click the gift icon and you'll see the code tag in the first category.

**Comment by harrison05** [comment]
Do you check on the newest version of eGift (v4.6.1)? Because we still can't reproduce it.

Regards.
