### ISSUE TITLE
when change color in Design theme header, mobile header doesn't change

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2336]
----------------------------------------

## What happened?
... I change the color of my header to blue, and my logo colors to white, but when logged in in mobile version the header does not change color so you cant see the logo ? is the header not suppose to change in mobile view also ?

## Steps to reproduce:
1. go to admincp then go to appearance, themes, 
2. select yout theme and then go to Design
3. change Header color then save, then login with mobile device and click on menu and you don't see your logo cause the header its always white?

## What is expected?
...
header color in menu on mobile view should change to same color as header color we choose in Design so when click on menu our logo will look same as on desktop website colors

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 nginx php7.2
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5 fresh install
...

## Screenshots
...
![change color to header](https://user-images.githubusercontent.com/17736688/43547273-641fe4cc-95a0-11e8-98ab-baff04469711.PNG)

**Comment by neil96** [comment]
Hi,

It's not a header friend.

Regards.

**Comment by spirogg** [comment]
Anyway to make this color change when we change colors ? Or no way possible. 

Thanks :)

**Comment by neil96** [comment]
It's possible. But it's inconsequential!

**Comment by spirogg** [comment]
No worries.
