### ISSUE TITLE
The currency for your membership has no price

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2337]
----------------------------------------

## What happened?
... i am registered user I setup to allow sponsor music, when I click on sponsor a song I get this:
- The currency for your membership has no price

but in my settings I have currency set as USD.  what is wrong here ??

what is issue ?

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/43607846-139f779a-9665-11e8-9395-ff5ed2d4dd16.PNG)

**Comment by spirogg** [comment]
isetup registered user to be able to purchase sponsor song, 1.00 and in currency i have set USD to be default
in Account settings for this registered user, i select currency drop down and slelect US, Dollars and then click save ?
so still i get this issue

**Comment by spirogg** [comment]
ticket number support-phpfox#588497 with login details to mysite

**Comment by spirogg** [comment]
i look in forum but no luck with this

https://community.phpfox.com/forum/thread/46094/the-currency-for-your-membership-has-no-price/

**Comment by neil96** [comment]
Could you also set price for Euro and Pound.

Regards.

**Comment by spirogg** [comment]
Yes in music app I set 1.00 for all songs and albums. For all 3 currency. Do I need to add currency for all apps ?? Or just music.

**Comment by spirogg** [comment]
@neil96 this is bug..  I've added 1.00 to everything all currency in music app still issue.
 if this is related to better ads, It shows I have version 4.2.2 of better ads there is no update..
