### ISSUE TITLE
in music app user profile pic not showing see photo

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2338]
----------------------------------------

## What happened?
...
after adding a song to music section, you dont see a profile pic in all songs, my songs, friends songs see photo. If you dont add a profile pic it shows example (AD) for admin. 

 if you add your profile pic, then it doesn't show anything. 

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
... must have3 profile pic in this area

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 nginx php7.2
...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots
...
![user profile pic not showing](https://user-images.githubusercontent.com/17736688/43664304-18ed131a-9732-11e8-83ac-5b0caf41249d.PNG)

**Comment by neil96** [comment]
It works on my side. Do you use phpFox storage or S3?

Regards.

**Comment by spirogg** [comment]
Nope. 

 I do not use any storage. Only regular file system in phpfox script.

**Comment by spirogg** [comment]
@neil96 also when you go to browse members and select a member the 120.png doesnt show 404 error when i right mouse click on photo area and click inspect in chrome browser says 404 error. this seems to be the same 120.png thats not showing in music app
![capture](https://user-images.githubusercontent.com/17736688/43743088-13bfbda6-999a-11e8-9908-ae5054a96e5e.PNG)

![404 error](https://user-images.githubusercontent.com/17736688/43741047-add01862-9992-11e8-8f78-3717b3648620.PNG)

- 
![no profile pic showing here](https://user-images.githubusercontent.com/17736688/43741049-b0ea837a-9992-11e8-81d1-7da1fd5797ce.PNG)

**Comment by spirogg** [comment]
same with photo for music app 

![capture](https://user-images.githubusercontent.com/17736688/43743159-5aafcb0c-999a-11e8-9adc-5701266298c2.PNG)
![404 error](https://user-images.githubusercontent.com/17736688/43743162-5ce1010c-999a-11e8-945d-3708f98922f3.PNG)

**Comment by harrison05** [comment]
Did you disable setting "Keep Non Square Images" on your site?

Regards.

**Comment by spirogg** [comment]
![keep non sqaure images](https://user-images.githubusercontent.com/17736688/43751525-d90fb354-99c2-11e8-80ff-40e604abb2dc.PNG)

**Comment by spirogg** [comment]
@Harrison05 do I leave it NO or turn it YES ??

**Comment by spirogg** [comment]
> Keep Non Square Images
> By default we create 2 thumbnails for each image. One keeps the original aspect ratio and the other is a fixed square image. With our current themes we only use the fixed square images. The original aspect ratio images are not really needed and disabling this feature is advised.

it say disabling this feature is advised ???

**Comment by harrison05** [comment]
@spirogg  Currently, you set it NO. So, the avatar with suffix **_120** doesn't exist. 
We will fix this bug in Music and Core.

Regards.

**Comment by spirogg** [comment]
@harrison05 @neil96 can you help out here for HellasCosmos
I think this is same issue on CDN not working, cant get a feed post of a photo or even in groups to add cover photo etc. 404 error not finding _500.jpg _1024.jpg 

he just upgrade to 4.6.1.b5 and now users cant use the site


"keep files on server" were off,    I turn it ON now
and "keep sqaure images" are YES now, but still cant upload a photo in feed and can't upload a cover photo in groups

please see here maybe you can fix his site or help him
https://community.phpfox.com/forum/thread/57398/group-cover-photo-not-show/

**Comment by spirogg** [comment]
EXAMPLE:
```
https://www.domain.com/CDN/file/file/pic/photo/2018/08/1626a8ff560a9f914516a352fe068217_1024.png
HTTP ERROR 404
```
but on server it is good
`https://www.domain.com/PF.Base/file/pic/photo/2018/08/1626a8ff560a9f914516a352fe068217_1024.png`

**Comment by spirogg** [comment]
i believe this is on blogs too an issue
