### ISSUE TITLE
Admin Can no longer edit comment when posting on friends wall

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2341]
Admin Can no longer edit comment when posting on friends wall

**Comment by harrison05** [comment]
Can you explain more about this issue? Please follow our **Issue Template**

Regards.

**Comment by spirogg** [comment]
@prepperz @Harrison05 

 i use fresh instal 4.6.1b5 you have to go to members >> user group settings>> 

select 
Apps: comments 
and 
Groups: registered user 

and you will see very first option : 
Can edit their own comments click to  **YES** 
clear cache and it should work

![edit there own comments app comments user registered user](https://user-images.githubusercontent.com/17736688/43755607-4799a75e-99d6-11e8-9ef3-035813ea536f.PNG)


![edit comments](https://user-images.githubusercontent.com/17736688/43755577-27e87390-99d6-11e8-9ed1-f219c83be729.PNG)

**Comment by prepperz** [comment]
Thanks Spirogg, but it seems the admin cannot edit there own comment. Go to a friends profile and then make a comment on their wall. Then try to edit that comment. Only option presented is delete.

**Comment by spirogg** [comment]
@prepperz do the same option in the photos except change user:  to administrator. Mine works. I can edit comment as admin. :)

**Comment by spirogg** [comment]
![screenshot_20180807-140722](https://user-images.githubusercontent.com/17736688/43796963-6b24184c-9a4b-11e8-80b2-1f7be9b461d2.png)
![screenshot_20180807-140732](https://user-images.githubusercontent.com/17736688/43796964-6b3e0644-9a4b-11e8-99a7-c5bd86856367.png)

**Comment by prepperz** [comment]
OK seems I  had to clear the cache.
