### ISSUE TITLE
when sponor or unsponsor  you have to click X after. to go away, but all others goes away after few seconds

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2343]
----------------------------------------

## What happened?
...
when sponsor or unsponsor in Music, Marketplace,Forums you have to click X after...
 all others apps so far I test  goes away by itself after few seconds
## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b5

## Screenshots
...
![sponosr](https://user-images.githubusercontent.com/17736688/43751515-c70cf748-99c2-11e8-99e2-bdaa13d618a1.PNG)
![unsponsor](https://user-images.githubusercontent.com/17736688/43751516-c71c68f4-99c2-11e8-8142-1294fe4d0cc6.PNG)

**Comment by spirogg** [comment]
polls also you have to click X to make it go away (popup)

![poll unsponsor](https://user-images.githubusercontent.com/17736688/43751756-cdfbb9d0-99c3-11e8-8e43-946c4c4e3f6e.PNG)
![polls sponosr](https://user-images.githubusercontent.com/17736688/43751757-ce0e7fe8-99c3-11e8-863a-8f2562eceec6.PNG)

**Comment by spirogg** [comment]
quiz also 

![quiz sponsor](https://user-images.githubusercontent.com/17736688/43751832-2cc1a3d0-99c4-11e8-90d8-942b48f7611b.PNG)
![quiz unsponsor](https://user-images.githubusercontent.com/17736688/43751833-2cd10906-99c4-11e8-8867-c9c72bd03ece.PNG)

**Comment by spirogg** [comment]
event also 

![event sponsor](https://user-images.githubusercontent.com/17736688/43752045-1a79d5c0-99c5-11e8-8338-d2f28880bfd8.PNG)
![event unsponsor](https://user-images.githubusercontent.com/17736688/43752046-1a8af576-99c5-11e8-9766-4f6bbd99d169.PNG)

**Comment by neil96** [comment]
Thanks @spirogg ,

We will discuss with team to unify this behavior.

Regards.

**Comment by david-phpFox** [comment]
We will fix in Events 4.7.1, Polls 4.7.1, Quizzes 4.7.1
