### ISSUE TITLE
when sponsor or feature in pages where is the blocks (Sponsor) (Feature) ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2344]
----------------------------------------

## What happened?
... when we sponsor a photo in pages I do not see any blocks for Sponsor OR Feature ?

where are these blocks suppose to appear ?? 

## Steps to reproduce:
1. create a page, then click photos add a photo and then sponsor and feature that photo
2. now look for the block sponsor and feature ??? no where can I find it
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/43752409-73fbb9aa-99c6-11e8-9a96-7cdc937c754b.PNG)

**Comment by spirogg** [comment]
same issue for sponsor and feature blogs in pages 
i think this will be the same thing for all pages - Blogs, Events, Forums-events, etc etc 
feature and sponsor no blocks show

![capture](https://user-images.githubusercontent.com/17736688/43752541-1a856c80-99c7-11e8-89ba-d9dc5ef83350.PNG)

**Comment by neil96** [comment]
Hi @spirogg ,

We do not support this block in Pages/Groups.

Regards.

**Comment by spirogg** [comment]
Feature request possibly ?

**Comment by neil96** [comment]
Yes possible.
