### ISSUE TITLE
why in photos we need to clear cache everytime to see change in photo app sponsor and feature?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2346]
----------------------------------------

## What happened?
... when adding a photo to sponsor or feature, we have to clear cache in admincp in order for it to start showing ? if user pays to sponsor a photo we will have to clear cache in order for them to see change? 
can you make this not cache so change is automatic ? in sponsor block and feature block for photos and im sure every other app that you can sponsor and feature ?

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...
4.6.1.b5
## Screenshots
...

**Comment by harrison05** [comment]
"can you make this not cache so change is automatic ?" Yes, we did it from the older version. Featured and Sponsored blocks have some settings in AdminCP which support you do that, at **AdminCP > Appearance > Blocks** 

![screen shot 2018-08-08 at 10 10 40](https://user-images.githubusercontent.com/41947198/43814641-94629f44-9af5-11e8-96d4-9eb606658e69.png)
![screen shot 2018-08-08 at 10 21 30](https://user-images.githubusercontent.com/41947198/43814642-95f9ba86-9af5-11e8-90b0-8804137751e3.png)

Regards.

**Comment by spirogg** [comment]
@Harrison05 Thanks I got it now... thanks for this @neil96 also for making this a feature in blocks, really awesome!!!!
