### ISSUE TITLE
when sponsor a forum thread and you click on it says: forum_thread is not a valid module.

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2347]
----------------------------------------

## What happened?
...
  I create a forum thread and then sponsor that thread, when I click on the sponsor block of that thread I get error message : forum_thread is not a valid module.   i try as registered user and admin does it for both
## Steps to reproduce:
1. create thread in forums, now sponsor thread, 
2. now click forums menu link again and see sponsored block with your thread
3. now click on thread you sponsor and it takes you to page that says forum_thread is not a valid module.

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5 fresh install
...

## Screenshots
...
![forum sponsor thread](https://user-images.githubusercontent.com/17736688/43761294-4e77655c-99ea-11e8-8fcc-6bb86cc30005.PNG)

**Comment by harrison05** [comment]
This is a bug, we will check and fix it.

Thanks for your report.

**Comment by spirogg** [comment]
@harrison05 @neil96 this is probably related #2353

**Comment by harrison05** [comment]
@spirogg We fixed this issue on Better Ads v4.2.3.
