### ISSUE TITLE
can you realign the top of page icon in photo swatch

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2349]
when you view photos the next button and top of page icon button are too close to each other can you realign it

----------------------------------------

## What happened?
...

## Steps to reproduce:
1. go to photos scroll down see photo swatch the icon to go to top of page is in the way of next buttom
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
your demo
...

## Screenshots
...
![realign page up icon in photo swatch](https://user-images.githubusercontent.com/17736688/43805056-edcbae78-9a63-11e8-8838-73b39301ea26.PNG)

**Comment by harrison05** [comment]
@spirogg We fixed this issue on Photo v4.6.4
