### ISSUE TITLE
Users cannot be added as Page admin if they change their name

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2350]
Page admin: cannot add certain users to page admin. The user show up on the invite search, but not on the admin add search.

**Comment by spirogg** [comment]
@prepperz can you take a snap shot to show what issue is. Or how to get to the issue ?

**Comment by spirogg** [comment]
On my test site fresh install 4.6.1.b5 it works. 

The only weird thing is.

 When admin set registered user Michelle for administrator privilege, she now can add Admin as administrator again. Even though admin is founder and administrator already. 

See photos. 
![screenshot_20180808-022606](https://user-images.githubusercontent.com/17736688/43822809-daca3ee4-9ab2-11e8-8256-e9b273775d31.png)

**Comment by spirogg** [comment]
Should not allow someone else to add Admin again. 
- it should say Admin - already has administrator privilege.

**Comment by spirogg** [comment]
@prepperz maybe there is a limit on how many administrators are allowed ??

**Comment by spirogg** [comment]
Or maybe they have to have joined the page in order to be admins. ??

**Comment by prepperz** [comment]
@spirogg Yes I thought about that. It seems even whether they join / like the page doesnt seem to matter. It's like a hit or miss. Some users you can add as an admin just fine and some doesn't come up at all in the search to add as admin. I don't know what phpfox fox parameters are. At this point I'm just scratching my head. They are already friends and already like the page and there are only two page admins so I don't see why it would be a problem when other pages have 4-5 or more admins.

**Comment by prepperz** [comment]
Ok, I figured out why this is an issue and titled it appropriately.  When they leave their "state/province" blank, they won't show up in the search for admin adds for pages or groups.

**Comment by harrison05** [comment]
@prepperz Can you explain more about your issue? Where they leave their "state/province"? Because I can't reproduce it even though I leave this field blank at "Edit profile page".

**Comment by prepperz** [comment]
@harrison05 try this. sign in with 2 different account. 

1. On account B, go to the pages manager for a particular page.
now on the invite link. type in the name of account A. Now goto Admin link and type in name of account A. They both show.

2.  Now for account A. Goto account setting and the change the name of account A to something else. Like, "InVIisible" or something.

3. repeat step 1 with the new name.

**Comment by david-phpFox** [comment]
Will fix in Core 4.7.2
