### ISSUE TITLE
Page invites does not check if invited user has already joined/like page

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2351]
In page invite, it allow a user to be invited an indefinite number of times even they already join.

**Comment by spirogg** [comment]
same for making administrator to pages another user can make an administrator even though they are already admins for pages

**Comment by harrison05** [comment]
@prepperz 
We can't reproduce this issue.  Could you give us more step to reproduce? 
See my attachment, admin can't invite people who liked that page.

![screen shot 2018-08-09 at 11 19 26](https://user-images.githubusercontent.com/41947198/43877820-1f9d3ecc-9bc6-11e8-868c-e2fd592c1298.png)

Thanks!

**Comment by harrison05** [comment]
@spirogg Can you create another issue on GitHub for your case? Thank you.

**Comment by prepperz** [comment]
to reproduce

1. Go to page. then click on manage page.
2. invite a user. User then likes page.
3. Can still invite same user....
