### ISSUE TITLE
 Manage Sponsorships dates search not working right for events maybe all apps

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2352]
----------------------------------------

## What happened?
...

Date from 8/7/2018 Date to 8/7/2018

Date from 8/8/2018 Date to 8/8/2018

is the same for events see photos

## Steps to reproduce:
1. go to Manage Sponsorships select dates yesterday and then submit look at events sponsored views  then try change date to today and submit then look at views is same number as yesterday even though you click on these events today 
2. 
3. 

## What is expected?
... should only show count of views and click for the dates selected. maybe all apps views and counts not working right when search by dates

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5 phpfox script and 4.2.2 better ads app
...

## Screenshots
...
![sponsored ads date](https://user-images.githubusercontent.com/17736688/43857648-940e48a6-9b11-11e8-9e86-32397612a04f.JPG)
![sponsored dates](https://user-images.githubusercontent.com/17736688/43857650-94468b08-9b11-11e8-9e54-d50be1d59264.JPG)

**Comment by spirogg** [comment]
When do you expect for better ads to be fixed. It affects alot of apps and doesn't work. Plus people can't pay for ads space ??

**Comment by harrison05** [comment]
@spirogg We fixed this issue on Better Ads v4.2.3.
