### ISSUE TITLE
sponsor forum thread block has no sponsor icon

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2354]
the sponsor block has no sponsor Icon in forums
----------------------------------------

## What happened?
...

 **see photo please** 

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots
...
![sponsored forum has no sponsor icon](https://user-images.githubusercontent.com/17736688/43860167-75ea6ba0-9b18-11e8-8a3f-d4edf5a77b18.JPG)

**Comment by harrison05** [comment]
We fixed in Forums v4.6.1
