### ISSUE TITLE
when setup smtp for mail I add password and save then clear cache and password dont save

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2355]
----------------------------------------

## What happened?
...
 hi if i add a password in admincp>> mail setting
I save it, then test email and it sends. now i go to clear cache and go back to admincp >> mail settings and try to test email again and it fails ? password seems not to save or something else doesn't save
## Steps to reproduce:

1. go to admincp >> settings >> Mail Server> select SMTP for mail

2. add your smtp details and email password etc etc then save.. then add a email address  to test.. then save then click on TEST to send email.. it sends ok

3. now go to admincp >> maintenance >> cache manager >> click on clear cache

4. now go back to admincp >> settings >> Mail Server

5. now click on TEST again and it will fail sending email ??

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots
...
- Here it send before clear cache 

![email sent before clear cache](https://user-images.githubusercontent.com/17736688/43861578-e3c4b776-9b1c-11e8-90ab-9fc8e50353e1.JPG)

- Here it Fails to send after clear cache 

![email cant send](https://user-images.githubusercontent.com/17736688/43861607-fd08cee8-9b1c-11e8-9f8f-6f3eaf7ffff3.JPG)

**Comment by spirogg** [comment]
I'm wondering why does emails still get delivered when someone likes or comments ? 
- Does it default to mail if smtp fails ?? 

Because email is not signed as TLS or SSL when I view sender security in Gmail. ?

**Comment by spirogg** [comment]
ok I think this is other cpanel plugin issue that ruins my SSL settings in admincp including email

please keep open for me to test again with differnt options : I turned ON and OFF if its cpanel plugin I will close this ticket myself sorry

**Comment by Elshara** [comment]
Try clearing cpanel cache. Experienced same issue.
