### ISSUE TITLE
clicks in events dont show up in Manage Sponsorships

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2356]
----------------------------------------

## What happened?
...    click dont work in Manage Sponsorships 

i click on my events that I sponsor and the clicks dont show they show 0 

## Steps to reproduce:
1. create an event sponsor it and then login as another user and click on the event you spnosred in events - sponsored block. 
2. now go to advertise >> Manage Sponsorships >> look for your event name you sponsored and look in column under Clicks.. it will show 0  
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

... 4.6.1.b5 phpfox script and better ads 4.2.2

## Screenshots
...
![event sponsor click incorrect](https://user-images.githubusercontent.com/17736688/43877861-b775cecc-9b61-11e8-86f0-6bed9989b972.PNG)

**Comment by spirogg** [comment]
Maybe this is also related to other bugs in better ads ?? Once you can fix better ads bugs. I can download again and test more. Maybe some other bugs might be related like the forums sponsor link so at this point should I keep testing or wait for better ads to be fixed ??

**Comment by harrison05** [comment]
You are the owner of that sponsor, so when you click on sponsor link, it doesn't count up total click. Please try with another account, and click on sponsor block.
Note: we also found a bug on block sponsor of Event App, sponsor link isn't correct, so we will fix it on Event. You can test your case in other apps.

**Comment by harrison05** [comment]
We fixed it on Event 4.6.2
