### ISSUE TITLE
Giving administrator privileges for pages you can add 2 same users with admin privileges

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2357]
----------------------------------------

## What happened?
...

The only weird thing is.

When admin set registered user Michelle for administrator privilege, she now can add Admin as administrator again. Even though admin is founder and administrator already.

## Steps to reproduce:
1. Ok create a page. As admin. Now go to page and add user1 as admin privilege. 
2. Now login as user1 and give admin adminstrative privilege. 
3. You will see admin is showing as admin for that page 2 times. 

## What is expected?
... Should not allow double admins of same user or admin 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

... 4.6.1.b5 

## Screenshots
...

**Comment by spirogg** [comment]
@harrison05 @neil96

On my test site fresh install 4.6.1.b5 

When admin set registered user Michelle for administrator privilege, she now can add Admin as administrator again. Even though admin is founder and administrator already.

**- See photos.** 
![screenshot_20180808-022606](https://user-images.githubusercontent.com/17736688/43822809-daca3ee4-9ab2-11e8-8256-e9b273775d31.png)


- 
- Should not allow someone else to add Admin again or any user again.

- **it should say Admin or (user-name) is already an administrator for this page.**

**Comment by harrison05** [comment]
@spirogg We fixed this issue on Pages/Groups v4.6.2
