### ISSUE TITLE
Under Invite for groups the texbox "Add a Personal Message" and text disappear after typing.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#2358]
This occurs on your demo version as well as my site 4.61.5 where you go to groups and manage a group. You click on Invite and type something in the "Add a Personal Message" the textbox and text disappear after you start typing.

**Comment by PhpFoxJohnJr** [comment]
Change the title to the second issue because maybe I already sent an invite and that is why it didn't show because when I added a new user and sent invite it seemed to work.  I also uninstall groups at the same time and reinstalled it so maybe that did it too...don't know which one fixed that issue.  The "Add a Personal Message" still disappears though so that is the only bug left.

**Comment by harrison05** [comment]
We can't reproduce this issue on our demo site, take a look on my screenshot

![screen shot 2018-08-14 at 09 44 06](https://user-images.githubusercontent.com/41947198/44068958-d56aabd4-9fa6-11e8-8b7a-daa0d49e5817.png)

Regards.

**Comment by PhpFoxJohnJr** [comment]
Just found out it does work on IE but not on Firefox or Chrome. The box disappears and font...because font is set to transparent.

![image](https://user-images.githubusercontent.com/14913734/44071556-775a4d30-9f4f-11e8-8547-101117f48e06.png)

**Comment by PhpFoxJohnJr** [comment]
Figured it out....Grammarly  now injects css is wrong...so it is not an issue with PhpFox.

![image](https://user-images.githubusercontent.com/14913734/44300673-9dd9e400-a2d0-11e8-9505-e502db4a1d0f.png)
