### ISSUE TITLE
Posting a commenting is slow to other users and pages 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2359]
----------------------------------------

## What happened?
...  If you are admin and post something in main site. And you have reply available to admin. It's really fast to post and comment. 

But after you post and comment. And login as other user. Reply to that post and comment on that post or comment and see it's a lot slower. 

Same when posting and comment on a page. 

## Steps to reproduce:
1. Post as admin and reply as admin 
2. See how fast it shows up. 
3. Then login as another user and reply to that post. See how much slower it is to show up. Why is this. ??

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...php7.2

## phpFox version
(Example: phpFox 4.6.0)

...
4.6.1.b5 fresh install 
## Screenshots

PLEASE READ THE COMMENTS AND REPLIES IN THE PHOTOS TO UNDERSTAND.
...
![slow](https://user-images.githubusercontent.com/17736688/43983984-3fde034e-9cc3-11e8-919d-080040673bcc.PNG)
![slower](https://user-images.githubusercontent.com/17736688/43983985-3fedac68-9cc3-11e8-9142-6f38678bd0ad.PNG)
![i comment again after another user and is slow again](https://user-images.githubusercontent.com/17736688/43983987-439f191e-9cc3-11e8-82e9-fdff4569d629.PNG)

**Comment by spirogg** [comment]
So if I begin the post and no one comments except for me, its super fast to show up
but as soon as another user comments or replies and I as admin comment again it takes longer to show up or if i reply to there comment is slower to show up

**Comment by spirogg** [comment]
also when I post in a page as admin or as page its fast even when I comment or reply on my own posts.

but as soon as another user starts to comment or reply then its slow for everyone to comment or reply to post.. slows it down and takes longer to show up
why is that ?


also when posting as another user in pages that is not admin it still slow to post

- please read the comments to understand

![pages commnet as other user slow](https://user-images.githubusercontent.com/17736688/43984258-097253c6-9cc5-11e8-8fc1-cca20d073698.PNG)

**Comment by spirogg** [comment]
ok there is 2 different scenarios i could think of.. if smtp email password is incorrect or not saving properly and also phpversion 7.2 

i am trying to figure out which one is the issue. im still testing.. 
iam using php7.1 now and seems normal everything you post comment or eply as admin and as user seems fast (same speed to showup)  before I was using php7.2 and it did that.
if its not php issue then its 

Settings >> Mail >> SMTP passowrd not saving after clearing cache.

if you have smtp setup to test this add all smtp details save changes > send test email> then go clear cache and then try to post comment as admin and user to see if this slows down the other user.

if not smtp then try php7.2 and see after clear cache in admincp and try again to post comment with admin and other user and see if it slows down for one user more than the other

**Comment by spirogg** [comment]
ok to me seems like its issue with php7.2 

seems to work normal with php7.1

**Comment by spirogg** [comment]
Any reason why this could be with php7.2 ?

**Comment by harrison05** [comment]
Your comment slows down because the system needs time to send email to users who just commented before on your post, I don't think it related to PHP version. 
So, we have a solution for your case: 
Enable the setting **"Email Queue"** (_Enable this to use Queue for sending email. It will help you prevent the overloading on the mail server. Please make sure that Cronjob has been set up to use this feature_)

Regards.
