### ISSUE TITLE
@harrison05 please read again Site stats not working correctly, its a bug

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2362]
----------------------------------------

## What happened?
... OK this is the ISSUE the initial profile photo and cover photo and timeline photo creates an album, if you delete all photos in timeline and delete your profile photo and cover photo the initial album doesn't get removed from database - stats.
when you add another profile pic or cover photo or timeline photos it doesn't show as another album. only the first initial album that was created for profile photo, cover photo and timeline photos album stays in database - stats
## Steps to reproduce:
1. Go to feed create a feed comment in feed reply to that comment.
Now view how many comments.
Should be 2 comments.
If you delete each comment then it works. If you delete the feed itself then it will still show 2 comments. So by deleting the feed the comments never get deleted

## What is expected?
...  - stats for comments should get minus when you delete a feed post
- also Status Updates:
 should be minus when you delete in feed.
- Read more below

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome, edge
## Server information
(Example: CentOS 7, php 7.1 apache)

...Centos 7 php7.1

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b5
...

## Screenshots

your demo site v4.phpfox.com

... - here i create a post has only 2 comments in stats for the day

![post n comment](https://user-images.githubusercontent.com/17736688/44295920-c6ce8a80-a278-11e8-97fd-9766dadae2f6.JPG)

- here i comment on my post - look at stats for the day in comments it show 3 now.

![site stats show 3](https://user-images.githubusercontent.com/17736688/44295922-cafaa800-a278-11e8-9f64-25e9fa4c6fef.JPG)

- Now i delete the post and still it shows 3 in stats for comments for today 
- this shows the count for stats is not working correct
![deleted feed first stats show 3 still](https://user-images.githubusercontent.com/17736688/44295923-cd5d0200-a278-11e8-86b8-08e595cd5273.JPG)

**Comment by spirogg** [comment]
- i have nothing no photos no comments no profile pics no pages music groups etc.. its all been deleted



![capture](https://user-images.githubusercontent.com/17736688/44182385-5edb4100-a0cc-11e8-9cbe-55798bb178ec.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/44182386-5edb4100-a0cc-11e8-9a9d-f295ccd16910.JPG)
![capture2](https://user-images.githubusercontent.com/17736688/44182387-5edb4100-a0cc-11e8-8ecc-ad7d33f613f8.JPG)
![capture3](https://user-images.githubusercontent.com/17736688/44182388-5f73d780-a0cc-11e8-9bfb-df5686bde36d.JPG)
![capture4](https://user-images.githubusercontent.com/17736688/44182398-6864a900-a0cc-11e8-9329-2de6ffacd6f1.JPG)
![capture5](https://user-images.githubusercontent.com/17736688/44182399-6864a900-a0cc-11e8-8968-8f79c502eb3b.JPG)
![capture6](https://user-images.githubusercontent.com/17736688/44182400-6864a900-a0cc-11e8-97fc-247a85ef18fa.JPG)
![capture7](https://user-images.githubusercontent.com/17736688/44182401-6864a900-a0cc-11e8-84e8-ce7a19571226.JPG)

**Comment by spirogg** [comment]
I've cleared Cache
 Reparser
Remove files no longer used
Counters
Rebuild Core theme
Clear all Cache

Still issue, I do not use anything cache except for file cache

**Comment by harrison05** [comment]
We can't reproduce this issue on our side. Site statistics are counting real-time from the database. 
Can you check your database in case some items still save on it but don't show on your site?
Example: check table <db_prefix>_photo and count total record on it...

Regards

**Comment by spirogg** [comment]
Just to confirm. 
- If you comment in a feed and just delete the feed the comments never get deleted. 
- if you delete the actual comment in a feed then it gets deleted.
- so this is not working right. You should be able to delete the whole feed and if there are comments in that feed they should get deleted also.

**Comment by spirogg** [comment]
Also when you add your cover photo and profile pic. It become a photo album. 
So now you go to photos>>photo album

Then delete the photo album photos so your cover and your profile. You delete it. Then view stats. Still shows 2 photo albums. It should say 0 not 2

**Comment by spirogg** [comment]
Status updates don't get removed after you delete them in feed also. 
If I update my status and then I delete it. It should go to 0 but I have nothing on my site in feeds or nothing at all on website and it still shows 6 for status updates.

**Comment by spirogg** [comment]
When I go to admin reparser 
I see blog text: run records 3
And 
Comment text: run records 7 

But I have no blogs and no comments. ?? When I click on them they stay the same.

**Comment by spirogg** [comment]
- Question ? 
what is the purpose of counters. 
I clicked on all of them to see if it would clear the stats and correct them to what is actually on my site and make the stat numbers to : 0 since I have 0 photos 0 albums 0 comments etc etc. But it's still shows I have comments photo albums etc. 
- So does the counter in admincp actually work ?? 
Please check

**Comment by spirogg** [comment]
@harrison05 
- Photo album is created when you upload a cover photo and a profile pic.

- when you go to photos >> my album - then click on the little gear 
it only allows you to update photo album ?
 it doesn't give you option to delete photo album?
- the only way that album goes away is you need to click update and delete photo. 
but that doesn't delete from stats photo album....
- so I'm thinking that's why it never deletes from stats.

# EDIT:: 
- OK this is the ISSUE the initial profile photo and cover photo and timeline photo creates an album, if you delete all photos in timeline and delete your profile photo and cover photo the initial album doesn't get removed from database - stats.  

when you add another profile pic or cover photo or timeline photos it doesn't show as another album. only the first initial album that was created for profile photo, cover photo and timeline photos album stays in database - stats

**Comment by harrison05** [comment]
Checked your issues on our side and found 2 issue as your description:
- Comments don't get removed after deleting feed item
- Status updates don't get removed after deleting its feed
The counters in AdminCP still working but it has issues like block Site Statistics in front-end. 

Thanks for your report. We will check and fix that.

Regards.
