### ISSUE TITLE
Unable to add newly created custom block file to User Profile (profile.index)

### ISSUE THREAD

**Issue by mohsinadeel** [PHPfox-Official/phpfox-v4-issues#2363]
## What happened?
I have created a new APP with a php block file and added it to APP's start.php too i.e.
`$module->addComponentNames('block', [
        'abc.display' => Block\Display::class,
        'abc.promo' => Block\Promo::class,
    ]);`

## Steps to reproduce:
1. Now when I want to add this block using Appearance -> Block -> Add New Block. No errors shown.
2. Newly added block does not appears

## What is expected?
Newly added block on User Profile Index page

## Server information
php 7.1 apache

## phpFox version
phpFox 4.6.0

## Screenshots

![screenshot_2018-08-16 admin cp block manager add new block](https://user-images.githubusercontent.com/16169522/44213635-90651280-a187-11e8-8146-b67f64a11335.png)
![screenshot_2018-08-16 admin cp block manager](https://user-images.githubusercontent.com/16169522/44213781-f05bb900-a187-11e8-8857-78be714552d4.png)

**Comment by harrison05** [comment]
Did you try to add your block to other pages (Ex: home page, music, photo...) to check its work or not? Besides that, can I take a look at the source code of it?

Or you can try add this block into function **setComponentBlock()** on file  **Install.php** of your app, like that:
```php
protected function setComponentBlock()
{
      $this->component_block = [
          'Latest Songs' => [
                'type_id'       => '0',
                'm_connection'  => 'profile.index',
                'component'     => 'song', //You should init this component name to function **setComponent**
                'location'      => '3',
                'is_active'     => '1',
                'ordering'      => '2',
            ],
     ];
}
```

Regards.

**Comment by mohsinadeel** [comment]
Yes I have tried on other page and its showing i.e on Profile Info page.
Let me give try to setComponentBlock and update you in a while.

Thanks @harrison05

**Comment by mohsinadeel** [comment]
Hi @harrison05 , I have tried to apply the above code inside setComponentBlock() but it did not work out for me.

**Comment by mohsinadeel** [comment]
Thanks @harrison05 . It was cache issue, the clear cache button was not actually clearing the cache. so have to manually delete the cache folder
