### ISSUE TITLE
Modified files after a fresh installation 4.6.1б5

### ISSUE THREAD

**Issue by kaligula7** [PHPfox-Official/phpfox-v4-issues#2364]
# Important!

Please follow this template!

----------------------------------------

## What happened?
121 Modified files after a  fresh installation 4.6.1б5

## Steps to reproduce:
1. fresh installation
2. ACP - Maintenance - Check Modified Files (/index.php/admincp/checksum/modified/)
3. 121 Modified files

## What is expected?
...

## Browsers and Devices tested
 Windown 7, Firefox 

## Server information
Example: CentOS 7, php 7.2.8 apache FCGI

...

## phpFox version
 phpFox 4.6.1B5

...

## Screenshots
...

**Comment by spirogg** [comment]
duplicate of #2198
