### ISSUE TITLE
Clicking back button on photos results in changed menu on main feed.

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2365]
# Important!

Please follow this template!

----------------------------------------

## What happened?
Clicking back button on photos results in changed menu on main feed.

## Steps to reproduce:
1. Scroll down main feed to a photo
2. Click on photo
3. Hover over photo to show back button and click it
4. You are return to the photo on main feed

## What is expected?
Menu has changed

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

phpFox Demo

## Screenshots
Scroll down main feed to a photo. Note menu title is "Home". Click on photo.
![photoback1](https://user-images.githubusercontent.com/17064302/44434319-6dc96400-a5a2-11e8-95de-b7a02d5e0b94.jpg)

Hover over photo to show back button. Click back button.
![photoback2](https://user-images.githubusercontent.com/17064302/44434332-7a4dbc80-a5a2-11e8-8872-30d8dafaa0ea.jpg)

You are returned to the photo on main feed. Note menu title has changed to "Photo".
![photoback3](https://user-images.githubusercontent.com/17064302/44434347-8174ca80-a5a2-11e8-95ee-6e8824bf8d56.jpg)

**Comment by spirogg** [comment]
this too #2290
