### ISSUE TITLE
Sign in block on visitors page bootstrap template isn't completely showing android mobile view; chrome browser. 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2368]
----------------------------------------

## What happened?
... I am using boostrap template. I have set to no one can sign up to website, just login and the sign in block is not completely visible. I do not see the sign in button - it's too small of a block 

see photo in mobile view. 

## Steps to reproduce:
1. Set website to no one can sign up. and Block for featured member on home page is active. 
2. now Log out and view visitors page. (main page with mobile (cellphone) www.yoursite(dot)com
3. You will see the sign in block shows email little but of password section but no signin button - it is too small of an area (block)

## What is expected?
... should show full block of sign in form.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
Mobile chrome.browser Android. 
## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b6
...

## Screenshots
...
![screenshot_20180823-010124](https://user-images.githubusercontent.com/17736688/44507641-e39c0100-a670-11e8-95a3-732769524ce1.png)

**Comment by spirogg** [comment]
Also doesn't allow to scroll down or up when trying to scroll in mobile view when you add your email and password to scroll to click in sign in (login) button.

**Comment by harrison05** [comment]
We improved visitor page in the newest version 4.7.1. You can check in this version
