### ISSUE TITLE
Message notification stays up forever if unread message is archived

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2369]
Message notification stays up forever if unread message is archived.

Also there is no option to retrieve or delete archive

**Comment by harrison05** [comment]
I reproduce this issue, notification count number stays up when archived an unread message, but when refresh page, it's gone. Does it look like your case?

**Comment by prepperz** [comment]
yep

**Comment by david-phpFox** [comment]
Fixed in Core Message 4.6.0
