### ISSUE TITLE
template bootstrap and Material : when upload photo in feed first and add comment to photo in feed, cover photo and profile shows twice - double ? see photo

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2370]
I give you access to my server to see for yourself this issue phpfox Ticket # 506287

----------------------------------------

## What happened?
... fresh install first: 

In Feed - upload a photo then comment ( just write "hello there") then go and  upload a profile photo and then go upload a cover photo,

-  now go to home and admin feed pages -  seems to add profile pic and cover photo twice ?
it creates double see photos below.

## Steps to reproduce: fresh install no feeds photos profile pics etc.. sort view in feed is Most Recent.

first steps: 
1. in feed on home page - upload a photo then comment on that photo, then add profile photo, then add cover photo 
2. refresh home page and scroll down see double of profile pic and cover photo in feeds
( home page feed and admin feed while sort is in Most Recent )
3.  if you don't see double of profile pic and cover photo when scroll down or load more... 
4. then on the first photo you uploaded, make a comment again, and then refresh and you will see it doubles the profile pic and cover photo. 

- this is weird.. not sure if it happens in any other combination of adding to feed, but it does in the steps I explain above 1 - 4 and only in this order and on fresh install, while in Most Recent -sort 
( Note: if sort is set to:  Top Stories it doesn't double in feed ) 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome and firefox
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php72

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1b6

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/44567075-6aff7800-a736-11e8-9970-c689f0970163.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/44567076-6aff7800-a736-11e8-93a2-3dec0a866c00.JPG)

- In this photo profile pic - cover photo and a reg photo doubles ??

![capture](https://user-images.githubusercontent.com/17736688/44567135-a732d880-a736-11e8-8b94-f025a78f8299.JPG)

- Material Theme also
if you need to see it I have 2 sites one material theme and one bootstrap theme, its saved like this for you to view if you cannot reproduce it - I will add a ticket with my info to website and dev site for you to look into. (**phpfox Ticket # 506287**)

![capture](https://user-images.githubusercontent.com/17736688/44567606-cd597800-a738-11e8-9d5f-b32314b8462c.JPG)

**Comment by spirogg** [comment]
seems if its on Most Recent then it doubles in feed

- If I Change sort to Top Stories then its good that is in main feed (Home)

- on Admin Feed it always does it since there is no sort option there

![capture4](https://user-images.githubusercontent.com/17736688/44568689-7d30e480-a73d-11e8-9fb6-006ec74dfdfb.JPG)
![capture3](https://user-images.githubusercontent.com/17736688/44568747-ab162900-a73d-11e8-9553-f1bfc9019e78.JPG)

**Comment by harrison05** [comment]
Hi @spirogg, I can reproduce your issue with step 1 to 4.

Thanks for your report.
