### ISSUE TITLE
Too many issues! Look att eh lies https://www.phpfox.com/ 

### ISSUE THREAD

**Issue by VlogMe** [PHPfox-Official/phpfox-v4-issues#2374]
Look at the lies! Look at the lies https://www.phpfox.com/ DON'T TAKE IT!

**Comment by spirogg** [comment]
@VlogMe seems you cant spell #2373

> Too many issues! Look att eh lies

**Comment by Elshara** [comment]
Works fine for me regarding most script functionality over here. Not
lying about that. Lol.

**Comment by harrison05** [comment]
Duplicate of #2373
