### ISSUE TITLE
featured member block users pics in visitors landing page not changing for template bootstrap see photo

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2376]
----------------------------------------

## What happened?
...

## Steps to reproduce:
1. when viewing featured member block in landing page using bootstrap theme
2. you login and change your profile pic then log out and mouse over Admin ( user) 
3. you will see 2 different profile pics the featured block on lading page doesn't change to new profile pic

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b6

## Screenshots
...
![featured members block for guest admin profile pic not changing](https://user-images.githubusercontent.com/17736688/44650852-5d075c80-a9ad-11e8-800c-5a332d3a068e.JPG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/44651036-dbfc9500-a9ad-11e8-8594-dfccd5c2b420.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/44651037-dbfc9500-a9ad-11e8-8355-53b956ac0f95.JPG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/44653081-5aa80100-a9b3-11e8-91a8-c4f2e30de153.JPG)

**Comment by spirogg** [comment]
- Also in my demo with bootstrap theme using chrome browser there is another issue.

1) I go to landing page (visitors page) then click on a user in the featured members block.
         (then it take me to that users page. )

2) then I click on the site logo (top left) to go back to landing page (home page).

3) now I try to click on a user again in featured members block with chrome browser and it doesn't allow me to click on any user. 

4) I have to refresh page in order to be able to click on a user again. 
(even if you click on logo again it still doesn't work until you refresh page

something gets stuck ?

**Comment by harrison05** [comment]
Block feature members on landing page shows old user avatar because it gets data from cached. 
This issue is related to https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/710
So we will discuss solution cache time for it and other blocks and inform you later.

P/s: we don't delete cache immediately after user update avatar to prevent slow down our site. 

Regards.

**Comment by david-phpFox** [comment]
Support in Core 4.7.0
