### ISSUE TITLE
Can't install apps: Error: Client not found

### ISSUE THREAD

**Issue by theoplooy** [PHPfox-Official/phpfox-v4-issues#2377]
# Important!

Please follow this template!

----------------------------------------

## What happened?
I tried to install apps from Apps/Find more, I picked the better ads app
I get the error 'client not found'

## Steps to reproduce:
1. Login as admin
2. goto apps
3. goto Find more

## What is expected?
Downloading the app

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
Firefox Quantum 61.0.2

...

## phpFox version
phpFox 4.6.1 Build 6 Release

...

## Screenshots
...
![error](https://user-images.githubusercontent.com/24503584/44773689-7a852380-ab71-11e8-835c-d279f0215ad0.png)

**Comment by spirogg** [comment]
please try again using File system for uploads not ftp or sftp
search in admincp > **file upload method** 
and select>> **file system** in dropdown and click save button at the bottom right

Also make sure you **allow third party cookies in your browser** for allow store to work properly

see photo for settings> then try again
![capture](https://user-images.githubusercontent.com/17736688/44754690-7f51c500-aae8-11e8-8875-6b7b71482393.JPG)

**Comment by spirogg** [comment]
also do you have your lic correct in the script ? 

double check your file permissions also

read: https://docs.phpfox.com/display/FOX4MAN/Installing+phpFox

**Comment by theoplooy** [comment]
Checked license, file permissions and have set ftp upload to file system.
It didn't help, same error...
![error](https://user-images.githubusercontent.com/24503584/44773722-91c41100-ab71-11e8-9b68-d3344b50c032.png)

btw, it's a new install

**Comment by spirogg** [comment]
Do you have your domain setup correctly in phpfox.com client area. 
 Where you add your domain https://either www or non www your domain.com
This is where you get your LIC ID 


Also please choose to allow third party cookies from store.phpfox.com in your browser. 
If this does not help. Maybe you can make a ticket at phpfox.com client area so they can take a look.

**Comment by theoplooy** [comment]
I'm using  https://www.   It has been setup in this way in the client area..

Thanks for all your suggestions..

**Comment by spirogg** [comment]
Why don't tyou try a different browser chrome and see if that works. ?

**Comment by spirogg** [comment]
I use chrome browser allow third party cookies from store.phofox.com and it works all the time.

**Comment by theoplooy** [comment]
Third party cookies were allowed, and explicitly allowing cookies from store.phpfox.com didn't help either.
Disabled my ad blocker, and tried Chrome...
