### ISSUE TITLE
site users cannot upload photos

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2378]
# Important!

Please follow this template!
----------------------------------------
## What happened?
My site users, and me cannot upload photos to the site. 
## Steps to reproduce:
1. go to the photos page
2. upload a photo
3. see error

## What is expected?
Photos do not get uploaded.

## Browsers and Devices tested
google chrome

## Server information
php version 5.6.37
...

## phpFox version
Phpfox 4.6.1 (build 5)
![share photos 22](https://user-images.githubusercontent.com/19263189/44706331-16ba0800-aa56-11e8-94af-b03bb000da98.png)

## Screenshots
...

**Comment by spirogg** [comment]
what version of photos, there is an update to photos app

**Comment by spirogg** [comment]
it works for me 4.6.1.b6 with latest photo app no issues uploading or by drag and drop photos ? do you have another photo app third party ? did you check admincp usergroup > registered user if you allow photo upload or what the MB of photo size you allow ??

**Comment by spirogg** [comment]
check your file permissions

https://docs.phpfox.com/display/FOX4MAN/Installing+phpFox

**Comment by erick260** [comment]
The current photos version i have installed is: 4.6.4 No, i do not have any 3rd party apps for photos. I  idk why my site is not letting anyone upload photos. when ppl goes to upload a photo they will get that error.

**Comment by erick260** [comment]
Yes, the  file permissions seemed to have been the problem. all fixed now...  thanks...

**Comment by spirogg** [comment]
@erick260 I'm glad you got it working :)
