### ISSUE TITLE
Question about Composer do we need composer active ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2379]
----------------------------------------

## What happened?

... just wondering if composer needs to be installed and active for phpfox to work correctly
 here is for cPanel that mentions composer?

https://documentation.cpanel.net/display/CKB/How+to+Set+Up+%28PHP%29+Composer#HowtoSetUp(PHP)Composer-RequiredPHPmodules

maybe if we use cPanel we should follow this so our websites will work correctly ? 
just wondering if this is needed ?

thanks if you can take a look and read the link for a second 
just to see if its needed for any user using cPanel with phpfox ?

thank you Spiro

**Comment by harrison05** [comment]
phpFox doesn't require PHP Composer, because we added all needed libraries to our source.
In the future, if we need it, we will announce in our documents.

Regards.

**Comment by spirogg** [comment]
Thanks.
