### ISSUE TITLE
adding hashtags to forums show in tags but doesn't pull up that forum thread

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2380]
----------------------------------------

## What happened?
...
adding hashtags to forums show in tags but doesn't pull up that forum thread
## Steps to reproduce:
1. go to forums add a thread and add #forum or #hashtag 
2. then go to main feed see in tags block #forum #hashtag 
3. noe click on tags you see no forum thread show

## What is expected?
...
should pull up the thread in forums you added hashtag too
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b6
...

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/44901532-4757a700-accd-11e8-94f0-9901aef28eb6.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/44901533-4757a700-accd-11e8-9987-ef7e1c3a5c4d.JPG)

**Comment by harrison05** [comment]
I can't reproduce your issue (phpFox 4.6.1b6 + Forum 4.6.1)
![screen shot 2018-09-04 at 10 08 28](https://user-images.githubusercontent.com/41947198/45008054-c67d1000-b02a-11e8-9ce2-c28458fe8a42.png)

**Comment by spirogg** [comment]
@harrison05 if we delete the forum post in feed only, but we still have the thread in forums app, 
then the trending hashtags don't work ? should it not go to forum app at this point to show the thread, or is it meant to only show hashtags in feed ?

![capture](https://user-images.githubusercontent.com/17736688/45023704-ba7a5980-affc-11e8-9b28-135a78efe275.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45023786-f3b2c980-affc-11e8-8da3-e52e1ee8d21d.JPG)
![capture2](https://user-images.githubusercontent.com/17736688/45023787-f3b2c980-affc-11e8-9af5-90c09a147d59.JPG)

**Comment by spirogg** [comment]
also when you delete a thread from feed, if you go to forums and view that thread and if it has Hashtags, and someone clicks on the hashtags, it takes you to feed page and says nothing there
