### ISSUE TITLE
Weird folder showing in PF.Base/file/cache need help

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2384]
Weird folders in cache PF.Base/file/cache

----------------------------------------

## What happened?
... When I view the directory of this it has 2 folders I've never seen before. 
page_meta_user.password 
page_meta_user.browse

Im really hoping this is normal and my server is not compromised somehow. ?? 

## Steps to reproduce:
1. ??? Check folders in  PF.Base/file/cache/
2. 
3. 

## What is expected?
...
 ???
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/44966795-f03b1780-af02-11e8-85c8-f78cded1a741.JPG)

![capture1](https://user-images.githubusercontent.com/17736688/44967559-d51ed680-af07-11e8-945d-9e8b87f9fd0b.JPG)
![capture](https://user-images.githubusercontent.com/17736688/44967560-d819c700-af07-11e8-8499-722ca0ae14e9.JPG)

**Comment by spirogg** [comment]
really weird I have no users just myself as admin, no one can signup, that feature is off and i'm the only one who has password to sign in ?  so not sure why this is,  i'm hoping its normal part of script and not a compromise of my site

**Comment by harrison05** [comment]
@spirogg Those cache folders were created to cache HTML content, but they have incorrect name format, we're investigating this case, it really weird, but I'm sure it doesn't compromise your site, no one can get your password via them. You can clear cache and check again.

**Comment by david-phpFox** [comment]
We have updated File-based Caching library.
