### ISSUE TITLE
Sorting events leads to error page

### ISSUE THREAD

**Issue by antoinemayer** [PHPfox-Official/phpfox-v4-issues#2385]
## What happened?
When trying to sort events using any of the dropdown lists ("Location", "Sort", "Show", "When"), Chrome leads me to an "ERR_CONNECTION_REFUSED" page.

It is due to the fact that when clicking one of the sorting options, the URL I'm redirected to starts with "localhost/..." instead of the required "localhost:8888/..." (as shown on the screenshots below).

## Steps to reproduce:
1. Go to "Events" page
2. Open any of the sorting dropdown lists
3. Click any option

## Browsers and Devices tested
Chrome (OS X)

## Server information
Localhost (MAMP)

## phpFox version
phpFox 7.1.0 (if correct)

## Screenshots
Choosing a sorting option:
![screen shot 2018-09-03 at 2 53 46 am](https://user-images.githubusercontent.com/5788761/44962790-4b7e0180-af25-11e8-9003-5c304996338d.png)

Error page:
![screen shot 2018-09-03 at 2 53 57 am](https://user-images.githubusercontent.com/5788761/44962793-56389680-af25-11e8-9228-b7ffbb8fb163.png)

**Comment by antoinemayer** [comment]
It seems to be due to the fact that when clicking one of the sorting options, the URL I'm redirected to starts with "localhost/..." instead of the required "localhost:8888/...".

**Comment by spirogg** [comment]
do you have a license from phpfox ? (nulled version) doesn't seem like its licensed ?

**Comment by antoinemayer** [comment]
no i don't

**Comment by harrison05** [comment]
@antoinemayer This issue appears on Event only or all apps?
