### ISSUE TITLE
hastags in comments don't show up in feed when click on them

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2387]
----------------------------------------

## What happened?
...
   when add a hashtag in comment and it shows as a #hastag but that comment doesn't show up when we click on the hashtag says nothing there ??

## Steps to reproduce:
1. go to a post and comment and add a hashtag in your comment
2. then click on the hashtag in your comment
3. it will go to feed and it shows nothing there

## What is expected?
... #hashtags should work in comments also, since we allow #hastags to show as #hastags in a comment

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...
4.6.1.b6
## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/45027183-4e9cee80-b006-11e8-96d2-181c9232922e.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45027184-4e9cee80-b006-11e8-82fc-d60ce3de434b.JPG)

**Comment by harrison05** [comment]
Currently, we don't support search hashtag on a comment. So, highlight hashtag on comment is useless, we will check and improve it later.

**Comment by harrison05** [comment]
We will remove hashtag in comment from Comment app v4.1.5

Regards.
