### ISSUE TITLE
Question regarding Memory Limit:	0.5 b (-1) in system overview ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2388]
----------------------------------------

## What happened?
...
 Is this normal for it to say 

Memory Limit: | 0.5 b (-1)   in Admincp> Maintenance > System Overview

is it still using the amount of memory I have allocated in php ?
or do I need to adjust something in settings somewhere ?

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

... Cenots php7.2

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b6

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/45061176-fcd98000-b068-11e8-8ecd-888dbcccd6ba.JPG)

**Comment by harrison05** [comment]
This setting = -1 means your site process can use unlimited memory (Use all memory of your service). 

> is it still using the amount of memory I have allocated in php ?

Yes, it is.
