### ISSUE TITLE
Auto detect language for guest

### ISSUE THREAD

**Issue by kaligula7** [PHPfox-Official/phpfox-v4-issues#2390]
# Important!

Please follow this template!

----------------------------------------

## What happened?
There is no automatic recognition of the language.
There is always the standard language EN.
IP InfoDB API Key is installed and working fine.
Additional language German.

## Steps to reproduce:
1. Auto detect language for guest? - ON
2. Clear Cache -ok.
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook,  on Ubuntu 16.04, ...)
Miscrosoft Edge on Windown 10, Firefox
## Server information
(Example: )

...CentOS 7, php 7.1 apache

## phpFox version
(Example: )

...phpFox 4.6.1B6

## Screenshots
...

**Comment by harrison05** [comment]
Can't reproduce this issue on our side. Please make sure you add language package with "Language Abbreviation Code" same with language your guest is using. 
With your case: language German should have Abbreviation Code is: **de** (ISO 639-1 Code)

**Comment by kaligula7** [comment]
Thanks for the answer!
Can you tell me where do I have to check if the abbreviation code is entered?
And what is the abbreviation code for Russian language?

**Comment by harrison05** [comment]
You can check abbreviation for a language at (focus on 639-1 column):
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes 

About abbreviation code on your language package, you can check when  add/edit a language package at: **AdminCP > Globalization > Languages**
