### ISSUE TITLE
when I create an event and post it, I have the option afterwards to comment but it doesn't work right and feed doubles

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2392]
- I am leaving it like that for you to see you have my login in phpfox client area via ticket #506287,
----------------------------------------

## What happened?
...

## Steps to reproduce:
1. ok create an event
2. after your done go to the event you created and **post something**
3. then **post a photo**
4. now **comment on the photo**..
5 now **comment on the post**...
6. comment twice on the photo and post 

- it seems when your commenting on a post or photo and hit enter sometimes it just disappears until you refresh the page or sometimes it doesn't even post and the text is still in the comment field.
 until you refresh the page

## What is expected?
...
should work like main feed when you comment it should show up right away

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php7.29
...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b6

## Screenshots
...
- in the first photo i hit enter 5 times and the text would not disappear from the comment field
![capture](https://user-images.githubusercontent.com/17736688/45135733-99357c80-b166-11e8-8624-960ccd0074ac.JPG)
- after I refreshed it shows all the same posts because i hit enter that many times but still the comment was in the comment field untill i refresh the page
![capture1](https://user-images.githubusercontent.com/17736688/45135734-99357c80-b166-11e8-8c91-51396910bfbc.JPG)

![capture2](https://user-images.githubusercontent.com/17736688/45135735-99357c80-b166-11e8-8cdf-d96a1254c25d.JPG)

- these last 2 photos i was typing in comment then pressed enter
- the text in field disappeared but did not show as a comment until I refresh page

![capture3](https://user-images.githubusercontent.com/17736688/45135736-99357c80-b166-11e8-896c-d7566c38e743.JPG)
![capture5](https://user-images.githubusercontent.com/17736688/45135743-9e92c700-b166-11e8-994e-f58f6a9b0364.JPG)

**Comment by spirogg** [comment]
- Also the feed doubles up with the same photo post and comments twice on same page 
- see my pic here
![capture](https://user-images.githubusercontent.com/17736688/45136299-00ecc700-b169-11e8-9ad7-51673f248583.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45136301-00ecc700-b169-11e8-98b8-fac0a1d5cda7.JPG)

**Comment by spirogg** [comment]
@harrison05 this seems to be ( part of the same issue as this #2370)  but in events and groups feed #2395

**Comment by spirogg** [comment]
_**please login and check my main website**_ **not the dev site** **thats the one i've tested** 

- I am leaving it like that for you to see you have my login in phpfox client area via ticket #506287,

I reopen the ticket if you need to login to see whats the issue

**Comment by harrison05** [comment]
I can't reproduce your issue on my side. About issue #2370, we fixed it in Core and will be released in the next version, it might have root cause like #2392 and #2395.

**Comment by spirogg** [comment]
@harrison05 will close for now and wait for core fix on issue #2370, 

> we fixed it in Core and will be released in the next version, it might have root cause like #2392 and #2395.
