### ISSUE TITLE
groups feed doubles also see photos

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2395]
----------------------------------------

## What happened?
...
 when I added a post with words then added a post with photo only then added some comments in each one the refreshed page and it doubles the post with a photo
## Steps to reproduce:
1. add a post by words in group feed
2. add a photo only in group feed
3. now comment on word feed and photo feed then comment again in word feed then photo feed
4. now refresh page - you wil see photo doubles up top to bottom adds it twice
## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos php7.2

## phpFox version
(Example: phpFox 4.6.0)

... 4.6.1.b6

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/45191943-701af780-b20b-11e8-98f0-2a4aaf0c276c.JPG)

- here is another closer look the same photo feed - First post and Last Post
![capture](https://user-images.githubusercontent.com/17736688/45192269-fc79ea00-b20c-11e8-94eb-9ffa34add32d.JPG)

**Comment by spirogg** [comment]
@harrison05 can you check this for all feeds it might be core issue for all feeds that this does the doubles
this seems to be ( part of the same issue as this #2370) but in events #2392 and this groups feed so far that i've tested

ALSO

_**please login and check my main website**_ **not the dev site** **thats the one i've tested** 

- I am leaving it like that for you to see you have my login in phpfox client area via ticket #506287,

 I reopen the ticket if you need to login to see whats the issue

**Comment by harrison05** [comment]
I can't reproduce your issue on my side. About issue #2370, we fixed it in Core and will be released in the next version, it might have root cause like #2392 and #2395.

**Comment by spirogg** [comment]
@harrison05 will close for now and wait for core fix on issue #2370, 

> we fixed it in Core and will be released in the next version, it might have root cause like #2392 and #2395.
