### ISSUE TITLE
Notification icon not consistently shown

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2396]
On the phpfox forum, the like notificationis not shown until you click on the thread and if you click on the main forum link, the notification disappears again.

Don't if this is just on the phpfox site or site owners as well.

Tested on chrome

**Comment by harrison05** [comment]
Can you explain more about this issue? Please follow our Issue Template (step to reproduce, app version, phpFox version, screenshot...)

Regards.

**Comment by prepperz** [comment]
Steps to reproduce. 
1. Goto the phpfox forum and post an issue.
2.  Someone click "like" on your thread.
3. Click on on the main forum the notification does not show,
4. click on the thread and the notification shows.

**Comment by harrison05** [comment]
I'm trying to reproduce with all your steps, but the issue still disappears. 
Do you mean this notification? Take a look at my screenshot
![screen shot 2018-09-12 at 09 09 25](https://user-images.githubusercontent.com/41947198/45397967-8c37f200-b66c-11e8-9494-b6fbbed9f532.png)

**Comment by prepperz** [comment]
@harrison05 this is on the main phpfox furm. Not the demo

**Comment by harrison05** [comment]
![screen shot 2018-09-14 at 10 42 32](https://user-images.githubusercontent.com/41947198/45528542-f1c1e500-b80a-11e8-8397-8c0c1059aff9.png)
It seems working well on my side.

**Comment by prepperz** [comment]
@harrison05 you still don't get it. It's not on the demo site. it's the phpfox main forum: https://community.phpfox.com/forum/
