### ISSUE TITLE
If we turn off to not allow to create a group or pages  for registered users they cannot manage the group or pages they are admins of ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2397]
----------------------------------------

## What happened?
... this is for Groups and Pages.

> right now If we turn off to not allow to create a group or pages for registered users they cannot manage the group or pages they are admins of ?

@spirogg This is a bug of Groups App. Can you help me create an issue for this in repo 
@harrison05 i've created the repo here thanks so much 🥇 
Thanks.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b6 

## Screenshots
...

**Comment by spirogg** [comment]
**@harrison05 if you need I can create repo for Pages separate ? let me know**

**Comment by harrison05** [comment]
@spirogg Thanks, we will check and fix in both Groups and Pages app, don't need to add more issue.

**Comment by PhpFoxJohnJr** [comment]
So this is fixed?  How?  I do see the group setting..
Can add groups?
but don't see...
Can edit own group?
