### ISSUE TITLE
 in apps> feed > settings > main feed if set to friends only ? you still see everyone in drop down and friends of friends when posting ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2399]
----------------------------------------

## What happened?
...
 when you set as admin in admincp>apps> feed> settings>  to friends only for Main Feed

 **why is there still when posting the drop-down selection for:**
- **Everyone** 
- **Friend of Friends**

- Everyone doesn't work since its friends only in admincp, 

- I would assume Friends of Friends should not work either since its set to friends only

## Steps to reproduce:
1. go to admincp and set app> feed> settings>  to friends only for main feed

![capture](https://user-images.githubusercontent.com/17736688/45335483-3f0d3080-b545-11e8-97e0-db86dd66e969.JPG)

2. then go post and select Everyone, only shows to friends only
3. now go post to friends of friends, still only shows to friends only

## What is expected?
... - Maybe the drop down setting should `hide Everyone and Friends of Friends`, when we set to friends Only in Feed ?

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b6

## Screenshots
...

- Maybe the drop down setting should Hide ( _**Hide Everyone and Friends of Friends**_ ) since we already have feed set to Friends Only, 

- _and just keep_ `Friends - Only Me and Custom`

![capture](https://user-images.githubusercontent.com/17736688/45335546-8693bc80-b545-11e8-994b-23304b9df8e0.JPG)

**Comment by harrison05** [comment]
It sounds reasonable. We will check this case.
