### ISSUE TITLE
creating friends list and added people to friends list not working right

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2400]
----------------------------------------

## What happened?
...

## Steps to reproduce:
1.  added a friends list
2. added 2 people but when adding vivian as friend the user next to her Bruce Wayne was added also ?
3. see photos for how I did this

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windows 10, Firefox on Ubuntu 16.04, ...)

Chrome browser latest version on windows10 
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7.2

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b6

## Screenshots
...

![capture3](https://user-images.githubusercontent.com/17736688/45338289-e55f3300-b551-11e8-8c25-46c64f2e8f0d.JPG)
![capture4](https://user-images.githubusercontent.com/17736688/45338290-e55f3300-b551-11e8-936d-0b20efb337dc.JPG)
![capture5](https://user-images.githubusercontent.com/17736688/45338292-e8f2ba00-b551-11e8-83c4-9f64dddedc0e.JPG)

**Comment by spirogg** [comment]
we need a better way to add users in friends list. this seems so hard to find first off, we should have create list after create list we should have another (+) sign to add users (friends to our list)
when you click (+) it popup your friends and you can select them.

the way you have it now sometimes it works, sometimes it adds someone else (LIKE IN THE PHOTO)
and sometimes it doesn't highlight to add them you have to get out of that screen then go back in to select that user

**Comment by harrison05** [comment]
I can't reproduce your issue on my side ☯️. Btw, If you want to improve this feature, feel free to post a feature request.

**Comment by spirogg** [comment]
@harrison05 https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/728

> I can't reproduce your issue on my side ☯️. Btw, If you want to improve this feature, feel free to post a feature request.

- this was your demo site...

 but  I close this now and hope you guys make fast the feature request ?
- so users can follow the same easy way to add friends - like the rest of the  script = (+) add button to add friends in friend list please
