### ISSUE TITLE
How many activity points should a user receive for ? activity points don't calculate correctly

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2403]
----------------------------------------

## What happened?
... Hi i have all setting for activity point "How many activity points should a user receive" to 1
in my photo it shows 40
but if you count the comments, posts, videos, blogs, etc there is only 36 ? so somewhere its not working to add and subtract correctly

p

## Steps to reproduce:

 FIRST: activate activity points on site.

1. go to admincp usergroup and setup everything to 1 point ( this should already be default in usergroup for apps already) but just in case for test purpose make sure they are all 1 activity point.

2. go add comments. blog. video. forum. etc so it can count activity points.

3. go to admin user page and look at drop down and click on activity points

- see if it is correct.
 if OK go to blog delete, forum delete, comment delete, post delete and (check again)
- see if it counts correct.
(this will let us know if adding and subtracting is really working. 

- on my site not working right see photo

## What is expected?
...
- should add and subtract correctly 

- #2362 is the culprit for activity points for comments

- **BUT ISSUE WITH Invite **:  **we also have issue with events always shows 1 event after delete all events see photos below**

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome 
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.2

## phpFox version
(Example: phpFox 4.6.0)
4.6.1.b6
...

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/45504293-0e98e280-b74f-11e8-957a-635dffa4b8f2.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45504308-148ec380-b74f-11e8-9a33-7fac5f93b95c.JPG)

**Comment by spirogg** [comment]
OK i believe this has to do with **comments,** when **deleting post the comments still stay as activity points.**

- **also I deleted event still shows as 1**
this for sure is not working right.

**Comment by spirogg** [comment]
![capture1](https://user-images.githubusercontent.com/17736688/45506782-e660b200-b755-11e8-9001-3c0cc114249e.JPG)
![capture](https://user-images.githubusercontent.com/17736688/45506783-e82a7580-b755-11e8-90a2-c1980578175d.JPG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/45506861-19a34100-b756-11e8-84af-80e621172dee.JPG)
![capture](https://user-images.githubusercontent.com/17736688/45506892-30e22e80-b756-11e8-9a92-25f484783764.JPG)

**Comment by spirogg** [comment]
@harrison05 

OK I clear cache , remove files not needed , duplicates , clear all cache, and rebuild theme

- still showing comments 
- still showing 1 event

- **PS I added 2 events then it changed to 2 but when i delete both events then it still shows 1 Event**

**Comment by harrison05** [comment]
@spirogg It seems a bug. Besides that, we're working on Activity Point and porting it to an independent app like Music, Photo... So we fixed many bugs of it. 
As our plan, we will release the new Activity Point App in the early October. Keep calm and waiting, my friend. ;)

**Comment by david-phpFox** [comment]
Fixed in Activity Point App 4.7.0
