### ISSUE TITLE
in groups and pages when we upload blog, events, music, photo, video and discussion we have problem with no categories and click on category goes to blank page

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2405]
----------------------------------------

## What happened?
...
-  when we upload to a group or pages one of these blogs, events, music, photo, video discussion and we use the categories, then when we go to any of those blog, events, music, photo, video, discussion there are no categories to the left side to select.

- Also when we add a blog, events, music, photo, video and select a category for each,  we go to view it and in the bottom the category shows and when we click on it, it goes to a blank page ??? see photos

example
## Steps to reproduce:
1. go to a group or pages and add a video music blog event and when you create it, select a category to add it to.
2. now go to groups or pages and see in the listing the category in small letters, (see photos)
3. please click on it and you go to a blank page. also on the left side there should be a block of categories for each app, including discussion (forum) also these should all stay in group or pages app - not change to forum music video blog event forum app etc. this should be separate only viewable in pages and groups

## What is expected?
... all apps in pages and groups should stay in pages and groups always....
- not bounce around to apps outside of groups - pages 
and 
- categories should be viewable in groups and pages under each app blog, events, music, photo, video, and discussions should never leave groups and pages app 
- Because when you click on to create one of these or view one of these pages and groups should be its own entity with these apps ... 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Microsoft Edge on Windows 10, Firefox on Ubuntu 16.04, ...)
chrome latest browser windows 10 pro
## Server information
(Example: CentOS 7, PHP 7.1 apache)

...centos 7 php7.2

## phpFox version
(Example: phpFox 4.6.0)

...4.6.1.b6 latest group and pages app

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/45664025-53b27100-bacf-11e8-8068-573c41eae812.JPG)
![capture1](https://user-images.githubusercontent.com/17736688/45664029-59a85200-bacf-11e8-93fa-b485535ef53b.JPG)
![capture2](https://user-images.githubusercontent.com/17736688/45664031-5c0aac00-bacf-11e8-836b-520cef6bbe5a.JPG)
![capture4](https://user-images.githubusercontent.com/17736688/45664071-96744900-bacf-11e8-9059-4286ee0e14a0.JPG)
![capture5](https://user-images.githubusercontent.com/17736688/45664072-970cdf80-bacf-11e8-90bd-06533e0d8d85.JPG)
![capture](https://user-images.githubusercontent.com/17736688/45664669-ad686a80-bad2-11e8-9e2b-9ec27743158b.JPG)

![capture6](https://user-images.githubusercontent.com/17736688/45664073-970cdf80-bacf-11e8-978f-fc7693a1d3ce.JPG)

**Comment by harrison05** [comment]
@spirogg We just reviewed this issue. As defined, we don't support show any block in block 1 & 3 for Apps in Pages/Groups detail to focus on the list items, so block Categories is hidden. But if you add an item in pages/groups, example: Add a new blog and select a category on pages/groups, you must enable 2 setting (see photo): **Display blogs which created in Group(Page) to Blogs app** to show your blog when filter by this category or search it in main Blogs page. With other apps integrate with pages/groups, we also support 2 settings like that.
![screen shot 2018-09-27 at 11 17 52](https://user-images.githubusercontent.com/41947198/46123234-7d923300-c247-11e8-96ad-173bd5c7c117.png)

**Comment by spirogg** [comment]
@harrison05 

The issue is phpfox says you can create user groups and make subscription to only group or pages. So if you do this it doesn't work as stated. If it's just usedgroup for groups it won't show category to blogs music etc if they click on category will show dead page. Not found. ??

**Comment by spirogg** [comment]
anything on this ?

**Comment by harrison05** [comment]
I'm sorry but our development team confirmed this workflow is applied for all our Core Apps. So, Admin must enable setting to show items posted in Pages/Groups on the main app page (As my above screenshot). We don't have plan to improve this case.

Regards.
