### ISSUE TITLE
New music app add to playlist on mobile device hidden 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2407]
----------------------------------------

## What happened?
... When in the feed (main page) when you try to add a song or add a playlist it's hidden behind the feed. See photos. 

## Steps to reproduce:
1. Go to main home page when logged in. 
2. You should see feeds. Find a song and try to add a new playlist. The create button is hidden behind the lower feed. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by spirogg** [comment]
![screenshot_20181002-094815](https://user-images.githubusercontent.com/17736688/46356687-d9cecb80-c628-11e8-81dc-1480e68820dc.png)

**Comment by spirogg** [comment]
![screenshot_20181002-094834](https://user-images.githubusercontent.com/17736688/46356815-1f8b9400-c629-11e8-8bb9-fd9ca3828575.png)

**Comment by david-phpFox** [comment]
Fixed in Music 4.6.2
