### ISSUE TITLE
Need option to remove "Space Used" and "Activity Points" from profile info box.

### ISSUE THREAD

**Issue by NeighborlyKoch** [PHPfox-Official/phpfox-v4-issues#2409]
Can not find an option to remove "Space Used and "Activity Points" from the Basic Info box in the user profile.

- Activity Points were disabled in the admin panel as we do not want to use them, but they still show up in user profile.

- No option to removed "Space Used" on basic info. Do not want this information visible.

![image](https://user-images.githubusercontent.com/43898408/46566523-d156e900-c8e5-11e8-990c-2c4e8b1fee67.png)

**Comment by harrison05** [comment]
I found your issues in current version 4.6.1b5, but we're working on the new independency Activity Points App and it will be released soon with phpFox v4.7.0 in this month.
- With new Activity Point app, we hide section "Activity Points" on this page. 
- About "Space Used" statistic, currently, we don't have any option to hide it, but only profile owner can see this statistic. Do you want to hide it for all users (including the owner)?

Regards.

**Comment by NeighborlyKoch** [comment]
Awesome. Sounds good with the new App!

Yes, we would like to hide it from all users, including owner would be fine as well.
