### ISSUE TITLE
Total of three phpfox site now sending out spam mail to the users.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#2411]
## What happened?
Getting SPAM using admins email address

The first site was up for several months, now it is happening on another site using the same email address.  During research of the first time, I changed passwords on the admin account, change the password on mail and even moved from sparkpost to GoDaddy.  The only thing that I thought solved it was creating a new user with a different email address and making that the new admin.  That seemed to stop it.  The next site I just made a fresh install under a different domain but used the same email address.  This site was just set up to show YouNet some bugs in their apps.  Today was the first spam email I received from this new site that was just put up last week.

Platform: Centos 7 with Plesk
Phpfox 4.6 and the latest version

See forum thread as now there are two people with the same issue.
https://community.phpfox.com/forum/thread/57438/spam-emails-sent-using-our-site-mail-configuration-and-credentials/

**Comment by spirogg** [comment]
@PhpFoxJohnJr

Out of curiosity - do your think it's coming  from contact us page ? 
Or
Is it coming from the newsletter where all users will get an email? 

Or

 are you just getting spam under admin email address. 
Does the other user you made up have an email you can see if it's sending same spam email to that user too ??

**Comment by PhpFoxJohnJr** [comment]
OMG!!!!  I am such an IDIOT...
I didn't catch the support because Norton was in front of it...
[Norton AntiSpam]Support: feeekwaq

But you are 100! correct!

WOW!  I gave phpfox 2 months to figure it out and that never came up...LOL.  I guess it is the simple stuff that goes right past us :)

Looking at more of them since I stop looking at them...I see another category which I should have noticed.
[Norton AntiSpam]Suggestions: mdmj
Best Payday Loan [admin@mydomain]

Ok, what got me confused and maybe the reason it didn't click was that on the first website I used john@email.com which was set up in the beginning and later I changed the mail system to admin@mydomain but I never change the email for staff contact us as it was still john@email.com so that so I forgot about that and later made a user for john and then I started getting the emails so I could not understand why my user john was getting the emails from the admin...perfect since now....DARN.

**Comment by PhpFoxJohnJr** [comment]
I am very relieved about this...glad it was stupidity and not an issue with phpfox.

**Comment by PhpFoxJohnJr** [comment]
Checked both sites and the Captcha was on...maybe that is why I was getting one a day...they got tired :)

**Comment by PhpFoxJohnJr** [comment]
Will close this for now and will wait to see if Srny who had the same type of same was from the contact page.
