### ISSUE TITLE
Sponsored and Featured block issue in Events index page

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2413]
Sponsored and Featured blocks not showing in Events index page.

**Comment by Ylmzef** [comment]
It's not showing when u select "ongoing" in admincp settings "Default time to sort events"

**Comment by spirogg** [comment]
What version ? They just make updates. 

What version of phpfox ?

**Comment by harrison05** [comment]
> It's not showing when u select "ongoing" in admincp settings "Default time to sort events"

Those blocks are using this setting. So, please make sure your feature/sponsor events have status is "ongoing".
