### ISSUE TITLE
Ad app not working

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2414]
Ad app not working; Ads not showing also when i enable Ad app left side of the site (Friend Requests | Messenger | Notifications Profile section) not showing.

## Browsers and Devices tested
Chrome

## Server information
Centos 6.10
PHP 7.2.11 & 7.1 & 7.0 & 5.6 & 5.5 & 5.4
Apache
fpm-fcgi

PHP Disabled Functions: | exec, passthru, shell_exec, system
PHP Loaded Extensions: | Core date libxml openssl pcre zlib filter hash Reflection SPL session standard cgi-fcgi bcmath bz2 calendar ctype curl dba dom enchant mbstring fileinfo ftp gd gettext gmp iconv imap intl json ldap exif mysqlnd odbc PDO pgsql Phar posix pspell shmop SimpleXML snmp soap sockets sqlite3 sysvmsg sysvsem sysvshm tidy tokenizer xml xmlwriter xsl zip mysqli pdo_mysql PDO_ODBC pdo_pgsql pdo_sqlite wddx xmlreader xmlrpc Zend OPcache

## phpFox version
phpFox 4.6.1 (build 6)

**Comment by harrison05** [comment]
We can't reproduce your issue on our side. Could you give us more information (app version, screenshot, step to reproduce...)? 

Regards.
