### ISSUE TITLE
Cant Add Activity Points Package

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2415]
# Important!

Please follow this template!

----------------------------------------

We cant Add a package for activity points.  When trying to create a new package for Activity Points it takes you too 500 oops with Error code: 4f3d77
...

## Steps to reproduce:
1. Try to add Activity points package
2. see error

## What is expected?
Wont allow us to create package

## Browsers and Devices tested
  Google Chrome ONLY

## Server information

Core Version: | 4.7.0

PHP Version: | 7.2.11
...

## phpFox version
4.7.0.

...

## Screenshots
...

**Comment by spirogg** [comment]
@harrison05 @erick260 I have the same issue

**Comment by Ylmzef** [comment]
same

**Comment by spirogg** [comment]
@erick260 @ylmzef this issue is fixed now. 

Go to admincp> apps> installed apps and upgrade to 4.7.1 it works. 

Thanks @harrison05 for fixing this 

Spiro

**Comment by spirogg** [comment]
@harrison05 see #2416

**Comment by david-phpFox** [comment]
Fixed in Activity Point 4.7.2
