### ISSUE TITLE
cant upload music

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2417]
# Important!

Please follow this template!
----------------------------------------

## What happened?
I just reinstalled core version 4.7.0 to test. When uploading music it never uploads 

## Steps to reproduce:
1. Go to the Music page
2. Upload a MP3 song.
3. Wait forever. 

## What is expected?
Music/mp3 never get uploaded.
## Browsers and Devices tested
Google Chrome 

## Server information
PHP Version: | 7.1.23
-- | --
## phpFox version
phpfox 4.7.0

## Screenshots
...

**Comment by spirogg** [comment]
Maximum file size of songs uploaded 
10
Max file size for songs upload in megabyte (MB). (1MB = 1000kb) For unlimited add "0" without quotes.

change to 15 or 20 in admincp > apps > installed > Music > usergroups > Administrator and Registered users etc. 

@erick260 @harrison05 I uploaded a song but took over 30-60 seconds to upload and its only 9.67mb

but with version 4.6.1 it only takes 10 seconds

Maybe issue with cron setup see this #2418

**Comment by harrison05** [comment]
@erick260 Your issue is resolved or not? please let me know. Because I can't reproduce it on my site, upload music is working well. You can check on the newest version 4.7.1
