### ISSUE TITLE
crons issue for sure there is something wrong with cron.php 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2418]
----------------------------------------

## What happened?
... why is cron look like this?

https:/demo.mysite.com/cron.php?token=h34iufhf34ifuh4fan332fn4

is this an issue https:/       ONLY 1 forward slash  ---->    /

when I tried to set cron /usr/local/bin/php /home/mysite.com/public_html/cron.php?token=h34iufhf34ifuh4fan332fn4
i get error

if I try to set it up with curl 
https:/demo.mysite.com/cron.php?token=h34iufhf34ifuh4fan332fn4
I never get a log for crons to see if it is working, So I assume it's not working

-----------------------------------------------
I GET ERROR with cli for cron in email

- 504 gateway time-out
---------------------------------------------

please check crons to see they are working on your end and give us path to look for cron.log

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 and apache and nginx php7.2

## phpFox version
(Example: phpFox 4.6.0)

...4.7.0

## Screenshots
...
![cron](https://user-images.githubusercontent.com/17736688/47941907-0ee76b80-debe-11e8-8579-62e103ab180d.PNG)

**Comment by spirogg** [comment]
when we look at setup crons in cpanel it says to use 

```
Enter the command "curl -s https://<your-domain>/cron.php?token=<your-defined-token>" in the blank field next to the Command field. 
(https://<your-domain>/cron.php?token=<your-defined-token> is the URL we received in the first part)
```

@harrison05 when i try to run in ssh command line 

itis stuck trying to run never finishes so somewhere there is error in code

`"curl -s https://<your-domain>/cron.php?token=<your-defined-token>" `

`*/5 * * * * curl -s https://<your-domain>/cron.php?token=<your-defined-token>`

**Comment by spirogg** [comment]
@harrison05 can you give us a fix for this ASAP
since crons is a very important part of running certain aspects of phpfox

thank you sir

Spiro

**Comment by spirogg** [comment]
It's not just the / that's missing even if you do https://your domain.com/cron.php?token=eh35djseiddjs 

It still doesn't work. 

Before in version 4.6.1 you could go to https://your domain.com/cron.php 
In browser it used to show in browser that it was working. 

Now it doesn't work just keeps spinning or errors out.

**Comment by harrison05** [comment]
Let's check your cron job again in phpFox v4.7.1. 
I will temporarily close this issue. 

Regards.
