### ISSUE TITLE
Incorrect website encoding for php 7.1.22

### ISSUE THREAD

**Issue by websistema1** [PHPfox-Official/phpfox-v4-issues#2419]
I use Russian and Ukrainian language packages on the site. I now have a version of php 5.6.36 installed on the server. php 7.1.22 does not support the mysql extension, but only mysqli, that is, in the configuration file /PF.Base/file/settings/server.sett.php instead of $ _CONF ['db'] ['driver'] = 'MySQL'; it was necessary to register $ _CONF ['db'] ['driver'] = 'mysqli'; - the error disappears, and the site begins work on a new version of php 7.1.22. But I was not happy for a long time, since almost the entire text began to appear in the wrong encoding. See the screenshot. I started changing the encodings in the database and in other places, but nothing helped. If I switch back to php 5.6.36, the site works with normal encoding and without errors. Tell me, how can I get the site to display the correct encoding on php 7.1.22?
https://community.phpfox.com/forum/thread/57547/incorrect-website-encoding-for-php-7-1-22/
# Important!

Please follow this template!

----------------------------------------

## What happened?
Incorrect website encoding for php 7.1.22

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

debian, php 7.1.22 apache

## phpFox version
(Example: phpFox 4.6.0)

phpFox 4.7.0

## Screenshots
...
![2018-11-03_173604](https://user-images.githubusercontent.com/14079310/47977456-c3e97600-e0c0-11e8-8a7f-0557a83ee8b8.jpg)

**Comment by spirogg** [comment]
@websistema1 what version of phpfox you do you use?

also,
did you try to turn off any third party apps to see if it still doesn't work?

try to turn off 1 by 1 third-party apps
 and then go to admincp - maintenance - clear cache - clear all cache and then click on rebuilt core theme do this after each app you turn off. and refresh your browser a few times....

then you can see what third party app might be the issue if tt even is third party app

hope this helps you


Spiro

**Comment by spirogg** [comment]
check this info also might help you

https://stackoverflow.com/questions/35424982/how-to-enable-mysqli-extension-in-php-7

The problem is that the package that used to connect PHP to MYSQL is depricated (php5-mysql). If you install the new package:

sudo apt-get install php-mysql
This will automatically update apache and php7.

Cheers!

**Comment by harrison05** [comment]
@websistema1 We just fixed your site. Please follow your ticket.

Regards.
