### ISSUE TITLE
Broken profile layout when the page is zoomed on iOS / Safari

### ISSUE THREAD

**Issue by kirkkhua** [PHPfox-Official/phpfox-v4-issues#2420]
## What happened?
User's profile page will be broken if we will zoom it in and out.

## Steps to reproduce:
1. Go to Anny user profile on v4.phpfox.com using iOS device (for instance iPhone X);
2. Zoom the page using pinch-to-zoom.

## What is expected?
Profile's layout should take full width of the page instead of only part of it.

## Browsers and Devices tested
Safari on iPhone X

## Server information
Server is v4.phpfox.com

## phpFox version
phpFox 4.7.0

## Screenshots
![v4 phpfox com](https://user-images.githubusercontent.com/5412712/47997913-2a44b780-e106-11e8-96fe-a37435adda9d.PNG)

**Comment by harrison05** [comment]
Hi, I can't reproduce your issue with my device (iPhone X), when zooming in, then zoom out, this page auto fix to the full width of the device.

![c504ecb8-1b8d-46a1-bbfc-c12729f257f5](https://user-images.githubusercontent.com/41947198/48110240-939b0680-e27d-11e8-9a53-fda762237503.png)

Regards.

**Comment by kirkkhua** [comment]
@harrison05 please see video attached
[ScreenRecording_11-07-2018 10-10-22.MP4.zip](https://github.com/PHPfox-Official/phpfox-v4-issues/files/2556547/ScreenRecording_11-07-2018.10-10-22.MP4.zip)

**Comment by kirkkhua** [comment]
The issue seems to be fixed in v4.7.1
