### ISSUE TITLE
message app do we need to click on user name every time they send us message to read it ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2421]
# Important!

Please follow this template!

----------------------------------------

## What happened?
... everytime i send a message to a user they open screen to see messages and in order to view my 2nd 3rd 4th etc messages they need to click on the left side on my name to show the messages

is there a way to get this to work without clicking on another users name to read there message

## Steps to reproduce:
1. go to messages click on a user name and send them a message
2. you both are online at the same time - now user opens messages and sends one to me
3. now i am still in messages and waiting to see message, but i dont get it unless i click on that users name on the left side of message

## What is expected?
...  should this not be able show messages automatically as soon as they send them ?

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
cenots 7 php 7.2
...

## phpFox version
(Example: phpFox 4.6.0)
4.7.0
...

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/48023503-94a82880-e103-11e8-926b-cfda34ac2983.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/48023504-94a82880-e103-11e8-8a5f-8fd02c6b97cd.PNG)

**Comment by spirogg** [comment]
in these screen shots as thomas user I had to get out of screen and reopen to see messages

- ![capture](https://user-images.githubusercontent.com/17736688/48023881-a5a56980-e104-11e8-8b3f-926b1335420f.PNG)
- 
![capture1](https://user-images.githubusercontent.com/17736688/48023871-99b9a780-e104-11e8-823a-10c3df347134.PNG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/48023881-a5a56980-e104-11e8-8b3f-926b1335420f.PNG)

**Comment by harrison05** [comment]
Yes, we know this case. Because **Messages** App doesn't support auto-update conversation with real-time. You must refresh it to get new messages. 
Only **Instant Messaging** App support this case, you can try it.

Regards.

**Comment by spirogg** [comment]
Is instant messaging the same app as messages ?? Just have to activate with node.js or is it the same older version ?? 

Will you be updating to newer look and feel like message app the IM ? 

If so I will wait. 

Thanks @Harrison05 
Great work so far. :)
