### ISSUE TITLE
Uninstalling the "Todo" app in v4.6 breaks site

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2423]
Uninstalling the "Todo" app in v4.6 breaks site

**Comment by harrison05** [comment]
Todo App currently doesn't compatible with phpFox version >4.6.0.
Can you take a screenshot about your issue (error log, messages...)? 

Regards.

**Comment by prepperz** [comment]
on the test site just throws the 500 error and stays there.

**Comment by harrison05** [comment]
Can you get more detail about that? You can find the detail of error in **PF.Base/file/log/main.log** (search your error code in this file). 
This issue might be related to setting with type **currency** of Todo App.

**Comment by harrison05** [comment]
Same issue with #2426
