### ISSUE TITLE
Cannot uninstall / remove older apps

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2426]
Cannot uninstall / remove older apps

**Comment by harrison05** [comment]
Can you give us more information about this issue? Please follow our Issue Template

Regards.

**Comment by prepperz** [comment]
For example. Older apps like the "todo" that was installed in the past as test was disabled, but left on the there. After a few iterations of phpfox updates the app cannot be enable or uninstalled.

**Comment by harrison05** [comment]
> For example. Older apps like the "todo" that was installed in the past as test was disabled, but left on the there. After a few iterations of phpfox updates the app cannot be enable or uninstalled.

Todo App doesn't compatible with phpFox version > v4.6.0. 
I have a trick for you to hotfix this case, go to **phpmyadmin** and access to 2 tables: 
- <your_prefix>_setting
- <your_prefix>_user_group_setting

You should search and remove all rows in them with a condition: 
**module_id = "todo" AND type_id = "currency"**, then clear /cache folder on your site.

Hope this solution can help you.
Regards.

**Comment by prepperz** [comment]
@harrison05 Nice solution. :) also see reference to cache issue https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2427

What about for the files (and or associated fies) and location directories?

**Comment by david-phpFox** [comment]
Auto remove Todo App when upgrade Core to 4.7.1 and support un-install a disable app in Core 4.7.1.
