### ISSUE TITLE
Clearing cache from convenient left menu doesn't notify if files are locked

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2427]
When clearing cache from the convenient left menu doesn't notify if files are locked and therefore does not always clear cache (but will always say successful)  until you go into maintenance > cache manager > clear cache > unlock files  then clear cache again.

**Comment by harrison05** [comment]
Currently, we don't check and notice locked files when clear caches from AdminCP menu. Let we check and discuss this case.

Regards.

**Comment by harrison05** [comment]
We updated workflow of this case in phpFox v4.7.1, please check.
