### ISSUE TITLE
Cannot use alpha numeric names when cloning themes

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2428]
Also the error flag of "Alphanumeric characters only for the theme name." make absolutely no sense.

**Comment by harrison05** [comment]
![screen shot 2018-11-19 at 10 06 08](https://user-images.githubusercontent.com/41947198/48684121-d5636f80-ebe2-11e8-926c-792c0673e2da.png)
Take a look on my screenshot, in the newest version of phpFox, field "Name" only support alphanumeric character, so it doesn't allow **white space** or any special characters. Please make sure you don't add any white space in it.

We will update and support "white space" in the next version.

Regards.

**Comment by harrison05** [comment]
Fixed in v4.7.1
