### ISSUE TITLE
v4.7 Does not retain size or position of pages avatar after upgrade

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2429]
v4.7 Does not retain size or position of pages avatar after upgrade and switching from bootstrap to material theme

**Comment by harrison05** [comment]
Could you give us more information?

Thanks!

**Comment by prepperz** [comment]
Not all of the avatar on pages are displaying correctly after the upgrade. Some looks fine and some are not. 
![screenshot](https://user-images.githubusercontent.com/19594886/48685842-8ee02780-eb86-11e8-9133-06a40fafb663.png)

**Comment by harrison05** [comment]
I can't reproduce it on my site. You can create a ticket, then we can check directly on your site.

**Comment by spirogg** [comment]
See #2439 might help this issue also

**Comment by harrison05** [comment]
@prepperz We checked on your site with information from your ticket, this is a bug if your Page lost cache for avatar id in phpfox_cache table. We hotfix issue on your site, and will fix in Pages App.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Groups 4.7.0
