### ISSUE TITLE
Unicode no longer retained in Menu (English) field

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2431]
Unicode no longer retained in Menu (English) field

**Comment by harrison05** [comment]
Could you give us more information?

Thanks!

**Comment by prepperz** [comment]
In the menu field copy and paste any of the unicode from here and then save.: https://emojipedia.org/green-heart/

**Comment by harrison05** [comment]
You are talking about field Menu in **Add New Menu** form in AdminCP, right? See my screenshot
![screen shot 2018-11-21 at 10 12 34](https://user-images.githubusercontent.com/41947198/48816802-32dbf580-ed76-11e8-8da1-a954cdff4de6.png)

**Comment by prepperz** [comment]
Yes that's correct

**Comment by harrison05** [comment]
Ok, we will check it.

**Comment by harrison05** [comment]
I checked with our team. We don't support Unicode icon on Main Menu because it might make breakdown layout, so just type text for it only. Hope you understand.

Thanks
