### ISSUE TITLE
Changing domain: ERROR for site owner: Invalid domain for site key

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2433]
if you clone the site to a different domain domain and use a different license and key iand make proper changes in the settings file it will flag  "ERROR for site owner: Invalid domain for site key" in the registration box.

![screenshot](https://user-images.githubusercontent.com/19594886/48795314-76792580-ecca-11e8-99e8-6b09d4c02188.png)

**Comment by spirogg** [comment]
Hi this is your Google recaptcha code. Not phpfox license issue :)

**Comment by spirogg** [comment]
Test by turn off recaptcha app

**Comment by prepperz** [comment]
@spirogg good catch.
