### ISSUE TITLE
Issue with route('/', 'core.index-member') function 

### ISSUE THREAD

**Issue by nthanhdo** [PHPfox-Official/phpfox-v4-issues#2435]
## I can't override route('/','music.index')?
It's always show the feed ('core.index-member')
I'm using phpfox 4.7 for that. 
On 4.6 version, I can do this. 
Anyone can help me this case? 
`PF.Site/Apps/core-music/start.php`
```
group('/', function () {
    route('/', 'music.index');
});
```

...

## phpFox version 4.7.0
...

**Comment by harrison05** [comment]
In the current version, you can't override another route at home page.
This is a bug of Core, we will fix on the next version.

Btw, you have another way to do this, you can add a hook to Music (or any other apps) (PF.Site/Apps/core-music/hooks) with filename "module_setcontroller_end.php", then add this below codes into it:
```php
<?php
if (Phpfox::isModule('music')) {
    if ($this->_sModule == 'core' && $this->_sController == 'index-member') {
        $this->_sModule = 'music';
        $this->_sController = 'index';
    }
}
```

Regards.

**Comment by harrison05** [comment]
@nthanhdo We fixed this issue in v.4.7.2. Please check.
