### ISSUE TITLE
when delete playlist from music app database does not remove in feed

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2438]
@harrison05
----------------------------------------

## What happened?
... when I add playlists in music app it shows in feed when I delete from music app it doesnt delete the playlist in database i use myadminphp to look this up and test

## Steps to reproduce:
1. add a music playlist
2. then view feed should show this is there, 
3. no go back to music app and delete playlist
4 open your myphpadmin or other database tool to view tables in mysql and go look for phpfox_feed
you will see the list there and each time you add playlist it shows, if you delete from music it never deletes from database ? and you get popup playlist not found playlist not found because of this

if you delete playlist from feed the database entry deletes, but if you delete from music app section, the database entry stays in database tabke phpfox_feed and causes errors when scrolling or when you wait for the updates to appear based on your time you set for refresh of feed

 
thanks hope you can get this fixed and check all other apps, since I have not for same issue ?

## What is expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)
cenots 7 php 7.2
...

## phpFox version
(Example: phpFox 4.6.0)

...phpfox4.7.0 
music app 4.6.2

## Screenshots
...
![music playlist error phpmyadmin](https://user-images.githubusercontent.com/17736688/49006356-88295580-f12e-11e8-9305-e30b8463024d.PNG)
![capture2](https://user-images.githubusercontent.com/17736688/49006364-8cee0980-f12e-11e8-8d86-8a29f0a9e105.PNG)
![capture](https://user-images.githubusercontent.com/17736688/49006367-8f506380-f12e-11e8-8de3-0447c4fb39e9.PNG)

**Comment by david-phpFox** [comment]
Fixed in Musics 4.6.3
