### ISSUE TITLE
Avatars for message are huge after upgrade from 4.6 to v4.7

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2439]
Avatars for message are huge after upgrade from 4.6 to v4.7. installing message from the store a second time fixed it.

**Comment by spirogg** [comment]
I think there is a setting in admincp> Maintenance >counters 

Not sure if this will just update count or resize avatar photos ? But there are a few of them. You can click on > Update Photo Thumbnails


See if this helps you 

After click remove files no longer needed and clear cache, clear all cache and rebuild theme.

**Comment by kibcode** [comment]
have you done these steps?

- remove files no linger used
- rebuild core theme
- clear cache
