### ISSUE TITLE
In v4.71, recaptcha in registration is cut off 

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2441]
![screenshot](https://user-images.githubusercontent.com/19594886/49263825-09783500-f41a-11e8-8ec0-4096d3bb62bd.png)

**Comment by Flirtnet** [comment]
I have the same issue

**Comment by david-phpFox** [comment]
Hi prepperz,

I have fixed in latest build of Core 4.7.1.

Best Regards,
David Nguyen

**Comment by spirogg** [comment]
Works for me in new install 4.7.1 desktop and mobile Android
