### ISSUE TITLE
Duplication in DB

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2442]
![screenshot](https://user-images.githubusercontent.com/19594886/49275918-e023cd00-f44a-11e8-8e3c-e6ee0a2e7531.png)

I'm noticing duplications. in the DB. Is this intentional?

**Comment by harrison05** [comment]
Those indexes are added from old version if you upgrade from Photo module to Photo Apps, you can manually remove duplicate indexes. 

Regards.
