### ISSUE TITLE
Keeping the "phpfox_log_session" in DB causes lots of serious issues

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2444]
Keeping the phpfox_log_session in the database causes a lot of really serious  issues ranging from making your site really slow, prevent upgrades, kills your DB server, 500 error issues, high CPU load and other erratic symptoms.

Should keep it very small, write to file instead of db, truncate, auto empty or something. Basically anything that don't need to be in DB shouldn't.

**Comment by harrison05** [comment]
About data in this table, we were set up a cron job to clear old data if user inactive longer than setting **Active Session**. This is full description for this setting:

> If a user is inactive longer than the specified setting they will be removed from the online session table. When this is done they will no longer appear to be online when other members view their profile. If the user suddenly becomes active after their session expired a new session will automatically be created.

Do you set up the cron job for your site?

Regards.

**Comment by prepperz** [comment]
Yes cron is setup. However, the log session will continue to pile up on the DB.

**Comment by prepperz** [comment]
Also related to this issue cron issue: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2418

It turns out I was missing a single forward slash in URL to the cron file. However, given that for some reason cron isn't properly running, it would definitely cause lots erratic issues as well as prevent many from upgrading. So may be consider an a safe guard to keep sites properly functioning especially during the upgrade process by checking and emptying the log sessions or maybe have it built in without needing cron scheduling for essential or critical things.

**Comment by david-phpFox** [comment]
We will consider for your suggestion.
I will temporarily close this issue.
