### ISSUE TITLE
v4.71 pages/groups edit thumbnail  does not save

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2446]
v4.71 pages edit thumbnail  does not save

**Comment by harrison05** [comment]
We just tested on your site with new Page and this feature working well. 
Can you give us more detail about this issue?

Regards.

**Comment by prepperz** [comment]
Click on a pages. Manage > photo > edit thumnail. readjust thumnal. now click save. It does nothing.

**Comment by harrison05** [comment]
> Click on a pages. Manage > photo > edit thumnail. readjust thumnal. now click save. It does nothing.

Okay, I can reproduce this issue. 
This is the root cause: You logged in as Site Admin and you edit thumbnail of a Page/Group you aren't Admin or Founder. So, if you edit your page/group, this feature is working well.
- Bug of Pages/Groups App, we will fix in the next version.

Regards.

**Comment by david-phpFox** [comment]
Fixed on Pages 4.7.0 and Groups 4.7.0
