### ISSUE TITLE
Urls don't work in photo description in detail view

### ISSUE THREAD

**Issue by nativedragon11** [PHPfox-Official/phpfox-v4-issues#2447]
## What happened?
When I posted an image with a url in the description, the url works (is clickable) in the feed, but when the image is viewed directly by clicking on it to enter detail view, the url is not active (not clickable), and appears as normal text.

## Steps to reproduce:
1. Upload and image and put a url in the image description
2. View the image in the feed. The url works
3. Click the image to see it in detail view. The url you have in the description does not work.

## What is expected?
The url should work in both views so that users can share a website or link related to their photos

## Browsers and Devices tested
Chrome on Android, Chrome on Windows 10, Firefox on Windows 10

## Server information
None relevant. Tested on both the Material and Bootstrap demos

## phpFox version
phpFox 4.7.1

## Screenshots
![screen1](https://user-images.githubusercontent.com/39366566/49359743-4b141480-f694-11e8-9c94-8ccf87495f35.png)
![screen2](https://user-images.githubusercontent.com/39366566/49359747-4ea79b80-f694-11e8-9a7d-577fd3fb5b98.png)

**Comment by harrison05** [comment]
Please follow your post in phpFox Community, this is a bug of Photos.

**Comment by harrison05** [comment]
Fixed in Photo v4.7.0.
