### ISSUE TITLE
Antispam question creation doesn't save

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2448]
There there is no save option or indicator that tells the admin that the question created is being saved. So, unless you hit enter it doesn't save. It is very counter intuitive.

**Comment by harrison05** [comment]
Can you explain more about this issue? 
A form only submits when you hit enter or submit button, so what's wrong with it?

Regards.

**Comment by prepperz** [comment]
That is the point. in the admincp when you first create the answers, there are no submit button / update button. So most just assume that it's automatically saved and later to find out that the save function is only triggered when they press enter. Otherwise it does not.

**Comment by harrison05** [comment]
I can't reproduce it, answers save when hit "Add Question" button
![screen shot 2018-12-07 at 09 54 36](https://user-images.githubusercontent.com/41947198/49625003-58b7fa00-fa06-11e8-988e-f7675fd2bf57.png)

**Comment by prepperz** [comment]
![screenshot](https://user-images.githubusercontent.com/19594886/49631612-aa3d9600-f9c0-11e8-8a19-de5413f9ca04.png)

**Comment by harrison05** [comment]
No, you don't need to hit enter to save Answers, just type your answers, then click "Add question" button to save.

**Comment by prepperz** [comment]
That's exactly the point. Clicking add question again doesn't make any sense.
Clicking add question is suggesting to the user that they want to "Add another" question, not save it. As a result, the admin will not click it.

I suppose if making another button is too much trouble. Just label it as "add question / save" or something,.
