### ISSUE TITLE
Cannot Disallow Main forum "Can browse and view the forum module" while still keeping pages / groups forum functional

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2449]
Cannot Disallow Main forum "Can browse and view the forum module" while still keeping pages / groups forum functional

**Comment by harrison05** [comment]
You want to disallow members access to Forum in the main menu but still allow members to use Discussion section in Pages/Groups, this is your mean?

**Comment by prepperz** [comment]
Correct. Not everyone wants a main forum. I can disable the menu, but anyone can still access the main forum if they know the links especially spammers and bots because it's very easy to spot a phpfox site.

**Comment by harrison05** [comment]
If you just want to hide Forum on the main menu, you can go to **AdminCP > Appearance > Menus** and de-active Forum menu.
