### ISSUE TITLE
Activity Points Sent Transaction history shows cryptic profile ID# instead of name

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2451]
Activity Points Sent Transaction history shows profile ID# instead of name

**Comment by harrison05** [comment]
Could you give us more information?

Thanks!

**Comment by prepperz** [comment]
Here ya go
![screenshot](https://user-images.githubusercontent.com/19594886/49516687-2ff9fe00-f868-11e8-8eed-656cc9c43d5d.png)

**Comment by david-phpFox** [comment]
Will fix in Activity Points 4.7.3

**Comment by prepperz** [comment]
Still not fixed in activity points 4.7.4

**Comment by harrison05** [comment]
> Still not fixed in activity points 4.7.4

We just fixed on new data, you can check with new transactions.
