### ISSUE TITLE
Activity Points Package purchase Test Sends an Empty Amount to Paypal.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2452]
Activity Points Package purchase Test Sends an Empty Amount to Paypal.

Likely related to https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2450

**Comment by david-phpFox** [comment]
Related to [#2450](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2450)
