### ISSUE TITLE
Sort Buttons Not Working in Browse Section

### ISSUE THREAD

**Issue by nativedragon11** [PHPfox-Official/phpfox-v4-issues#2453]
## What happened?
When browsing members in mobile view (bootstrap theme), the "sort" buttons don't work at all. This feature also appears completely absent in the material theme.

## Steps to reproduce:
1. Either from mobile or resized browser window, go to the browse section ( https://v4-bootstrap.phpfox.com/user/browse/ )
2. Click the 3 dots next to the search icon to open the sort menu
3.  Click the sort buttons. You will see they do nothing.

## What is expected?
Should be able to click the buttons to sort members by most recent/active, and sort results by amount

## Browsers and Devices tested
Chrome on Android, Chrome on Windows 10, Firefox on Windows 10

## Server information
phpFox demo sites

## phpFox version
phpFox 7.7.1

## Screenshots
![screenshot](https://user-images.githubusercontent.com/39366566/49430440-3ef98700-f768-11e8-8f70-cfe82579ba77.png)

**Comment by harrison05** [comment]
We will fix in the next version of phpFox.

Thanks.

**Comment by harrison05** [comment]
Hi @nativedragon11 , we fixed it in v4.7.2, please check.
