### ISSUE TITLE
Non-visible blocks cause weird display issues

### ISSUE THREAD

**Issue by lethality** [PHPfox-Official/phpfox-v4-issues#2454]
Weird block placement issues when adding non-visible html

**To reproduce:**

1. Firstly, look at a users profile page, and note the sizing and placement of the feed block, then add a block, most likely example for most people being Google Analytics, which is javascript. Use instructions provided at: [https://docs.phpfox.com/display/FOX4MAN/Integrate+Google+Analytics+to+your+phpFox+site](https://docs.phpfox.com/display/FOX4MAN/Integrate+Google+Analytics+to+your+phpFox+site)

2. Clear cache, and refresh that user's profile page, look at the difference, scroll down the page and see the way the content suddenly jumps to the right when the scroll main-menu becomes visible, it's a horrible UX, and seeing as the block has no front-end html blocks, there's no reason it should happen.

## What is expected?
The feed and pages should remain totally unchanged by a block like this.
The obvious main issue, regarding the way it moves across when you scroll, is the fact the addition of the block causes a new 256px margin-left in .layout-main #content-holder.layout-middle. 

## Browsers and Devices tested
Opera v56 on Windows 10 Pro.

## Server information
Centos 7.6, Apache 2.4, PHP 7.2

...

## phpFox version
v4.7.1

...

## Screenshots
..
![How the page looks WITHOUTblock activated](https://user-images.githubusercontent.com/520295/49434102-573ec580-f7ab-11e8-896f-3e679f90e99f.png)
![How it looks WITH the block activated](https://user-images.githubusercontent.com/520295/49434103-573ec580-f7ab-11e8-9d87-ba61d5aabde0.png)
![How it looks when you scroll](https://user-images.githubusercontent.com/520295/49434104-573ec580-f7ab-11e8-9b2b-225263e2139c.png)

**Comment by david-phpFox** [comment]
Released Core 4.7.2
