### ISSUE TITLE
Photo Comments Doesn't Pickup Smilies :)

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2456]
Photo Comments Doesn't Pickup Smilies :)

**Comment by harrison05** [comment]
Currently, we don't support parse emoji icon from keyword in a comment.

**Comment by prepperz** [comment]
If memory serves, it was previously supported. Just did a quick test and no longer does it in the status either.

**Comment by harrison05** [comment]
Currently, only emoji code support by "Twemoji Awesome" app can be converted to icon.

Regards.
