### ISSUE TITLE
Deleting shoutbox message does not disappear until refreshed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2459]
Deleting shoutbox message does not disappear until refreshed

**Comment by harrison05** [comment]
On our site, the message disappears immediately after deleted.

**Comment by prepperz** [comment]
It does the same thing on the demo site on chrome.

![screenshot](https://user-images.githubusercontent.com/19594886/49900345-51408880-fe2c-11e8-82c7-d173f514005b.png)

**Comment by harrison05** [comment]
Ok. I can reproduce it. This issue only occurs when you delete a message immediately after you chat without refresh page. 

Thanks for your report.
