### ISSUE TITLE
Home Main text in theme displays at bottom

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2461]
The text does not display from the top. Is this intentional?

**Comment by harrison05** [comment]
Can you take a screenshot?

**Comment by prepperz** [comment]
In previous version it's at top. maybe compromise and offer an option for top or bottom?
![screenshot](https://user-images.githubusercontent.com/19594886/49850010-fb2b0100-fda9-11e8-91ff-288491b78c24.png)

**Comment by harrison05** [comment]
This is intentional. It works as design.
