### ISSUE TITLE
Uploading cover photo for pages show on main photo, but not pages photo

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2463]
Uploading cover photo for pages show on main photo, but not pages

**Comment by harrison05** [comment]
Please make sure you enable those settings

![screen shot 2018-12-12 at 10 19 43](https://user-images.githubusercontent.com/41947198/49845237-7a472600-fdf8-11e8-8613-4d88e3d8ac9d.png)
