### ISSUE TITLE
Pages video thumbnail not aligned when scrolling down

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2464]
![screenshot](https://user-images.githubusercontent.com/19594886/49684291-1ba04600-faa0-11e8-963d-b8df1b59b94a.png)

**Comment by harrison05** [comment]
It might have the same root cause with issue #2429

**Comment by prepperz** [comment]
Groups are also affected

**Comment by david-phpFox** [comment]
Fixed on Pages 4.7.0 and Groups 4.7.0

**Comment by prepperz** [comment]
Still not fixed in pages or groups for 4.7
