### ISSUE TITLE
Delete videos from pages takes user away from page to main video

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2466]
This has been reported for years and it quickly gets annoying after a while.

**Comment by harrison05** [comment]
Do you check with the newest version? We can't reproduce on our side. After deleted video in page, it redirect to **pages/<page_id>/video/**

**Comment by prepperz** [comment]
Steps to reproduce: goto pages video > click on gear of video > then select delete. 

It will take you to main video that is no longer on the page.

**Comment by harrison05** [comment]
Finally, I can reproduce. It only occurs when you delete a Video in a Page and you aren't an Admin of this Page.

**Comment by david-phpFox** [comment]
Will fix in Videos 4.7.1

**Comment by david-phpFox** [comment]
Fixed in Videos 4.7.1
