### ISSUE TITLE
default pages display filter is misleading

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2469]
When pages is clicked from the menu the default filters says, "Latest" which is misleading and the page does not show the latest pages. Until the drop down filter is selected and "latest" is clicked on and then it will show the latest pages.

![screenshot](https://user-images.githubusercontent.com/19594886/49729230-e122de80-fc42-11e8-829d-9307d9a7fe51.png)

**Comment by david-phpFox** [comment]
Fixed in Pages 4.7.0 and Groups 4.7.0
