### ISSUE TITLE
If phpfox site admin is Adding xxxx admin in pages and if xxxx like the page it will say phpfox site admin like it in feed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2470]
If phpfox site admin is Adding xxxx admin in pages and if xxxx like the page it will say phpfox site admin like it in feed instead of xxxx. 

Also no notification alert is shown that xxxx like the page.

**Comment by david-phpFox** [comment]
Fixed in Pages 4.7.0
