### ISSUE TITLE
Activity points history show deleted items as points sent

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2471]
![screenshot](https://user-images.githubusercontent.com/19594886/49820807-e406f780-fd46-11e8-905d-fc1d6398b7ae.png)

**Comment by harrison05** [comment]
This is our business rule, "Sent" mean "Users lost points they were earned when deleted an item".

**Comment by prepperz** [comment]
This will confuse many users because the total sent will keep going. and if they add / delete repeated on purpose can you can see the issue. Probably a good idea to have a different stat for deleted items.

![screenshot](https://user-images.githubusercontent.com/19594886/49849020-cddc5400-fda5-11e8-9c24-c6c8f149f682.png)

**Comment by harrison05** [comment]
Ok. We will check this case in the next version of Activity Point App. 
I will temporarily close this topic and inform you if have any update.

Regards.
