### ISSUE TITLE
Home main text darkens the whole page instead of just text area

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2472]
Home main text darkens the whole page instead of just text area

**Comment by prepperz** [comment]
If this working as designed, then it's not right as previous versions only  the text box area is darkened and not the whole page.
![screenshot](https://user-images.githubusercontent.com/19594886/49850340-12b6b980-fdab-11e8-8b15-07af143b8484.png)

**Comment by harrison05** [comment]
I working as our new designed, it might differ with the older version. Our team verified it before released.
