### ISSUE TITLE
Featured pages: Cannot click on images

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2473]
Featured pages: Cannot click on images

**Comment by harrison05** [comment]
Could you give us more information?

Thanks.

**Comment by prepperz** [comment]
see screenshot
![screenshot](https://user-images.githubusercontent.com/19594886/49848370-daab7880-fda2-11e8-8f6d-1f5cf57b7238.png)

**Comment by harrison05** [comment]
About issue missing avatar, you can check avatar source on your site is still existed or not. About issue can't click on the cover, we will check it.

**Comment by david-phpFox** [comment]
About issue missing avatar, maybe is old data, the cause is missing square image. we will check and fix it in Pages 4.7.0 and Groups 4.7.0

**Comment by david-phpFox** [comment]
Fixed in Pages 4.7.0 and Groups 4.7.0
