### ISSUE TITLE
Featured pages: If more than two are featured, thumbnail is not displayed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2474]
Featured pages: If more than two are featured, thumbnail is not displayed. Maybe related to this; https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2486

**Comment by harrison05** [comment]
Could you give us more information?

Thanks!

**Comment by prepperz** [comment]
See screenshot
![screenshot](https://user-images.githubusercontent.com/19594886/49848349-b51e6f00-fda2-11e8-808d-9b552a38beec.png)

**Comment by prepperz** [comment]
This issue seems to be resolved by the recent pages and group thumbnail / avatar updates.
