### ISSUE TITLE
Pages: Nice test?

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2475]
What is this?

![screenshot](https://user-images.githubusercontent.com/19594886/49841435-a2497180-fd85-11e8-9259-a68418c141ba.png)

**Comment by david-phpFox** [comment]
Hi prepperz,

This issue belong to old phrase.
Please go to phrase management and search variable name "module_blog" then change it to "Blog".

Best Regards,
David Nguyen.
