### ISSUE TITLE
Activity Points: Cannot edit action phrase directly from app admincp

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2476]
Activity Points: Cannot edit action phrase directly from app admincp. Some default phrases are nonsensical or not correct.

**Comment by harrison05** [comment]
Which phrases do you want to edit? Could you explain more?

**Comment by prepperz** [comment]
Any of these. Which can be done through phrase manager, but a real pain.
![screenshot](https://user-images.githubusercontent.com/19594886/49848618-f3685e00-fda3-11e8-9641-b1767e3215d3.png)


to the user some of the phrases don't make sense

![screenshot2](https://user-images.githubusercontent.com/19594886/49848876-23643100-fda5-11e8-90a4-ad4773e5349f.png)

**Comment by david-phpFox** [comment]
Please go to AdminCP > Phrases, search and change these phrases.
