### ISSUE TITLE
Wordwrap doesn't work properly in messages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2480]
Wordwrap doesn't work properly in messages

**Comment by davidnguyen88** [comment]
Please follow [issue template](https://github.com/PHPfox-Official/phpfox-v4-issues/blob/master/ISSUE_TEMPLATE.md). We can not verify issue with little info.

**Comment by david-phpFox** [comment]
Will fix in Message 4.7.1

**Comment by david-phpFox** [comment]
Fixed in Message 4.7.1
