### ISSUE TITLE
Related group not displaying thumbnail/avatar

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2483]
![screenshot](https://user-images.githubusercontent.com/19594886/50053742-46c20f80-0108-11e9-86cb-64a8ca971c27.png)

**Comment by harrison05** [comment]
This group lost image source, it only happens for some old data, we will fix in the next version of Groups App.

**Comment by david-phpFox** [comment]
Fixed in Groups 4.7.1
