### ISSUE TITLE
site admin cannot claim pages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2484]
admin cannot claim pages

**Comment by PhpFoxJohnJr** [comment]
Do you mean admin of the site or admin of the group.

**Comment by prepperz** [comment]
website admin

**Comment by harrison05** [comment]
See my screenshot. Does it be your issue?
![screen shot 2018-12-17 at 09 53 05](https://user-images.githubusercontent.com/41947198/50064059-ab04d200-01e1-11e9-995c-b35843f29215.png)

**Comment by prepperz** [comment]
Yes

**Comment by david-phpFox** [comment]
Fixed in 4.7.2
