### ISSUE TITLE
Pages/groups: Site admin cannot reassign owner to site admin

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2485]
Pages/groups: Site admin cannot reassign owner to site admin

**Comment by harrison05** [comment]
I can't reproduce this issue.

**Comment by prepperz** [comment]
When I go to a pages> select a page > click on the 3 dots and then reassign and type in my username, it doesn't come up.

It's possible that it may also be related to this: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2350

**Comment by harrison05** [comment]
Could you clear cache and check again? If this issue is resolved, it might related to #2350

**Comment by prepperz** [comment]
Yup tried clearing the cached many times issues still exist.

**Comment by harrison05** [comment]
We will check this issue again after fixed #2350.

**Comment by harrison05** [comment]
This issue was fixed, you can check with Pages/Groups v4.7.2
