### ISSUE TITLE
User profile page  not displaying thumbnail/avatar for certain liked pages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2486]
![screenshot](https://user-images.githubusercontent.com/19594886/50078236-70d10b80-01b4-11e9-9ae2-706ac11797c4.png)

![screenshot](https://user-images.githubusercontent.com/19594886/50081354-3ff4d480-01bc-11e9-9456-e3b83fc7c2a7.png)

https://v4.phpfox.com/profile-5168/

**Comment by david-phpFox** [comment]
Fixed in Pages 4.7.1
Please check again on our demo: https://v4.phpfox.com/profile-5168/
