### ISSUE TITLE
Deactivated menu items are somehow getting reactivated over time

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2487]
## What happened?
Been noticing previously deactivated menu items are somehow getting reactivated over time.

## Steps to reproduce:
Have not investigated to see what is triggering it.

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
CentOS 7, php 7  apache

...

## phpFox version
(Example: phpFox 4.7.1)

...

## Screenshots
...

**Comment by harrison05** [comment]
I checked this case, a menu auto reactivated after I upgrade its app. This might a bug of Core, we will check and fix.

Thanks.

**Comment by david-phpFox** [comment]
Hi all,

We has fixed this issue on Core 4.7.2. It will be released in next week.

Thanks.

**Comment by david-phpFox** [comment]
We are ready to release 4.7.2 but we have to release it after the holiday to better support when there is a problem.

**Comment by spirogg** [comment]
@david-phpfox

When you say after the holiday can you give us a specific date ?  1st week of Jan 2019 2nd week of Jan 2019 ??

Thanks 
Spiro

**Comment by david-phpFox** [comment]
Hi @spirogg 

1st week of Jan 2019

**Comment by david-phpFox** [comment]
Released Core 4.7.2
