### ISSUE TITLE
Feed: "Sort by - Most Recent" not working properly

### ISSUE THREAD

**Issue by KamAZenok** [PHPfox-Official/phpfox-v4-issues#2489]
## Steps to reproduce:

1. Make a new fresh installation of PHPFOX 4.7.1
2. In Admin Panel go to "Apps -> Installed -> Feed" and set: Criterion to sort top stories in feed - "Both", Default criterion to sort on New Feed - "Most Recent". Save Changes.
3. At the homepage of the site choose "Sort by - Most Recent"
4. Make some posts in the feed. You need to make a lot of posts until you see the rotating circle at the bottom of the screen, showing that older posts are loading.
5. Choose some posts _BELOW_ that rotating circle (earlier). Give "like" to some and write comment to other, for example.
6. Update page and wait some minutes until message "You have <#> updates" appears.
7. Click on it, and you will see your posts with "like" and "comment" at the top of the feed!
8. NOTE: "Sort by" is still "Most Recent" !!!
9. Now you can give "like" and write comment to ANY of the posts, and all of them will go to the top of the feed. (NOTE: It is important to make first action with the posts, which are located in the next portion of data, i.e. BELOW rotating circle, as described at step 5)

On Demo site at - https://v4.phpfox.com/ - it also can be reproduced

## Browsers and Devices tested
Any browsers

## Server information
CentOS 7, php 7.2.13, apache, MySQL 5.5.5-10.3.11-MariaDB

## phpFox version
phpFox 4.7.1

**Comment by KamAZenok** [comment]
Thanks. What about fixing?

**Comment by david-phpFox** [comment]
We will fix and release it in Core 4.7.2

**Comment by kerstar** [comment]
Great!

**Comment by david-phpFox** [comment]
Released Core 4.7.2
