### ISSUE TITLE
Scrolling down in an empty market place shakes really bad

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2490]
## What happened?
Scrolling down with an empty market place shakes really bad 

## Steps to reproduce:
1. goto empt market place and scroll down
2. 
3. 

## What is expected?
it should not be shaking

## Browsers and Devices tested
Chrome on Windown 10

## Server information
CentOS 7, php7, apache

...

## phpFox version
phpFox 4.7.1

...

## Screenshots

**Comment by harrison05** [comment]
Do you mean the main menu is shaking when scrolling down?

**Comment by prepperz** [comment]
yes

**Comment by harrison05** [comment]
We will check this case.

Regards.

**Comment by harrison05** [comment]
@prepperz Could you check with the current version of phpFox and Material? Do it still occurs or not? Because our development team informs me that was fixed.

Regards.
