### ISSUE TITLE
Link in phpFoX demo detected by my anti virus software

### ISSUE THREAD

**Issue by starplan** [PHPfox-Official/phpfox-v4-issues#2491]
I thought that I would inform you of the following.

----------------------------------------

## What happened?

While scrolling down the main feed in the demo, my anti virus software detacted a link and would not allow me to scroll down futher after clicking on the load more button. The link that was detected is below.

------------------------------------

Dangerous URL blocked;https://v4.phpfox.com/_ajax?&core[ajax]=true&core[call]=feed.viewMore&page=8&year=&month=&last-feed-id=27920&core[security_token]=e1d56e6bb2411612b33b8d5aa15f00b3&core[is_admincp]=0&core[is_user_profile]=0&core[profile_user_id]=0&_=1545072115416;https://v4.phpfox.com/_ajax?&core[ajax]=true&core[call]=feed.viewMore&page=8&year=&month=&last-feed-id=27920&core[security_token]=e1d56e6bb2411612b33b8d5aa15f00b3&core[is_admincp]=0&core[is_user_profile]=0&core[profile_user_id]=0&_=1545072115416;Heuristic

------------------------------------

## Steps to reproduce:

Using Kasperski Free anti virus

1. Login into demo
2. Scroll down feed clicking on "Load More" until anti virus detects the above link (After puppet horse and rider). 
3. 

## What is expected?
Cannot scroll beyond point where link is detected

## Browsers and Devices tested
(Kasperski Free antivirus, Firefox 64, ...)

## Server information

...

## phpFox version
(phpFox Demo)

...

## Screenshots
...

**Comment by harrison05** [comment]
It seems this link is right. We defined this link with many parameters to load more feeds with current loading conditions.

**Comment by spirogg** [comment]
It means the posted link at that section your computer detecting  a virus or website link that usually is bogus with viruses so you not click on it.

 We must remove that post / blog post in feed or link from feed
-  once reported and admin removes this will not happen anyway longer.
- It's protection for users.  I've seen this before. When scrolling the feed.

**Comment by spirogg** [comment]
@harrison05

Maybe you can make it that the link will not be added to feed and admin will get notice about spam - virus

- so it doesn't ruin visitors view when scrolling
- and also user doesn't report your website IP and domain  as a virus or spam website 
then goolge blocks you 
Or browser chrome Firefox Safari 
 Bad for seo.

**Comment by harrison05** [comment]
@spirogg Thank for your suggestion, but I think it isn't easy to detect a link on feed is spam-virus by our source Core. Users have to report feed manual, or Admin can Disable all external link or add some dangerous URLs to blacklist in AdminCP.
