### ISSUE TITLE
Some of the phrases are displayed in the wrong language

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2492]
## What happened?

I just translate the website into my language and noticed that three phrases still display in English, although I have translated them and cleaned the cache.

Two phrases are the "Reset" and "Submit" buttons in the user browsing module:
https://www.mysite.com/user/browse/

The third phrase, which is displayed in English despite its translation, is "Search" on this page:
https://www.mysite/search/?q=

Another bad phrase is the phrase "members" in relation to the number of people who like a given group.

In the attachment I send screenshots, where I showed the problem.

I described the problem in more detail in the ticket with the number: #478396 and I've been waiting for a week for your help in repairing the problem.

## Browsers and Devices tested
Chrome, Firefox, Edge on Windows 10

## phpFox version
4.7.1

...

## Screenshots
![memberslike6](https://user-images.githubusercontent.com/38014237/50125284-62dcc280-0268-11e9-9206-07a8c1756f49.png)
![memberslike7](https://user-images.githubusercontent.com/38014237/50125286-62dcc280-0268-11e9-95d5-036c651416bb.png)
![searchphrase](https://user-images.githubusercontent.com/38014237/50125287-62dcc280-0268-11e9-83da-ad70b84dfe59.png)
![submitphrase2](https://user-images.githubusercontent.com/38014237/50125288-62dcc280-0268-11e9-8c38-f6fea334da5e.png)

**Comment by david-phpFox** [comment]
About no. member of group, please translate for phrase '1_member' and add new phrase 'member' then translate it.

For phrases can not translated, we will fix it in 4.7.2

**Comment by kerstar** [comment]
David, Your advice has helped me and in places where there was a issue now is the correct language, but now I found another place where the same problem appeared.

On the "www.examplesite.com/exampleuser/groups/" page, the words "member" and "members" are displayed in the wrong language.
In the attachment I am sending a screenshot of the issue shown.
![memberslike8](https://user-images.githubusercontent.com/38014237/50408371-5d8ff280-07e9-11e9-90d9-fb32320e0a8e.png)

**Comment by david-phpFox** [comment]
Released Core 4.7.2
