### ISSUE TITLE
I noticed a problem in verification messages

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2493]
## What happened?
I noticed that the user can send any number of re-verification messages.
I mean that the "Resend verification e-mail" button does not disappear, which may cause abuse on the part of dishonest persons, causing that by typing a fake e-mail address user can spam an e-mailbox, which may lead to falling into the spam list.

Can you somehow limit the resending of the verification message? 
For example, so that the user can click on the button after 15 minutes from the first sending of the verification email.

## Browsers and Devices tested
Chrome, Firefox, Edge on Windows 10

## phpFox version
4.7.1

**Comment by harrison05** [comment]
This is a good requisition. We will consider it.

Regards.

**Comment by spirogg** [comment]
Can you add this in 4.7.2 please. It's a small addon will take you ~10mins :)

**Comment by harrison05** [comment]
> Can you add this in 4.7.2 please. It's a small addon will take you ~10mins :)

Version 4.7.2 was ready for release from last week, so we can't push new feature to it. We will implement this feature in v4.7.3

P/s: btw, this feature will take more than 10 mins to implement and verify. 

Thanks.
