### ISSUE TITLE
Error while editing phrases

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2494]
## What happened?

When searching for a phrase for further editing, it is redirected to the main page of phrases, without applying the specified phrase as a filter.

## Steps to reproduce:
1. Goto "Manage Language Packages" (Globalization->Languages) and select the desired language pack (Manage Phrases)
2. In the phrase page that opens choose your preferred language (except for English / not English) in "Language Packages" 
3. Specify the search phrase in "Search For Text" like "Send"
4. And click the "Search" button

Then there is a redirection to the edit page of all phrases without the use of any filters.

## What is expected?
It is expected that the search phrase for the selected language will be displayed.
Instead, it shows a list of all the phrases for all languages in a row.
The error appeared immediately after upgrading to 4.7.0 and was preserved in update 4.7.1.

## Browsers and Devices tested
Firefox and Chrome on Windown 10

## Server information
Core Version: 4.7.1
PHP Version: 7.2.8
Operating System: Linux
GZIP: Enabled
SQL Driver Version: MySQL 5.6.34
SQL Slave Enabled: No
SQL Total Slaves: N/A
SQL Slave Server: N/A

## phpFox version
phpFox 4.7.1

## Screenshots
Please pay attention to the address bar of the browser. 

before
![1](https://user-images.githubusercontent.com/11414490/50306224-3bb70880-0495-11e9-801d-3e46c31e5be5.jpg)

 and after clicking the search button.
![3](https://user-images.githubusercontent.com/11414490/50306338-9a7c8200-0495-11e9-91f9-ee825d1dde77.jpg)

**Comment by harrison05** [comment]
I can't reproduce this issue on my site (v4.7.1). If this issue still appears in your site, you can submit a ticket in our client area, then we will have a direct check on your site.

Regards
