### ISSUE TITLE
Incorrect display of the phrase when loading images

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2495]
## What happened?
When uploading photos to the album after selecting a photo, the inscription on the button changes.

## Steps to reproduce:
1. goto /photo/add/?album=3125
2. choose a photo from the computer
3. and the button changes its value

## Browsers and Devices tested
Chrome on Windown 10

## Server information
Core Version: 4.7.1
PHP Version: 7.2.8
Operating System: Linux
GZIP: Enabled
SQL Driver Version: MySQL 5.6.34
SQL Slave Enabled: No
SQL Total Slaves: N/A
SQL Slave Server: N/A

## phpFox version
phpFox 4.7.1

## Screenshots
This error is present only in other languages.
![7](https://user-images.githubusercontent.com/11414490/50308223-eb42a980-049a-11e9-9024-91d74a7b6ca7.jpg)

in English - everything is correct
![8](https://user-images.githubusercontent.com/11414490/50308224-ebdb4000-049a-11e9-86b4-05f767216973.jpg)

**Comment by harrison05** [comment]
I can't reproduce this issue, phrases still show correctly 
![screen shot 2018-12-21 at 11 02 08](https://user-images.githubusercontent.com/41947198/50324149-f257cf00-050f-11e9-8d8f-f176aace1400.png)
