### ISSUE TITLE
Does not show photo for music playlist

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2496]
## What happened?
A photo for a music playlist is installed and correctly displayed in the playlist itself, but it is not in the list of playlists.

## Steps to reproduce:
1. go to /music/browse/playlist/view_my-playlist/

## What is expected?
It is expected that the installed photo for the music playlist will be displayed in the list of all music playlists.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
Core Version: 4.7.1
PHP Version: 7.2.8
Operating System: Linux
GZIP: Enabled
SQL Driver Version: MySQL 5.6.34
SQL Slave Enabled: No
SQL Total Slaves: N/A
SQL Slave Server: N/A

## phpFox version
phpFox 4.7.1

## Screenshots
![10](https://user-images.githubusercontent.com/11414490/50308904-fd254c00-049c-11e9-8de4-1e8d6e2d1899.jpg)
![11](https://user-images.githubusercontent.com/11414490/50308905-fd254c00-049c-11e9-963a-806fe9f8961c.jpg)

Upon closer examination, it turned out that if you add `_square` to the address line of the image file, the image is displayed (see Figure)
Before:
`/PF.Base/file/pic/music/2018/11/b8d8a9518c5d0f977d5752f3dc45c46c_500.png`
After:
`/PF.Base/file/pic/music/2018/11/b8d8a9518c5d0f977d5752f3dc45c46c_500_square.png`

![12](https://user-images.githubusercontent.com/11414490/50309200-41fdb280-049e-11e9-93ca-9615a6b3b1f8.jpg)

**Comment by harrison05** [comment]
We will check and fix in Music App.

Thanks.

**Comment by david-phpFox** [comment]
Will fix in Music 4.6.4.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Music 4.6.4

**Comment by joblux** [comment]
The changelogs for the blog module recent just mentions : bugs fixes...cant the changelogs be more specific and detailed, it will be useful to people who modified the code...and not only for modules but all kind of upgrade..4.7.5 many changes had been missing which cause a lot of prejudice to modiffied code.
