### ISSUE TITLE
Profile views do not work properly

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2497]
## What happened?
I noticed that profile views do not work properly in the "Basic info" tab on the user's profile.
This is manifested by the fact that all the time there is a value of 1 even though I have visited this profile many times as a logged in user from different accounts, as well as many times in incognito mode as a guest. The value of the "profile views" field is always "1".
The exception is the administrator account where there are "3" views, even though I've had dozens of views of this account from many accounts, as well as as guests in incognito mode.

## Steps to reproduce:
1. Log in to several user accounts
2.  From these accounts, view the account and contents of one user (main profile, photos, videos)
3.  The user's "Profile Views" field will always show "1".
Clearing the cache does not help.

## Browsers and Devices tested
Chrome, Firefox, Edge on Windows 10

## phpFox version
4.7.1

## Screenshots
![profileviews1](https://user-images.githubusercontent.com/38014237/50319428-a41edd80-04c7-11e9-9d53-02e42e20537d.png)
![profileviews2](https://user-images.githubusercontent.com/38014237/50319429-a41edd80-04c7-11e9-93fe-e22ab6cc97f1.png)
![profileviews3](https://user-images.githubusercontent.com/38014237/50319430-a41edd80-04c7-11e9-8352-5561ccb10d37.png)

**Comment by harrison05** [comment]
This counter is working well on my site. Noticed that **Profile Views** only update if:
- Setting **Profile Tracking** is disabled
- You're logged in
- You're not the owner of that profile
- Owner of that profile doesn't turn on **Invisible Mode**

**Comment by kerstar** [comment]
I followed the guidelines you provided and I still have this problem. 
Can you check it again? 
I have a fresh installation of phpfox 4.7.1. 
This problem is 100% on my website. I provided the access data for my website in the ticket number: # 498683 (I described another issue there, which was fixed, but the data for logging in there I gave). 
Can You check it?

**Comment by spirogg** [comment]
Just wondering do you have crons setup ?

**Comment by spirogg** [comment]
i am setup as 2 admins and just now 2 new users i activate in admincp for login as user

then i logged in as other admin and viewed other registered members and they show as 1 each then I login as registered memberA and view registered member B and now it shows 2 then I login in as me admin and view memberB and now it shows as 3

did the same for registered memberA and started to count

@harrison05 

can you give us exact cron setup should be 
`curl -s https://`  
or 
`/usr/bin/curl -s https://`
or how to properly use curl for cron.php?token=w9euc9euevuhv 
- should be better docs for people to setup correctly 

also do we need 2 crons setup for phpfox site or just the one with
` cron.php?token=w9euc9euevuhv`
or do we need 
`/usr/local/bin/php /path/to/your/cron.php`
i think cron is used to count correct ?

**Comment by kerstar** [comment]
Cron is set up correctly because I added videos for testing purposes and was automatically processed as cron works.

**Comment by harrison05** [comment]
@spirogg We already added a guide for customer setup cron job at https://docs.phpfox.com/display/FOX4MAN/Setup+Cron
About profile count, we don't use cron, it simple count up when a user views another user profile.

@kerstar If this issue still appears on your site, you can submit a ticket, we will check directly because we can't reproduce it on our side.
