### ISSUE TITLE
Browse male/female does not work

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2498]
## What happened?
browse male / female search does not work.

## Steps to reproduce:
1. browse
2. goto to 3 dots.
3. click on male/female

https://v4.phpfox.com/user/browse/?search%5Bfrom%5D=&search%5Bto%5D=&search%5Bcountry%5D=&null=1&search%5Bcity%5D=&search%5Bzip%5D=&custom%5B1%5D=&search%5Bgender%5D=1&custom%5B1%5D=&custom%5B2%5D=&search%5Bsort%5D=u.last_login&search%5Bsort_by%5D=DESC&search%5Bsubmit%5D=

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1

...

## Screenshots

**Comment by kerstar** [comment]
I have the same issue on my site ...

**Comment by david-phpFox** [comment]
Hi all,

We has seen this issue, and it will be fixed in Core 4.7.2. We will release it in next week.

Thanks.

**Comment by kerstar** [comment]
Great news! Thank you David!

**Comment by david-phpFox** [comment]
Hi all,

We are ready to release 4.7.2 but we have to release it after the holiday to better support when there is a problem.

Thanks.

**Comment by kerstar** [comment]
Hi David,

Sure, thanks for the information!

**Comment by david-phpFox** [comment]
Released Core 4.7.2
