### ISSUE TITLE
membership pkg when logged out vs logged in no buttons to select ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2499]
----------------------------------------

## What happened?
... 
- when you are logged out and view membership pkg there are no buttons to select
- you have to go to main page to sign up from there again.

- also when compare pkg when logged out there is no buttons to select
- you again have to go to main site to signup again

## Steps to reproduce:
1. be logged out and go to signup page click link that says CLICK HERE to learn more about our memberships
- 
![learn about membership](https://user-images.githubusercontent.com/17736688/50378699-eba78580-05fd-11e9-877f-a278a4538ef4.PNG)

2. then you see memberships with buttons to select and link under it says: Compare Subscription packages ( click that link)

- 
![compare sub pkgs](https://user-images.githubusercontent.com/17736688/50378701-f5c98400-05fd-11e9-9755-b64170d6842a.PNG)

3. from there you get redirected to plan comparison full page with no buttons to select

- 
![plan comparison when logged out](https://user-images.githubusercontent.com/17736688/50378706-011caf80-05fe-11e9-8386-65e861711d7e.PNG)

4. users also have option to click on Membership packages link and that also has no buttons to select

- ![link to vew](https://user-images.githubusercontent.com/17736688/50378683-8f446600-05fd-11e9-9628-7d00ee70de75.PNG)

- 
![membership pkg when logged out](https://user-images.githubusercontent.com/17736688/50378713-0f6acb80-05fe-11e9-9c91-7223671acfcc.PNG)

## What is expected?
...  

- I would think the same look and feel should be when logged out or logged in 

- when you view membership or compare Pkg you should be able to see buttons to select that plan - pkg 

- 
![membership pkg when logged in](https://user-images.githubusercontent.com/17736688/50378716-201b4180-05fe-11e9-9ea0-d440fe06f90a.PNG)
![plan comparison when logged in](https://user-images.githubusercontent.com/17736688/50378717-201b4180-05fe-11e9-89de-5eb6559067ad.PNG)

- then you get redirected to sign up page and that selection is chosen and user continues to signup!

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## Server information
(Example: CentOS 7, php 7.1 apache)

...  centos 7

## phpFox version
(Example: phpFox 4.6.0)

...4.7.1

## Screenshots
...  

- we need to be able to have buttons to select when your logged out.
- when user select that button they will redirect user to the main signup page with that (option) selected and new user can continue to signup!

- **Will be so much easier for users to signup - no confusion**

- **less likely to lose new users from being confused and just click off the page and go somewhere else because they say to much back n forth clicking **

- **Here are photos below**

- **when logged out** - here are photos that have **NO buttons to select**

- ![membership pkg when logged out](https://user-images.githubusercontent.com/17736688/50378571-fca2c780-05fa-11e9-96fd-c34395c38cb8.PNG)
- ![plan comparison when logged out](https://user-images.githubusercontent.com/17736688/50378572-fca2c780-05fa-11e9-881c-48eab1578d4a.PNG)

- **when logged in** - here are photos that **Have buttons to select**

- ![membership pkg when logged in](https://user-images.githubusercontent.com/17736688/50378589-41c6f980-05fb-11e9-8ee6-b6e2bb366c84.PNG)
- ![plan comparison when logged in](https://user-images.githubusercontent.com/17736688/50378590-425f9000-05fb-11e9-80f2-55109af12e44.PNG)

**Comment by harrison05** [comment]
It's working as our design. Your request should be an improvement, we will consider and improve it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Subscription 4.6.2
