### ISSUE TITLE
Trends just show numbered link

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2500]
Trends show numbers. In this case just a post to a post in the market place.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1

...

## Screenshots
![screenshot](https://user-images.githubusercontent.com/19594886/50383518-5a7af200-0683-11e9-96f8-a57251048a0a.png)

**Comment by harrison05** [comment]
This block show number because have an item which added a hashtag with this number. You can click on it and view that item.

Regards.

**Comment by prepperz** [comment]
This makes no sense if it's working as designed. Shouldn't the trends be certain words or hash tag or something instead of nonsensical numbered links?

**Comment by harrison05** [comment]
Trends block gets hashtag users added in their items. So, it doesn't control this hashtag is a number or not. 
Example: I posted a blog and add hashtag **#2018**, this hashtag will show on Trends block, we don't prevent it.

Regards.

**Comment by prepperz** [comment]
Thanks for clarifying. Looks like someone posted a market placing listing with a number hashtag. I see other worded hash tags now..
