### ISSUE TITLE
Message always toward bottom instead of top

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2501]
## What happened?
Message always shows at bottom instead of top, so users have to scroll even if empty.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1

...

## Screenshots
![screenshot](https://user-images.githubusercontent.com/19594886/50383781-41287480-0688-11e9-920b-612bfcec6fa5.png)

**Comment by harrison05** [comment]
The newest messages always show at bottom of conversation, so what's your issue? I don't understand.

**Comment by prepperz** [comment]
![screenshot](https://user-images.githubusercontent.com/19594886/50393253-db3cfb00-0722-11e9-8ddc-4c7f7bf66cf3.png)

Even when there is no message or just you still have to scroll down which becomes really annoying.

**Comment by harrison05** [comment]
We will check and fix it.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Messages App 4.7.2
