### ISSUE TITLE
Top portion of message is always offscreen in view all messages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2502]
## Steps to reproduce:
1. Click on message > view all messages
2. Now click on any message

## What is expected?
Top portion of message is displayed off screen

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1, Material theme

...

## Screenshots

**Comment by harrison05** [comment]
This page is working as design. Your expected is so confused. 
Could you give us more information?

**Comment by prepperz** [comment]
The problem occurs for sites that don't use instant messenger. Not all site use the node.js instant messanger or is instant supposed to be default now?

Anyhow this is what I was referring to https://v4.phpfox.com/index.php/mail/
Basically when you click on a message the first paragraph is off the screen to the top so you cannot see it and would need to scroll up even if it's just 1 line.

**Comment by harrison05** [comment]
Can you take a screenshot? When clicking on a message from the left side, it only loads 10 latest messages first, so you have to scroll up to load older.

Regards.

**Comment by prepperz** [comment]
![screenshot-1](https://user-images.githubusercontent.com/19594886/50414220-50bbd080-07e2-11e9-95f7-7208bb978882.png)


![screenshot](https://user-images.githubusercontent.com/19594886/50414233-5fa28300-07e2-11e9-9098-490603f7dac7.png)

**Comment by harrison05** [comment]
I got this bug. We will check and fix in Message App.

**Comment by david-phpFox** [comment]
Will fix in Messages App 4.7.2

**Comment by david-phpFox** [comment]
Fixed in Messages App 4.7.2
