### ISSUE TITLE
Registration recaptcha cut-off still not fixed.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2503]
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2441

**Comment by spirogg** [comment]
4.7.1. desktop and Android mobile works correct for me @prepperz 

But it's a clean install not an upgrade from 4.7.0

**Comment by harrison05** [comment]
Do you upgrade to the newest version 4.7.1?

**Comment by Flirtnet** [comment]
Still does not work for me. I have an upgrade not new install. I think the captcha app needs an update

**Comment by prepperz** [comment]
@harrison05 yes, upgrade.

**Comment by harrison05** [comment]
We checked package 4.7.1 on Client Area, this build was contained source codes to fix this bug.
Please go to your Client Area and download the newest package v4.7.1, upload to your site, then rebuild core theme, clear cache.

Regards.

**Comment by prepperz** [comment]
Issue still persist after uploading new package

**Comment by harrison05** [comment]
@prepperz  You can check our demo site: https://v4-bootstrap.phpfox.com/, it's working well.
Do you have any custom on the registration form? If not, you can submit a ticket.

Regards.

**Comment by prepperz** [comment]
Nope. no custom stuff.

**Comment by harrison05** [comment]
> Nope. no custom stuff.

After checked your site via ticket, we found that issue still appears because you're using reCAPTCHA App on the registration form. This bug doesn't fix on this app. BTW, we don't support this app anymore.

You should use Captcha app (must enable setting "Captcha on Registration") instead reCAPTCHA to be fixed this issue now.

Regards.

**Comment by Flirtnet** [comment]
Ok I guess I am having the same problem. Because it does not appear on registration either.

**Comment by harrison05** [comment]
I just edited my comment after checked with my team. Please follow.

**Comment by prepperz** [comment]
After some clarification issue is resolved.  (*Note to phpfox: make a note of this for users)

For those that are using the recapcha app, they no longer support it and you should now uninstall it and use the "captcha" app instead and then activate in the registration settings.
