### ISSUE TITLE
Pages/groups choose from photos as cover, but no option to make cover

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2504]
## What happened?
Pages/groups choose from photo for cover, after selecting a photo no option exist to make it a cover.

## Steps to reproduce:
1. From any page, click on choose from photo icon
2. select a photo
3. 

## What is expected?
...can't go any further

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1, Material theme

...

## Screenshots

**Comment by harrison05** [comment]
You must go to photo detail and select option in the drop-down:
![screen shot 2018-12-24 at 10 43 25](https://user-images.githubusercontent.com/41947198/50390347-d6029f00-0768-11e9-83f0-f85128a4a05f.png)

**Comment by prepperz** [comment]
This definitely needs to be better. There's a major disconnect and not very intuitive (not user firendly) at all. That extra 3 steps isn't necessary and will confuse a lot of people as it did me.  They should just be able to select which photo to set to pages cover or make profile cover from right after selecting "choose from photo" and then the options should be available from the gear icon of each photo or right on the photo to make it obvious since the intention was to choose a photo to set as cover. This will avoid a lot of confusion, make it more fluid  and save 3 unnecessary steps.

**Comment by harrison05** [comment]
You can add a new feature request for this case, it sounds good. Then, our team will review it and inform you later.

Thanks - Merry Christmas.

**Comment by prepperz** [comment]
Likewise. Will do. Thanx.

**Comment by harrison05** [comment]
I saw the new feature request. So, I will close this topic. 

Thanks.
