### ISSUE TITLE
Another place with displaying a bad language phrase

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2505]
## What happened?
In the github ticket # 2492 I described the problem of displaying the wrong language for some phrases. The problem has been fixed and you mentioned that you will introduce the patch in phpfox 4.7.2 this week.

Your advice has helped me and in places where there was a issue now is the correct language, but now I found another place where the same problem appeared.

On the "www.examplesite.com/exampleuser/groups/" page, the words "member" and "members" are displayed in the wrong language.
In the attachment I am sending a screenshot of the issue shown.

Can you fix this problem in phpfox 4.7.2?
## Browsers and Devices tested
Chrome, Firefox, Edge on Windows 10

## phpFox version
4.7.1

...

## Screenshots
![memberslike8](https://user-images.githubusercontent.com/38014237/50408430-6208db00-07ea-11e9-8055-d5f515b4484d.png)

**Comment by kerstar** [comment]
At www.examplesite.com/pages/ the phrase "Like" in the number of people who likes a given page is displayed in English instead of in Polish, despite the translation of this phrase.
![pageslike1](https://user-images.githubusercontent.com/38014237/50408675-c4fb7180-07ec-11e9-8495-aaf1eec5bead.png)

**Comment by kerstar** [comment]
Another update:

Go to https://www.examplesite.com/user/browse/ and try to search for a user who does not meet the search requirements.

A page appears with the notification "No members found." In English, although this phrase has been translated into Polish.
![nomembersfoundphrase](https://user-images.githubusercontent.com/38014237/50409533-ab115d00-07f3-11e9-9dba-936303c476ce.png)

**Comment by harrison05** [comment]
About issue "members" and "member" don't translate might cause you don't add translate for phrases "groups_total_members" and "groups_total_member". 
Please go to AdminCP > Globalization > Phrases and search for those var_name (Click on "View More Search Options" in Phrases page to see this option), then update.

The same case with "No members found", please check translate.

Regards.

**Comment by kerstar** [comment]
Thanks for the tips. I did as you wrote and now it works!

**Comment by harrison05** [comment]
Everything seems ok, I guess I can close this topic now.

Regards.
