### ISSUE TITLE
Translated phrases can not be saved in custom fields if the field was empty

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2506]
## What happened?
In Admin CP, I added custom fields and by accident in one of the check boxes I forgot to enter the translated phrase into Polish. The field is empty, and when I try to complete and save it, it does not save and is still empty. 
I tried to clear the cache, but it did not help.

In the attachment I am sending screenshots with the bug shown.
You can check it on my site and AdminCP (I've provided details to the page in the ticket number: # 365665)

Can you fix it in phpfox 4.7.2?

## Steps to reproduce:
1.  Go to AdminCP -> Members -> Custom fields
2.  Edit Custom Field
3.  Try to fill in the empty phrase field for the Polish language
4.  Try to save 
5.  The entered phrase has not been saved.

## Browsers and Devices tested
Chrome, Firefox, Edge on Windows 10

## phpFox version
4.7.1

...

## Screenshots
![customfieldsphrase](https://user-images.githubusercontent.com/38014237/50410020-bf0a8e00-07f6-11e9-891b-bfd308187502.png)
![customfieldsphrase2](https://user-images.githubusercontent.com/38014237/50410021-bf0a8e00-07f6-11e9-8faa-7e5f043945ee.png)

**Comment by harrison05** [comment]
We will check and fix this bug.

Thanks.

**Comment by kerstar** [comment]
No problem. You fix it in phpfox 4.7.2?

**Comment by david-phpFox** [comment]
We will fix it in Core 4.7.2.

**Comment by kerstar** [comment]
OK, Thank You David.

**Comment by david-phpFox** [comment]
Released Core 4.7.2
