### ISSUE TITLE
I can't change the order of custom fields on the user's profile

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2507]
## What happened?
If I try to change the order position of custom fields in AminCP -> Members -> Custom fields -> Manage custom fields and then click on the "Update order" button and clear the cache, then the position of custom fields change does not take place in user profile.

The problem may arise from the fact that one custom field has assigned the basic (default) location of the "Main Section" and the second field is assigned to the "Basic Information" location, but if I assign the second field to the "Main Section" to display on the main page the user's profile above the first or below the first field, then this field is displayed in the "Basic Info Info" tab.

Can you fix it in phpfox 4.7.2?
You can check it on my website. I have provided the data to the page in the ticket number: #365665 with a different issue.

## Steps to reproduce:
1.  AminCP -> Members -> Custom fields -> Manage custom fields
2.  Try to change the order of the custom fields and click "Update Order" button.
3.  Clear the cache
4.  Entry in AminCP -> Members -> Custom fields -> Manage custom fields has been saved and displayed correctly, but the order has not changed on the user profile.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

## phpFox version
4.7.1

## Screenshots
![customfieldschangeposition](https://user-images.githubusercontent.com/38014237/50410475-76080900-07f9-11e9-9fe1-f5cde519ae60.png)
![customfieldschangeposition2](https://user-images.githubusercontent.com/38014237/50410476-76080900-07f9-11e9-9fe7-c651783292f6.png)

**Comment by david-phpFox** [comment]
Hi kerstar, 
Core is supporting order for all custom fields but not support "about me" field when show data, because it is 1 block in manage blocks, you can move it to anywhere. Please try add more fields and check them.
