### ISSUE TITLE
Sharing main url on FB only shows description, but no image

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2508]
## What happened?
No image when sharing main url on facebook social media

## Steps to reproduce:
1. goto facebook and share the link: https://v4.phpfox.com/

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

## Screenshots

**Comment by david-phpFox** [comment]
Improved in Core 4.7.5
