### ISSUE TITLE
Can't disable invite people via Email in Pages and Groups

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2509]
## What's happened?
Can't disable invite people via Email in Pages and Groups

Can I turn it off somehow? I know that this is probably not a bug, but it is a big oversight, because it should be possible to disable people from being invited by e-mail in Pages and Groups for Pages and Groups administrators.

No possibility to disable turn off inviting people by email can lead to spamming and uncontrolled inviting people on a massive scale by administrators of Pages and Groups.

The page owner should be able to disable this invite function for Pages and Groups administrators.

Can you tell me how can I turn it off?
Can you tell me which piece of code and what file should I delete (or comment on) so that can not invite people for Pages and Groups administrators?
I will be very grateful.

Regards and I wish you a pleasant Wednesday.

## Browsers and Devices tested
Chrome, Firefox, Edge on Windows 10

## phpFox version
4.7.1
...

## Screenshots
![inviteemail1](https://user-images.githubusercontent.com/38014237/50430073-2e997f80-08c2-11e9-870d-934dc90dc36b.png)
![inviteemail2](https://user-images.githubusercontent.com/38014237/50430074-2e997f80-08c2-11e9-9700-9c13ca8eab60.png)

**Comment by harrison05** [comment]
Yes. Currently, we don't support this feature. If you want this, you can add a new feature request, we will review it. Btw, if you want hotfix on your site, you have to custom some codes.

Example for Groups: 
You have to edit file: **PF.Site/Apps/core-groups/views/controller/add.html.php** and delete the element: 
```html
<div class="form-group invite-friend-by-email">....</div>
```
Then, clear cache.
The same solution with Pages.

Regards.
