### ISSUE TITLE
Activity Points Sent Transaction history still shows profile ID not fixed in 4.7.4

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2511]
reference: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2451

**Comment by spirogg** [comment]
@prepperz 

Profile User ID Connection
Set to Yes if you would like to have user profiles connected via their user ID#. Set to No if you would like to have user profiles connected via their user name. 

Note if you connect via their user ID# you will allow your members the ability to use non-supported characters which are not allowed if connecting a profile with their user name. 

Warning: This action cannot be reversed. 
This setting may lock users out if you force log in by their user names 

----------------------------------------------
Do you have this set to user id. Or username. 

I have it in username and it shows username when transfer points. 
- but I don't try it with user ID.

**Comment by prepperz** [comment]
@spirogg it's set to "no"

**Comment by harrison05** [comment]
We just fixed this bug on new transactions, you can check with new one.
