### ISSUE TITLE
Activity point price invalid if less than $1.00

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2512]
## What happened?
Activity point price invalid if less than $1.00

## Steps to reproduce:
1. Make a package for less than $1.00 

## What is expected?
invalid

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

## Screenshots

**Comment by spirogg** [comment]
Thanks for reminder 
@harrison05
Also subscription pkg has the same thing. You can't sell for 0.99 cents or even 1.99 it rounds up or it just simply won't allow it.

Nice find in the activity @prepperz 

Might be in marketplace and other areas also?
Can someone from @phpfox check  all areas and fix it. 

Thanks @prepperz your on top of it - all  over it. :)

**Comment by harrison05** [comment]
@spirogg @prepperz Yes, they are bugs on Activity Points and Subscriptions. We will check and fix.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.2 and Subscription 4.6.2
