### ISSUE TITLE
Weird activity pack showing up in account setting payment method ?

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2513]
## What happened?
Weird activity pack showing up in account setting payment method

## Steps to reproduce:
1. Make some activity points package
2. maybe do a test purchase / not sure.
3. https://xxxx,com/index.php/user/setting/

## What is expected?
see screen shot. What is it?

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

## Screenshots
![screenshot](https://user-images.githubusercontent.com/19594886/50497844-8098ed00-0a09-11e9-9ad5-669c437041af.png)

**Comment by harrison05** [comment]
This is description of Paypal gateway, Admin controls this text at **AdminCP > Globalization > Payment Gateways**, see my screenshot:
![screen shot 2018-12-28 at 09 50 12](https://user-images.githubusercontent.com/41947198/50500786-183c2100-0a86-11e9-9ec6-b7b03a811c11.png)

**Comment by prepperz** [comment]
ah ok I see it now.
