### ISSUE TITLE
Page Not found when No subscription package is created

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2514]
## What happened?
When no subscription package is available, it says page not found.

## Steps to reproduce:
1. click on your personal avatar down arrow > membership

## What is expected?
Shows page not foud.
https://xxxx.com/index.php/subscribe/

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

## Screenshots
![screenshot](https://user-images.githubusercontent.com/19594886/50498129-1d5c8a00-0a0c-11e9-8860-f0070e57a2cf.png)

**Comment by david-phpFox** [comment]
We has fixed it in Subscription 4.6.2. It will be released soon.

**Comment by david-phpFox** [comment]
Fixed in Subscription 4.6.2.
