### ISSUE TITLE
Search is terrible. Does not include blog content.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2515]
## What happened?
Search does not include content which make it kind of useless. Is this the same for every other section of the web site? If it is then the search systems needs a massive improvement,

## Steps to reproduce:
Goto main blog and search for any word in the contents of a blog.

## What is expected?
No result.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
Blog still supported search with blog's content. But in some cases, the search function works incorrect and return wrong results. 
We will check it again.

Thanks.

**Comment by cyristvirus** [comment]
Can agree to this. The search function is worthless almost if it does not search content. It searches titles it seems.

**Comment by david-phpFox** [comment]
Fixed in Blog 4.6.5
