### ISSUE TITLE
On mobile, Home main text doesn't properly wrap and it's centered. Looks terrible.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2516]
## What happened?
On mobile, Home main text doesn't properly wrap and it's centered. Looks terrible. 
Simiar to https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2465 but a lot worse because it's centerned on mobile.
## Steps to reproduce:
1. browse home page with mobile chrome browser.

## What is expected?
Word wrap breaks words and is centered.

## Browsers and Devices tested
Chrome on android

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
It might have the same root cause with #2465, we fixed it in the next version 4.7.2

**Comment by david-phpFox** [comment]
Released Core 4.7.2
