### ISSUE TITLE
when adding blocks we can no longer choose the block and automatic selected for you

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2518]
Can you please fix this one please, was good feature just select block and its set for you. doesn't work any more
----------------------------------------

## What's happened?
...

## Steps to reproduce:
1. go to admincp> Appearance> Blocks
2. create new block or choose existing one and choose > Placement View Sample Layout
3. here you can view and before could select what block and it would change the block automatically

NOW doesn;t work any longer you click on the block to choose and it doesnt change in selector

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
...   tested on chrome

## Server information
(Example: CentOS 7, php 7.1 apache)
CentOS 7  7.2
...

## phpFox version
(Example: phpFox 4.6.0)

...
4.7.1
## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/50509475-96c79d00-0a4b-11e9-94c8-856abcffc0ec.PNG)

**Comment by harrison05** [comment]
We fixed this issue in v4.7.2. Please check again after we released this version.

Regards.

**Comment by david-phpFox** [comment]
Released Core 4.7.2
