### ISSUE TITLE
pagination in admin cp in member search results missing first / last (beginning / ending)

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2519]
## What happened?
missing first / last (beginning / ending)
Cannot go to the end or beginning

## Steps to reproduce:
1. browse from admin cp
2. try to go to end of pagination. You can't
3. 

## What is expected?
missing beginning / ending in pagination

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

## Screenshots
![screenshot](https://user-images.githubusercontent.com/19594886/50527771-6833db80-0ab8-11e9-872f-7f173e862e25.png)

**Comment by harrison05** [comment]
We don't support first/last in pagination for AdminCP in the current version. 
But we will check and implement it in v4.7.3.

Thanks.
