### ISSUE TITLE
when setup subscription pkg's doesnt work correctly and is stuck even after admin makes changes to usergroup ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2520]
----------------------------------------

## What's happened?
...

## Steps to reproduce:

 I setup 2 pkg's - 1-free pkg and 1 paid for Pro pkg= 2.99
made active for users to signup and select pkg 

i signed up with paid for 2.99, but did not pay, then went to admincp members and approved user to be pro user, then I tried to login as pro user and it said pay with paypal.

so then I logged in as admin again and changed to the pro user to registered user, and then tried to login again and still show please pay with paypal. even though its reg registered user. I cleared cache cleared all cache removed files not needed and rebuild . still stuck on pro user even though in admincp under members list it shows this user as registered user.

I also tried to click on membership from this user i created and then click on packages to view all pkg's and to possible downgrade to free pkg - but free pkg doesn't show to downgrade it only shows pay with paypal. 

so cant a user that's on paid pkg downgrade first of all ?
second why wont it allow the admin to change that user to a registered user or Pro user for free. admin should be able to override subscription pkgs ??

so now I'm stuck as an admin that cant make this user Free registered user.

so if a user decides after signing up to not be paid user and wants to go back to free pkg, it not possible and not even I as admin can make them free registered user ??

this is a bug and or not made properly

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

4.7.1

## Screenshots
...

**Comment by spirogg** [comment]
Even when i turn off the paid pkg in admincp it still stuck and asking user to pay for subscription

**Comment by spirogg** [comment]
- here are photos 

- i tried with button on and off and still same issue
- ![capture](https://user-images.githubusercontent.com/17736688/50529691-6704ad80-0abc-11e9-9c58-fd42196f49df.PNG)

- ![capture](https://user-images.githubusercontent.com/17736688/50529914-1726e600-0abe-11e9-827a-fe602da9f183.PNG)

- ![capture1](https://user-images.githubusercontent.com/17736688/50529903-037b7f80-0abe-11e9-93dc-6f3a1ce01c6c.PNG)

- ![capture5](https://user-images.githubusercontent.com/17736688/50529694-6e2bbb80-0abc-11e9-8c2f-f5695db07869.PNG)

- ![capture1](https://user-images.githubusercontent.com/17736688/50529698-71bf4280-0abc-11e9-89eb-6135d26fa597.PNG)

- ![capture3](https://user-images.githubusercontent.com/17736688/50529701-7552c980-0abc-11e9-900d-9285fe1e733a.PNG)

- ![capture4](https://user-images.githubusercontent.com/17736688/50529706-78e65080-0abc-11e9-8e9d-a9be420fcd96.PNG)

- ![capture2](https://user-images.githubusercontent.com/17736688/50529709-7edc3180-0abc-11e9-8a5c-77f8610c39a0.PNG)

**Comment by spirogg** [comment]
if you want I can send a request to phpfox support for you to look at ?

**Comment by spirogg** [comment]
also when setting up pkg, it says pro user on success and on fail it reverts to registered user if they dont pay

so this is not working either

![capture1](https://user-images.githubusercontent.com/17736688/50529888-ee9eec00-0abd-11e9-8b1f-68839f46e5e8.PNG)

**Comment by kerstar** [comment]
You should fix it in 4.7.2 version...

**Comment by harrison05** [comment]
@spirogg Thank for your report, we will check this issue.
@kerstar might a bug of Subscription App and it should be fixed on it, not in v4.7.2. We will release a new version for this app later.

**Comment by david-phpFox** [comment]
Fixed in Subscription 4.6.2.
