### ISSUE TITLE
URL in messages does not open in a new wndow

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2521]
## What happened?
Url in messages open in same windows instead of new one.

## Steps to reproduce:
1. Share a url when writing a private message
2. Click on url
3. 

## What is expected?
opens in same windows and takes users away from site

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

**Comment by david-phpFox** [comment]
Will fix in Messages App 4.7.3

**Comment by david-phpFox** [comment]
Fixed in Messages App 4.7.3
