### ISSUE TITLE
Pages avatar/thumbnail is resized even if nothing is touched

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2522]
## What happened?
Page avatar is resized even when nothing is touched. This may apply everywhere else such as groups and personal profiles.

## Steps to reproduce:
1.  Goto to any pages > manage > photo > edit thumbnail
2. save

## What is expected?
Avatar is resized

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
When you click Save, our process will crop a new image from old image and update for Page, it doesn't detect image was changed or not. So if you don't have any change, you shouldn't click save.
