### ISSUE TITLE
External links does not open in a new window

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2524]
## What happened?
Apparently externals links are not opening in a new window throughout the entire site by defualt.

## Steps to reproduce:
post an external link anywhere and then click on it.

## What is expected?
It takes the user away and leaves the site.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Currently, we don't have any option to open external link in new tab. I think it is necessary
Let we discuss this case and inform you if have any update. 

Thanks
