### ISSUE TITLE
Cannot create a pages  sub category within a newly created empty  category

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2525]
## What happened?
...

## Steps to reproduce:
1. Create a pages category "Testcat"
2. Create a new category and try to select "Testcat". You can't it's not on the list.
3. Once you make a page in the "Testcat" categoy then it shows in the main category list.

might also affect groups

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Might be related to Cached. We will check and fix it.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in 4.7.2
