### ISSUE TITLE
Cannot reassign category to subcategory after it's created and saved

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2526]
## What happened?
Cannot switch category to subcategory after it's created and saved

## Steps to reproduce:
1. create category "dog" and save it
2. Edit category "dog"

## What is expected?
Option for sub category no longer available

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.1 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Yes, it is working as our business rule, when you edit a parent Category, you can't change it becomes a child of another category.

**Comment by prepperz** [comment]
It would be very useful to allow it to reassign as subcategory. This will save a lot of work and time of having to delete category, creating a new category as a subcategory and then re-categorizing all the associated pages. That can be a nightmare.

 A small mistake can delete all the pages associated with the category. However, if it can simply be reassigned as a subcat, the chance of unintentional deletion is almost zero.

Also allow for 2 levels deep instead of the current 1 level deep make it very useful and greater flexibility for organization and keeping things clean.

**Comment by harrison05** [comment]
When you delete a parent category, you can select other one and move all sub-categories and pages to it. I don't think it cost much time to do that. 
Currently, we don't have any plan to improve this rule.
