### ISSUE TITLE
sitewide block 3 or 10 when refresh page it drops below not staying in place

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2527]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... i added your advertisement ad to block 3 and also tried block 10
it shows properly when you first go to page but when if you refresh page it drop below the page see photos. doesn't do it on all but certain pages it does it

## Steps to reproduce:
1. create an advertisement in blocks choose block 3 or block 10
2. add your code for the ad banner
3. choose sitewide and then go to home page when logged out. see ad should be displayed properly on right side, then if you refresh it drops down below

## What's expected?
... should stay in place even if you refresh page

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...   latest chrome browser edge browser windows 10 latest

## Server information
(Example: CentOS 7, php 7.1 apache)

...
centos 7 php 7.2
## phpFox version
(Example: phpFox 4.6.0)

...
4.7.2
## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/50669063-a7669e80-0f88-11e9-8db5-80cbec17caf0.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/50669064-a7669e80-0f88-11e9-8ab7-e655fd8d2d1e.PNG)
![capture2](https://user-images.githubusercontent.com/17736688/50669065-a7669e80-0f88-11e9-814f-97517fdf523f.PNG)
![capture3](https://user-images.githubusercontent.com/17736688/50669066-a7669e80-0f88-11e9-9104-b23bdec557e4.PNG)
![capture4](https://user-images.githubusercontent.com/17736688/50669067-a7669e80-0f88-11e9-9c56-74dc003f1ff2.PNG)
![capture5](https://user-images.githubusercontent.com/17736688/50669068-a7669e80-0f88-11e9-8e09-f755cece2cbe.PNG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/50669154-28259a80-0f89-11e9-85ac-eedc5fad8c71.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/50669155-28259a80-0f89-11e9-8d08-14d360b60a04.PNG)

**Comment by spirogg** [comment]
after you refresh page it drops below ?

**Comment by harrison05** [comment]
Did you add a new block to Site Wide at block 10 with type is **HTML Code**?

**Comment by spirogg** [comment]
@harrison05 
- yes

- here is my photo of settings 

- ![capture](https://user-images.githubusercontent.com/17736688/50720791-787c2580-1079-11e9-82e0-79dd66512ae2.PNG)

**Comment by spirogg** [comment]
- @harrison05 here it is again,  I delete the first ad and start new no extra tags ie `<center> <br />`
- just your ad code
- and still does it


- ![capture](https://user-images.githubusercontent.com/17736688/50720849-baf23200-107a-11e9-9a7e-34a96e38bda0.PNG)

- ![capture1](https://user-images.githubusercontent.com/17736688/50720850-baf23200-107a-11e9-9a15-92b46916018e.PNG)

**Comment by spirogg** [comment]
- even block 3

- same issue

- ![capture](https://user-images.githubusercontent.com/17736688/50720888-7e730600-107b-11e9-83d9-c931b6c5390c.PNG)
- ![capture1](https://user-images.githubusercontent.com/17736688/50720889-7e730600-107b-11e9-9420-b3652d484a9a.PNG)

**Comment by harrison05** [comment]
Ok, I got it. This is a bug of Core, we will check and fix it.

Thanks.
