### ISSUE TITLE
Clicking pages subcategories menu collapses and re-opens the entire menus on the left

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2528]
## What happened?
...pages menu collapses and re-opens when subcategory is clicked on.

## Steps to reproduce:
1. click on the pages category menu on the left side with some subcategories
2. click on the the subcategory

## What is expected?
The entire menu structure collapses and re-opens every time. If the category is further down, it does not maintain its position. It will always show the beginning of the menu every time.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
When you click on sub-categories, browser redirects to another page, so javascript function on Category block will reload and it takes a short time to init and re-open again.

**Comment by prepperz** [comment]
Ya that ruins the whole experience. Kind of like a bomb exploding every time it's clicked.
