### ISSUE TITLE
Changes in pages categories (adding, deleting etc...) doesn't take immediate effect until cache is cleared

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2529]
## What happened?
Adding categories or deleting doesn't take immediate effect

## Steps to reproduce:
1. Create or delete a category
2. try to change the category of a page to it's not there til after a long delay or until cleared

## What is expected?
new or deleted categories are delayed 

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Same issue with #2525

**Comment by david-phpFox** [comment]
Fixed in Pages/Groups 4.7.2
