### ISSUE TITLE
Deleting/creating a pages subcategory take you out of the subcategory section

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2530]
## What happened?
It takes 4 steps to delete a subcategory. It is deleted, it takes you out of the subcategory and then you'll need to look for the main category and then go into the subcategories to locate it and delete again.

This is like moving 4 steps backwards for every 1 step forward. It's time consuming and extremely annoying.

## Steps to reproduce:
1. goto to any pages category > then subcategory
2. Now delete the subcategory

## What is expected?
It should stay in the in the section being worked on but it does not.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
After you confirmed to delete a sub-category, it's deleted immediately. 
Why you have to look for the main category and delete again?

Regards.

**Comment by harrison05** [comment]
Ah, I understand, you want to stay at sub-categories page after deleted a sub, right?

**Comment by prepperz** [comment]
correct

**Comment by harrison05** [comment]
Ok, we will discuss to improve it because current workflow when deleting a sub-category is applied for almost apps.

**Comment by david-phpFox** [comment]
I have improved in 4.7.2
