### ISSUE TITLE
No date as to when pages/groups are created

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2533]
## What happened?
Really surprised that there are no date as to when pages are created.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Yes, we save creation date of Page but don't show it anywhere.

**Comment by prepperz** [comment]
It would be helpful to have the option to display it as it becomes a chronological record in time.

**Comment by spirogg** [comment]
Yes. Option to turn on off this feature if you make it a feature. Would be nice.

**Comment by harrison05** [comment]
Ok, we will review your request. 

Regards.

**Comment by david-phpFox** [comment]
Has supported in Pages/Groups 4.7.3
