### ISSUE TITLE
No Centering button on ckeditor

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2537]
## What happened?
No Centering button on ckeditor to center text or other things.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
To allow this feature, you can go to **AdminCP > Apps > CKEditor** and change CKEditor package to **Full Package** in Settings tab
![screen shot 2019-01-07 at 15 42 08](https://user-images.githubusercontent.com/41947198/50757727-ce77e580-1292-11e9-9465-984f8a8f9193.png)

**Comment by prepperz** [comment]
Is there a way to allow membership levels to access the standard package and the site admin the full package?  ,,, various custom package for various membership level?

**Comment by harrison05** [comment]
No, isn't. With the current version of CKEditor, you can't do that.

Regards.
