### ISSUE TITLE
Cannot edit your post after posting on someone's profile

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2539]
## What happened?
Cannot edit a post on friends profile

## Steps to reproduce:
1. Go make a post on a profile
2. Now try to edit it
3. 

## What is expected?
Cannot edit the post

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
I can't reproduce this issue. We still supported Edit/Delete your post on friend's wall.

Regards.

**Comment by prepperz** [comment]
Weird, I tested it again and it works fine.
