### ISSUE TITLE
Editing the privacy policy kills any previous format (and probably any previous page).

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2540]
## What happened?
Any previous format is lost. All spaces and paragraphs. This may apply to any other page being edited.

## Steps to reproduce:
1. Edit privacy policy and save
2. 
3. 

## What is expected?
Should mess up what is previous on there, but it does.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
I try to edit Policy page in AdminCP but it's working right after saving. 
Could you give us more information?

Thanks

**Comment by harrison05** [comment]
I try to edit Policy page in AdminCP but it's working well after saving.
Could you give us more information?

Thanks

**Comment by prepperz** [comment]
Might just be a weird anomaly, but it basically stripped all spaces from paragraphs so the entire thing becomes one super long sentence. I can no longer reproduce it. I'll repost if I come across it again.

**Comment by harrison05** [comment]
Ok, let me know if you meet it again.

Thanks
