### ISSUE TITLE
No page found when no subscription is created still not fixed 

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2541]
reference: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2514

**Comment by harrison05** [comment]
v4.7.2 seems working well on my site 
![screen shot 2019-01-09 at 10 24 25](https://user-images.githubusercontent.com/41947198/50874961-c6d25100-13f8-11e9-80f2-ea893fc5d632.png)

**Comment by prepperz** [comment]
![screenshot](https://user-images.githubusercontent.com/19594886/50875694-85f62000-1397-11e9-80fd-2a62614ae840.png)

https://v4.phpfox.com/subscribe/

**Comment by harrison05** [comment]
Oh, this is the old version on our demo. 
I just upgraded to the newest version.

Regards.
