### ISSUE TITLE
Deactivated menu gets reactivated still not fixed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2542]
reference: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2487

Steps to reproduce.

1. from menu admincp, deactivate a menu and then re-arrange menu order
2. Click on convenuent clear cache on the left and you'll see that menu is reactivated.

**Comment by harrison05** [comment]
> I checked this case, a menu auto reactivated after I upgrade its app. This might a bug of Core, we will check and fix.
> 
> Thanks.

Same my previous comment in #2487, we fixed the issue that menu auto reactivated after you upgraded an app. Please check this case first.

About this topic, referring your step to reproduce, I saw this bug, it might be related to menu cached - another bug. We will check and fix.

Thanks.
