### ISSUE TITLE
Issue with unselect custom fields in the Browse Users section

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2544]
## What's happened?
In the browse users section, if I use a search using a custom field (in this case checkbox, but the issue is also for other custom fields) , after which we want to change the parameter of the search custom field to another field or any field, after clicking on "Submit" the field that we selected is still selected. 
If I click on the reset button "and then again on "Submit"then the custom field will continue to be selected.

Can you fix this bug on my site? 
I provided the data to the website in ticket #422718.
## Steps to reproduce:
In the ticket number #422718 I showed a link to the video on YouTube, where I recorded and show how to reproduce the issue.

## Browsers and Devices tested
Chrome in Windows 10

## phpFox version
4.7.2

**Comment by harrison05** [comment]
I checked this issue. 
This is a bug of Core. We will check and fix it.

Thanks.

**Comment by kerstar** [comment]
Thank You Harrison. It's working fine now.

**Comment by harrison05** [comment]
Ya, we just hotfix on your site and it will be released in the next version of phpFox.

Thanks.

**Comment by kerstar** [comment]
Thank you once again Harrison.
