### ISSUE TITLE
when hiding profile info you just get blank area before it use to say some wording 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2545]
----------------------------------------
 

## What's happened?
...if you hide profile info it should say something about this area is Private or something like that

## Steps to reproduce:
1. make profile info hide from other users - 
2. then logout and view profile info
3. should say Private or User info Private (something rather than nothing)

## What's expected?
@harrison05
...should say Private or User info Private (something rather than nothing)

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome edge

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php 7.2

## phpFox version
(Example: phpFox 4.6.0)

...4.7.2

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/51066387-6fd2a480-15cf-11e9-9166-60bd4e202072.PNG)

**Comment by harrison05** [comment]
Did you disable this privacy setting? See my screenshot
![screen shot 2019-01-14 at 09 52 03](https://user-images.githubusercontent.com/41947198/51094739-18585280-17e2-11e9-8ed3-f6553183ef22.png)

**Comment by spirogg** [comment]
@harrison05 

Yes. 

The issue is we use to have varname
" this profile is Private". Now it doesn't say anything so it look as if it is broken. ?

**Comment by harrison05** [comment]
Ok, we will check and fix it.
