### ISSUE TITLE
The phrase "Custom" displays in the wrong language

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2546]
## What's happened?
I am trying to translate the phrase "Custom", which is visible in the visibility settings of added posts, photos. I translated the phrase, I cleaned the cache, but the phrase "Custom" still appears in the wrong language.

Harrison, in the ticket number #771732, I gave access to my website. Can you check it and correct this issue? Thank you.
## Steps to reproduce:
1. Go to AdminCP and try translate phrase "Custom" to another language, click save and clear all caches.
2. Go to user wall and click on the selection of the visibility of adding content
3. The phrase has not been translated

## What's expected?
The phrase is displayed in the wrong language.

## Browsers and Devices tested
Chrome on Windows 10

## phpFox version
4.7.2

...

## Screenshots
![custom1](https://user-images.githubusercontent.com/38014237/51080972-68052400-16e5-11e9-9762-4f6ad3aa056a.png)
![custom2](https://user-images.githubusercontent.com/38014237/51080974-6c314180-16e5-11e9-8dd6-965835853246.png)

**Comment by david-phpFox** [comment]
Hi Kerstar,

Please search the phrase "custom_span_click_to_edit_span" and translate it.

Best Regards,
David phpFox

**Comment by kerstar** [comment]
Hi David.

Thanks for the help. Now it is working! 
You can close this application.
