### ISSUE TITLE
Invite app

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#2548]
## What's happened?
Tried to send Invite to a person that is not a member

## Steps to reproduce:
1. go to invite page
2. enter email
3. click send

## What's expected?
To sent invite

## Browsers and Devices tested
Chrome

## Server information
CentOS 7, php 7.3 apache, Nginx)

## phpFox version
(Example: phpFox 4.7.2)

**Comment by harrison05** [comment]
I can't reproduce it on my side. Invite still sent to emails:
![screen shot 2019-01-14 at 10 19 29](https://user-images.githubusercontent.com/41947198/51095258-17292480-17e6-11e9-81e4-88dbd995ea18.png)

Try to test your email setup in AdminCP is working or not.

Regards.

**Comment by djafrika** [comment]
Setup is fine. Test passes. Tested smtp and mail method. Every other emails are being sent except invite...

**Comment by harrison05** [comment]
If the issue still occurs in your site, you should create a ticket in the client area, our team will help you check directly.

Regards.
