### ISSUE TITLE
When pages admin shares a photo post, email notice says Site admin made post

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2549]
## What happened?
Email notification

Hello xx,

"Site admin  name" posted some images on page "xyz".
To see the image, follow the link below:
https://www.xxxx.com/index.php/xxxxx/

Kind Regards,

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by david-phpFox** [comment]
Fixed in 4.7.2
