### ISSUE TITLE
Doesn't properly parse when sharing links on pages status

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2551]
## What happened?
Sharing links doesn't properly parse:

## Steps to reproduce:
1. Share this link;  https://cryptonewsreview.com/breaking-binance-freezes-funds-stolen-in-cryptopia-hack/
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
I can't reproduce it, see my screenshot, everything seems ok
![screen shot 2019-01-17 at 09 28 02](https://user-images.githubusercontent.com/41947198/51291617-564fb380-1a3a-11e9-885e-711d1f86b21a.png)
![screen shot 2019-01-17 at 09 28 30](https://user-images.githubusercontent.com/41947198/51291618-564fb380-1a3a-11e9-8436-870a6516a2f5.png)

**Comment by prepperz** [comment]
That's weird, I get this on mine:

![screenshot](https://user-images.githubusercontent.com/19594886/51292794-1953d480-19da-11e9-8817-54822e756365.png)

**Comment by harrison05** [comment]
I try to test on our demo site, it is working well too
Site cryptonnewsreview.com is using Cloudflare service, this is the response from that site when your site try to fetch info from it:

> What happened?
>                 
> There is an unknown connection issue between Cloudflare and the origin web server. As a result, the web page can not be displayed.
>                  
> What can I do?
>                        
> If you are a visitor of this website:   
> Please try again in a few minutes.
>   
> If you are the owner of this website:
>   
> There is an issue between Cloudflare's cache and your origin web server. Cloudflare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team.  Please include the Ray ID (which is at the bottom of this error page). Additional troubleshooting resources.

It might an error when your site connects to that site.
