### ISSUE TITLE
Deleteing a pages status doesn't delete the feed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2552]
## What happened?
Deleting a pages status doesn't delete feed

## Steps to reproduce:
1. Share this link on pages status:  https://cryptonewsreview.com/breaking-binance-freezes-funds-stolen-in-cryptopia-hack/
2. Now delete the status
3. check main feed on site. Hit the site home link

## What is expected?
Should have deleted the feed, but it does not.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by david-phpFox** [comment]
Will be fixed in Pages 4.7.3 and Core 4.7.3

**Comment by spirogg** [comment]
@david-phpfox

When you you expect 4.7.3 Core
 to be released.. week 2 weeks just wondering. ?

**Comment by david-phpFox** [comment]
Fix in Pages 4.7.3
