### ISSUE TITLE
No option in created groups setting for blog to not be added to main blog list

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2553]
## What happened?
No option in created groups setting for blog to not be added to main blog list
The main blog becomes useless due to the spam blogs always on top
## Steps to reproduce:
1.  post any spam blog from an individual account
2. 
3. 

## What is expected?
pages have options whether to include photo in main photo, why not the same for blogs in custom group settings?

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
If you want to hide blogs which posted in Groups in the main blog section, you should disable this setting in Blog App:
![screen shot 2019-01-17 at 09 32 36](https://user-images.githubusercontent.com/41947198/51291780-edb50680-1a3a-11e9-9409-b48b18869b19.png)

**Comment by prepperz** [comment]
That's  not what I mean. What I mean is the user group (like admin, registered etc...)  and not to disable blog, but  just for blogs in a certain user group to not display in the main blog list.

Use case: For example, this is useful if you want only want the site admin blog to show in the main blog list, but not the registered users.

**Comment by harrison05** [comment]
> Use case: For example, this is useful if you want only want the site admin blog to show in the main blog list, but not the registered users.

Currently, Blog App doesn't support this feature and we don't have a plan to implement it.
