### ISSUE TITLE
Uninstalling app doesn't confirm what's being uninstalled

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2554]
## What happened?
Doesn't reaffirm what's being uninstalled. What if you unintentionally clicked on the wrong one? I am noticing this quite frequently throughout the phpfox site. These small attention to detail is important.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
Should reaffirm what's about to be uninstalled.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

## Screenshots

![screenshot](https://user-images.githubusercontent.com/19594886/51286253-2d8ad800-19c0-11e9-93ac-144bf2dd244c.png)

**Comment by harrison05** [comment]
This popup is working as design, Admin absolutely can click **No** or **Close** button if he doesn't make sure what App will be uninstalled. Currently, we don't have any plan to improve it.

Regards.
