### ISSUE TITLE
Issue in displaying letters

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2556]
## What's happened?
Hello,
I discovered a bug that only appears in some places. 
It consists in the fact that in some places Polish letters do not display correctly, only there are issues in the places of Polish letters.

The issues appears, among other things, in the title of the header about creating a custom list of friends for which the published items will be visible.

Home -> Go to the place where you publish the status -> Click on the field where you change the people for whom the publication will be visible -> Click on Custom -> Click on create new list -> In the window where the place for the list and selection appears friends, the header has issues.

The phrase that should be displayed in the place where the issue is: "Utwórz listę znajomych".

Can You fix Harrison on my website?
I have provided access to my website on the ticket number #775544.
I also provided there data for an account where you can check this issue.
Thank you.

## Browsers and Devices tested
Chrome on Windows 10

## phpFox version
4.7.2 (fresh instalation)

## Screenshots
![letters](https://user-images.githubusercontent.com/38014237/51368368-6aa1b800-1aef-11e9-9ba7-af88c334df5c.png)
![letters2](https://user-images.githubusercontent.com/38014237/51368369-6aa1b800-1aef-11e9-9828-35af7806bf70.png)
![letters3](https://user-images.githubusercontent.com/38014237/51368370-6b3a4e80-1aef-11e9-9d80-995456d6ca1b.png)

**Comment by kerstar** [comment]
@harrison05

**Comment by kerstar** [comment]
I found another similar issue and described it in this application:
(https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2558)

Can you help me to fix these bugs...?

**Comment by harrison05** [comment]
We noted those bugs and will be fixed in v4.7.3. 
If you posted a ticket, our supporter will help you fix in your site soon.

Regards.
