### ISSUE TITLE
Cannot Edit your status if post includes a link

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2557]
## What happened?
Cannot edit your status post

## Steps to reproduce:
1. post your status and then try to edit it.
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by kerstar** [comment]
On my website works - fresh installation 4.7.2

**Comment by kerstar** [comment]
Check the settings for editing content for a given group of users

**Comment by prepperz** [comment]
.
![screenshot](https://user-images.githubusercontent.com/19594886/51445228-cd05de80-1cd0-11e9-8cfb-e39f9c5f4051.png)

Am I looking at the right place? Enabling / disabling "Can edit own user status?" has no affect.

**Comment by spirogg** [comment]
@prepperz
I got your first photo that you didn't want to send. Anyway you can retract that email ? 
Not that it matters to me but possibly to you since you know if it's sensitive or not ?

**Comment by prepperz** [comment]
@spirogg I don't think you can. no biggie.

**Comment by spirogg** [comment]
Sorry :( just wanted to let you know.

**Comment by prepperz** [comment]
@spirogg Thanks for looking out. :)

**Comment by prepperz** [comment]
OK. I figured out the issue and re-titled it appropriately.

**Comment by harrison05** [comment]
Yes, currently we don't support edit a Status with link

**Comment by prepperz** [comment]
It definitely should be enhanced for sure. That's standard on every social media site.

**Comment by harrison05** [comment]
> It definitely should be enhanced for sure. That's standard on every social media site.

Could you post another feature request? We will review to implement it later.

Thanks.

**Comment by prepperz** [comment]
Done: https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/772

**Comment by harrison05** [comment]
Thanks, @prepperz. I will close this topic, please follow the new one.
