### ISSUE TITLE
Next issue in displaying letters

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2558]
## What's happened?
I discovered a bug that only appears in some places.
It consists in the fact that in some places Polish letters do not display correctly, only there are issues in the places of Polish letters.

The issue appears in the notification location after we accept an invitation to friends from another user. In screen shots I show where the problem is. 
The correct phrase should be "Ty i Admin jesteście teraz znajomymi".
Another bug with Polish characters is described in this application: 
(https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2556)

Can you help me fix this bug and earlier on my site?  
I have provided data to my site in the ticket number #775544.

Thank you.

## Steps to reproduce:
1. Invite someone to friends
2. The second person must accept your invitation
3. An issue will appear with Polish letters in the phrase confirming the invitation

## Browsers and Devices tested
Chrome, Firefox, Edge on Windows 10

## phpFox version
phpfox 4.7.2 - fresh installation

...

## Screenshots
![letters4](https://user-images.githubusercontent.com/38014237/51448300-f0a74400-1d25-11e9-9452-7062e1834bbb.png)
![letters5](https://user-images.githubusercontent.com/38014237/51448301-f0a74400-1d25-11e9-8b57-961f3af8aa6e.png)

**Comment by kerstar** [comment]
Can you tell me how I can fix this issue myself? Which file to edit? 
I can't open my ticket because I don't have paid support and it will take two weeks to fix this bug in the low priority.

**Comment by david-phpFox** [comment]
We noted those bugs and will be fixed in v4.7.3.

**Comment by kerstar** [comment]
@david-phpFox 
I heard you plan to release the phpfox 4.7.3 release next week. 
Can you tell me when? At the beginning of the week, in the middle of the week or at the end of the week? 
This is very important information for me.
