### ISSUE TITLE
Uploaded Pages cover image does not resize

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2560]
## What happened?
Uploaded cover image does not resize for pages cover and probably other sections as well.

## Steps to reproduce:
1. Upload a large cover image
2. 
3. 

## What is expected?
Should resize, but it didn't

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
I remember we discussed this issue before in #2481 , the cover is resized with some width, ex: 1024, 500...
