### ISSUE TITLE
egifts missing

### ISSUE THREAD

**Issue by djafrika** [PHPfox-Official/phpfox-v4-issues#2561]
What's happened?
1.If you add more than 6 gifts via admin panel and then go on profile to buy a gift, after popup opens, there are 6 gifts on page one and the same ones on page two.
2.if you add more than 10, in admin panel are shown only 10, without pagination. So you cannot access gifts on page two.

Steps to reproduce:
1. add gifts via admin panel
2. try to find gifts

What's expected?
To work

Browsers and Devices tested
Chrome on Windows 10

Server information
CentOS 7, php 7.3 apache Nginx

phpFox version
4,7,2

**Comment by harrison05** [comment]
I just checked, 2 points are bugs of eGift App. 
We will fix them.

Thanks.
