### ISSUE TITLE
Disable All External URL's dont work

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2563]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When "Disable All External URL's" is enabled external url's display as links.

## Steps to reproduce:
1. Enable "Disable All External URL's"
2. Add an url into comment, blog etc
3. Save and click on the link

## What's expected?

URL's should not show up as link.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

All browsers and devices

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

phpFox 4.7.2

**Comment by kerstar** [comment]
Strange.
Normally how should this function work?
All url's that the user adds in the comment should not display, or only the external ones? 
Internal should work?

**Comment by kibcode** [comment]
the name of that setting says "external" so i think that only external urls wont be converted to links.

**Comment by kerstar** [comment]
I checked it on my site (tested on phpfox 4.7.2 fresh instalation).

I turned on the "Disable All External URL's" option and cleared the cache.

I logged in as a regular user and added a link to the comment, and to the custom field displayed on the user's profile.

In both cases, the external link was seen as a URL.

Can you fix it in 4.7.3?

**Comment by harrison05** [comment]
This feature is working as our design. We just improved work follow on it from version 4.6.1. 
When this setting is enabled, we only remove **href** in all external links to prevent user click and redirect to other sites, we don't remove links in user's content.

Note: We will remove clickable on those links and make them same with normal text.

Regards.

**Comment by kerstar** [comment]
@harrison05 
Will you fix it and remove clickable links in phpfox 4.7.3?

At the moment it looks like when I enable "Disable All External URL's" and clear the cache, all external links users can add in comments and custom fields are clickable. This is a big problem, because I already have 2-3 bots each day, which register accounts and send spam by pasting links.

**Comment by harrison05** [comment]
@kerstar Yes, we will fix and remove clickable on external links in v4.7.3 but we don't remove them from content if setting "Disable All External URL's" enable.
