### ISSUE TITLE
Issue in pages and groups apps

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2564]
## What's happened?
If the user likes the site and joins the group, then if his account is deleted by the administrator in the AdminCP, then the site's page counts and the number of group members are not reduced. In the case of the "members" tab on pages and groups, the deleted user does not appear there (it is as it should be here) and the value is correct, while the main page and group counter is bad.

If the new user likes the site or joins the group, then the value of the counter does not increase and now the correct value matches the reality.

## Steps to reproduce:
1. The user likes the example page and joins the sample group
2. The administrator deletes this user's account
3. The value of page likes, and the number of group members has not been reduced

## phpFox version
4.7.2

**Comment by david-phpFox** [comment]
Fix in Pages/Groups 4.7.3
