### ISSUE TITLE
Thumbnail image of  user profile doesn't update til cache is cleared

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2565]
## What happened?
when user updates their profile image, the smaller thumbnail you see when you search people to add to a page is not updated and still sows the letter instead of image until cache is cleared

This affects all sections

## Steps to reproduce:
1. while being logged in as admin on a different browser create a new account and upload profile image.
2. From the admin account go to a page and search for the new user
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Could you take a screenshot of screen where it's happening? Because I test in Invite tab on Pages, this issue doesn't occur.

**Comment by prepperz** [comment]
Here you go. :) 
![screenshot](https://user-images.githubusercontent.com/19594886/51653001-9396d280-1f5f-11e9-9903-c8f3b3768715.png)

**Comment by harrison05** [comment]
Ok, I got it, it seems an issue with cache avatar system. We will check and fix.

Thanks.
