### ISSUE TITLE
If pages admin changes their personal profile name. The name on the pages admin list does not update until cache is cleared

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2568]
## What happened?
The name on the admin list is not updated until cache is cleared when the admin changes their name.

## Steps to reproduce:
1. Change the name of the pages admin from account settings
2. go to the page and look at the admin list on the bottom left
3. 

## What is expected?
.Name should be updated, but does not until cache is cleared

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by david-phpFox** [comment]
Fix in Pages 4.7.3
