### ISSUE TITLE
new fresh install activity points not working ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2569]
----------------------------------------

## What's happened?
... i installed fresh install 4.7.2 and as admin I set some activity points to 10 and 100 
example upload photo get 100 points

I upload 3 photos and no points when I go to activity points ?
it shows 0 total for activity points

## Steps to reproduce:
1. fresh install
2. activate activity points
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php7.2
...

## phpFox version
(Example: phpFox 4.6.0)

... 4.7.2

## Screenshots
...
![capture](https://user-images.githubusercontent.com/17736688/51716913-5df7f500-2004-11e9-86f0-6b474e7facc0.PNG)

**Comment by harrison05** [comment]
Do you set up cronjob? Activity points you got is added to a queue and only update when cronjob run.

**Comment by spirogg** [comment]
ok yes, i had
/usr/local/bin/php /home/username/public_html/cron
instead of curl -s https://
i change to curl command and its now working thanks
