### ISSUE TITLE
Cannot edit description of photo and video in the feed

### ISSUE THREAD

**Issue by KamAZenok** [PHPfox-Official/phpfox-v4-issues#2570]
## What's happened?
Cannot edit description of photo and video after it was published in the "feed" / "pages feed"

## Steps to reproduce:
1. Make post containing photo or video. Add description.
2. Click "three dots" at the upper right corner.

## What's expected?
Logically expected to be "Edit" item also. But there is only "Delete".
In the Pages Feed it is the same.

## Browsers and Devices tested
Windows 10, Chrome

## Server information
CentOS 7, PHP Version:  7.2.14, MySQL 5.5.5-10.3.12-MariaDB, Apache

## phpFox version
phpFox 4.7.2

## Screenshots
![1](https://user-images.githubusercontent.com/44835622/51744112-d962b080-20af-11e9-9e4f-41d4e5bf6f54.jpg)
![2](https://user-images.githubusercontent.com/44835622/51744136-eaabbd00-20af-11e9-9f9d-a1916a0c1978.jpg)
![3](https://user-images.githubusercontent.com/44835622/51744141-ef707100-20af-11e9-8721-23cb1d69cdc2.jpg)
![4](https://user-images.githubusercontent.com/44835622/51744146-f39c8e80-20af-11e9-9143-014f813878ba.jpg)

**Comment by kibcode** [comment]
i think that this is working as designed because the menu is for the feed item not the item (e.g. image) you uploaded itself. using the delete button also deletes only the feed item...

**Comment by harrison05** [comment]
Yes, currently we don't support edit feed of items (Photo/Video is an example...). 
But, we will improve and support edit Status posted with Photo/Video/Link.

Regards.

**Comment by david-phpFox** [comment]
Improved in Core 4.7.3
