### ISSUE TITLE
Adjusting thumbnail size in pages > manage > photo > edit thumbnail replaced cover image with thumbnail.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2571]
## What happened?
When you go into manage the page and adjust the thumbnail it replace cover image with the thumbnail. I can't remember if the initial cover image was a straight upload or if it was a select from photo.  Regardless it seems to have replaced it.

This issue seems to also, be random. Cannot reproduce 100% of the time.

## Steps to reproduce:
1. Goto any page > pages > manage > photo > edit thumbnail > resizes > save
2. 
3. 

## What is expected?
It should not be replacing the cover image with the thumbnail, but it did.
.
## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.2 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Is this same issue with #2522 ?

**Comment by prepperz** [comment]
It's possible, but I cannot be sure as the cover image is getting replaced by the thumbnail image.

**Comment by harrison05** [comment]
>When you go into manage the page and adjust the thumbnail it replace cover image with the thumbnail. 

If your page cover is selected from photos and you set page's avatar as cover, when you edit avatar > cover is changed too.

**Comment by prepperz** [comment]
Then it's obviously an issue.  lol
Maybe create separate instance for the avatar from photo once it has been selected.

**Comment by harrison05** [comment]
Ok, we will check and try to find a solution for this case.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Pages 4.7.3
