### ISSUE TITLE
Important! There are no bug fixes on the list in the phpfox 4.7.3 version, despite submitting them to github!!!

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2572]
## What's happened?

Important! There are no bug fixes on the list in the phpfox 4.7.3 version, despite submitting them to github.

I have browsed the list of bugfixes in phpfox 4.7.3 on the page:
[https://docs.phpfox.com/display/FOX4MAN/phpFox+4.7.3](https://docs.phpfox.com/display/FOX4MAN/phpFox+4.7.3) 
and I saw that on the list there are no two reported bugsthat have been reported a long time ago. 
You forgot to fix them ...?

Check this:
1. [https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2544 ](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2544 )
2. [https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2493 ](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2493 )
3. [https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2531](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2531) 
4. [https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2399](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2399)

On github, these bugs are marked as those that you can fix in 4.7.3, but in the list of bugfixes that are here: [https://docs.phpfox.com/display/FOX4MAN/phpFox+4.7.3](https://docs.phpfox.com/display/FOX4MAN/phpFox+4.7.3) these bugs are not shown.

Have you forgotten about them?... 
Can you fix them in 4.7.3? Should we wait for version 4.8.0 ...?

## phpFox version
4.7.3

**Comment by Elshara** [comment]
I follow this git hub for awhile. All the open ones tend to close
within a couple days. Either they're in an internal bug tracker, or
they are dismissed. git Hub doesn't have a status for actively being
developed. You'd think Microsoft would have that introduced. It would
do wonders for windows 10 should they wish to publicly develop it and
open source the project.

**Comment by kerstar** [comment]
The same for this issue: [https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2563](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2563)
You have indicated that you are repairing in 4.7.3, and on this list: [https://docs.phpfox.com/display/FOX4MAN/phpFox+4.7.3](https://docs.phpfox.com/display/FOX4MAN/phpFox+4.7.3) there is no information about fixing this bug ...
Really?

**Comment by harrison05** [comment]
@kerstar Don't worry, I confirmed that all of them were fixed in v4.7.3, our team just updated changelog. Notice that changelog you saw yesterday is not completed.

**Comment by harrison05** [comment]
@kerstar Don't worry, I confirm that all of them were fixed in v4.7.3, our team just updated changelog. Notice that changelog you saw yesterday is not completed.

**Comment by harrison05** [comment]
We just released v4.7.3, you can upgrade and check all of them.

Thanks.
