### ISSUE TITLE
When adding categories and sub categories to video app its doesnt notice doubles ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2573]
----------------------------------------

## What's happened?
...when I go to videos app and add sub categories with the same name, it accepts the doubles and even triples, see photo. I have Salsa 2 times, this should not allow the Same name for a category or even sub category in Video app or any of your apps where we are able to create categories or sub categories

can you please fix this in 2.7.3 if possible

also can you chekc music app also and ALL OTHER APPS where we can add cats and sub cats

## Steps to reproduce:
1. video app
2. add category use drop down select main category
3. then under that type in your sub
then repeat above steps woth the same name for the sub cat and you will see it adds it 2 times even 3 4 5 10 times same word, 

see photo there are multiple words the same in the photo.
## What's expected?
... should block same category and sub category wording with same spelling from being added..

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...4.7.2 centos 7 php 7.2

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![video categories - sub cat](https://user-images.githubusercontent.com/17736688/51926286-93ab2e00-23b6-11e9-9464-1160d6531d41.PNG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/51926435-ebe23000-23b6-11e9-9476-ea1e3bf8eab0.PNG)

**Comment by spirogg** [comment]
Also would be nice if all apps that we can add categories and sub categories if they automatically sorted Alphabetically

so if I add category or sub cat (example "Salsa" it will be added Alphabetically so we don't have to adjust those cats and sub cats.. I know this is feature request - but just adding it it here anyway

**Comment by harrison05** [comment]
As our defined, we allow Admin to add many categories with the same name and applied for all Core Apps have categories. About sorted Alphabet, because categories support drag-drop to reorder them, therefore if we support sorted Alphabet, this feature will work incorrectly.

Regards.

**Comment by spirogg** [comment]
Ok. It would be nice not to be able to have same wording and is caught by phpfox script. I can understand the alphabetical will not work correctly if we do that. I can live with that. But double categories are a pain in tye A$$ :😂
But if there is no way to make this stop duplicate. I can live with this too. 

PS 😄🗾🎲🎯
