### ISSUE TITLE
something weird with shoutbox 6 same posts,  then one and then 2 same posts ??

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2574]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
my fresh install i added videos music some photos from feed and app all videos music created a group 

than i add wording in shoutbox Happy Birthday I refresh and I have 6 same posts ?
then I write OMG refresh only one then I write this is crazy and double posted same words

I also had clicked on like of my own posts like unlike etc.. not sure what order but you can look at photos

maybe has something to do with i click like and unlike on my own post ? really weird

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...
only one post at a time
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
...

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.2

## phpFox version
(Example: phpFox 4.6.0)

...
4.7.2 fresh install
## Screenshots
...
- first post and like -

![capture](https://user-images.githubusercontent.com/17736688/51957260-8c187300-2410-11e9-9dc8-cb4820651053.PNG)

- and here is second and third double post

![capture1](https://user-images.githubusercontent.com/17736688/51957279-a3eff700-2410-11e9-9226-a8da406f39cd.PNG)

**Comment by spirogg** [comment]
@harrison05 here is more info still does it on my dev site fresh install 4.7.2

SHOUTBOX Double posts

ok what i tried on another fresh install is upload some photos and videos go to feed (home page) and add again "Happy Birthday" liked it in shoutbox as admin refreshed a couple times was good, then I added another few words "how are you ?/" liked it as admin

**i refresh and still OK**

 **then in feed I like a few photos and video and refresh** 

**- then first word doubles "Happy Birthday" then the other words "how are you ?/" doubles**

_weird_

![capture](https://user-images.githubusercontent.com/17736688/51959400-c3d7e880-2419-11e9-90ff-47dd94ad325c.PNG)
![capture1](https://user-images.githubusercontent.com/17736688/51959401-c3d7e880-2419-11e9-8e76-9b536b8199e3.PNG)

**Comment by spirogg** [comment]
![capture](https://user-images.githubusercontent.com/17736688/51959500-495b9880-241a-11e9-95ad-a818ae2f7014.PNG)


Double again

**Comment by spirogg** [comment]
Hope you have 4.7.3 I will reinstall fresh and hope this is a bug from something else and can report back here. Just saw you updated 4.7.3 Material theme so I need to check download if it's 4.7.3 now. :) Hope so.

**Comment by spirogg** [comment]
ok Also Happens on groups shoutbox

I just added 2 words
Join our group
Puerto Rico
and then I liked both of those words
- **then I refresh and there were duplicates of Join Group**
- **then I unliked 1 of the joined Group words refresh page and its back to normal**

- **it has to do with like button** in shoutbox

![capture](https://user-images.githubusercontent.com/17736688/51972888-10cfb500-2442-11e9-9748-822b9bd7d304.PNG)

- 
![capture1](https://user-images.githubusercontent.com/17736688/51972895-15946900-2442-11e9-87ec-8ef59269ced4.PNG)

**Comment by spirogg** [comment]
Ok thanks. It's bug. Still after update to 4.7.3 is still happen when you click like and refresh page a few times. :(

**Comment by harrison05** [comment]
Ya, it still appears in the current version, we will fix and update in the next version of Shoutbox App

**Comment by cyristvirus** [comment]
Any idea when this update will be released?

**Comment by harrison05** [comment]
> Any idea when this update will be released?

We haven't yet defined time to release the new version for this App. If you have an issue with it, you can submit a ticket for quick support.

Regards.

**Comment by harrison05** [comment]
@cyristvirus We just released Shoutbox v4.3.1. You can upgrade and check.

Regards.
