### ISSUE TITLE
Page not found if "Enable Subscription Packages" is disabled

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2575]
## What happened?
Disabling "Enable Subscription Packages" displays "page not found" when selecting membership
## Steps to reproduce:
1. Click on dropdown arrow next to avatar and then select membership

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.3 (Upgraded), Material theme

...

**Comment by david-phpFox** [comment]
Fixed in Subscription 4.6.4
