### ISSUE TITLE
user Process, set UserID for new feed entry

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2577]
PF.Base\module\user\include\service\process.class.php Line 389

change
`(Phpfox::isModule('feed') ? Phpfox::getService('feed.process')->add('user_cover', $iPhotoId) : null);`

to

`(Phpfox::isModule('feed') ? Phpfox::getService('feed.process')->add('user_cover', $iPhotoId, 0, 0, 0, (int)$iUserId) : null);`

Becuase of, if I set a UserID for updateCoverPhoto, it will overwrite with loggedin UserID in feed process.

**Comment by harrison05** [comment]
Currently, if you don't set UserId, the feed process will get current logged in UserId become feed's owner. 
I guess this is your issue: It seems working well with our Photo Apps, but it might a mistake if another 3rd App call to function updateCoverPhoto with $iUserId != current logged in. Do you mean like that?

**Comment by Bjoern3003** [comment]
I use my own third party app, that is calling the updateCoverPhoto function wich is calling in a loop for all users in the database. I can transfer the userid to this function, but not to the feed.process service in this case.

**Comment by harrison05** [comment]
Ok, we will update in the next version.

Regards.
