### ISSUE TITLE
Multiple Usergroups for each User

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2579]
Maybe it could be interesting, that each user can be in more than one Usergroup.

eg. One User is Forum moderator AND blog author. So he has access to moderate Forums and edit Blog articles. 
In this case, its easier to manage the usergroups.

**Comment by harrison05** [comment]
It sounds interesting but it will take a lot of time to implement and manage user groups.
So sorry, we don't have any plan to implement this feature in the current time.

Regards.

**Comment by Bjoern3003** [comment]
To create an App for this feature, it could be nice to add an Plugin Hook in PF.Base\include\library\phpfox\phpfox\phpfox.class.php on Line 1314

So we can create an App to Check more than only one Group. Is this possible for next release. Maybe any other Ideas.
