### ISSUE TITLE
Deleting pages status with link does not go away until refreshed

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2580]
## What happened?
Deleting pages status with link does not go away until refreshed

## Steps to reproduce:
1. Post a status on pages with description and a like and delete it

## What is expected?
It should disappear, but doesn't until it's refreshed.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.3 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
I can't reproduce this issue. Could you take a screenshot?

**Comment by prepperz** [comment]
it looks like it resolved itself. However, On the phpfox demo site when you share it on your wall and then delete it post , it temporarily display "can find" or delete and then deletes it.

**Comment by harrison05** [comment]
Oh, I don't understand the issue on our demo, could you take a screenshot?

**Comment by prepperz** [comment]
Use this link: https://www.businessinsider.com/alaco-wealthy-saudis-moving-nine-figure-sums-out-intimidated-2019-2?IR=T

![screenshot](https://user-images.githubusercontent.com/19594886/52841049-2216f380-30c9-11e9-9f9c-8df6a482455b.png)

**Comment by harrison05** [comment]
Ok, I can reproduce it now, it might a bug from Pages or Core. 
We will check and fix it.

Regards.

**Comment by david-phpFox** [comment]
Fix in Pages 4.7.3
