### ISSUE TITLE
Sharing a pages status link on Facebook doesn't parse the link image or description, but always page cover image

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2581]
## What happened?
Pages cover image is always parsed by FB when status links are shared on FB,

## Steps to reproduce:
1. Post a pages status with descriptions and link.
2. Click on home share that feed to your wall
3. Now right clik on the image or title of pages status you shared on your wall.  The link should be like so: https://www.xxxxxx.com/index.php/whateverpages/?link-id=1071

## What is expected?
The image and description of the shared link (not the pages cover) should be parsed by FB

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.3 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Because of the link: _https://www.xxxxxx.com/index.php/whateverpages/?link-id=1071_ doesn't set meta tag **og:image**, so FB will auto get the biggest img tag in that page  and set as preview thumbnail on FB.

**Comment by david-phpFox** [comment]
Fixed in Pages/Group 4.7.4
