### ISSUE TITLE
Cannot view attached images in messages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2583]
## What happened?
Cannot view attached images in message when it is clicked. You have to download it and then view it.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
Should be able to just click on attache image and view with option to download.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.3 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Did you mean image too small to view detail in conversation?

**Comment by prepperz** [comment]
No. It does not display the image. When you click it, it will download the image and have to save it first and then view it externally.
![screenshot](https://user-images.githubusercontent.com/19594886/52940636-fe57e580-3334-11e9-9d64-66aa350507da.png)

**Comment by harrison05** [comment]
I just checked on my side (Message v4.7.2), when attaching an image, it has a small thumbnail in conversation, so when clicking on the thumbnail, you can view full image size, check my screenshot
![screen shot 2019-02-19 at 10 09 18](https://user-images.githubusercontent.com/41947198/52987630-7c4be780-342e-11e9-9e2e-d6549826f5b4.png)

**Comment by prepperz** [comment]
hmmm. I don't get that on mine. It just downloads. What file format is that?

**Comment by harrison05** [comment]
It's an image file with extension: png or jpg

**Comment by prepperz** [comment]
OK try the test like this. Use a set, 1 jpg and 1 png. Should see something isn't working right.
1.  Test1 use the insert photo of each format and send it.
2. Test2 use the attached option of the same set and send.

![screenshot](https://user-images.githubusercontent.com/19594886/53081778-83740380-34c9-11e9-94ad-2890c533c671.png)

**Comment by harrison05** [comment]
Ya, I checked 2 cases, it's still working right in my side. It weird...
![screen shot 2019-02-21 at 10 06 02](https://user-images.githubusercontent.com/41947198/53140843-94ec0700-35c0-11e9-91e6-df0fedf43043.png)

**Comment by prepperz** [comment]
Ya the weird part is the jpg seems to work fine, but not  the png or may the opposite I forget.

**Comment by harrison05** [comment]
In my side, both of them are working well.
![screen shot 2019-02-22 at 09 31 00](https://user-images.githubusercontent.com/41947198/53215780-ac8cc380-3684-11e9-99f9-7d5164fe0445.png)
![screen shot 2019-02-22 at 09 31 09](https://user-images.githubusercontent.com/41947198/53215784-b31b3b00-3684-11e9-96d0-a195bb9a036f.png)
