### ISSUE TITLE
Issue with displaying custom fields on the user profile home page

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2584]
What's happened?
Hello,

I removed the default custom field on the user's home page profile and wanted to add a new one (and in fact a few) and I have a big problem.
I have problem with displaying custom fields on the user profile home page.
The problem is that I can not add a custom field to the home page of the profile at the top left 
and I can not change the order of the custom fields.

In AdminCP-> Members-> Custom Fields, when editing or adding a custom field, I have two options to locate the custom field location:
1. Users Profile - Main section
2. Users Profile - Basic Information

When I select "Users Profile - Main section", the custom field is displayed at www.examplesite.com/user/info/, and if I select the "Users Profile - Basic Information" location, the custom field is not displayed anywhere.

In the earlier version of phpfox (4.7.0, 4.7.1, 4.7.2) I did not have this problem.

I wanted to be able to add some non-standard fields to the main page of the user profile on the left at the top above the "Friends" tab, but there is probably some error and I can not do it.

Can you fix this bug on my site? ..

Additional question:
If you create a new group for custom fields, you must select "Custom Fields" from the drop-down list in the "Module" section?

Can You fix it?
I have provided data to the website in ticket # 721588
Thank You Sir.
## Steps to reproduce:
1. Go to AdminCP-> Members-> Custom Fields and try add new custom fields on user's home page profile

## What's expected?
The custom field does not appear on the user's home page.

## Browsers and Devices tested
Chrome, Firefox on Windows 10

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
4.7.3 fresh installation (not updated)

...

## Screenshots
![customfield1](https://user-images.githubusercontent.com/38014237/52921486-005f7b80-3318-11e9-99c7-dfe40879662f.png)
![customfield2](https://user-images.githubusercontent.com/38014237/52921487-005f7b80-3318-11e9-9b9b-bd8c7a751dca.png)

**Comment by kerstar** [comment]
@harrison05 Can you help me fix this problem on my site? I have to wait again for version 7.3.4...?

**Comment by kerstar** [comment]
Please check the update of my ticket, because I gave it another place where there is the same problem - it is impossible to set the fields to be displayed in the "Info" tab, only all are displayed on the main page.

**Comment by harrison05** [comment]
If you want to display a custom field in the "Info" tab, you should select Location is Main Section when creating it:
![screen shot 2019-02-19 at 10 12 15](https://user-images.githubusercontent.com/41947198/52987765-12800d80-342f-11e9-8aa6-21296eed6f36.png)

**Comment by kerstar** [comment]
I confirm. I did as you wrote and now it works! Thanks!

**Comment by david-phpFox** [comment]
Hi kerstar,

Can you please give us your email used on the ticket system?
We will check and fix this problem on your site.

Best Regards,
David

**Comment by kerstar** [comment]
@david-phpFox 
I received information that the bug has been fixed, but ok, you can check this:
My email in ticket system: champion.rocky@gmail.com

Thanks David!

**Comment by kerstar** [comment]
@david-phpFox 
Let me know if you change something in code, because I need to know about it.

Thank You.

**Comment by david-phpFox** [comment]
Hi kerstar,

I have checked with my team, this problem was fixed on your site.

Best Regards,
David

**Comment by kerstar** [comment]
Hi David,

Sure. I saw earlier that it was fixed, but as you wrote that you check, I did not know if you forgot something yet or whether it was about the second part of the bug I described in the ticket.

Thank you very much. It helped me a lot, that you fixed this bug.

Have a nice day David!
