### ISSUE TITLE
I can not translate the phrase "Select All" in messages

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2585]
## What's happened?
I can not translate the phrase "Select All" in messages

## Steps to reproduce:
1. Go to www.examplesite.com/mail/

## What's expected?
In the upper left corner, the phrase "Select All" is not displayed in the correct language, it has been omitted that it has been translated.

## Browsers and Devices tested
Chrome on Windows 10

## phpFox version
phpfox 4.7.3 fresh installation (not updated from the previous version)

## Screenshots
![selectall](https://user-images.githubusercontent.com/38014237/52979524-4da22280-33d6-11e9-9573-7c6e2d30d694.png)

**Comment by harrison05** [comment]
This is a bug of Message App, we will check and fix it.

Thanks.

**Comment by david-phpFox** [comment]
Fix in Message 4.7.3
