### ISSUE TITLE
CKeditor Link new window (_blank) does not open in new window

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2586]
## What happened?
Link does now open in new window

## Steps to reproduce:
1. Create link. Set target as new window (_blank)
2. 
3. 

## What is expected?
Should open in new window, but doesn't

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.3 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
I checked on my site with posted a new Blog, and it's working well. The link is open on a new tab when clicking on it
![screen shot 2019-02-20 at 09 55 36](https://user-images.githubusercontent.com/41947198/53063209-f4c9ab80-34f5-11e9-8f67-f06c8bfcd422.png)

**Comment by prepperz** [comment]
Use the same url  you are testing it from. :)

**Comment by harrison05** [comment]
Ah. Did you mean add an internal link? I just checked and it doesn't work as you say.

We will check this issue, it might related to ajax mode in phpFox site.
