### ISSUE TITLE
Message refresh to last message while viewing long messages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2587]
## What happened?
If a user sends you multiple messages, for example 10 long messages. While your're reading message number it will refresh/update and display the last message and you have to scroll backup to read the message. 

## Steps to reproduce:
1.  Type 10 long message and send
2. Try to read it
3. 

## What is expected?
While viewing the message display should stay same position until you are ready to scroll down. 

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.3 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Did you mean, scroll bar auto scrolling to top after it finish load more old messages and you must scroll down again to read new messages?

**Comment by prepperz** [comment]
What i mean is that it will auto scroll to the botttom while i'm in the middle of reading a message.

**Comment by harrison05** [comment]
Ya, I see. This issue occurs when Newsfeed executes the function to check new update in the background. We will check it.

**Comment by david-phpFox** [comment]
Fix in Message 4.7.3
