### ISSUE TITLE
Issue with a popup window in the message app

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2588]
## What's happened?
Go to any message on a mobile device with a small screen. A window will pop up that is too large and can not fit on the screen, making it impossible to read the message.
I fixed the problem on my site by adding the max-window parameter for mobile devices in the css file and giving the appropriate values.

## phpFox version
4.7.3 fresh install

**Comment by david-phpFox** [comment]
Fix in Message 4.7.3
