### ISSUE TITLE
Language Phrases with Number (4.7.3)

### ISSUE THREAD

**Issue by Lidercan** [PHPfox-Official/phpfox-v4-issues#2589]
Hello,
these phrases are from 4.7.3. I do not understand why the number come ... Is this issue on my PC or script ..?
                 Variable                                                                              Original
app_7dbf338d0fa404846ac31e47b6aecd45     "Days to Expire" must be greater than or equal to 0
app_290da1bd782b46dd450f650e6f9fe3ee      "Sponsor listing price" must be greater than or equal to 0

**Comment by harrison05** [comment]
Ya, this phrase name was automatically generated by Core base on its value. Don't worry, it's working right, just focus on the value.
