### ISSUE TITLE
Custom Gender Display Error

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2590]
There is a display Error in Bootstrap and Material Template if I want to add a custom Gender to my profile.

![01032019135051](https://user-images.githubusercontent.com/13675579/53639318-27c41b80-3c29-11e9-954f-393a16b727e8.jpg)

Is this a known bug?

**Comment by harrison05** [comment]
This is a bug, we fixed in v4.7.4, please waiting for this version.

Thanks.
