### ISSUE TITLE
After upgrade to v4.7.4. Clicking on down arrow > admincp opens up multiple pop-up windows

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2593]
## What happened?
After upgrade to v4.7.4 Clicking on down arrow > admincp opens up multiple pop-up windows

update: 3/7/2019 2:38 pm
This also affects wigets front end when link Target "new window(_blank) is utilized internal link seems to produce an endless windows oop-up loop.. This could possibly affect every other  section that might utilizing this such as blogs, forum etc... 

Google search / chrome or other means may possibly view it as Malware as it renders the browser unusable at times as it is overloading the browser with pop-up windows.  The same for fire fox. This is really bad given it is also happening on the front-end.

## What is expected?
This need immediate attention.

## Browsers and Devices tested
Chrome & firefox on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Could you explain more about this issue? Take a look on my screenshot, is this section?
![screen shot 2019-03-07 at 09 38 28](https://user-images.githubusercontent.com/41947198/53928490-ec0fd280-40bc-11e9-803f-af1115306663.png)

**Comment by prepperz** [comment]
Yes. On the screenshot click on "admincp" and it will open multiple windows of the link. Other site owners that did the updates are also confirming the same issue. https://community.phpfox.com/forum/thread/57755/

**Comment by PhpFoxJohnJr** [comment]
I can confirm as well...yes the testing is slacking (sorry).  Glad you are here to post it as I have pretty much given up posting bugs.

**Comment by PhpFoxJohnJr** [comment]
Even their email announcing 4.7.4 has a button to read the blog and it goes to phpfox home page.  Guess no one tested that as well.  You would think the blog URL would be https://www.phpfox.com/blog/2019/phpfox-4-7-4-official-release/

**Comment by david-phpFox** [comment]
We will check and fix in 4.7.4 (build 2).

**Comment by joblux** [comment]
i cant believe that...new version is in fact just a bunch of fixes not really bringing new stuff and on top of that it messes up all your current site. bad bad bad communication !

**Comment by david-phpFox** [comment]
Fixed in 4.7.4 (build 2).
Please update it again.

Sorry for our mistake.
