### ISSUE TITLE
Post 4.7.4 upgrade now forced flags External link as "This link leads to an untrusted site. Are you sure you want to proceed to"

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2595]
## What happened?
Post 4.7.4 upgrade now flags External link as "This link leads to an untrusted site. Are you sure you want to proceed to"

This is a terrible solution.  Please make it so it does not flag by default and make it an option for those site admins that choose to use where they can turn it on or off as well as edit the phrase. It's very poor assumption and It's very misleading and negatively impacts both the phpfox site and the external site.

Yes, it even says phpfox site can't be trusted from the admincp dashboard for external link about 4.7.4 relase.

At least change the default text to," This is an external link. Are you sure you want to proceed to {link}?" instead. It's not the job of phpfox to pre-judge whether a link is good or bad. 

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
This feature is working as our design. Admin can disable this warning by setting "External Links Warning" in AdminCP. Currently, you can change warning phrase as you said.
![screen shot 2019-03-08 at 09 36 41](https://user-images.githubusercontent.com/41947198/54003718-b551bf00-4185-11e9-98d2-f64774838fe1.png)

**Comment by prepperz** [comment]
I was looking for it prior to posting the issue, but could not find it. I'll have another look.

**Comment by prepperz** [comment]
Disabling the setting has no effect. Still flags the warning.  Same deal for the front end. Nothing. click on the admin dashboard and More News & Updates
phpFox 4.7.4 Official Release

**Comment by harrison05** [comment]
> Disabling the setting has no effect. Still flags the warning. Same deal for the front end. Nothing. click on the admin dashboard and More News & Updates
> phpFox 4.7.4 Official Release

Okay, I just double checked again. This is a bug of 4.7.4, we will fix it.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
