### ISSUE TITLE
User Profile URL with dots in url are wrong

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2597]
On each page is the same problem. I think its global.

Please have a look at this example:
User Name is Tim.b
Profile URL is /Tim.b

On Picture Link, the URL is correct.
On Username URL ists wrong. There where the dot replaced with Slash

The Screenshot is taken in photo detail page.

![08032019175615](https://user-images.githubusercontent.com/13675579/54042936-a68dfb00-41cb-11e9-838b-5fe8e1c1dd0e.jpg)

**Comment by harrison05** [comment]
I wonder how this user can set a username with a dot between. Because phpFox doesn't allow this, here is error warning
_"Not a valid user name. User name can only contain alphanumeric characters and _ or - and must be between 5 and 25 characters long."_

**Comment by Bjoern3003** [comment]
We have manual inserted User by import from Wordpress.

Maybe we have to check and replace characters, but the bug is almost there, that the URL an Image is working fine and on Username not.

**Comment by harrison05** [comment]
Ok, I understand this issue, we will check and fix it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
