### ISSUE TITLE
missing add thread button

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2599]
## What happened?
...Missing add thread button

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/19594886/54067408-8f6ffd00-420d-11e9-9ab1-f6ada6234bf9.png)

**Comment by harrison05** [comment]
It's not a bug. This button doesn't show because setting "Can post a new thread?" is disabled. You can check on your site, it's working well.

Regards.
