### ISSUE TITLE
Resume YounetCo Issue 

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2600]
Hello,
Got this issue when installing Resume on my site after update 4.7.4 
I delete it then i downgrade to 4.7.3 to install it again. because there no version of resume available for 4.7.4 Phpfox new patch and install it again. Same issue

![Capture d’écran de 2019-03-09 11-01-46](https://user-images.githubusercontent.com/46829598/54069924-8a399f00-425b-11e9-9fcf-185859828abc.png)
![Capture d’écran de 2019-03-09 11-05-35](https://user-images.githubusercontent.com/46829598/54069925-8a399f00-425b-11e9-95d6-15fbb5436822.png)

**Comment by harrison05** [comment]
It seems this App doesn't compatible with our v4.7.4. 
You should contact with YouNetCo for support.

Regards.

**Comment by joblux** [comment]
Well Resume in the store looks updated and ready for  4..7.4 : https://store.phpfox.com/apps/resume-v4-younetco.

**Comment by harrison05** [comment]
> Well Resume in the store looks updated and ready for 4..7.4 : https://store.phpfox.com/apps/resume-v4-younetco.

If Resume on your site still breakdown, you should contact YouNetCo for help. This is not a bug of phpFox.
