### ISSUE TITLE
Contact form with CKeditor allows open door foreign code execution.  Needs immediate attention

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2601]
## What happened?
When the full package is selected in admincp. The same full features are also used in the contact form. This is bad as it introduces some security issues. For example, the fully exposed front facing ckeditor with all it's feature including iframe and flash options etc ... This is great for the admin, but not for the front end as these allow foreign code executions without ever needing to even login.

This is an open door invite for malicious activities.

## Steps to reproduce:
1. Go to admincp > apps > installed > phpfox ckeditor > settings > select full package.
2. Goto the contact page and refresh.

## What is expected?
The site admin should be able to disable certain features for the contact form.  The Contact form input should be very basic anyway.

The solutions are in the feature request I've submittted a while back.  https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/768

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/19594886/54075834-15259400-4272-11e9-8fa0-54691c96d58d.png)

**Comment by joblux** [comment]
we could use the catcha but either way its sooo heavy on the server the full package...it should be selectable to certain area of the website only.

**Comment by harrison05** [comment]
We will review your issues like new feature requests:
- Allow admin customize feature on CKEditor full package, related to [https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/768](url)
- "The Contact form input should be very basic anyway"

Regards.

**Comment by hamadax** [comment]
Both CKEditor and Froala allow for HTML tags to be excluded from the editor even if inserted in code view, they will be stripped out. Suggestion to give the admin the ability to select the prohibited tags in the admin cp. This worked for me in other projects where problematic users were injecting meta refresh tags into free product listings.

**Comment by david-phpFox** [comment]
Hi all, 

We will remove CKEditor out of the Contact form, the contact form should be a simple editor.

Looking forward to your update.

Regards,
David

Support Staff
www.phpFox.com
Start Your Social Network Today!

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
