### ISSUE TITLE
Selected menu item Font awesome and title does not match  display when menu is reordered

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2602]
## What happened?
Font awesome and title does not correctly display when menu is reordered

## Steps to reproduce:
1. Make some menu items with font awesome and  link them to a page in pages.
2. re-order the menu
3. select each menu item and scroll down on each one

## What is expected?
Each menu item selection should be displaying matching titles and font awesome, but not always the case.

 

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

## Screenshots
In the screenshot below, the menu item is, "Exchange" with a font awesome gear icon, but it's displaying the Education menu item instead.

![Screenshot](https://user-images.githubusercontent.com/19594886/54139362-c1dd4e00-43f7-11e9-886e-70722613669d.png)

**Comment by harrison05** [comment]
Ya, I got your issue. Main menu is focused on parent app menu of your URL. It is difficult to fix because might affect other cases and make them work incorrectly. We will check and inform you if have any update.

Regards.

**Comment by harrison05** [comment]
Hi @prepperz 

We fixed this issue from phpFox v4.8.3. It related to issue #2973 

Regards.
