### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2603]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...I set up Google recaptcha Api in my website phpfox in captcha box with
Recaptcha type v2
Recaptcha public and prive key from google recaptcha then i save it 
- enabled captcha on registration.
But it doesnt work. 
Got an error instead of Robot checkup

## Server information
 php 7. apache

...

## phpFox version
4.7.4

...

## Screenshots
...

**Comment by harrison05** [comment]
I can't reproduce the issue on my side (Captcha v4.6.1). Please make sure your configs in reCAPTCHA is correct. (reCAPTCHA type, Domains...)

Regards.
