### ISSUE TITLE
$Ready(function() Fires Twice on Pages with Editor

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2604]
On all Pages, where the CKEditor was inserted (eg. with `{editor id='description'}` the JS Function `$Ready(function(){});` where fired twice.

**Comment by harrison05** [comment]
Yes, $Ready is a JS function of our Core, not $(document).ready(). So it fire whenever pagg load init JS. Example: when you call $Core.loadInit()

**Comment by Bjoern3003** [comment]
But why does init CKEditor fires the $Ready again? Is that correct? What do I have for a function on pages with ckeditor, that not fires on ckeditor init.

**Comment by harrison05** [comment]
Are you sure CKEditor fires $Ready again? Or other functions were called to reload it.
If you have a function and want to fire it when init page, you should call it on $Behavior or $Ready function.

**Comment by Bjoern3003** [comment]
Yes I am sure. I created a App, with ckeditor. this page fies $Ready twice. If I remove ckeditor, that the $Ready funktion only firec once. Same on create Blog eg and all other Pages, that are using ckeditor.

**Comment by harrison05** [comment]
Does your function execute many times and make duplicate events fire? 
If this right, you should add a variable as a flag out of $Ready and check it before run your function or add a prop/attribute to your element to detect it init or not.

Regards.

**Comment by Bjoern3003** [comment]
I thought that is a bug, so I reported it. I have already implemented a flag, that its working for me. But I think the Problem is sidewide.

**Comment by harrison05** [comment]
I can't confirm this is a bug because JS re-init is useful for some cases and your source codes must control duplicate event fire.

Regards.
