### ISSUE TITLE
Google Adsense not working

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2605]
I can not Add Google Adsense Code to "BetterAds". He is cutting HTML Code after 135 chars.

**Comment by harrison05** [comment]
We will check this case and inform you if have any update.

Regards

**Comment by david-phpFox** [comment]
Hi Bjoern3003,

The app does not support add Google Adsense to the body of HTML Ad type.
To add Google Adsense, please go to AdminCP > Blocks and add a block with block type is HTML Code.

Regards,
David

**Comment by Bjoern3003** [comment]
Then, you have to Update your Docs for Users: https://docs.phpfox.com/display/FOX4MAN/Setting+up+Google+Adsense

**Comment by david-phpFox** [comment]
Hi Bjoern3003,

The document is correct, it guides Admin can create HTML based ads directly from your AdminCP with HTML as the block type. This is what we will use for our Google ads.

Regards,
David

**Comment by Bjoern3003** [comment]
But it don't work, because of limitation of 135 chars

**Comment by harrison05** [comment]
I checked our document, it's correct. When you add block with type = **HTML Code**, you can add Google Ads code in to field **PHP/HTML Code** without limitation. 
Note: We don't support add Google Ads into HTML Ad of Better Ads. Please double check and follow our document.
![Screen Shot 2019-03-27 at 13 38 05](https://user-images.githubusercontent.com/41947198/55055624-235b1900-5096-11e9-8f77-7f51a9d37f89.png)

**Comment by Bjoern3003** [comment]
Now I understand, I have tried to Add the Adsense Code in Better Ads App. **Solved**
