### ISSUE TITLE
Change Forum Signature in Frontend

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2606]
I think I'm stupid, but I can not find section, where I can change my Forum Signature in Frontend.

In Admin backend, I can change Forum Signature each User in Useredit, but where can I change my Signature in Frontend?

**Comment by harrison05** [comment]
We deprecated Signature in Forum, we will deprecate it at Edit user form in the future. So, don't mind about it.

Regards.

**Comment by Bjoern3003** [comment]
Is there anything else comming?

**Comment by harrison05** [comment]
Currently, we don't have plan for a new feature related to Signature.

**Comment by david-phpFox** [comment]
Dear Bjoern3003,

We will remove the Signature in Forum in AdminCP > Edit user form.

Regards,
David

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
