### ISSUE TITLE
Manage theme

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2607]
Hello, 
I want to create a new theme in phpfox.. Wanted to know what are the main files to customize because there is many files that looks the same in many folders, too much override of css files. 
I am using Sublim SFTP to change files.. can you recommend an adequat framework for phpfox to test in local if possible.. the theme manager looks like bugy isn't it ?
Thanks

**Comment by harrison05** [comment]
You can check our document to customize a theme at https://docs.phpfox.com/display/FOX4DEVDOC/Theme+Development+Guide

If you want to preview your theme in the frontend, you can add new parameter **force-flavor=<your theme id>** to your URL
Example: <site_url>?force-flavor=material
