### ISSUE TITLE
Apostrophe breaks incorrectly in blog

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2609]
## What happened?
Blog breaks incorrectly

## Steps to reproduce:
1. See screenshot

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

## Screenshots

![Screenshot](https://user-images.githubusercontent.com/19594886/54644761-94844600-4a70-11e9-9aef-6a07a8b7d71e.png)

**Comment by harrison05** [comment]
Ok, we will check this issue.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
