### ISSUE TITLE
Pages admin add Still cannot find users that changed their username or name at some point

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2610]
## What happened?
Cannot find users in pages admin add search if users change their username or name at some point.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
Maybe also include a way to find or add them via their email address they've used to register.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

**Comment by prepperz** [comment]
In the mean time, how do we add admins?

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
