### ISSUE TITLE
Special Char Problem on Usernames

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2611]
On different Positions where Problem with SpecialChars in Username.

Is this a known Issue?

![20032019103905](https://user-images.githubusercontent.com/13675579/54674395-a0b5e500-4afc-11e9-84b8-95e236115be3.jpg)

![20032019103856](https://user-images.githubusercontent.com/13675579/54674333-79f7ae80-4afc-11e9-9361-cce1084bb586.jpg)

You can see, that the Name is in the Database is correct. I wonder, that the Username is in the Memberlist for example correct.

**Comment by Bjoern3003** [comment]
Not only on Usernames. Found a problem, that All Vars, that a cleaning with Phpfox::getLib('parse.output')->clean() where wrong.

If I remove `$sTxt = preg_replace('/[\x00-\x1F\x7F-\xFF]/', '', $sTxt);` in PF.Base\include\library\phpfox\parse\output.class.php on Line 471, everything is working fine.

**Comment by harrison05** [comment]
This is a new code we added to fix ajax loading with special characters. It might an issue with it.
We will check and update.

Regards.

**Comment by harrison05** [comment]
> Not only on Usernames. Found a problem, that All Vars, that a cleaning with Phpfox::getLib('parse.output')->clean() where wrong.
> 
> If I remove `$sTxt = preg_replace('/[\x00-\x1F\x7F-\xFF]/', '', $sTxt);` in PF.Base\include\library\phpfox\parse\output.class.php on Line 471, everything is working fine.

This is a new code we added to fix ajax loading with special characters. 
But we didn't release it and hotfix some sites only. How did you get this code?

Btw, we will check again.

Regards.

**Comment by Bjoern3003** [comment]
Maybe installed it some one of your support. I did not know exacly.

**Comment by harrison05** [comment]
> Maybe installed it some one of your support. I did not know exacly.

Ok, we will check and update it in the final release version.
