### ISSUE TITLE
Theme Design

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2613]
Hello,
I can see that there is many files in.less like landing.less block.less etc but all the css informations seems to be loaded from autoload-474.css overrighting all changes.. 
that looks new because of the 474 which is the newest version of phpfox.
So if i want to design my own landing page for exemple and still use phofox functions and blocks
What are all the possibilities that i can get... 
Thanks

**Comment by AmineBAIK1** [comment]
Can see that changes took effect in bootstrap.css in PF.Site/flavors/materiel/flavor/bootstrap.css
When i create a new theme from blank the folder flavor is empty should i create a file .css in this folder
to have the same abilty to change css like i want. or it an other composant ?

**Comment by harrison05** [comment]
No, you don't need to add the bootstrap.css file, this file is combined from other .less files in your theme when rebuilding core theme. If you want to custom layout, please follow our document at https://docs.phpfox.com/display/FOX4DEVDOC/Theme+Development+Guide

**Comment by AmineBAIK1** [comment]
Yeah, Looks like it's true and its rebuilded from Less folder and files too but how do we "Rebuild core theme" of a New created theme ?

**Comment by harrison05** [comment]
You can "Rebuild core theme" after installing your new theme and set it as default template, at AdminCP > Maintenance > Rebuild Core Theme.
Btw, if you want to apply CSS change immediately, you should define this constant at **PF.Base/file/settings/debug.sett.php** file:
```php
define('CSS_DEVELOPMENT_MODE', true); 
```
