### ISSUE TITLE
Posting 2 url links on 2 different lines is displayed as a single line on a users's wall

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2614]
## What happened?
If you post 2 urls on to separate lines on a user's profile page, it's displayed as a sing line.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
