### ISSUE TITLE
User profile popup is partially hidden below screen

### ISSUE THREAD

**Issue by jwpwhite** [PHPfox-Official/phpfox-v4-issues#2615]
When I click on the like count for a user and I hover over the last like in the list, user profile popup displays below the bottom of the page so that only part of the popup is visible. See attached...

When the user profile popup is close to the bottom of the screen, it should popup above your pointer rather than below it.

![User Profile Popup Hidden](https://user-images.githubusercontent.com/27361659/55088469-73e16f00-50b4-11e9-8c72-7de48bbce1da.png)

**Comment by harrison05** [comment]
We will check this issue

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
