### ISSUE TITLE
4.7.4 (build 2) - Why does it show a Custom Gender?

### ISSUE THREAD

**Issue by jimmybsilva** [PHPfox-Official/phpfox-v4-issues#2617]
## What's happened?
On the User Registration form it does not require the user to select a gender also I shows the option of CUSTOM?

![image](https://user-images.githubusercontent.com/35279981/55509431-e0a6bd00-5610-11e9-879e-9b68c91e0a92.png)

## Steps to reproduce:
I only have 2 genders selected 
![image](https://user-images.githubusercontent.com/35279981/55509507-03d16c80-5611-11e9-8ae1-523fd0476e49.png)

![image](https://user-images.githubusercontent.com/35279981/55509633-4430ea80-5611-11e9-97c8-e4dbecb1d255.png)

## What's expected?
It should force the user to select a gender and should not show _

> custom gender

_?

## Browsers and Devices tested
Chrome on  Macbook

## Server information
PHP Version: 7.2.13

...

## phpFox version
4.7.4 (build 2)
...

**Comment by harrison05** [comment]
You can disable Custom gender option by going to **AdminCP > Members > User Group Settings**, then select Apps **User** and user groups you want to disable it (In your case, the group name is **Guest**) and turn off setting **_Can add custom gender?_**

Regards.

**Comment by jimmybsilva** [comment]
Thanks that Solved my issue
