### ISSUE TITLE
Notification not displayed til thread is clicked on phpfox community forum.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2618]
## What happened?
Notification not displayed til thread is clicked on phpfox community forum. This is likely the case for all sites as well.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
We told about this issue before, this is limitation Community Forum, but it doesn't affect to phpFox platform. 
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2396

**Comment by david-phpFox** [comment]
Hi Prepperz, 

We have fixed this issue on the Community Forum, you can check it again.

Regards,
David
