### ISSUE TITLE
'Maximum Length for Full Name' value incorrect when using non-English letters

### ISSUE THREAD

**Issue by KamAZenok** [PHPfox-Official/phpfox-v4-issues#2621]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When I use non-English (i.e. Cyrillic) letters in registration form in 'First Name' and 'Last Name' fields, one cyrillic letter counts as two latin letter. So, I need to double 'Maximum Length for Full Name' value in the 'AdminCP - Members - Manage Settings' menu.
In other words... If I set 'Maximum Length for Full Name' value to 10, I only can fit 5 cyrillic letters in 'First Name' + 'Last Name' fields. If I set value to 20, I only can fit 10 cyrillic letters... And so on...
I think it is somehow connected with Unicode/ANSI encoding...

## Browsers and Devices tested
Chrome, Microsoft Edge on Windown 10, Chrome Mobile on Android

## Server information
CentOS 7, php 7.2.17, MySQL 5.5.5-10.3.14-MariaDB, Apache)

## phpFox version
phpFox 4.7.4 (build 2)

## Screenshots
...

**Comment by harrison05** [comment]
This is a bug. We will check and fix it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.5
