### ISSUE TITLE
Upgrading pages to 4.7.4 app in admincp logs admin out and no one can login. Requires immediate attention

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2623]
## What happened?
If you click on upgrade on the pages app you it logs you and and you can't log back in. 
Clearing the phpfox cache saves your bacon.
## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
I just upgraded Pages 4.7.4 on my site, but I don't meet issue as you said. !?
Do you try to reload and sign in again?

**Comment by prepperz** [comment]
Yup. Reloaded. Did a hard refresh and same thing on chrome.  Had to manually clear phpfox cache.

**Comment by prepperz** [comment]
Tried it again, Seems the safest way is to clear cache first and then update again. No issues.

**Comment by harrison05** [comment]
On my side, I don't need to clear cache before update.
