### ISSUE TITLE
When user post a blog on pages and admin deletes blog from page, but still shows blog count as 1 on user profile

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2624]
## What happened?
Blog count not correct

## Steps to reproduce:
1. User post a blog on pages blog
2. admin deletes blog
3. goto to user profile and their blog shows count as 1

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
I tried to reproduce your issue, but it doesn't appear on my side. Page 4.7.4 and Blog 4.6.4

Regards.
