### ISSUE TITLE
Issue with mobile css dimming entire photos

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2626]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When viewing photos on mobile phones or when the browser window is resized to mobile size  to more or less mobile size, each photo is dimmed by the following css code:

@media screen and (max-width: 1024px)
.photo-listing .photo-listing-item .item-outer .item-media:after {
opacity: 1

Combine that with a mobile phone screen dimmed to 50% or when a phone is auto brightness and the photos can be barely seen.

## Steps to reproduce:
1. View photos on mobile! domain.com/photo/
2. Alternatively, resize / shrink browser window
3. 

## What's expected?
Dim only the bottom area of the photo to enclose the text overlay and the gear icon.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

All browsers.

## Server information
(Example: CentOS 7, php 7.1 apache)

Not relevant.

## phpFox version
(Example: phpFox 4.6.0)

4.7.5

## Screenshots

See dimmed vs undimmed

![image](https://user-images.githubusercontent.com/48427415/56453091-6ceffa00-630a-11e9-8f4c-dbef24066e43.png)

![image](https://user-images.githubusercontent.com/48427415/56453099-82fdba80-630a-11e9-837a-53eac9242330.png)

**Comment by harrison05** [comment]
I will check with my team about this issue and inform you if have any update.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Photos 4.7.5
