### ISSUE TITLE
Default photo ordering is wrong - Needs to order by file name by default.

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2627]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When uploading a bunch pf photos to create albums, the order in which the photos is uploaded is completely wrong. For example, cameras number files sequentially by date taken so they are properly shown in a folder by default. I go out take some photos at a concert or at the beach, then upload them... what I get is a shuffled mess of what I just uploaded. They need to keep the same order and the sequence of events. The same issue happens when uploading photos that must keep the same order and the files were intentionally named solely for the purpose of keeping a certain order, an example is a book or magazine where the file names are page001.jpg, page002.jpg and so on. I uploaded part of a book, about 10 pages and the pages got shuffled of course. Now add the fact that we can cannot reorder the files once uploaded by any meaningful criteria pertaining to the file name or date taken (or other exiff data), then this app becomes pretty much useless for real world uses and social media functionality. I have been in this industry for over 20 years and any common sense approach to this would take the files being uploaded or dragged, put them in an array, sort the array, then upload them in that order, so this way, even  if you are sorting by the ID column by default, then at least you get the order correctly.

## Steps to reproduce:
1. Just upload a bunch of photos from your phone to an album you just created.
2. Files names 001.jpg, 002.jpg etc... are shuffled.
3. No way to reorder, so the only way to upload 200 photos into an album and keep the same order as the original is to upload the 200 files, one at a time.

## What's expected?
Pu the filenames of the files being uploaded into an array, sort, then upload by the sort order.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

Any

## Server information
(Example: CentOS 7, php 7.1 apache)

Any

## phpFox version
(Example: phpFox 4.6.0)

4.7.5

## Screenshots
...

**Comment by hamadax** [comment]
Here is an example. One of my albums contains over 2000 photos that need to be in order. Totally shuffled.

![image](https://user-images.githubusercontent.com/48427415/56453329-0c16f080-630f-11e9-81ab-1ca04a846ce3.png)

**Comment by harrison05** [comment]
We will check this issue and inform you if have any updates.

Regards.

**Comment by hamadax** [comment]
Thanks. Here is another example we ran into for journalistic use. A user uploaded the 400+ pages in the Mueller report as jpg files and they were shuffled, rendering it pretty much useless without the proper order. The files were intentionally named with a suffix "Page 001, Page 002" etc...

![image](https://user-images.githubusercontent.com/48427415/56500553-564bcd80-64d9-11e9-88e6-4b0bbf760dd1.png)

**Comment by david-phpFox** [comment]
Hi all,

We will check and support user can drag/drop to reorder photos in the edit album page. 
And support the user can sort by the title of photo (A-Z, Z-A) in photos page (All Photos, My Photos, Friends' Photos, User's Photos, Page's Photos, and Group's Photos)

These features will available in the next version of the Photos App.

Regards.
David

**Comment by david-phpFox** [comment]
Improved in Photos 4.7.5
