### ISSUE TITLE
Adding image in blog via browse cuts off top portion of image

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2629]
## What happened?
When adding an image to the blog via browse file it cuts off the top portion of the image and does not keep the original proportions of the of the original image....

## Steps to reproduce:
1.  Add blog
2. browse file for image
3. 

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

## Screenshots
...

**Comment by david-phpFox** [comment]
Fixed in Blog 4.6.5
