### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2631]
Hello,
Is that normal that i dont have captcha in my DB?
![captcha](https://user-images.githubusercontent.com/46829598/56471425-aaf83580-6452-11e9-88bc-8ca4d6073564.png)
![CAPTCHA](https://user-images.githubusercontent.com/46829598/56471427-afbce980-6452-11e9-9e46-bb9713d397af.png)

**Comment by harrison05** [comment]
Yes, this is normal. Captcha App doesn't save data to your database.

Regards.

**Comment by AmineBAIK1** [comment]
It doesnt save my captcha type? my recaptcha type? my Google ID? So where they are save 
Regards

**Comment by harrison05** [comment]
They are saved in the Setting table.

Regards.
