### ISSUE TITLE
Posting as page for photo and video is inconsistent

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2632]
## What happened?
Posting as page for photo and video is inconsistent. For example you can post as page for photo or video in status, but not in the photo or video section of the page. 

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
Page owner should consistently be able to post as page in all sections and aspects of the page, but is not the case.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.4 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
> For example you can post as page for photo or video in status, but not in the photo or video section of the page.

I check this case, you absolutely can post photo/video when login as Page in the Photo/Video section.
![Screen Shot 2019-04-23 at 11 05 31](https://user-images.githubusercontent.com/41947198/56553172-c29cfe80-65b7-11e9-8b0e-1d3b40abf00d.png)

**Comment by prepperz** [comment]
Ah ok. I haven't tried login as page.
