### ISSUE TITLE
When splitting first and last name, form validation does not work properly

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2634]
# Important

Please follow this template!

----------------------------------------

## What's happened?
I split the full name into first and last name, now the registration form is not validating the names properly when the registration is done via multiple pages. The validation fires up in the last step and the user loses the photo they uploaded in previous screen, location and google recaptcha.

Validation of first and last names needs to be in the first screen just like it does with full name. 

I have to disable this method for now.

## Steps to reproduce:
1. Split first and last name from admincp setting
2. Make you registration multi-step
3. Validation fails for first and last name, photo uploaded is lost as well as location and google recaptcha.

## What's expected?
This needs to be fixed asap imo.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.6
