### ISSUE TITLE
Extra spacing in member cover text... Lives in -- Country

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2636]
# Important

Please follow this template!

----------------------------------------

## What's happened?
There is an extra space in the user's profile header text. Lives in space space United States.

## Steps to reproduce:
1. Look at any profile where the setting would render Lives in <country>
2. 
3. 

## What's expected?
Remove extra space.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/56675457-1a0b9f00-668a-11e9-8d41-be690db9c6fe.png)

**Comment by david-phpFox** [comment]
Fixed in Material Theme 4.7.6
