### ISSUE TITLE
When impersontaing a user with "login as", the IP address of the user is replaced with the admin's

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2637]
# Important

Please follow this template!

----------------------------------------

## What's happened?

Login as user should be done incognito, the ip address of the last login is replaced with the admin's ip address. The user will see this with some apps. The idea of having this option is for diagnostic and investigative matters. Both scenarios should not log the admin's ip address.

## Steps to reproduce:
1. Use the login as user feature in the admincp
2. Check the ip of last login.
3. 

## What's expected?
Never log the ip of an admin logging as a user. This is not how it is done! The user will see this with some apps. The idea of having this option is for diagnostic and investigative matters. Both scenarios should not log the admin's ip address.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
It works as designed. User should know that IP to control who logged into their account. We won't fix this case.

Regards.

**Comment by hamadax** [comment]
Thanks for your input. Here is my five cents on this. What is the purpose of this feature? I can only think of two main functions: diagnostic and investigative matters. Example: A police subpoena or court order that needs immediate attention and the admin needs to login as this user to gather evidence quickly and visually. Another is to provide support.

If the user is able to block the admin's IP addresses, then this feature is useless for the admin. I have programmed something like this ages ago and made sure that admins impersonating users' logins are doing so incognito. It takes a few lines of code to fix this.

I know official requests would alternatively be done from the database itself, but why have this feature in the first place if it cannot keep the admin's session private.

If you use exchange server, the server admin can have or assign full control over mailboxes for example, but during that login session, the IP will never be logged in a way that is shown to the user. because it would be corrupting login data for that specific user. What happens instead is the session itself is tagged as an admin session, but the end user never sees this and even if you prepare a litigation report, the admin IP will never show there.

Anyhow, I have seen this done properly in other applications, you guys just missed the final touch!

**Comment by lethality** [comment]
I'm inclined to agree with hamadax, that a user shouldn't be aware of an administrators IP address. Name any other service that will tell you the personal information of someone who has administered your account?
Of course there's multiple, and different reasons in which people will use this tool, and not all of them ethical, but generally, if I'm running a site, my admin are trusted to be carrying out actions for a legit reason and should do so without their details being revealed.
