### ISSUE TITLE
Need pagination for ban section

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2643]
# Important

Please follow this template!

----------------------------------------

## What's happened?
I am banning thousands of names, over 100K records. All are being loaded into the ban section from the admincp. I loaded them directly into the database. Now, if I go to edit them, the page will most surely time out or the browser will crash since it is trying to load them all in one shot.

## Steps to reproduce:
1. Load ban list into database. I use dictionary of bad words, brand names, and other proprietary lists. Will go over 100K records.
2. Go to ban section in admin cp to edit or even look at...
3. Page times out or crashes browser.

## What's expected?
Need to put pagination and search functions.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
Ok, we will improve it.

Regards.

**Comment by david-phpFox** [comment]
Improved in Core 4.7.6
