### ISSUE TITLE
Vimeo and dailymotion videos not showing thumbnails

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2644]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Adding a video from Vimeo and dailymotion works but does not generate a thumbnail for the video.

## Steps to reproduce:
1. Use the video app to add any video from vimeo or dailymotion
2. Check the video in the video app
3. Video has no thumbnail preview.

## What's expected?
Have it generate a thumbnail preview like YouTube videos.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/56678876-b5ecd900-6691-11e9-8c31-baf02adb9a47.png)

**Comment by harrison05** [comment]
Which Video version you are using? Because I checked on our site and they have thumbnails.
![Screen Shot 2019-04-26 at 11 04 05](https://user-images.githubusercontent.com/41947198/56782871-38e96d00-6813-11e9-8947-e274e6f78ef5.png)

Regards

**Comment by hamadax** [comment]
Negative. It does not work. I am using latest. 4.7.4

Reinstalled, rebuilt core theme, cleared cache. Still not working.

Here is one of my test videos: https://vimeo.com/330664249

![image](https://user-images.githubusercontent.com/48427415/56899062-8575b800-6a60-11e9-9b1a-a177699544d6.png)

![image](https://user-images.githubusercontent.com/48427415/56899116-aa6a2b00-6a60-11e9-91c7-77e0ef5ed73c.png)

**Comment by harrison05** [comment]
It works on my site
![Screen Shot 2019-05-02 at 09 37 42](https://user-images.githubusercontent.com/41947198/57054321-14cbd700-6cbe-11e9-9c53-d57b6208e74c.png)
I think this is an issue with your site only, you can submit a ticket and our support team will check directly on it. 

Regards.
