### ISSUE TITLE
Blog view count is counting page refresh or impressions, not actual views; when users are logged in with invisible mode

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2646]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Go to any blog article and click refresh the page a few times. The view count keeps going up with every page refresh. This is not correct. This will result in artificial manipulation / abuse of search and sorting via most views.

## Steps to reproduce:
1. See above. Views in this sense is acting like an impression.
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
Yes, If you want to prevent this case, you should go to **AdminCP > Apps > Track** and enable setting **Unique viewer counter**

![Screen Shot 2019-04-26 at 13 49 16](https://user-images.githubusercontent.com/41947198/56788749-76a5c000-682a-11e9-9d7a-a13ad3c1f792.png)

Regards.

**Comment by hamadax** [comment]
Yes I am aware of this option and it has always been turned on. I tested this a few times with this option turned ON and OFF. Always counts with page refresh. It's a bug as far as I can tell.

**Comment by harrison05** [comment]
I can't reproduce the issue as you said. It's working well with the newest version of Blog App 4.6.5

**Comment by hamadax** [comment]
> 
> 
> I can't reproduce the issue as you said. It's working well with the newest version of Blog App 4.6.5

I found the issue... It's not working if you are a logged in user. Just tested it. Works fine with anonymous visitors, any logged in user is able to refresh page and it keeps counting regardless of the setting. BTW, I am using latest versions of track, core and blogs. Everything is stock and updated.

**Comment by hamadax** [comment]
This issue will easily allow manipulation of views. Another issue here that should not be there on a production site. IS there a quick fix to this that I can apply to the code?

**Comment by harrison05** [comment]
> I found the issue... It's not working if you are a logged in user. Just tested it. Works fine with anonymous visitors, any logged in user is able to refresh page and it keeps counting regardless of the setting. BTW, I am using latest versions of track, core and blogs. Everything is stock and updated.

I tested with a logged in user but it still disappears. You can check on our demo site, the counter is working right. If issue still appears on your site, please submit a ticket and our support team will help you check.

Regards.

**Comment by hamadax** [comment]
I submitted a ticket. It's a bug. Please note that to reproduce this, the user has to be in invisible mode. So any user browsing in invisible mode can cheat the system. Here is the reply from support:

> The cause of the issue is this account has enabled "Invisible Mode", please disable this setting (/user/privacy/ --> Invisible Mode) and check again. However, it's confusing for user, we'll improve this function in the future.

I really do not want to disable this for certain users so I can't just disable it. Please come up with a fix soon. Thanks!

**Comment by harrison05** [comment]
Our support team will check and respond as soon as we can.

Thanks.
