### ISSUE TITLE
Bug in \Core\Theme\Objects.php

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2647]
Line 235

I think the Line 
`if ($type == 'app' && file_exists(PHPFOX_ROOT) . $path) {`

must be changed to 
`if ($type == 'app' && file_exists(PHPFOX_ROOT . $lessPath)) {`

**Comment by kerstar** [comment]
@Bjoern3003 

Can you tell me how this bug affects the site? 
This bug affects security? What does it show up with?

Thank you.

**Comment by Bjoern3003** [comment]
He does not find/parse css files, who are implemented in apps with setHeader function.

**Comment by kerstar** [comment]
@Bjoern3003 

Thanks for explaining.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.6
