### ISSUE TITLE
Register Block

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2648]
Hello,
I Have deleted the lines of user terms accept in user.controller.register.html.php and added them to user.block.register.step2.html.php it's deleted it's not displayed but cant go through the second step because its still required somewhere.... is there any Js file that did this? 
Regards.

**Comment by AmineBAIK1** [comment]
![Capture d’écran de 2019-04-29 18-17-50](https://user-images.githubusercontent.com/46829598/56911015-348bb100-6aac-11e9-885f-b0556ac60e63.jpg)
![Capture d’écran de 2019-04-29 18-18-58](https://user-images.githubusercontent.com/46829598/56911016-35244780-6aac-11e9-9e35-289b6e589666.jpg)

**Comment by harrison05** [comment]
You should update function **\User_Service_Register::getValidation**, because this function push validates **terms and conditions** to step 1, you should move it to step 2

Regards.

**Comment by AmineBAIK1** [comment]
Thanks Harrison! You are clearly the most performant support at phpfox
