### ISSUE TITLE
Banned users still showing in Friend Suggestions and Members

### ISSUE THREAD

**Issue by jwpwhite** [PHPfox-Official/phpfox-v4-issues#2654]
## What's happened?
Banned users still showing in Friend Suggestions and Members.

## Steps to reproduce:
1. View banned users shown in the Suggestions block
2. View banned members show in the Members page

## What's expected?
I would expect banned users to not be visible to user on the platform.
From what I can see, the only way to stop them being show on the platform is to delete them. However, if you do this then they can just use the same email address to create a new account!

## Browsers and Devices tested
Chrome on Windows 10

## Server information
AWS ELB

## phpFox version
phpFox 4.7.3

**Comment by harrison05** [comment]
Ok. We will check this case and inform you later.

Regards.
