### ISSUE TITLE
Format Number (eg. Activity Points) in Template files

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2655]
On many templates pages are the number_format smarty function using to format number.

We are using . as thousands Delimiter and , for decimal. The easiest way could be to add a modifier in cache.class.php or impliment the plugin function for functions an modifiers, that you have startet in Line 1667.

**Comment by harrison05** [comment]
Oh, as I know, number_format also support you to change thousands/decimal Delimiters with the following syntax:

```php
number_format:(int_decimals):(string_decimal_separator):(string_thousands_separator) 
```

**Comment by Bjoern3003** [comment]
You mean in Template directly? Of course. But I think it is easier to add modifier function to change it on all positions in template with one custom change or Setting in Backend. So all third party developer can use it also.
