### ISSUE TITLE
subscribe

### ISSUE THREAD

**Issue by erick260** [PHPfox-Official/phpfox-v4-issues#2656]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When you have Subscription on registration is required, an also have a free package users can pick. When clicking an registering with a package that cost you cannot edit your membership too switch back too normal free package.

## Steps to reproduce:

1. Enable Subscription on registration is required.
2. in Subscriptions create two packages one free an one that cost. Select Add to Registration on both.
3. Create a new account an choose the membership that cost. 
4. Once registered you cannot choose too switch too another membership.  
 5. On admincp-browse users that user is created in Registered User even if they selected the premium membership. So us admins can't really tell the user is really locked out due too they can't switch memberships

## What's expected?
The user account gets locked because they cannot switch memberships

## Browsers and Devices tested
Chrome On WebKit AndroidOS 5.1.1

...

## Server information
PHP Version: | 7.1.28

Core Version: | 4.7.5
-- | --

- | --

## phpFox version
(Core Version: | 4.7.5
-- | --

...

## Screenshots
...

**Comment by harrison05** [comment]
Users can change the package after signup. They can click on the arrow down at the corner right and select Membership, then redirect to Membership Packages and select another package. See my screenshot
![Screen Shot 2019-05-04 at 09 44 08](https://user-images.githubusercontent.com/41947198/57172968-c8b19b80-6e51-11e9-97ac-a8a5dca3dc35.png)
