### ISSUE TITLE
No space break does not work in messages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2657]
## What happened?
No space break break (shift+enter) does not work.

## Steps to reproduce:
1. Create or reply to a message 
2. Use shit+enter in the message
3. send

## What is expected?
For no space break to work, but it does not

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.5 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Which app are you using? Default **Message App** or **Instance Message App**

**Comment by prepperz** [comment]
Default message app

**Comment by harrison05** [comment]
You can use Enter key to break line instead of Shift + Enter

**Comment by prepperz** [comment]
There are times when you need to use shift+enter instead of just enter. As it gives two different results.

**Comment by harrison05** [comment]
Currently, the Message App only supports one result for break line.
