### ISSUE TITLE
Support Unicode

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2658]
In my case, we have Pages, who are have unicode in the Page title.

For example: &#x1f6d2; Discounter Werkzeug &#x1f6d2;
`&#x1f6d2; Discounter Werkzeug &#x1f6d2;`

In the ProfilePopUp Add from younetco, is it working well.

![08052019152159](https://user-images.githubusercontent.com/13675579/57378566-54565f80-71a5-11e9-98c6-c2e3c2a4a4bf.jpg)

https://prnt.sc/nm0i6b

**Comment by harrison05** [comment]
Oh, Which Unicode you add to the page title when create,  **&#x1f6d2 ;** or  🛒 ? 
the Unicode icon is working well on my site
![Screen Shot 2019-05-09 at 10 30 25](https://user-images.githubusercontent.com/41947198/57425490-87e8c680-7245-11e9-97d4-c5e1cf32f6b6.png)

**Comment by Bjoern3003** [comment]
I have tried both.

When I add Icon direct, I see it in input field title. After Submit, I only see "?" as Titlename, as placeholder for the Shoppingcart icon. He is also store the Icon as ? in Database

If I add the HTML Code, I only see the plain HTML Code as Title name like my screenshot. But the ProfilePopUp shoing the Icon correct. And he is saving & as &amp;

The Database is created as InnoDB utf8_general_ci

**Comment by harrison05** [comment]
You can try switch your Database to utf8mb4 and check again. This is why I said that

>  In MySQL utf8 uses 3 bytes to store a character and cannot store every utf-8 character, you need 4 bytes for this and therefore you need utf8mb4

**Comment by Bjoern3003** [comment]
How does it store in your database? can you add a screenshot? 

Why I ask? I have tried a second fresh phpfox installation on a different server. There is no problem with unicode. Now I want to see, why its not working at the other one.
Both Datatables on the different Server has the same configuration.

To your answer: I have tried to change Database/Table and row to utf8mb4 and add again a new Page. The same result. Maybe its a server configuration, how he is insert the data to Database (Charset). I can not find a Setting in phpfox, who is set the Datatable charset for connect.

**Comment by harrison05** [comment]
It store in my database like this:
![Screen Shot 2019-05-13 at 09 48 30](https://user-images.githubusercontent.com/41947198/57593162-70bb1900-7564-11e9-9510-d86cfdd02f46.png)
And I use collation latin1 and phpfox use default charset on your DB config to setup for Apps.
![Screen Shot 2019-05-13 at 09 49 05](https://user-images.githubusercontent.com/41947198/57593192-8c262400-7564-11e9-922f-52c113961de5.png)

**Comment by Bjoern3003** [comment]
Okay, this looks like my Database entry on my second server. I don't understand it. But I have to search the Problem on my SQL Server.
