### ISSUE TITLE
Apps that are disabled are showing in main menu after being updated or activated then deactivated.

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2659]
# Important

Please follow this template!

----------------------------------------

## What's happened?
After updating the marketplace app, it appeared in the site main menu. I have it disabled so why do this? Same thing for apps that are activated then deactivated.
## Steps to reproduce:
1. Activate, then deactivate app.
2. Remove from site menu.
3. Activate, then deactivate app again.
4. The menu item remains and of course it goes to page not found since it is deactivated.

## What's expected?
1- Any deactivated app should not show in site main menu.
2- Updating a deactivated app should not put it in the main menu! It's still deactivated.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by hamadax** [comment]
Also apps that are activated, deactivated, then activated or updated lose their previous position in the main menu. As soon as I updated the video app, it moved to the last position. As soon as I updated the marketplace app (which was deactivated), it appeared in the last position and yielded a page not found, since it was disabled!

**Comment by harrison05** [comment]
I can't reproduce it with your step. When App is disabled, its menu on the main menu will be disabled too, checked on version 4.7.5.
Issue menu auto enable is fixed before at #2487
