### ISSUE TITLE
Filter is not retained and does not work properly in admincp

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2661]
## What happened?
Filter is not retained and does not work properly in admincp when there are multiple pages as you delete pending users.

## Steps to reproduce:
1. Goto members in admincp
2. View more search options > show members > pending verification members > search
3. Search results in multiple pages
4. select delete

## What is expected?
Filter results should be retained, but instead it just resets after it's delete instead of showing the remaining results so you can continue to delete the the pending registries. Extremely annoying annoying. There should also be an option to delete the entire pending registries.

Back-end user maintenance has always been historically weak and sloppy and really needs vast improvements.  It would be a nightmare for sites dealing with lots of users with the current back-end state.
 

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.5 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
I check on my site. When delete a user in AdminCP, page doesn't reload, it updated in the background and remove that user from list. How that issue occurs on your site?

**Comment by prepperz** [comment]
That's the problem. Once it removes the users, it then resets. For example if you have more than 10 pages worth or it can become a nightmare and extremely annoying because it's like 1 step forward and 10 steps backward.

**Comment by harrison05** [comment]
Oh, I got it, you're using multiple delete with **Delete** button at the bottom right. 
Yes, It reset page. Our team will check and find a solution to improve it.

Thanks.

**Comment by prepperz** [comment]
Correct.

**Comment by david-phpFox** [comment]
Improved in Core 4.7.6
