### ISSUE TITLE
call profile photo and cover in member index

### ISSUE THREAD

**Issue by EgyCheETah** [PHPfox-Official/phpfox-v4-issues#2663]
phpfox how to call profile photo and cover in member index?

[https://i.stack.imgur.com/DAhdD.jpg](url)

i have try many codes 

`<img width="70%" src="<?php $avatarpath = Phpfox::getParam('core.url_user');$avatarpath .= Phpfox::getUserBy('user_image');$avatarpath = str_replace("%s","_200",$avatarpath);echo $avatarpath;?>"/>`

and many other codes but get nothing

**Comment by harrison05** [comment]
Did you add this code in Block with type PHP Code?
![Screen Shot 2019-05-16 at 10 17 27](https://user-images.githubusercontent.com/41947198/57824029-dfe27880-77c3-11e9-98ef-011bd0d99358.png)
Or if you're using PHP Block File, you can handle object user in the controller and assign to view to show image by {img ... } tags.

**Comment by EgyCheETah** [comment]
@harrison05 would u give me a tip plz ?

**Comment by harrison05** [comment]
You can add a block with type PHP Code in AdminCP (See my previous screenshot).
Or, If you're working on a 3rd App, you can add a new block component and use 
**{img user=$aUser suffix='_200_square'}**  with **$aUser** is object assign from block component.
then add that block to your site

**Comment by EgyCheETah** [comment]
Really sry about dat

But could u plz tell me which control file i can edit ? With code 

So i can post profile items like name, photo and cover at any block in member index  ? {img} or { any profile tags }

Thx in advance for kindly reply and ur help

**Comment by EgyCheETah** [comment]
Up @harrison05

**Comment by harrison05** [comment]
If you want to know how to add a block, please check phpFox document:
https://docs.phpfox.com/display/FOX4DEVDOC/Add+First+Block

Regards
