### ISSUE TITLE
Feed cuts off the top of the blog image

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2665]
## What happened?
When adding an image to the blog, the image is cut off at the top in the feed.

## Steps to reproduce:
1. Create a blog
2. Browse photo (1204 x 655)
3. publish

## What is expected?
...Should be showing full image in the status feed, but does not.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.5 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
Yes, because that image on feed is using as a background image, so we limit the height of parent container and stretch image to fit the layout. User can click on it to view full image at detail blog page.

**Comment by prepperz** [comment]
Is it possible to stretch it in a way to display the full image? It just looks like it's broken when it's cut off.

**Comment by harrison05** [comment]
We can stretch it in like detail page to display the full image. But it seems a not good layout on feed.
I will check will frontend team and inform you later.

**Comment by david-phpFox** [comment]
Fixed in Blog App 4.6.6
