### ISSUE TITLE
Admincp

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2667]
Hello, 
Since this morning, My site went all blank just by himself, i though it were a cyber attack but looked at my files in server.. they are still here. But cant acces site just got blank everywhere even in Admincp... tried to force-flavor with an other theme still nothing. 
So my question is How can i rebuild core theme/clear cache if i have not acces to the admin CP and when it's all blank.
What can i do ? can i rebuild core theme from the server without get acces to adminCp.. ?

**Comment by AmineBAIK1** [comment]
After adding a trigger line that was missing for no reason.. its not blank anymore but got 500Error page with code : Error code: 8cc661

**Comment by harrison05** [comment]
> What can i do ? can i rebuild core theme from the server without get acces to adminCp.. ?

If you are using File System cache, you can remove cache by delete folder: PF.Base/file/cache. But rebuild core theme, you have to do that in AdminCP, try to access URL: your_domain/admincp/theme/bootstrap/rebuild/

About your error (Error code: 8cc661), you can check this code in PF.Base/file/log/main.log to see the reason.

Regards.
