### ISSUE TITLE
Site acting up after adding Adsense code with Analytics activated in another block

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2668]
# Important

Please follow this template!

----------------------------------------

## What's happened?
I followed instructions for adding google adsense code. Regardless of what block is chosen, some pages are failing to load and some have layout broken.

## Steps to reproduce:
1. Added adsense code to block 5.
2. Analytics code is in another block. 1 or 3.
3. Pages do not load or layout breaks until I deactivate google adsense code.

![image](https://user-images.githubusercontent.com/48427415/58343215-6defdc00-7e20-11e9-820c-e73dde1e28dc.png)

## What's expected?
Explain how we can activate both at the same time on the same pages.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

all

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by hamadax** [comment]
Should I be linking analytics to ads or combining the google snippets?

**Comment by harrison05** [comment]
Do you disable full ajax mode on your site?
We noted in our document for Google Adsense: https://docs.phpfox.com/display/FOX4MAN/Setting+up+Google+Adsense
