### ISSUE TITLE
Incorrect coding of some feed news feed links

### ISSUE THREAD

**Issue by websistema1** [PHPfox-Official/phpfox-v4-issues#2670]
When adding to the feed some links whose sites contain Ukrainian coding (lang = \"uk\"> <head> <meta http-equiv = \"X-UA-Compatible\") or (charset = windows-1251 \") - the sites are displayed with broken coding.
For example, the link https://goloszmin.org or https://replyua.net is displayed with a damaged encoding. 
For phpFox 4.7.5

![2019-05-23_212241](https://user-images.githubusercontent.com/14079310/58378931-ff885680-7fa4-11e9-9252-07fe1e44cdcc.jpg)

![2019-05-23_212312](https://user-images.githubusercontent.com/14079310/58378936-0616ce00-7fa5-11e9-8f01-2b658354d017.jpg)

It is urgently necessary to fix this, because of this, users do not want to use the site, since Ukrainian news is displayed incorrectly on the feed.

**Comment by harrison05** [comment]
This is a bug, we will fix in the next version of phpFox. If you want a hotfix on your site, please submit a ticket, our support team will check it.

Regards.

**Comment by websistema1** [comment]
I sent a ticket to correct

Regards

**Comment by harrison05** [comment]
> I sent a ticket to correct
> 
> Regards

Our team will help you fix it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.6
