### ISSUE TITLE
Photo module update 

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2671]
Hello, 
Recently installed the new update of Photos and tried to drag photos in edit album photo somestimes it working sometimes got that photo is not with the cursor and go down
![Capture d’écran de 2019-05-28 16-25-06](https://user-images.githubusercontent.com/46829598/58486110-8d12a480-8165-11e9-88ff-9306eff97b0a.jpg)

**Comment by harrison05** [comment]
Do you mean drag & drop photos sometimes work but sometimes not (can't drag photos)?

Regards

**Comment by joblux** [comment]
well to me its  clear on the screen shot that when moving third picture to the right, there is an issue with the over all lay out of the photos ...

**Comment by harrison05** [comment]
I can't reproduce this issue on my site. You should submit a ticket and our team will check it on your site.

Regards.
