### ISSUE TITLE
Missing phrases in subscription app

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2672]
## What's happened?

Some phrases can not be translated.

## Steps to reproduce:

Try to translate the period value that shows on package item on index page e.g. "monthly".

## What's expected?

Should be possible to translate as phrase.

/service/subscription.php starting at line 186

## phpFox version

phpFox 4.7.5
Subscription App 4.6.4

...

**Comment by david-phpFox** [comment]
Fixed in Subscription 4.6.5
