### ISSUE TITLE
Missing phrase "most popular" in subscription app

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2673]
## What's happened?
"most popular" can not be translated.

## phpFox version
phpFox 4.7.5
Subscription App 4.6.4

**Comment by harrison05** [comment]
You should search by the text "Most Popular" at **AdminCP > Globalization > Phrases** and translate all phrases with this value. (This phrase on Subscriptions app have a variable like: "app_....")

Regards.

**Comment by kibcode** [comment]
the phrase only works in admincp. "Most Popular" badge on subscription index is a hardcoded string in the template file.

**Comment by harrison05** [comment]
Ok, I found it. We will fix this issue.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Subscription 4.6.5
