### ISSUE TITLE
Add a block

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2674]
I Want to create a block in AdminCp with Phpcode and put the file tooltip.html.php on it to get this tried with this approch https://docs.phpfox.com/display/FOX4DEVDOC/Add+First+Block but get error 500 when i past the following code $module->addComponentNames('block', [
    'todo.recent_items' => Block\RecentItems::class,
]); for exemple ... Where to past it ?

**Comment by harrison05** [comment]
If you add **'todo.recent_items' => Block\RecentItems::class** to **addComponentNames** function, your view file must have file name is: **recent_items.html.php**

Regards.

**Comment by AmineBAIK1** [comment]
Ok, Is it possible to add this 
![Capture d’écran de 2019-06-10 16-56-01](https://user-images.githubusercontent.com/46829598/59204483-0320fd80-8ba1-11e9-8fb7-f40910c351d9.jpg) In a block for exemple in Member home page? [The Screen is when you hover a username is user/browse

**Comment by AmineBAIK1** [comment]
to show my profile

**Comment by AmineBAIK1** [comment]
@harrison05

**Comment by harrison05** [comment]
Yes, this popup is a block from module User, you can found its source at: 

**PF.Base/module/user/include/component/block/tooltip.class.php**
**PF.Base/module/user/template/default/block/tooltip.html.php**
