### ISSUE TITLE
When ADDING friend, otherside cannot close Notification dropdown

### ISSUE THREAD

**Issue by cyberhmong** [PHPfox-Official/phpfox-v4-issues#2676]
phpfox4  Version 4.7.5

When ADDING friend, they cannot close dropdown notification after clicking ACCEPT.
note: The accept is a success though if you ignore this and hit refresh.

ReCreating is simple, just ADD, other user accepts and it gives error 500 in debug. Notification drop down does not close.

Type of error.
jquery.js?v=7b3eec6e0aaf4bd3bd25b1da0d3a5fa9:9659 POST https://www.site.com/_ajax/ 500 (Internal Server Error)

Which file causing this?
jquery.js
/home/admin/public_html/PF.Base/static/jscript/jquery/jquery.js

Type of server:
centos webcpanel
Nginx-->Varnish-->Apache-->php-fpm

**Comment by harrison05** [comment]
I can't reproduce it on my site. It might be an issue on your site. You should submit a ticket in the Client Area of phpFox, our team will help you to check.

Regards.
