### ISSUE TITLE
Shift+Break is not retained in widget ckeditor

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2677]
## What happened?
Shift+break not retained in widget ckeditor

## Steps to reproduce:
1.  make a table with 3 column.
2. In column 2, type a word and then shift+break and then another word.
3. Save it. (it will work properly)
![Screenshot1](https://user-images.githubusercontent.com/19594886/58689567-6024e400-8355-11e9-99c2-99f4a502784f.png)

4. Go back to widget and edit again and it will show that shift break is not retained.
![Screenshot2](https://user-images.githubusercontent.com/19594886/58689575-66b35b80-8355-11e9-9c60-46f90df2203d.png)

## What is expected?
Shift+break should be retained, but does not when going back to re-edit.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.5 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
"Shift+break not retained in widget ckeditor" 
Could you explain more about the widget? Where did you get it? Or take a screenshot.

Regards.

**Comment by prepperz** [comment]
It's the pages / group widget. I've updated the above to include screenshots.

**Comment by david-phpFox** [comment]
Fixed in Pages/Groups 4.7.5.
