### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2678]
Hello, 
What does it mean ? The no invoice ? 
Because i sub to a package and i didnt recevied anything on Email or A popup with the invoice Nothing. 
![Capture d’écran de 2019-05-31 17-10-05](https://user-images.githubusercontent.com/46829598/58715505-49b77080-83c7-11e9-93be-c29f701ee3d2.jpg)

**Comment by harrison05** [comment]
It means if user signup and buy a package but they don't pay it immediately, the subscription app will save that payment as a pending invoice. But next time, user login, subscription can't found this pending invoice to show purchase popup again > user can't pay to login.

Regards.

**Comment by joblux** [comment]
to save  a payment as an invoice ? what does that even mean ?

**Comment by joblux** [comment]
Can you explain the whole logic of the invoicing please, clearly.

**Comment by harrison05** [comment]
> to save a payment as an invoice ? what does that even mean ?

When users select a package has fee after signup and go to checkout page, we create an invoice for it and mark status is pending. If they don't pay it, the next time login, they will be redirected to checkout page again to pay that invoice.

**Comment by joblux** [comment]
where are the invoices retrievable, i cant get to se eany of those generated invoices...

**Comment by AmineBAIK1** [comment]
What's the URL of The Pendings Membships?

**Comment by AmineBAIK1** [comment]
site/ad/invoice exists but site/subscribe/invoice doesnt exist ? Why? is there an other alternatif or an other URL for this?

**Comment by harrison05** [comment]
You can find all your subscription plans at (My subscription): **<site_domain>/subscribe/list/**, if you click on package image, it will redirect to detail and show invoice list.

**Comment by AmineBAIK1** [comment]
Ok thanks What's the link for  Pending membships ? <site_domain>/subscribe/ ?????

**Comment by harrison05** [comment]
@AmineBAIK1 This is: /subscribe/list, it also shows the pending subscription
![Screen Shot 2019-06-11 at 09 51 59](https://user-images.githubusercontent.com/41947198/59240435-a53af700-8c2e-11e9-8269-92ed19895a9d.png)
