### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2679]
Hello, 
I Am trying to put a default date of +30 after today like if today is 06/01/2019 The first june 
I want to display the 07/01/2019 the first of july. 
I am editing this 
![Capture d’écran de 2019-05-31 22-10-04](https://user-images.githubusercontent.com/46829598/58732273-50f37400-83f1-11e9-94cf-84de646d3754.jpg)
But i got everytime the same date " Thecurrentdate" 
![Capture d’écran de 2019-05-31 22-08-54](https://user-images.githubusercontent.com/46829598/58732285-5ea8f980-83f1-11e9-9c82-3c9d4fe44f4f.jpg)
How it's possible? Even when i put a simple number in start_month 6 for june 
i didnt get it ...

**Comment by harrison05** [comment]
Ah, select_date doesn't support start_month and start_day, it only supports start_year. With your case, you should assign your expected date in **$aForms** object from controller.
Example: your date_prefix is **time_expire_**, in your controller, should use assign function with:
```php
$this->template->assign(array(
      'aForms' => [
                  'time_expire_month' => date('n', strtotime('+1 month')),
                  'time_expire_day' => date('j', strtotime('+1 month')),
                  'time_expire_year' => date('Y', strtotime('+1 month'))
             ]
));
```
Remember that, you only assign default **$aForms** when create new item, when edit, it must be value of the current item.
