### ISSUE TITLE
currency position of price display

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2681]
In Germany, the Currency Symbol is placed AFTER price. You have hardcoded the currency symbol on each position in front of the price.

Please add a template function (for example as modifier) to format the price like https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2655 and position the symbol. 

The position of currency symbol and number format should configurable in backend.

**Comment by harrison05** [comment]
You can config format of Currency at **AdminCP > Globalization > Currencies**

Regards.

**Comment by Bjoern3003** [comment]
Yes, but not on all places.

Example? 
Have a look at: PF.Site\Apps\core-activity-points\views\controller\package.html.php Line 26 and 30

**Comment by harrison05** [comment]
Oh, this is a mistake, It should apply the currency format from Admin. We will check and fix it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Activity Points 4.7.6
