### ISSUE TITLE
Jobposting / Subscriptions / Feature / Memberships

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2682]
Hello, 
I set up and paypal sandbox then i tried to Add a job then i selected the option feature the job with money !! that redirected me to Paypal payement i Paid with my sandbox account ! 
the payment was accepted But  The job was not featured and if i feature the job with the admin that works. 
Same thing if i try to upgrade membship the payment is accepted by am still in the same  group the upgrade didnt work and didnt put me in the succes group.

**Comment by harrison05** [comment]
You can check the merchant PayPal account, what is your transaction status? Does it mark as completed or wait to approval?

**Comment by AmineBAIK1** [comment]
![Capture d’écran de 2019-06-10 17-08-34](https://user-images.githubusercontent.com/46829598/59205103-68c1b980-8ba2-11e9-8b51-0d6aa017d56f.png)
![Capture d’écran de 2019-06-10 17-07-32](https://user-images.githubusercontent.com/46829598/59205152-8ee75980-8ba2-11e9-9683-21153a72821f.jpg)

**Comment by AmineBAIK1** [comment]
Yes I got the payement and i got the notification for the buyer and for the buisness account ! But the user who paid the 100$ for a package in this example is still not upgraded and still basic.

**Comment by harrison05** [comment]
Which type of your subscriptions package? One time or Recurring, please try to test both of them. Sandbox mode on PayPal sometimes needs a delay time to return callback to phpFox site for update transaction. I used to wait a day when working with it.
