### ISSUE TITLE
Single line break containing URL is not displayed on a separate line in photo description for pages

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2685]
## What happened?

Single line break containing URL is not displayed on a separate line in photo description for pages.

## Steps to reproduce:
1. Add a one line description and hit enter
2. On the second line type in a url and save.
3. 

## What is expected?
The description should be displayed on one line. The url should be displayed on the second line.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.5 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
This might a bug from Core, we will check it.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.7.
