### ISSUE TITLE
Location 

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2686]
In some sites there is an autocomplete location at the input like if i put "Pa" that will show me 
Paris,France an others for exemple. 
![TCi94](https://user-images.githubusercontent.com/46829598/59452692-9874f980-8e0e-11e9-928b-ccdd98504887.jpg)
So, My question is : Why in phpfox the location it's still a basic input.?

**Comment by harrison05** [comment]
Because we don't integrate location with Google Place Autocomplete.
You can request this feature at PHPfox-Official/phpfox-v4-feature-requests, and we will review it.

Regards.

**Comment by AmineBAIK1** [comment]
Ok, Thanks i will.

**Comment by spirogg** [comment]
Is the Google place still free to use or do we need to pay for it per use ? or per view this might be something to discuss or explain to admins before making that option.

**Comment by harrison05** [comment]
Ya, it free but limited usage, when you reach the limit, you must pay for it. Check out their pricing at https://cloud.google.com/maps-platform/pricing/sheet
