### ISSUE TITLE
Mobile LandingPage

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2688]
Hello,
I have customized my LandingPage on desktop but i want to open material default landing page in mobile and maybe Tabs too.. 
Whats the best way to do that? I'v tried we UserAgents With Conditions on Screens got everytime blankpage?! 
Phpfox allow this? thanks

**Comment by harrison05** [comment]
Yes, we usually use UserAgents to check it's desktop or mobile. Example:

```javascript
/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)
```

**Comment by AmineBAIK1** [comment]
![ABCD](https://user-images.githubusercontent.com/46829598/59604569-d4f56d80-910c-11e9-85f7-5beab0e73805.jpg)
Yes, Tried with the script but got every time the same blank page..weird look screen

**Comment by harrison05** [comment]
Ohh, function detectmobi() on your code is a javascript function, but you call it in Twig syntax so it can't be found (if you enable debug mode, you will see that error). You should call it in js Ready function
```javascript
<script type="text/javascript">
    $Ready(function() {
	if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
//Do something with your template, example: show default Material Landing and hide other
	}
    })
</script>
```

**Comment by AmineBAIK1** [comment]
<script type="text/javascript">
		$Ready(function() {
				if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
$('container1').show();
$('container2').hide();
				}
			})
		</script>
so if i do this, it should work no?

**Comment by AmineBAIK1** [comment]
`<script type="text/javascript"> $Ready(function() { if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) { $('container1').show(); $('container2').hide(); } }) </script>

so if i do this, it should work no?`

**Comment by AmineBAIK1** [comment]
`<script type="text/javascript"> $Ready(function() { if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) { $('container1').show(); $('container2').hide(); } }) </script>`
So if do this, it should work no?

**Comment by harrison05** [comment]
Yes, it works.
