### ISSUE TITLE
IM App push notifications for Mobile Apps not working.

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2690]
IM App push notifications for Mobile Apps not working.
I tested it on phpfox ios app and android app.

It was announced with verion 1.4 on https://www.phpfox.com/blog/2019/phpfox-mobile-app-version-1-4-official-release/
– Have push notification for new messages.

**Comment by harrison05** [comment]
Don you setup Firebase on your App? Follow our guide at https://docs.phpfox.com/display/FOX4MAN/How+to+support+push+notifications+for+new+messages+on+phpFox+Mobile+apps

**Comment by Ylmzef** [comment]
I tested it on phpfox app not my website.
v4.phpfox.com

**Comment by harrison05** [comment]
Oh, our mistake. We just updated Firebase sender Id for v4.phpfox.com. Now, it's working well.
Note: you must log out and log in again to receive notifications.

Regards
