### ISSUE TITLE
Server Setup issue for IM Module

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2692]
I am trying to update IM module but i am getting following issue when i start im server from ssh;

xx@xxx.xx[~/server]# node index.js
/xxx/xxx/server/index.js:138
            senderId,
                    ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

When i try with older version it's working fine.
Also i have created and updated firebase server key/id from config.js

**Comment by harrison05** [comment]
It shows a syntax error, please double check codes in your config file.

**Comment by Ylmzef** [comment]
I am using core codes.
I didn't change anything from index.js also i download apps several times from store.

**Comment by Ylmzef** [comment]
i have reinstall node server on ubuntu server and it's working fine.
I got the issue on centos server.

**Comment by harrison05** [comment]
Nice to hear it. 👍
