### ISSUE TITLE
Sql error / Empty Feed

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2695]
Hello, 
After installing the new background feed & Reaction ! Got this error with Sql with Empty feed/home content !!! Nothing 
![Capture d’écran de 2019-06-22 01-24-44](https://user-images.githubusercontent.com/46829598/59955867-fcda2d80-948c-11e9-9f69-9d6312e00403.png)

**Comment by harrison05** [comment]
You can go to **PF.Base/file/log/main.log** to view the root cause of this error. 
Let me know if this is a bug from phpFox
_P/s: Make sure the connection between your site and database is good._

Regards.
