### ISSUE TITLE
Pages and Groups Flickers from the Menu to the top with animated cover image

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2697]
## What happened?
When an animated gif cover image is used the pages and groups pages will flicker from the menu and above. The lower portion is unaffected. This was not an issue in the version prior to 4.7.6

## Steps to reproduce:
1. Upload an animated gif image as a cover. 
2. Goto to page and observe.

## What is expected?
The page should not be flickering.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.6 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
I can't reproduce your issue on my side. You can submit a ticket, then we will check it on your site.

Regards.

**Comment by prepperz** [comment]
Done. Info is included on ticket #468802
