### ISSUE TITLE
New app SAVED can we control the cache to turn it on or off  or not ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2700]
Good Day my friends it's been a long time 
I first wanted to say congratulations. Super awesome 👏 I love 4.76 and the 3 new apps. 😀

## What's happened?
...
When I installed fresh install of 4.7.6 I didn't see Saved app so I installed from app store. 

Then I cleared cache remove files not needed. Rebuild  and then clear all cache 

Still nothing. After a few minutes of just refreshing pages I finally saw.it. I saved a few item and only 2 showed saved. Then refresh clear cache clear all cache and more showed up. 
## Steps to reproduce:
1. fresh install
2. install app
3. try to save a few items and go to Saved see if they are all there or if we need to clear cache always ?
you should check upon a fresh install if after you add a few photos and or feeds and try to save them and see if it is working? or if you have to reinstall the app from the phpfox store ?

## What's expected?
... Just need to know if the app has option to select cache ON OFF or if its even cached all together

if it is cached can we get the option to limit the time of cache like some other apps we did before ?

( OK I found where we look for cache settings = in blocks section, no settings for cache there for this )

Thanks @harrison05 I hope your all doing well and great job again I say on all the fixes and updates 😀😀

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome browser

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.2 Apache mariadb latest

## phpFox version
(Example: phpFox 4.6.0)

...4.7.6

## Screenshots
...
😀😀😀🤗🤗🤗

**Comment by spirogg** [comment]
OK i don't see this having any cache settings in the admincp blocks area. so is it cached or is it not cached ?

**Comment by harrison05** [comment]
Nice to see you again, @spirogg. I'm glad you came back

> try to save a few items and go to Saved see if they are all there or if we need to clear cache always ?

Do you talk about Purchase History? Because I can't found Saved item on our Core. Could you take a screenshot?

> OK i don't see this having any cache settings in the admincp blocks area. so is it cached or is it not cached ?

Oh, setting about cache time just support for Block, and phpFox doesn't have the option to on/off cache for apps.

**Comment by harrison05** [comment]
Nice to see you again, @spirogg. I'm glad you came back

>I saved a few item and only 2 showed saved. Then refresh clear cache clear all cache and more showed up.

>OK i don't see this having any cache settings in the admincp blocks area. so is it cached or is it not cached ?


We don't cache saved items, could you try with another account? does it still occurs or not? Because it doesn't appear on my site.

**Comment by spirogg** [comment]
@harrison05 this was just an isolated incedent i reinstalled and seems working now  :)

Thanks Harrison Its good to be Back
