### ISSUE TITLE
Saved app var showing when saving photo albums

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2701]
----------------------------------------

## What's happened?
...
when saving a photo album you see var name not actual description or name of photo album in Saved App section
## Steps to reproduce:
1. go to photos then my albums then select a photo album, timeline or cover photos
2. click on the three dotts to select save
3. now go view your saved it shows var name not actual name

## What's expected?
...
should show actual name 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

chrome browser latest
...

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.2 apache mariadb   latest

## phpFox version
(Example: phpFox 4.6.0)

...4.7.6

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/60247784-ecf48c00-9886-11e9-89ff-22609a142d7a.PNG)

**Comment by spirogg** [comment]
also happens when you view all albums
this is your demo site in this snap shot


![Capture](https://user-images.githubusercontent.com/17736688/60248054-74da9600-9887-11e9-9739-d287f54c56c5.PNG)

**Comment by david-phpFox** [comment]
Fixed in Saved Items 4.1.1
