### ISSUE TITLE
when viewing all albums not showing all 5 photos across the bottom row all the time

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2702]
----------------------------------------

## What's happened?
...
when you go to photos and view all albums and you scroll down
there seems to be a weird pattern not showing across all photos, it actually gets 5 then 4 then next time you click load more you get 3 then load more then 2 load more than 1 load more starts all over the pattern 5 then 4 then 3 then 2 then 1 etc.. see photos
## Steps to reproduce:
1. go to your demo click on photos then all Albums
2. continue to scroll down until you see more the load more button
notice at this point the bottom row of photos how many you see ?

3. now scroll down till you see the blue load more button again
now take notice of the last row at the bottom of how many photos they are across then keep doing this you will see a pattern 5 4 3 2 1 then start all over really weird ??

## What's expected?
... should be 5 photos across at bottom row - all the time

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

... latest chrome browser 

## Server information
(Example: CentOS 7, php 7.1 apache)

...
your demo site

## phpFox version
(Example: phpFox 4.6.0)

...your demo site

## Screenshots
...
![Capture7](https://user-images.githubusercontent.com/17736688/60248918-4362ca00-9889-11e9-9b3a-920e8cfb62e9.PNG)
![Capture6](https://user-images.githubusercontent.com/17736688/60248919-4362ca00-9889-11e9-8df1-62b9a666d2a0.PNG)
![Capture5](https://user-images.githubusercontent.com/17736688/60248920-4362ca00-9889-11e9-8320-f7bf19139b1f.PNG)
![Capture4](https://user-images.githubusercontent.com/17736688/60248921-4362ca00-9889-11e9-9285-59c650f86e54.PNG)
![Capture2](https://user-images.githubusercontent.com/17736688/60248922-4362ca00-9889-11e9-8320-a1a9a99e4fce.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/60248923-43fb6080-9889-11e9-82f5-27be82c6b0d4.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/60248925-43fb6080-9889-11e9-9389-19d747cc91df.PNG)

**Comment by spirogg** [comment]
see the pattern we should always have 5 across at the bottom when clicking on the load button

thanks
Spiro

**Comment by harrison05** [comment]
I reproduce on our demo site https://v4.phpfox.com/photo/albums/ but it seems working well, always load 9 items per page
![Screen Shot 2019-06-28 at 11 51 09](https://user-images.githubusercontent.com/41947198/60318071-cc6a2600-999b-11e9-800b-05d948a68b67.png)
![Screen Shot 2019-06-28 at 11 51 49](https://user-images.githubusercontent.com/41947198/60318072-cc6a2600-999b-11e9-86d1-a254f54452e1.png)
![Screen Shot 2019-06-28 at 11 52 17](https://user-images.githubusercontent.com/41947198/60318073-cc6a2600-999b-11e9-96fc-69fb0651af6a.png)

**Comment by spirogg** [comment]
@harrison05 

Do we have option somewhere in adminCP to make it 12 items per page ? - Then the page will look even and full.

When using 9 items only some users will think there is no more to load even if the load more button is there, it looks empty or like it didn't finished loading properly ?

Thanks

Spiro

**Comment by spirogg** [comment]
Or is this not the issue ?

 even if we use 12 there will there still be empty spaces at the bottom ?

thanks

Spiro

**Comment by harrison05** [comment]
>Do we have option somewhere in adminCP to make it 12 items per page ? - Then the page will look even and full.

Currently, Admin only can set total items show per page for Photo listing, doesn't support on Album listing.

>even if we use 12 there will there still be empty spaces at the bottom ?

Yes, if you use 12 items per page, on desktop screen ,it show 5 items each row. 12 will nice for tablet or mobile with 4, 3, 2 or 1 items each row.

Regards.

**Comment by spirogg** [comment]
@harrison05 

Thanks
