### ISSUE TITLE
your demo bootstrap has 2 group apps on top menu 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2703]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
 not a bug - just I noticed and looks funny for customers who might want to buy -
you  just need to remove one group in the top menu so it look professional :)
## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/60283884-d888b180-98cf-11e9-8959-ee699a7c9da1.PNG)

**Comment by harrison05** [comment]
Ok, we removed it. 

Thanks a lot.
