### ISSUE TITLE
Question ? about hide in news feed ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2704]
----------------------------------------

## What's happened?
... When you are an Admin and posting in Feed, is there a setting that disallows users the ability to hide or block Admins from the Feeds. 

I know we have an option that users can't Block Admins - but I don't see option not to Hide or Hide all feeds from Admins? 

I think users should not be able to block Admins ( or we should have an option that says should users be able to Hide admins in Feed YES NO 

## What's expected?
...
should have option for admins to set, where users can't block admins in feed
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.7.6

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/60377482-158e9a00-99dd-11e9-9264-a44a623a95e5.PNG)

**Comment by harrison05** [comment]
>I know we have an option that users can't Block Admins - but I don't see option not to Hide or Hide all feeds from Admins?

Yes, we don't support setting to allow hide or not on feed. Everyone can hide feed from others.

Regards.

**Comment by spirogg** [comment]
@harrison05 Thanks

**Comment by harrison05** [comment]
@spirogg We just add a new setting to allow Admin enable/disable this feature. It will available in the next version.

**Comment by spirogg** [comment]
@harrison05 thanks
