### ISSUE TITLE
Shout box avatar is huge

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2705]
## What happened?
Shoutbox avatar image is huge.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.6 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
Could you take a screenshot? Because it small on our demo site
![Screen Shot 2019-07-01 at 10 15 44 AM](https://user-images.githubusercontent.com/41947198/60408764-78a14c00-9bea-11e9-9c8f-858b37c73019.png)

Regards.

**Comment by prepperz** [comment]
here you go
![Screenshot](https://user-images.githubusercontent.com/19594886/60410230-3e598f80-9b95-11e9-8e5d-74ad49674424.png)

**Comment by harrison05** [comment]
Did you try to rebuild core theme and clear cache?

Regards.

**Comment by prepperz** [comment]
OK. It took several tries. after activating it, but it's resolved.
