### ISSUE TITLE
Double adding photos to directories after adding a CDN server to phpfox

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2706]
## What's happened?

Hello,

The issue I noticed today in phpfox.

I've properly configured the CDN server.

If a user adds a photo, it is visible in this folder:
cdn1.mydomain.com/file/pic/photo/2019/07
Everything is fine here.

But...I noticed that this image was also added to the folder:
mydomain.com/PF.Base/file/pic/photo/2019/07/

This is a bug, because the photo is unnecessarily duplicated, and undermines the sense of using the CDN server.

Can you help me to fix this issue?
I have provided data for my website and to ftp in the ticket number: 334348.

Thank you.

## Steps to reproduce:
1.  Add a photo if CDN is on
2.  
3. 

## What's expected?

The photosis doubled. 
They are added to both the CDN server and the basic directory in phpfox in /PF.Base/file/pic/photo/2019/07/

## phpFox version
4.7.3

**Comment by harrison05** [comment]
No, it not a bug. Please go to **AdminCP**, search settings "**Keep Files In Server**" and disable it.

Regards.
