### ISSUE TITLE
Pictures are not compressed if the photo's width is less than 1024 pixels

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2707]
## What's happened?
Pictures are not compressed if the photo's width is less than 1024 pixels.

This is a mistake, because if we have a high weight limit for the added image, if one of the images added is smaller than 1024 pixels in width, the image will not be compressed and will take up a lot of space on the page.

However, if the same photo, which weighs a lot more than 1024 pixels wide, and put them on the page, it will be compressed.

Can you tell me how I can fix this issue?
No, I can not wait to update the Photos app because my phpfox no longer supports the latest releases of this application.
Can you help me fix it?
I have provided data for my website and to ftp in the ticket number: 334348.

## Steps to reproduce:
1. Add an photo whose width is less than 1024 pixels

## What's expected?
The photo will not be compressed

## phpFox version
4.7.3

**Comment by harrison05** [comment]
Because we create many thumbnail sizes for a photo, ex: _240, _500, _1024, so if your image has a width smaller than thumbnail width, we don't stretch out it, then thumbnail size doesn't change.

Regards.
