### ISSUE TITLE
need help, If you can try

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2708]
my app I created Add Users from adminCP works perfect except the users I add ( the points dont add) it shows the activity points in the bottom just doesn't add it up top see phtoto

can you give me any reason why this might happen ? 
If I turn on register and i register a user it works
but when adding a user from adminCP from my app it doesnt add to top 
really weird

any Idea if you can help

would be much appreciated
----------------------------------------

## phpFox version
(Example: phpFox 4.6.0)

...  4.7.6

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/60488316-471a9600-9c67-11e9-8848-67c5e48cd5d7.PNG)

**Comment by spirogg** [comment]
![Capture](https://user-images.githubusercontent.com/17736688/60488398-7f21d900-9c67-11e9-9c22-cfcea8316143.PNG)

**Comment by spirogg** [comment]
and here is a user I added via the register front end

![Capture](https://user-images.githubusercontent.com/17736688/60488657-1d15a380-9c68-11e9-95bb-82290fbaa510.PNG)

**Comment by spirogg** [comment]
everything else seems to work just as needed, except it doesn't total on top in activity points ?

**Comment by harrison05** [comment]
Do you call to our function to add a new user? If will add all necessary row to database and make it work correctly. Your issue looks like missing data in **user_activity** table.
```php
PF.Base/module/user/include/service/process.class.php: \User_Service_Process::add()
```

Regards.

**Comment by spirogg** [comment]
> Do you call to our function to add a new user? If will add all necessary row to database and make it work correctly. Your issue looks like missing data in **user_activity** table.
> 
> ```
> PF.Base/module/user/include/service/process.class.php: \User_Service_Process::add()
> ```
> 
> Regards.

@harrison05  Im still not seeing what i would need to add and where?
I have been away too long and I am forgetting :( 

Can you have a look in my app and can please help me
-  can you tell me what I need to add and where please

because Seems I have already added Tables 
$tables = [
            'user_activity',
but not sure

see some code below maybe this is not correct with tables ?
```
`private function create($aVals)
    {
        $email = $aVals['email'];
        $url = null;
        $password = (new Hash())->make($aVals['password']);
        $iGender = 0;
        $user_name = $this->generateValidUserName($aVals['display_name']);
        $id = db()->insert(':user', [
            'user_group_id' => NORMAL_USER_ID,
            'email' => $email,
            'password' => $password,
            'gender' => $iGender,
            'full_name' => db()->escape($aVals['display_name']),
            'user_name' => $user_name,
            'user_image' => '',
            'joined' => PHPFOX_TIME,
            'last_activity' => PHPFOX_TIME
        ]);
        $tables = [
            'user_activity',
            'user_field',
            'user_space',
            'user_count'
        ];`
```

**Comment by harrison05** [comment]
Your code has enough extra required tables when create user. With your **$tables**, you have to insert new records to them, example:
```php
db()->insert(Phpfox::getT('user_activity'), [
  'user_id' => $id
]);
```
You should take a look on source code of **\User_Service_Process::add**. You might need to add:
- Custom fields
- Subscription if required
- Send verify email/sms if Admin enables them.
...

Regards.

**Comment by spirogg** [comment]
PS> My initial issue is solved 

Hi it was so simple i just added 'activitypoint_statistics' at the bottom of tables and it worked
$tables = [
            'user_activity',
            'user_field',
            'user_space',
            'user_count',
            'activitypoint_statistics'
        ];`

**Comment by spirogg** [comment]
> Your code has enough extra required tables when create user. With your **$tables**, you have to insert new records to them, example:
> 
> ```
> db()->insert(Phpfox::getT('user_activity'), [
>   'user_id' => $id
> ]);
> ```
> 
> You should take a look on source code of **\User_Service_Process::add**. You might need to add:
> 
> * Custom fields
> * Subscription if required
> * Send verify email/sms if Admin enables them.
>   ...
> 
> Regards.

Last quick question - if I have users after wards that were already signed up from my app in backend how can I add these fields so there activitypoint_statistics will start to calculate ?
is there something I can do in DB or is there any code I can run to allow all users prior to fix to have activitypoint statistics working ?
sorry my friend for the questions

**Comment by spirogg** [comment]
Ok fix for this issue is just reinstall Activity app from store and all users prior will be ok now. Thanks Harrsion
