### ISSUE TITLE
PromoteJob / Iframe / Links

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2709]
Hello, 
The Thing is i want that the Review of Promote Job be shown in Email of Job Alert 
This is the Review 
![1](https://user-images.githubusercontent.com/46829598/60520789-4d038c00-9ce6-11e9-8be0-adcf767feda8.jpg)
I tried to change this file and added promotejob in message array like this 
![Capture d’écran de 2019-07-02 15-22-12](https://user-images.githubusercontent.com/46829598/60520853-69072d80-9ce6-11e9-8f13-6d97b8d64cd2.png)
And then added in phrases in AdminCp 
{promotecode} in the message layout. 
But get always blank !! in theory it works but why not?

**Comment by harrison05** [comment]
What's the value of $sPromoteCode? Remember to add inline CSS to your HTML tag, because email can't load CSS file from phpFox.

Regards.

**Comment by AmineBAIK1** [comment]
` public function getPromoteCode($iId, $en_photo, $en_description)
    {
        $sFrameUrl = Phpfox::getParam('core.path_file').'module/jobposting/static/php/promotejob.php?id='.$iId.'&en_photo='.$en_photo.'&en_description='.$en_description;
        return '<iframe src="'.$sFrameUrl.'" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:180px; height:360px;" allowTransparency="true">;</iframe>';
    }`

There is Inline css in the html tag in the return of the function getPromoteCode used to declare the value of $sPromotecode 
Look at line  $sPromoteCode = Phpfox::getService('jobposting.job')->getPromoteCode($iId, 1, 1);

**Comment by harrison05** [comment]
Why do you add "iframe" to show your HTML? the iframe isn't shown up in almost mail (Refer: https://www.campaignmonitor.com/blog/email-marketing/2019/01/do-iframes-work-in-email/)
I think you should push HTML and inline CSS directly in your email instead of load it from an iframe.

Regards.

**Comment by AmineBAIK1** [comment]
Ok, I loaded the Logo comapny in the email with this a just static link logo in cloudfront with this : 
'jobpicture' => '<img src="https://duftkzrwele4o.cloudfront.net/file/pic/jobposting/2019/06/83a6e67ea48772d755294029d1473415.jpg" alt="" id="x_js_thickbox_core_image" style="min-width:400px; min-height:229px" width="400" height="229">'
But i need to get the company log of the job i tried with those : 
`<a href="{permalink module='jobposting.company' id=$aCompany.company_id title=$aCompany.name}" class="ynjp_bg-img" 
			style="background-image: url({img server_id=$aCompany.server_id path='core.url_pic' file="jobposting/".$aCompany.image_path suffix='_500' max_width='120' max_height='115' return_url=true})"></a>` and other with ' and no ' with many things, The best thing is to replace src with
`server_id=$aCompany.server_id path='core.url_pic' file="jobposting/".$aCompany.image_path suffix='_500' max_width='120' max_height='115' return_url=true` but not working too ! any tips

**Comment by AmineBAIK1** [comment]
Ok, I loaded the Logo comapny in the email with this a just static link logo in cloudfront with this :
'jobpicture' => `'jobpicture' => '<img src="https://duftkzrwele4o.cloudfront.net/file/pic/jobposting/2019/06/83a6e67ea48772d755294029d1473415.jpg" alt="" id="x_js_thickbox_core_image" style="min-width:400px; min-height:229px" width="400" height="229">'`
But i need to get the company log of the job i tried with those :
<a href="{permalink module='jobposting.company' id=$aCompany.company_id title=$aCompany.name}" class="ynjp_bg-img" style="background-image: url({img server_id=$aCompany.server_id path='core.url_pic' file="jobposting/".$aCompany.image_path suffix='_500' max_width='120' max_height='115' return_url=true})"></a> and other with ' and no ' with many things, The best thing is to replace src with
server_id=$aCompany.server_id path='core.url_pic' file="jobposting/".$aCompany.image_path suffix='_500' max_width='120' max_height='115' return_url=true but not working too ! any tips

**Comment by AmineBAIK1** [comment]
Okey, Thanks I loaded the logo in the email with this that worked: `jobpicture' => '<img src="https://duftkzrwele4o.cloudfront.net/file/pic/jobposting/2019/06/83a6e67ea48772d755294029d1473415.jpg" alt="" id="x_js_thickbox_core_image" style="min-width:400px; min-height:229px" width="400" height="229">'
`
But now i need to load " The logo" Of the "Job" posted by the company, Tried to modify the src with : 
`return_url=true
                   server_id=$aCompany.server_id
                   title=$aCompany.name
                   path='core.url_pic'
                   file="jobposting/".$aCompany.image_path suffix=''`
and also all the html tag like this : `'<a href="{permalink module='jobposting.company' id=$aCompany.company_id title=$aCompany.name}" class="ynjp_bg-img" 
			style="background-image: url({img server_id=$aCompany.server_id path='core.url_pic' file="jobposting/".$aCompany.image_path suffix='_500' max_width='120' max_height='115' return_url=true})">''</a>'` any tips..

**Comment by harrison05** [comment]
Oh, I think email can't understand your smarty code. You should insert the real URL to email content. Should update your code and get image url first:
```php
$jobPicture = Phpfox::getLib('image.helper')->display(array(
                'server_id' => $aCompany.server_id,
                'title' => $aCompany.name,
                'path' => 'core.url_pic',
                'file' => 'jobposting/'.$aCompany.image_path,
                'suffix' => '',
                'return_url' => true,
            ));
...
'jobpicture' => '<a href="'.Phpfox::permalink('jobposting.company', $aCompany.company_id, $aCompany.name).'" class="ynjp_bg-img" style="background-image: url('.$jobPicture.')"></a>'
```

**Comment by AmineBAIK1** [comment]
- https://domainame.com/PF.Base/file/pic/jobposting/Arrayimage_path This is what $jobPicture is containing, it must contain at least for me a cloudfront link pointing to the picture in my AWS S3 bucket but its pointing to Local, When i used the Href cloudfront link directly it worked. Tried with what you proposed, still same. This link for the picture is just empty... Weird. 

- And secondly There is default Message like Hello [User_name] { message} Regards [Site_title] Where can we modify those default message Hello and Regards, site title ?

**Comment by harrison05** [comment]
- Do you test the value of $jobPicture after getting it as my suggestion? Is it correct link to image on CloudFront?
- "Hello [User_name] { message}": you can't change, it's default.
- "Regards [Site_title]": you can change it at **AdminCP > Settings > Mail Server** with setting **Signature**

Regards.

**Comment by AmineBAIK1** [comment]
Yes this is the value of $jobPicture https://domainame.com/PF.Base/file/pic/jobposting/Arrayimage_path

**Comment by TheJobWork** [comment]
This is not a third party issue, its a phpfox issue, wich accordign to what i read is unable to provide a oslution to how to personalise the header and footer of email from system...this is unseen.

**Comment by harrison05** [comment]
I think you should debug email content after mail library process it and before the system sends it out.

```php
\Phpfox_Mail::send()
```
