### ISSUE TITLE
Manage hidden issue

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2711]
## What's happened?
i have tested the new feature on my dev site and it worked fine but at some point that i can not reproduce atm i was not able to unhide posts of a user. the user just does not show up on the manage hidden page.

even i cant reproduce it i think there is some kind of bug with the new feature. you should check the code again.

please also add a setting to disable this new feature. it is a very good feature for some sites but not for others.

## Steps to reproduce:

i cant reproduce this at the moment

## What's expected?
all users that are hidden should show up on the manage page to make it possible to unhide post or users again.

## Server information
lampp with php 7.3

...

## phpFox version

phpFox 4.7.6
...

**Comment by harrison05** [comment]
We don't support users unhide posts after they leave the newsfeed page like user/page/group, they only can unhide post right after hiding a post.

We will discuss about setting enable/disable this feature.

Regards.

**Comment by kibcode** [comment]
ok got it... then i think it was a single post =)

**Comment by david-phpFox** [comment]
We will add a new setting to support disable this feature on Core 4.7.7.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.7.
