### ISSUE TITLE
Block issue 

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2712]
When we add block with those informations here i want a profile.small as a block in my memberhomepage added it but it not shown. With core/contacts/profile etc tried all 
![Capture d’écran de 2019-07-03 14-01-44](https://user-images.githubusercontent.com/46829598/60590120-7b8f6e80-9d9b-11e9-8acc-fac0d786d84d.jpg)

**Comment by harrison05** [comment]
Currently, we only support this block on the User Profile page, when you add it to other pages, it'll work incorrectly. 
But, we will improve to support this. Please wait for a new update.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.7.
