### ISSUE TITLE
Sharing a pages or group widget on Facebook shows a blank image

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2713]
## What happened?
Blank image when sharing pages or group widget.

Another issue is all widget just shows a cube icon and cannot be changed for each widget page.

## Steps to reproduce:
1. share any widget page on FB 

## What is expected?
Should display at least page avatar, cover or something.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.6 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Do you check to share the detailed URL of that page/group? Is it have an image or not?

Regards.

**Comment by prepperz** [comment]
Yes, there is an image, but the sharing the widget produce a blank image.

**Comment by harrison05** [comment]
If your page/group have an avatar/cover, FB will get it as a preview image. It doesn't get image on your widget content.

Regards.

**Comment by prepperz** [comment]
That is exactly the point. When sharing the pages or groups widget on facebook, it shows a blank image even though there is an avatar and a cover image.

**Comment by harrison05** [comment]
It might an issue with old data when create thumbnails for avatar of pages/groups. We will check and update to support this case.
P/s: We just hotfix on your site and it's working correctly now, please try to share on Facebook again.

Regards.

**Comment by prepperz** [comment]
It works now. Thanks. How did you manage to do the hot fix on the site tho?

**Comment by david-phpFox** [comment]
Fixed in Pages/Groups 4.7.6
