### ISSUE TITLE
Big issue in the "phpFox CDN" application

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2714]
## What's happened?

Hello,

The bug is that when I change the order of the CDN server in the list in the "phpFox CDN" application, the images are no longer visible.

For example, all photos are visible correctly.
In the "phpFox CDN" application, I was editing one CDN server in such a way that I added SSL to the domain name - that was earlier http://cdn3.mydomain.com, and I changed to https://cdn3.mydomain.com

I saved and changed the cache in phpfox.

It turned out that the edition of the CDN server domain name caused that this server changed its position in the list of CDN servers in the "phpFox CDN" application.

Ok, changing the position is not a bad thing, but it turned out that such a change causes that the photos that were on this server are assigned to another server (the one that swaps the position on the list after the edited server). 
This server, which takes the position of the previously edited CDN server, obviously has no photos and files referenced by phpfox and an issues appears (no photo on the page).

For example:
I had a list of 6 CDN servers on the list:

Upload URL		---		        View URL			---	                Key
http://cdn1.mydomain.com/	http://cdn1.mydomain.com/	Here_is_secret_key
http://cdn2.mydomain.com/	http://cdn2.mydomain.com/	Here_is_secret_key
http://cdn3.mydomain.com/	http://cdn3.mydomain.com/	Here_is_secret_key
http://cdn4.mydomain.com/	http://cdn4.mydomain.com/	Here_is_secret_key
http://cdn5.mydomain.com/	http://cdn5.mydomain.com/	Here_is_secret_key
http://cdn6.mydomain.com/	http://cdn6.mydomain.com/	Here_is_secret_key

I was editing the CDN server, which occupied the second position on the list, namely:
http://cdn2.mydomain.com/

By editing this server I changed in both links (Upload URL and View URL) from http to https, then I saved this change and cleaned the phpfox cache.

The server I was editing changed its position in the list (it appeared at the top or at the bottom of the list of servers - I do not remember exactly).

The position of the edited server (the second on the list) was now taken by the http://cdn3.mydomain.com/ server.

So after editing (adding https in place of http) of the http://cdn2.mydomain.com/ server and saving the changes, the list of servers in the "phpFox CDN" application looks like this:

Upload URL		---	        View URL			  ---              Key
http://cdn1.mydomain.com/	http://cdn1.mydomain.com/	Here_is_secret_key
http://cdn3.mydomain.com/	http://cdn3.mydomain.com/	Here_is_secret_key
http://cdn4.mydomain.com/	http://cdn4.mydomain.com/	Here_is_secret_key
http://cdn5.mydomain.com/	http://cdn5.mydomain.com/	Here_is_secret_key
http://cdn6.mydomain.com/	http://cdn6.mydomain.com/	Here_is_secret_key
https://cdn2.mydomain.com/	http://cdn2.mydomain.com/	Here_is_secret_key

And here a strange bug appears:
Links to photos that were stored on the cdn2.mydomain.com server and looked like this: https://cdn2.mydomain.com/file/pic/photo/2019/07/cb96d7bfb73753e31daabc21b9986f11_500.jpg, changed their address to https://cdn3.mydomain.com/file/pic/photo/2019/07/cb96d7bfb73753e31daabc21b9986f11_500.jpg - that is, to the server that took the second position on the list.
Of course, users can not see the photos now because phpfox refers to a CDN server that does not have these files.

The only solution to this problem (although it is a primitive, time-consuming and flawed solution) is to delete all servers from the list in the "phpFox CDN" application and add them again in the correct order.
However, this causes a problem, because as we edit this list, or if we edit one server from the CDN server list and the order of servers in the list changes, which will cause the above issue, if in a user adds a picture (to the wrong list) and then we will correct this list for the correct one, then the photos that this user added during our edition of the CDN server list will later be invisible.

Can you help me fix this bug?
It's a stupid bug, but it causes big problems.
Similarly, if you try to delete photos that refer to a bad CDN server. 
As a result, users will not be able to delete photos.
I have provided data for my website and to ftp in the ticket number: #832719

Thank you.

## Steps to reproduce:

1.  Edit some server in the "phpFox CDN" application and then save the changes and clear the cache in phpfox.

## What's expected?

The position of the edited CDN server has changed.
All image links that were stored on this server now refer to another CDN server, which causes an bug, because another sewer CDN does not have these files.

## phpFox version
4.7.3

**Comment by harrison05** [comment]
I understand your issue, the server_id is changed after you edit a CDN server. 
We will check and find a solution for this bug.

Regards.

**Comment by kerstar** [comment]
@harrison05 I hope that the update that will fix this bug will be available on my phpfox version (4.7.3). If it will not be compatible, please fix this bug on my website (I provided the data in the ticket). Thank you.

**Comment by david-phpFox** [comment]
Fixed in phpFox Storage app 4.6.3.
