### ISSUE TITLE
DB Syntax Error

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2715]
I Activated the debug mode of PHPFOX and then i got this 500 Error in my home page 
I got this with an other version of PHPFOX and an other site with an other DB too. 
![2019-07-06 02-14-27](https://user-images.githubusercontent.com/46829598/60749064-038c9880-9f95-11e9-897f-e2f7f7c3ab26.jpg)

**Comment by harrison05** [comment]
If you enable block **profile.small** on Homepage, please disable it. 
Currently, this block can't work on pages without profile detail

Regards.
