### ISSUE TITLE
Pending Membership, when clicked on doesnt take us to pending ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2716]
----------------------------------------

## What's happened?
...
 Hello, if we have pending members for a group and we click the big green button it takes us to all members not the selected pending members, we have to click ogain on the pending members tab - it should just opwn the pending members tab so we don't have to click again if possible
## Steps to reproduce:
1.  go to one of your groups and if there is Pending memberships - click the big green button
2. next you will see 3 tabs (All Members) (Pending Requests) (Group Admins)
3. The selected after clicking Pending Memberships is = (All Members )

## What's expected?
...   But it should be (Pending Requests) not (All Members) because we clicked on Pending Memberships. So it should link directly to (Pending Request) tab (open) so we don't have to click again to get to pending requests.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...
chrome latest
## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7.2 apache
...

## phpFox version
(Example: phpFox 4.6.0)

...4.7.6

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/60751696-147edf00-9f80-11e9-9e5f-39fd63d8ae52.PNG)

**Comment by spirogg** [comment]
- PS this was on your Demo site Just FYI

**Comment by harrison05** [comment]
Oh, we will check and fix it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Groups 4.7.6
