### ISSUE TITLE
1 more small Question please

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2717]
Hi @harrison05 
- the users I add don't have password_salt when looking at DB table (phpfox_user)
![password_salt](https://user-images.githubusercontent.com/17736688/60760139-09ff2c80-9ff6-11e9-90db-6eaad4f4bcdf.PNG)

- seems only registered users from front end get the password_salt characters
but added from back end its only shows NULL
see photo below
![password_salt2](https://user-images.githubusercontent.com/17736688/60760184-d1138780-9ff6-11e9-85e3-47571cf0d39b.PNG)
- 

 - Do you think this is a security issue or no big deal ?

## phpFox version
(Example: phpFox 4.6.0)

... 4.7.6

## Screenshots
...

**Comment by AmineBAIK1** [comment]
Did you add them with a Random password salt initially? 
I have done a similar thing few days ago and i got all the password salt in my DB. 
Weird ..

**Comment by harrison05** [comment]
@spirogg if you're using **(new Core\Hash())->make($aVals['password']);** to hash password, you won't need password salt. Otherwise, you need password salt to hash password, example:
```php
$sSalt = $this->_getSalt(); //This is private function of User_Service_Process class, you can refer code from it.
$aVals['password'] = Phpfox::getLib('hash')->setHash($aVals['password'], $sSalt);
$aVals['password_salt'] = $sSalt;
```

**Comment by spirogg** [comment]
thanks so much @harrison05
