### ISSUE TITLE
Function Get CustomField

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2718]
Hello,
in User Browse profiles [ User info ] 
Additionally to Location,Gender and Joined, I'v added a custom field [ Current Job] 
And want to integrate it .. so i must pass by info.class in module user / block ! 
But it's seems like i must load it in a function and there is no call like this in the CS 
![Get](https://user-images.githubusercontent.com/46829598/60769885-6127fe80-a0d5-11e9-9658-cfe632a6319e.jpg)

**Comment by harrison05** [comment]
You must add custom code to get that Custom Field in this block, you can get it from "user_custom" table

Regards.
