### ISSUE TITLE
Disable App in Activitypoints, also hide the App in Frontend 

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2720]
When I deactivate an App in my Activitiy Points Backend:

https://prnt.sc/oe2t9j

Then the Title in Frontend should also be hide, not only the subsection

https://prnt.sc/oe2trd

**Comment by harrison05** [comment]
We will check and fix it.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Activity Points 4.7.6
