### ISSUE TITLE
Feed Status Background app

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2721]
----------------------------------------

## What's happened?
...
 When you go to AdminCP > Apps > Installed and click on Feed Status Background App
and click edit, you do not see a list of the photos uploaded

- 
![Capture](https://user-images.githubusercontent.com/17736688/61167919-f6c6f200-a50a-11e9-864d-5ff6dfa81d34.PNG)

it says you can reorder photos, but not delete photos.

-  but there is no photos that show to reorder them

- 2 Also when you add your own photos the photos do not show either so you can see what photos you want or if you ever want to delete one or add more you know which ones you have added
-  or to reorder them you can't cause you don't see the photos ?

- 
![Capture4](https://user-images.githubusercontent.com/17736688/61167932-4ad1d680-a50b-11e9-8bd6-64c1653b4716.PNG)

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...
you should see photos in a row or somehow to be able to delete or reorder them

- Also you you should have option to change size of uploaded photos not just 1mb we should be able to change this factor if admins wanted too ? or maybe raise it to 2mb
I know the reason is that we need to have it light so we can post fast and it will not take alot of space or be slow to load, but I think 2mb should be better.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...
chrome latest browser
## Server information
(Example: CentOS 7, php 7.1 apache)

...
centos 7 php7.2 apache latest
## phpFox version
(Example: phpFox 4.6.0)

...    phpfox 4.7.6  - Feed Status Background App 4.1.0

## Screenshots
...

**Comment by spirogg** [comment]
- PS Also can you make the image for upload - drag and drop image Larger ?

- I was almost lost where to click on to upload image(s) from my computer 

- ![Capture](https://user-images.githubusercontent.com/17736688/61168025-cda76100-a50c-11e9-974f-72e0fbee321c.PNG)

SHOULD BE BIG LIKE THIS

- 
![upload button](https://user-images.githubusercontent.com/17736688/61168027-dbf57d00-a50c-11e9-8038-06a594a1846b.PNG)

**Comment by spirogg** [comment]
Also why is there 2 small images to upload should only be one button on the top not the bottom
- ![Capture](https://user-images.githubusercontent.com/17736688/61168038-00e9f000-a50d-11e9-8192-468d49f3b583.PNG)


THANKS :)

**Comment by harrison05** [comment]
Do you try to rebuild core theme and clear cache? It seems missing css

Regards.

**Comment by spirogg** [comment]
@harrison05 yes I rebuild theme and cleared cache alot still issue persists

le me check again if I uninstall and reinstall

UPDATE: Uninstalled and reinstalled cleared cache all cache and removed files no longer needed , then rebuild core theme and still issue persists ?

**Comment by spirogg** [comment]
@harrison05 where can I check if css is missing ? its really weird this issue, still persist after rebuild theme I tried uninstall re-install app 
cleared cache rebuild theme and no luck still issue ?

**Comment by spirogg** [comment]
![Capture](https://user-images.githubusercontent.com/17736688/61429526-4d0da980-a8ec-11e9-9150-e7ff61b76da9.PNG)

**Comment by harrison05** [comment]
Check your cache system in case it's locked. 
![Screen Shot 2019-07-19 at 10 01 10](https://user-images.githubusercontent.com/41947198/61506416-29da1b80-aa0c-11e9-870d-25070800b021.png)

Do you install many third-party apps? Try to disable them and rebuild again, might have a syntax error on CSS file. Issue doesn't appear on my side
![Screen Shot 2019-07-19 at 10 05 40](https://user-images.githubusercontent.com/41947198/61506614-db794c80-aa0c-11e9-8235-7efb6d3d2fae.png)

Or submit a ticket, our team will check it for you.

Regards.

**Comment by spirogg** [comment]
harrison05 I just did new install of 4.7.7 and its working perfect now sorry that was weird in fresh install 4.7.6 ?? maybe just a fluke on my OS cetnos 7 

now is working great

thanks
