### ISSUE TITLE
the phrase hello has a comma, but in script not text

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2722]
----------------------------------------

## What's happened?
...
I added a comma on HELLO, and now it shows 2 commas, 
Example  >>>>>>>>>>>>   HELLO,,
- 
![Screenshot_20190713-042025](https://user-images.githubusercontent.com/17736688/61169670-bcb71980-a525-11e9-8639-1adcb4cf5597.png)

-

I then Remove comma from hello and then there is one comma in email i get..
HELLO,
Can you update and remove comma from code and leave this be comma in phrase if we want to add.

see photo there is no comma in the phrase >>>> but the emails show comma

- 
![Capture](https://user-images.githubusercontent.com/17736688/61169643-4dd9c080-a525-11e9-9b5e-3411c63b2230.PNG)

## What's expected?
... no comma in code should be only in phrase

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...     4.7.6

## Screenshots
...

**Comment by harrison05** [comment]
Yes, we have a default comma on source code after "Hello" phrase, remove it from your translated phrase is the fastest solution. 

Regards.

**Comment by spirogg** [comment]
> Yes, we have a default comma on source code after "Hello" phrase, remove it from your translated phrase is the fastest solution.
> 
> Regards.

@harrison05 If I remove it from phrase and I use my own email template > there is still a comma there when its not needed, 

its better if you remove from code the comma and just add in phrase after Hello, instead please

**Comment by harrison05** [comment]
I will check your request with the development team and let you know if have any update.

Regards.

**Comment by harrison05** [comment]
Hi @spirogg , after check and discuss with our team. We can't remove comma in source code because it might affect to old customers who translated that phrase.

**Comment by spirogg** [comment]
@harrison05 

the big problem now is if we use a template as I suggested here > #2719

there will be an extra comma and extra dead spaces either at the top of email 
 or middle of the email template

see photo below
- 
![Capture](https://user-images.githubusercontent.com/17736688/62103941-b33aea80-b263-11e9-9d47-1730ef680326.PNG)

- 
- so really the template will look unprofessional.

**Comment by spirogg** [comment]
this is going to be a bigger issue down the road for phpfox, when people want to use templates. 

@harrison05  you cannot add a template - it will have extra spaces (white spaces) and a comma showing before the  start of the template

please reconsider

what if I wanted a word instead of Hello,
I wanted to Put:  AWESOME !!! 

it would now look like AWESOME, !!!

(your limiting people to what they write.) what if they don't want a comma there ?

I know its a small thing but the admin should have control of a comma or period or any character

PLEASE >>>>>>>>>>> can you create a little ON / OFF feature for this
then with the ON OFF Feature >>  it doesn't ruin prior customer sites.

and it will still allow for new customers and old customers to remove it with the ON / OFF button if they don't want it. or if they want to use a special template,


thank you please

Spiro

**Comment by harrison05** [comment]
Okay, our team will review this case again and inform you if have any update.

Regards.

**Comment by spirogg** [comment]
Hello @harrison05 any word on the comma ?

it's a thorn in my eyes

**Comment by spirogg** [comment]
@phpfoxaccount @paulkellow @phpfoxdev @harrison05 

- the people with older versions can just add a comma in the text box if they want it still.

**please come on guys remove the comma from the core file and leave it up to the admin if he wants to use that character or an exclamation etc.. you are forcing me to use a comma when i don't want it  ???**

**REMOVE THE COMMA**  ITS SO USELESS AND SO UNPROFESSIONAL TO LEAVE IT IN CORE FILE..

**Comment by harrison05** [comment]
Hi @spirogg 

We will improve it, move the comma into a phrase, so Admin can translate or remove it.

Regards.
