### ISSUE TITLE
User info for guest

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2724]
Hello in Browse members for guest when the option is activated, The user infos ( like location gender etc) are hidden for guest. 
What's the easy method show user for everyone? Is there a setting in admincp because i didnt find it ...

**Comment by kerstar** [comment]
I was also wondering how to enable this option. 
Somebody knows?

**Comment by harrison05** [comment]
The user info shows or not based on their privacy setting. Admin can't control it.
![Screen Shot 2019-07-15 at 11 37 56](https://user-images.githubusercontent.com/41947198/61195844-06099380-a6f5-11e9-8eb6-f712d1d207b2.png)

Regards.

**Comment by AmineBAIK1** [comment]
It's all on "Anyone can see and view " but it still not showed for guest ... 
a bug ?

**Comment by harrison05** [comment]
> It's all on "Anyone can see and view " but it still not showed for guest ...
> a bug ?

Oh, I checked, this is a bug. We will fix and show user tooltip for guest but it only shows when setting "User AJAX Tooltip" is enabled.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.7.
