### ISSUE TITLE
Multi language site - Google Index

### ISSUE THREAD

**Issue by AmineBAIK1** [PHPfox-Official/phpfox-v4-issues#2725]
Hello,
When the site has multi languages(English, French, Russian whatever) Google index onlty the english language because when we change language only the phrases are updated in intern and doesnt affect google research.. 
- So How is it possible to index all those differentes languages pages ?

**Comment by TheJobWork** [comment]
a multilingual option but no possibility of having google index all different languages...very limiting.

**Comment by harrison05** [comment]
Duplicate to #2728
