### ISSUE TITLE
"Share on your wall" - how to change the value of this setting for new users?

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2726]
Hello,

@harrison05 , can you tell me how I can change the default "Share on your wall" setting from "Community" to "Friends Only" for newly registered users?

My guess is that the default value of settings in the "Privacy Settings" tab in the user settings is based on the "User Default Privacy Setting on Registration" setting in AdminCP.

I want the "User Default Privacy Setting on Registration" setting to be set to "Anyone" (as it is currently), except that the "Share on your wall" option is set to "Friends Only" instead of "Community" by default.

Can you tell me where I can change it?
My guess is that I need to change the value of some setting field in the database, which is responsible for the "Share on your wall" setting, but I do not know which field.
Can you tell me how to change it?

![privacy_3](https://user-images.githubusercontent.com/38014237/61187543-0e20ef00-a673-11e9-9577-5068849a7db5.png)
![privacy_1](https://user-images.githubusercontent.com/38014237/61187545-137e3980-a673-11e9-92e5-681f8e35d897.png)

**Comment by harrison05** [comment]
> I want the "User Default Privacy Setting on Registration" setting to be set to "Anyone" (as it is currently), except that the "Share on your wall" option is set to "Friends Only" instead of "Community" by default.

Oh, we don't support this special case. If you want to do that, you must modify the source code or using hook from module User.

Regards.

**Comment by spirogg** [comment]
Friends Only Profile
With this setting enabled only friends can view each other's profiles.
Note this will override your user's privacy settings and force anything related to viewing their profile and have it set to "Friends Only".

**Comment by spirogg** [comment]
maybe this will do it ? 
setting to friends only for all of their profile and then users can adjust what they want afterwards ?

- 
![Capture](https://user-images.githubusercontent.com/17736688/61431299-9c56d880-a8f2-11e9-9417-261c82c7d896.PNG)


 not sure,  I did not try it but just a suggestion for you to try and see if it might work in you case ?
you can also redirect your users after signup to the privacy page

**Comment by kerstar** [comment]
Hi @spirogg 

No, this option does not apply here.

I wanted all options to be set by default as they are, except for the "Share on your wall" field, which should be default to "Fiends only" instead of "Community" (as it is currently the default).

The problem was solved (the code had to be modified).
