### ISSUE TITLE
 Next issue in phpfox CDN app...

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2727]
## What's happened?
It consists in the fact that - after switching on / off the dark mode in Dark Mode app, some photos on the wall are not displayed.
I need to refresh the page and then they are visible.

I contacted the developer of the Dark Mode application because I thought the problem lies in their application.
I got the answer from him:

> Regarding image load issues: after dark mode switched, there photo is fetched from https://www.mydomain.com/PF.Base/file/pic/photo/2019/07/3c62d778f7c2e239804f0645cd1baf6d_1024.jpg
> 
> and not displayed. If we reload the page, the photo is fetched from https://cdn3.mydomain.com/file/pic/photo/2019/07/3c62d778f7c2e239804f0645cd1baf6d_1024.jpg 
> In this case photo does not exist and shows HTTP ERROR 404.
> 
> Developers have pointed that this problem may be related to CDN services recently set up on your phpFox instance.

Interestingly, I did not notice this bug on the accounts of regular users. 
The issue is only when I am on the phpfox admin account.

Can you help me to fix this issue?
This bug prevents normal use of the site.

I also recorded a video where I showed this bug (link is in the ticket).
I have provided login details in the ticket number: #517211

## Steps to reproduce:
1. Log in to my website (I have provided login details in the ticket number: #517211).
2. Switching on / off the dark mode in Dark Mode app

## What's expected?
The photos on the wall are not displayed
After refreshing the pages are visible.

## phpFox version
4.7.3

## Screenshots
![cdn_photo_1](https://user-images.githubusercontent.com/38014237/61227292-564c1a00-a724-11e9-8fc6-4a3e968c39eb.png)
![cdn_photo_2](https://user-images.githubusercontent.com/38014237/61227305-5c41fb00-a724-11e9-8fc2-fac79b2dbee6.png)

**Comment by harrison05** [comment]
It's a bug from phpFox Storage (CDN) on the first time reload page after clear cache. We will check it.

Regards.

**Comment by kerstar** [comment]
Great. Is it possible that this week you will release the phpfox CDN (storage) update that fixes this bug?

**Comment by kerstar** [comment]
@harrison05 You are wrong. This issue occurs every time I turn dark mode on or off. 
Not only the first time after clearing the cache.

**Comment by harrison05** [comment]
> @harrison05 You are wrong. This issue occurs every time I turn dark mode on or off.
> Not only the first time after clearing the cache.

No, I'm not. Dark mode App from 3rd clear cache after switching, so it same with the case I mentioned.

**Comment by kibcode** [comment]
hi @kerstar, are you using the dark theme mode app from scheinwelt-media? the app does only delete its own cache items not the full website cache. so it seems you are using another app for dark mode.

**Comment by kerstar** [comment]
Hi @Scheinwelt-Media 

No, I do not use your Dark Theme application .
I use the Dark Theme Mode application from the Foxer team.

Do they both differ essentially?
Application from the Foxer team clear all cache in phpfox when the user turns on or off the dark mode, instead of clearing the cache of a single user?

**Comment by kibcode** [comment]
not sure about how they handle cache but there is no need to delete all cache files after switching on or off. since dark mode is not listed in store anymore i will give you and all others using the app a discount of 50% if you want to switch to dark theme mode.

**Comment by david-phpFox** [comment]
Fixed in phpFox Storage app 4.6.3.
