### ISSUE TITLE
The third bug this week in the phpfox CDN (storage) application - large photos are not displayed

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2730]
## What's happened?

During this week, I reported to you two bugs in the phpfox CDN (storage) application that you have repaired.

Unfortunately, today I found the third bug, and it is revealed by the fact that after clicking on the thumbnail of the image, the large picture is not displayed, because it leads to a bad file location (I have not changed anything here).

I am sending screenshots where I showed this bug.

The bug does not apply to all photos. 
Some photos, after clicking on the thumbnail, are displayed correctly.

Will you help me fix this problem? (displaying photos is the basic function of phpfox and it is impossible to run a community without it).

Login and FTP details, where you can see this bug I gave in the ticket number: #424128

## Steps to reproduce:
1. Click on the thumbnail of the photo

## What's expected?
The big picture is not displayed (some photos are displayed correctly)

## phpFox version
4.7.3

**Comment by harrison05** [comment]
It looks like you're using a 3rd App to view photo detail, it might a bug from this app. Please request support from this App's owner. Because my team check on your site and issue doesn't occur when go to detail photo page.

Regards.

**Comment by kerstar** [comment]
@harrison05 It seems to me that you are not entirely right.
I went to detail photo page and there are no photos on the thumbnail bar (see the attachment).
![cdn_app_4](https://user-images.githubusercontent.com/38014237/61425993-1bf79e00-a919-11e9-9fb4-dc88f22e5ee4.png)

**Comment by kerstar** [comment]
I just added a new photo and it displays correctly. 
It seems to me that the bug occurs when, depending on which CDN server the photo is saved.

**Comment by kerstar** [comment]
Hi @harrison05 
Are you sure this is a bug in the Popup Photo Viewer application? 
The issue was not there before. 
It appeared since I started using phpFox CDN (storage).

**Comment by harrison05** [comment]
Hi @kerstar, 
After check carefully on your site. I confirm it's an issue from phpFox Storage. And our team just fixed it. Please check again.
A new update for this app will be released soon.

Regards.

**Comment by david-phpFox** [comment]
Fixed in phpFox Storage app 4.6.3.
