### ISSUE TITLE
A question about the security of earlier versions of phpfox <4.7.7

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2732]
## What's happened?

I have read your description of the new features / improvements that you have applied in the latest phpfox 4.7.7 and a reflection has come to me:

In section 5 you wrote "Encrypt sensitive data of site configuration stored in the database."

Does this mean that earlier versions of phpfox are not secure?
I am using version 4.7.3 - should I be afraid of something?
Version 4.7.3 has some security bugs?

Yes, I know that I always update phpfox to the latest version, but in my case it is very difficult and expensive (I have phpfox core modifications).

Can you tell which files should be replaced in phpfox from the latest version to mine, in order to be able to implement this improvement regarding data encryption?

**Comment by kerstar** [comment]
Hello,

Ok, I think I've found parts of the code that are responsible for the use of encryption.
Files that have been changed:
1. \PF.Base\include\library\phpfox\setting\setting.class.php
2. \PF.Base\module\admincp\include\service\setting\process.class.php
3. \PF.Base\module\admincp\include\service\setting\setting.class.php 

I have selected the code snippets on the screen shots, which are probably responsible for the encryption.

Here I have a few questions:
1. What element does this change concern?
I'm asking because I see that previously the password for FTP was also encrypted, and in the new version of phpfox 4.7.7 it looks like only the encryption structure has changed.

2. Does the phpfox 4.7.3 version have a safety bug?

3. If I replace the code from the phpfox 4.7.7 version, which I have marked on the screen, to my files (phpfox 4.7.3), will it work? (I do not mean replacing whole files, only fragments of code that are responsible for encryption).

I wanted my phpfox to be safe, that's why I am asking these questions to you.
(Prejudice: no, I can not update the entire phpfox to the latest version, because my phpfox has core modifications and the update is very expensive and time-consuming.
I just wanted to update only the piece of code that is responsible for encryption).

![encrypt1](https://user-images.githubusercontent.com/38014237/61597238-637a7480-ac0e-11e9-9585-e9e6fb5b1189.png)
![encrypt2](https://user-images.githubusercontent.com/38014237/61597239-637a7480-ac0e-11e9-9831-0edffccb8913.png)
![encrypt3](https://user-images.githubusercontent.com/38014237/61597240-637a7480-ac0e-11e9-9a73-62f2b9ebb7b9.png)
![encrypt4](https://user-images.githubusercontent.com/38014237/61597241-64130b00-ac0e-11e9-8936-7b2a4d0f2bdc.png)
![encrypt5](https://user-images.githubusercontent.com/38014237/61597242-64130b00-ac0e-11e9-85f4-62739e1575e8.png)
![encrypt6](https://user-images.githubusercontent.com/38014237/61597243-64130b00-ac0e-11e9-86d7-2d9fe54e309a.png)
![encrypt7](https://user-images.githubusercontent.com/38014237/61597244-64130b00-ac0e-11e9-9863-e986f33ad3c0.png)

**Comment by harrison05** [comment]
Hi @kerstar, I can answer your questions:

> What element does this change concern?

We modified it to improve the code structure and add encrypt not only mail password but also other password settings.

> Does the phpfox 4.7.3 version have a safety bug?

v4.7.3 we encrypt private settings but it not enough, so we improve it in v4.7.7 and we remove some codes to prevent the risk from Admin login, see the function: \User_Service_Auth::_logAdmin

> If I replace the code from the phpfox 4.7.7 version, which I have marked on the screen, to my files (phpfox 4.7.3), will it work? (I do not mean replacing whole files, only fragments of code that are responsible for encryption).

You can do this. But you're missing our change in function **\Phpfox_Ftp::__construct()**, don't forget it, it's important change.

Regards.

**Comment by kerstar** [comment]
Thanks for the information. I will try to do it today.

**Comment by kerstar** [comment]
@harrison05 

Should I modify the " _logAdmin" function in:
PF.Base\module\user\include\service\auth.class.php
?
It looks the same as in phpfox 4.7.3


and modify the "__construct" function in:
PF.Base\include\library\phpfox\ftp\ftp.class.php
replacing it with the function from phpfox 4.7.7 in place of function 4.7.3?

**Comment by kerstar** [comment]
Hi @harrison05 

Ok, I was tired before and I did not notice the difference in the "_logAdmin" function in the file: PF.Base\module\user\include\service\auth.class.php. 
Now I have found a difference in this function.

Harrison, should I understand that in addition to the code I have marked on screen shots in the first message, it is enough to also modify these two functions: " _logAdmin" in PF.Base\module\user\include\service\auth.class.php and function "__construct" in PF.Base\include\library\phpfox\ftp\ftp.class.php files?
That's all?

Together, I must modify five files:
1. \PF.Base\include\library\phpfox\setting\setting.class.php
2. \PF.Base\module\admincp\include\service\setting\process.class.php
3. \PF.Base\module\admincp\include\service\setting\setting.class.php
4. \PF.Base\module\user\include\service\auth.class.php
5. \PF.Base\include\library\phpfox\ftp\ftp.class.php

That's all? Did I forget something?

**Comment by harrison05** [comment]
Yes, that's all for "Encrypt sensitive data of site configuration stored in the database."

**Comment by kerstar** [comment]
OK thanks for the information!

Can you tell me if there is any way to check if the modification I'm doing works correctly? (I have not made this modification yet).

**Comment by harrison05** [comment]
I think your works correctly because we must compare two files to see the difference between them. You can check phpFox Change Log at https://github.com/PHPfox-Official/phpfox-change-logs

Regards.

**Comment by kerstar** [comment]
Hi!

Ok, I will call in the ticket as I will make this modification. I'll deal with this today.

Thanks again for the information!

**Comment by kerstar** [comment]
@harrison05 

Hi Harrison!
Ok, I changed the files and at first glance, I did not spoil anything, but I have no way to verify whether or not I omitted something.
Check out my ticket please: #690257

Regards,
kerstar

**Comment by harrison05** [comment]
Our support team will handle your ticket. Please follow it.

Regards.

**Comment by kerstar** [comment]
@harrison05 
Paul from your team just wrote to me in ticket that you can not help me in this matter. 
Well, it's a pity. I hope that these 5 files are all about this security patch.

Regards,
kerstar

**Comment by harrison05** [comment]
> @harrison05
> Paul from your team just wrote to me in ticket that you can not help me in this matter.
> Well, it's a pity. I hope that these 5 files are all about this security patch.
> 
> Regards,
> kerstar

Oh, sorry about that, you have to do it by yourself. If you have other questions, just ask me on GitHub.

Regards.

**Comment by kerstar** [comment]
Sure, no problem

If you are sure that only these five files:
1. \PF.Base\include\library\phpfox\setting\setting.class.php
2. \PF.Base\module\admincp\include\service\setting\process.class.php
3. \PF.Base\module\admincp\include\service\setting\setting.class.php
4. \PF.Base\module\user\include\service\auth.class.php
5. \PF.Base\include\library\phpfox\ftp\ftp.class.php

responsible for "Encrypt sensitive data of site configuration stored in the database." it's probably all should be ok.

Thank you Harrison for the information that helped me implement this security patch.
