### ISSUE TITLE
The fourth bug in the phpFox Storage (CDN) app (and possibly in the Attachments app)

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2733]
## What's happened?
The bug is that if I go to the "Attachments" tab on the user profile, and then delete an attachment, it is not deleted if the attachment is placed on the CDN server.
After clicking "Delete attachment", and then confirming this operation, the attachment is removed from the list of attachments, but it is not removed from the CDN server.

If I delete an attachment that is placed on the main server (not on the CDN server), the attachment is deleted from the server correctly.

Can you fix it?
The impossibility of removing attachments is a big inconvenience because there is unnecessary clutter on the server.
If this is a bug in the "Attachments" application, then I have a big problem and will ask for a hot fix for this bug, because this application is the core of phpFox and only when the next version of phpFox is released will be fixed (I can't update phpfox to a newer version, because I have core modifications).

By logging into my site you can try to remove the attachment and then check if it has been removed from the CDN server.

I have provided login details in the ticket number: #186715

## Steps to reproduce:
1.  Log in to my website
2.  Go to the "Attachments" tab on the user's profile
3.  Delete some attachment (which is on the CDN server)
4.  Check if the attachment has been removed from the CDN server

## What's expected?
The attachment was removed from the list of attachments, but it was not removed from the CDN server.

**Comment by harrison05** [comment]
I can't reproduce it on my side. But we will help you check it on your site via Ticket. Please wait for an update from our support team.

Regards.

**Comment by kerstar** [comment]
Ok, I will wait for help in the ticket, but it is definitely a issue, because I did not modify anything in the phpfox Storage application.

**Comment by harrison05** [comment]
Our support team will detect and fix the issue on your site. If it's a bug from our App, we will fix it.

Thanks.

**Comment by kerstar** [comment]
Thanks!

**Comment by kerstar** [comment]
@harrison05 

Update:
You mentioned that your team diagnosed and fixed this problem on my site. 
I checked it again - I removed the attachment that was on the CDN server. 
The attachment disappeared from the list of attachments, but it is still on the CDN server.
Are you sure that the bug has been correctly diagnosed?

**Comment by harrison05** [comment]
> @harrison05
> 
> Update:
> You mentioned that your team diagnosed and fixed this problem on my site.
> I checked it again - I removed the attachment that was on the CDN server.
> The attachment disappeared from the list of attachments, but it is still on the CDN server.
> Are you sure that the bug has been correctly diagnosed?

Oh, you should follow your ticket in Client Area, our support team will response if your issue was fixed. I mean I don't control that.

Regards.

**Comment by kerstar** [comment]
Hi!

Ok, in that case I am waiting for a response in ticket. 
I understood from your earlier statement that the error was fixed, and when I checked it, I was surprised that it was still there. So I misunderstood your answer.

In that case, I will follow my ticket.

**Comment by david-phpFox** [comment]
Fixed in Storage App 4.6.4
