### ISSUE TITLE
Show visual feedback when deleting an album with a large set of photos

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2735]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When deleting an album with a large amount of photos, there is no visual feedback that the deletion process is happening in the background. This can take a long time depending on the number of photos in the album and the user gets confused to what's going on or whether their command actually worked.

## Steps to reproduce:
1. Delete an album with a large set of photos. Mine had over 1600 photos.
2. You get no feedback while the deletion process is being executed.
3. In my case, this took over a minute and I had to refresh the page.

## What's expected?
Show a user a scrolling wheel or any kind of feedback that the deletion process is being executed!

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
We will discuss this case.

Regards.
