### ISSUE TITLE
Photo app meta description issue

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2737]
# Important

Please follow this template!

----------------------------------------

## What's happened?
The photo app is appending the following to the end of the meta description "... total of 20 photo(s)." Someone wanted to put the total number of photos but made a mistake I guess. Please remove it. It serves no purpose.

## Steps to reproduce:
1. Visit demo or any other phpfox site - photo section
2. Check meta tags: description
3. Code is appending "...total of 20 photo(s)"

## What's expected?
Remove it please. No one cares how many photos we have! I have not checked every other app like videos, groups, events etc. for similar issues.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

4.7.7 - Latest as of 7/23/19

## Screenshots
![image](https://user-images.githubusercontent.com/48427415/61746391-971de180-ad69-11e9-8dd6-b79d80d6abc4.png)

**Comment by harrison05** [comment]
It shows an incorrect total photo in the meta description. We will check and update it, but we won't remove it. Because it figures out the number of photos on your site and guests will know how large of your site.

Regards.

**Comment by hamadax** [comment]
Well, what if my site site is small or new with a few hundred images? This would actually can be counterproductive or embarrassing to show the world that my site has a 100 photos only! Also, it is not uniform. Other sections / apps meta descriptions do not display the total count of groups, pages, videos, music files, blogs etc... Keep in mind that this will most likely be cut off anyways on search engines depending on how long the admin has set up the meta description for the app. IMO, this is better suited for the user photo section under the profile, not the site's photo section. In other words, it would make more sense to show how many photos a user has, if they allow it through privacy settings.

**Comment by harrison05** [comment]
> Well, what if my site site is small or new with a few hundred images? This would actually can be counterproductive or embarrassing to show the world that my site has a 100 photos only! Also, it is not uniform. Other sections / apps meta descriptions do not display the total count of groups, pages, videos, music files, blogs etc... Keep in mind that this will most likely be cut off anyways on search engines depending on how long the admin has set up the meta description for the app. IMO, this is better suited for the user photo section under the profile, not the site's photo section. In other words, it would make more sense to show how many photos a user has, if they allow it through privacy settings.

Ok. We will discuss this case with your suggestion.

**Comment by spirogg** [comment]
@hamadax @harrison05  this can hamper people to signup to new site's, I agree with @hamadax 
unless you make it a photo app feature where admin can turn this on or off

possible 
Would you like to add the total number of photos of your site in meta description ?  ON / OFF

**Comment by harrison05** [comment]
Our development team decided to remove the total number of photos from meta description. Because it is getting an incorrect value, and related to the privacy of photos, it might slow down site if try to get correctly.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Photos App 4.7.7.
