### ISSUE TITLE
Please indicate that we need to rebuild core theme in order for custom meta description and keywords to take effect.

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2738]
# Important

Please follow this template!

1-There is no mention on admincp/setting/edit/?group-id=seo that we need to rebuild the core theme and clear the cache in that order for the custom seo settings to take effect.
2- Also, the last field on that page "Meta Description Profile" should be "Profile Meta Description" - It is backwards!

## What's happened?
See above. There is no warning or note to indicate that any changes done in the SEO settings must be followed by rebuilding the theme in order for the changes to take effect.

## Steps to reproduce:
1. Change SEO settings for Events or other section
2. Clear cache alone does not cut it, must be rebuild theme, then clear cache.
3. 

## What's expected?
This is not for a user to figure out. Good design tries not to make the user think at all. Please spell it out somewhere on that page or it should be done automatically every time that page is updated.

Thanks!

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
As I know, in almost cases, you have to change Phrase value when update Meta value. 
Example: I change photo meta description phrase
![Screen Shot 2019-07-24 at 10 47 09](https://user-images.githubusercontent.com/41947198/61763691-7c4a7c00-ae00-11e9-9fad-92718ed327e4.png)
And after change them, you must Clear Cache. Don't need to Rebuild Core Theme.

So we will improve 2 points:
- Auto clear cache after Admin change Phrases and apply new values immediately.
- Change "Meta Description Profile" to "Profile Meta Description".

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.8.
