### ISSUE TITLE
Full name not being validated at all or checked for ban words

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2740]
# Important

Please follow this template!

----------------------------------------

## What's happened?
The full name is entered is neither being validated or checked for ban words.

## Steps to reproduce:
1. Use a ban word or a single letter there in the full name field and it will work.
2. I have put my name as F***k and it goes through although that word is banned.
3. I have used special characters and it also goes through such as @@@ @@@@

## What's expected?
Validate the full name and run the ban filter check. I know it is almost impossible to do this with high accuracy, but garbage in equals garbage out. It is better to have some control than none.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

All

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

/4.7.7 - Latest as of 7/23/19

## Screenshots
...
/

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.8.
