### ISSUE TITLE
On Signup New Friend - Only admins are shown!

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2741]
# Important

Please follow this template!

----------------------------------------

## What's happened?
I need to add a staff member account to be the default friend on signup. This is an account dedicated to help new members. Why is it limited to admins only? Why expose admin accounts in the first place?

## Steps to reproduce:
1. Go to admin cp: admincp/setting/edit/?group-id=registration
2. "On Signup New Friend" only shows admin accounts in the drop down.
3. 

## What's expected?
Show and allow staff accounts as well. I do not want to expose any admin accounts.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

All

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

Latest 4.7.7

## Screenshots
...

**Comment by harrison05** [comment]
We will check and inform you if have any update.

Regards.

**Comment by harrison05** [comment]
We will support Admin select a Staff to "On Signup New Friend" setting.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.8.
