### ISSUE TITLE
weird little bug in photo link area / private mode

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2743]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
i have set private for profile and a few other things, in photo i do not have private

 i have set to all but photos don't show ?

## Steps to reproduce:
1.  see photos of settings it will show you my privacy settings
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...
4.7.7
## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/62336004-ec59a180-b493-11e9-84c9-f52b269cf863.PNG)

![Capture1a](https://user-images.githubusercontent.com/17736688/62336008-f085bf00-b493-11e9-9b0e-d23c95b46081.PNG)

![Capture11](https://user-images.githubusercontent.com/17736688/62336017-f67ba000-b493-11e9-9489-1b44d791cd4b.PNG)

**Comment by spirogg** [comment]
![Capture](https://user-images.githubusercontent.com/17736688/62336060-262aa800-b494-11e9-9ea9-2b9c2e5a8392.PNG)

**Comment by spirogg** [comment]
if i set to community the link for photos is now hidden

- 

![Capture](https://user-images.githubusercontent.com/17736688/62336995-62600780-b498-11e9-8f2c-089e42866ebc.PNG)

- 

![Capture](https://user-images.githubusercontent.com/17736688/62337027-84598a00-b498-11e9-8c77-780cfa0efda0.PNG)

**Comment by harrison05** [comment]
Yes, you can control profile menu at **Profile Menu Settings** and what's your problem?

Regards.

**Comment by spirogg** [comment]
@harrison05 What I am saying is that I did not set photos to private so they should show ??

**- look close at the screenshot below** 


** I am a guest Only not logged in**

1) it says it has 58 photos but no photos show when you click photos or albums?

I have set photos to = ALL

so its showing how many photos there are but when you click on the tab there is no photos showing
that is my problem :)
## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/62336004-ec59a180-b493-11e9-84c9-f52b269cf863.PNG)

**Comment by spirogg** [comment]
NO PHOTOS FOUND even though photos shows 58 and photos is set to ALL

**Comment by harrison05** [comment]
> NO PHOTOS FOUND even though photos shows 58 and photos is set to ALL

Ok, I got this. No photos found because the owner doesn't set privacy is Everyone. It might make others confuse, our team will discuss this case.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Photos App 4.7.7.
