### ISSUE TITLE
question, why some profiles you can't click on ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2744]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
  There are some profile photos in your demo site thatyou cannot click on, is this from a setting or from upload via facebook ? or why does this happen ?

thanks

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...
      your demo 

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/62336866-ebc30a00-b497-11e9-9444-aef3397e64ff.PNG)

**Comment by spirogg** [comment]
if you try to click on the round profile photo it is not a link to profile ( its not clickable)  why?

**Comment by harrison05** [comment]
Because of that photo was deleted and only avatar thumbnail still exists.

Regards.

**Comment by spirogg** [comment]
Thanks
