### ISSUE TITLE
Question: Where can I edit the CKeditor templates ?

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2745]
![Screenshot](https://user-images.githubusercontent.com/19594886/62363119-86e5cf00-b4ec-11e9-818b-fbd7a7adaa0e.png)

**Comment by harrison05** [comment]
Could you give us more information?

Thanks!

**Comment by prepperz** [comment]
When you click on the template icon in ckeditor, a window pops up that presents a few options of template choices.

**Comment by harrison05** [comment]
Oh, currently, we don't support Admin custom CKEditor Template. If you want to do this, you have to modify source code.

Regards.

**Comment by prepperz** [comment]
Which file can I find the template source in?

**Comment by harrison05** [comment]
You can find it at **core-CKEditor/assets/ckeditor_full/plugins/templates/templates/default.js**

Regards.

**Comment by prepperz** [comment]
Thank you.
