### ISSUE TITLE
Only able to delete notifications 1 at a time

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2746]
## What happened?
Currently, users are only able to delete q notifications at a time and this can be very overwhelming if they get a lot of notifications. Try deleting a few hundred let alone a thousand. It's a waste of time and really take away from users enjoying the experience.

## What is expected?
Add a delete all notification option

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.7 (Upgraded), Material theme

...

## Screenshots

**Comment by harrison05** [comment]
We supported user delete all notification, just click **View All Notifications**, then select **Delete All Notifications** at Notifications page.

Regards.
