### ISSUE TITLE
phpFox Phrases in iOS app: 'Share something in your mind'

### ISSUE THREAD

**Issue by jwpwhite** [PHPfox-Official/phpfox-v4-issues#2747]
## What's happened?
The phrase 'Share something in your mind' should be 'Share something on your mind'

## What's expected?
I have updated the phrase in Admin CP however the phrase is not changing in the iOS mobile app.

## Steps to reproduce:
1. Core Version: 4.7.3
2. Mobile Api: 3.3.3
3. Mobile App: 1.5

## Browsers and Devices tested
iPhone 7 running iOS 12.3.1

It would be great if phpFox could get a full review of their English phrases because many of them use pretty poor English. 'Share something in your mind' is the first thing you see when the app opens so it does not give a good first impression to users.

**Comment by harrison05** [comment]
We will fix this.

Thanks.

**Comment by hamadax** [comment]
> It would be great if phpFox could get a full review of their English phrases because many of them use pretty poor English. 'Share something in your mind' is the first thing you see when the app opens so it does not give a good first impression to users.

I second that. I would help if there is a way to do this. I must have fixed hundreds of phrases already.

**Comment by david-phpFox** [comment]
Fixed in Mobile 1.6.x
