### ISSUE TITLE
No instant message on nodejs on phpfox 4.7.7

### ISSUE THREAD

**Issue by doserg** [PHPfox-Official/phpfox-v4-issues#2749]
The module does not work on nodejs with phpfox 4.7.7.
I tried all versions 8,9,10,11 and 12.
In the logs I get a very large number of messages of the form

onConnection
VERIFY HOST
VERIFY CLIENT: failed
VERIFY HOST: ok
connect with
VERIFY TOKEN
CLIENT TOKEN: a14f2fd5dd41d7ee08 ............
SERVER TOKEN: a14f2fd5dd41d7ee087 ...........
VERIFY CLIENT: successfully

If I turn on the nodejs server, the browser loads the processor.
config.js checked many times.
Please help me figure it out.

**Comment by harrison05** [comment]
I recommend you submit a ticket in Client Area if you have a problem when setup nodejs server for IM App.

Regards.

**Comment by doserg** [comment]
Thank.  Wrote and Ticket.  Maybe someone has encountered such a problem.

**Comment by harrison05** [comment]
Ok, just follow your ticket.
