### ISSUE TITLE
Please add "expand all" button on both front and back end activity points actions so the user does not have to click 15 times!

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2751]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Whether this is being used from the front end "how to earn" section or back end "/admincp/app/?id=Core_Activity_Points", the user has to expand each item to see the data. Please add a simple "expand /collapse all" to open/close all of them in one click. Currently, it is annoying and counter intuitive to have to click each one - up to 15 times!!!

## Steps to reproduce:
1. Go to either sections mentioned above, more importantly: "how to earn" page
2. No option to expand and collapse all
3. 

## What's expected?
Add a button or icons to open all, so the user does not click over and over again to see the breakdown of points.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

All
## Server information
(Example: CentOS 7, php 7.1 apache)

NA

## phpFox version
(Example: phpFox 4.6.0)

Latest as of 8/20/19

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/63316894-ac414e00-c2de-11e9-92cd-b43ce592d9f4.png)

**Comment by harrison05** [comment]
We will check and improve it.

Thanks.

**Comment by harrison05** [comment]
Fixed on Activity Points v4.7.7
