### ISSUE TITLE
Editing Announcement Content in English does not update in admin until cache is cleared

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2753]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Editing an existing announcement content does update in the admincp until ache is manually cleared.

## Steps to reproduce:
1. Edit existing announcement and view on front end. It updated.
2. Go to same announcement in admin cp and edit again. Old content is still there.
3. Old content will not update in the admin cp until cache is cleared.

## What's expected?
Please fix the issue in the edit announcement page.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

All

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

Latest as of 8/20/19

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/63320281-4d360600-c2eb-11e9-89ef-8c08f18bb51c.png)

**Comment by harrison05** [comment]
This issue will be fixed in the next version of Announcement App.

Thanks.

**Comment by harrison05** [comment]
This bug was fixed in Announcement v4.6.1.

Regards.
