### ISSUE TITLE
Phrase for Guest and Banned Groups in Blogs "Approve blogs before they are publicly displayed?" is confusing.

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2754]
# Important

Please follow this template!

----------------------------------------

## What's happened?
"Approve blogs before they are publicly displayed?" is set to true by default for guests and banned groups in Blogs. Same phrase for Events is much clearer: "Events must be approved first before they are displayed publicly?"

The idea is to be uniform and clear in Pages, Groups, Events etc...

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
Please update phrase to match that in the Events and Groups settings. "Blogs must be approved first before they are displayed publicly?"

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

4.7.7

## Screenshots
...

**Comment by hamadax** [comment]
I may have misunderstood what this means. Anyhow, the language used is not clear, but I now think this is not a bug.

**Comment by harrison05** [comment]
We will review these phrases in our Core Apps.

Regards.

**Comment by david-phpFox** [comment]
Fixed in the newest version of apps released.
