### ISSUE TITLE
when you are in Pages or Groups and adding a Thread in discussion, there are still links to main forum ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2760]
----------------------------------------

## What's happened?
...   When I add a thread in Pages (discussion) and click on the thread the top still has all the links to the main website forum, so if they click on it they will be takien away from the Pages discussion - Thread ??

## Steps to reproduce:
1.  See Photo Below
2. when you create a page, then add a thread, then click on the thread, the very top links are to the main forum so if you click on them you get lost in the main forum, you should not see the main forum links - it should take you to the main Discussion for the Page you created
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

... 4.7.7

## Screenshots
...
As you can see below the top links I have lined with ? mark are the links that take you away from the Pages Discussion - Thread 

- 
![pages discussion board has links to regular forum](https://user-images.githubusercontent.com/17736688/63990148-8c611580-caa8-11e9-9d5b-2b947aa9bd2a.PNG)

- Groups discussion has the same issue 

![group discussion](https://user-images.githubusercontent.com/17736688/63991260-a1d83e80-caac-11e9-8f3c-4f913c3ecf40.PNG)

**Comment by harrison05** [comment]
All apps integrate with Pages/Groups are working with workflow. Items you post on Pages/Groups still belonging to those apps. So when you view detail, it shows App's menus. We don't have plan to change this.

Regards.

**Comment by spirogg** [comment]
@harrison05 is there a way to hide those links in groups and pages only ? just wondering

thanks

Spiro

**Comment by harrison05** [comment]
Modify source code is the only way to hide those links. Because we don't support Admin hide them from AdminCP

Regards.
