### ISSUE TITLE
site_name in phrase doesn't seem to give me my sitename ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2762]
----------------------------------------

## What's happened?
...
  in phrases I am trying to add {site_name} so it will show in front end of website, but it's not

the phrase I am trying to change is: 
This link leads to an untrusted site. Are you sure you want to proceed to {link}?

and I want to change it to:
This is an external link. By Continuing, you will be redirected to another website that is not endorsed by nor part of {site_name}  Are you sure you want to proceed to this {link}?

the site_name wont show up in front end popup, is there not a way to have this show the sitename, when adding {site_name} in phrases like we already have in other phrase areas and it shows ?

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

4.7.7

## Screenshots
...

- here is phrase below: 
![site_name not working](https://user-images.githubusercontent.com/17736688/63995252-8295dd00-cabd-11e9-8aef-b0ba3ff6e513.PNG)

- and here is screen shot, it doesn't allow to get the real sitename in the popup ?
![popup](https://user-images.githubusercontent.com/17736688/63995302-a0634200-cabd-11e9-8c36-ab20a17a354b.PNG)

**Comment by Bjoern3003** [comment]
The Phrase, where you are adding the Variable, has to support it.

You can not add to all phrases your own Variables.

In you case, you have to write the sitename in plain text. or if its a custom phrase, who you have added in a template file or app, you have to add site_name as supported variable.

For example 
`_p('this_link_leads_to_an untrusted_site', array('site_name', Phpfox::getParam('core.site_title'));`

**Comment by harrison05** [comment]
@spirogg If you and a new variable on a phrase, you should add value for it when using that phrase in source code.

**Comment by spirogg** [comment]
> @spirogg If you and a new variable on a phrase, you should add value for it when using that phrase in source code.

ok I request feature request here #872
@Bjoern3003 thank you for your response also 
and @harrison05 thanks for all your help :)
