### ISSUE TITLE
In groups and pages using mobile drop down gets hidden

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2763]
----------------------------------------

## What's happened?
...
When using your mobile phone and clicking on the gear to edit delete feature etc the pages or groups the drop down gets hidden by the category 

See photos 
## Steps to reproduce:
1. Use your mobile and go to pages or groups select the gear you will see the drop down and a little part of it gets hidden from the category drop down 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

... 4.7.7

## Screenshots
...

**Comment by spirogg** [comment]
![Screenshot_20190902-094547](https://user-images.githubusercontent.com/17736688/64123304-9ebda680-cd69-11e9-964d-8c18afd466a2.png)
![Screenshot_20190902-094522](https://user-images.githubusercontent.com/17736688/64123337-b8f78480-cd69-11e9-8525-d4cee89e1a23.png)
![Screenshot_20190902-094516](https://user-images.githubusercontent.com/17736688/64123352-c01e9280-cd69-11e9-8921-5ca613056b35.png)

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.8.
