### ISSUE TITLE
Bug in Shoutbox app - Delete old messages not working

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2764]
## What's happened?
Some time ago (a few months ago) I set the "Delete old messages" function in the Shoutbox settings to 30 days.
I later added a message in the Shoutbox app.

According to this setting, it should be automatically deleted after 30 days. 
Unfortunately, the message has not been deleted.

P.S.
By the way, 2 months ago I reported to you another bug in the Shoutbox application and it has still not been repaired: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2734
When will you release the patch?

Can you help me fix both issues?

I gave the data to FTP in ticket number: #117431

Thanks.

## phpFox version
4.7.3

...

## Screenshots
![Shoutbox_bug1](https://user-images.githubusercontent.com/38014237/64134604-a3bd3d00-cddf-11e9-833c-52df9abecc79.png)
![Shoutbox_bug2](https://user-images.githubusercontent.com/38014237/64134605-a3bd3d00-cddf-11e9-9078-fa6280827f63.png)

**Comment by harrison05** [comment]
> Some time ago (a few months ago) I set the "Delete old messages" function in the Shoutbox settings to 30 days.

> I later added a message in the Shoutbox app.
According to this setting, it should be automatically deleted after 30 days.
Unfortunately, the message has not been deleted.

This is a bug of shoutbox, we will check and fix it.

About #2734 , we fixed this issue but we haven't released a new version of Shoutbox yet, so I don't update the label of that topic.

Regards.

**Comment by kerstar** [comment]
@harrison05 

Ok, I understand. I have two questions. If you can, pease answer them:
1. When do you plan to release an update for this application that fixes these bugs?
2. Will the update be compatible with phpfox 4.7.3? (it's important for me)

**Comment by harrison05** [comment]
1. I don't know when we will release this app, maybe after version 4.7.8 of phpFox, it decided by our manager.
2. Yes, start support version of Shoutbox is 4.6.0, so it compatible with 4.7.3.

Regards.

**Comment by kerstar** [comment]
I meant whether the update that will fix these bugs will be compatible with phpfox version 4.7.3.
I asked because not all updates are compatible with this version (e.g. Photos, Groups, Pages, Movies apps).

In that case, I am waiting for the update (I hope you will release it soon).

**Comment by harrison05** [comment]
> I meant whether the update that will fix these bugs will be compatible with phpfox version 4.7.3.

If the next version of Shoutbox doesn't require phpFox version higher than 4.7.3, it will compatible with v4.7.3. With the current source code, the min phpFox version for the next version still is 4.6.0.

Regards.

**Comment by kerstar** [comment]
@harrison05 

You have fixed this error in the update, BUT...
The issue is still when someone likes our message in Shoutbox.
Then, after a certain time, the message is not deleted, but it still appears.

Harrison, can you check it on my website?
Can you help me fix this issues?

I gave the data to FTP in ticket number: # 117431
