### ISSUE TITLE
cover_image_server_id is missing in groups getSameCategoryPages() function

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2765]
in the getSameCategoryPages() in PF.Site\Apps\core-groups\Service\Groups.php is the cover_image_server_id missing for the related block.

Find:
`return db()->select('p.*, pc.name as category, pu.vanity_url, u.*, pt.destination as cover_image_path')`

Replace:
`return db()->select('p.*, pc.name as category, pu.vanity_url, u.*, pt.destination as cover_image_path, pt.server_id as cover_image_server_id')`

**Comment by kerstar** [comment]
Hi @Bjoern3003 

What is the manifestation of this issue?

**Comment by Bjoern3003** [comment]
This, what the function said :-)

It does not show the Cover Image on the related Groups Block.

**Comment by kerstar** [comment]
Thanks for the explaining and sorry for my bad english ;)

**Comment by david-phpFox** [comment]
Fixed in Groups 4.7.7.
