### ISSUE TITLE
Subscribe a recurring package in url /subscribe not update column "renew_type" = 1

### ISSUE THREAD

**Issue by akiraphat94** [PHPfox-Official/phpfox-v4-issues#2766]
# Important

Please follow this template!

----------------------------------------

## What's happened?
- When user subscribe a new recurring package in page /subscribe. Column "renew_type" empty in table "phpfox_subscribe_purchase" (renew_type in case should be value 1 for recurring package)

## Steps to reproduce:
1. login
2. go to page /subscribe
3. select a recurring package
4. check column "renew_type" in table "phpfox_subscribe_purchase" we will see "renew_type" = NULL

## What's expected?
I think in case column "renew_type" = 1 is correct ?

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

Chrome Windown 10

## Server information
(Example: CentOS 7, php 7.1 apache)

7.2.11 apache

## phpFox version
(Example: phpFox 4.6.0)
phpFox 4.7.2
...

## Screenshots
...
![subscribe](https://user-images.githubusercontent.com/11713836/64422215-b9777e80-d0cd-11e9-94f7-42d4b91ceb48.png)
![db](https://user-images.githubusercontent.com/11713836/64422275-e62b9600-d0cd-11e9-8f8d-2f93f5b6646a.png)

**Comment by harrison05** [comment]
Renew method only update after you select one and select a gateway to pay your subscription. 
It's working well on my side.

Regards.
