### ISSUE TITLE
Blog changelog path is wrong from store

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2767]
## What happened?
Changelog doc path for blog from admin cp is wrong. it's showing: https://docs.phpfox.com/display/FOX4MAN/Blog+-+Changelog

Correct path should be: https://docs.phpfox.com/display/FOX4MAN/Blogs+-+Changelog

## Steps to reproduce:
1. from admincp: apps > find more > blogs > changlog > our doc

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.7 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
We updated it.
Thank you.
