### ISSUE TITLE
Third Bug in Shoutbox app - Delete old messages again not working after update App

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2768]
## What's happened?

Guys...

Recently, I reported to you two bugs in the Shoutbox application that you fixed in the update.

After installing this update, the issue at first glance was gone - messages after a specified time were deleted.

However, in some circumstances messages are not deleted.

Well, I added a message with only the Emoji icon, and then I liked the message from another user's account.

After a period of 1 day (after this period, messages should be deleted), the message has not been deleted (More than 29 hours have passed since this message was added).

I don't know if the reason was that the message was just an Emoji icon or because another user liked the message.

Can you help me fix this problem?
This is very important to me because I will modify the Shoutbox application, and unfortunately I can't start work if it contains an bug.
I hope you don't make me wait for the update again... ;/

You can see the bug on my page.
Applies to messages containing the Emoji icon itself.

Can you help me fix this small issue?

I gave the data to FTP in ticket number: #579710

## Steps to reproduce:
1.  Add only Emoji to the message
2.  Like this message from another account
3.  The message will not be deleted automatically after a specified time

## Screenshots
![Shoutbox_bug3](https://user-images.githubusercontent.com/38014237/64998071-0ab01b00-d8e3-11e9-9e2e-ed8f2fc22398.png)

![Shoutbox_bug4](https://user-images.githubusercontent.com/38014237/65004974-98e5ca80-d8fe-11e9-870f-92b361e7f928.png)

**Comment by spirogg** [comment]
Hi @kerstar just wondering after updating the app did you click on remove files not needed, then clear cache and rebuild core?
Not sure if that may help ?

**Comment by spirogg** [comment]
Or do you think clearing cache or all cache in Admincp might fix it ? Maybe since emoji it's stuck in cache ?

**Comment by harrison05** [comment]
Hi @kerstar , do you set up cron job on your site? Because our development team said that issue was fixed and verified.

Regards.

**Comment by kerstar** [comment]
Hi @spirogg 

I updated the Shoutbox app, then cleared the cache.
I did not click "remove files not needed" and "rebuild core theme" after updating this application.

Hi @harrison05 
It is strange, but the message with the icon has disappeared, but the next test message is still despite the fact that 24 hours have passed since it was sent.

Regarding the cron settings - yes, everything is definitely well set up here. I did it according to your instructions - if I add a movie to the site, it will be published in a moment - cron works.

Harrison, why is the message not deleted after 24 hours if I set the message to be deleted in the Shoutbox application after 1 day?

It's kind of weird. 24 hours pass, cron should delete this message.

The time on my server is set correctly - it is late than the one on my computer by 2 hours, but the message was added on September 17 at 00:17, and as I just checked on the server I have the date and time September 18, 01:38 (see the attachment to this message), I had 3:38 on my computer at the time, so according to both times it was more than 24 hours and cron did not delete the message.

![Shoutbox_bug5](https://user-images.githubusercontent.com/38014237/65099700-f4c85600-d9c7-11e9-87fc-f4e1afd493f7.png)
![Shoutbox_bug6](https://user-images.githubusercontent.com/38014237/65099702-f4c85600-d9c7-11e9-993b-bbfce36a6928.png)

**Comment by harrison05** [comment]
I think is have an issue with your cron when it executes, it might be stuck by something else. So we need to check it on your site. Please follow your ticket, our supporter will handle it.

Regards.

**Comment by kerstar** [comment]
Hi!

There must be a issue somewhere, but I don't know where.

I found a function that is responsible for deleting messages that are older than the number of days that was set in the Shoutbox application settings - in my case it is 1 day.

![Shoutbox_bug12](https://user-images.githubusercontent.com/38014237/65188467-c3ef2c00-da6e-11e9-8c8f-1b70e82ee6ab.png)


The function logic appears to be correct, but after 24 hours cron job does not delete the message. 
It removes them much later and I don't know what it depends on.

I thought the reason may be that the time on the server is set incorrectly, but for this I added a new message to the Shoutbox named "test" and then read the timestamp value in the mysql database for "phpfox_shoutbox" for this message.

![Shoutbox_bug8](https://user-images.githubusercontent.com/38014237/65188500-d8cbbf80-da6e-11e9-8c1f-d24c1650224c.png)


Then I compared the timestamp values ​​between the first message and the second one and it turned out that I added the second message 26.5 hours after I added the first message, so the first message should be deleted after 24 hours, but it is still visible.

Then I made sure that the cron job is well configured.
Here are its settings:

![Shoutbox_bug11](https://user-images.githubusercontent.com/38014237/65188539-f4cf6100-da6e-11e9-9fcb-9251f4e924dd.png)


To be sure, I added a movie from a computer that is processed using FFMPEG on the server. 
After a short time, the film was visible on the site, so cron job works.

![Shoutbox_bug10](https://user-images.githubusercontent.com/38014237/65188651-2cd6a400-da6f-11e9-810d-f0f9b822bf7e.png)

I have no idea what could be causing this bug.

@harrison05 can you ask Paul to check it?
I added the application on Tuesday, but Paul still has not checked it, because the ticket has a slow status, and as you can see I am trying to help you diagnose the bug (which I have been doing for 2 years...).

Ticket number where I provided access to the site: #579710

![Shoutbox_bug7](https://user-images.githubusercontent.com/38014237/65188704-4f68bd00-da6f-11e9-87e9-59460768b2cf.png)
![Shoutbox_bug9](https://user-images.githubusercontent.com/38014237/65188705-4f68bd00-da6f-11e9-80aa-5d6eb419592d.png)

**Comment by kerstar** [comment]
The message is still visible after 36 hours

![Shoutbox_bug13](https://user-images.githubusercontent.com/38014237/65210302-0595cc00-da9b-11e9-8eeb-9bcd0e27428a.png)

**Comment by harrison05** [comment]
Because of our Delete Old Message function is set on Cron, and it runs one time per day. 

Example: Last run of it is **12 PM today (A)**, so next time it runs is **12 PM tomorrow (B)**. But your message send on **8 AM today** so when (A) run > this message won't be deleted before (B) run > Even though it over 24h but message still appears because (B) run on 12 PM.

Don't be rush, it have a schedule and if you set Cron correctly, it will run, I'm absolutely sure.

Regards.

**Comment by kerstar** [comment]
Hi,

Ok thanks for explaining @harrison05 
Thank you.
