### ISSUE TITLE
When update a feed the date should change ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2769]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
Hi I had a feed from Sept 7th I wrote. Today I click edit and wrote more. But the date stay the same and it did not move to top of feed ?
## Steps to reproduce:
1. Edit a feed you posted a few days ago
2. Now go.look at date it stays the same 
3. Also refresh feed the new updated feed you edited doesn't change to top of feed 

## What's expected?
...
It should update new date and become top of feed 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

... 

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

... 4.7.7

## Screenshots
...

**Comment by harrison05** [comment]
Feed update_date will change if someone comment or like it.

Regards.
