### ISSUE TITLE
Mobile app shows days in feed in Spanish ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2770]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
Hi I downloaded mobile app again from Google, (Android) and check my site. In feed it's showing Spanish words for howahy days the feed was or how many minutes , hours. 
## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...
Not sure if you have different languages built into app but I only have English language not Spanish. 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![Screenshot_20190916-220742](https://user-images.githubusercontent.com/17736688/65037801-11a35180-d914-11e9-847b-abb6b0a65eb0.png)
![Screenshot_20190916-221619](https://user-images.githubusercontent.com/17736688/65037819-1d8f1380-d914-11e9-8a63-ffadd4ea1ca4.png)
![Screenshot_20190916-221247](https://user-images.githubusercontent.com/17736688/65037833-27b11200-d914-11e9-81ae-9aead4eac7e9.png)

**Comment by spirogg** [comment]
Also on main website above the feed shows the month date year and time 
In my photo one feed shows September 7, 2019 12:15pm 
But on mobile app it's just says hace 9 dias , even though the site has only English language.

**Comment by harrison05** [comment]
Could you check your language code again (AdminCP > Globalization > Languages)? It is EN or EO? Because mobile app gets date info and translates based on the language you selected.

Regards.
