### ISSUE TITLE
CDN not working, when cache_skip enabled

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2771]
We are using CDN for Images.

But, if the $_CONF['core.cache_skip'] set to true, phpfox is trying to get images from server, and not from cdn.

That, what I found is, that the setting() function in PF.Site/Apps/core-cdn/start.php and \PF.Site\Apps\core-cdn\Model\CDN.php returns null, if I set cache_skip to true.

**Comment by kerstar** [comment]
Hi @Bjoern3003 
Can you tell me, what exactly is the cache_skip function used for?

**Comment by harrison05** [comment]
> That, what I found is, that the setting() function in PF.Site/Apps/core-cdn/start.php and \PF.Site\Apps\core-cdn\Model\CDN.php returns null, if I set cache_skip to true.

Which version of CDN App you're using? Could you give us the line number of that code? Because we don't see CDN check cache_skip in it.

Regards

**Comment by Bjoern3003** [comment]
This is a global conf from phpfox to skip the sidewide cache.

**Comment by harrison05** [comment]
> This is a global conf from phpfox to skip the sidewide cache.

But CDN App doesn't use this config. It weird.

**Comment by Bjoern3003** [comment]
I have describred at the top.

Please read again. 🙂 The core setting function returns null.

Maybe a cache problem, that settings not loading, when cache is disabled.

**Comment by harrison05** [comment]
Yes, I got it now. It is an issue with Cache setting when enabling cache_skip. We will check this issue.

Thanks.

**Comment by Bjoern3003** [comment]
Can you release the bigfix here, please, so i can fix it on our environment too.

**Comment by harrison05** [comment]
> Can you release the bigfix here, please, so i can fix it on our environment too.

Our team is finding a solution to this issue, it's hard to fix. This setting is recommended for developers, so if you run a production site, don't enable it, site will be slow down.

Regards.

**Comment by Bjoern3003** [comment]
I have it only enabled on our dev pages.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.8.
