### ISSUE TITLE
I found the fifth big bug in the CDN application...

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2772]
## What's happened?

My hands fall...
I found the fifth bug in the phpFox Storage (CDN) app...

The bug is that after adding the video, it cannot be played.

The bug is definitely in the phpFox CDN application, because the first video that was added before I configured the CDN can be played correctly.

Here I can't provide video links on my site, but I gave them in ticket number: #702331

Check this @harrison05 , it's two minutes and you will make sure that the bug is 100% in phpfox Storage (CDN).

Yes, I use the Video Viewer Popup application, but it is definitely not the cause of the problem.
If you go to "View Detail Page" then this application is not there and the bug occurs. - I mention this because you similarly claimed with an issue with photos, and at the end it turned out that I was right and that there was an bug in the phpfox CDN, and not in the Photo Viewer Popup application.

Yes, I submitted the ticket...
Anyway, I've already reported four other bugs in phpFox that you have fixed.
I hope you will help me because you can see that I care about good quality phpFox...

Earlier bugs that I reported in the phpFox CDN application (one cannot be found here):
1. https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2730
2. https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2727
3. https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2714

## Screenshots
![cdn_video_1](https://user-images.githubusercontent.com/38014237/65206110-61a62380-da8e-11e9-8373-cb81ab974e58.png)
![cdn_video_2](https://user-images.githubusercontent.com/38014237/65206111-61a62380-da8e-11e9-862c-91d2bf852738.png)

**Comment by harrison05** [comment]
Hi @kerstar ,

Which is the URL of the error video? CDN link or Local link

**Comment by kerstar** [comment]
Hi @harrison05 

The issue concerns the CDN link.
The video that is locally on the server has no error and can be played.

I would not like to publicly provide a link to my page here - I gave it in the ticket #702331

**Comment by harrison05** [comment]
Oh, our supporter will check your ticket.

Regards.

**Comment by kerstar** [comment]
Ok, in that case I am waiting for the answer in the ticket.

**Comment by kerstar** [comment]
Hi,

@harrison05 The problem is that the video link goes to a local server (where there is no video) instead of pointing to the CDN server where the video is located.
Video thumbnails are loaded correctly from the CDN server.

Exactly the same problem was with photos.
In this case, you have corrected this bug (for photos) (for which I thank you) and said it was a CDN app bug.

Guys, fix this issue, it's just a few minutes...

![cdn_video_3](https://user-images.githubusercontent.com/38014237/65471412-46149180-de6f-11e9-9864-da035782048b.png)

**Comment by harrison05** [comment]
Maybe, it gets wrong CDN server_id or server_id when get URL to view doesn't match. After you uploaded video, do you change or delete CDN servers in AdminCP?

**Comment by kerstar** [comment]
No, I did not change anything in the CDN server settings, nor did I delete or add a new server. 
I didn't change anything here.

The video has been correctly uploaded on the CDN server, the video thumbnails are also on the CDN server (the thumbnails are displayed correctly), however the video player tries to load the video from the local server (where there is no video) instead of from the CDN server.

**Comment by harrison05** [comment]
> No, I did not change anything in the CDN server settings, nor did I delete or add a new server.
I didn't change anything here.
> The video has been correctly uploaded on the CDN server, the video thumbnails are also on the CDN server (the thumbnails are displayed correctly), however the video player tries to load the video from the local server (where there is no video) instead of from the CDN server.

Oh, It needs to be check on your site directly to find a reason.

**Comment by kerstar** [comment]
Ok, I'm still waiting on the ticket for an answer...

**Comment by kerstar** [comment]
Hello,
The bug has been repaired.
It turned out to be a bug in the core-videos application.

Instructions for others how to fix it (only if you use CND servers):

In the file:
PF.Site\Apps\core-videos\Service\Video.php

On line 515, replace this code

`if (Phpfox::getParam('core.allow_cdn') && $aVideo['server_id'] > 0 && $aVideo['destination']) {`

on this code

`if ($aVideo['server_id'] > 0 && $aVideo['destination']) {`

**Comment by harrison05** [comment]
Hi @kerstar , 
the issue you found in Video App was fixed in the current version 4.7.5. 
Update your Video App to fix it.

P/s: Please follow our template https://github.com/PHPfox-Official/phpfox-v4-issues/blob/master/ISSUE_TEMPLATE.md when posting an issue. It will help us quickly determine your issue.

Thanks.
