### ISSUE TITLE
Cancelled member delete does not update display

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2773]
## What happened?
When deleting cancelled members, the list displayed is not updated.

## Steps to reproduce:
1. Members > canncelled members > delete

## What is expected?
The list should be updated as well as an option to  select all for mass delete.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.7 (Upgraded), Material theme

...

**Comment by spirogg** [comment]
@prepperz Does it delete after clear cache ? Just wondering

**Comment by prepperz** [comment]
it only updates display when you refresh

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.8.
