### ISSUE TITLE
when you have subscriptions off it should hide Membership in dropdown menu ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2775]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...  when I turn off subscrptions or never have activated them, the membership in the user dropdown should be hidden somehow. 

## Steps to reproduce:
1.  turn off subscriptions
2. go to the top right  dropdown and you see membership link
3. this link should be hidden

## What's expected?
...
when subscription feature is off the Membership link should be hidden

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
chrome
...

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7.2
...

## phpFox version
(Example: phpFox 4.6.0)

...   4.7.7

## Screenshots
...
- 
![Capture](https://user-images.githubusercontent.com/17736688/65381144-b6c17f80-dcb0-11e9-91e0-20dd108c095a.PNG)
- 
![Capture2](https://user-images.githubusercontent.com/17736688/65381146-bfb25100-dcb0-11e9-8682-dbe414524c44.PNG)

**Comment by harrison05** [comment]
I don't think it's possible, even though you disabled those settings, users still see the old packages they were purchased, "My subscription" still available. But I know, with a new user, this is useless. We will discuss about this case.

Regards.

**Comment by hamadax** [comment]
I just ran across this issue. Agree with @harrison05. New users should not see this. A workaround @spirogg is to disable the app from admincp/apps/ and that will hide it in the user menu and send to 404 page if they still manage to visit this section. Not ideal, but does the job for me for now.

**Comment by spirogg** [comment]
@harrison05 any word on this ?

**Comment by harrison05** [comment]
We improved it in Subscriptions App v4.6.6 - Membership menu only shows when the setting "Enable Subscription Packages" is enabled or users have at least one purchase.

Regards.
