### ISSUE TITLE
Saved App: my collections default image disappears after adding or removing saved

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2777]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
  I Created 3 collections, then added some things to 2 of them.
 then added a 4th collection but it would not show in the left block (recently updated).
- Also When I went to My Collections the default image disappeared for the collections I saved things too

## Steps to reproduce:
1.  go to saved 
2. click to add collection add a few collections 
3. after look at collection in left side (recently updated) - its not showing all collections just the ones you added something too   
4. then go to my collection and look at collection that has something added to it. 
**its blank no default image shows.** 
- but the collection that you did not add anything too has the default image

## What's expected?
...
 first I think we are caching the collection in the left side (left block recently updated), so when you add a collection it doesn't show in the list until you add something to the collection ( recently updated left block)
 - So we should Not Cache this block

**Also When you click on My Collection:**
- the default image should not disappear after you have saved some things to your collection

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

... chrome firefox

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 tested with php 7.2 php 7.3

## phpFox version
(Example: phpFox 4.6.0)

...4.7.7 fresh install 

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/65389647-1b66f380-dd1e-11e9-992e-71569aec64d0.PNG)

- Notice there are 4 collections and below image shows only 3 collections in left (Recently updated  Block)

![Capture1](https://user-images.githubusercontent.com/17736688/65389656-26ba1f00-dd1e-11e9-94ed-91a25a04d03c.PNG)

**Comment by spirogg** [comment]
**UPDATE ON BLOCK:**

After 10 mins or more... I finally see in Recently Updated Block, the Latest Collection I added: **3test** 

so this block is for sure cached....
- we should not cache this block cause users can get confused why there collection not showing in recently updated Block

![Capture](https://user-images.githubusercontent.com/17736688/65389828-8a911780-dd1f-11e9-835a-da19720882e1.PNG)


-----------------------------------------------------------------------------------

**BUT STILL ISSUE with default image disappearing**

When you click on My Collection:

- the default image should not disappear after you have saved some things to your collection

**Comment by spirogg** [comment]
- Maybe we should create a feature where users can upload their own photo for each collection they create (like Music Platlist) ,


![image](https://user-images.githubusercontent.com/17736688/65392069-19109380-dd36-11e9-9bca-c55a49236f02.png)



- If not there should still be a default image for each collection whether there is something in the collection or not. 
- this default image should not disappear

- or  You can create the default image in the saved app for (My Collection) , to be like when a new user signs up, their profile image is 2 letters and a different color.
- So make the default image in (my collection) like the default image of a new user ? 

like below image:
![Capture](https://user-images.githubusercontent.com/17736688/65390064-3850f600-dd21-11e9-85ce-3d14e8d5682f.PNG)

**Comment by harrison05** [comment]
Hi @spirogg ,

- Block Recent Updated only shows 3 collections and sort by Last Updated. When you add new collection, it goes to top of this block. But if don't shows, might a bug of Cache, we will check this case again.

> then go to my collection and look at collection that has something added to it.
its blank no default image shows.

- I can reproduce it now. We will also check it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Saved Items 4.1.1
