### ISSUE TITLE
question about google ads and ajax mode ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2778]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
https://docs.phpfox.com/display/FOX4MAN/Setting+up+Google+Adsense

- I just finished reading this doc about google ads and confused, it say we need to turn off ajax mode for google ads to work??
-----------------------------------------------------------------------------------
- This tutorial will work for any type of ad with javascript
- As an Admin you can create HTML based ads directly from your AdminCP by creating a new block, choosing HTML as the block type. This is what we will use for our Google ads.

- When making your ad at Google, please be sure your code is async.

**Original ads code from Google which you can use on your block, _with ajax mode disabled,_ in v4.4 and above:**

**Why we have to disable ajax mode ?** 

**seems really weird that we can't keep ajax mode ON to keep ads working.**

I have not tried yet but reading below it says **_with ajax mode disabled,_ in v4.4 and above:**

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
... google ads should work with ajax mode ON or OFF ? 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.2 7.3

## phpFox version
(Example: phpFox 4.6.0)

...
4.7.7
## Screenshots
...

**Comment by harrison05** [comment]
Because when you enable ajax mode, user switch between pages, the browser doesn't refresh, it just pushes new contents, Google Ads might not load/init or not tracking, not appears, something else...

Regards.

**Comment by spirogg** [comment]
@harrison05

Maybe an Idea ??


Is it possible to add some code before or after the Google code that will disable ajax mode when adding an advertisement in any block just for that advertisement. ? 

So when adding Google ads above the Google code or below the Google code  we add some other code that will turn off ajax just for that certain advertisement only when that code runs ? Would be better than turn off ajax mode for whole site ??
