### ISSUE TITLE
ad app: when click preview ad its all dark you don't really see the ad

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2779]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... Hi I created an ad placement for block 11 and then went to create an ad, uploaded a image and clicked preview. after clicking preview the image and page is really dark i canot see the preview of my ad

## Steps to reproduce:
1. create ad placement on block 11
2. upload a image - banner 
3. click preview

## What's expected?
... should be a clear view not dark so you can see the actual preview of the image - banner you uploaded

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)
centos 7 php 7.2
...

## phpFox version
(Example: phpFox 4.6.0)

...4.7.7

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/65464073-a4655400-de1e-11e9-83d1-969953fa5597.PNG)

**Comment by harrison05** [comment]
I see preview image is under dark overlay, this is a bug, we will check and fix.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Better Ads 4.2.7.
