### ISSUE TITLE
Events app: View on Map missing event photo we uploaded

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2782]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Missing Event Photos in view on Map
## Steps to reproduce:
1. go to events
2. click on view on maps
3. scroll to see an event - photos don't show

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...4.7.8 upgraded

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...
![event-0](https://user-images.githubusercontent.com/17736688/65635502-0ef4cc00-dfa6-11e9-9ea6-9b5434f68ee2.PNG)
![events-map-no-photo-showing](https://user-images.githubusercontent.com/17736688/65635517-16b47080-dfa6-11e9-8415-0bfaf1c063b7.PNG)

**Comment by spirogg** [comment]
PS. If we don't add our own photo it shows default event photo 
- But if you add a photo does not show uploaded photo

**Comment by harrison05** [comment]
Oh, this issue might be related to setting "Keep Non Square Images". Do you turn off this setting on your site? We will update the Event App and upload to phpFox store.

Regards.

**Comment by harrison05** [comment]
@spirogg You can get the new build of Event on Store now. We just fixed this bug.

**Comment by spirogg** [comment]
@harrison05 Keep Non Square Images". Do you turn off this setting on your site? YES
 I turned this off.

- But I don't see a new version it shows 4.7.2 still for events ?

**Comment by spirogg** [comment]
@harrison05 

OK 

- **It's the Same version number 4.7.2**
- **We All just need to go to store and reinstall Events App and it Works Now** 

Thanks

Spiro

**Comment by spirogg** [comment]
@harrison05 

You should change version number so in Admincp those customers that downloaded and upgraded before fix will know it's been updated and fixed 

Just my thoughts 

Thanks again Spiro

**Comment by david-phpFox** [comment]
Fixed in Events 4.7.3
