### ISSUE TITLE
Profile comment edit option barely visible

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2783]
## What happened?
...Profile comment edit option is barely visible.

## Steps to reproduce:
1. Post a comment on a user's status.
2. Try to edit comment,
3. 

## What is expected?
Should be darker and visible.

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.7 (Upgraded), Material theme

...

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/19594886/65636188-d35eff80-dfaf-11e9-8742-54a2866d6d59.png)

**Comment by harrison05** [comment]
I don't think this button is too hard to see. It shows when you hover on the comment.

**Comment by prepperz** [comment]
Ya. It's barely visible when you hover over it. It needs to be more obvious to improve and make it easier on the user experience. On facebook it's very easy to see. Even on github it's very clear to see. 

On phpfox, not so much. Why does phpfox make so much harder for the user just to use it?

**Comment by harrison05** [comment]
Okay, I will check with the development team about this case.

Regards.

**Comment by david-phpFox** [comment]
Improved in Comments app 4.1.1.
