### ISSUE TITLE
Two technical questions about phpfox 4.7.8

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2784]
## What's happened?

Question 1:

In files:
PF.Base/module/admincp/include/component/controller/demo.class.php
PF.Base/module/admincp/include/component/controller/limit.class.php
PF.Base/module/admincp/include/component/controller/upload.class.php

you added this code:

```
        // check authorization
        Phpfox::isUser(true);
        Phpfox::getUserParam('admincp.has_admin_access', true);
```

Is this a security patch?

Question number 2:

Is this file: PF.Base\module\api\template\default\block\gateway\form.html.php 

and function:

```
$Behavior.disableButtonWhenClick = function () {
  if ($(".js_core_action_button_disable_check").length) {
    $(".js_core_action_button_disable_check").each(function () {
      $(this).on('click', function () {
        $(this).prop('disabled', true);
        $(this).parents('form:first').submit();
      })
    });
  }
}
```

in file: PF.Base\static\jscript\main.js

responsible for improving "Prevent users from double-click when purchasing with Activity Point"?

**Comment by harrison05** [comment]
Hi @kerstar , 
About 2 your questions:
Question 1: Yes, we added this code to improve security.
Question 2: Yes, it prevents users from double-click and duplicate payment when purchasing with Activity Point.

Regards.

**Comment by kerstar** [comment]
I understand. 
Regarding the first question, are these three files the only place where the security patch is implemented, or did I miss something?

**Comment by harrison05** [comment]
> I understand.
> Regarding the first question, are these three files the only place where the security patch is implemented, or did I miss something?

Oh, I'm not sure about that, because we updated many files each time release a new version. You can track our changelog and bug fix/improvement for detail.

Regards.
