### ISSUE TITLE
Using my Android mobile phone when spam enabled for feed it freezes you can't click on X

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2785]
# PLEASE IMPROVE TIME DELAY 

----------------------------------------

## What's happened?
... I set spam on feed in Admincp
I go to feed and enter "hello" 
This generates a popup error you already added this ... 

But the popup won't allow you to close it. 

Tried on mobile phone android using  chrome browser.. 
Will try on desktop later and report here. 
- Desktop works just mobile device not working 

## Steps to reproduce:
1. Set spam score and turn on for feed 
2. Type in hello send 
3. Type in again hello in feed and you will get popup error that you already wrote hello
4 try to.clixk the X to close the popup 
You cannot. 

## What's expected?
... Should be able to close the popup error window with android mobile phone using chrome browser. 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...mobile chrome for Android phone 

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.2

## phpFox version
(Example: phpFox 4.6.0)

...4.7.8 upgraded from.4.7.7

## Screenshots
...

**Comment by spirogg** [comment]
![Screenshot_20190926-132713~2](https://user-images.githubusercontent.com/17736688/65716113-1f6b7c00-e064-11e9-83bf-78ed40db828d.png)

**Comment by harrison05** [comment]
We tested on some Android devices, but can't reproduce this issue :-/ when touching on X icon, it might have small delay time, but it always close.

**Comment by spirogg** [comment]
@harrison05 
Ok I waited 5-10 secs and was able to close. Weird we have to wait for that long. Anyway to you guys can improve this,  not so long this delay to click X please. 

It takes too.long for delay 
Thanks

**Comment by harrison05** [comment]
Ok, we will check this case.

Regards.

**Comment by david-phpFox** [comment]
Optimized in Core 4.7.9.
