### ISSUE TITLE
when saving settings of blocks, it does not say at the bottom that it is saved. or updated successfully see screenshots

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2786]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
if you go to blocks and select the gear for anyone of the blocks, then click settings, then change something then click save it does not tell you if it was saved successfully 
## Steps to reproduce:
1. go to admincp, then go to Appearance > then blocks
2. choose any block and click under Settings the gear
3. then you have 3 choices> choose settings
4. change something in those settings and click SAVE CHANGES Bottom Red Button
5. You don't see any Banners at the footer that say your changes were saved.

## What's expected?
...
We Should see a banner at the footer that says are "changes were saved". just like all other areas..

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...
chrome firefox
## Server information
(Example: CentOS 7, php 7.1 apache)

... centos 7 php 7.2 7.3

## phpFox version
(Example: phpFox 4.6.0)

... 4.7.8 upgraded from 4.7.7

## Screenshots
...

- **This photo - area of the blocks does not show saved at the footer ??**
![Capture](https://user-images.githubusercontent.com/17736688/65720842-7413f480-e06e-11e9-9e36-f356f913de69.PNG)

- **But this photo below does show it, we should see the same footer in the above photo also after clicking Save Changes**
![Capture1](https://user-images.githubusercontent.com/17736688/65720970-b806f980-e06e-11e9-8219-0818863130bc.PNG)

**Comment by harrison05** [comment]
Ok, we will check and improve it.

Thanks

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.9.
