### ISSUE TITLE
Hastag date is incorrect, I add hashtag today and its shows trending since sept 20th ??

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2787]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... I see this #1007
 but still don't understand why if we add a hastag today....
 its trending 7 days back?
- because its only been trending since today... since we add it today ??

## Steps to reproduce:
1. add a hastag today and then click on it a few times, the hastag will show its been trending since 7 days ago, (Back 7 days in date) ?
2. 
3. 

## What's expected?
...
the feature trending 7 days should be if I have #hastag added today it will trend for 7 days starting today - so today its trending... tomorrow..., then 3, 4, 5, 6 ,7 days forward....
-  not backward 7 days ??

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome firefox

## Server information
(Example: CentOS 7, php 7.1 apache)

...CentOS 7 php7.2 & php7.3

## phpFox version
(Example: phpFox 4.6.0)

...4.7.8 upgrade from 4.7.7

## Screenshots
...

- HERE SHOWS THE DATE TRENDING 
- NOT SAME AS DATE I ADDED THE #HASTAG
![Capture](https://user-images.githubusercontent.com/17736688/65735904-b35a3980-e09e-11e9-8379-37084d00f3d3.PNG)

**Comment by harrison05** [comment]
Hi @spirogg ,

That trending text is show number days based on setting **Days a Tag Can Trend**, default is 7 days. It meant this block display hashtags which added from 7 days ago to now. It not a bug.

Regards.
