### ISSUE TITLE
Events time format is set to 12 hour format in admincp but creating event time stays at 24 hr format ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2788]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... Hi when adding a new event or editing an event, the time format is always 24 hr format, but the setting in admincp is set to 12 hr format... I know the actual time after set shows in 12 hr format, but when adding the time, its should also be in 12 hr format ?

## Steps to reproduce:
1. set time for events app in admincp to 12 hr format
2. go to event app and create an event or edit one already created
3. click on the time and you will see the settings are always in 24 hr format, which can create user being upset because in USA they only know 12 hr format, some users will get confused

## What's expected?
... Fix creation time for events to also be 12 hr format for adding to events for USA users PLEASE

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome firefox
## Server information
(Example: CentOS 7, php 7.1 apache)

...
CentOS 7 php 7.2 7.3
## phpFox version
(Example: phpFox 4.6.0)

...4.7.8 upgraded from 4.7.7

## Screenshots
...
- ![Capture](https://user-images.githubusercontent.com/17736688/65736479-b7875680-e0a0-11e9-9159-c5d26460143a.PNG)
- ![Capture1](https://user-images.githubusercontent.com/17736688/65736489-bbb37400-e0a0-11e9-95a3-a96b2539425e.PNG)
- ![Capture2](https://user-images.githubusercontent.com/17736688/65736496-c0782800-e0a0-11e9-8024-c62da22ee9da.PNG)
- ![Capture3](https://user-images.githubusercontent.com/17736688/65736500-c4a44580-e0a0-11e9-9f57-84acc8dd1209.PNG)

**Comment by harrison05** [comment]
Currently, we don't support the 12-hour format when create a new event. Just apply this setting when showing events.

Regards.

**Comment by spirogg** [comment]
@harrison05 then can you ask team about this for feature request. Or would you like me to add to feature request page ?

**Comment by spirogg** [comment]
@harrison05 I created a feature request for this here #892
