### ISSUE TITLE
Shoutbox text disappears after v.4.7.8 upgrade

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2789]
## What happened?
Shoutbox text disappears after v.4.7.8. Is this intentional?

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.8 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Hi @prepperz ,

Could you take a screenshot or something else? Because this app is working well on our Demo Site https://v4.phpfox.com/.

Regards.

**Comment by prepperz** [comment]
Basically any previous text written by users have disappeared from the the shoutbox after the v4.7.8 upgrade.

![Screenshot](https://user-images.githubusercontent.com/19594886/65894870-8052c700-e378-11e9-89dd-354c2ce2ac53.png)

**Comment by harrison05** [comment]
Please check the setting "Delete old messages" in Shoutbox App. It will automatically remove old messages based on this setting.

Regards.

**Comment by prepperz** [comment]
Ah. OK.
