### ISSUE TITLE
Video comment count still remains if user is deleted

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2790]
## What happened?
If the user makes a comment on a video and then the user is deleted, the comment count still remains.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.8 (Upgraded), Material theme

...

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.9.
