### ISSUE TITLE
"Load more" Stuck in a loop and does not work properly on profile page after v4.7.8 upgrade

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2791]
## What happened?
The load more function is not working properly on a user;s profile page.

## Steps to reproduce:
1.  Goto to a profile, scroll down until "Load more" is visible. Notice there is already feeds below it.
2.  Click on "Load more" and it will continually be stuck on the same feeds.

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.8 (Upgraded), Material theme

...

## Screenshots

![Screenshot](https://user-images.githubusercontent.com/19594886/65833331-482a8600-e29d-11e9-9c5c-80ceba5dc6ea.png)

**Comment by harrison05** [comment]
I can't reproduce this issue on my side. 
You can create a ticket and we will check it on your site to find a root cause.

Regards.

**Comment by prepperz** [comment]
Done. Ticket: #187442
