### ISSUE TITLE
Issue: Unable to delete video from CDN server

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2792]
## What's happened?

After the user removes the video, the video file is not deleted from the CDN server.

This is a big issue, because in this way you can quickly fill up disk space and you will not be able to control which file to delete manually.

Answering: Yes, I have a correctly set cron job - it works.

Is this an issue related to this bug? link: [https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2780](https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2780)

**Comment by harrison05** [comment]
Which version of the Video App you are using?

P/s: Please follow our template https://github.com/PHPfox-Official/phpfox-v4-issues/blob/master/ISSUE_TEMPLATE.md when posting an issue. It will help us quickly determine your issue.

Thanks.

**Comment by kerstar** [comment]
I apologize for not checking it out earlier.

I'm using phpfox version 4.7.3 and Videos app version 4.7.3

From what I learned, this bug was not fixed there.

**Comment by harrison05** [comment]
Oh, you should update to the Video version 4.7.5, we fixed the CDN issue on it.

Regards.

**Comment by kerstar** [comment]
Specially to check this I installed the latest version of phpfox (4.7.8) and the latest version of the Videos application (4.7.5) and here is this bug. 
I added CDN servers, then uploaded the video. 
When the video appeared on the page (as cron converted using ffmpeg), I deleted the video. 
There is still video file on the CDN server, it has not been removed. 
Video thumbnails also remained - they have not been removed either.

I also talked to Paul from your team. He claims that there is an error in the application.

Please fix this and release the update BEFORE the next phpfox 4.7.9 release...

**Comment by kerstar** [comment]
Update:
Strange, but I just added the video to the site again and deleted it again. 
This time the video file has been removed from the server. 
Video thumbnails have also been removed.

The only difference was that the video and thumbnails were added to another CDN server - in fact all CDN servers are on the same server only in different directories (e.g. cdn1.mydomain.com, cnd2.mydomain.com etc.), so it's not the server's fault.

There is a issue and sometimes it removes video and thumbnails, sometimes it doesn't.

**Comment by kerstar** [comment]
Hi @harrison05 
Have you checked this issue? What is your opinion on this subject? 
Paul from your team says there is a bug here, and you say you have fixed it in an earlier version. 
I checked it several times and movies from CDN servers are deleted randomly (once removed, other times the video files remain on the CDN server).

**Comment by kerstar** [comment]
hello?

**Comment by harrison05** [comment]
> Hi @harrison05
> Have you checked this issue? What is your opinion on this subject?
> Paul from your team says there is a bug here, and you say you have fixed it in an earlier version.
> I checked it several times and movies from CDN servers are deleted randomly (once removed, other times the video files remain on the CDN server).

I checked on my side with multiple CDN servers, but it's working well. Video source and thumbnail are removed after delete video (Video - 4.7.5, phpFox - 4.7.8, phpFox Storage - 4.6.3). Which phpFox Storage version you are using?

**Comment by kerstar** [comment]
Hi @harrison05 

PhpFox 4.7.8 (fresh installation), Video app 4.7.5, phpFox Storage app 4.6.3.

The issue is for sure. I don't know why, but movies are randomly removed from CDN servers.

Add some videos so that they are on other servers, then delete them and check if the files have been deleted.

Have you talked to Paul from your team? He confirmed this bug.

Please check it out because it is an important issue that cluttering disk space with unnecessary files unnecessarily.

**Comment by harrison05** [comment]
Hi @kerstar 

Okay, I will transfer this issue to development team and they will try to detect and fix if it occurs.

**Comment by kerstar** [comment]
Hi @harrison05 

Thank you. 
In that case, I am waiting for confirmation of this bug and update of the Videos app compatible with phpfox 4.7.8

**Comment by kerstar** [comment]
@harrison05 
Paul from your support team informed me that this bug will be fixed in the next version of phpfox. Thank you for NOT apply a hotfix to my site despite reporting this bug (not counting dozens of others). Now I have to wait for the next version of phpfox, it is not known how much time to test again, knowing life again there will be some serious error and I will have to wait again. I've been waiting since December 2017 and I still can't start building the community.

**Comment by harrison05** [comment]
Hi @kerstar 
Please check my newest comments at #2804 , we fixed this issue in **phpFox Storage** v4.6.4.

Regards.
