### ISSUE TITLE
Question about downloading application from the store

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2793]
## What's happened?

Is it possible to download the application from the store as a zip file without installing updates?

If you've fixed some issues in any of the previous updates of apps, then maybe you can tell me how I can download the update in the form of a zip package from your store?
I mean, I will analyze the file changes and fix this issue myself if it has been fixed in the update.

The only problem is that I have phpfox version 4.7.3, , so some applications cannot be installed directly from the store in my case.

(Yes, I know that I should always update phpfox, but I already have a heavily modified core and it will be very time consuming).

One way to get this update for this application would be to artificially overwrite the current compatible version of phpfox in the database, so as to download the update from the store, but I could cause problems with this.

That is why I asked about the possibility of downloading the application from the store in a zip package format, so that I can analyze the changes and replace the appropriate code fragments manually.

Is it possible?

**Comment by harrison05** [comment]
Hi @kerstar ,
We don't support download apps from Store as a zip file. We recommend you upgrade to the newest version for the stable. You can merge your custom codes into them after upgrade.

Regards.

**Comment by kerstar** [comment]
Ok, I understand. Thanks for the information.
