### ISSUE TITLE
Missing _120 video thumbnail on CDN server

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2794]
## What's happened?

Missing _120 video thumbnail on CDN server

## Steps to reproduce:
1.  Upload video to CDN server

## What's expected?
Missing _120 video thumbnail on CDN server

## phpFox version
4.7.8, videos app 4.7.5

## Screenshots
![video1](https://user-images.githubusercontent.com/38014237/66093044-e31dab80-e58e-11e9-8e71-49b8f740b75b.png)
![video2](https://user-images.githubusercontent.com/38014237/66093045-e31dab80-e58e-11e9-9b04-418df09ce5eb.png)

**Comment by kerstar** [comment]
Question (important!)

Will you update the Videos app before releasing phpfox 4.7.9?

**Comment by harrison05** [comment]
Hi @kerstar ,
Do you test upload images to that CDN server in other apps? Is it working well or not.

> Will you update the Videos app before releasing phpfox 4.7.9?
I can't confirm this, because the new release is decided by our manager.

Regards.

**Comment by kerstar** [comment]
Hi @harrison05 

> Do you test upload images to that CDN server in other apps? Is it working well or not.

I checked it by adding two photos to the site using the "Photos" app. 
All photo thumbnails added with the "Photos" application are correctly added to the CDN server.

![photos_thumbnails_cdn](https://user-images.githubusercontent.com/38014237/66174353-d95e7b80-e654-11e9-85ee-bf6f9e810828.png)

I added another video again, this time added to another CDN server. And the same problem - the _120.jpg file is missing.

![video3](https://user-images.githubusercontent.com/38014237/66174395-0448cf80-e655-11e9-9a92-1e8ff633e37a.png)
![video4](https://user-images.githubusercontent.com/38014237/66174396-0448cf80-e655-11e9-952b-1fcd6e70c352.png)

> I can't confirm this, because the new release is decided by our manager.

Please ask the manager to release the update before releasing the phpfox 4.7.9 version, because there are bugs in the Videos application that need to be fixed, and the last update of this application was three months ago.
Please ask the manager to issue the update before releasing the phpfox 4.7.9 version, because there are bugs in the Videos application that need to be fixed, and the last update of this application was three months ago.

Also take into account the bug that I described here https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2792 and check my update in that topic. There is definitely a bug. 
Paul from your team confirmed it.

**Comment by harrison05** [comment]
Hi @kerstar ,
Our team checked this case and confirm this is a bug of Video App. It missing image with suffix _120 after processed Video.
We will fix this bug.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Video 4.7.6.
