### ISSUE TITLE
Problems in Translation Page in Admincp

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2795]
What's happened?
I have many problems with translation page, is full of problems since the relase of the last phpfox version 4.7.8
I cant move prev, next .
I cant found phrases by "not translated"  (next, prev button are missing)
filters dont work anymore.

## Browsers and Devices tested
(Example: Firefox...)

## phpFox version
(Example: phpFox 4.7.8)

**Comment by harrison05** [comment]
Hi @Unite2Me ,

We will check and fix this issue.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.9.
