### ISSUE TITLE
Why is args var in main.js $Core.executeFunctionByName() function commented out

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2796]
Please have a look at main.js and search

$Core.executeFunctionByName = function (

Why is the parameter args commented out? It s missing at the called return function.

**Comment by harrison05** [comment]
Parameter "args" is commented out because it's useless. "args" in return function is using a variable defined above: **var args = [].slice.call(arguments).splice(2)**

Regards.

**Comment by Bjoern3003** [comment]
Oh sorry, I have this declaration not seen. My misstake.
