### ISSUE TITLE
AdminCP >manage pages> create a page, says invalid URL when try to re-create Privacy Page, because I accidentally deleted it?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2797]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
  First, by accident I deleted the Privacy page, then I try to recreate it but keeps saying invalid URL or already exits.. I tried to clear cache rebuild core nothing works
## Steps to reproduce:
1. go to privacy page and delete it
2. then go to admincp>appearance>pages
3. now you will see only one page, terms.. now click create page and input Privacy, try to save you will see you get invalid URL 

## What's expected?
...   we should be able to delete and recreate any page including Privacy and terms.

PLEASE HELP HOW TO FIX THIS

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)
ceontos 7 php7.3
...

## phpFox version
(Example: phpFox 4.6.0)

...fresh install 4.7.8

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/66136259-ca2dee00-e5c0-11e9-9b33-2b6fc9ca4122.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/66136269-cc904800-e5c0-11e9-9642-38487cf20693.PNG)
![Capture2](https://user-images.githubusercontent.com/17736688/66136277-cf8b3880-e5c0-11e9-9231-919ba98e3c87.PNG)

**Comment by harrison05** [comment]
Hi @spirogg ,

My team informed that our validation when create page doesn't allow add title URL same with a module name and we have module **Privacy** (PF.Base/module/privacy), so you can't add a page with URL **privacy** even though you deleted old Privacy page.

We will check this case, and find a solution to improve. With v4.7.8, please add a page with another URL and enable it in footer menu.

Regards.

**Comment by spirogg** [comment]
@harrison05
Maybe you can add all those modules under Admincp> find missing settings 
And if we delete the pages by accident. When we click on "Find missing settings" it reinstalls the pages that have modules

**Comment by harrison05** [comment]
> Hi @spirogg ,
> 
> My team informed that our validation when create page doesn't allow add title URL same with a module name and we have module **Privacy** (PF.Base/module/privacy), so you can't add a page with URL **privacy** even though you deleted old Privacy page.
> 
> We will check this case, and find a solution to improve. With v4.7.8, please add a page with another URL and enable it in footer menu.
> 
> Regards.

Our team decided that we don't support add a new Page with URL same with a module name. Please select a valid name for it.

Regards
