### ISSUE TITLE
View more is hardly noticeable when posting links with multiple lines

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2798]
## What happened?
When posting on the pages status, the "view more" option is hardly noticeable when posting links on multiple lines. May be put the view more on a separate line or make it bold to draw attention to it.  Other wise people won't even notice it at all.

## Steps to reproduce:
1. 
2. 
3. 

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.8 (Upgraded), Material theme

...

## Screenshots

![Screenshot](https://user-images.githubusercontent.com/19594886/66258174-d99f6980-e76f-11e9-88b2-539ffe2e0c4e.png)

**Comment by harrison05** [comment]
It works as our design and we haven't planned to change it yet.

Regards.

**Comment by prepperz** [comment]
Maybe separate it a bit more because if people really don't pay too much attention (and people are lazy in general) they'll think it's part of the link and they end up clicking the link instead of more content.   ... or they just simply think there's no more content.
