### ISSUE TITLE
function findMissingPhrases is not working in phpFox 4.7.8

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2799]
## What's happened?
Function findMissingPhrases is not working.

I have uploaded a second language that has translated variables that does not have the primary language 'en'.
Then I added elements with variables on the page that correctly display the uploaded second language, while the language 'en' (primary) does not display, because it is not in its dictionary.
I am trying to import variables by clicking "Find Missing Phrases" on the language 'en', a notification is displayed that the operation is successful, but the missing phrases have not been added to the primary language 'en'.

I checked the files in the \PF.Src\Core\Phrase.php and PF.Base\module\language\include\component\controller\admincp\missing.class.php files and did not notice any significant changes that could affect this bug.
I replaced the PF.Base\module\language\include\component\controller\admincp\phrase\phrase.class.php and file with the one from the previous version and it didn't help either (except for improving the pagination in the "Languages" section, because there is an error that has already been reported here)

@harrison05 , I know you will check it out, but you can give instructions on which file to fix? 
This is an annoying bug and it's difficult to translate phrases through phpMyAdmin...

## phpFox version

Fresh installation 4.7.8

**Comment by harrison05** [comment]
> I have uploaded a second language that has translated variables that does not have the primary language 'en'.

How did you add the second language? Install from phpFox Store or select New Language in AdminCP.  **Find missing phrases** feature will get all phrases in "phrase.json" of all apps. Please make sure you don't have a JSON syntax error in them and your missing phrases are added.

Regards.

**Comment by kerstar** [comment]
Ok, this seems like my mistake. 
I imported a second language manually from a file, this language already contained translated phrases that did not have the primary language "en".
The places where the phrases were not translated did not have the file "phrase.json", only variable phrases in the code were entered. 
Maybe that's why this was the issue.

**Comment by harrison05** [comment]
Ok, let check it again and inform me if you meet any issues.

Thanks.
