### ISSUE TITLE
Android App Sharing Bug

### ISSUE THREAD

**Issue by Shamelesshit** [PHPfox-Official/phpfox-v4-issues#2800]
# Important

Please follow this template!

----------------------------------------

## What's happened?
The phpfox mobile app version 1.5.1 for android has a sharing bug when using the native share function to share content to site, sometimes it works and sometimes it just opens the app, this seems to happen if the app is already open or running in the background.

## Steps to reproduce:
1. Find a photo in your phones browser, hold down on the photo to open options menu, select share image once the share menu appears select phpfox app.
2. If your desired photo appears in the share menu click share, once it is posted you will be redirected back to the image you shared on the web page.
3. Now repeat steps 1 and 2 this time the app will only load and the image you wanted to share will not appear into the share menu to be shared to your feed.

## What's expected?
the app should always share the selected content the user is trying to share to their feed I would expect.

## Browsers and Devices tested
Chrome version 77.0.3865.92 for android 
Phpfox mobile app version 1.5.1 for android 
Running on Samsung Galaxy Note 10+ Android version 9

## Server information
Tested on your test server: https://mobileapi.phpfox.com

## phpFox version
I would assume the test server is running 4.7.8?

## Screenshots
Video of issue: https://shamelesshit.com/mobile-app-share-issue.mp4

**Comment by harrison05** [comment]
Hi @Shamelesshit,

We will fix this bug in the next version.

Thanks.

**Comment by david-phpFox** [comment]
Fixed in Mobile 1.6.x
