### ISSUE TITLE
scroll with mouse does not work in Country and states/province, also state scroll bar on the right side is too small

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2802]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... when registering as a user and you have Country and state for users to register they can't use their mouse wheel to scroll the countries and states in Chrome.

## Steps to reproduce:
1. activate country and state in admincp> registration
2. then go to signup page and click on country> now try to use your mouse wheel to scroll the countries and also try for states..
3. you can't,
4. also the right menu bar for states is really small and you can hardly use it to scroll since the mouse wheel scrolling doesn't work

## What's expected?
...
should be able to use the mouse wheel to scroll and also should have more space in the states/province to the right side of the scroll bar, so users can scroll with that if needed.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...latest chrome browser

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php 7.2

## phpFox version
(Example: phpFox 4.6.0)

...4.7.8

## Screenshots
...
![Capture1](https://user-images.githubusercontent.com/17736688/66444524-2651a180-ea09-11e9-8866-bea8e99b871f.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/66444525-2651a180-ea09-11e9-87d9-97e215cf4cac.PNG)

**Comment by harrison05** [comment]
Hi @spirogg ,

We will check and fix if this is a bug.

Thanks

**Comment by david-phpFox** [comment]
Fixed in Material Theme 4.7.9.
