### ISSUE TITLE
A big, important request to phpFox team

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2805]
I have been waiting for a stable version of phpfox for 20 months, which will have no bugs before I start building a community.
I have been constantly testing subsequent versions of phpfox for 20 months, I keep reporting bugs and comments (other users do this too).
And you still spend, you release phpfox, which has serious bugs preventing you from building a website with the community.
You keep repeating EXACTLY the same issues that I reported to you earlier and that were previously fixed. Where did these errors come from once they were repaired?
Link 1: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2803
Link 2: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2804

Why don't you test phpfox before you release another version?
Why don't you focus on the release of the STABLE version? Why don't you focus on correcting the bugs that users report to you, instead of releasing new untested features? I guess you should first focus on phpfox to have no bugs, and then introduce improvements in the form of new features.
Why do I still have to wait and wait? How can I be sure that the next version you will release will be good if you repeat bugs that were previously reported and fixed?
I really want phpfox to be a good script, but I'm tired of waiting and waiting...
You should take these words to heart.

Can you check everything works properly before releasing the next version of phpfox and not treat us as beta testers?

**Comment by david-phpFox** [comment]
Hi kerstar,

We have received your ticket, please follow this ticket and provide us info your site installed with the newest version of Core, we will check this issue if it is an issue of Core, we will fix it in next version.

Thanks,
David

**Comment by kerstar** [comment]
@david-phpFox 

Thanks for contacting David.

I gave you the details of my website with phpFox 4.7.8 in this ticket: #724530 -  (I added a new message there, where I entered login details).

Don't fix this bug on my site, just fix this issue in the next version of phpFox (I hope that I will not wait for phpFox to be released for two months). 
I have reported many bugs in the CDN malfunctioning. 
Paul informed me that you would also fix a bug that causes videos to not be removed from CDN servers: link to thread: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2792 and ticket: #575188 (Paul confirmed this bug on this ticket, not on github).

Please make sure everything works before releasing the next version of phpFox. 
Make sure users can correctly add photos, videos, attachments to CDN servers and that they will be correctly removed from CDN servers (now there are bugs with videos and attachments
Link to thread with incorrect removing of videos: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2792
Link to thread with incorrect attachment deletion: https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2804

**Comment by harrison05** [comment]
Hi @kerstar
Please check my newest comments at #2804 , we fixed this issue in phpFox Storage v4.6.4.

Regards.
