### ISSUE TITLE
When in mobile view can we reposition the cover photo ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2808]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
Just noticed that when we're using our android mobile device, we can't reposition our cover photo ? 
## Steps to reproduce:
1. Go to user profile, click icon to upload remove - choose photos - but in mobile view on my Android device. I can't see an option to reposition the cover photo ??
2. 
3. 

## What's expected?
...
I think we should be able to reposition our cover photos like in desktop. 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...android chrome browser 

## Server information
(Example: CentOS 7, php 7.1 apache)

...CentOS 7 php 7.3.10

## phpFox version
(Example: phpFox 4.6.0)

...fresh install 4.7.8

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

Currently, we don't support **Reposition** cover on the mobile view.

Regards.
