### ISSUE TITLE
Quick question about Facebook login - signup ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2809]
# Important

Please follow this template!

----------------------------------------

## What's happened?

When we activate Facebook login - signup and we have set registration to verify email and admin needs to approve users signing up 
- do these rules apply with Facebook  - signup or do they get access right away ? 
...

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)
CentOS 7 php 7.3.10
...

## phpFox version
(Example: phpFox 4.6.0)

...fresh install 4.7.8

## Screenshots
...

**Comment by harrison05** [comment]
> When we activate Facebook login - signup and we have set registration to verify email and admin needs to approve users signing up 
> do these rules apply with Facebook - signup or do they get access right away ?

After users log in by Facebook, they don't need to verify email, Facebook did that. 
Currently, **Approve users** doesn't work if using FB Login, it might a bug. We will check this issue.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Was this fixed yet?

**Comment by harrison05** [comment]
Fixed frome Facebook App v4.6.3
