### ISSUE TITLE
Page reloads, if we click a navi link from form page

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2812]
# Important

Please follow this template!

----------------------------------------

## What's happened?
The Page is trying to reload the Page by Ajax Function, but is going in error function and reload the Page be href, (PF.Base/static/jscript/main.js#L2316) if we are on a page with an Form.

## Steps to reproduce:
1. Go to Blogs an click on the green Add new Button.
2. In this page, click on a link in phpfox. For example Startpage or what ever
3. The Page tried to load the website by Ajax.

## What's expected?
Load Page by Ajax, because full Ajax is enabled.

## phpFox version
Latest 4.7.8

**Comment by harrison05** [comment]
Hi @Bjoern3003 

It might a bug when loading ajax page, we will check this issue. 

Regards.

**Comment by Bjoern3003** [comment]
Hi @harrison05 did you found the bug? Is it fixed in the next release?

**Comment by harrison05** [comment]
Hi @Bjoern3003 

We fixed this issue and it will be released with v4.7.9.

**Comment by david-phpFox** [comment]
Fixed in Core 4.7.9.

**Comment by Bjoern3003** [comment]
I think, in some cases, its almost there. Can you describe your bugfix?

**Comment by Bjoern3003** [comment]
Okay, I saw, taht you have tried to fix this issue by reloading js function for link clicking by using settimeout. This is not the best way to coding. In my case its very bad!

Now you have opend a new bug, for all apps, who are using own JS Code, to look up on href cleck events. Because now your code is primary and all JS from third party Apps a unbind to the click event, after you are calling the initClickAllLinks() again.

I can reproduce it, by commenting out you code in main.js L#4677 and L#4669

I think your main.js does need a refactor from professional as well. The Performance is also very bad. (settimeout with 500ms - really?). You only bugfix bad coding with new bad coding, so that cou close bugs by open new bugs...

**Comment by harrison05** [comment]
If you want to open a link without Ajax loading, you can add class "no_ajax" to that link.

**Comment by Bjoern3003** [comment]
I did not want to Open a link without ajax loading.
