### ISSUE TITLE
ToolTip Bug

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2814]
## What's happened?
When i click in username I see the tooltip with user info but the profile image is in the wrong size (like cut in the middle)

## Steps to reproduce:
1. Click in username of one user and u will see the profile pic in small size not in the full circle

## Browsers and Devices tested
All browser

## phpFox version
phpFox 4.7.8
...

## Screenshots
https://ibb.co/DC8p8dM

**Comment by kerstar** [comment]
Affirmative. The issue is also on my page.

**Comment by kerstar** [comment]
Hi @Unite2Me 

Resolution for this issue:

Edit file:
\PF.Site\flavors\material\html\user.block.tooltip.html.php

In line7:

Change this code:

`{img user=$aUser suffix='_50_square' max_width=50 max_height=50}`

to this code:

` {img user=$aUser suffix='_120_square' max_width=120 max_height=120}`

**Comment by spirogg** [comment]
@Unite2Me @kerstar 
you are using bootstrap theme correct?
- cause I don't see this issue on Material theme?

![Capture1](https://user-images.githubusercontent.com/17736688/67164020-b661e600-f33b-11e9-8a45-b1fef82c73c4.PNG)

**Comment by harrison05** [comment]
Hi @Unite2Me 
Did you try to rebuild core theme and clear cache? It's working well on my site.

@kerstar You don't need to replace **_50_square** to **_120_square**, our image library will do that.

Regards.

**Comment by kerstar** [comment]
Hello @harrison05 

On my page (fresh install phpFox 4.7.8, and phpFox 4.7.3) I noticed this issue and replacing _50_square  to _120_square helped to solve this problem.
