### ISSUE TITLE
Menu' icon "home" missing

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2815]
## What's happened?
When i visit homepage the home icon is missing in index.visitors

## Steps to reproduce:
Check the homepage logged off.

## What's expected?
U cant see the icon for homepage when u scroll down in the center menu'

## Browsers and Devices tested
All browsers

...

## phpFox version
(Example: phpFox 4.7.8)

...

## Screenshots

https://ibb.co/9ZYZqGq

**Comment by kerstar** [comment]
On my site (phpFox 4.7.8) I did not notice this issue.

**Comment by spirogg** [comment]
@Unite2Me @harrison05 
I also notice this, 

steps to reproduce.
1. first log in to site
2. then click on a user profile
3. now scroll down to bottom, you don't see the home menu on top 

Material theme
4.7.8 fresh install

![Capture1](https://user-images.githubusercontent.com/17736688/67163727-0e96e900-f338-11e9-80d3-cd471fb7c89b.PNG)

**Comment by kerstar** [comment]
Hi @spirogg 

You misunderstood the issue. As you scroll the page on the user's profile, there is actually no icon, but this is not a issue.
@Unite2Me meant no icon on the home page (not on the user's profile page).

**Comment by harrison05** [comment]
@spirogg  The profile page doesn't include in Main Menu, so it doesn't show an icon on menu when scrolling down.

@Unite2Me issue doesn't happen on my site, which version of phpFox and Material template you're using?

![Screen Shot 2019-10-21 at 11 04 54](https://user-images.githubusercontent.com/41947198/67176128-fc2db580-f3f2-11e9-8139-04e0a3f2cfc6.png)

Regards.
