### ISSUE TITLE
Issues with marketplace on latest release.

### ISSUE THREAD

**Issue by zoeaa2019** [PHPfox-Official/phpfox-v4-issues#2816]
# Important 

Please follow this template!

----------------------------------------

## What's happened?

Not able to create a listing because it needs a location. However, it doesn't accept any location.

After you manually disable the php code that checks the location field and you manage to create a listing a whole bunch of settings are missing like allowing people to buy the item using points or buying it at all.  

I thought it was a browser, cache or maybe even site-specific issue. So I created a fresh install and still had the same issue.

phpFox 4.7.8 & all the latest apps.

![2019-10-18_1842missingbuybutton](https://user-images.githubusercontent.com/56743785/67132601-433f5f00-f1d7-11e9-9c04-2a25375decb0.png)
![2019-10-18_1842missingoptions](https://user-images.githubusercontent.com/56743785/67132603-46d2e600-f1d7-11e9-933e-e8c9833d9737.png)
![2019-10-18_1845locationissues](https://user-images.githubusercontent.com/56743785/67132683-87326400-f1d7-11e9-8d6e-69550aac21f5.png)

**Comment by spirogg** [comment]
@zoeaa2019 I confirm this issue.
@harrison05 
- Does the Market app now need to use Google API Key in order to function? 
- I don't remember needing to have google API location,  to add a listing prior?

**Comment by harrison05** [comment]
> Does the Market app now need to use Google API Key in order to function?

Yes, you need Google API to support the autosuggest location.

Regards.
