### ISSUE TITLE
when we mouseover  page name we don't get tooltip image like in groups

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2817]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... when creating a page and then mouseover the page name it doesnt show the page (tooltip) like users and groups.

## Steps to reproduce:
1.  create a page - then upload a photo
2. now go to page feed
3. place your mouse curser over the page name - there is no tooltip 

## What's expected?
...
should be able to mouseover and get the tooltip like in groups
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
latest chrome version as of today 10/21/2019
...

## Server information
(Example: CentOS 7, php 7.1 apache)

... CentOS 7  php 7.3.10

## phpFox version
(Example: phpFox 4.6.0)

... fresh install 4.7.8

## Screenshots
...
- here is group tooltip that works
![Capture2](https://user-images.githubusercontent.com/17736688/67256017-95d48180-f44a-11e9-97a9-2313c540a793.PNG)

- THIS IS PAGE tooltip not working
![Capture1](https://user-images.githubusercontent.com/17736688/67256030-a258da00-f44a-11e9-91a8-b9985d278c7c.PNG)

**Comment by spirogg** [comment]
Also

if you have a username that was created by a user, and you create a page with the same name it should not be allowed to have the same name as the Group or Page
- we should not allow same name as users name to be added as a page or group 


![Capture2](https://user-images.githubusercontent.com/17736688/67256578-7ab74100-f44d-11e9-80b2-6a158fa115bd.PNG)

**Comment by spirogg** [comment]
- I did more testing and the issue is: Vanity URL
if we don't add a Vanity URL then the Tooltip Does not work
- 
![Capture1](https://user-images.githubusercontent.com/17736688/67256901-0b425100-f44f-11e9-885d-9f4b33441c91.PNG)

- the mouseover does not work until you create the Vanity URL for that page.

- after adding Vanity URL then mouseover  ( tooltip ) works
![Capture2](https://user-images.githubusercontent.com/17736688/67257130-18ac0b00-f450-11e9-8a45-c83154dd2fa1.PNG)


- Same for Groups 
if you don't create the Vanity URL for that group then the tooltip does not work for groups also ?

**Comment by harrison05** [comment]
Hi @spirogg 

Oh, we know this issue, but tooltip only can detect pages have vanity URL.

**Comment by david-phpFox** [comment]
Supported in Core 4.7.9.
