### ISSUE TITLE
when in my user profile and I select choose from photo to add cover photo doesn't work

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2818]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
i am trying to add a cover photo from the cover photo dropdown
I select choose from photo and it takes me to photos, then i click on a photo and it takes me to photo viewer ?

## Steps to reproduce:
1. go to your user profile page
2. select to camera to upload a cover photo
3. select - Choose from Photo
takes you to your photos and now try to click on a photo 
it just takes you to the photos page ?? 
am i missing something here ?

## What's expected?
...
you should be able to click on a photo and it should be added as your cover photo ??
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

... chrome browser latest version as of today 10/21/2019

## Server information
(Example: CentOS 7, php 7.1 apache)

... CentOS 7 php7.3.10

## phpFox version
(Example: phpFox 4.6.0)

...4.7.8 fresh install

## Screenshots
...
![Capture1](https://user-images.githubusercontent.com/17736688/67259898-00db8380-f45e-11e9-9377-b07c12377d06.PNG)

![Capture1](https://user-images.githubusercontent.com/17736688/67259928-25cff680-f45e-11e9-80eb-ca63c1a49261.PNG)

![Capture1](https://user-images.githubusercontent.com/17736688/67259942-48620f80-f45e-11e9-8035-8c1fa7a93519.PNG)

nothing here
![Capture1](https://user-images.githubusercontent.com/17736688/67259974-6cbdec00-f45e-11e9-849e-f1bb3c35841d.PNG)

**Comment by spirogg** [comment]
@harrison05 

Same for Pages and Groups - 

when you select > choose from photo:
 are you suppose to just click a photo and it should upload as cover photo?

- or does it just take you to photos, then you need to click on photo then select the 3 dots ... and then select make cover photo ? 

- if so this is ridiculous to many steps and the choose from photos should be removed. ?

please explain to me how this feature works, cause its not working on my site nor on v4.phpfox.com 

thanks

Spiro

**Comment by kerstar** [comment]
I confirm I have the same problem.

After clicking "Choose from Photos", it redirects me to my photos, where there is no option to choose a cover photo.

@harrison05 Can you release a patch for the Photos app that fixes this problem? (for phpFox 4.7.8)
(or can you provide repair instructions?)

**Comment by harrison05** [comment]
Hi @spirogg @kerstar 

> or does it just take you to photos, then you need to click on photo then select the 3 dots ... and then select make cover photo ?

Yes, this is the workflow of that feature. It not a bug.

**Comment by kerstar** [comment]
Hi @harrison05 

I understand. Will the next version of the Photos app be compatible with the current version of phpFox 4.7.8?

**Comment by spirogg** [comment]
@harrison05 maybe a feature request to make this easier for users. It's too complicated if new user signs up and there is no directions. Workflows would be easier if click choose from photos then photos appear then we can click on the little gear and set as cover photo. Much easier 
Thanks 

Spiro.

**Comment by harrison05** [comment]
@kerstar We haven't released a new version of Photo app, current version 4.7.7 is compatible with phpFox v4.7.8

@spirogg Okay, our team will review your request, improve user experience.

Regards.

**Comment by david-phpFox** [comment]
Hello @spirogg  @kerstar,

We will improve it in the next version of of the Photos app be compatible with the current version of phpFox 4.7.8

Regards.

**Comment by kerstar** [comment]
Hi @david-phpFox 
Great! (please check in advance for any issues before release the next version of the Photos app).

**Comment by harrison05** [comment]
Available in Photos v4.7.8
