### ISSUE TITLE
in feed when select hide all if its sponsored or featured we can hide only till we refresh then comes back again

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2819]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... in feed when we select hide all from (username) 
if its a sponsored feed,  we can only hide it until we refresh then it comes back again., is there a way to keep it hidden and not see it again when we refresh ?

## Steps to reproduce:
1. go to v4.phpfox.com
2. see main feed there is a sponsored blog in feed, select hide all from that user
3. it disappears, now refresh page or click on home button.. it reappears again.. we need to be able to hide users, not matter if it's sponsored item or not. 
- can you please add sponsored or featured items to be able to hide them from any user as well.

thank you

Spiro

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...
chrome latest version as of 10/22/19

## Server information
(Example: CentOS 7, php 7.1 apache)

... CenOS 7 php 7.3.10

## phpFox version
(Example: phpFox 4.6.0)

... 4.7.8 fresh install

## Screenshots
...

**Comment by spirogg** [comment]
- this sponsored blog from this user doesn't get hidden even though this user is hidden 

![Capture1](https://user-images.githubusercontent.com/17736688/67262673-45215080-f46b-11e9-97cd-134c05293741.PNG)
![Capture2](https://user-images.githubusercontent.com/17736688/67262674-45b9e700-f46b-11e9-9a81-9ed57ba0eb41.PNG)

**Comment by spirogg** [comment]
- even if I block this user / the sponsored blog of this user in Feed is still visible to me.

![Capture1](https://user-images.githubusercontent.com/17736688/67263479-e14c5700-f46d-11e9-933f-1e4dceeef8df.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

> this sponsored blog from this user doesn't get hidden even though this user is hidden

This is a bug from Ads App, we fixed it but haven't released it. If you need a hotfix in your site, please contact us in Client Area.

> even if I block this user / the sponsored blog of this user in Feed is still visible to me.

Currently, we don't check blocked users when getting sponsored feeds. 
But we will check and improve it.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Better Ads 4.2.7.
