### ISSUE TITLE
event shows profile country in home feed and user profile feed

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2820]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
@harrison05 i created this as a new issue to not take up @prepperz issue

-  issue :
1. I have set timestamp in Admincp as America/Chicago 
2. I have set users profile I live in San Juan, Puerto Rico
3. I added timezone to America / Chicago in users setting 
4. I created an event 
When go to home page in feed and users profile feed, it shows event but shows where user lives next to event place see below this is a bug.
 - should not show in feed event where user lives
- It should just show the event place. ( San Francisco, CA) not Puerto Rico
See below. This is the event that shows in feed 
- MONDAY, OCTOBER 21, 2019 4:37 PM
Test
San Francisco, CA , Puerto Rico
1 guest

- please note the extra comma also
This should be removed in feed 
, Puerto Rico

## What's expected?
... should not add user profile country in events

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome latest version as of today 10/22/19

## Server information
(Example: CentOS 7, php 7.1 apache)

...
CentOS 7 php 7.3.10
## phpFox version
(Example: phpFox 4.6.0)

...4.7.8 fresh install events app version 4.7.2

## Screenshots
...
snapshots below:
- this is home page Feed
 ![Capture2](https://user-images.githubusercontent.com/17736688/67255495-f6ae8a80-f447-11e9-9893-ac89093a2a30.PNG)
- this is user profile Feed
![Capture2](https://user-images.githubusercontent.com/17736688/67255543-2b224680-f448-11e9-941e-8628ca682276.PNG)

> Hi @harrison05 
> Which Event version you're using? This location only shows event location, doesn't related to user profile location.
4.7.2 see photo below

![Capture1](https://user-images.githubusercontent.com/17736688/67257369-404fa300-f451-11e9-93a2-1f7e4a9836cc.PNG)

**Comment by spirogg** [comment]
i created another event on your site, with my country as greece, and i put a BS location and it did the same thing

![Capture1](https://user-images.githubusercontent.com/17736688/67258605-15684d80-f457-11e9-970d-a84ba0f0ba7a.PNG)


- 

- so if we don't have google api and we add an event or even with google api but we put a wrong location and we use a country  in our profile it will also show profile country of user. 
![Capture1](https://user-images.githubusercontent.com/17736688/67258751-c40c8e00-f457-11e9-8de2-e386cc1aa1bc.PNG)

![Capture1](https://user-images.githubusercontent.com/17736688/67258887-67f63980-f458-11e9-904b-a8af4ba688e4.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/67258913-8825f880-f458-11e9-8654-ad5ae8d2df0e.PNG)


- for some reason its pulling the country of user profile if you don't have google api activated and if user doesn't select a location from google api and just writes there own location then the country shows in feed event 

i test on phpfox demo site also.

PS doesn't matter what country you have in user profile it will still show at the end of the event location

- yes if no google api is on or user creates event and doesn't select a location from google api list, then the user profile - country will show in the event in home feed and user profile feed 

another test below
![Capture1](https://user-images.githubusercontent.com/17736688/67259199-31b9b980-f45a-11e9-9421-fb2f22097d10.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

I got your issue. When create a new event, if you don't set "Google API Key" or don't select a location from Auto-suggest dropdown of Google Map, event location will get the current country from your profile setting. 
Btw, I think this is a bug, our team will check again.
<img width="1050" alt="Screen Shot 2019-10-23 at 11 00 42" src="https://user-images.githubusercontent.com/41947198/67356737-58c0da00-f585-11e9-839f-1b320505a53e.png">

Regards.

**Comment by david-phpFox** [comment]
Fixed in Event 4.7.3.
