### ISSUE TITLE
Question: How to disable view on map

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2821]
There is a "view on map" on the upper left corner on the event app. How do I disable or hide that?

![download](https://user-images.githubusercontent.com/19594886/67618014-3adabb80-f7b7-11e9-88d6-0ce3d31275c6.png)

**Comment by spirogg** [comment]
hi @prepperz 

its a block in events 

![Capture](https://user-images.githubusercontent.com/17736688/67625958-a601ad80-f80a-11e9-859f-f293c9fdcfb6.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/67625989-fa0c9200-f80a-11e9-830d-2dc143c0e1c4.PNG)

**Comment by prepperz** [comment]
@spirogg Thanks buddy
