### ISSUE TITLE
Can't create new page inside admincp

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2823]
## What's happened?
When I try to create a new page inside admincp and save it I get an error message that says: "Page title is invalid." although the title is OK.

## What's expected?
I should be able to save the page because the title is written OK.

## Browsers and Devices tested
Latest version of Firefox

## phpFox version
Latest version

**Comment by spirogg** [comment]
- what version of phpfox are you using? 
- is it fresh install or upgrade from prior version?
- are you using material theme or did you use a third party theme ?
- Did you modify code?

- also do you have any third party apps installed? > if so try to turn off your third party apps one by one and try to create a page.
- also what system do you have > Ubuntu 14 16 18 ?  CentOS 7 php version
- what characters are you using plain English ? or any special character in title or url title ?

here is mine and it works no issue 
phpfox 4.7.8 fresh install
 CentOS 7.7 php 7.3 MariaDB 10.3

![Capture](https://user-images.githubusercontent.com/17736688/68269813-c73f7680-0020-11ea-9db8-3d2d1001bdb4.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/68269814-c73f7680-0020-11ea-84fb-986231d462b2.PNG)
![Capture2](https://user-images.githubusercontent.com/17736688/68269815-c73f7680-0020-11ea-8e98-bfc60e009d45.PNG)

**Comment by spirogg** [comment]
only issue i see in mine is this #2824 but still i can create a page

**Comment by turha71** [comment]
Really strange... it's working fine today. Yesterday I was not able to create the page. Something in the cache browser probably.

Sorry for your time

**Comment by spirogg** [comment]
@turha71 never hurts to report cause I found error also based of your reporting for same area :) have a great day or night depending where you live 👍

**Comment by harrison05** [comment]
Hi @turha71 

This issue was resolved I will close it now. Let us know if you meet any issues.

Regards.
