### ISSUE TITLE
PLEASE: Change these phrases not to confuse admins please

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2824]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
 i created a page and entered a tile , then title url  i entered a different one from the title.
example:

title = Mary
title url = where is mary

then I get a warning that where-is-mary already exists?

- which is not correct : DOES NOT EXIST
## Steps to reproduce:
1. go to admincp>appearance>pages
2. create a new page > enter title Mary
3. now click to change url title > and enter: where is mary 
you will see that anything you type in the title url field with spaces will create this warning that it exists even though it does not exist

- if you click save it will still create the page and work as normal.

**my Issue** - False Warning Only. if you write with spaces where is mary or what dog do you love

- **UPDATE:** The url MARY is already existed. We recommend you change this url as following.

- **Also** if we type in all CAPS it throws this warning again

if you initially type:  where-is-mary      >> no warning 
or what-dog-do-you-have
then there is no warning at all only with Spaces and CAPS

## What's expected?
...
- **should not give False warning of existence**

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome firefox latest version

## Server information
(Example: CentOS 7, php 7.1 apache)

...
 CentOS 7.7 phpfox 7.3 Apache MariaDB 10.3

## phpFox version
(Example: phpFox 4.6.0)

...fresh install 4.7.8

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/68270495-0969b780-0023-11ea-85bb-158b64ea0860.PNG)

![Capture](https://user-images.githubusercontent.com/17736688/68270687-c4925080-0023-11ea-9bab-33c83ef57e32.PNG)

**Comment by spirogg** [comment]
**UPDATE:  @harrison05 @phpfox please read below...**

OK, now I see what your trying to say with this warning, except the wording should be different..

- OLD PHRASE: `The url MARY is already existed. We recommend you change this url as following.`

- NEW PHRASE: `The Url Title <b>{original_url}</b> is not supported, we do not allow Caps or Spaces. Instead, please use our recommended url listed above.`


- Also please change default phrase: 
`The Url title is exist. `
change too:  
`the Url title exists.`

Please change in the default phpfox phrases - Language.
- this makes more sense and does not confuse users like me 👍 

![Capture](https://user-images.githubusercontent.com/17736688/68273399-e4c60d80-002b-11ea-8731-fa6fe031220a.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

I understand your request. We will check and improve this warning message.

Regards.

**Comment by david-phpFox** [comment]
Updated in Core 4.7.9.
