### ISSUE TITLE
Music App setting >registered users> can delete all songs ON for default please change

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2825]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
In Music app, I found this setting enabled for registered users and banned users by default, **can delete all songs. ON**

- can you PLEASE **set default to NO** in the music app for registered users and banned users also, someone will not notice and think the default is NO and then build there site and another user will delete all the sites songs :(

## Steps to reproduce:
1. install 4.7.8  phpfox default settings of music app for registered users and banned users: **can delete all songs**
2. this setting needs to be set to NO as default
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...
4.7.8 phpfox 
4.6.5 music app

## Screenshots
...

@harrison05 
- The setting should be set to NO below in this screenshot by default for registered users and Banned users Thanks

![music app default is set to delete all music](https://user-images.githubusercontent.com/17736688/68281286-f5cb4a80-003c-11ea-8042-ef1ddedb49e7.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

We will improve this case.

Regards.

**Comment by david-phpFox** [comment]
Improved in Music 4.6.6.
