### ISSUE TITLE
Timestamp on messages

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2826]
## What's happened?
Although I change the timestamp to work with 24h format, in messages the time format is always 12h. Just can't change it to 24h. Don't know if this is a bug or if I'm missing a setting.

## phpFox version
4.7.8 fresh install

## Messages version
4.7.5

**Comment by spirogg** [comment]
try in admincp and serach for "


Global Timestamp
F j, Y
Each module has items that are displayed and use our timestamp settings to display the date the way we would like. 

If a module does not specify a timestamp setting it will use the default timestamp layout which is controlled with this setting. 

For a better understanding on how to modify this setting and what the string values stand for you can follow up on the PHP date() function here.


this is for events timestamp so you can try these seetings in global timestamp and see if this helps you :)

`l, F j, Y g:i a` for 12hr format

and

`l, m-j-Y, G:i` for 24hr format.

**Comment by spirogg** [comment]
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2813

**Comment by turha71** [comment]
I have just added the G:i to the global setting, cleared cache, but the time on my messages is still 12h. Did you check on your dev site?

The time I'm refering to is the one that show in a tolltip when we mouse over the messages.

Thanks

**Comment by spirogg** [comment]
@turha71 i just tried G:i no luck 12 hr format still ? yes i got the same should be a bug lets wait for someone  or @harrison05 to help us :)

**Comment by harrison05** [comment]
Hi @turha71 @spirogg 

If you want to change timestamp format in Message, you must change setting "**Time to String**" from **g:i a** to **G:i**. You can find this setting in AdminCP via Search Setting box

Regards.

**Comment by turha71** [comment]
Thanks Harrison... it worked

**Comment by prepperz** [comment]
Had similar issues with the events earlier/ Why does phpfox make this process so convoluted? It should really be an easy process. Point click and it should automatically setup the correct format.
