### ISSUE TITLE
How recurring paypal working with subscription in phpfox

### ISSUE THREAD

**Issue by akiraphat94** [PHPfox-Official/phpfox-v4-issues#2827]
## I have a question:
- Can you tell me about auto recurring payment paypal working with subscription in phpfox
- Example I have subscribed a package with paypal (1 month period auto recurring)
- After 1 month this package will be expired and paypal will auto payment this package recurring but i don't know how my webserver can update new expiry_date for this package in table "phpfox_subscribe_purchase" if paypal payment recurring success.
 
Thanks and sorry about my english

**Comment by harrison05** [comment]
Hi @akiraphat94 

In the first time you purchased a recurring package, we send a notify URL to Paypal, so when you paid success, Paypal sent a notification to the phpFox site via it to update **expiry_date** in DB. 
After 1 month, Paypal will auto charge and send notification again to that URL, therefore we can know your subscription was renewed and update **expiry_date** in DB.

Regards.

**Comment by akiraphat94** [comment]
Thanks for your response.
I have using https://www.authorize.net also for payment recurring package
In configuration this gateway on admincp contain a sentence:
**Enable Silent Post URL via: Account > Settings > Choose Silent Post URL. The Silent Post URL feature should be enabled, and the Silent Post URL should be set to: ... **

I think this setting to used for recurring package (callback to webserver) when package is expired like notify URL of paypal, correct ?
I have to setting "Silent Post URL" on authorize.net or not ?
Thank you so much.

**Comment by harrison05** [comment]
Hi @akiraphat94 

You can read more about **Slient Post URL** at this link: https://support.authorize.net/s/article/Silent-Post-URL
It works like notify URL of Paypal and you have to set up it into your account in case you don't use **Authorize.net webhook** (http://developer.authorize.net/api/reference/features/webhooks.html).

Regards.
