### ISSUE TITLE
Error:: Cannot use object of type Closure as array in

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2828]
## What's happened?
Just noticed that on my main.log file everytime I go to a page I get this error message:

error
2019-11-14 21:25:40
Error Code: 0df708
Error: Cannot use object of type Closure as array in /home/pedroeli/public_html/redepax.pt/PF.Base/include/library/phpfox/phpfox/phpfox.class.php:1897
Stack trace:
#0 /home/pedroeli/public_html/redepax.pt/PF.Base/start.php(631): Phpfox::run()
#1 /home/pedroeli/public_html/redepax.pt/index.php(5): require('/home/pedroeli/...')
#2 {main}

...

## phpFox version
4.7.8

Fresh Install. Only apps from phpfox.

**Comment by harrison05** [comment]
Hi @turha71 

This issue doesn't appear on our side. You can submit a ticket in client area, we will check it directly on your site.

Regards.

**Comment by turha71** [comment]
Just found that this is related to some changes I made. Sorry.  These changes work just fine, but it gives that error message. Witch means in a while, I will have hundreds of Megas in the file. Is there any way to disable the system on writing in that file? I know it's not advisable, but is there any way of doing that?

Thanks

**Comment by spirogg** [comment]
@turha71 you can setup a cron job to clear this file once a day every hour or every 15 mins etc. I am not sure what code to write but you can make from to clear the log file so then it will just clear it every so many mins hours or day you specify. Best way I think. Then if you ever see an error there for something else it will be easier to fix your site. Hope this helps a little.

**Comment by spirogg** [comment]
Also there is option logrotate 
If you Google logrotate you can read more. Some people say logrotate is better option you can set the days. So I read an example you can set for every 7 days logrotate will rotate that file, meaning delete your old log file and create a new one. 

Maybe @harrison05  can give you better option. But you can always read about logrotate. 😀

**Comment by spirogg** [comment]
https://linux.die.net/man/8/logrotate
