### ISSUE TITLE
When can we expect a new build with fixes ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2829]
@harrison05 

Just wondering when we can expect a new build. 4.79 or 4.80?
 It's been almost 2 months and usually we get a an update every 30 days 😀

Thanks so much !!
Regards,
Spiro

**Comment by kerstar** [comment]
@spirogg 

The next version will be phpfox 4.8.0. The new version will be released this month.

**Comment by spirogg** [comment]
Thanks @kerstar

**Comment by PhpFoxJohnJr** [comment]
I wasn't expecting to hear 4.8 as that milestone accepted 35 featured requests.

**Comment by kerstar** [comment]
Last month I asked the phpFox team when they would release version 4.7.9. 
I have been informed that the next version will be version 4.8.0

**Comment by david-younet** [comment]
Hi all,

Thanks for the question, we are development 4.8.0 but we will release 4.7.9 for bug fixes and improvements in this month.

Regards.

**Comment by david-phpFox** [comment]
Hi all,

Thanks for the question, we are development 4.8.0 but we will release 4.7.9 for bug fixes and improvements in this month.

Regards.

**Comment by kerstar** [comment]
Hi @david-phpFox 

Thanks for the information. 
This is very good news! 
I just have a big request here (like other users): before you release version 4.7.9, please check and make sure there are no issues...
