### ISSUE TITLE
Four questions

### ISSUE THREAD

**Issue by kerstar** [PHPfox-Official/phpfox-v4-issues#2831]
Hi,

@harrison05  I have four short questions.
1. When do you plan to release the Photos app update? In this month?
2. When do you plan to release the Chat Plus app?
3. Will it be compatible with phpFox 4.7.9 (no phpFox 4.8.0)?
4. Will Chat plus be available in the Pro package?

**Comment by paulkellow** [comment]
Hi, 
Thank you for your questions. 

I can inform that we just released new Photos 4.7.9 on phpFox Store. You can check and upgrade this app from now.
About other release plans, we are going to update you via our blogs and newsletter when having official info.

Have a nice day.

**Comment by kerstar** [comment]
OK. Thanks for info.
