### ISSUE TITLE
Addressing with @username in pages comment not clickable

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2832]
## What happened?
.After the recent recent @username does nothing when trying to clicking on them.

## Steps to reproduce:
1.  In any pages wall comment. address a user with the @ and when the name appears try to click on it. You can't.

## What is expected?
...

## Browsers and Devices tested
Chrome on Windown 10

## Server information
24 Cores, CentOS 7.6.1810, php7.0.27, apache 2.4.6, MySQL: 5.5.60-MariaDB

...

## phpFox version
phpFox 4.7.8 (Upgraded), Material theme

...

**Comment by harrison05** [comment]
Hi @prepperz 

Could you explain more about this issue? or take a screenshot, because "mention a user" in page comment is working well on my side.

Regards.

**Comment by prepperz** [comment]
Seems to have been resolved by clearing the cache.
