### ISSUE TITLE
question where can I find the main visitors page to add to another page ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2833]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...

hi I was wondering is there a way to get the code copy and paste the visitors page ( see Image Below) to add it to a new page of an app I have created ?
- I want the page to only display the websites images ( like in the photo below) and the sign in block ( not the Signup block). thanks

![image](https://user-images.githubusercontent.com/17736688/69635006-0e65c980-1019-11ea-83ac-5f38930e8378.png)

- I do not need the menu on top just the welcome images and right block that says sign in
thanks for your help in advance

**Comment by cyberhmong** [comment]
I Just css Selector{display:none}
Just Example. I don't remember exactly atm.

**Comment by harrison05** [comment]
Hi @spirogg 

> I want the page to only display the websites images ( like in the photo below) and the sign in block ( not the Signup block). thanks

You can set Banners for Welcome page at **AdminCP > Appearance > Themes > Select your current theme > Homepage > Upload image to Banners section**

> I do not need the menu on top just the welcome images and right block that says sign in
thanks for your help in advance

You can disable the Main menu for Guest by enabling setting **Hide Main Menu**

Regards.

**Comment by spirogg** [comment]
@harrison05 hi thanks for answer. But you didn't understand my question.. I have an app: redirect when users logout. I wanted to find some code to add to my apps page for the default.  Right now I have a page /goodbye

 in my app when users logout it sends them  to /goodbye page...in this page in my app I have added php code for signin box, but I also wanted to get the code for images from the welcome page and next to it the signin box also.. so was wondering where I can finde the code to add to my goodbye page so the images from users welcome page will show in /goodbye page ? 

Hope you understand now 
And thank you for reply

**Comment by harrison05** [comment]
@spirogg I understood.

In your app, you can add a hook with name: **user.service_auth_logout__end.php** and call function **Phpfox::getLib('url')->send(<your_url_here>)** to redirect to your URL.

Regards.
