### ISSUE TITLE
Upgrade Process dont Open...

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2834]
## What's happened?
Cant Update to 4.7.9

## Steps to reproduce:
1. I update all files but when i go to: https://mysite.com/index.php?phpfox-upgrade=true

## phpFox version
From 4.7.8 to 4.7.9
...

**Comment by raulw** [comment]
Same here. Thanks!

**Comment by spirogg** [comment]
I just talked to them they are working on a fix. They will update us via email they said. 
Should be a quick fix. 
Just wanted to update you since I spoke to them just 1/2 hour ago. 😀

**Comment by spirogg** [comment]
@harrison05 @phpfoxdev 

both downloads of version 4.7.8.zip from september and 4.7.9.zip from nov 26th only have version 4.7.8 in them.. in PF.Base/install/include/4.7.8.php and version.php content at bottom only shows 4.7.8

but i think the download from today version 4.7.9 should have 4.7.9.php in PF.Base/install/include/version/
also in PF.Base/install/include/version.php the contents of this file should also have 4.7.9 at the bottom but its only showing 4.7.8 so it seems there is no update, and i think that is why we cant install the upgrade. ? correct me if I am wrong

**Comment by spirogg** [comment]
Ok guys all fixed they said. Go to client area and redownload new PKG and try to upgrade again 😀😀😀

**Comment by harrison05** [comment]
We just fixed and updated a new package for v4.7.9, please download it and try to upgrade again.

Thanks.
