### ISSUE TITLE
issue with cron

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2835]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... i clicked on cron job thinking you created on the same page to change the Cron Job Token
but this is not good... people who are new will never think they can change there cron job Token and will have lots of spam bots killing their server - vps with this ddos attacks..
- cause its the same token for each new install...
- please fix this or add a link to Cron Job Token in CronJob link in admincp so people know there is a cron job token they need to change.

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.7.9

## Screenshots
...

![Capture](https://user-images.githubusercontent.com/17736688/69693262-5f69d200-109a-11ea-873a-7b43e9bc3663.PNG)
here is what this should be like.. **right now i was lost** where did the cron token go ???
then i remembered to search for cron token and finally i found it.. we need to keep it on the same page all of the info cron link and token also PLEASE
![Capture1](https://user-images.githubusercontent.com/17736688/69693261-5f69d200-109a-11ea-86e4-4791cc0082ce.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

> cause its the same token for each new install...

Which install you are talking about? Because each phpFox Site has a random token and it not the same.

> please fix this or add a link to Cron Job Token in CronJob link in admincp so people know there is a cron job token they need to change.

We will review this request.

Regards.

**Comment by spirogg** [comment]
thanks 
Add field to configure cron token below token URL #2835

[Add field to configure cron token below token URL #2835
](https://docs.phpfox.com/display/FOX4MAN/phpFox+4.7.10)
