### ISSUE TITLE
how to disallow people from using your reaction and stickers from your website

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2836]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... it would be nice if you could not allow anyone other than your IP to use your stickers and reaction images.. this will help keep your server usage down. and not cost you lots of money and or slow down your site..

is there anyway you can fix this to disallow outside sharing of these

example
https://v4.phpfox.com/PF.Site/Apps/core-comments/assets/images/stickers/set_2/06.gif
https://v4.phpfox.com/PF.Site/Apps/p-reaction/assets/images/love.svg
## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.7.9

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

Currently,  we don't disallow outside sharing of stickers and reactions icon. But I think you can do this by change RewriteRule rules in your .htaccess file. Something like that: http://altlab.com/htaccess_tutorial.html

Regards.
