### ISSUE TITLE
fastcache cause error 500

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2837]
## What's happened?

> `Error Code: 0b48eb
> Error: Call to undefined function phpFastCache\Core\Pool\IO\mb_strtolower() in /home/unite2/public_html/PF.Base/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Pool/IO/IOHelperTrait.php:55
> Stack trace:
> #0 /home/unite2/public_html/PF.Base/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(58): phpFastCache\Drivers\Files\Driver->getPath()
> #1 /home/unite2/public_html/PF.Base/vendor/phpfastcache/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(48): phpFastCache\Drivers\Files\Driver->driverCheck()
> #2 /home/unite2/public_html/PF.Base/vendor/phpfastcache/phpfastcache/src/phpFastCache/CacheManager.php(218): phpFastCache\Drivers\Files\Driver->__construct(Array)
> #3 /home/unite2/public_html/PF.Base/include/library/phpfox/cache/cache.class.php(202): phpFastCache\CacheManager::getInstance('Files', Array)
> #4 /home/unite2/public_html/PF.Base/include/library/phpfox/phpfox/support.php(142): Phpfox_Cache->__construct()
> #5 /home/unite2/public_html/PF.Base/include/library/phpfox/phpfox/support.php(74): Phpfox_Service_Container->build('cache')
> #6 /home/unite2/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(473): Phpfox_Service_Container->get('cache')
> #7 /home/unite2/public_html/PF.Base/include/library/phpfox/setting/setting.class.php(367): Phpfox::getLib('cache')
> #8 /home/unite2/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(142): Phpfox_Setting->set()
> #9 /home/unite2/public_html/PF.Base/include/init.inc.php(193): Phpfox::dependencyInjection()
> #10 /home/unite2/public_html/PF.Src/Core/Engine.php(80): require('/home/unite2/pu...')
> #11 /home/unite2/public_html/PF.Base/start.php(36): Core\Engine->initLoadClass('/home/unite2/pu...')
> #12 /home/unite2/public_html/index.php(5): require('/home/unite2/pu...')
> #13 {main}`

## phpFox version
phpfox 4.7.9

**Comment by kerstar** [comment]
Hi @Unite2Me 
Did this issue occur in phpFox 4.7.8?

@harrison05 Can you give a hotfix patch for this issue? (Yes, I know that you will fix this issue in the next version of phpfox ..)

**Comment by Unite2Me** [comment]
no, this happen since my update to 4.7.9 , i never see this problem in 4.7.8 :(

**Comment by kerstar** [comment]
That's not good.
If this issue was not found in phpFox 4.7.8, this is probably a minor issue. 
phpFox 4.7.9 contains only minor patches and is not much different from the previous version of phpFox 4.7.8.
@harrison05  please provide instructions that fix this problem (or indicate the file that causes this issue).

**Comment by spirogg** [comment]
@Unite2Me try to go to your php.ini 
And look for apc.enabled can be set to 0 to disable APC from php.ini Than restart your web server or php-fpm. Let me know if this works.

**Comment by harrison05** [comment]
Hi @Unite2Me 

Which PHP version you're using? And, did you enable **PHP multibyte extension** in your PHP server?

**Comment by Unite2Me** [comment]
with php 7.3 im not able to access at my site (i see error 500 always)
with 7.2 this happen only on homepage (core.index.guest)

i dont know how this is possible,i dont changed hosting since years...
and hostiso dont changed nothing in last days in config..
yes, my host support php multiple extension of php with cpanel..

**Comment by Unite2Me** [comment]
my host say:  APC is not supported anymore, old and unused, we use opcache, redis, brotli for caching.

I think phpfox need find a solution for APC problem :(

**Comment by Unite2Me** [comment]
if i use 7.3 how default my site is all white  with this in error log:

[29-Nov-2019 16:13:12 GMT] PHP Fatal error:  Interface 'JsonSerializable' not found in /home/unite2/public_html/PF.Base/vendor/phpfastcache/phpfastcache/src/phpFastCache/Core/Item/ExtendedCacheItemInterface.php on line 27

any news @harrison05 & @kerstar

**Comment by spirogg** [comment]
Ask hostiso to  Check your Php info Settings, Json is Enabled.

**Comment by Unite2Me** [comment]
i can be sure about json is enable, because with php7.2 i dont see this problem.. with 7.3 yes..

**Comment by spirogg** [comment]
Just wondering. Do you have third party apps ?? Did you try to turn off these apps. Also can you create a subdomain 
Dev.yoirdomain.com and install 4.7.8 
Test it's working. Then try update 4.7.9 and see if issues still there ? This will maybe help see what the issue maybe. I don't have this issue using cpanel also. So maybe you can test to see if you get same issue

**Comment by kerstar** [comment]
@Unite2Me 
I installed a fresh installation of phpFox 4.7.9 on a server with php 7.3 with the opcache option enabled. 
I did not notice this issue, the site is working normally.
Why do you use Redis? If you have an ssd disk on your server, then Opcache is all you need. 
What is the point of installing Redis in this case?

**Comment by Unite2Me** [comment]
I had send discussion link to hostiso staff, I hope they make a check with phpfox team for find the problem..
if i disable redis i get errors since 4.7.8 upgrade to 4.7.9

**Comment by Unite2Me** [comment]
ok, i had deactivated all plugins and re-added in my vps php7.3 how default and site dont work...
if i switch to php 7.2 site work..
but why???

who can check?

**Comment by kerstar** [comment]
Hi @Unite2Me 

I checked. I enabled Opcache on php 7.3 on phpFox 4.7.8 and phpFox 4.7.9. 
In both cases I don't see any issue, the pages are working properly. I don't use Redis, I have a basic php configuration.

**Comment by spirogg** [comment]
> ok, i had deactivated all plugins and re-added in my vps php7.3 how default and site dont work...
> if i switch to php 7.2 site work..
> but why???
> 
> who can check?

Hi @Unite2Me can you tell me what you use for php setting in cpanel and what version of cpanel are you on ? 
can you use in ea4 php all option with opcache and see if this will work? 
![Capture](https://user-images.githubusercontent.com/17736688/70117252-9572fd00-162a-11ea-8fb3-d0766daa93c2.PNG)
