### ISSUE TITLE
Tooltip issue on mouse over pages title.

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2839]
## What's happened?
When I go to pages and mouse over the title of a page a tooltip opens but without any info or images.

## Steps to reproduce:
1. Go to pages section
2. Mouse over the title of a page 

## What's expected?
It should show the information from that page

## Browsers and Devices tested
Latest Chrome

## phpFox version
phpfox: 4.7.8
Pages: 4.7.7

...

## Screenshots
![85233b31-fd90-4dce-a9ed-16e218da86a1](https://user-images.githubusercontent.com/9699688/69869100-c5757580-12a3-11ea-9d0a-d0cf12689282.jpg)

**Comment by spirogg** [comment]
I have not checked it yet. I installed 4.7.9 will check to see if fixed. But they said it was fixed in 4.7.9 of PhpFox..I'll come back and let you know. I hade this issue #2817

**Comment by harrison05** [comment]
Hi @turha71 

As our reply at issue #2817, the tooltip in Pages is supported from phpFox v4.7.9, please upgrade your site to the newest version.

Regards.

**Comment by turha71** [comment]
Yes, after upgrade it's workig ok. Thanks
