### ISSUE TITLE
activity points plugin hook

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2840]
the plugin hook in "/Job/UpdatePoints.php" is the same at start and end. if i use this hook the script does not work.

please change the hook at the end of the function.

activity points app 4.7.6

**Comment by harrison05** [comment]
Hi @Scheinwelt-Media 

Thanks for your report. We will update it.

Regards.

**Comment by kibcode** [comment]
hey @harrison05 when can we expect a fix for this?

**Comment by PhpFoxJohnJr** [comment]
Echo...On Dec 1, 2019, we will update it.

**Comment by harrison05** [comment]
Fixed on Activity Points v4.7.7
