### ISSUE TITLE
Missing phrases for translation on comments

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2841]
## What's happened?
When adding or creating a new comment there are (in AdminCP) no variables for translating these phrases into other languages: "`RECENT`" and "`ALL`" 

## Steps to reproduce:
1. Goto admincp/language/phrase
2. choose any language other than English
3. Search for these phrases returns zero result

## What's expected?
Searched phrases

## Browsers and Devices tested
all

## Server information
all

## phpFox version
phpFox 4.7.9

## Screenshots
![Untitled-3](https://user-images.githubusercontent.com/11414490/69899156-ad186000-1362-11ea-9c93-1912f6f5805f.jpg)

**Comment by harrison05** [comment]
Hi @CimborNet 

This is a bug, we will fix in the next version of Comments App. 
But, you can hotfix, by going to **AdminCP > Globalization > Phrases**, then click on button **New phrase** and add new 2 phrases with value "Recent" and "All" (Must select **Quick** option - see my screenshot)
![Screen Shot 2019-12-02 at 10 17 55](https://user-images.githubusercontent.com/41947198/69928059-08765980-14ed-11ea-896c-8300866a8124.png)

Then, back to Phrases manage page, you can translate them.

Regards.

**Comment by david-phpFox** [comment]
Fixed in Comments 4.1.2.
