### ISSUE TITLE
Incorrect display of phrases FIRST and LAST at the AdminCP/LANG/PHRASE.

### ISSUE THREAD

**Issue by CimborNet** [PHPfox-Official/phpfox-v4-issues#2842]
## What's happened?
In the section for editing phrases (`admincp/language/phrase/`) when switching to the **second** and **subsequent** pages and **using a non-English** interface in AdminCP at the bottom of the page we see an **incorrect display** of phrases for the `first `and `last `pages.

## Steps to reproduce:
1. Goto admincp/language/phrase/
2. scroll to the bottom of the phrase page
3. go to page 2,3,4 ... (except the first and last)

## What's expected?
I would like to see the correct display of words inside the page navigation button.

## Browsers and Devices tested
all

## Server information
all

## phpFox version
phpFox 4.7.9

## Screenshots
English AdminCP
![Untitled-1](https://user-images.githubusercontent.com/11414490/69899392-8ad41180-1365-11ea-8051-4e69ffd151f6.jpg)

non-English AdminCP
![Untitled-2](https://user-images.githubusercontent.com/11414490/69899394-8f98c580-1365-11ea-94fd-26474cb9ad39.jpg)

**Comment by harrison05** [comment]
Hi @CimborNet 

This is a layout issue, we will check and fix it.

Thanks.

**Comment by harrison05** [comment]
Fixed in phpFox v4.7.10
