### ISSUE TITLE
No support for default emoji's

### ISSUE THREAD

**Issue by Shamelesshit** [PHPfox-Official/phpfox-v4-issues#2844]
## What's happened?
When users make a status post, or comment on someone else's post using smileys from their native keyboards on their phones or on screen keyboards sometimes the smileys show up correctly and most of the time they just appear like some scrambled chicken scratch like this: ߘȰߔ 

As you might guess this is very annoying to users.. 

I believe it is due to database collation or text parser phpfox is using.. would love to see this fixed! 

## Steps to reproduce:
1. Visit phpfox site on your mobile device  
2. post comments with emoji's from your phones keyboard
3. do this with different emoji's and it will eventually mess up

## What's expected?
this is the end of 2019 going into 2020.. people are using emoji's more than ever now days and they expect them to appear correctly.. not all scrambled up..

## Browsers and Devices tested
Windows 10 64 bit pc using firefox and chrome latest version browsers, issue is the same.
Android 9 firefox and chrome latest version mobile browsers, issue seems to be the same across platforms and browsers.

...

## Server information
CentOS using mariaDB 

...

## phpFox version
phpfox 4.7.9

...

## Screenshots
...
![79114580_1688332898009323_7602039869937811456_n](https://user-images.githubusercontent.com/56236348/69907311-968cfb80-1398-11ea-94b5-5c045cf3b843.jpg)
![78948641_484946088800589_4854858197619441664_n](https://user-images.githubusercontent.com/56236348/69907312-9ab91900-1398-11ea-935a-32e1033344c0.jpg)

**Comment by harrison05** [comment]
Hi @Shamelesshit 

Which is Encoding and Collation in your database? Because it working well on my site. Do you test on our demo site? Does it occur?

Regards.

**Comment by Shamelesshit** [comment]
Hey @harrison05,  it does occur on the v4 phpfox demo site, I believe it has something to do with symbols like "!?" being at the end of sentences before emojis.. I hope this info will help!

![Screenshot_20191211-025114_Chrome](https://user-images.githubusercontent.com/56236348/70606702-ad1a2a80-1bc2-11ea-8484-f83dcd94ddfb.jpg)

![Screenshot_20191211-024934_Chrome](https://user-images.githubusercontent.com/56236348/70606669-996ec400-1bc2-11ea-8748-3242a4090d80.jpg)
![Screenshot_20191211-024718_Chrome](https://user-images.githubusercontent.com/56236348/70606690-a4c1ef80-1bc2-11ea-813f-f9bdfdeb0242.jpg)

**Comment by harrison05** [comment]
Hi @Shamelesshit 
> Hey @harrison05, it does occur on the v4 phpfox demo site, I believe it has something to do with symbols like "!?" being at the end of sentences before emojis.. I hope this info will help!

I just checked on our demo site, it doesn't occur (you can check my comment on your wall). Do you try to post emoji by other devices? It's weird

Regards.

**Comment by Shamelesshit** [comment]
Hmm that is very weird.. Let me try some different keyboards and devices maybe browsers and see what I can come up with thanks for helping 👍

**Comment by Shamelesshit** [comment]
Hello @harrison05!

I have discovered the problem symbols regardless of the connection type, browsers type or version, keyboard type or version or device type if a comment contains any of the following symbols in it anywhere at all the default emojis will show up broken and weird. 

The symbols are 
" double quote
' single quote or apostrophe 
& ampersand or and 
< less than
 > greater than

No matter where in a comment they are placed or how long the Comment if you place these symbols in it and an emoji you will get weird results 

Thanks again for the help!

**Comment by harrison05** [comment]
Hi @Shamelesshit 

I understand now. We will check and find a solution to fix it.

Thanks for your report.

**Comment by Shamelesshit** [comment]
@harrison05 thanks allot I'm glad we could work together to figure it out and hopefully find a fix 👍👍

**Comment by kerstar** [comment]
Hi @harrison05 

Did you fix this issue in the last Comments app update?

**Comment by Shamelesshit** [comment]
Hi @kerstar 

I can confirm this issue was solved i've been testing it this morning and it does appear to be working correctly now!

**Comment by kerstar** [comment]
Hi @Shamelesshit 

Thanks for info!

**Comment by david-phpFox** [comment]
Fixed in Comments 4.1.2.
