### ISSUE TITLE
Problem with comments app uninstall

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2845]
## What's happened?
I install the new comment app to test, but there were a lot of issues even after rebuilding the core theme and decided to go back to the native comments. After uninstalling the app the native comments don't show anymore and now I don't have comments on my network. 

How can I have the native comments back?

In attach I'm sending an image of what happened after I install the app. I try to rebuind the theme, but nothing. The first image is the avatar that show big, then you have the comment box and after that a image that I don't know what it is.

![comment app](https://user-images.githubusercontent.com/9699688/69914948-98f76000-1441-11ea-93f9-756b57c2ee0a.jpg)

## What's expected?
I expected to be able to return back to the native comments if I uninstall the comment app.

## phpFox version
4.7.8

**Comment by harrison05** [comment]
Hi @turha71 

We removed the native comment module from the newest of phpFox, you have to use Comments App. Did you clear cache after rebuild core theme? Because this issue doesn't occur on our site.

Regards.

**Comment by turha71** [comment]
Ok... just upgrade to latest version and it's working ok now. thanks
