### ISSUE TITLE
Map of my localization show on pages info

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2846]
## What's happened?
When I edit pages info a map of my localization is added to the text. I don't want this to happen. Is there any setting that I can use to disable this option? I only want to disable this on pages, and not on events where I enable the option to check my localization when using "View on Map".

## What's expected?
I expected to have an option to disable this only on pages. Don't make any sense to have this option on pages info, because I could be editing this info on a different location from the one the page is. So imagine that on that text I say that my page (business) is in one city, but I'm editing this in another city. The map will not match the page location.

It will be nice also to add to pages an option to set the location of the page, and the map will show that location, and not the location where I'm currently.

I have created a featured request here:
https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/912

## phpFox version
4.7.9

**Comment by harrison05** [comment]
Hi @turha71 

I got your issue. Currently, when you edit Page's Location, it only suggests locations near your current location. We will review your request in case we should improve this.

Regards.

**Comment by turha71** [comment]
Thanks Harrison for considering this...

I will be honest. I have made this feature request not knowing that there was a tab for location:
https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/912

Imagine my members! Because we are used to see the location on the first tab as in events and marketplace, and if we don't see it on the first tab we think there is no field for location.

So please considerer placing the location on the first tab and make it work the same way as events, allowing us to set any location with the map updating in the bottom. And then add also a "View on Map" block for showing all pages on google map.

Regards

**Comment by harrison05** [comment]
Hi @turha71 

Ok, we will review your feature request.

Regards.
