### ISSUE TITLE
question about countries and states uploading and saving

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2847]
Question about uploading Countries / States
----------------------------------------

## What's happened?
...

-  @harrison05 I have added all states/ provinces in all countries each with the .txt file. is there a way I can save and pkg into 1 file all countries / states ? 
and possible to upload all at one time ?

- or what do you suggest in case I need to reinstall on a fresh install ? what is the best way to do this ?

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.7.9

## Screenshots
... example 
![Capture](https://user-images.githubusercontent.com/17736688/70126664-1f2cc580-163f-11ea-828e-e8b60f5f152a.PNG)

**Comment by kerstar** [comment]
Hi @spirogg 

How did you add states and provinces using the txt file? I added to the database.

**Comment by spirogg** [comment]
@kerstar when you go to Admincp
Countries and you see the top right blue button if you click it says to import .txt file 
So for each country I added states in each .txt file and imported. Took a long time 😂
But I finally finished 
I just wanted to know if there is a good way to save this into one file? 
 so I can reupload if needed later 

Thanks 

Spiro

**Comment by harrison05** [comment]
Hi @spirogg 

Currently, we only support import states/provinces for each Country at one time. 
But we will review your request and inform you in case we can implement it.

Regards.

**Comment by harrison05** [comment]
Hi @spirogg 

We won't support import multiple Countries at one time. 

Regards.
