### ISSUE TITLE
Video Count on FEED does not add to views

### ISSUE THREAD

**Issue by jimmybsilva** [PHPfox-Official/phpfox-v4-issues#2849]
## What's happened?

When you are on the main feed and you view a video it does not add to the count. Please get excited about people viewing their videos.

## Steps to reproduce:
1.  Go to the main Feed 
2.  Watch a video 
3.  Refresh and see if the count is updated.

## What's expected?

 It would be great if there was an option that automatically added a view once the video loaded on the feed or when someone watched it.

## Browsers and Devices tested
 Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10,

## Server information
 CentOS 7, php 7.2 apache)

...

## phpFox version
Phpfox 4.7.9

...

## Screenshots
...
If you notice count is still zero, watched and refreshed and the count is still 0

![image](https://user-images.githubusercontent.com/35279981/70286141-dbd97080-177e-11ea-91ec-db49acaaa486.png)

**Comment by harrison05** [comment]
Hi @jimmybsilva 

With the current version of Videos app, the total view only increases when you view detail of a video. So, when you click to play on Feed it doesn't count.

Regards.

**Comment by harrison05** [comment]
We implemented this feature in the newest version of Video App 4.7.9 - Total view will increase if you play a video on Activity feeds

Regards.
