### ISSUE TITLE
Newsletter is sent to 0 members

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2850]
## What's happened?
When I create a newsletter to be sent to all my members, the newsletter reports that it is sending to 0/0 mails sent. Check the attach image.

## What's expected?
if my network as 50 members it should say: 0/50 mails sent

(Example: phpFox 4.6.0)
4.7.9

## Screenshots
![newsletter](https://user-images.githubusercontent.com/9699688/70324274-f49d6100-1826-11ea-81dd-85ec55d3eb4b.jpg)

**Comment by harrison05** [comment]
Hi @turha71 

- Do you check your mail config that works or not? 
- Do you enable option **Override Privacy** when you create a newsletter?
- Make sure your newsletter condition "Location, Gender, Age..." match with your member 

Regards.

**Comment by turha71** [comment]
I have created a newsletter to send only to the administrator usergroup that has 2 members.
The configurations used are on the attached image.
In the end, I have 0/0 when I should have 0/2
No email is sent.

![configuration](https://user-images.githubusercontent.com/9699688/70699680-6a8b4780-1cc1-11ea-8eb1-6afa4af600f5.jpg)

**Comment by harrison05** [comment]
Hi @turha71 

The newsletter is working well on our side. You can submit a ticket in the client area, then we can check it on your site to find the root cause.

Regards.
