### ISSUE TITLE
Long name goes out of the box

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2851]
## What's happened?
If the name is too long it goes out of the box in profile. For details please see the attached image.

## phpFox version
4.7.9

## Screenshots

![long_name](https://user-images.githubusercontent.com/9699688/70373609-60440480-18e1-11ea-8ecb-35423b0b55e8.jpg)

**Comment by harrison05** [comment]
Fixed in Material Theme v4.7.10
