### ISSUE TITLE
Profile info misconfiguration

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2853]
## What's happened?
When we add a block to position 1 or 3 in Profile Info some information gets misconfigured

## phpFox version
4.7.9

## Screenshots
![profile-info](https://user-images.githubusercontent.com/9699688/70654817-f9ab4780-1c4e-11ea-9bcf-d4f738b8854a.jpg)

**Comment by harrison05** [comment]
Hi @turha71 

Which type of block did you add to the Profile info page (PHP Block File / PHP Code / HTML Code) ?

**Comment by turha71** [comment]
Hi,

The block on position 1 are the ones generated by custom fields, in this case is the "About me" block.

Regards

**Comment by turha71** [comment]
Ok, you can close this issue... the problem was with the map on the top.

Sorry for your time.
