### ISSUE TITLE
Ad postion still shows on some pages

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2854]
## What's happened?
I have created an ad position to show my ads only on core.index-members. So I have selected all the pages I don't want the ads to show and leave unselected only the core.index-members.

But still, there are pages where the ads show. Here go the list:

- Reading a thread in the forum
- Edit Profile page
- Adding new video
- creating new page (didn't check groups)
- creating new event
- adding new forum post
- contact us page
- see all notifications page
- activity points page
- page that says: Profile is private.
 
probably there are more pages.

## What's expected?
The ads shouldn't show in any page besides the core.index-members

## phpFox version
4.7.9

## Screenshots
![ads](https://user-images.githubusercontent.com/9699688/70789089-45aed700-1d8a-11ea-94d6-1a04dcd9cbac.png)

**Comment by harrison05** [comment]
Hi @turha71 

We will check this issue, this might a bug from Ads App.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Might be a bug?  Dated December 16, 2019

**Comment by harrison05** [comment]
Fixed in Ads v4.2.8
