### ISSUE TITLE
THANK YOU PHPFOX TEAM & MERRY CHRISTMAS ALL 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2858]
@harrison05 and phpfox team

( ( ( MERRY CHRISTMAS !!!! ) ) )

**- You guys are working hard**

- I wanted to thank you for helping us get more fixes and better customer support this YEAR than ever before 

THANKS AGAIN...

Best Regards,
Spiro

**Comment by harrison05** [comment]
Thank you, @spirogg 

Merry Christmas and Happy new year.
We're happy to have customers like you, hoping you can work with phpFox in the long term. 

Regards.

**Comment by PhpFoxJohnJr** [comment]
Merry Christmas and Happy New Year PHPFOX...I am back to typing again.

**Comment by spirogg** [comment]
Ok no we have an Android app for GitHub. 😜😜😜😜 Nice. Finally
