### ISSUE TITLE
Icon don't work when adding new menu to profile using plugin

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2862]
## What's happened?
When I add the following code to the plugin **profile.service_profile_get_profile_menu** the icon I select don't show. Instead, it shows the default one of the box.

```
$aMenu = array(
	'phrase' => _p('Mensagens Privadas'),
	'url' => '.mail',
	'actual_url' => '.mail',
	'icon' => 'feed/photo.png'
	);       	

$aMenus[] = $aMenu;
```

## phpFox version
4.7.9

**Comment by harrison05** [comment]
Hi @turha71 

If you're using our Material Theme, you should use property "icon_class" instead of "icon".
Example:
```php
$aMenu = array(
	'phrase' => _p('Mensagens Privadas'),
	'url' => '.mail',
	'actual_url' => '.mail',
	'icon_class' => 'ico ico-photos-alt-o'
);  
```
Regards.

**Comment by turha71** [comment]
Thanks... it worked just fine.

Where can I see a list of all icons from ico? Is there in the net a website like font awesome where I can see all the icons?

Thanks

**Comment by harrison05** [comment]
Hi @turha71 

You can view demo of Lineficon at the link: 
**<your_site_url>/PF.Site/flavors/material/component/linefico.html** 

Regards.

**Comment by turha71** [comment]
Thanks... didn't know that page existed. Very usefull.
