### ISSUE TITLE
Language Editing Problem

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2865]
What's happened?
I see some problems when i choose lang "ITALIAN" - manage 
i translate some phrase but when i save the result the system lose the setting "italian" and show to me all languages phrases.

This happen with filters too...

## Browsers and Devices tested
Firefox

## phpFox version
Firefox 4.7.9

**Comment by harrison05** [comment]
Hi @Unite2Me 

Do you mean filter conditions are reset after click "Save All"?

Regards.

**Comment by Unite2Me** [comment]
> 
> 
> Hi @Unite2Me
> 
> Do you mean filter conditions are reset after click "Save All"?
> 
> Regards.

yes, i had suggest to phpfox team to make a better translation system like the "fox v3" for translate single module, and export only the selected modules (for relase a lite translation or pro is a good tool for me)

**Comment by harrison05** [comment]
Hi @Unite2Me 

I will close this topic, please follow our update in #2880 
We will fix it in the next version of phpFox.

Regards.
