### ISSUE TITLE
AdminCP Stats Counter Fix

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2866]
## What's happened?

I dont know why this happen,but i had removed all feeds (manually, and is boring do this)
but in my admincp i continue to show 600+ feeds,i clean cache and rebuild the theme but i continue to see 600+feeds.

## Browsers and Devices tested
Firefox

## phpFox version
PHPFOX 4.7.9

#screenshot 
https://ibb.co/JzvzxsZ

**Comment by harrison05** [comment]
Hi @Unite2Me 

Where did you see that Feeds counter? Could you take a screenshot?

Regards.

**Comment by Unite2Me** [comment]
> 
> 
> Hi @Unite2Me
> 
> Where did you see that Feeds counter? Could you take a screenshot?
> 
> Regards.

yes, is this: https://ibb.co/JzvzxsZ

**Comment by harrison05** [comment]
Hi @Unite2Me 
That counter is total "User Status" on your site. It counts records in table "user_status".
I test on my site: add new status then delete its feed, the counter is working correctly.
I wonder how did it happen on your site?
