### ISSUE TITLE
Counter issue in Forum App when using child forums

### ISSUE THREAD

**Issue by SWEIHER** [PHPfox-Official/phpfox-v4-issues#2867]
I have the following forum structure:

Main Category
  Forum 1
  Forum 2
    Child Forum 2.1
    Child Forum 2.2
  Forum 3

When creating a thread in "Forum 3" and someone answers on it, then you can see on the main forum overview page in the line for Forum 3: "1 Threads   1 Posts".
When I do the same on "Forum 2", then you will see still "0 Threads   0 Posts" in the line for Forum 2.
Seems if a child forum exist then the counter does not count the threads and posts in it. Only threads and posts in the child forums "Child Forum 2.1" and "Child Forum 2.2" will be counted for "Forum 2" but not those directly in Forum 2.

Tested on Firefox 72 and Chrome 79.

## Server information
phpFox Version: | 4.7.9
ForumApp Version: | 4.6.3
PHP Version: | 7.3.14
PHP Sapi: | fpm-fcgi
PHP safe_mode: | False
OS: | Linux Debian 9.11
SQL Driver Version: | MySQL 5.5.5-10.1.26-MariaDB-0+deb9u1
nginx 1.16.1.3-debian9.0.19111813

**Comment by harrison05** [comment]
Hi @SWEIHER 
I tried to reproduce this issue, same with your steps. But it doesn't occur on my side. You can see my screenshots, the counter still counts thread/post in "Forum 2" directly.

![Screen Shot 2020-02-07 at 13 48 25](https://user-images.githubusercontent.com/41947198/74007336-ae908500-49b0-11ea-8f2a-23e8465603af.png)
![Screen Shot 2020-02-07 at 13 48 41](https://user-images.githubusercontent.com/41947198/74007345-b3553900-49b0-11ea-8c6b-c8e1940c8f6f.png)

**Comment by SWEIHER** [comment]
Hello @harrison05,
due to your answer I made some tests and added some new subforums and categories. When posting in these new forums everything worked fine. Then I wiped the whole forum and set it up again from scratch. Now counting works as intended. Seems that something was wrong with the existing forums. Maybe sth. regarding older versions?
Please excuse the false alarm. Topic is closed.
