### ISSUE TITLE
Admincp settings spam assistance email white list 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2868]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...hi it become an issue when users sign up and try to change their password. In admincp settings spam assistance
There is at the bottom email white list. On a fresh installs of phpfox ver 4.7.9 
You have @yahoo.com @google.com
So if a users has signed up with @gmail.com email he will not get any emails at all. Is there a way to set default @gmail.com like before. I have had a few people ask why they not get emails. So I found this and changed to Gmail instead of Google. 

- Before this version it was working just fine. 
Maybe an idea is to write out example but not in the box. Leave it blank so users emails can get emails - notification emails etc. Or fix it to say @gmail.com as default. 

## Steps to reproduce:
1. Fresh install 
2. Set admin email as a Gmail address
3. Logout and choose forgot password
4. Wait for email. ?? There is no email ever sent. 
5 go change in admincp settings Spam assistance the last box from *@google.com to *@gmail.com and url white list needs *.gmail.* now logout and select forgot password. Now you will get the email. ??

- also When I do a fresh install of phpfox 4.7.9 but I use myemail@outlook.com as admin email without changing settings in spam assistance I get all emails even though outlook.com is not in white list. Why is this so ? 

Only Gmail gives issues unless you change in these fields
```
URL white list
*.gmail.*
Email white list
*@yahoo.com, *@gmail.com

```
Can you please let me know why Outlook emails work and Gmail doesn't unless we add the correct values for Gmail on fresh install to receive emails and notifications ? 

Thanks 
## What's expected?
...
This should be default setting when fresh install. 
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...all browsers 

## Server information
(Example: CentOS 7, php 7.1 apache)

...Centos 7 php 7.3

## phpFox version
(Example: phpFox 4.6.0)

...4.7.9

## Screenshots
...

**Comment by spirogg** [comment]
*@yahoo.com, *@gmail.com
Also you need url white list too to fix.

**Comment by spirogg** [comment]
Questions?

**Disable All External Emails**
Enable this feature to remove all external emails from the site.
- 1) if I turn this on will this block all emails not on white list from signing up ? 

- 2) if yes > what if I had 200 users who signed up with @me.com emails but now I no longer want users with that email to be able to sign up. ( will the other 200 users not be able to use the site? or not get notifications emails etc any more ?
 
Notice: Sites added to the "Email White List" will be allowed.


**Email White List**
Add sites that you want to allow in external emails.

- when adding emails ( example *@yahoo.com, *@gmail.com ) to white list.

Will this be the only email addresses able to sign up or sign in to website if I Enable this feature ? 
or will they just not get emails notifications etc sent to them ?
-  3) what exactly is this feature used for ?

**Comment by harrison05** [comment]
Hi @spirogg 
**Disable All External Emails** setting doesn't block email notifications sent to users. It just filters and removes all emails that don't allow in the white list (Ex: item's description, comment, status...)
Did you check your email server config, can it work with Gmail? Because it is working well on my side.

Regards.
