### ISSUE TITLE
Left column modification

### ISSUE THREAD

**Issue by EgyCheETah** [PHPfox-Official/phpfox-v4-issues#2869]
Hi guys

I am trying to edit and modificat the left block on my localhost but it is actually appear the the codes instead of fetching the data so any tips please? 

V 4.7+

Here is a screenshot
![DSC_0597](https://user-images.githubusercontent.com/25225276/74081302-2795e800-4a56-11ea-9296-c1c9450ace49.JPG)

**Comment by harrison05** [comment]
Hi @EgyCheETah 

Where did you add that code? Could you show us your source code and its relative path?
