### ISSUE TITLE
Please support Panels in your bootstrap.less

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2871]
Hi Please add

`@import "bootstrap/panels.less";`

to your PF.Base/less/bootstrap.less

**Comment by harrison05** [comment]
Hi @Bjoern3003 

I will inform our FE team to review your request and inform you if have any updates.

Regards.

**Comment by harrison05** [comment]
Hi @Bjoern3003 

Your request is now available in phpFox v4.7.10

Regards.
