### ISSUE TITLE
My website was offline and I didn't know.

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2872]
## What's happened?
Today someone wrote to me saying that there was a blank page on my website and they couldn't access it. But everything was ok to me. Then I logout and saw that there was a blank page, the one that shows when I have the website offline. I went to admincp and saw that the site was offline but I didn't click on that setting. So what happen?

Well, what happen was that yesterday I try to make a backup using your app, and the backup didn't finish. Some error happen, probably related to some server limitations. But it seems that if the backup gives an error the website is kept in offline mode, and that's bad. 

## What's expected?
If that backup gives an error, the website should return to online mode and not be kept on offline mode.

## phpFox version
Lastest version: 4.7.9

**Comment by harrison05** [comment]
Hi @turha71 

You can submit a ticket in the client area, our team will help you check directly. If this is a bug, we will fix it.

Regards.

**Comment by turha71** [comment]
Hi,

My issue is not with the error during backup. I believe that is because of my php limitation configuration and because the file being generated is higher than the php limit.

My issue here is that if there is an error during backup the website is kept offline, and because I am login I don't notice and my members that are not login can't log into the site.

So, if the backup gives an error, then the website should return back to online mode and not kept offline.

Regards

**Comment by harrison05** [comment]
Hi @turha71 

We will check this case, could you tell us which error occurred on your site during the backup process? 

Regards.
