### ISSUE TITLE
Problem with Fresh Installation (403 Error)

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2873]
## What's happened?
I got a error message in final fresh installation step.
(in docs for clients of phpfox i dont see any article with this 403 error)

## Steps to reproduce:
1. I start fresh installation, put my licence codes ,choose the modules, admin details but i have this error:
Forbidden

You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

## What's expected?
Icant install new phpfox.

## Browsers and Devices tested
Firefox

## phpFox version
4.7.9

**Comment by spirogg** [comment]
What server you have. Do you have this error before with another version installed ? What php version ? Centos 7 ubuntu ?

**Comment by Unite2Me** [comment]
I have vps with hostiso, with php 7.2

**Comment by harrison05** [comment]
Hi @Unite2Me 

You should check the File permission of your web directory which contained the index.php files.

Regards.

**Comment by Unite2Me** [comment]
I fixed this with intercrase some php.ini values..
but why dont add in the install check the field who say "install setup req more execution time in php.ini"? this help new installations...
