### ISSUE TITLE
Making Invite app and Group app more consistence.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#2874]
When you invite someone through the Invite App and you enter the email into the "to" text box you do not have to hit the enter key for it to save the email.

When you invite someone through the Group App on the group tab called "invite" and you enter the email into the "Invite People via Email" text box you need to specifically hit the enter key for it to save the email to the text box.  Once you hit the enter key it highlights the email in a grey color and gives an "x" option to remove this email.

I am not sure which version the users want but lets us at least use one or the other instead of two different processes.  The only issue I see with the second version is that if you don't hit the enter key and you hit the send key, it does makes it look like it sent the email but it really does not send it.

4.7.9 Phpfox

**Comment by harrison05** [comment]
Hi @PhpFoxJohnJr 

We understand that "Invite by Email" in our apps aren't consistent. We will review them and inform you if have any update.

> The only issue I see with the second version is that if you don't hit the enter key and you hit the send key, it does makes it look like it sent the email but it really does not send it.

And we will also check this issue.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Wait...first this is not an Enhancement.  They are the same screen just in a different area of the site.  So pick a version and do a copy-paste thingy as there have been at least two upgrades since March 27.

**Comment by PhpFoxJohnJr** [comment]
Thank you very much.  I can't to test it.
