### ISSUE TITLE
Update - Answered: question about CentOS8 + php7.3 or 7.4 with phpfox?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2875]
----------------------------------------

## What's happened?
...  Is it possible to use CentOS8 + php7.3 or 7.4 with phpfox?
has anybody tried or know if it will work? 

thanks in advance

Spiro

**Comment by spirogg** [comment]
Ok I just tried it with Plesk Obsidian.. Installed centOS8 then installed Plesk and then installed phpfox 4.7.9

- works perfect actually seems faster than centOS 7 but could just be me :) 

- thanks I just I answered my own Question ... 

- @harrison05 
- do you know when 4.7.10 is coming, I see some wording in phpfox documentation for version 4.7.10 
<also on github I see in the change log shows 4.7.10 ? >
- https://github.com/PHPfox-Official/phpfox-change-logs/blob/master/4.7.10.log

but when logged in to see if we have the update it still shows download 4.7.9 and 4.7.10 is not avail ? 

- thanks alot and hope you all are staying Safe

**Comment by harrison05** [comment]
Hi @spirogg 

We will release version 4.7.10 in this month, might next week or later. 
Just stay away from COVID-19 and wait for the new version of phpFox.

Regards.

**Comment by spirogg** [comment]
Thanks brother 👍
💪 stay healthy my Friend

Regards,
Spiro G 😀
