### ISSUE TITLE
Language Importer

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2876]
## What's happened?
I have my demo site where I translate all phpfox,
if i try to download my custom pack is ok.
when i upload the pack customized in my new phpfox installation is like I imported english default phrases and not the custom done by me.

## Steps to reproduce:
1. log in my IT demo site,
2. download my IT lang pack
3. fresh installation of phpfox
4. Upload my IT lang pack
5. I refresh the phrases of pack
6. My IT pack have all phrases in english like the default pack.

## Browsers and Devices tested
Firefox latest

## phpFox version
phpfox 4.7.9

**Comment by harrison05** [comment]
Hi @Unite2Me 

I can't reproduce this issue on my side.

You can check file **module-core.xml** after you exported your lang package (in zip file), and make sure all translated phrases are in it. Trying to clear cache after import if every phrase corrects. 

Regards.

**Comment by Unite2Me** [comment]
yeah, I had try to choose how default but i still have all phrases in english inside my IT pack..
but this dont happen in my live site with the some pack.

**Comment by Unite2Me** [comment]
@harrison05 can u make more test? I really think this bug need to be confirmed and fix :(

**Comment by harrison05** [comment]
I tested with some Languages, but they're still working well, they keep all phrases translated after export and import to other sites, double-check your exported lang file - **module-core.xml, phpfox-language-import.xml** (language code, translated phrases...).

If the issue still occurs on your site, you can submit a ticket in Client Area, our team will help to check.

Regards.
