### ISSUE TITLE
Member deletion doesn't delete all records

### ISSUE THREAD

**Issue by lethality** [PHPfox-Official/phpfox-v4-issues#2878]
When you delete a member from the AdminCP, not all rows referencing them in the database are removed, for example: privacy settings

1. Have a member, and verify they have corresponding settings saved, eg.  **phpfox_user_privacy**
2. Delete the user (tested in AdminCP)
3. Most user records deleted, but their privacy settings remain.

When a user is deleted from back or front-end, all records linked specifically to that user_id should be deleted.

## Browsers and Devices tested
Opera Version:67.0.3575.97 on Windows 10.

Server:
CentOS Linux 7.7.1908
PHP 7.3.16

phpFox version:
4.7.9

**Comment by harrison05** [comment]
Hi @lethality 

We will check and improve this.

Regards.

**Comment by harrison05** [comment]
We updated this feature in v4.8.0

Regards.
