### ISSUE TITLE
theme breaks with php7.4.4 enabled?

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2879]
## What's happened?

local install of phpFox with xampp php7.4.4 breaks the theme. it works fine with php7.3.16. not testet on a live site.

## Server information

ubuntu xampp, php 7.4.4, apache

## phpFox version

tested with v4.7.9 & v4.7.10

## Screenshots
![pf1](https://user-images.githubusercontent.com/13225682/79049851-3bacc000-7c26-11ea-8e24-3c90725a9b64.png)

**Comment by spirogg** [comment]
@Scheinwelt-Media same on live site I just installed 4.7.10 on centOS 7 with Plesk obsidian control panel and  php 7.4.4 and I get broken invite page and some other  pages are breaking also. But when using php7.3 it works. Fine. Tested last night

**Comment by harrison05** [comment]
Hi @Scheinwelt-Media 

We will check compatible between phpFox with PHP 7.4.4 and inform you if we have any updates.

Regards.

**Comment by harrison05** [comment]
We will support PHP v7.4.4 in the next version of phpFox. With the current version 4.7.10, we only support max version PHP v7.3.

Regards.

**Comment by harrison05** [comment]
We will support PHP v7.4 in the next version of phpFox.

Regards

**Comment by spirogg** [comment]
@harrison05 thanks brother. Hope you and your family are doing well 😀
