### ISSUE TITLE
Lang Edit Problem [New]

### ISSUE THREAD

**Issue by Unite2Me** [PHPfox-Official/phpfox-v4-issues#2880]
https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2865
this is back in 4.7.10

## phpFox version
phpFox 4.7.10

when i choose "save all" page reload with all phrases in all languages mix without remember the pack who i choose to edit.

**Comment by harrison05** [comment]
Hi @Unite2Me 

This is a mistake from our development team when fixing this bug. 
We will check and update it.

Regards.

**Comment by harrison05** [comment]
Related to #2865

**Comment by harrison05** [comment]
Fixed in phpFox v4.8.0
