### ISSUE TITLE
Word filters cause issues in the admincp functionality and unpredictable results in the functionality of the entire application.

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2881]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Word filters cause issues in the admincp functionality and unpredictable results in the functionality of the entire application.

## Steps to reproduce:
1. I loaded a batch of word filters via csv. List is over 500 words.
2. In the admincp installed apps section, the app names are being censored.
3. Subscription section stopped working.
4- Some actions on front end no longer function. They just hang.
5- Removing the word list fixes the issue, but I need the censorship feature to work!

## What's expected?
Censorship should not be included in the entire back end and from affecting any code.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

ALL

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

... 479 - Latest as of 4/12/20

## Screenshots
...
![image](https://user-images.githubusercontent.com/48427415/79080997-66ab1880-7ce7-11ea-8173-cdbb41afb885.png)

![image](https://user-images.githubusercontent.com/48427415/79081009-7dea0600-7ce7-11ea-9ee5-dfa49bee31f5.png)

**Comment by hamadax** [comment]
![image](https://user-images.githubusercontent.com/48427415/79081197-2ba9e480-7ce9-11ea-98fb-be0fcd6649c4.png)

This is a line sample of approx. 500 word filters.

Removing all the word filters, then clearing cache and rebuilding theme. Things start working again.

![image](https://user-images.githubusercontent.com/48427415/79081300-1aada300-7cea-11ea-8806-64825361564e.png)

![image](https://user-images.githubusercontent.com/48427415/79081325-63655c00-7cea-11ea-950d-1ccefcb1b418.png)


Perhaps the subscribe section is acting up from the latest upgrade!!!

**Comment by harrison05** [comment]
Hi @hamadax 
I can answer your report 

> 2. In the admincp installed apps section, the app names are being censored.

We will fix this case, banned words shouldn't filter the app's name in AdminCP.

> 3. Subscription section stopped working.

We haven't met this issue yet, could you provide us more information (filtered words and their replacement...) or you can open browser console to see errors, then let us know.

Regards.

**Comment by harrison05** [comment]
> We will fix this case, banned words shouldn't filter the app's name in AdminCP.

This improvement is now available in phpFox 4.8.0.
