### ISSUE TITLE
Mobile App-Youtube videos

### ISSUE THREAD

**Issue by erick-1990** [PHPfox-Official/phpfox-v4-issues#2882]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When on mobile app, clicking on a youtube video takes you offsite.

## Steps to reproduce:
1. Click on a youtube video in mobile app.
2.  Video wont play on site
3. 

## What's expected?
YouTube videos wont play on site, takes you offsite.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

Mobile App -Android 

## Server information
(Example: CentOS 7, php 7.1 apache)

PHP Version 7.2.29

## phpFox version
(Example: phpFox 4.6.0)
4.7.10 
...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @erick-1990 

This isn't a bug. 
It's working as our design. Because Youtube doesn't allow play videos directly on Mobile App without their APIs, but the site owner must pay for that. So we open Youtube to play videos.

Regards.
