### ISSUE TITLE
Add Placement issue

### ISSUE THREAD

**Issue by Lupus71** [PHPfox-Official/phpfox-v4-issues#2887]
phpFox version 4.7.10

Aplication Ad
- When adding new placement, I choose any block for preview, but after clicking View Sample Layout, the block number 6 preview is always displayed.
- The whole page does not fit the screen, there is a problem with closing the page preview. You need to move the bar a bit at the bottom of the page with the mouse to close it.
![add placement](https://user-images.githubusercontent.com/13299029/80239125-f2b22e00-865f-11ea-8511-dad6fc6ca66d.png)

**Comment by harrison05** [comment]
HI @Lupus71 

Which version of Ad App you're using? Sample Layout always shows all placements that ad can be added.
![Screen Shot 2020-04-27 at 10 09 49](https://user-images.githubusercontent.com/41947198/80330506-8efe4f80-886f-11ea-939e-d995c6feee40.png)

Regards

**Comment by Lupus71** [comment]
I'm using version 4.2.7

**Comment by harrison05** [comment]
I think this bug only occurs on your site. Because I checked on some sites, it doesn't happen. You can submit a support ticket and we can check directly on it.

Regards.

**Comment by Lupus71** [comment]
I will.
Regards
