### ISSUE TITLE
Email addresses need to be converted to all lowercase on sign up before entering into database. Use strtolower or similar function.

### ISSUE THREAD

**Issue by hamadax** [PHPfox-Official/phpfox-v4-issues#2889]
# Important

Please follow this template!

----------------------------------------

## What's happened?
This is quite elementary. Before saving an email address to the database, force an PHP `strtolower` function on all email addresses used in sign up forms and anywhere else an email address can be entered by the user. Most phones and tablets capitalize the first letter when they cannot determine the type of form being filled. In this case, phones are not sensing a form type on the email form field during sign up so admin@example.com would go into the database as Admin@example.com and stays this way.

## Steps to reproduce:
1. I tested on Edge and Chrome on Android with both stock and swift keyboards.
2. I tested on Apple iPad with Safari and Chrome.
3. Sign up using a phone or tablet.
4. User can enter AdmIn@EXAmple.com or Admin@example.com (keyboard issue) when <input type="email"> is not defined in HTML. The database will save it this way. This is no good.

## What's expected?
before saving email addresses to databases, force an PHP `strtolower` function on all email addresses used in sign up forms and anywhere else an email address can be entered by the user.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @hamadax 

We will check and improve this. 

Thanks for your report.

**Comment by harrison05** [comment]
We improved this case in phpFox v4.8.0

Regards.
