### ISSUE TITLE
Banned usernames missing error/feedback message on sign-up

### ISSUE THREAD

**Issue by lethality** [PHPfox-Official/phpfox-v4-issues#2890]
## What's happened?
Pretty sure there's nothing I could have changed that's caused this, but I've added username and email filters. When matching a banned username, the signup page is displayed but there's no message as to what's wrong. When I tried and matched an email address, there was a red error message displayed above the form as expected.

## Steps to reproduce:
1. Add a username to ban filter eg. sexy
2. Register a user with an offending username, eg. sexy_person
3. Complete rest of user registration form and submit

## What's expected?
When the registration form is posted and you're brought back to it with errors, there should be an error on the page telling you that username cannot be used.

## Browsers and Devices tested
Google Chrome 80.0.3987.163 (Official Build) (64-bit), Windows 10 Pro.

## Server information
CentOS 7, php 7.3.17, Apache w/ Nginx

## phpFox version
PHPFox 4.7.10

**Comment by harrison05** [comment]
Hi @lethality 

> Add a username to ban filter eg. sexy

If you add only filter with value "sexy" and input username "sexy_person", filter system won't restrict that username, you should use the asterisk (*) for wildcard entries when add new ban word. Example: "sexy*"

I just checked and the filter still working correctly for username.

Regards.

**Comment by lethality** [comment]
Thanks, I can see that now and managed to get the error to display, something else is causing my registration to return to the same page then, I'll investigate more.
