### ISSUE TITLE
Issue in Photos app with Profile Pictures not showing up in Profile Albums

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2891]
----------------------------------------

## What's happened?
... I am using the latest 4.7.10 phpfox fresh install
I created a user via registration form, added a profile pic during signup. the profile pic shows next to the users name, BUT does NOT show when you click on the profile photo under Albums
 see photos below.

## Steps to reproduce:
1. create a user or even update any users profile photo
2. click on profile photo and it takes you to albums
3. when viewing the album for all your profile photos they are blank, when clicking on a profile album - photo the photo viwers shows up but does NOT show the profile photo, it just keeps spining and spining. 

this is a bug  can you please give us an update

## What's expected?
... you should be able to view all the profile photos you have uploaded 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...Chrome Latest version Version 81.0.4044.122 (Official Build) (64-bit)

## Server information
(Example: CentOS 7, php 7.1 apache)
centOS 7 php 7.3.17 nginx
...

## phpFox version
(Example: phpFox 4.6.0)

phpfox 4.7.10 fresh install
...

## Screenshots
...

![Capture1](https://user-images.githubusercontent.com/17736688/80458087-e6df9980-88f5-11ea-8d4d-b2925e2e4659.PNG)
![Capture2](https://user-images.githubusercontent.com/17736688/80458090-e7783000-88f5-11ea-9019-f6139751882a.PNG)
![Capture3](https://user-images.githubusercontent.com/17736688/80458092-e7783000-88f5-11ea-812f-9443406708ea.PNG)
![Capture4](https://user-images.githubusercontent.com/17736688/80458093-e7783000-88f5-11ea-988d-0bbc85181a55.PNG)

**Comment by spirogg** [comment]
ok i tried a few different photos and now it seems to work, ??
this was a fresh install so it was really weird. I will try again on my dev site to reinstall fresh 4.7.10 and try again to see if I have the same issue and report back

**Comment by lethality** [comment]
I had this issue, and when inspecting, was finding that the image location being used in the gallery was incorrect

**Comment by spirogg** [comment]
@lethality did it correct itself ? Or did you do something different to fix this ? Thanks

**Comment by harrison05** [comment]
Hi @spirogg 

This might a bug from the Photos app. We will check and inform you if have any updates.

Regards.

**Comment by lethality** [comment]
Just to offer some more info on this, as I've had new registrations replicating it (user has uploaded image but it doesn't display):
Source "data-image-src" = PF.Base/file/pic/photo/2020/05/fefc171b283d4f5ddeade0aa59ed4cef.png
"data-image-src-alt" = PF.Base/file/pic/photo/2020/05/fefc171b283d4f5ddeade0aa59ed4cef_1024.png

Actual image location is: PF.Base/file/pic/**user**/2020/05/fefc171b283d4f5ddeade0aa59ed4cef.png

My images that work are also in PF.Base/file/pic/user/*...
I'm not aware of any change or add-on that would be causing the path to be saved incorrectly.

**Comment by lethality** [comment]
Any progress or fix coming for this? It's quite a showstopper not having Photos display where people expect them.

**Comment by harrison05** [comment]
Hi, we fixed this bug and the new Photo 4.7.9 will be released soon.

Regards.

**Comment by spirogg** [comment]
> Hi, we fixed this bug and the new Photo 4.7.9 will be released soon.
> 
> Regards.

thanks @harrison05 much love

**Comment by lethality** [comment]
> > Hi, we fixed this bug and the new Photo 4.7.9 will be released soon.
> > Regards.
> 
> thanks @harrison05 much love

You able to change display photos? I created a new user, initial on-registration avatar has saved and displays fine, fixing above issue, but I'm unable to change that image afterwards, it's not even making it to the server.
