### ISSUE TITLE
wrong plugin in newsletter

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2894]
## What's happened?

function __call in newsletter service uses wrong plugin "notification.service_notification__call". it is also wrong in process and callback.

## phpFox version
Newsletter 4.6.1

**Comment by PhpFoxJohnJr** [comment]
I thought going to apps would make bug fixing faster?  Asked on April 30 and responded on May 5 and now it is October?

**Comment by spirogg** [comment]
@harrison05 has this been fixed ?

**Comment by harrison05** [comment]
This bug was fixed in Newsletter v4.6.2.

Regards.
