### ISSUE TITLE
IM app not working with Android app

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2895]
# Important

Please follow this template!

----------------------------------------

## What's happened?
IM app not working with Android app.

## Steps to reproduce:
1.  I login the app
2. Click on im/chat button on bottom bar
3. It's not loading
4. I click terms link on menu section site loading in app browser
5. After that the chat section loading and i get notifications about messages in a certain amount of time.

## Server information
PHP7.3
Redis
Nodejs

...

## phpFox version
phpFox 4.7.10

Also i check it with v4.phpfox.com domain too.

**Comment by david-phpFox** [comment]
This issue was fixed in Mobile 1.7.0
