### ISSUE TITLE
Restful-API: parameters for "POST /user" and "PUT /user/custom" undocumented

### ISSUE THREAD

**Issue by daniol** [PHPfox-Official/phpfox-v4-issues#2898]
## What's happened?
Try to use the Restful API to create users for migrate a old user database into phpfox. The parameters are not documented. It took me hours to find it expects the following syntax as with the method "PUT". So the user array looks like this:

```
    $user=array(
        'val'=> array(
           "user_name"=>"test",
           "full_name"=>"Test user",
           "email"=>"test@test.com"
           "gender"=>1,
           "title"=>"User title"
           //...
         )
    );
```

In the PUT example, however, there are not all parameters documented (for example, "birthday_search", "is_friend", ...

It is also not documented:
* How to establish friendship relation with two users
* Update custom fields (request not documented: what should be supplied on the "custom" array?)
* How to upload the profile image (sending a file named "image" with multipart/form-data is not working)

## Steps to reproduce:
1. Using PHP and CURL, post to http://localhost/index.php/restful_api/user, trying to figure how to provide the user object for the request.

## What's expected?
API documentation is complete and with working examples (for request and response)

## Server information
php 7.3.17, apache2, Windows

## phpFox version
phpFox  4.7.10

**Comment by harrison05** [comment]
HI @daniol 

You can find out all Restful API document of phpFox at https://docs.phpfox.com/display/FOX4DEVDOC/API and it sperate to each section (user, friend, blog ...). APIs only support some common features, not for all features of phpFox.

Regards.
