### ISSUE TITLE
From E-Mail in Contact Module

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2900]
Hi,

the From E-Mail Address in the contact module is almost the configured From E-Mail in the Module.

So, If I want to answer the Person who are Contacted me, I answer to our own E-Mail Address. Then I have to put the Users Mails vom COntent, and add it to the E-Mail Client To Field.

Please add a configuration, that site admins can check, the from E-Mail Address (The Users one, or the own one).

**Comment by harrison05** [comment]
Hi @Bjoern3003 

> the From E-Mail Address in the contact module is almost the configured From E-Mail in the Module.

A contact email will be sent to "Staff Emails" list, could you explain more about your request? Any screenshots might helpful. 

Regards.

**Comment by Bjoern3003** [comment]
Sure, the TO is correct, but the FROM... Try it by yourself and send a mail by the contact form. Then reply in your client. You will reply to your own e-Mail Address and not to the user, who has used the contact form.

**Comment by Bjoern3003** [comment]
Hi, any updates here? This should be a small fix.

It is annoying every day to enter the recipient in the TO field when someone contacts us.

**Comment by harrison05** [comment]
Hi @Bjoern3003 

> Sure, the TO is correct, but the FROM... Try it by yourself and send a mail by the contact form. Then reply in your client. You will reply to your own e-Mail Address and not to the user, who has used the contact form.

Ok, I got this, we will check and improve it soon.

Regards.
