### ISSUE TITLE
Issue in Hide Polls on Feed Entry

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2903]
If we hide the vote by set the setting in the poll himself, the Answers are visible in the Feed Entry.

To fix this, go to PF.Site/Apps/core-polls/views/block/feed-rows.html.php on Line 54 and replace it with

`<a href="javascript:void(0);" class="item-vote-number" {if isset($aPoll.answer) && count($aPoll.answer) && !isset($bDesign) && $aPoll.total_votes > 0 && ((Phpfox::getUserParam('poll.can_view_user_poll_results_own_poll') && $aPoll.user_id == Phpfox::getUserId()) || Phpfox::getUserParam('poll.can_view_user_poll_results_other_poll')) && (Phpfox::getUserParam('privacy.can_view_all_items') || $aPoll.hide_vote != '1' || ($aPoll.hide_vote == '1' && Phpfox::getUserId() == $aPoll.user_id))}onclick="$Core.box('poll.pageVotes', 900, 'poll_id={$aPoll.poll_id}'); return false;"{/if}>{$aPoll.total_votes|short_number} {if $aPoll.total_votes == 1}{_p('poll_total_vote')}{else}{_p('poll_total_votes')}{/if}</a>`

**Comment by harrison05** [comment]
This is a bug, we will check and fix it.

Thanks for your report.

**Comment by spirogg** [comment]
@harrison05 is this fixed in 4.8.3 ?

**Comment by harrison05** [comment]
@spirogg , we fixed it in Poll App version 4.7.2
