### ISSUE TITLE
Chat Plus not supporting specialchars

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2905]
![27052020163216](https://user-images.githubusercontent.com/13675579/83033669-afb8f100-a037-11ea-941f-b8fbf4b1a786.jpg)

![27052020163401](https://user-images.githubusercontent.com/13675579/83033868-ee4eab80-a037-11ea-865f-11363991b33e.jpg)

![27052020163419](https://user-images.githubusercontent.com/13675579/83033878-ef7fd880-a037-11ea-9a7f-0e7b5cfcd0f5.jpg)

and so on...

**Comment by harrison05** [comment]
Hi @Bjoern3003 

We will check and fix this issue if it's a bug in our source code.

Regards.

**Comment by harrison05** [comment]
Note: Please follow our issue template when you post a new topic (https://github.com/PHPfox-Official/phpfox-v4-issues/blob/master/ISSUE_TEMPLATE.md) it will help us to reproduce and detect issue quickly.
