### ISSUE TITLE
History Back in the Feed

### ISSUE THREAD

**Issue by Bjoern3003** [PHPfox-Official/phpfox-v4-issues#2906]
The Page is not loading the last position, where I was, if I click in the Feed on any entry. For example a Group.

The Page is reloading the complete Website, after using the history Back Button in my Browser and is going to top (not to my last position).

**Comment by harrison05** [comment]
Hi @Bjoern3003 

We will discuss to find a solution for this case and inform you if we have any updates.

Regards.
