### ISSUE TITLE
Forgot password process is frustrating users

### ISSUE THREAD

**Issue by jwpwhite** [PHPfox-Official/phpfox-v4-issues#2910]
## What's happened?
The forgot password procedure is different to what most people expect and this results in confused and frustrated users. Here is the current process:
1. User requests password to be reset via Forgot Password and is sent an email asking to confirm the password reset
2. The link in the email the user receives triggers the password to be reset but the link opens into a login page with no information about what has just happened and what the user needs to do next. If users read the reset email carefully, they would be fine but in reality nobody reads the email and just expect to know what will come next of be guided as to what comes next...
3. This lack of info and then confusion results in users submitting a second password reset. This cascades into multiple emails and even more confusion.

I cannot think of another a platform that follows the same forgot password procedure as phpFox so I really think it needs to be tweaked to iron out this issue.

## Steps to reproduce:
1. Download phpFox app from Apple App Store
2. Create account or login with existing account
3. Logout of the app
4. Tap on Forgot password, enter email address and submit

## What's expected?
There are two solutions:
1. The reset password link in the forgot password email sent to the user should open on a page and allow the user to enter a new password. This is a pretty standard approach which most platform use so it is exactly what users are expecting (This is a very good thing as it prevents user frustration). It is also a single step process as the user just need to add a new password rather than logging in with a temp password and then changing the password...
2. The second solution is for the reset password link in the email sent to the user to open on page the tells them what they need to do next. E.g. "Thanks for confirming that you forgot your password and want your password reset. We have emailed you a new password to this email address". By taking this approach, the user is told exactly what they need to do next. Rather than wonder why they have been presented with a login screen as with the current process...

## Browsers and Devices tested
All browsers and devices

...

## Server information
phpFox demo servers

...

## phpFox version
Whatever phpFox version phpFox is running for the demo

**Comment by harrison05** [comment]
Hi @jwpwhite 

I can't reproduce this case as your step, because "Change Password" feature doesn't send email to users, it just check old password and new password, then updates if they passed.

You're talking about the "Forgot password" feature, don't you?

Regards.

**Comment by jwpwhite** [comment]
Hi @harrison05 
Apologies, it is the Forgot Password process that I am talking about. 
I have amended my description above.
Cheers
John

**Comment by jwpwhite** [comment]
Hi @harrison05
Any updates on the above?

**Comment by harrison05** [comment]
Hi @jwpwhite 

Sorry for the delay in getting back to you. About forgot password process, you can shorten it by enabling setting: 
**Shorter Password Reset Routine** - If this is enabled when a user clicks on Forgot your password he will receive an email with a link, when clicking on the link he will be shown an input where to change the password. The site will not assign a new password to that user and the previous password will work until it has been reset.

Regards.

**Comment by jwpwhite** [comment]
Great, thanks @harrison05
