### ISSUE TITLE
Epileptic effect on start page

### ISSUE THREAD

**Issue by daniol** [PHPfox-Official/phpfox-v4-issues#2914]
## What's happened?
The home page of phpfox does an epileptic effect on some tablet resolutions, for example 800x1280. The content starts to shake. See attached video.

I've found this happens with resolutions with a width from 768 to 990. Resizing it smaller oder larger, stops the effect.

I am using the default "material" theme, not changed in any way. I think it has something to do when using recaptcha (v2) and facebook login at the same time.

## Steps to reproduce:
1. Open homepage (user not logged in)

## What's expected?
Normal responsive layout, without any annoying effect.

## Browsers and Devices tested
Firefox 77.0.1, Windows 10 x64
Chrome 83.0.4103.106, Windows 10 x64

## phpFox version
phpFox 4.7.10

## Screenshots
See attached video: 
[phpfox-epileptic.zip](https://github.com/PHPfox-Official/phpfox-v4-issues/files/4808365/phpfox-epileptic.zip)

**Comment by harrison05** [comment]
Hi @daniol 

We will check this case. If it's a bug from our template we will fix it.

Regards.
