### ISSUE TITLE
Warning about external link on embed videos

### ISSUE THREAD

**Issue by daniol** [PHPfox-Official/phpfox-v4-issues#2915]
## What's happened?
When activating the setting "External Links Warning", it is also displayed when clicking on an embed video (for example when a user posts a Youtube link as a status).

## Steps to reproduce:
1. Activate the setting "External Links Warning"
2. Share a Youtube video as status
3. Click on the thumbnail of the video to play
4. A "external link" warning is displayed

## What's expected?
No warning

## phpFox version
4.7.10

**Comment by harrison05** [comment]
Hi @daniol 

You can see in the description of "External Links Warning" setting is **"Warn users when they have clicked on a link that will direct them to another site."**. So, if you share a link as Status and click on it, this setting will trigger and show a warning. If you share a YouTube link as Video, then click on video embed, this setting won't trigger, just play video.

Regards.

**Comment by daniol** [comment]
Hi @harrison05 :

Unfortunately that's what is happening: 

If you share a YouTube link as Video and click on video embed (image thumbnail), the video will be played **AND** the link warning will be displayed at the same time.

That does not work as designed, it's a bug.

**Comment by harrison05** [comment]
Hi @daniol 

We can't reproduce this issue on our side. When clicking on Youtube video embed on feed, it just plays video.
You can submit a ticket in the client area, our team will help you check it on your site.

Regards.
