### ISSUE TITLE
updated to 4.8 from 4.7.10 shoutbox issues

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2916]
----------------------------------------

## What's happened?
...
after update to 4.8 shout box is not align and also you can not edit delete messages even though in settings we have option ON to edit delete messages 

see photos below

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...
should work

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome latest version

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php 7.3 apache

## phpFox version
(Example: phpFox 4.6.0)

...
4.8 
## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/86490686-def50900-bd2d-11ea-8cea-d8d44022f8cd.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/86490687-df8d9f80-bd2d-11ea-9c90-f061b0e23958.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

This issue occurs because Shoutbox v4.3.2 doesn't compatible with phpFox 4.8.0. 
New version 4.3.3 will release soon in the next few days and this issue will be fixed.

Regards.

**Comment by daniol** [comment]
Why do you release a new version without updating and releasing first all apps? This is not a beta!
