### ISSUE TITLE
Update from 4.7.10 to v4.8 completed, but displays file not found everywhere except the root index

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2917]
# Important

Please follow this template!

----------------------------------------

## What's happened?
updating from v 4.7.10 to v4.8  completed, but displays file not found everywhere except the root index. 

## Steps to reproduce:
1. upload
2. confirm update prompts
3. update complete. view site 

the home page displays fine, but everything else just displays file not found including adminco

## What's expected?
Should display any part of the site

## Browsers and Devices tested
 Chrome on Windown 10, Firefox

...

## Server information
(CentOS 7, php 7.2 apache)

...

## phpFox version
phpFox 4.7.10

...

## Screenshots
...

**Comment by spirogg** [comment]
Hi @prepperz did you check .htaccess file or check To see if you had short urls enabled ? 
Possibly htaccess file not having the correct information for short urls ?

**Comment by prepperz** [comment]
.htaccess is not used.

Weird, I've never enabled short url, but taking a look at the setting it's says it's enabled and there's no option to disable it.

![Screenshot](https://user-images.githubusercontent.com/19594886/86572401-e3454000-bf40-11ea-94f1-b005b582d373.png)

**Comment by harrison05** [comment]
Hi @prepperz 

> Weird, I've never enabled short url, but taking a look at the setting it's says it's enabled and there's no option to disable it.

It occurs because Short URL is enabled but missing .htaccess file or this file has an invalid configs. 
You can disable Short URL by edit  **../file/settings/server.sett.php** and change $_CONF['core.url_rewrite'] value from **'1'** to **'2'**

Regards.

**Comment by prepperz** [comment]
@harrison05 perhaps it'd be a good idea to include an option to disable short urls in the admincp

**Comment by harrison05** [comment]
> @harrison05 perhaps it'd be a good idea to include an option to disable short urls in the admincp

Hi @prepperz , we won't support this feature. Admin must control it with .htaccess and server.sett files.
