### ISSUE TITLE
CDN stops working

### ISSUE THREAD

**Issue by maniacscorpio** [PHPfox-Official/phpfox-v4-issues#2918]
# Important
i am using bunnycdn since last many months & it was working perfectly but when i upgraded to 4.8.0. it stops working. Even i try keycdn it also not working..   As per Bunnycdn customer care  you need to speak to the script creators about, because it appears to just stop rewriting URLs to the CDN. 
-

## What's happened?
...

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.8.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @maniacscorpio 

Can you explain more about this issue? Where did you configs Bunnycdn? step to reproduce or any screenshots might helpful. Or you can submit a ticket in client area, our team will check directly on your site.

Regards.

**Comment by maniacscorpio** [comment]
Ticket is submitted .. Nether BunyCDN nor KEYCDN is working after 4.8.0 upgrade..  Needs immediate solution because my website becomes very slow.. I am using the CDN since last many moths it was working perfectly-

i configured Bunnycdn or keycdn in bellow settings pages and it was working perfectly before update .. 

1. admincp/setting/edit/?module-id=PHPfox_CDN_Service#pf_cdn_service_enabled

2. admincp/setting/edit/?module-id=core#allow_cdn

3. admincp/setting/edit/?module-id=core#push_jscss_to_cdn

4. /admincp/setting/assets/manage/


Kindly check the issue in your demo 4.8.0 version..

Thanks & Regards

**Comment by harrison05** [comment]
Hi @maniacscorpio 

This is a bug with CDN Url of Assets Handling, we will fix it. 
About your ticket, our team will handle it soon. Please follow it.

Thanks for your report.
