### ISSUE TITLE
Groups App - Privacy issue

### ISSUE THREAD

**Issue by sryn101** [PHPfox-Official/phpfox-v4-issues#2920]
What's happened?
Unable to set privacy to a post on groups. 

## Steps to reproduce:
1. Join a group and write something on the post
2. There is no option to set privacy, Let's users want to share it with their own friends only. 

## What's expected?
There should be an option to set privacy, there are required database field, but it is not shown on UI, so considering it as bug

## Browsers and Devices tested
Chrome on PC
...

## Server information
php 7.1 apache

...

## phpFox version
 phpFox 4.8.0

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @sryn101 

I can confirm this is not a bug, it's business rule of groups. Privacy of your post on Group will base on group privacy, we have 3 types: 

![Screen Shot 2020-07-08 at 14 24 33](https://user-images.githubusercontent.com/41947198/86890304-4d1f3e80-c127-11ea-9e1c-b75e4349df5b.png)

Regards.
