### ISSUE TITLE
Spam configuration is not working correctly. 

### ISSUE THREAD

**Issue by sryn101** [PHPfox-Official/phpfox-v4-issues#2921]
## What's happened?
Many users are posting duplicate messages but still not flagged as spam 

## Steps to reproduce:
1. Set spam configuration message count to 5
2. Post the same message in multiple places more than 5 times
3. Those messages are still active and not considered as spam

## What's expected?
Spam messages should be flagged

## Browsers and Devices tested
 Chrome on PC
...

## Server information
 php 7.1 apache

...

## phpFox version
phpFox 4.8

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @sryn101 

> Set spam configuration message count to 5

Which setting did you set this value?
![Screen Shot 2020-07-15 at 09 24 13](https://user-images.githubusercontent.com/41947198/87496039-f52f8d00-c67c-11ea-8c59-2c93eb3be241.png)
Please read those settings description (my screenshot) and make sure you understand their uses.

Regards.
