### ISSUE TITLE
Shorter Password Reset Routine not working correctly

### ISSUE THREAD

**Issue by sryn101** [PHPfox-Official/phpfox-v4-issues#2922]
What's happened?
When "Shorter Password Reset Routine" config is enabled, users get an option to provide new password directly, but when they try to login with new password, it doesn't work. However, when this setting is not enabled, they get an auto generated password which works fine. 

## Steps to reproduce:
1. Enable"Shorter Password Reset Routine"
2. Click on forget password
3. You will receive an email to reset password 
4. Provide new password and save it. 
5. Try to login with new password, it doesn't work. 

## What's expected?
"Shorter Password Reset Routine" enabled should work correctly. 

## Browsers and Devices tested
Chrome on PC

...

## Server information
 php 7.1 apache

...

## phpFox version
phpFox 4.8

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @sryn101 

We can't reproduce this issue on our side. Please submit a ticket in client area if it still occurs on your site. Our team will help you check it directly.

Regards.
