### ISSUE TITLE
Mobile app - Images file names are seen as image names 

### ISSUE THREAD

**Issue by sryn101** [PHPfox-Official/phpfox-v4-issues#2925]
What's happened?
Image "FILE" names are seen as image names all over, eg., if my file name is IMG_20200501_1234123.jpg and image label is "New york", instead of showing new york, it shows IMG_20200501_1234123.jpg

## Steps to reproduce:
1.  Upload an image on mobile app
2. Let some one comment on it. 
3. When a notification is generated, it says User XYZ commented on your photo  IMG_20200501_1234123.jpg instead of saying "New york "

## What's expected?
Image name or label should be seen instead of file name. 

## Browsers and Devices tested
Android Mobile app

...

## Server information
php 7.1 apache

...

## phpFox version
phpFox 4.8.0

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @sryn101 

When you upload a photo on Mobile App, it will set the file name as photo name after uploading. You can change its name when editing this photo.

Regards.
