### ISSUE TITLE
Instant messaging app sound notifications

### ISSUE THREAD

**Issue by sryn101** [PHPfox-Official/phpfox-v4-issues#2926]
What's happened?
Sound notifications are not working on instant messaging app after upgrade

## Steps to reproduce:
1. Upgrade IM app on PHPFox 4.8.0
2. When someone responds to chat earlier we were getting sound notification
3. Now there is no sound notification

## What's expected?
When someone responds sound notification should be generated 

## Browsers and Devices tested
Chrome on PC

...

## Server information
php 7.1 apache

...

## phpFox version
 phpFox 4.8.0

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @sryn101 

This issue doesn't occur on our site, please make sure you don't **Turn off notification** of conversation with your friend.
You can submit a ticket, we will handle it on your site.

Regards.

**Comment by sryn101** [comment]
Hi @harrison05 ,

I have submitted a ticket and I was able to reproduce this on demo PHPFox site as well. - https://mobileapi.phpfox.com/ 

I am summarising the issues here: 
 1) Earlier (before upgrading to 4.8.0) we were getting default sound
notification on website whenever we received a message notifications, that's
not there any more, I tried with both default and uploading custom sound.
2) Messages don't get updated automatically on IM chat app on website unless we refresh the webpage.
Please check at the earliest.
3) When a message is "READ" it still shows up as unread on website, we can
still see number of messages marked in RED.

**Comment by harrison05** [comment]
Hi @sryn101 

We will check and respond to you on your ticket soon. I will close this topic now, please follow your ticket.

Regards.
