### ISSUE TITLE
Banned users can still chat

### ISSUE THREAD

**Issue by sryn101** [PHPfox-Official/phpfox-v4-issues#2929]
What's happened?
I had a banned a user, but he is still able to chat with me

## Steps to reproduce:
1. Ban a user 
2. Message him on Instant message
3. He replies back

## What's expected?
Banned user shouldn't be able to login, get notifications or do any activity on website or mobile app

## Browsers and Devices tested
Android App
...

## Server information
php 7.1 apache

...

## phpFox version
phpFox 4.8.0

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @sryn101 

When a user is banned, he can't log in (and be forced to log out) on both website and mobile app. So he can't access chat. This is the current workflow of Ban User feature.

Regards.

**Comment by sryn101** [comment]
Hi @harrison05  I had raised a Ticket with ID: 808224 for support to check it on site, and I was told that banned users are not getting forced logged out, so shouldn't this be considered as bug?

**Comment by harrison05** [comment]
Hi @sryn101 

We improved this case on Mobile app, if user is banned, they will be forced logout from app.

Regards.
