### ISSUE TITLE
Sharing comment  from page status no longer work

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2930]
## What's happened?
Sharing to pages status to your wall no longer work.

## Steps to reproduce:
1.  click the Share icon of any status pages status and share it to your wall.
2. 
3. 

## What's expected?
It should display on your wall

## Browsers and Devices tested
chrome
...

## Server information
(CentOS 7, php 7.2 apache)

...

## phpFox version
(Updated to phpFox 4.8.0)

...

## Screenshots
...
![Screenshot](https://user-images.githubusercontent.com/19594886/87241693-a6bb8d80-c3f3-11ea-8034-1ac281ccd4bd.png)

**Comment by harrison05** [comment]
Hi @prepperz 

This is a bug from Comment Apps. We will check and fix it

Thanks for your report.
