### ISSUE TITLE
IM keepalive issue

### ISSUE THREAD

**Issue by Ylmzef** [PHPfox-Official/phpfox-v4-issues#2934]
After a few minutes of inactivity the connection drops with nodejs server.
Is there any keepalive settings for im server?

**Comment by harrison05** [comment]
Hi @Ylmzef 

How long you inactive on your site then it happens?

**Comment by Ylmzef** [comment]
3 min or like that

**Comment by harrison05** [comment]
Hi @Ylmzef 

We don't meet this issue on our side. You can submit a ticket, our team will check directly on your site.

Regards.
