### ISSUE TITLE
Disabling site wide ajax will impact on photos navigation

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2935]
## What's happened?
I don't want to use site-wide ajax on my website. But when I disable it, the navigation with arrows and thumbs on photos is no longer available.

## Steps to reproduce:
1. Disable site-wide ajax
2. Click on a photo in the photo section and you are stuck on that photo, you can't navigate to other photos

## What's expected?
I expected that after disabling site-wide ajax I still be able to navigate through photos.

## phpFox version
4.8.0

**Comment by harrison05** [comment]
Hi @turha71 

Currently, thumbnails list in detail only support when you view photo which belonging to an album, a feed, or redirect via ajax mode from the listing page. If you disable ajax mode, we can't get related photos from previous page because it loads a new page.

Regards.
