### ISSUE TITLE
V4.8  Registration approval steps bypassed by spam members

### ISSUE THREAD

**Issue by torontoguy** [PHPfox-Official/phpfox-v4-issues#2936]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...On a fresh install of V4.8  where the registration procedure includes the requirement to approve members, spam signups are able to bypass the membership approval process.     The reason I know this is a V4.8 issue is because if I install V4.7.10 it doesn't happen and then if I upgrade that version to 4.8 it doesn't happen.   It only happens on a FRESH install of V4.8

## Steps to reproduce:
1.   Install fresh version of  V4.8
2.   Set registration to  'approve members'
3.   Wait for a spam registrant

## What's expected?
...   Spam members will be able to fully register for the site without admin approval

## Browsers and Devices tested

 Has nothing to do with a particular browser
...

## Server information
Linux, VPS Cloud, PHP7.2.33,   at TMDHosting
...

## phpFox version
Phpfox 4.8

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @torontoguy 

We don't meet this issue. If it still occurs on your site, you should submit a ticket, our team will help you check it out.

Regards.

**Comment by torontoguy** [comment]
Thank you for following up on this.
It's really strange but I had the issue for three days running and then reported it..  Lo and behold not two days later all fake registration attempts have stopped...  not only on the one website I have using V4.8, but on all the websites using 4.8..   and I was averaging 5-10 fake registrations a day.
Go figure..    Anyway.. I am pleased.

terry
