### ISSUE TITLE
After upgrade, no widgets found for existing widgets.

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2937]
## What's happened?
I am not sure if it's v 4.8 or 4.8.1 as I didn't  check for this in 4.8, but the existing widgets are no longer listed from the pages admin menu.

## Steps to reproduce:
1. Goto any pages with an existing widget.
2. Click on the pages gear, manage and then widget and it will display no widgets list.

## What's expected?
It should display a list of existing widget.

## Browsers and Devices tested
Chrome on Windown 10

...

## Server information
CentOS 7, php 7.2 apache

...

## phpFox version

 phpFox 4.8.1 upgraded

## Screenshots

![Screenshot](https://user-images.githubusercontent.com/19594886/92335866-333ba280-f069-11ea-9309-ae7ca365bbeb.png)

**Comment by harrison05** [comment]
Hi @prepperz 

We don't meet this issue on our side. 
Did you try to add a new widget? Is it still disappear?

**Comment by prepperz** [comment]
All the old widgets for pages and groups are not found, but it's still there on the front end.  When I create a new widget, it shows up shows up, but not the old ones on the backend, I also noticed that when creating a widget it was also missing options for what type of content it is as well.

![Screenshot](https://user-images.githubusercontent.com/19594886/92735459-6cb12e00-f347-11ea-912d-d121cc3e5793.png)

**Comment by prepperz** [comment]
It seems other site owners are also experiencing the same issue as well.

**Comment by harrison05** [comment]
Hi @prepperz 

I can inform you this is an improvement of Pages and Groups apps. With the old version, when you add a new widget, you can set it is a Block or Menu (Field **Is Block?** in add widget form - This field was removed in new version). But after upgrade to the newest version, we separate it into 2 sections:
- **Widgets**: all old widgets with Is Block = Yes will show up here. If you add a new item from this section -> It will be a Block
- **Menus**: all old widgets with Is Block = No will show up here. If you add new item from this section -> It will be a Menu

![Screen Shot 2020-09-16 at 09 36 11](https://user-images.githubusercontent.com/41947198/93285888-1e48d700-f800-11ea-8261-affd4b62543d.png)

Regards.

**Comment by prepperz** [comment]
Ah ok.
