### ISSUE TITLE
Home icon disappear after adding url

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2938]
## What's happened?
When I edit the home menu and add to the URL (that is blank) the URL of my site (http://www.mysite.com) the home icon disappears and only shows the home word. I need to add this full URL to the URL field because I don't want the main page of my site to open using ajax and the only way of doing this, without disabling site wide ajax, is to add the full URL of the page. 

## Steps to reproduce:
1. Edit home menu
2. Add full url of your website to the url field that is blank
3. you will see that the home icon disappear and only show the word "home" on the menu

## What's expected?
I expected that after adding the full url of the website to the URL field, to make that page open without ajax, the home icon to show, but it only shows the "home" word.

## phpFox version
4.8.1

**Comment by harrison05** [comment]
Hi @turha71 

Home icon only appears if the first menu has an empty URL.

Regards.

**Comment by turha71** [comment]
Hi Harrison,

Could you help me to find the file and lines of code that controls this, so I can change it and make it work the way I need?

Thanks

**Comment by harrison05** [comment]
Hi @turha71 

You can find its source code at **PF.Site/flavors/material/html/core.block.template-menu.html.php**, line 68

Regards.

**Comment by turha71** [comment]
Thanks!
