### ISSUE TITLE
Page App: Adult Images show in Home Feed to guests even when set not to.

### ISSUE THREAD

**Issue by torontoguy** [PHPfox-Official/phpfox-v4-issues#2939]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When creating a page with adult images and adult images set to 'hard warning',  the 4 samples that show up in the feed when viewed by someone who hasn't logged in and is a 'guest' show one adult image in the frame that shows how many other images are in the posting.     (The image set to hard adult warning is normally not shown to guests because it is restricted by age )

## Steps to reproduce:
1. Create a page
2.  Upload images at least 6 or more 
3. Set at least 5 images to 'hard warning adult'

## What's expected?
...If you use any browser to look at the page and it goes to the home page feed for the page,  there will be a feed summary of 4 images...  the 4th image which shows how many more images there are in the posting, although it has been marked as adult, is showing as a normal image.

## Browsers and Devices tested
Firefox, Edge, Chrome, Opera

...

## Server information
Linux  VPS service

...

## phpFox version
 phpFox 4..8.0

...

## Screenshots
  This is the home page, wall:  https://www.thisaintjane.com/index.php/diesel/
Shows an adult image in the feed posting

And this is the photos page:   https://www.thisaintjane.com/index.php/diesel/photo/
Shows no adult images  as should be the case

**Comment by harrison05** [comment]
Hi @torontoguy 

We will check and fix this bug.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Make sure to check to see if this is on the Group App as well as they both share the same table and probably some remaining code.
