### ISSUE TITLE
photo group settings > music wording in photo group settings need to be removed and add back photo wording  instead 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2940]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...this is photo settings and photoapp group settings not music settings, the wording needs to change from music to photos see bold wording below....

Flood control photos
5
How many minutes should a user wait before they can upload another batch of photos? Note: Setting it to "0" (without quotes) is default and users will not have to wait.

refresh_featured_photoHow many minutes or seconds the script should wait until it refreshes the feature photo?
1 min
Define how many minutes or seconds the script should wait until it refreshes the feature photo. Notice: To add X minutes here are some examples: 1 min 2 min 30 min If you would like to define it in seconds here are some examples: 20 sec 30 sec 90 sec

maximum_image_width_keeps_in_serverMaximum image width keeps in server (in pixel)
1200
If image width user upload higher than this value will crop to this value.

can_sponsor_albumCan members of this user group mark a **music album** as Sponsor without paying the fee?
can_purchase_sponsor_albumCan members of this user group purchase a sponsored ad space for their **music albums**?
photo_album_sponsor_priceHow much is the sponsor space worth for photo albums? This works in a CPM basis.
$
0

can_feature_photo_albumCan feature a photo album?
auto_publish_sponsored_albumAuto publish sponsored **music album**?
After the user has purchased a sponsored space, should the **music album** be published right away? If set to No, the admin will have to approve each new purchased sponsored **music album** space before it is shown in the site.

## Steps to reproduce:

1. go to admincp
2. click on apps >Photos > ussergroup settings ( check all wording)
3.  remove music and add photos instead the wording is suppose to say **photos** not music 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.8.1 fresh install

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

This issue occurs because setting phrase name of 2 apps was override each other. We will improve to make sure it doesn't appear with a new installation. 

Regards.

**Comment by spirogg** [comment]
@harrison05 thanks
