### ISSUE TITLE
upload a new video, then Email when ready does not show title ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2943]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... 

when user uploads new video, they get an email saying the video is ready to view, in the email it doesn't show the video title

 
it should show  EXAMPLE: /video/play/31/coffee-pot-brewing/

instead it only shows EXAMPLE: /video/play/31/

How can we add the title at the end so it is like all other emails /video/play/31/title_to_video

## Steps to reproduce:
1. upload a video (add title description)
2. wait for video to upload and process
3. go to your email and view email sent that says your video is ready
4. see it doesn't show you the title

## What's expected?
... It should show the title at the end of the link just like other notification emails, when you like or comment on videos and photos the email shows the title at end of link.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome

## Server information
(Example: CentOS 7, php 7.1 apache)

...nginx php-fpm

## phpFox version
(Example: phpFox 4.6.0)

...4.8.1 fresh install

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

We will improve it.

Regards.

**Comment by harrison05** [comment]
Hi @spirogg 

We improved it in the newest version of Videos App - 4.7.9

Regards.
