### ISSUE TITLE
when in admincp you have set can edit photos to NO for a UserGroup, The UserGroup can not add a title or description to photo ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2944]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
when in admincp you have set can edit photos to NO for a UserGroup, The UserGroup can not add a title or description to photo when uploading ?
## Steps to reproduce:
1. As admin go to admincp> manage usergroups 
2. select registered user and photo
3. find can edit photos and set to NO
4. then login as registered user and Go to photos and click upload photo you will see there is no option to add title and description
## What's expected?
...
you should be able to add title and description to photo even though after you won't be able to edit the photo.
otherwise the photo will take whatever the name of the file is on users computer or mobile and look horrible on website.
- We Need to allow users to add title description and add category - even if we select user cannot edit photo afterwards, initial upload should have these options to add title desc and select category for photo to be added too.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome

## Server information
(Example: CentOS 7, php 7.1 apache)

... centOS 7 nginx php-fpm

## phpFox version
(Example: phpFox 4.6.0)

4.8.1 fresh install
...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

We will check this case.

Regards.
