### ISSUE TITLE
@harrison issue is AJAX - when view feed and scroll down a a little if you try to click on logo it doesn't take you back to top of feed ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2949]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...

when you view feed and scroll down till you see the load more spinning and next section shows in feed, then try to click on logo it doesn't take you back to top of feed ? you stay at the load more section of feed ? 

THS HAPPENS ONLY WHEN YOU:
- Scroll passed the second section (_scroll down to see more_) 
- twhen if you click on the logo you will be directed back to the load more section of feed. see photos

## Steps to reproduce:
1. sign in and click home page Icon
2. scroll down till you see the load more spinning and next section shows in feed
3. then try click on your logo 
4.you will go back to the load more section of the feed. 

## What's expected?
...

anytime you click on your logo you should be put back to the top of the home page feed, but for some reason it keeps you at the load more section of feed. ??

- tested on your demo site also. 
- but if you can find a way to click on the home icon - only then do you go back to the top of the feed
- or if you click 2 or more times really fast on your logo

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...all broswers

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 nginx - php 7.2 7.3 7.4

## phpFox version
(Example: phpFox 4.6.0)

...4.8.1 fresh install

## Screenshots
...
![home](https://user-images.githubusercontent.com/17736688/96853818-6de27a00-1420-11eb-85eb-f0fe13d84c56.PNG)

![stuck-middle](https://user-images.githubusercontent.com/17736688/96853823-6e7b1080-1420-11eb-8067-9c1d05d87437.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

This might an issue. We will check it.

Regards.

**Comment by harrison05** [comment]
We fixed this issue in version 4.8.2.

Regards.

**Comment by spirogg** [comment]
> We fixed this issue in version 4.8.2.
> 
> Regards.

@harrison05 not working with upgrade from fresh install 4.8.1 then upgrade top 4.8.2
cleared cache 
removed files not used 
rebuilt theme 
not working after upgrade

also your installation for fresh install of 4.8.2 is not working right missing apps each install never a complete installation ?

ticket#168327 in clients area I just posted with photos, first fresh install marketplace video polls the second install was missing more apps - missing videos polls quizzes marketplace saved aso really weird

**Comment by spirogg** [comment]
@harrison05 I have fresh install of phpfox 4.8.2 in 2 seperate occasions

one is dev.mydomain.com
and the other fresh install 4.8.2 in mydomain.com

and both of them do not allow to go to the top when clicking on LOGO

also I have notice the same issue when in forums and photos and other areas , 

- when go to photos and scroll down then click on myphotos link or all photos link it also does not allow to go to the top
same with forums ?
what can be this issue it happens on my server both installations are fresh installs?

one is using nginx php fpm 7.4
and the other is using proxy apache and nignx php7.4

firefox browser and chrome browser latest versions on both browsers

- photos section same thing?
![Capture](https://user-images.githubusercontent.com/17736688/98642090-737e0200-22f2-11eb-97da-3cc6700175a4.PNG)

- forums section same thing?
![Capture](https://user-images.githubusercontent.com/17736688/98642196-a7592780-22f2-11eb-89fc-b258270efd61.PNG)

**Comment by spirogg** [comment]
I can click 100 times it won't bring it back to the top of feed, photo section forum section even the Visitors page if you scroll down and click on logo it stay at the bottom and does not go back to top

**Comment by spirogg** [comment]
@harrison05 same on your demo https://v4.phpfox.com/

![Capture](https://user-images.githubusercontent.com/17736688/98650981-42f09500-22ff-11eb-92bb-56bd209cbd09.PNG)

**Comment by spirogg** [comment]
@harrison 

**I found out when we disable Ajax this issue no longer exists...**  

**SO AJAX creates this issue.**
- Somehow we need to fix this - its really aggravating to have to scroll up to the top.

please find a way 

if you add  # at the end of domain like this > domain.com/index.php# 
then it works `but that would not be realistic for this case.`. 

- **but there has to be a way to make this work correctly with Ajax ON**

**Comment by harrison05** [comment]
Hi @spirogg 

This issue was fixed in the newest build of v4.8.2, you can download a new one (we just updated it) and check again.  
It also works on our demo site.

Regards.

**Comment by spirogg** [comment]
ok fixed thanks
