### ISSUE TITLE
when set usergroup to approve photos they can still add photos in comments on Feed ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2950]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
- It seems when in admincp we set usergroups > photos app
- they need approval from admin for uploading photos 
- they can still circumvent and upload photos in comments. in all apps including feed. 
can we make it to where approval for photos in this section as well? 

## Steps to reproduce:
1. go to admincp> apps> photos>set usergroups needs approval for upload photo
2. then go to any app and make a comment and add a photo, then you can also comment on comment and add a photo as well
3. You should not be able to add a comment - photo on feed if Photo needs approval from admin before show on website.

## What's expected?
...

I would think that they can't upload any photos because they need approval first?
this needs a fix please

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...all browsers

## Server information
(Example: CentOS 7, php 7.1 apache)

...CentOS 7 php7.3

## phpFox version
(Example: phpFox 4.6.0)

...4.8.1 fresh install

## Screenshots
...
![comment photos](https://user-images.githubusercontent.com/17736688/96973867-173b7580-14de-11eb-9497-f1fa523be2a1.PNG)
![comment photos1](https://user-images.githubusercontent.com/17736688/96973869-17d40c00-14de-11eb-9edb-25b3d13877e9.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

We will improve it.
If users add a photo in a comment and setting "Photos must be approved first before they are displayed publicly?" is enabled, their comment will be marked as pending and it only shows after admin approved.

Regards.

**Comment by spirogg** [comment]
excellent work 
works now 4.8.2
comments app 4.1.5
- **AGAIN GREAT WORK** @harrison05 
![Capture](https://user-images.githubusercontent.com/17736688/98797632-78b27e00-23d2-11eb-89f8-8d158551e13a.PNG)
