### ISSUE TITLE
when select photo upload needs approval and add photo & comment in feed - after approval the photo & comment does not show in feed?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2951]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...

**when** admin sets photo upload needs approval in admincp 
then a user adds a photo & comment in feed : after admin approved photo it doesn't show in feed ?

- When admin approves the photo, the photo & comment does not show in feed where it originated? only shows in photo app.

- **but** when a user adds a video & adds a comment in the feed section, 
-then admin approves the video - then the comment and video show in the feed.

**So I would think the same process would be needed for the photo / comment as well** 

## Steps to reproduce:
1. go to admincp? photos app and set need approval for upload photos
2. next go to admincp videos and set needs approval for upload videos
3. now sign in as user and try post a comment and photo in feed.
4. and then post a video (upload) and comment in feed.

5. now login as admin and go to photos and approve photo and then go to feed, nothing shows 

6. now go to video and approve the video then go to feed and see the comment and video show in feed

![Capture](https://user-images.githubusercontent.com/17736688/96975677-65517880-14e0-11eb-9135-e49708954ed0.PNG)

## What's expected?
...
**I believe the photo and comment you upload in feed should show in feed after admin approves it.**

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...all browsers

## Server information
(Example: CentOS 7, php 7.1 apache)

CentOS 7, php 7.3

## phpFox version
(Example: phpFox 4.6.0)

...4.8.1 fresh install

## Screenshots
...
![dalmation](https://user-images.githubusercontent.com/17736688/96975345-f411c580-14df-11eb-92df-9cafeedba4a7.PNG)
![popup in feed](https://user-images.githubusercontent.com/17736688/96975359-f70cb600-14df-11eb-8f0d-48c6a64ced2d.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/96975855-b3667c00-14e0-11eb-8d5e-b8bce102206e.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/96976011-e7da3800-14e0-11eb-9ed9-4dc8eea59535.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

Our tester informs us that they can't reproduce this issue with the current version of phpFox and Photos App. Please check it again with v4.8.2

Regards.

**Comment by spirogg** [comment]
I am trying to install fresh install but not getting all apps just tried 2 times. Plus my update not working as you suggest for this issue and another please check your servers. Something is wrong in your servers when we try to update and fresh install of 4.8.2

**Comment by spirogg** [comment]
ok downloaded 4.8.2 fresh install today 11/11/2020 and this is now working well..


**EXCELLENT JOB @harrison05** @phpfoxaccount TEAM

NOW THIS IS PERFECT😁😁😁😁😁😁😁😁😁😎😎😎😎😎😎😎

GREAT JOB YOU GUYS!!!!
