### ISSUE TITLE
when creating an event and adding photo it does not get the rule from admincp to 1200px its too big and needs to be cropped 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2952]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
when we add an event and add a photo the admincp setting does not crop the photo so its too big.
I have default settings in admincp for 1200 px. 

The same photo show perfect in photo app and when upoaded to feed section, but when added to event it's not cropped and is too big

## Steps to reproduce:
1. choose a photo and upload to photos app see photo size looks good 
2. now go create event and upload the same photo.
3. now go view the event and click on it and see photo is too big gets cut off

## What's expected?
...
 we should crop the photos equally for events also based on the settings we have in admincp

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...all browsers

## Server information
(Example: CentOS 7, php 7.1 apache)

CentOS 7, php 7.3

## phpFox version
(Example: phpFox 4.6.0)

...4.8.1 fresh install

## Screenshots
...
- **THIS PHOTO IS UPLOADED IN FEED AND FITS PERFECT IN FRAME**
![Capture](https://user-images.githubusercontent.com/17736688/96989241-09d8b800-14eb-11eb-88f9-4c9b0112bad2.PNG)

- **THIS PHOTO IS UPLOADED IN EVENTS AND IS CUT OFF IN FRAME**
![Capture](https://user-images.githubusercontent.com/17736688/96989381-37256600-14eb-11eb-97f3-5d361856671c.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

Photo cut off on Event detail because we're using it as a background cover, so it can't show a full photo with a large height.

Regards.

**Comment by spirogg** [comment]
@harrison05 suggestion to be able to custom width and height in admincp or resize like we do profile image ? would help make site look very much nicer these photos
