### ISSUE TITLE
all settings are set to NO but videos still show in feed from groups and pages ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2953]
# Important

Please follow this template!

----------------------------------------

## What's happened?

...**Display videos which created in Group to the All Videos page at the Video app**
Enable to display all public videos to the both Video page in group detail and All Videos page in Video app. Disable to display videos created by an users to the both Video page in group detail and My Videos page of this user in Video app and nobody can see these videos in Video app but owner.
Notice: This setting will be applied for all types of groups, include secret groups.
**NO**

**Display videos which created in Page to the All Videos page at the Video app**
Enable to display all public videos to the both Video page in page detail and All Videos page in Video app. Disable to display videos created by an users to the both Video page in page detail and My Videos page of this user in Video app and nobody can see these videos in Video app but owner.
**NO**

all settings are set to NO but videos still uploads to feed from groups and pages ?

## Steps to reproduce:
1. set all the above options to NO
2. go to a group and pages and upload a video 
3. then go to feed and you will see the videos, the setting above mean no videos show in video apps and also not in feed. 

## What's expected?
...   no videos uploaded from groups or pages should show in feed when you have the above settings set to NO

**Display videos which created in Group to the All Videos page at the Video app** NO
**Display videos which created in Page to the All Videos page at the Video app** NO
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Microsoft Edge on Windows 10, Firefox on Ubuntu 16.04, ...)

...
all browsers

## Server information
(Example: CentOS 7, php 7.1 apache)

...CentOS 7, php 7.3

## phpFox version
(Example: phpFox 4.6.0)

4.8.1 fresh install...

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/96991652-64bfde80-14ee-11eb-85d6-e3d78e11e3e4.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/96991813-a2bd0280-14ee-11eb-9602-63a66b84c65e.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

It's working correctly. Those settings only hide Videos in Pages/Groups on the listing page of Videos app (All Videos, Friend's Videos...), it not prevent show video on the main feed.

Regards.

**Comment by spirogg** [comment]
Hi @harrison05 I thought this feature request would hide all pages and groups from feed as well

https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/688

that's  why I posted this here. 

I thought that the feature request was already made since approved and the also included the main feed since the feed stays in groups and or pages.. so the main feed would not see the videos or photos 

thanks again for your reply

Spiro

**Comment by spirogg** [comment]
Ok. No worries I just tested if group is closed or private nothing shows in main feed 
Thanks 😀
