### ISSUE TITLE
IM app: big problem - seems like you will manage your messages as the link says **Manage Messages** not delete all messages

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2954]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
**In this section there is not enough emphasis that once you enter your info and press submit all messages will be deleted.**
- seems like you will manage your messages as the link says **Manage Messages**
- this should say **Delete Messages**

THIS IS WHAT WORDING IS NOW

**The administrator can remove all old messages from Node JS server**
To continue. Please enter your admin login details.
Email
`adminEmail`
Password
`adminpassword`
_Warning Make sure you want to remove all old messages because it cannot be undone_

---

**THIS IS WHAT YOU NEED TO ADD  :**

**Warning Administrator, this will delete all messages from Node JS server.**
To delete all messages Now . Please enter your admin login details.
Email
`admin_email@domain.com`
Password
`your_admincp password`

**Warning** By clicking **Submit**. **All MESSAGES WILL BE DELETE**. **Warning** this cannot be undone.
## Steps to reproduce:

---
1. admincp> apps> Instant messages >settings > Mange Messages. 
3. the wording is not enough Warning, because seems like your going to login to another area to manage your message and be able to choose which ones you can delete (manage messages) But this is not managing messages - THIS IS ONLY DELETE ALL MESSAGES.. 

- PLEASE FIX THE WORDING - I thought this was taking me to a page to manage user messages where I can see all messages and then decide if I want to delete or keep 

- ( **I thought I was going to manage my users messages not press submit and deleted all the messages!!!!**)

## What's expected?
... 

- please fix the wording so no one else makes the same mistake - **this could cost an admin a lot of MAD customers and leave the website**

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...all browsers

## Server information
(Example: CentOS 7, php 7.1 apache)
CentOS 7, php 7.2
...

## phpFox version
(Example: phpFox 4.6.0)

...4.8.1

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/97067475-36401300-1583-11eb-8bbc-a9e74bb38dde.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

Thanks for your suggestion. We will improve the wording on this page.

Regards.

**Comment by harrison05** [comment]
We improved it on Instant Messaging v4.8.1

Regards.
