### ISSUE TITLE
IPv6 Lookup issue

### ISSUE THREAD

**Issue by petati94** [PHPfox-Official/phpfox-v4-issues#2960]
# Important

Please follow this template!

----------------------------------------

## What's happened?
If your system supports IPv6 adresses and you try to lookup an address in Users section (click to Users' IP), then the system send an error: "Not a valid IP address."
 

## Steps to reproduce:
1. Enable IPv/ Access on your server
2. Wait until a user log in with IPv6 address
3. Try to lookup the IPv6 in Phpfox

## What's expected?
Lookup the IPv6 as well not just IPv4

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)
CloudLinux 7.8 + WHM 
PHP 7.4.12
Litespeed HTTP SERVER
...

## phpFox version
(Example: phpFox 4.6.0)
PhpFox 4.8.1
...

## Screenshots
![kép](https://user-images.githubusercontent.com/49201524/98154387-fd823100-1ed4-11eb-8b9a-9c8b3a17f8f8.png)
...

**Comment by harrison05** [comment]
Hi @petati94 

We can't reproduce your issue on our site, you can submit a ticket in the client area. Our team will check directly on your site.

Regards.
