### ISSUE TITLE
IM chat - issue if  not friends - you can still chat with a non friend,  if you refresh the browser ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2961]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
first i was friends with someone,
then i unfriended that user. so i still see user in the chat - so I click on user and small chat box opens and says 
"you cannot message this person any longer"

- but then I refresh browser and the message disappears and now I can chat with that user even though I am no longer friends.

## Steps to reproduce:
1. go to a friend (user) and unfriend them.
2. now find the user in your chat and click the user.
3. now a small chat box opens bottom of your screen, says (you no longer can chat)
4. now please **refresh your browser** and now you see the small chat box is available to chat again? ( even though user is not friends)

**this is a bug**

## What's expected?
...
if you are no longer friends with anyone and you set usergroup (messages app to: friends only to chat) you should not be able to chat with that user any longer.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome browser

## Server information
(Example: CentOS 7, php 7.1 apache)

...centOS 7 php 7.4=3

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2 updated from fresh install 4.8.1

## Screenshots
...
**settings set to friends**
![Capture1](https://user-images.githubusercontent.com/17736688/98412330-57056f80-203d-11eb-9b47-045e0c696709.PNG)

![Capture](https://user-images.githubusercontent.com/17736688/98411588-ef025980-203b-11eb-9dd2-46b7e8b8027c.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/98411592-ef9af000-203b-11eb-9b12-b8abb37da012.PNG)
![Capture2](https://user-images.githubusercontent.com/17736688/98411593-ef9af000-203b-11eb-929b-92315463b86a.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/98415670-51128d00-2043-11eb-9287-60be9e519549.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

We will check this issue and inform you later.

Regards.

**Comment by spirogg** [comment]
Happens on your demo as well just FYI. Thanks 

Spiro

**Comment by harrison05** [comment]
We fixed this bug on IM app v4.8.1

Regards.
