### ISSUE TITLE
IM chat - set usergroup to administrator: the option: Restrict message to friends is set to NO for admin - but we still can not send messages

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2962]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
ok so in messages app, we have usergroup settings..
if we set usergroup to administrator:  the option: **Restrict message to friends** is set to NO for admin
- ( so I should be able to message anyone in chat because of this setting, it should not restrict the admin usergroup.)

## Steps to reproduce:
1. go to admincp> apps > messages app
2. usergroups > set dropdown to administrator> then make sure you select Restrict message to friends  NO
3. now save and clear cache.
4. now go to main website and see if you can chat a user not friends with you ( or unfriend a user ) then try to chat? 
it will not let you so this setting is not working in my opinion...

## What's expected?
... if you have the setting **Restrict message to friends** to NO for administrator group, 
- you should be able to message chat any user if they are friends or **no friends**

NOW if I refresh browser in this issue: #2961 i can send message chat

-  **but this is another issue with administrator settings not refresh** **issue**

- **As Administrator I should have admin rights to message chat delete read messages etc from all users**, this is not possible with IM and messages app right now

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome

## Server information
(Example: CentOS 7, php 7.1 apache)

...centOS 7 php 7.3

## phpFox version
(Example: phpFox 4.6.0)

4.8.2 upgrade from fresh install 4.8.1...

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/98412980-7ea90780-203e-11eb-8e92-a5bd99d85ff2.PNG)
![Capture](https://user-images.githubusercontent.com/17736688/98415030-12300780-2042-11eb-9578-9c04f7c1cf88.PNG)

**Comment by harrison05** [comment]
Hi @spirogg 

Setting "Restrict message to friends" is a setting of Message App, so it won't work on Instant Message App.

Regards.

**Comment by spirogg** [comment]
Ok thanks. 

Hopefully chatplus has more advanced features for admin to set I will see soon after getting the Installation on my new server. Thanks @harrison05
