### ISSUE TITLE
Number of comment will be shown on activity feeds

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#2963]
## What's happened?
When scrolling the feed so it has to autoload more items or the button to load more items is clicked, all comments and replies are visible for the new loaded items.

## Steps to reproduce:
1. number of comment will be shown on activity feeds is set to 2 
2. add comments to a feed that has to load on scrolling down
3. scroll down to see all comments visible

## What's expected?
The number of comments should be same as the setting when loading more feed items

## phpFox version
phpFox 4.8.2
comments 4.1.5

**Comment by spirogg** [comment]
I can confirm 
fresh install 4.8.2
comments4.1.5
- the first photo is before the load more button has 8 comments and 4 hidden.

- ![Capture](https://user-images.githubusercontent.com/17736688/98793837-09d32600-23ce-11eb-8907-aac33974fae3.PNG)

- the second photo is after clicking or scrolling past the load more button it shows all 8 comments.


![Capture](https://user-images.githubusercontent.com/17736688/98794366-954cb700-23ce-11eb-86e3-506cda231cc4.PNG)

**Comment by kibcode** [comment]
@harrison05 when can we expect a fix for this? this bug is extremely problematic for large sites. sometimes a post has several hundred comments then the performance is very bad.

**Comment by harrison05** [comment]
Hi @Scheinwelt-Media 

This bug will be fixed and release in the next version of Comment Apps. If you need a hotfix, please contact us via client area.

Regards.

**Comment by spirogg** [comment]
@harrison05 was this fixed in 4.8.3 I didn't test but asking

**Comment by harrison05** [comment]
Hi @spirogg 

This issue was fixed in Comment App version 4.1.6. 

P/s: I don't know why all email notifications from Github were marked as spam in my mailbox. So I can't reply to you soon. Sorry about that.

Regards
