### ISSUE TITLE
pages app: when user comments on cover photo of pages in pages feed the notification link takes you to pages (pagename) photos page

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2965]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... 
I created a page > then I upload avatar and cover photo for page.
then as another user from IOS app commented on the pages cover photo in the feed of pages,
- then when I get notification on main desktop and email notifications the link takes me to pages photos  - instead of the comment in the pages feed.
Also - so if you look in pages > photos  or pages > photos>  albums the avatar or cover photos are not there?

this seems weird

## Steps to reproduce:
1. go to pages and create a new page > then go to page and upload cover photo
2. now login as another user and go to the page you created and in the feed where it shows  **name of page: updated their cover photo**. then write a comment in the feed for the cover photo.
3. now log back in as the user who created the page, and see your notification - then click on notification it takes you to
 pages> (pagename)> photo,  not the feed to reply back in the pages feed.
4. while you see the cover photo > please see the 3 links top left that say pages> (pagename)> photo please click on photo link
5. now you are back in pages under photo> if you look the cover photo not show in photo or albums ?

## What's expected?
... in Pages, when a user comments in the feed section on a cover photo or anything 
the notification the other user gets, should take you to the feed comment not the  pages> (pagename)> photo. section

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...
chrome
## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php7.4

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2 fresh install

## Screenshots
...
![Capture](https://user-images.githubusercontent.com/17736688/99039065-462c9080-254c-11eb-9622-07192f21969b.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/99039075-49278100-254c-11eb-8373-0fa9231c9500.PNG)
![Capture4](https://user-images.githubusercontent.com/17736688/99039265-a6bbcd80-254c-11eb-998f-e8e025603f97.PNG)

# now when you look for your cover photo in albums or photo section of pages there is nothing there ?

![Capture2](https://user-images.githubusercontent.com/17736688/99039138-69574000-254c-11eb-905e-609df551220b.PNG)
![Capture3](https://user-images.githubusercontent.com/17736688/99039147-6bb99a00-254c-11eb-89f2-3b26ba31d7f8.PNG)

**Comment by spirogg** [comment]
so I think this is a bug, 

- first - notification that someone commented on the feed of a photo should take you to the feed comment
- second - there is no album for avatar
- third - there is not album for cover photo

also for groups the cover photo and avatar do not show under albums

**Comment by harrison05** [comment]
Hi @spirogg 

I can confirm those points:

> first - notification that someone commented on the feed of a photo should take you to the feed comment

This is a rule of Photo app, when you act on a photo feed, the notification will link to photo detail.

> second - there is no album for avatar
> third - there is not album for cover photo

Please make sure you enable those settings in Pages/Groups Apps.
![Screen Shot 2020-11-19 at 11 43 08](https://user-images.githubusercontent.com/41947198/99622452-c24b3a80-2a5c-11eb-86a0-9850deab0212.png)

Regards
