### ISSUE TITLE
when we set Thread Display: [user=2]mary[/user] why does it not just use Mary instead, like in IOS app

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2966]
# Important

Please follow this template!

----------------------------------------

## What's happened?

...when we set Thread Display in apps> comments> settings..

`If set to Yes comments will be displayed in a thread format allowing users to reply to specific comments instead of the general item they are commenting on.`

**why does it not use the **username only** but instead say** 

- [user=2]mary[/user]       why does it not just use **Mary** instead 

## Steps to reproduce:
1. turn on thread display in comments
2. then go reply to a user then they reply back to you,  then you reply back: it popup [user=2]mary[/user] 
3. in IOS it adss ONLY the **username** as it should not the brackets etc...   >    [user=2]mary[/user] 

## What's expected?

...we should only see the username of the user that you are replying too just like in the IOS app

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...chrome

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos7 php 7.4

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2 fresh install

## Screenshots
...

- DESKTOP SHOWS BRACKET USERNAME

![Capture](https://user-images.githubusercontent.com/17736688/99046874-015b2680-2559-11eb-9856-0658e5f9635f.PNG)

- 
- IOS SHOWS USERNAME ONLY

![image](https://user-images.githubusercontent.com/17736688/99047170-6c0c6200-2559-11eb-8dfb-94315be6c8b3.png)

**Comment by spirogg** [comment]
#2966

**Comment by harrison05** [comment]
Hi @spirogg 

We haven't supported this feature on the desktop site yet. So, I will mark this topic as a new feature request.

Regards.

**Comment by Bjoern3003** [comment]
I asked for that, 1 Year ago. No update :-(

https://github.com/PHPfox-Official/phpfox-v4-feature-requests/issues/913

**Comment by spirogg** [comment]
@harrison05 can we ask the team to make this a priority. This is in everyone's website. If we have it on mobile we should be able to have on on desktop please. Talk to @phpfoxdev @phpfoxaccount

**Comment by harrison05** [comment]
We're working on this feature. It might available in the next version.

Regards.

**Comment by harrison05** [comment]
Implemented in Comments App 4.1.7

Regards.

**Comment by spirogg** [comment]
@harrison05 i wish I would if explained better. When we post something in feed and we add @michelle (example) it still shows the code instead of name like in comments that you fixed. ?

**Comment by spirogg** [comment]
[user=2]mary[/user]

This still shows when you go to home page Feed 
If I try to add a posts or photo or video and tag a user it still shows [user=2]mary[/user] instead of Mary :(

**Comment by spirogg** [comment]
Comments works great.  It not starting a new post

**Comment by harrison05** [comment]
> [user=2]mary[/user]
> 
> This still shows when you go to home page Feed
> If I try to add a posts or photo or video and tag a user it still shows [user=2]mary[/user] instead of Mary :(

Did you upgrade to phpFox v4.8.4?

**Comment by spirogg** [comment]
@harrison05 yes. Comments work but starting a new post in feed does Not work.

**Comment by harrison05** [comment]
@spirogg It's weird, this improvement is working on our demo site https://v4.phpfox.com/

**Comment by harrison05** [comment]
![Screen Shot 2021-04-14 at 10 56 42](https://user-images.githubusercontent.com/41947198/114652460-1a3a5480-9d10-11eb-9465-b97ee3a9159c.png)

**Comment by spirogg** [comment]
@harrison05 the issue is the template. i created my own template - (example createnew template from material, named it mywebsite

i added my logo and favicon
saved as default template

now i do the upgrade, to 4.8.4

now I remove files no longer needed find missing settings, then language find missing phrases, then rebuild core theme, then clear cache...

now i try to @harrison05  and it does not work, so i check Material template and set as default clear cache and now it works.

- so the issue is the template before the upgrade, it does not change or rebuild to the same as material template
- so does not work
- only the original Material template as default works.
this has to be a bug

**Comment by harrison05** [comment]
Hi @spirogg please follow your post #3008. We will work on it.
