### ISSUE TITLE
Photo status doesn't show up on feed 

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2967]
## What's happened?
Photo status doesn't show up on feed 

## Steps to reproduce:
1. click photo status and add photo
2. select photo album
3. add

## What's expected?
...

## Browsers and Devices tested
Chrome on Windown 10

...

## Server information
CentOS 7, php 7.2 apache

...

## phpFox version phpFox 4.8.2 upgrade

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @prepperz 

We can't reproduce this issue on our side. Which Photos and phpFox version you're using? You can submit a ticket in client area, our team will check it directly on your site.

Regards.
