### ISSUE TITLE
Is there a way to remove the shifting of content to the right from left when one scrolls down

### ISSUE THREAD

**Issue by vinikatyal** [PHPfox-Official/phpfox-v4-issues#2968]
# Important

Please follow this template!

----------------------------------------

## What's happened?

![Screenshot 2020-11-25 at 7 18 12 PM](https://user-images.githubusercontent.com/5568656/100235895-fa69e600-2f52-11eb-98dd-fee74660a358.png)

Content moves left to right once I scroll down

## Steps to reproduce:
1. Go to Profile home page
2. When you scroll down the content shifts to the right
3. 

## What's expected?
Can we remove this behaviour? unable to find the js code for the same

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @vinikatyal 

When you scroll down, contents on left and right will be fixed at the bottom of them. If you disable all blocks on 2 sides, the middle content will extend to those placements. 
We don't meet your issue on our site, please double-check to make sure you don't have any weird content on your site in the left and right block.

Regards.
