### ISSUE TITLE
Pages menu breaks when browser is resized to small window in chrome

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2971]
## What's happened?

Pages menu breaks when browser is resized to small window in chrome

## Steps to reproduce:
1.  resize to smallest window
2. 
3. 

## What's expected?
it's shouldn't break

## Browsers and Devices tested
Chrome on Windown 10

...

## Server information
CentOS 7, php 7.2 apache

...

## phpFox version phpFox 4.8.2 upgrade

...

## Screenshots
...
![Screenshot](https://user-images.githubusercontent.com/19594886/101263090-e1122800-3710-11eb-9f98-9fd1d5213a67.png)

**Comment by harrison05** [comment]
Hi @prepperz 

We will check and fix this bug.

Thanks for your report.
