### ISSUE TITLE
One menu item is always highlighted when Multiple main menus are linked to various pages /groups

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2973]
## What's happened?

One menu item is always highlighted regardless of which item is clicked on.

## Steps to reproduce:
1. Create multiple menu items linked to various pages amd place it on main menu.
2. Click on any of the menus and there will be only one menu item highlighted.
3. 

## What's expected?

The menu that is click is the one that should be highlighted

## Browsers and Devices tested
Chrome on Windown 10

...

## Server information
CentOS 7, php 7.2 apache

...

## phpFox version phpFox 4.8.2 upgrade

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @prepperz 

We will check and fix this issue.

Thanks for your report.
