### ISSUE TITLE
Browse User footer commands block page selector

### ISSUE THREAD

**Issue by karlkunc** [PHPfox-Official/phpfox-v4-issues#2974]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... When you are in admin CP using the mobile browser, not in desktop mode, The commands in the footer to verify ban etc are covering up the ability to switch pages via the page selectors at the bottom of the page. 

## Steps to reproduce:
1. Tried it on Google chrome
2.  Tried it on firefox
3. 

## What's expected?
...The bottom of the page with the page numbers should be above the commands

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...Google chrome, Firefox, Android Samsung S10 plus

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2

First screenshot is Firefox 2nd screenshot is chrome
![Screenshot_20201207-203408_Firefox](https://user-images.githubusercontent.com/74743076/101426976-00a18000-38cc-11eb-9fb2-1971fc750ae5.jpg)

![Screenshot_20201207-203004_Chrome](https://user-images.githubusercontent.com/74743076/101427026-1b73f480-38cc-11eb-9721-2fa98e6ebb7d.jpg)

## Screenshots
...

**Comment by harrison05** [comment]
Hi @karlkunc 

We will check and fix this issue.

Thanks for your report.

**Comment by karlkunc** [comment]
Thankyou
