### ISSUE TITLE
Default photos in themes

### ISSUE THREAD

**Issue by karlkunc** [PHPfox-Official/phpfox-v4-issues#2975]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... Default photos not showing up when uploaded to the material theme default photo section 

## Steps to reproduce:
1. Cleared cache on system and mibile
2. 
3. 

## What's expected?
... Image should show up after upload and a cache clear

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2

## Screenshots
...
  This is more of a request to make additional notes in the phpfox manual. A * should be added to reflect that systems using the asset handling CDN will not be able to view the photo that was uploaded in the view box and the photo will not be active until you Transfer the files to the CDN.

** Actually after further testing. when using asset handling the default cover photo is only showing up in the web version and not the mobile android app.   I did a cash clear on the mobile cash clear on the main system

 rebuilt core theme and did a file clear on mobile and still the default cover photo only shows up on the website version

**Comment by harrison05** [comment]
Hi @karlkunc 

Which "Assets Handling" storage is enabling on your site? If you're using CDN, you can turn it off and check with Local storage, if the issue disappears you can submit a ticker, our team can check and fix it on your site. 

Regards.

**Comment by karlkunc** [comment]
I tried it with it on and with it off. See attached for my off setting.

Karl Kunc u044099
truck 22K-440
4405509792

**Comment by karlkunc** [comment]
Hold on, still testing it.

Karl Kunc u044099
truck 22K-440
4405509792

**Comment by karlkunc** [comment]
After further testing on it. With asset handling turned on with the CDN
that's pointing to Google AWS S3. The default picture shows up on the web
version and the mobile web version but not on the mobile apps, ios or
Android.

Karl Kunc u044099
truck 22K-440
4405509792

**Comment by harrison05** [comment]
Hi @karlkunc 


> After further testing on it. With asset handling turned on with the CDN that's pointing to Google AWS S3. The default picture shows up on the web version and the mobile web version but not on the mobile apps, ios or Android. 

Our mobile app doesn't use default photos uploaded on web because it has special default photos set.

Regards.

**Comment by karlkunc** [comment]
I did not know that. Is that in the app build? I didn't see that is one of
the options when I was getting the app built

Karl Kunc u044099
truck 22K-440
4405509792

**Comment by harrison05** [comment]
> I did not know that. Is that in the app build? I didn't see that is one of the options when I was getting the app built

They're in our API source code (Admin can't change), and we don't include them in our options when built an app for customers. 
But you can request us if you want to change them.

Regards.
