### ISSUE TITLE
Twitter preview not parsing

### ISSUE THREAD

**Issue by karlkunc** [PHPfox-Official/phpfox-v4-issues#2976]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...Not getting a preview of twitter link

## Steps to reproduce:
1. created new api key and secret
2. Set permissions to read, then tested it with read and write, and read write and direct. 
3. 

## What's expected?
...Preview of tweet when link to tweet is posted in the news feed.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...Chrome

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2

## Screenshots
...

**Comment by karlkunc** [comment]
![Untitled](https://user-images.githubusercontent.com/74743076/101995283-dc142200-3c96-11eb-827f-9699c5c1d6c6.jpg)

**Comment by harrison05** [comment]
Hi @karlkunc 

Please make sure your Twitter link doesn't restrict view permission, our system can't get info from a link that doesn't allow to view by guest.

Regards.

**Comment by karlkunc** [comment]
I posted a tweet with no privacy restrictions. I logged out of my account
and just looked at it through a Google search to make sure that it could be
viewed by everybody. I made sure my API keys were correct. Did that 3 times
with copy paste. Instagram doesn't parse either. I also saw someone else on
the community page post about the same issue that it stopped working when
they upgraded to 4.8.2.
Karl Kunc u044099
truck 22K-440
4405509792

**Comment by harrison05** [comment]
Hi @karlkunc 

Did you try to share a Twitter link with our default Twitter API/Secret keys by left empty on those settings? Does it work?

**Comment by karlkunc** [comment]
I did not try that but I will try that.

Karl Kunc u044099
truck 22K-440
4405509792

**Comment by karlkunc** [comment]
When I remove the API key it is just the link that is posted. When I have
the API key installed it just shows the bird and login.

Karl Kunc u044099
truck 22K-440
4405509792

**Comment by karlkunc** [comment]
I tried what you asked

**Comment by harrison05** [comment]
We still don't meet that issue (see my screenshot), you can submit a ticket in client area. Our team will help you check it directly.

![Screen Shot 2020-12-21 at 10 10 27](https://user-images.githubusercontent.com/41947198/102735376-ddb7a700-4374-11eb-912a-5a211e30536a.png)
