### ISSUE TITLE
Email notifications still being sent with email turned off in user settings

### ISSUE THREAD

**Issue by karlkunc** [PHPfox-Official/phpfox-v4-issues#2978]
# Important

Please follow this template!

----------------------------------------

## What's happened? Email notifications still being sent with email turned off
...

## Steps to reproduce:
1. Turned email off for 2000 users
2. Viewed logs at mailgun that emails were still being sent
3. 

## What's expected? No emails
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...all

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.8.2

## Screenshots
...
   I think I have identified it to when a user tags another user in a comment it will trigger an email to the user that was tagged.

**Comment by harrison05** [comment]
HI @karlkunc 

How did you do to turn off Email Notifications for 2000 users? Did you clear cache after do that?

Regards.

**Comment by karlkunc** [comment]
Well I manually did a bunch then I used Fox expert email verified for the others. But before I did that I had my email shut down and still I will receive emails that I've been tagged in a comment. Even when I switch the top notification for email off I will still get an email for the tagged in the comment. And yes I've done many cache clears over the past month.

**Comment by karlkunc** [comment]
![Screenshot_20201220-222155_Chrome](https://user-images.githubusercontent.com/74743076/102736005-d9a66d80-4311-11eb-889c-d386c23eaa59.jpg)
![Screenshot_20201220-222055_Gmail](https://user-images.githubusercontent.com/74743076/102736007-dad79a80-4311-11eb-8f5d-b5ebeaacb65e.jpg)

**Comment by harrison05** [comment]
Hi @karlkunc 

This is a bug with Email notification in case "Tag other in comment". We will check and fix it.

Regards.
