### ISSUE TITLE
Some shared videos from youtube don't get the youtube thumb

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#2979]
## What's happened?
Some of my members add youtube videos into the core video app, and some of these videos don't show the thumb. What I have noticed is that some youtube videos have two thumbs URLs, and others only one.

I will explain it.

Go to this url:
https://www.getyoutubevideothumbnail.com/

And search for the thumb using this youtube video:
https://www.youtube.com/watch?v=T6QpO5Naqmo

What you will notice is that this video doesn't have the thumb for High Resolution / Definition (1280x720)

Only have the thumb for Medium Quality (320x180)

The problem is that your video app only searches for the thumb on the first URL and if don't find it then will not show the thumb.

So, the system should search for the first option that is a high-resolution thumb, and that's what it does now, but if doesn't find it, then it should search for the second option that is a less quality photo.

Regards

**Comment by harrison05** [comment]
Hi @turha71 

We got this issue. It will be fixed and released in the next version of Video App.

Regards.
