### ISSUE TITLE
YouTube preview in status + external links warning

### ISSUE THREAD

**Issue by lethality** [PHPfox-Official/phpfox-v4-issues#2980]
When "External Links Warning" setting is enable, and a YouTube url is posted as a status, clicking the thumbnail which opens the video player dialog **also** displays the 'untrusted link' dialog as per the external link setting. 

## Steps to reproduce:
1. Set "External Links Warning" to 'On'
2. Paste a YouTube video URL as a status
3. Click the thumbnail in the feed

## What's expected?
Clicking that thumbnail shouldn't result in that behaviour as you're not leaving your site, the dialog on-top of the video player looks messy, it should either simply not display, OR possibly make URL's added in the "URL White List" not trigger the warning

## Browsers and Devices tested
Windows 10 - reproduced in Google Chrome 87.0.4280.141 and Opera 73.0.3856.329
...

## Server information
Centos 8 - Plesk
PHP 7.4.14
...

## phpFox version
phpFox 4.8.2

...

## Screenshots
![image](https://user-images.githubusercontent.com/520295/104991596-08019080-5a17-11eb-96a0-2a80374455e7.png)

**Comment by harrison05** [comment]
Hi @lethality

We will check and fix this issue.

Thanks for your report.
