### ISSUE TITLE
using MacBook Pro M1 (with the newest chip) It won't allow me to download any app from admincp? 

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2982]
# Important

Please follow this template!

----------------------------------------

## What's happened?
... I just downloaded latest 4.8.3 of phpfox installed by fresh install on centOS 7 php 7.4 apache MariaDB 10.3

everything was perfect... 

then I wanted to download my apps from admincp>apps>purchase history ( store.phpfox.com )

## Steps to reproduce:
1. so I first logged into admincp> then cleared cache and rebuilt core theme
2. then I went to admincp> apps> purchase history
3. then I found the app I wanted to download> I clicked on the link
4. it opens frame page to the app> then I clicked on download and it spins for .5 seconds and then it has the login form and I need to log back in. enter email and password and then takes me to my user feed page.
really weird. I have tried everything and it always does this. 

then I used my windows 10 pro laptop with chrome browser and I was able to download with no issues any app I have purchased. 

## What's expected?
...
should have no issues to download an app from the store from admincp >apps> purchased history
or admincp> apps > more from MacBook Pro M1 Safari browser

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...Safari Version 14.0.2 (16610.3.7.1.9) on newest MacBook Pro M1

## Server information
(Example: CentOS 7, php 7.1 apache)

...centOS 7 php 7.4 apache mariaDB 10.3

## phpFox version
(Example: phpFox 4.6.0)

...fresh install 4.8.3

## Screenshots
...

**Comment by spirogg** [comment]
PS I opened a ticket on client area,  but also posting here incase someone else might have the answer or the same issue as me - so maybe to get a solution.

PS I tried and set (allow popups) in SAFARI and turned off (enable content blockers) but still the issue persists.

**Comment by spirogg** [comment]
<img width="1327" alt="Screen Shot 2021-01-21 at 2 26 17 AM" src="https://user-images.githubusercontent.com/17736688/105331788-78d0b600-5b99-11eb-9532-edd1cc809109.png">

**Comment by harrison05** [comment]
Hi @spirogg 

We got your ticket and working on it. We will inform you if have any updates.

Regards.

**Comment by spirogg** [comment]
> Hi @spirogg
> 
> We got your ticket and working on it. We will inform you if have any updates.
> 
> Regards.

ok I just wanted to post here as well, so if any other phpfox customer has this issue they know this is getting worked on and will be updated here as well. 

thanks - really weird cause in windows 10 in chrome works no problem..

But I am glad you are working on this issue.. thanks again and HAPPY NEW YEAR to you and your family my friends :)

**Comment by harrison05** [comment]
Hi @spirogg 

Our team inform that issue occurs because of setting from Safari, see my screenshot:

![Screen Shot 2021-01-22 at 15 54 40](https://user-images.githubusercontent.com/41947198/105652782-b6f90d00-5eec-11eb-8ec3-02130e389c9f.png)

If you enable setting "Prevent cross-site tracking" (Apple said about it: "Some websites use third-party content providers. You can stop third-party content providers from tracking you across websites to advertise products and services.") third-party app can't access to data in your local device, so phpFox store can't get login info when you install app and return to your site (because it's working on iframe). We can't bypass this setting on Safari. 

Regards.

**Comment by spirogg** [comment]
@harrison05 ok that worked. I turned off that setting, cleared cache and then tried again and I got it to work. 

after installing, I turned it back on. 
So at least we know if this is issues because apple security I can still upload and update apps from my Mac laptop.
then for safety turn on this feature again after updates...

thanks for helping 

Spiro

**Comment by spirogg** [comment]
@harrison05 maybe in docs you can add this for future reference for any other users who might have this problem please.

thanks again my friend :)

kind regards,
Spiro
