### ISSUE TITLE
Upgrading to v4.8.3 results in Slow pages backend loading issue

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#2984]
## What's happened?
Upgrading to v4.8.3 results in Slow pages backend loading issue

## Steps to reproduce:
1. click to manage any page
2. 
3. 

## What's expected?
Should not be so slow to load

## Browsers and Devices tested
Chrome on Windown 10

...

## Server information
24 core, CentOS 7, php 7.2 apache

...

## phpFox version phpFox 4.8.3 upgrade

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @prepperz 

Can you explain more about this issue? Which page is slowing down? How long to load it? and check your network in case it's slowing.

Regards.

**Comment by prepperz** [comment]
@harrison05 pretty much any any group or pages when going into to manage them. It; takes quite some time before it loads. It seems to do it consistently.

**Comment by spirogg** [comment]
hi at @prepperz I am starting on a fresh install 4.8.3 and created a new test group added a blog to it and commented a few times.. logged out and back in again to test if we go to group click on manage from main group area and after we click on group and I don't see any slowness? not sure why you experience this slowness.. just trying to give my comment on this issue so you know its not on fresh install at least.. I can try adding a page as well and see if that slows things down, but it seems pretty fast on my end

EDIT: created a pages also and did a few comments upload photo etc, but not slow actually really fast when clicking on manage, both  pages and groups ? just fyi my friend

**Comment by prepperz** [comment]
@spirogg ya Fresh installs are not the same as upgrading from previously existing installs and pages.

**Comment by spirogg** [comment]
Yes I figured but did the test just so you would at least k ow it's not an issue on fresh install :) sorry I can't help you further with any testing cause I only did fresh hope you get an answer and solution.

**Comment by harrison05** [comment]
We only found an issue that makes the page loading slowly after clear cache and access to AdminCP - Dashboard. It will be fixed in the next version.

Regards.
