### ISSUE TITLE
Sharing previously uploaded videos

### ISSUE THREAD

**Issue by karlkunc** [PHPfox-Official/phpfox-v4-issues#2986]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When you go to your videos and try to share it 
,unless the video is set to an everyone privacy the share option is not there. 

## Steps to reproduce:
1. Went to my videos that I had uploaded and set the privacy to everyone in the share option was there
2. Changed the privacy to friends only and the share button disappeared.
3. Changed option to friends of friends and the share option was not there.

## What's expected?
... Should be able to share video into feed again regardless of privacy setting.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...4.8.3

## Screenshots
...

**Comment by harrison05** [comment]
Hi @karlkunc 

This is not a bug, you can only share an item (via Share button) with privacy "Everyone"

Regards.
