### ISSUE TITLE
IPV6 Support

### ISSUE THREAD

**Issue by lethality** [PHPfox-Official/phpfox-v4-issues#2988]
## What's happened?
I believe #2960 was an attempt to report this issue but it wasn't explained or understood well by both parties.
The last_ip_address column in phpfox_user is a VARCHAR(15), it's not long enough to store an IPV6 format address. So if you click on a users IP from the AdminCP's, it will display "Not a valid IP address."

## Steps to reproduce:
1. Log into PHPfox using an IPV6 address
2. In PHPfox admincp, on the dashboard (latest admin logins), or via the admincp's user browser, you will see the IP as a link, albeit too short.
3. Verify in database backend, how the IP is stored, mine for example is being truncated to the first 15 characters.

## What's expected?
The issue isn't with the display of the IP, it's the storage. for example, my IP is in the format 2a00:23c4:9a16:2e00:9146:4f50:0000:0000 (obscured last characters), but only "2a00:23c4:9a16:" is in the database.

## Browsers and Devices tested
Opera on Windows 10 PC

## Server information
Centos8, PHP 7-4.14, Apache/nginx

## phpFox version
PHPfox 4.8.3

## Screenshots
![image](https://user-images.githubusercontent.com/520295/106216795-ca95c380-61cb-11eb-9a5c-1e979561694c.png)
![image](https://user-images.githubusercontent.com/520295/106216839-daada300-61cb-11eb-99c1-17f20b402e6c.png)
![image](https://user-images.githubusercontent.com/520295/106216866-eb5e1900-61cb-11eb-9f70-916ee9bbc7fa.png)

**Comment by harrison05** [comment]
Hi @lethality 

We will improve the max length of this field to support store IPv6.

Regards.
