### ISSUE TITLE
Non-Recurring Subscriptions Don't Have Durations

### ISSUE THREAD

**Issue by PENTAGON4** [PHPfox-Official/phpfox-v4-issues#2990]
# Important

Please follow this template!

----------------------------------------

## What's happened?
I set up a subscription but don't want it to auto-renew. The only way to do it is to have no duration. However, I need a duration of a year for the subscription plan so customers can manually pay after one year, one month, etc.

## Steps to reproduce:
1. Create a subscription
2. Need Non-recurring
3. Now I'm unable to designate a duration

## What's expected?

I expect to still have some duration option even when it is non-recurring

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

Edge

## Server information
(Example: CentOS 7, php 7.1 apache)

Cloudlinux 7.9

## phpFox version
(Example: phpFox 4.6.0)
PHPFox 8.3

## Screenshots
...

**Comment by harrison05** [comment]
Hi @PENTAGON4 

We will review your request and inform you if we have any updates.

Regards.

**Comment by PENTAGON4** [comment]
Awesome! Thank you.

**Comment by harrison05** [comment]
We improved Subscription package in v4.6.7. 
From now, you can set a "Renew payment method" for the recurring packages, it can be auto-renew or manual renew or both of them.

Regards.
