### ISSUE TITLE
Recurring Subscriptions and Paypal's Preapproved Payments Not Deleting

### ISSUE THREAD

**Issue by PENTAGON4** [PHPfox-Official/phpfox-v4-issues#2991]
# Important

Please follow this template!

----------------------------------------

## What's happened?

I created a test subscription. Canceling subscription doesn't inactivate subscription in Paypal's preapproved payments. Saw in screenshot, how to delete the preapproved payment but some customers may still not be able to do this without help.

I have a WHMCS site for a hosting company that does mark subscriptions inactive when customer's cancel their service. It doesn't use the API as far as I can see. However, I'm not a programmer.

## Steps to reproduce:
1. User buys a subscription
2. Preapproved Payment is created in user's Paypal account
3. User cancels subscription
4. User gets message to delete preapproved payment in Paypal, too.
5. Users must manually make subscription inactive not to get charged again.

## What's expected?

I thought the Paypal payment gateway on PHPFox would mark preapproved payment INACTIVE in user's Paypal account for them.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

Edge

## Server information
(Example: CentOS 7, php 7.1 apache)

Cloudlinux 7.9

## phpFox version
(Example: phpFox 4.6.0)

phpfox 8.3

## Screenshots
![preapproved payments](https://user-images.githubusercontent.com/4534587/107123264-66b96d80-6851-11eb-980b-afafbd59adb9.png)

**Comment by harrison05** [comment]
Hi @PENTAGON4 

We will check and improve it.

Regards.

**Comment by PENTAGON4** [comment]
Great!

**Comment by harrison05** [comment]
Fixed in Subscriptions v4.6.7
