### ISSUE TITLE
when not allow blog posts from groups or pages to blogs - trending tags still shows in blogs app ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2994]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...

when not allowed group or pages blogs to be posted in regular blog app the tags show in trending and when clicked on nothing shows in blog app. so when we click on a tag it shows nothing. 

can we remove tags from showing in trending blog app when we do not allow group or pages blogs to blogs app.

this way the trending tags will not show up so we can not click on them and get empty blog.

## Steps to reproduce:
1. first go to admincp apps installed blog settings
2. turn OFF 
Display blogs which created in Group to Blogs app
Enable to display all public blogs created in Group to Blogs app. Disable to hide them. NO

Display blogs which created in Page to Blogs app
Enable to display all public blogs created in Page to Blogs app. Disable to hide them. NO
3. save
4. now go to a group or pages and create a blog and add to a category and add tags. then save
5. now go to blogs and you will see trending tags, when you click on the tags nothing shows in the blog.
6. I know because we have settings to NO but tags should not show for blogs posted in groups or pages if we have set NO in settings 

## What's expected?
...
we should see no trending tags

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...Safari Version 14.0.3 (16610.4.3.1.4)

## Server information
(Example: CentOS 7, php 7.1 apache)

...centOS 7. php 7.3 apache

## phpFox version
(Example: phpFox 4.6.0)

...fresh install 4.8.3

## Screenshots
...
<img width="1010" alt="blogs trending" src="https://user-images.githubusercontent.com/17736688/107137496-d7549e80-68d2-11eb-89e6-9155ffb81ea3.png">

**Comment by harrison05** [comment]
Hi @spirogg 

I understood your request. Currently, we save topics of Blogs from Pages/Groups in the same location with topics from Blog App so when the Popular Topics block gets data, it can't ignore them. 
We need to check and find a solution for this case. I will inform you later if have any updates.

Regards.

**Comment by harrison05** [comment]
We improved this in Blogs v4.6.7
