### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 ()asBreadcrumbs.min.css.map

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/phpfox-v4-issues#2995]
# Important

Please follow this template!

----------------------------------------

## What's happened?
...
what is this error for did we forget a file or misspell this ?

Failed to load resource: the server responded with a status of 404 ()
https://www.mydomain.com/PF.Base/theme/frontend/default/style/default/css/asBreadcrumbs.min.css.map

## Steps to reproduce:
1. go to main website https://www.yourdomain.com 
2. now open console and you see the error. 
3. 

## What's expected?
...
should not be this 404 error, this is bad for SEO also with google
## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...Safari

## Server information
(Example: CentOS 7, php 7.1 apache)
centOS 7 PHP7.3 APACHE
...

## phpFox version
(Example: phpFox 4.6.0)

...fresh install 4.8.3

## Screenshots
...

**Comment by harrison05** [comment]
Hi @spirogg 

We will check and fix this issue.

Thanks.
