### ISSUE TITLE
Cannot Transfers Files Back from S3 or Digital Ocean

### ISSUE THREAD

**Issue by PENTAGON4** [PHPfox-Official/phpfox-v4-issues#2996]
# Important

Please follow this template!

----------------------------------------

## What's happened?
I was changing from S3 to Digital Ocean. I didn't realize I could not transfer the S3 files back to my server and then to Digital Ocean.

## Steps to reproduce:
1. Files are stored on S3
2. There's a transfer files button from server to S3 but not back again
3. You can't just copy files to Digital Ocean or you end up with image place holders

## What's expected?
I expect to have a Transfer Files button that transfers files back from S3 or Digital Ocean back to the Server and/or Transfer Files button to transfer S3 directly to Digital Ocean (or S3 Compatible storage etc.) It should also have the ability to store files on server and remotely at the same time (as an option).

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

NA

## Server information
(Example: CentOS 7, php 7.1 apache)

Cloudlinux 7.9

## phpFox version
(Example: phpFox 4.6.0)

PHPFox 8.3

## Screenshots
...

**Comment by harrison05** [comment]
Hi @PENTAGON4 

We don't have any plan to support transfer files from S3 to Digital ocean or download files back to phpFox server. 
You can find tool support migration data from S3 to DO. Example: https://www.digitalocean.com/community/tutorials/how-to-migrate-from-amazon-s3-to-digitalocean-spaces-with-rclone

Regards.
