### ISSUE TITLE
Antispam question doesn't work

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#3001]
## What's happened?
Antispam question doesn't work

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
Chrome on Windown 10

...

## Server information
24 core, CentOS 7, php 7.2 apache

...

## phpFox version phpFox 4.8.3 upgrade

...

## Screenshots
![Screenshot](https://user-images.githubusercontent.com/19594886/110594582-fac96e00-814a-11eb-8f92-44e57de46880.png)

**Comment by harrison05** [comment]
Fixed in phpFox v4.8.4.
