### ISSUE TITLE
Load more to see remaining pages like doesn't work

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#3002]
## What's happened?
The load more options don't work when trying to see the reaiming number of likes for pages.

## Steps to reproduce:
1.  Goto any community pages
2. In the likes section, click on more. (it does nothing)
3. 

## What's expected?
...

## Browsers and Devices tested
Chrome on Windown 10

...

## Server information
24 core, CentOS 7, php 7.2 apache

...

## phpFox version phpFox 4.8.3 upgrade

...

## Screenshots
...

**Comment by harrison05** [comment]
Could you give us more information or step to reproduce this issue? 

Thanks.

**Comment by prepperz** [comment]
@harison. I updated it with instructions

**Comment by harrison05** [comment]
We can't reproduce this issue on our side. 
Tested on our demo site with phpFox v4.8.3 and Pages v4.7.12 (Example: https://v4.phpfox.com/maxfoxer/)
You can create a ticket if it still appears on your site.

Regards.
