### ISSUE TITLE
Hashtags on the website are not working properly

### ISSUE THREAD

**Issue by AvaianoFC1** [PHPfox-Official/phpfox-v4-issues#3004]
**# Important

Please follow this template!**

----------------------------------------

**## What's happened?**
Hashtag is not working properly

**## Steps to reproduce:**
1. Log in to a profile of any web site that has the source code for phpFox. Template: FB Clone.

2. Create a hashtag on that site. For example: #Test
![1](https://user-images.githubusercontent.com/60239369/111852352-5affa300-88f5-11eb-85b3-8f5c07bfac35.png)

3. The website will create a HashTag called "#Test".
![2](https://user-images.githubusercontent.com/60239369/111852366-6a7eec00-88f5-11eb-950b-b4f7a6a195ca.png)

4. Click on the "#Test" link.
![3](https://user-images.githubusercontent.com/60239369/111852382-75d21780-88f5-11eb-9a53-42c3067ccdf3.png)

**## What's expected?**
The website should create or show a new page that contains all of the hashtag's publications, right?
But instead, only the string name appears in the news feed.
In that case, it would appear only written:
"#Test".

**## Browsers and Devices tested**
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
Chrome on Windows 10.
...

**## Server information**
(Example: CentOS 7, php 7.1 apache)
Core Version: | 4.7.7
Operating System: | Linux
-- | --
...

## phpFox version
(Example: phpFox 4.6.0)
PHP Version: | 7.0.28

...

## Screenshots
...
The screenshots were attached on "Steps to Reproduce".

**Comment by harrison05** [comment]
Hi @AvaianoFC1 

After you click on a hashtag, phpFox site will redirect to the new feeds and filter all feeds (contain that hashtag) which you have permission to view. Your reproduce step is the current workflow of hashtags. Example on demo site: https://v4.phpfox.com/hashtag/test/

P/s: With phpFox version 4.8.3, we got a bug when filter hashtags and make them work incorrectly. That bug will be fixed and release in the next version 4.8.4

Regards.

**Comment by harrison05** [comment]
> With phpFox version 4.8.3, we got a bug when filter hashtags and make them work incorrectly. That bug will be fixed and release in the next version 4.8.4

We fixed this bug in phpFox 4.8.4

Regards.

**Comment by AvaianoFC1** [comment]
OK, thank you very much.

You all are Excellent.

Em seg., 12 de abr. de 2021 às 05:00, harrison05 ***@***.***>
escreveu:
