### ISSUE TITLE
Cannot send comments on Smartphone

### ISSUE THREAD

**Issue by petati94** [PHPfox-Official/phpfox-v4-issues#3007]
# Important

Please follow this template!

----------------------------------------

## What's happened?
After the update to 4.8.4 mobile users aren't able to send comments on the contents because sending button missing and Enter press not working.

## Steps to reproduce:
1. Update to phpfox 4.8.4
2. Try to comment on mobile friendly interface
3. 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)
Cloudlinux 7 (cPanel/WHM), PHP7.4, Litespeed HTTP Server 5.4.12
...

## phpFox version
(Example: phpFox 4.6.0)
phpfox 4.8.4
...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @petati94 

Did you upgrade to Comment v4.1.7? 
If you're using CKEditor please upgrade to the newest v4.2.5, old version of it might affect to Comment app.

Regards.
