### ISSUE TITLE
Mobile view main menu

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#3010]
## What's happened?

When opening the main menu on mobile view and clicking a menu item the menu does not hide. The new site loads but the menu still shows up.

## What's expected?

The menu should close after clicking a menu item

## Browsers and Devices tested
Chrome Android
Android Webview
...

## phpFox version
phpFox 4.8.4

## Workaround

I have added some javascript to remove the menu on click until this is fixed

`$('.site-menu-small li a').on('click', function() {
	$('.main-navigation').removeClass('in');
});	`

**Comment by harrison05** [comment]
Hi @Scheinwelt-Media , Do you enable **Bundle JavaScript & CSS** on your site?

**Comment by kibcode** [comment]
@harrison05 it does not matter if its enabled or not

**Comment by spirogg** [comment]
I have the same issue 
Safari browser as well. iPhone 11 Pro Max

**Comment by spirogg** [comment]
@Scheinwelt-Media where did you add the code for the main menu to close after selecting in css in the template editor at the bottom ??

**Comment by spirogg** [comment]
@harrison05 these last few bugs really make for our site to be inoperable for user. #3008 #3009 #3010 #3011 can we get a quick update 4.8.4.a or 4.8.5 these really make it hard for users to use the website on mobile please.

**Comment by harrison05** [comment]
We will check and fix this bug and consider a quick update for Material Template

Regards.

**Comment by kibcode** [comment]
@spirogg i use a helper-app for my own mobile app and added it in the autoload.js. you can also put it into the ready function of the themes javascript.
