### ISSUE TITLE
Multiple profile image upload

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#3011]
## What's happened?

When uploading a profile image and clicking on save it takes very long to finish the action. Some users pressing the button many times so it uploads the same image multiple times.

## Steps to reproduce:
1. Upload or change profile image
2. Click save more than one times

## What's expected?

It should not be possible to upload the same image over and over again

## phpFox version
phpFox 4.8.4

## Workaround

I added a short jquery script to remove the buttons after clicking the save button.

`$('#profile_crop_me input').on('click', function() {
	$('#profile_crop_me input, #profile_crop_me a').remove();
});`

**Comment by harrison05** [comment]
Hi @Scheinwelt-Media 

We will check and fix this bug

Thanks for your report.
