### ISSUE TITLE
Newsletter not sending

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#3012]
## What's happened?

I added a newsletter and after saving the table shows 0/0 and "sending". No mails are sent at all.

Cron is set up and notifications and testmails are sending

## Steps to reproduce:
1. Add new Newsletter with text and all usergroups
2. Start sending

## What's expected?
The table should show the amount of newsletters and send them to the users

## Server information
Linux Debian 10

## phpFox version
phpFox 4.8.4
Latest Newsletter app

**Comment by harrison05** [comment]
Hi @Scheinwelt-Media 

We can't reproduce this issue on our side. Please check and make sure your cronjob is working well or you can submit a ticket in the client area, our team will check it directly on your site.

Regards.

**Comment by kibcode** [comment]
the cron.log shows this: `cron.log.DEBUG: job not found {"job":"core_newsletter_send_email_users"}`

**Comment by harrison05** [comment]
Please submit a ticket in our client area, we will check it on your site.

Regards.
