### ISSUE TITLE
Video fullscreen in feed

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#3013]
## What's happened?

When starting a video in the main feed and clicking the fullscreen button the player goes to fullscreen but the video itself shows very small. When going to the video item and clicking fullscreen it works without issues.

## Steps to reproduce:
1. Upload a new video
2. Start the video in main feed
3. Click the fullscreen button of the video player

## What's expected?
the video should play in fullscreen

## Browsers and Devices tested
Chrome
Firefox
Android webview

## Server information
Linux Debian 10

## phpFox version
phpFox 4.8.4

**Comment by harrison05** [comment]
We will check and fix this bug.

Thanks for your report.
