### ISSUE TITLE
Command Line For task 

### ISSUE THREAD

**Issue by jimmybsilva** [PHPfox-Official/phpfox-v4-issues#3014]
## What's happened?

The current task method of running the cron via the browser is very slow and it always times out because of Cloudflare. 

## What's expected?

I tried to run my own custom cron and it never ran it was supposed to just log a file to show me the cron is working. 
We need to have an option to run the task via cron in the command line. 

...

## phpFox version
(Example: phpFox 4.6.0)
4.8.0
...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @jimmybsilva 

Please follow our guide to set up Cronjob in your site server: https://docs.phpfox.com/display/FOX4MAN/Setup+Cron
