### ISSUE TITLE
4.8.2 - Support Registration with Phone number but not with invite only sites.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#3016]
# Important

Please follow this template!

----------------------------------------

## What's happened?
PhpFox indicates the ability to register with a phone number.

## Steps to reproduce:
1. Turn on invite-only in adminCP
2. 
3. 

## What's expected?
...The invite-only field should be coded the same way the registration field as either email or phone number.  The invite send field should also accept either option as well.  Come on guys, 3.6 - 4 billion smart phones in use today and mobile web traffic accounts for 52.6 percent of global traffic...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Microsoft Edge on Windows 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by harrison05** [comment]
Hi @PhpFoxJohnJr

Do you want us to allow send invitations via Phone number? See my screenshot

![Screen Shot 2021-05-24 at 09 25 33](https://user-images.githubusercontent.com/41947198/119288359-95c5e480-bc72-11eb-9072-c06c3bdd6f2a.png)

Regards.

**Comment by PhpFoxJohnJr** [comment]
Yes, It should use the same phone field and full_phone_number field in the User table.  I tried the registration for the first time (honestly did try it before because I received no answer on the forum on how it worked) and it worked pretty damn well.  I know now, you are able to go into your account settings now and add your email and can log in either way which is awesome!

The scenario I see is two people meet somewhere away from a computer and one person can send an invite to that person's phone and that person can accept it right there on their phone.  This gives the opportunity for the invitee to explain some of the features and what to do without going back to either a pc because some people don't have their email set up on their phone or even like using email like my kids...who only text everything and never check their email.

I think the verification was also sent through the phone which was also a good idea as well.

The one thing I add for emails because I wanted to reduce the temptation to spam it but adding a limit.  I added to the file:
PF.Base/module/invite/include/component/controller/index.class.php on line 26.

Add one more than you want. so 11 will let 10 emails go through (I didn't notify the users so the spammers will think it went through because no one should be sending that many invites for my site at once.

$aMails = explode(',', $aVals['emails'], 11);

I don't know if this is even possible with phone numbers.

Thanks for all you do!

**Comment by harrison05** [comment]
We will check and improve this. It might available in the next version of phpFox.

Thanks for your request.

**Comment by PhpFoxJohnJr** [comment]
That would be very unexpected.  I appreciate all the work you guys and girls do, and I try to help out when I can :)

**Comment by harrison05** [comment]
We improved this feature in phpFox 4.8.6

Regards.

**Comment by PhpFoxJohnJr** [comment]
Thank you very much!!!  I really do appreciate all your work.

**Comment by PhpFoxJohnJr** [comment]
Can you double-check if this still works in 4.8.9.  I attempted to invite through SMS and it did send the text and directed the user to the website but it said "Your invitation has expired or it was not valid"  I tried on two different phones.  My site is an invite-only site.
