### ISSUE TITLE
Already created Music Albums in Groups are not available in drop down box in the "to share a song" entry form.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#3017]
# Important

Please follow this template!

----------------------------------------

## What's happened?
Created a new group.
Added an Album first.
Then went back to the Group Main page.
Click on the Music menu.
The Dropdown menu gives two option (share song or add album)
Click on Share Song.
The entry form shows a dropdown box for Album selection.
When click the only option is Select an Album.

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
To see the Album I already entered. 

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

************IMPORTANT************PLEASE READ**************************
the above line on your default form here has Microsoft and Windows spelled incorrectly :)

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

4.8.5

## Screenshots
...

**Comment by harrison05** [comment]
Hi @PhpFoxJohnJr 

Did you add a Music album to Group? When you share songs in a group, we only load albums that belonging to it.

Regards.

**Comment by PhpFoxJohnJr** [comment]
Sorry I missed adding that detail above.  Let me redo my process

(The reason why I created the Album first was that when I went to share a song there is a dropdown box that says "Select an album".  But I haven't created an Album yet so that makes sense.  So I made an Album, listed in the new steps below.  What it comes down to is the dropdown box in "Share a Song" form that says "Select an album" can not be used because you can't populate it .  I tried Groups and Pages.

I created a new Group and now tried it on Pages.
Added an Album first (because you need an album to add songs to it.
Then went back to the Group Main page and it does  show an album with zero songs (that is perfect).
Click on the Music menu.
The Dropdown menu gives two option (share song or add album)
Click on Share Song.
The entry form shows a dropdown box for Album selection (this is also correct).
When I click the option is "Select an Album" to add this song, the already created album is not there.

Update:  I created a new album this time, but before I left the "Add an Album" process I added a song to that album.  My thinking was maybe an Album needed at least one song before you can add additional songs to that album using the menu called "Share Song".  So now I have an album with a song and then I tried "Share a Song" and the dropdown box still didn't work.

So I looked there is no way to populate that dropdown box in "Share a Song" entry form...so it is a bug trust me :)

**Comment by harrison05** [comment]
Hi @PhpFoxJohnJr 

I tried to reproduce issue with your step, but it still doesn't occurs. You can see my screenshot (tested on our Demo site)

I created a new Album in Group without upload any songs into it

![Screen Shot 2021-06-02 at 09 57 40](https://user-images.githubusercontent.com/41947198/120418914-96a1f900-c38b-11eb-856d-0033232861d3.png)

Then I select "Share Song" in Group Detail > Music

![Screen Shot 2021-06-02 at 09 57 08](https://user-images.githubusercontent.com/41947198/120418963-ade0e680-c38b-11eb-9fa7-88dbc2ab3f98.png)

As you can see, that album appears on the select box. 
So I can't confirm this is a bug.

**Comment by PhpFoxJohnJr** [comment]
Your pictures show it works.  I can't seem to get into the demo and it is late will try tomorrow.  I did test it on a new install of 4.8.5.

**Comment by PhpFoxJohnJr** [comment]
Just an update.  I think I narrowed it down to YouNet Business Directory App.  When I shut it off it then works correctly.  I went to their demo site for the business directory and the dropdown box didn't work....really weird if you ask me.  I sent a ticket to YouNet and will update if they find the issue or they figure out that I was wrong :)

**Comment by PhpFoxJohnJr** [comment]
YouNet indicated they will fix this issue in the next update.

**Comment by PhpFoxJohnJr** [comment]
The issue has been fixed with the new update for Business Directory 4.02p7 from YouNetCo on 7/22/2021.
