### ISSUE TITLE
Can't create an HTML AD

### ISSUE THREAD

**Issue by turha71** [PHPfox-Official/phpfox-v4-issues#3020]
## What's happened?
When I try to create an HTML AD the layout for images is still there. It doesn't change to the HTML layout.

## Steps to reproduce:
1. Go to ads and click on "add new ad"
2. The default layout is for images.
3. Click on HTML and the default layout for images doesn't change, so I can't add the html.

## phpFox version
4.8.5

**Comment by harrison05** [comment]
Hi @turha71 

I can't reproduce this issue on our site. Do you enable any "Ad Block" extension on your browser? If yes, please disable it, because that extension will block resources from our Ads app and make it works improperly.

Regards.

**Comment by turha71** [comment]
Sorry, you are right. After disabling ad-block it's working.

But still, on the text field, I can't add the AdSense code. Part of the code disappears. How to add Adsense code?

Regards

**Comment by harrison05** [comment]
I don't think you can add AdSense code to HTML Ads. If you want to use it, you should add it in an HTML Block (AdminCP > Appearance > Blocks) 

Regards.
