### ISSUE TITLE
Naresh, JohnJr and Eric had error 500 all over with php9 with 4.8.6

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [PHPfox-Official/phpfox-v4-issues#3021]
# Important

Please follow this template!

----------------------------------------

## What's happened?
https://community.phpfox.com/forum/thread/58599/issue-with-php-8/

## Steps to reproduce:
1. 
2. 
3. 

## What's expected?
...

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)

...

## Server information
(Example: CentOS 7, php 7.1 apache)

...

## phpFox version
(Example: phpFox 4.6.0)

...

## Screenshots
...

**Comment by PhpFoxJohnJr** [comment]
You can delete this after you read it....just wanted you to know ASAP.

**Comment by harrison05** [comment]
Hi @PhpFoxJohnJr 

If your site shows a 500 error, you can check main.log (AdminCP > Assets > Log Handling) to see what is that error.
I think your site has one or more apps that don't support PHP 8.0 or don't compatible with phpFox 4.8.6.

Regards.

**Comment by PhpFoxJohnJr** [comment]
I bet that is what it was.  Sorry for the drama :)  
hope you have a great day!!!!
You can remove this or can I?

**Comment by harrison05** [comment]
I will close this topic.

Regards.
