### ISSUE TITLE
Profile pictures upload path

### ISSUE THREAD

**Issue by raulw** [PHPfox-Official/phpfox-v4-issues#3026]
**Observation:**
Until version... at least 4.7.8 and how many version afer, I don't know (because I only notice now, at 4.8.7) the structure of folders used for profile picture uploads was in this format:

_/file/pic/user/year/month/pic.xxx_

now is:

_/file/pic/user/pic.xxx_

_so practicaly, no more year and month._

**Problem:**
The new structure format, in my opinion and in a logical thinking... it's **not good at all** and can cause problems on long term. 

**Why?** 
 Because uploading all the profile pictures in the same folder, especially on big communities, makes that folder huge (many file in single folder). For example, on my server, that folder, already has more than 65.000 photos and any FTP/SFTP client barely opens/list it.

Others:
I've saw that timeline photos and other are still in old style (year/month), which is good.
As far as I can see, the old format stopped for me in 06.2021 (the last folder) but I don't know which version I had then (not to old because I usually update when a new version appears). I mentioned an older version above, because that version I had on a test/development server (which was not updated from initial install) and I can confirm it was that way.

**Comment by raulw** [comment]
Printscreen from your demo (https://v4.phpfox.com/phpfoxdemo)

<img width="687" alt="Screenshot 2021-10-25 at 14 12 41" src="https://user-images.githubusercontent.com/3592095/138686977-d05cf927-8c55-4422-b861-0036f499b5c8.png">

As I said, only the profile picture, any other pictures, works like it should.

**Comment by harrison05** [comment]
Hi @raulw 

We will improve it in the next version. Thanks for your report.

Regards.

**Comment by raulw** [comment]
@harrison05 thank you very much for the answer and considering this.
