### ISSUE TITLE
Comment reply not working correctly

### ISSUE THREAD

**Issue by kibcode** [PHPfox-Official/phpfox-v4-issues#3028]
# Important

Please follow this template!

----------------------------------------

## What's happened?
When comment reply is enabled and a users replies to a reply the script adds the users name again and again.

## Steps to reproduce:
1. Add a comment
2. Reply to the comment
3. Reply to the reply

## What's expected?
The username should show up one time.

## Browsers and Devices tested
Chrome mobile, Chromium webview, Firefox mobile

...

## phpFox version
phpFox 4.8.8
Comments 4.1.10

**Comment by harrison05** [comment]
Hi @Kibcode 

We can't reproduce this issue, please provide us more information about it, any screenshot or screen record will helpful.

Regards.

**Comment by kibcode** [comment]
i heard this from clients and was able to reproduce it on a mobile device. seems like its an issue on mobile only.

**Comment by harrison05** [comment]
We also check on the mobile app, but still can't reproduce it. Username only shows up one time if you're replying to another user's reply.

**Comment by kibcode** [comment]
will try to record a video for you. the issue is therei saw it but i am not sure yet how to reproduce.
