### ISSUE TITLE
Question: How to edit the dropdown menu and also make it scrollable

### ISSUE THREAD

**Issue by Mikekay262** [PHPfox-Official/phpfox-v4-issues#3031]
I recently added a number of third-party apps to my site which increased the number of items in the dropdown menu for account settings.

I expect that as the number of items on the list increases the menu becomes scrollable but this does not happen. The menu is fixed and displays as seen in the attached screenshot and so users are unable to log out of their accounts since the logout option is the last item on the list. I also expect that there's an option to edit the menu list to add or remove items but I only found the menu settings option in AdminCp seems to only apply to the main menu and not the dropdown menus as well.
...

 I tested it on devices with different screen sizes(including laptops) and the problem only occurs on devices with smaller screens irrespective of the browser used

...

I  use  CentOS 7, php 8, apache Server

...
phpFox version 4.8.8

![Screenshot 2021-12-14 8 01 14 PM](https://user-images.githubusercontent.com/73533545/146074640-0cd67f80-7197-457d-9166-3d03fa26ce74.png)

Any ideas on how to resolve this, please?

**Comment by harrison05** [comment]
Hi @Mikekay262 

**I think this is an issue in Material Template, our team will check and improve it.**

By the way, if you want a quick fix to your site, I have a temporary solution, please follow my step:
1. Access to AdminCP > Appearance > Themes
2. Select your default themes. In the Manage theme page, select menu "CSS" and add below CSS code:
`#hd-cof ul.dropdown-menu {
    max-height: 400px;
    overflow: auto;
}`
3. Finally, save your changes.

Regards.
