### ISSUE TITLE
Ban filters can be duplicated

### ISSUE THREAD

**Issue by daniol** [PHPfox-Official/phpfox-v4-issues#3034]
## What's happened?
If you enter a filter twice, it will be created duplicated instead of showing an error or ignoring it.

## Steps to reproduce:
1. Go to the IP block filter on the admin settings
2. Add a new IP address or IP range to the ban list
3. Add the same IP again: no error occurs, duplicated filters are created

## What's expected?
Either an error should be displayed or the duplicated entry should be ignored

## phpFox version
phpFox 4.8.8

## Notices
It happens with the IP and email address filter, probably also with the other filters

**Comment by harrison05** [comment]
Hi @daniol ,

We will check this issue.

Thanks for your report.
