### ISSUE TITLE
Forum 500 error - version 4.6.6 - (PhpFox 4.8.9)

### ISSUE THREAD

**Issue by raulw** [PHPfox-Official/phpfox-v4-issues#3035]
**What's happened?**

After I've updated the forum to the latest version 4.6.6 it gives me 500 error

**Steps to reproduce:**

1.  Use the latest phpfox 4.8.9
2. Update to the latest forum 4.6.6
3. Groups the latest version 4.7.14 (deactivate it)

**What's expected?**

`[256] Calling a Service from an invalid Module. Make sure the module is valid or set to active. (groups::groups) (/home/myfolder/public_html/PF.Base/include/library/phpfox/error/error.class.php) [96] Error Code: 442856 Stack trace: #0 /home/myfolder/public_html/PF.Base/include/library/phpfox/error/error.class.php(96): trigger_error('Calling a Service from an invali...', 256) #1 /home/myfolder/public_html/PF.Base/include/library/phpfox/module/module.class.php(990): Phpfox_Error::trigger('Calling a Service from an invali...', 256) #2 /home/myfolder/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1177): Phpfox_Module->getService('groups', ) #3 /home/myfolder/public_html/PF.Site/Apps/core-forums/Service/Thread/Thread.php(755): Phpfox::getService('groups') #4 /home/myfolder/public_html/PF.Site/Apps/core-forums/Service/Forum.php(970): Apps\Core_Forums\Service\Thread\Thread->getMyThreadTotal() #5 /home/myfolder/public_html/PF.Site/Apps/core-forums/Controller/ForumController.php(448): Apps\Core_Forums\Service\Forum->buildMenu() #6 /home/myfolder/public_html/PF.Base/include/library/phpfox/module/module.class.php(1168): Apps\Core_Forums\Controller\ForumController->process() #7 /home/myfolder/public_html/PF.Base/include/library/phpfox/module/module.class.php(566): Phpfox_Module->getComponent('Apps\Core_Forums\Controller\Foru...', Array, 'controller') #8 /home/myfolder/public_html/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(2038): Phpfox_Module->getController() #9 /home/myfolder/public_html/PF.Base/start.php(636): Phpfox::run() #10 /home/myfolder/public_html/index.php(5): require('/home/myfolder/public_html/PF.Base...') #11 {main}`

**What I have tried:**

1. I don't use groups, but I have activated it and the error is still there. 
2. I had changed the config in groups (under integration) to not integrate with forum but the error is still there. 
3. I had uninstall and re-install gropus, the error is still there.
4. Of course I have tried all the rest: rebuild core theme, clear cache, find missing settings and so on (after every change)

**Server information**

Centos, Php 7.4.28

**phpFox version**

4.8.9

**Comment by raulw** [comment]
I've also tried on dev. environment, same error (but only if groups is deactivated):

`[256] Calling a Service from an invalid Module. Make sure the module is valid or set to active. (groups::groups) (/home/myfolder/public_html/development/PF.Base/include/library/phpfox/error/error.class.php) [96]
Error Code: 60da9a
Stack trace:
#0 /home/myfolder/public_html/development/PF.Base/include/library/phpfox/error/error.class.php(96): trigger_error('Calling a Service from an invali...', 256)
#1 /home/myfolder/public_html/development/PF.Base/include/library/phpfox/module/module.class.php(990): Phpfox_Error::trigger('Calling a Service from an invali...', 256)
#2 /home/myfolder/public_html/development/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(1169): Phpfox_Module->getService('groups', )
#3 /home/myfolder/public_html/development/PF.Site/Apps/core-forums/Service/Thread/Thread.php(755): Phpfox::getService('groups')
#4 /home/myfolder/public_html/development/PF.Site/Apps/core-forums/Service/Forum.php(970): Apps\Core_Forums\Service\Thread\Thread->getMyThreadTotal()
#5 /home/myfolder/public_html/development/PF.Site/Apps/core-forums/Controller/IndexController.php(109): Apps\Core_Forums\Service\Forum->buildMenu()
#6 /home/myfolder/public_html/development/PF.Base/include/library/phpfox/module/module.class.php(1168): Apps\Core_Forums\Controller\IndexController->process()
#7 /home/myfolder/public_html/development/PF.Base/include/library/phpfox/module/module.class.php(566): Phpfox_Module->getComponent('Apps\Core_Forums\Controller\Inde...', Array, 'controller')
#8 /home/myfolder/public_html/development/PF.Base/include/library/phpfox/phpfox/phpfox.class.php(2024): Phpfox_Module->getController()
#9 /home/myfolder/public_html/development/PF.Base/start.php(635): Phpfox::run()
#10 /home/myfolder/public_html/development/index.php(5): require('/home/myfolder/public_html/develop...')
#11 {main}`

 Dev. environment is clean, no changes to anything, "stock apps".

**Comment by raulw** [comment]
Tried on clean install, with same scenario, forum latest version and groups deactivated, the error is there. If the groups are activated, everything is fine. The problem is, I don't want groups on me site, so, any suggestion? Fix? (currently I rolled back to the previous version of forum)

**Comment by harrison05** [comment]
Hi @raulw,

I can confirm this is a bug from Forum App. It only occurs if your site doesn't enable the Groups or Pages app.
We will check and fix this issue in the next version.

Regards.

**Comment by raulw** [comment]
> Hi @raulw,
> 
> I can confirm this is a bug from Forum App. It only occurs if your site doesn't enable the Groups or Pages app. We will check and fix this issue in the next version.
> 
> Regards.

Thanks for confirming this. Yes, I have notice that you need to have both active (Groups and Pages) in order to work... which, in my case, I don't use any of them. Until the fix, which I hope to be as soon as possible, I have overwrite the files with the old version files.

**Comment by Unite2Me** [comment]
i can confirm this happen with 4.8.10 tioo...

**Comment by raulw** [comment]
Yes, thank you for confirming it. **The big** problem is that it's **4 months later** and nobody cares about this bug. Just unbelievable how unreliable PHPFox have became.

**Comment by raulw** [comment]
Next month is ONE YEAR since I reported this bug and the bug is still there. This says much about PHPFox and now... they have pretensions to pay for upgrade to V5. This bug will not be fixed never... because they don't care about it, they only care about how to get more money from existing customers by force them to upgrade to V5. Shame!

**Comment by raulw** [comment]
Anyone considering PHPFox, keep away, this is an **abandoned project**.

**Comment by harrison05** [comment]
I would like to announce that issue was fixed in Forum app v4.6.7.

Thank you for your patience and understanding.
