### ISSUE TITLE
Flavor Bootstrap - Login screen missing password field - 

### ISSUE THREAD

**Issue by jimmybsilva** [PHPfox-Official/phpfox-v4-issues#3036]
## What's happened?
When you upgrade to phpfox 4.8.9 the login does not show the password field fully. It is so small that you can't see what you typed in.

## Steps to reproduce:
1.  Go to phpfox demo site 
2. https://v4.phpfox.com/?force-flavor=bootstrap  - Must use flavor version 
3. look at the login box and its missing part of the password field. 

## What's expected?
The password field should be expanded and you should be able to see the whole password field

## Browsers and Devices tested
Chrome Version 100.0.4896.88 (Official Build) (x86_64)
Also Iphone 13 pro max safari 

## phpFox version
phpfox 4.8.9

...

## Screenshots
...
![Screen Shot 2022-04-26 at 5 33 07 PM](https://user-images.githubusercontent.com/35279981/165846036-f90af0a3-d11f-4426-9ef3-ab179a5ca423.png)

**Comment by jimmybsilva** [comment]
Today I just noticed it got fixed on the demo how did you guys fix it?

**Comment by harrison05** [comment]
Hi @jimmybsilva 

It's a bug of phpFox, we will officially fix it in the next version 4.8.10.

Regards.
