### ISSUE TITLE
Invalid email verification

### ISSUE THREAD

**Issue by prepperz** [PHPfox-Official/phpfox-v4-issues#3040]
## What's happened?
New user registration email verify link says invalid, but user is already registered

## Browsers and Devices tested
chrome
...

## Server information
CentOS 7, php 7.2.24 apache

...

## phpFox version 4.8.10)

...

## Screenshots
![image](https://user-images.githubusercontent.com/19594886/190190938-bb6611a2-0ce6-437e-8bb4-73e9b1ad5590.png)

**Comment by harrison05** [comment]
Hi @prepperz 

We can't reproduce this issue on our side. I recommend you submit a ticket in client area and our supporter will help you check the issue directly on your site.

Regards.
