### ISSUE TITLE
Blog User profile Picture is Extra large on pc

### ISSUE THREAD

**Issue by Steppinbig** [PHPfox-Official/phpfox-v4-issues#3041]
# Important

Please follow this template!

----------------------------------------

## What's happened?
I embeded a youtube video in blog and posted the blog But the User Profile picture shows up extra large on PC, phone and you have to scroll down past the profile picture to see the actual posting of the blog. But it looks fine on phpfox app.

## Steps to reproduce:
1. embed a youtube video in a blog
2. fill in title and select category
3. click publish

## What's expected?
Small regular size profile picture where you don't have to scroll down to get to the blog.

## Browsers and Devices tested
(Example: Chrome on iPhone X, Safari on Macbook, Miscrosoft Edge on Windown 10, Firefox on Ubuntu 16.04, ...)
Brave, Firefox, and Chrome
...

## Server information
(Example: CentOS 7, php 7.1 apache)
Linux 4.19.150-76.ELK.el6.x86_64, CloudLinux v6.10.0, PHP Version 7.4.29

...

## phpFox version
(Example: phpFox 4.6.0)
phpfox 4.8.10

...

## Screenshots
...
![New Project](https://user-images.githubusercontent.com/113927334/191067992-09ace727-8b89-4679-aeeb-67a2f2e04ec6.jpg)

**Comment by harrison05** [comment]
Hi @Steppinbig 

Did you try to "Rebuild Core Theme" in AdminCP > Maintenance? If you did that but issue still occurs, you should submit a ticket in client area and our supporter will help you check the issue directly on your site.

Regards.
